/-
Based on Prove2Me node HorizontalPadicL.SeededHorizontalPrimeSystemV3.orderExponent_le_exponent_v2
(037c8a4e-0925-4a6c-a910-eaa2f7801ddf) by davidloeffler (2026-09-25).

Proof based on Prove2Me submission 55c68323-5c7e-4b2b-ac9c-6ddec2629132
by davidloeffler (2026-09-25); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_PrimePowerPropagationV2
public import Definitions.KN.Def_KN_InverseSeedConventionV2

/-!
# Orderly congruences bound local p-power exponents (inverse-seed convention)

Theorem statement: `HorizontalPadicL.SeededHorizontalPrimeSystemV3.orderExponent_le_exponent_v2`
(`037c8a4e-0925-4a6c-a910-eaa2f7801ddf`), by davidloeffler, 2026-09-25.

Proof: submission `55c68323-5c7e-4b2b-ac9c-6ddec2629132`, by davidloeffler, 2026-09-25 (ACCEPTED);
locally adapted.

Congruence modulo p^m implies that the maximal local p-power quotient
has exponent at least m.

This replacement uses the inverse-seed convention matching MTT criticalLValue: the orderly-prime
expression and Euler augmentation are eta(l)*a_l - eta(l)^2 - epsilon(l). The critical values and
seed hypotheses themselves retain the character eta. It supersedes
`HorizontalPadicL.SeededHorizontalPrimeSystemV2.orderExponent_le_exponent`.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section
open scoped BigOperators

namespace HorizontalPadicL

theorem _root_.solution
    {N k p B : ℕ} {ι : MTT.Qbar →+* ℂ} [Fact p.Prime]
    {ιp : MTT.Qbar →+* ℂ_[p]} {f : MTT.Eigenform N k ι}
    {η : DirichletCharacterWithLevel}
    (L : SeededHorizontalPrimeSystemV3 p ιp f η B) :
    ∀ n, L.orderExponent ≤ L.exponent n := by
  intro n
  unfold SeededHorizontalPrimeSystemV3.exponent
  rw [← Nat.pow_dvd_iff_le_padicValNat (Fact.out : p.Prime).ne_one]
  exact ((L.primeAt_orderly n).2.1.symm).dvd'
  exact Nat.sub_ne_zero_iff_lt.mpr (L.primeAt_prime n).one_lt

end HorizontalPadicL
end

end privateSection

public section publicSection

noncomputable section
open scoped BigOperators

namespace HorizontalPadicL

/-- Congruence modulo p^m implies that the maximal local p-power quotient
has exponent at least m. -/
theorem SeededHorizontalPrimeSystemV3.orderExponent_le_exponent_v2
    {N k p B : ℕ} {ι : MTT.Qbar →+* ℂ} [Fact p.Prime]
    {ιp : MTT.Qbar →+* ℂ_[p]} {f : MTT.Eigenform N k ι}
    {η : DirichletCharacterWithLevel}
    (L : SeededHorizontalPrimeSystemV3 p ιp f η B) :
    ∀ n, L.orderExponent ≤ L.exponent n :=
  solution L

end HorizontalPadicL
end

end publicSection
