/-
Based on Prove2Me node MTT.Eigenform.nebentype_mem_ringOfIntegers
(c936cb93-837c-4aa5-b2ea-4546b6f84fa1) by davidloeffler (2026-09-20).

Proof based on Prove2Me submission 6182b489-3dd4-488d-98b6-8454b83b4861
by davidloeffler (2026-09-20); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_MTT_EigenformCoefficientField
public import Mathlib.RingTheory.IntegralClosure.Algebra.Basic

import Mathlib.Algebra.Algebra.Hom.Rat
import Mathlib.NumberTheory.MulChar.Lemmas
import Mathlib.RingTheory.RootsOfUnity.Minpoly

/-!
# Nebentype values lie in the ring of integers of the coefficient field

Theorem statement: `MTT.Eigenform.nebentype_mem_ringOfIntegers`
(`c936cb93-837c-4aa5-b2ea-4546b6f84fa1`), by davidloeffler, 2026-09-20.

Proof: submission `6182b489-3dd4-488d-98b6-8454b83b4861`, by davidloeffler, 2026-09-20 (ACCEPTED);
locally adapted.

Let $f$ be an MTT eigenform with coefficient field $K_f$ and nebentype $\varepsilon_f$. Every value
of the nebentype, viewed as an element of $K_f$, lies in its ring of integers:

$$
\varepsilon_f(a)\in\mathcal O_{K_f}
\qquad(a\in\mathbf Z/N\mathbf Z).
$$

Nonzero nebentype values are roots of unity; the possible zero values are integral as well.

## Explanation of the source proof

If $\varepsilon_f(a)=0$, integrality is immediate. Otherwise $a$ is a unit modulo $N$, and the value
of the multiplicative character is a root of unity of order dividing the finite group $(\mathbf
Z/N\mathbf Z)^\times$. Hence it satisfies the monic polynomial $X^d-1$. Integrality descends through
the injective inclusion $K_f\hookrightarrow\overline{\mathbf Q}$, giving membership in $\mathcal
O_{K_f}$. The uploaded Lean theorem is deliberately at `_root_.solution`.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

theorem solution
    {N k : ℕ} {ι : MTT.Qbar →+* ℂ} (f : MTT.Eigenform N k ι)
    (a : ZMod N) :
    (⟨f.epsilon a, f.nebentype_mem_coefficientField a⟩ : f.coefficientField) ∈
      integralClosure ℤ f.coefficientField := by
  rw [mem_integralClosure_iff]
  let inclQ : f.coefficientField →ₐ[ℚ] MTT.Qbar :=
    f.coefficientField.subtype.toRatAlgHom
  let inclZ : f.coefficientField →ₐ[ℤ] MTT.Qbar := inclQ.restrictScalars ℤ
  apply (isIntegral_algHom_iff inclZ inclZ.injective).mp
  change IsIntegral ℤ (f.epsilon a)
  by_cases ha : f.epsilon a = 0
  · simpa [ha] using (isIntegral_zero : IsIntegral ℤ (0 : MTT.Qbar))
  · have hu : IsUnit a := MulChar.apply_ne_zero_iff.mp ha
    let := Fintype.ofFinite (ZMod N)ˣ
    let d := Fintype.card (ZMod N)ˣ
    have hd : 0 < d := Fintype.card_pos
    have hroot := f.epsilon.apply_mem_rootsOfUnity hu.unit
    have hpow : (f.epsilon a) ^ d = 1 := by
      simpa [IsUnit.unit_spec hu] using (mem_rootsOfUnity' d _).mp hroot
    refine ⟨Polynomial.X ^ d - 1,
      Polynomial.monic_X_pow_sub_C 1 (Nat.ne_of_gt hd), ?_⟩
    simp [hpow]
end

end privateSection

public section publicSection

noncomputable section

/-- Every nebentype value, regarded as an element of the coefficient field,
belongs to its ring of integers. -/
theorem MTT.Eigenform.nebentype_mem_ringOfIntegers
    {N k : ℕ} {ι : MTT.Qbar →+* ℂ} (f : MTT.Eigenform N k ι)
    (a : ZMod N) :
    (⟨f.epsilon a, f.nebentype_mem_coefficientField a⟩ : f.coefficientField) ∈
      integralClosure ℤ f.coefficientField := _root_.solution f a
end

end publicSection
