/-
Based on Prove2Me node HorizontalPadicL.positiveDensityOrderlySet_to_primeSystem_inverseSeed_v2
(41fd2636-d820-49e2-8385-68716ee4538e) by davidloeffler (2026-09-25).

Proof based on Prove2Me submission f07ba611-0aa4-44e3-9ef6-8aa5e42d91fd
by davidloeffler (2026-09-25); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_SeededPrimeGaloisDataV2
public import Definitions.KN.Def_KN_InverseSeedConventionV2

import Theorems.KN.Thm_HorizontalPadicL_positiveDensityPrimeSet_infinite_v2

/-!
# Enumerating a positive-density orderly-prime set (inverse-seed convention)

Theorem statement: `HorizontalPadicL.positiveDensityOrderlySet_to_primeSystem_inverseSeed_v2`
(`41fd2636-d820-49e2-8385-68716ee4538e`), by davidloeffler, 2026-09-25.

Proof: submission `f07ba611-0aa4-44e3-9ef6-8aa5e42d91fd`, by davidloeffler, 2026-09-25 (ACCEPTED);
locally adapted.

Let $A$ be a positive-density set of rational primes, all orderly with the same exponent $m>0$, and
all avoiding a fixed modulus $B$. Then $A$ admits an injective enumeration which, together with its
density certificate and local properties, defines a seeded horizontal prime system of order exponent
$m$.

This is the set-theoretic passage from the Chebotarev prime set to the sequence required by the
horizontal measure construction.

This replacement uses the inverse-seed convention matching MTT criticalLValue: the orderly-prime
expression and Euler augmentation are eta(l)*a_l - eta(l)^2 - epsilon(l). The critical values and
seed hypotheses themselves retain the character eta. It supersedes
`HorizontalPadicL.positiveDensityOrderlySet_to_primeSystem`.

## Explanation of the source proof

A set of primes of positive natural density is infinite. Choose an injective enumeration of the
Frobenius prime set. Each enumerated prime inherits primality, avoidance of the fixed modulus, the
orderly-prime property, and the common exponent $m$. Transporting the original natural-density
certificate across the equality between the range of the enumeration and the prime set supplies the
density field. These data form the required seeded horizontal prime system.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

open HorizontalPadicL

theorem solution
    {N k p m B : ℕ} {ι : MTT.Qbar →+* ℂ} [Fact p.Prime]
    {f : MTT.Eigenform N k ι} {η : DirichletCharacterWithLevel}
    {V : SeededEigenformPadicPlaceData (p := p) f η}
    (hm : 0 < m)
    (D : SeededOrderlyFrobeniusClassData f η m B V)
    (δ : ℝ) (hδ : 0 < δ)
    (hdensity : HasPrimeNaturalDensity D.primes δ)
    (horderly : ∀ ⦃ℓ : ℕ⦄, ℓ ∈ D.primes →
      IsOrderlyPrimeForSeededEigenformV3 p m V.embedding f η ℓ) :
    ∃ L : SeededHorizontalPrimeSystemV3 p V.embedding f η B,
      L.orderExponent = m := by
  classical
  have hinfinite : D.primes.Infinite :=
    positiveDensityPrimeSet_infinite_v2 D.primes δ hδ hdensity
  let : Infinite D.primes := Set.infinite_coe_iff.mpr hinfinite
  let : Denumerable D.primes := Denumerable.ofEncodableOfInfinite D.primes
  let e : ℕ ≃ D.primes := (Denumerable.eqv D.primes).symm
  have hrange : {ℓ : ℕ | ∃ n : ℕ, (e n : ℕ) = ℓ} = D.primes := by
    ext ℓ
    constructor
    · rintro ⟨n, rfl⟩
      exact (e n).property
    · intro hℓ
      obtain ⟨n, hn⟩ := e.surjective ⟨ℓ, hℓ⟩
      exact ⟨n, congrArg Subtype.val hn⟩
  let L : SeededHorizontalPrimeSystemV3 p V.embedding f η B :=
    { orderExponent := m
      orderExponent_pos := hm
      primeAt := fun n => e n
      primeAt_prime := fun n => D.prime_of_mem (e n).property
      primeAt_injective := by
        intro a b hab
        apply e.injective
        exact Subtype.ext hab
      primeAt_avoids := fun n => D.avoids (e n).property
      primeAt_orderly := fun n => horderly (e n).property
      naturalDensity := δ
      naturalDensity_pos := hδ
      has_naturalDensity := by simpa [hrange] using hdensity }
  exact ⟨L, rfl⟩
end

end privateSection

public section publicSection

namespace HorizontalPadicL

theorem positiveDensityOrderlySet_to_primeSystem_inverseSeed_v2
    {N k p m B : ℕ} {ι : MTT.Qbar →+* ℂ} [Fact p.Prime]
    {f : MTT.Eigenform N k ι} {η : DirichletCharacterWithLevel}
    {V : SeededEigenformPadicPlaceData (p := p) f η}
    (hm : 0 < m)
    (D : SeededOrderlyFrobeniusClassData f η m B V)
    (δ : ℝ) (hδ : 0 < δ)
    (hdensity : HasPrimeNaturalDensity D.primes δ)
    (horderly : ∀ ⦃ℓ : ℕ⦄, ℓ ∈ D.primes →
      IsOrderlyPrimeForSeededEigenformV3 p m V.embedding f η ℓ) :
    ∃ L : SeededHorizontalPrimeSystemV3 p V.embedding f η B,
      L.orderExponent = m := _root_.solution hm D δ hδ hdensity horderly

end HorizontalPadicL

end publicSection
