/-
Based on Prove2Me node HorizontalPadicL.attachedEigenform_nonvanishingCount_eq
(eafc3e76-d595-4f6f-8d06-7ae1d84ced99) by davidloeffler (2026-10-08).

Proof based on Prove2Me submission de51c2f1-29c9-42b4-9e87-a35eeda08dcd
by davidloeffler (2026-10-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_EllipticCurveAttachedEigenform

/-!
# Equality of elliptic-curve and attached-eigenform nonvanishing counts

Theorem statement: `HorizontalPadicL.attachedEigenform_nonvanishingCount_eq`
(`eafc3e76-d595-4f6f-8d06-7ae1d84ced99`), by davidloeffler, 2026-10-08.

Proof: submission `de51c2f1-29c9-42b4-9e87-a35eeda08dcd`, by davidloeffler, 2026-10-08 (ACCEPTED);
locally adapted.

Let E be a modular elliptic curve over the rationals, fix a complex embedding ι, and let f_E be its
specified weight-two eigenform at the least modular level. For every natural number d and every real
conductor bound X, the number of primitive Dirichlet characters of exact order d, conductor at most
X and coprime to the level, with nonzero central twisted value, agrees for f_E and E:

$$ C_{f_E,d}(X)=C_{E,d}(X). $$

This identifies the two counting functions for the same specific attached form, allowing eigenform
nonvanishing theorems to be transferred to E without choosing an unspecified eigenform.

## Explanation of the source proof

For every order d and conductor bound X, the attached-eigenform count equals the elliptic-curve
count. Both count precisely the same primitive Dirichlet characters, subject to the same order,
conductor and coprimality conditions, and test the same central twisted value of the chosen
minimal-level cusp form. After unfolding the attached construction, equality is definitional.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

open HorizontalPadicL

theorem solution
    (iota : MTT.Qbar →+* ℂ) (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (hmod : IsModular E) :
    ∀ d : ℕ, ∀ X : ℝ,
      eigenformNonvanishingCount iota (attachedEigenform iota E hmod) d X =
        nonvanishingCount iota E hmod d X := by
  intro d X
  rfl
end

end privateSection

public section publicSection

noncomputable section

open HorizontalPadicL

theorem HorizontalPadicL.attachedEigenform_nonvanishingCount_eq
    (iota : MTT.Qbar →+* ℂ) (E : WeierstrassCurve ℚ) [E.IsElliptic]
    (hmod : IsModular E) :
    ∀ d : ℕ, ∀ X : ℝ,
      eigenformNonvanishingCount iota (attachedEigenform iota E hmod) d X =
        nonvanishingCount iota E hmod d X := _root_.solution iota E hmod
end

end publicSection
