/-
Based on Prove2Me node MTT.Eigenform.heckeEigenvalue_isIntegral
(b602e93d-e30a-4a10-989b-4f770faf14f9) by davidloeffler (2026-09-18).

Proof based on Prove2Me submission 28304ff0-667e-422d-ba8c-b3144535a6b2
by davidloeffler (2026-09-18); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_Arithmetic
public import Mathlib.RingTheory.IntegralClosure.Algebra.Basic

import Theorems.KN.Thm_MTT_Cohomology_eigenform_hecke_stable_period_lattice

/-!
# Prime Hecke eigenvalues are algebraic integers

Theorem statement: `MTT.Eigenform.heckeEigenvalue_isIntegral`
(`b602e93d-e30a-4a10-989b-4f770faf14f9`), by davidloeffler, 2026-09-18.

Proof: submission `28304ff0-667e-422d-ba8c-b3144535a6b2`, by davidloeffler, 2026-09-18 (ACCEPTED);
locally adapted.

For a normalized algebraic Hecke eigenform f of positive level and weight at least two, the
eigenvalue a_ell(f) is integral over Z for every prime ell.

The intended reduction uses the nonzero finitely generated period-evaluation lattice stable under
multiplication by a_ell(f), and the standard finite-module criterion for integrality.

## Explanation of the source proof

Let L be the nonzero finitely generated Z-submodule of Qbar supplied by
MTT.Cohomology.eigenform_hecke_stable_period_lattice for the prime ell. By construction,
multiplication by a_ell(f) sends L into L. Mathlib's finite-module integrality criterion
isIntegral_of_smul_mem_submodule then shows that a_ell(f) is integral over Z. The signed-packet
component of the lower theorem records that this lattice is the one attached to f, not an unrelated
existential lattice.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

theorem solution
    {N k : ℕ} (hN : 0 < N) (hk : 2 ≤ k)
    (ι : MTT.Qbar →+* ℂ) (f : MTT.Eigenform N k ι)
    (l : ℕ) (hl : l.Prime) :
    IsIntegral ℤ (f.coeff l) := by
  obtain ⟨ψ, _hpacket, hne, hfg, hstable⟩ :=
    MTT.Cohomology.eigenform_hecke_stable_period_lattice hN hk ι f l hl
  let L : Submodule ℤ MTT.Qbar :=
    Submodule.span ℤ {v : MTT.Qbar | ∃ s j r, j ≤ k - 2 ∧
      v = MTT.Cohomology.evaluation j r (ψ s) /
        ((k - 2).choose j : MTT.Qbar)}
  exact isIntegral_of_smul_mem_submodule L hne hfg (f.coeff l) (by
    intro x hx
    simpa only [smul_eq_mul, L] using
      hstable x (by simpa only [L] using hx))
end

end privateSection

public section publicSection

noncomputable section

theorem MTT.Eigenform.heckeEigenvalue_isIntegral
    {N k : ℕ} (hN : 0 < N) (hk : 2 ≤ k)
    (ι : MTT.Qbar →+* ℂ) (f : MTT.Eigenform N k ι)
    (l : ℕ) (hl : l.Prime) :
    IsIntegral ℤ (f.coeff l) := _root_.solution hN hk ι f l hl
end

end publicSection
