/-
Based on Prove2Me node HorizontalPadicL.residualKernel_discr_prime_dvd_level_mul_p
(ae669fc9-ed13-4e50-af51-60c68eae9f0d) by davidloeffler (2026-09-20).

Proof based on Prove2Me submission 0cbcfc71-f2fd-4087-9ebd-55d7ace13654
by davidloeffler (2026-09-20); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_EigenformResidualGaloisRepresentationV2
public import Mathlib.NumberTheory.NumberField.Discriminant.Different

/-!
# Prime divisors of a residual kernel-field discriminant divide Np

Theorem statement: `HorizontalPadicL.residualKernel_discr_prime_dvd_level_mul_p`
(`ae669fc9-ed13-4e50-af51-60c68eae9f0d`), by davidloeffler, 2026-09-20.

Proof: submission `0cbcfc71-f2fd-4087-9ebd-55d7ace13654`, by davidloeffler, 2026-09-20 (ACCEPTED);
locally adapted.

Let $f$ be an MTT eigenform of positive level $N$ and weight $k\geq 2$, let $p$ be prime, and let
$D$ be residual Galois-representation data for $f$ at a chosen $p$-adic embedding. If a rational
prime $\ell$ divides the discriminant of the finite Galois kernel field recorded by $D$, then $\ell$
divides $Np$. Equivalently, the kernel field is discriminantly unramified away from the modular
level and the residue characteristic.

## Explanation of the source proof

For a prime l not dividing Np, the residual-representation package says that the inertia subgroup at
every prime Q above l is trivial. Its cardinality is therefore one. Mathlib identifies the
cardinality of inertia with the global ramification index and that index with the local ramification
index at Q; the latter equals one exactly when the integer-ring extension is unramified at Q. The
discriminant criterion `NumberField.not_dvd_discr_iff_forall_liesOver` then shows that l does not
divide the kernel-field discriminant. Contraposition gives the result. The uploaded theorem is at
`_root_.solution`.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

namespace HorizontalPadicL

open NumberField Ideal FrobeniusDensity

theorem _root_.solution
    {N k p : ℕ} [Fact p.Prime]
    (hN : 0 < N) (hk : 2 ≤ k)
    {ι : MTT.Qbar →+* ℂ}
    (f : MTT.Eigenform N k ι) (ιp : MTT.Qbar →+* ℂ_[p])
    (D : EigenformResidualGaloisRepresentationData hN hk f ιp) :
    letI : Field D.kernelField := D.kernelField_field
    letI : NumberField D.kernelField := D.kernelField_numberField
    ∀ {l : ℕ}, l.Prime →
      (l : ℤ) ∣ NumberField.discr D.kernelField → l ∣ N * p := by
  let K := D.kernelField
  let : Field K := D.kernelField_field
  have : NumberField K := D.kernelField_numberField
  have : IsGalois ℚ K := D.kernelField_galois
  intro l hl hldisc
  by_contra hldvd
  have hlcop : Nat.Coprime l (N * p) :=
    hl.coprime_iff_not_dvd.mpr hldvd
  have hnotdisc : ¬ (l : ℤ) ∣ NumberField.discr K := by
    rw [NumberField.not_dvd_discr_iff_forall_liesOver K (𝓞 K)
      (Nat.prime_iff_prime_int.mp hl)]
    intro Q hQmax hQover
    have : Fact l.Prime := ⟨hl⟩
    have : Q.IsPrime := hQmax.isPrime
    have : Q.LiesOver (ratPrimeIdeal l) := hQover
    have hI : Q.inertia (K ≃ₐ[ℚ] K) = ⊥ :=
      D.unramified_outside hl hlcop Q inferInstance inferInstance
    rw [← Ideal.ramificationIdx_eq_one_iff,
      ← Ideal.ramificationIdxIn_eq_ramificationIdx
        (ratPrimeIdeal l) Q (K ≃ₐ[ℚ] K),
      ← Ideal.card_inertia_eq_ramificationIdxIn
        (G := K ≃ₐ[ℚ] K) (ratPrimeIdeal l) Q,
      hI]
    simp
  exact hnotdisc hldisc

end HorizontalPadicL
end

end privateSection

public section publicSection

noncomputable section

namespace HorizontalPadicL

/-- Every rational prime dividing the discriminant of the kernel field of an
eigenform's residual Galois representation divides the product of the modular
level and the residue characteristic. -/
theorem residualKernel_discr_prime_dvd_level_mul_p
    {N k p : ℕ} [Fact p.Prime]
    (hN : 0 < N) (hk : 2 ≤ k)
    {ι : MTT.Qbar →+* ℂ}
    (f : MTT.Eigenform N k ι) (ιp : MTT.Qbar →+* ℂ_[p])
    (D : EigenformResidualGaloisRepresentationData hN hk f ιp) :
    letI : Field D.kernelField := D.kernelField_field
    letI : NumberField D.kernelField := D.kernelField_numberField
    ∀ {l : ℕ}, l.Prime →
      (l : ℤ) ∣ NumberField.discr D.kernelField → l ∣ N * p := _root_.solution hN hk f ιp D

end HorizontalPadicL
end

end publicSection
