/-
Based on Prove2Me node HorizontalPadicL.seededHorizontalPadicLFunction_assemble_v4
(fb490c4e-b63a-4812-9aad-c4b8f7ee761a) by davidloeffler (2026-09-25).

Proof based on Prove2Me submission d5ae83c7-34b2-4089-b92c-5be1f3291c2c
by davidloeffler (2026-09-25); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_SeededHorizontalPadicLFunctionV3B
public import Definitions.KN.Def_KN_SeededThetaConstructionV2B
public import Definitions.KN.Def_KN_InverseSeedConventionV2

/-!
# Package a faithful theta measure as a clean seeded horizontal p-adic L-function

Theorem statement: `HorizontalPadicL.seededHorizontalPadicLFunction_assemble_v4`
(`fb490c4e-b63a-4812-9aad-c4b8f7ee761a`), by davidloeffler, 2026-09-25.

Proof: submission `d5ae83c7-34b2-4089-b92c-5be1f3291c2c`, by davidloeffler, 2026-09-25 (ACCEPTED);
locally adapted.

A normalized theta measure with faithful character realization, interpolation, and nonzero trivial
value packages with the original positive-density prime system to give a seeded horizontal p-adic
L-function on the clean replacement definition spine.

This is the clean-spine replacement used to remove deprecated definition bundles from the live
graph.

## Explanation of the source proof

This is a packaging argument. Use the given prime system and normalized measure as the corresponding
fields of the seeded horizontal \(p\)-adic \(L\)-function. The supplied character-realization and
interpolation hypotheses establish the bundled interpolation property, and rewriting along the
resulting equality of prime systems gives the asserted nonvanishing at the trivial horizontal
character.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

open HorizontalPadicL

set_option linter.unusedVariables false in
theorem solution
    {N k p B : ℕ} {ι : MTT.Qbar →+* ℂ} [Fact p.Prime]
    (f : MTT.Eigenform N k ι) (hnew : IsNewEigenform f)
    (η : DirichletCharacterWithLevel) (ιp : MTT.Qbar →+* ℂ_[p])
    (L : SeededHorizontalPrimeSystemV3 p ιp f η B)
    (μ : SeededNormalizedThetaMeasureV3 L.toConstructionData)
    (hcharacters : μ.characters.HasExpectedProperties)
    (hinterp : μ.InterpolatesSeededCriticalValues)
    (htrivial : μ.measure.eval
      (trivialHorizontalCharacterV2 p L.toConstructionData.exponent) ≠ 0) :
    ∃ ν : SeededHorizontalPadicLFunctionV4 (B := B) p ιp f η,
      ν.primes = L ∧ ν.InterpolatesSeededCriticalValuesV4 ∧
      ν.measure.eval (trivialHorizontalCharacterV2 p ν.primes.exponent) ≠ 0 := by
  let ν : SeededHorizontalPadicLFunctionV4 (B := B) p ιp f η :=
    { primes := L
      coefficientRing := μ.coefficientRing
      coefficient_integral := μ.coefficient_integral
      measure := μ.measure }
  refine ⟨ν, rfl, ?_, htrivial⟩
  refine ⟨μ.characters, hcharacters, ?_⟩
  intro χ
  exact hinterp χ
end

end privateSection

public section publicSection

noncomputable section

namespace HorizontalPadicL

/-- Package a faithful normalized theta measure together with the original
positive-density prime system. -/
theorem seededHorizontalPadicLFunction_assemble_v4
    {N k p B : ℕ} {ι : MTT.Qbar →+* ℂ} [Fact p.Prime]
    (f : MTT.Eigenform N k ι) (hnew : IsNewEigenform f)
    (η : DirichletCharacterWithLevel) (ιp : MTT.Qbar →+* ℂ_[p])
    (L : SeededHorizontalPrimeSystemV3 p ιp f η B)
    (μ : SeededNormalizedThetaMeasureV3 L.toConstructionData)
    (hcharacters : μ.characters.HasExpectedProperties)
    (hinterp : μ.InterpolatesSeededCriticalValues)
    (htrivial : μ.measure.eval
      (trivialHorizontalCharacterV2 p L.toConstructionData.exponent) ≠ 0) :
    ∃ ν : SeededHorizontalPadicLFunctionV4 (B := B) p ιp f η,
      ν.primes = L ∧ ν.InterpolatesSeededCriticalValuesV4 ∧
      ν.measure.eval (trivialHorizontalCharacterV2 p ν.primes.exponent) ≠ 0 := _root_.solution f hnew η ιp L μ hcharacters hinterp htrivial

end HorizontalPadicL
end

end publicSection
