/-
Based on Prove2Me node HorizontalPadicL.ellipticCurve_minimalModularLevel_iff_localEulerFactorDegree_lt_two
(c7f83142-37ef-43e3-9262-ef2e86ce5f10) by davidloeffler (2026-09-18).

Proof based on Prove2Me submission 83f8c962-dce9-46d1-8654-71f5794dcf04
by cm_beta (2026-09-21); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_HorizontalPadicL_LocalEulerFactorDegree

import Theorems.KN.Thm_HorizontalPadicL_minimalModularLevel_dvd_iff_localEulerFactorDegreeBelowTwo
import Theorems.KN.Thm_HorizontalPadicL_not_minimalModularLevel_dvd_iff_localEulerFactorDegreeTwo

/-!
# The minimal modular level detects subquadratic local Euler factors

Theorem statement:
`HorizontalPadicL.ellipticCurve_minimalModularLevel_iff_localEulerFactorDegree_lt_two`
(`c7f83142-37ef-43e3-9262-ef2e86ce5f10`), by davidloeffler, 2026-09-18.

Proof: submission `83f8c962-dce9-46d1-8654-71f5794dcf04`, by cm_beta, 2026-09-21 (ACCEPTED); locally
adapted.

**This is a formalization of a standard textbook result, so low-priority**

Let $E/\mathbb{Q}$ be an elliptic curve which is modular in the sense that its Hasse–Weil $L$-series
is the q-expansion of a weight-two cusp form, and let $N_{\min}$ be the least level at which such a
form exists. For every prime $p$,
$$
p \mid N_{\min} \quad\Longleftrightarrow\quad L_p(E,s)^{-1} \text{ has degree }<2.
$$
In coefficient terms, primes dividing $N_{\min}$ satisfy $a_{p^{r+2}}=a_p a_{p^{r+1}}$, while primes
not dividing $N_{\min}$ satisfy the normalized quadratic recurrence $a_{p^{r+2}}=a_p a_{p^{r+1}}-p
a_{p^r}$. Thus the prime support of the minimal modular level agrees with the bad local-factor
support of the elliptic curve.

## Explanation of the source proof

We split the characterisation of the prime support of the minimal modular level into its ramified
and unramified halves.

For a modular elliptic curve $E/\mathbb{Q}$ with modular conductor $N_E$ and a prime $p$, the parent
statement is the conjunction of two equivalences:

$$p\mid N_E \iff \deg L_p(E,\cdot)<2, \qquad p\nmid N_E \iff \deg L_p(E,\cdot)=2.$$

Together they say that the primes dividing the level are exactly those at which the local Euler
polynomial fails to be quadratic, and that the remaining primes carry the full quadratic factor.

The reduction introduces one child for each equivalence:

- `minimalModularLevel_dvd_iff_localEulerFactorDegreeBelowTwo`, the ramified direction;
- `not_minimalModularLevel_dvd_iff_localEulerFactorDegreeTwo`, the unramified direction.

Both are assumptions of this submission, not results of it.

Although the two equivalences concern complementary conditions on $p$, they are not formally
interchangeable here: degree below two and degree exactly two are separate predicates in the
formalisation rather than negations of one another, so neither statement follows from the other
without knowing that the degree is at most two. Keeping them apart records that fact rather than
obscuring it, and matches how they are used: arguments about the level itself need the ramified
characterisation, while arguments about the Euler product away from the level need the unramified
one.

Mathematically the content is the standard dichotomy of reduction types. Degree below two at $p$ is
the signature of bad reduction, the local factor being linear in the multiplicative case and
constant in the additive case; good reduction gives the full factor $1-a_pX+pX^{2}$.

In Lean the reduction is the introduction rule for conjunction applied to the two children at the
same curve, modularity witness and prime.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxRecDepth 100000
set_option maxHeartbeats 400000
set_option linter.all false

open HorizontalPadicL

theorem _root_.solution
    (E : WeierstrassCurve ℚ) [E.IsElliptic] (hmod : IsModular E)
    (p : ℕ) (hp : p.Prime) :
    (p ∣ modularConductor E hmod ↔ LocalEulerFactorDegreeBelowTwo E p) ∧
      (¬ p ∣ modularConductor E hmod ↔ LocalEulerFactorDegreeTwo E p) :=
  ⟨HorizontalPadicL.minimalModularLevel_dvd_iff_localEulerFactorDegreeBelowTwo E hmod p hp,
   HorizontalPadicL.not_minimalModularLevel_dvd_iff_localEulerFactorDegreeTwo E hmod p hp⟩

end privateSection

public section publicSection

namespace HorizontalPadicL

/-- The prime support of the least modular level is exactly the set of places
where the elliptic curve's local Euler polynomial has degree below two;
equivalently, the primes outside the level are exactly those with the normalized
quadratic local factor. -/
theorem ellipticCurve_minimalModularLevel_iff_localEulerFactorDegree_lt_two
    (E : WeierstrassCurve ℚ) [E.IsElliptic] (hmod : IsModular E)
    (p : ℕ) (hp : p.Prime) :
    (p ∣ modularConductor E hmod ↔ LocalEulerFactorDegreeBelowTwo E p) ∧
      (¬ p ∣ modularConductor E hmod ↔ LocalEulerFactorDegreeTwo E p) := _root_.solution E hmod p hp

end HorizontalPadicL

end publicSection
