/-
Based on Prove2Me node HorizontalPadicL.coprimeDiscriminant_simultaneousSeededFrobeniusClass_exists_v2
(77bb9d30-8d23-4457-8f5d-f68d26e885ae) by davidloeffler (2026-09-25).

Proof based on Prove2Me submission c7805816-bbd2-4be3-be0a-51eb1c48ec60
by davidloeffler (2026-09-25); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_SeededPrimeGaloisDataV2
public import Definitions.KN.Def_KN_EigenformResidualGaloisRepresentationV2
public import Mathlib.NumberTheory.NumberField.Discriminant.Different

import Theorems.KN.Thm_NumberField_not_dvd_discr_sup_of_not_dvd_discr
import Theorems.KN.Thm_IsCyclotomicExtension_Rat_prime_dvd_discr_dvd_conductor
import Theorems.KN.Thm_HorizontalPadicL_coprimeRamification_productFrobeniusClass_exists_v2

/-!
# Coprime discriminants give the simultaneous seeded Frobenius class

Theorem statement: `HorizontalPadicL.coprimeDiscriminant_simultaneousSeededFrobeniusClass_exists_v2`
(`77bb9d30-8d23-4457-8f5d-f68d26e885ae`), by davidloeffler, 2026-09-25.

Proof: submission `c7805816-bbd2-4be3-be0a-51eb1c48ec60`, by davidloeffler, 2026-09-25 (ACCEPTED);
locally adapted.

Let a residual eigenform representation have kernel-field discriminant supported on $Np$, and choose
a residue class on which the seed character has full order. If the seed conductor is coprime to
$Np$, then there is a Chebotarev class of primes whose residual and $p^mN$-cyclotomic Frobenius
components are trivial and whose seed component is the chosen full-order value, while avoiding a
prescribed integer $B$. Consequently the primes have all congruence, coprimality, coefficient and
character properties recorded by `SeededOrderlyFrobeniusClassData`.

## Explanation of the source proof

Apply the product-Frobenius theorem already established for the clean definition spine. Its
compositum input is the standard theorem that a rational prime unramified in each of two number
fields remains unramified in their compositum. Its cyclotomic input follows from the discriminant
formula for cyclotomic fields: every prime dividing the discriminant of an $n$-th cyclotomic field
divides $n$.

The residual-kernel discriminant support and the coprimality of the seed conductor with $Np$ then
give the hypotheses of that theorem, which returns the required simultaneous seeded Frobenius class.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

namespace HorizontalPadicL

theorem _root_.solution
    {N k p : ℕ} [Fact p.Prime]
    (hN : 0 < N) (hk : 2 ≤ k)
    (ι : MTT.Qbar →+* ℂ) (f : MTT.Eigenform N k ι)
    (η : DirichletCharacterWithLevel)
    (m B : ℕ) (hB : 0 < B)
    (hηcoprime : Nat.Coprime (N * p) η.2.conductor)
    (V : SeededEigenformPadicPlaceData (p := p) f η)
    (D : EigenformResidualGaloisRepresentationData hN hk f V.embedding)
    (a : (ZMod η.1.1)ˣ)
    (ha : orderOf (η.2 (a : ZMod η.1.1)) = orderOf η.2)
    (hdiscr :
      letI : Field D.kernelField := D.kernelField_field
      letI : NumberField D.kernelField := D.kernelField_numberField
      ∀ {l : ℕ}, l.Prime →
        (l : ℤ) ∣ NumberField.discr D.kernelField → l ∣ N * p) :
    Nonempty (SeededOrderlyFrobeniusClassData f η m B V) := by
  refine coprimeRamification_productFrobeniusClass_exists_v2
    hN hk ι f η m B hB hηcoprime V D a ha hdiscr
      NumberField.not_dvd_discr_sup_of_not_dvd_discr
      ?_
  intro n hn K hK hcyclo l hl hldisc
  exact IsCyclotomicExtension.Rat.prime_dvd_discr_dvd_conductor
    n K hl hldisc

end HorizontalPadicL
end

end privateSection

public section publicSection

noncomputable section

namespace HorizontalPadicL

/-- The pure Galois-theoretic step in the seeded-prime construction.

Suppose the kernel field of a residual eigenform representation has
discriminant supported on `N * p`, and choose a residue class on which the
seed character has full order.  If the seed conductor is coprime to `N * p`,
then the residual kernel field and the `p ^ m * N` cyclotomic field are
linearly disjoint from the seed cyclotomic field.  A product automorphism
which is trivial on the first two factors and realizes the chosen seed class
therefore determines the required Chebotarev class. -/
theorem coprimeDiscriminant_simultaneousSeededFrobeniusClass_exists_v2
    {N k p : ℕ} [Fact p.Prime]
    (hN : 0 < N) (hk : 2 ≤ k)
    (ι : MTT.Qbar →+* ℂ) (f : MTT.Eigenform N k ι)
    (η : DirichletCharacterWithLevel)
    (m B : ℕ) (hB : 0 < B)
    (hηcoprime : Nat.Coprime (N * p) η.2.conductor)
    (V : SeededEigenformPadicPlaceData (p := p) f η)
    (D : EigenformResidualGaloisRepresentationData hN hk f V.embedding)
    (a : (ZMod η.1.1)ˣ)
    (ha : orderOf (η.2 (a : ZMod η.1.1)) = orderOf η.2)
    (hdiscr :
      letI : Field D.kernelField := D.kernelField_field
      letI : NumberField D.kernelField := D.kernelField_numberField
      ∀ {l : ℕ}, l.Prime →
        (l : ℤ) ∣ NumberField.discr D.kernelField → l ∣ N * p) :
    Nonempty (SeededOrderlyFrobeniusClassData f η m B V) := _root_.solution hN hk ι f η m B hB hηcoprime V D a ha hdiscr

end HorizontalPadicL
end

end publicSection
