/-
Based on Prove2Me node AdicCompletion.exists_domain_dvr_complete
(321b13ea-c50b-4685-a62c-50be4c5cfb83) by riccardo.brasca (2026-09-24).

Proof based on Prove2Me submission 0dd2194c-3612-4c7c-83bd-d53c78e9e22b
by riccardo.brasca (2026-09-24); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Theorems.FLT.Thm_IsDiscreteValuationRing_adicCompletion_isDomain_isDiscreteValuationRing_isAdicComplete
public import Theorems.FLT.Thm_Ideal_IsMaximal_exists_adicCompletion_localization_ringEquiv
public import Mathlib.RingTheory.DedekindDomain.Dvr
public import Mathlib.RingTheory.AdicCompletion.Topology

/-!
# The completion of a Dedekind domain at a nonzero prime is a complete DVR

Theorem statement: `AdicCompletion.exists_domain_dvr_complete`
(`321b13ea-c50b-4685-a62c-50be4c5cfb83`), by riccardo.brasca, 2026-09-24.

Proof: submission `0dd2194c-3612-4c7c-83bd-d53c78e9e22b`, by riccardo.brasca, 2026-09-24 (ACCEPTED);
locally adapted.

Let $A$ be a Dedekind domain and let $\mathfrak p$ be a nonzero prime ideal of $A$. The
inverse-limit completion

$$\widehat A_{\mathfrak p}=\varprojlim_{n\ge0} A/\mathfrak p^n$$

is an integral domain and a discrete valuation ring, and is complete with respect to its own maximal
ideal.

This gives the algebraic local coefficient ring used when passing from field-valued Galois
representations to integral lattices. The existing ring structure on the inverse limit is retained.

## Explanation of the source proof

Let $A$ be a Dedekind domain and $\mathfrak p$ a nonzero prime ideal. Its completion

$$\widehat A_{\mathfrak p}=\varprojlim_n A/\mathfrak p^n$$

is an integral domain, a discrete valuation ring, and complete for its maximal
ideal. The proof passes through the localization $A_{\mathfrak p}$, so the ring
structure on the displayed inverse limit is preserved.

A nonzero prime of a Dedekind domain is maximal, and its localization is a DVR.
Choose a uniformizer there. The existing proved theorem on the completion of a
DVR supplies the domain, DVR, and completeness properties of the completed
localization. The existing proved localization/completion comparison identifies
that ring with $\widehat A_{\mathfrak p}$. Transport the domain and DVR properties
along this ring isomorphism. Ring isomorphisms carry maximal ideals to maximal
ideals, so adic completeness transports as well.

The two platform inputs are
[the DVR completion theorem](https://prove2.me/theorems/a0e3aec5-3479-5c44-9927-bcd6e6f2d355)
and [the localization/completion
comparison](https://prove2.me/theorems/d1ec29e0-26c9-5e94-b475-5ce731ee73ca).
Both are already Proved. The localization being a DVR and the transport lemmas
are in mathlib. No new open input is introduced.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

/-!
Completion of a Dedekind domain at a nonzero prime, by localization to a DVR.

Exact Prove2Me inputs:
* `IsDiscreteValuationRing.adicCompletion_isDomain_isDiscreteValuationRing_isAdicComplete`,
  theorem `a0e3aec5-3479-5c44-9927-bcd6e6f2d355`;
* `Ideal.IsMaximal.exists_adicCompletion_localization_ringEquiv`,
  theorem `d1ec29e0-26c9-5e94-b475-5ce731ee73ca`.

Mathlib supplies the DVR property of the localization and transfer of domain,
DVR, and adic completeness along the completion comparison.
-/

noncomputable section

open IsLocalRing

/-- Completing a Dedekind domain at a nonzero prime gives a complete DVR. -/
theorem solution
    {R : Type*} [CommRing R] [IsDedekindDomain R]
    (P : Ideal R) [P.IsPrime] (hP : P ≠ ⊥) :
    ∃ (_ : IsDomain (AdicCompletion P R))
      (_ : IsDiscreteValuationRing (AdicCompletion P R)),
      IsAdicComplete (maximalIdeal (AdicCompletion P R)) (AdicCompletion P R) := by
  let : P.IsMaximal := (inferInstance : P.IsPrime).isMaximal hP
  let A := Localization.AtPrime P
  let : IsDiscreteValuationRing A :=
    IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain R hP A
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible A
  obtain ⟨hD, hV, hC, _⟩ :=
    IsDiscreteValuationRing.adicCompletion_isDomain_isDiscreteValuationRing_isAdicComplete A ϖ hϖ
  obtain ⟨e, _⟩ := Ideal.IsMaximal.exists_adicCompletion_localization_ringEquiv P
  let : IsDomain (AdicCompletion P R) := e.symm.toMulEquiv.isDomain _
  let : IsDiscreteValuationRing (AdicCompletion P R) :=
    IsDiscreteValuationRing.RingEquivClass.isDiscreteValuationRing e
  refine ⟨inferInstance, inferInstance, ?_⟩
  have hc := (IsAdicComplete.congr_ringEquiv
    (maximalIdeal (AdicCompletion (maximalIdeal A) A)) e).mpr hC
  rw [IsLocalRing.map_ringEquiv_maximalIdeal] at hc
  exact hc
end

end privateSection

public section publicSection

/-!
Completion of a Dedekind domain at a nonzero prime, by localization to a DVR.

Exact Prove2Me inputs:
* `IsDiscreteValuationRing.adicCompletion_isDomain_isDiscreteValuationRing_isAdicComplete`,
  theorem `a0e3aec5-3479-5c44-9927-bcd6e6f2d355`;
* `Ideal.IsMaximal.exists_adicCompletion_localization_ringEquiv`,
  theorem `d1ec29e0-26c9-5e94-b475-5ce731ee73ca`.

Mathlib supplies the DVR property of the localization and transfer of domain,
DVR, and adic completeness along the completion comparison.
-/

noncomputable section

open IsLocalRing

namespace AdicCompletion

/-- Completing a Dedekind domain at a nonzero prime gives a complete DVR. -/
theorem exists_domain_dvr_complete
    {R : Type*} [CommRing R] [IsDedekindDomain R]
    (P : Ideal R) [P.IsPrime] (hP : P ≠ ⊥) :
    ∃ (_ : IsDomain (AdicCompletion P R))
      (_ : IsDiscreteValuationRing (AdicCompletion P R)),
      IsAdicComplete (maximalIdeal (AdicCompletion P R)) (AdicCompletion P R) := _root_.solution P hP

end AdicCompletion
end

end publicSection
