/-
Based on Prove2Me node HorizontalPadicL.elliptic_curve_nonvanishing
(53466256-0006-44f1-b2e6-81abf6f407e1) by davidloeffler (2026-09-17).

Proof based on Prove2Me submission 3b2ead81-a182-4c86-9228-d6f93320d787
by davidloeffler (2026-10-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.KN.Def_KN_HorizontalPadicL

import Definitions.KN.Def_KN_EllipticCurveAttachedEigenform
import Theorems.KN.Thm_HorizontalPadicL_attachedEigenform_isNew
import Theorems.KN.Thm_HorizontalPadicL_attachedEigenform_nonvanishingCount_eq
import Theorems.KN.Thm_HorizontalPadicL_corollary_5_17_v2

/-!
# Theorem 1.1(1) — fixed-order nonvanishing for one elliptic curve

Theorem statement: `HorizontalPadicL.elliptic_curve_nonvanishing`
(`53466256-0006-44f1-b2e6-81abf6f407e1`), by davidloeffler, 2026-09-17.

Proof: submission `3b2ead81-a182-4c86-9228-d6f93320d787`, by davidloeffler, 2026-10-08
(SKETCH_ACCEPTED); locally adapted.

For every complex embedding of the algebraic numbers, every modular elliptic curve over the
rationals, and every d congruent to 2 modulo 4 with d at least 6, the number of primitive
exact-order-d characters of conductor at most X, conductor coprime to the least modular level, and
nonzero MTT twisted critical value at j = 0 has a lower bound of the stated logarithmic-power form
for some positive exponent.

## Explanation of the source proof

Let f_E be the specific weight-two eigenform attached to E at its least modular level N. The newness
theorem gives that f_E is new, and the separate counting theorem identifies its nonvanishing count
with that of E for every order and conductor bound. Apply Corollary 5.17 to f_E at weight two and
positive level N, then transfer its logarithmic-power lower bound through this equality. This
reduction uses the named attached form rather than an unspecified existential witness.

<!-- Generated by add_prove2me_provenance.py -->
-/

noncomputable section privateSection

open HorizontalPadicL

theorem solution
    (ι : MTT.Qbar →+* ℂ) (E : WeierstrassCurve ℚ) [E.IsElliptic] (d : ℕ)
    (hmod : IsModular E) (hcase1 : d % 4 = 2 ∧ 6 ≤ d) :
    ∃ α : ℝ, 0 < α ∧
      HasLogPowerLowerBound (nonvanishingCount ι E hmod d) α := by
  let f := attachedEigenform ι E hmod
  have hnew : IsNewEigenform f := attachedEigenform_isNew ι E hmod
  obtain ⟨α, hα, hbound⟩ := corollary_5_17_v2
    (modularConductor_pos E hmod) (by norm_num) (by norm_num) ι f hnew d hcase1
  refine ⟨α, hα, ?_⟩
  rw [← funext (attachedEigenform_nonvanishingCount_eq ι E hmod d)]
  exact hbound

end privateSection

public section publicSection

open scoped BigOperators NNReal

namespace HorizontalPadicL

theorem elliptic_curve_nonvanishing
    (ι : MTT.Qbar →+* ℂ) (E : WeierstrassCurve ℚ) [E.IsElliptic] (d : ℕ)
    (hmod : IsModular E) (hcase1 : d % 4 = 2 ∧ 6 ≤ d) :
    ∃ α : ℝ, 0 < α ∧
      HasLogPowerLowerBound (nonvanishingCount ι E hmod d) α := _root_.solution ι E d hmod hcase1

end HorizontalPadicL

end publicSection
