/-
Based on Prove2Me node IsCyclotomicExtension.Rat.prime_dvd_discr_dvd_conductor
(f5057246-6fea-4212-94ec-ea78f29cc47c) by davidloeffler (2026-09-20).

Proof based on Prove2Me submission 7e343652-c973-490f-894c-23c4214b5ad7
by davidloeffler (2026-09-20); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic

/-!
# Prime divisors of a cyclotomic discriminant divide its conductor

Theorem statement: `IsCyclotomicExtension.Rat.prime_dvd_discr_dvd_conductor`
(`f5057246-6fea-4212-94ec-ea78f29cc47c`), by davidloeffler, 2026-09-20.

Proof: submission `7e343652-c973-490f-894c-23c4214b5ad7`, by davidloeffler, 2026-09-20 (ACCEPTED);
locally adapted.

If $K/\mathbf Q$ is an $n$-th cyclotomic field and a rational prime $\ell$ divides
$\operatorname{disc}(K)$, then $\ell$ divides $n$.

## Explanation of the source proof

Pass divisibility of the integer discriminant by l to divisibility of its natural absolute value.
Rewrite this absolute value using `IsCyclotomicExtension.Rat.natAbs_discr`. Mathlib's
`Nat.prod_primeFactors_pow_totient_ediv_dvd` shows that the denominator in the formula divides `n ^
Nat.totient n`, so the displayed quotient divides this power. Hence l divides a power of n, and
primality of l gives l divides n. The uploaded theorem is at `_root_.solution`.

<!-- Generated by add_prove2me_provenance.py -->
-/

public noncomputable section publicSection

/-- Every rational prime dividing the discriminant of an `n`-th cyclotomic
field divides `n`. -/
theorem IsCyclotomicExtension.Rat.prime_dvd_discr_dvd_conductor
    (n : ℕ) [NeZero n] (K : Type*) [Field K] [NumberField K]
    [IsCyclotomicExtension {n} ℚ K]
    {l : ℕ} (hl : l.Prime)
    (hldisc : (l : ℤ) ∣ NumberField.discr K) : l ∣ n := by
  have hnat : l ∣ (NumberField.discr K).natAbs :=
    Int.natAbs_dvd_natAbs.mpr hldisc
  rw [IsCyclotomicExtension.Rat.natAbs_discr n K] at hnat
  have hden : (∏ q ∈ n.primeFactors, q ^ (n.totient / (q - 1))) ∣ n ^ n.totient :=
    Nat.prod_primeFactors_pow_totient_ediv_dvd (NeZero.pos n)
  have hpow : l ∣ n ^ Nat.totient n :=
    hnat.trans (Nat.div_dvd_of_dvd hden)
  exact hl.dvd_of_dvd_pow hpow

end publicSection
