/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.RayClass.CongruenceQuotient

import TauCeti.NumberTheory.NumberField.Global.Approximation.Weak
-- Private in `RayClass.Basic`; needed below for `ClassGroup.mk_toPrincipalIdeal`.
import TauCeti.RingTheory.ClassGroup.Basic

/-!
# The ray class exact sequence

For a modulus `m` of a number field `K`, forgetting its congruence and sign conditions sends a ray
class to an ordinary ideal class.  This file constructs the full exact sequence

```text
1 → unitsCongruenceSubgroup m → (𝓞 K)ˣ → A m → RayClassGroup m → ClassGroup (𝓞 K) → 1,
```

where `A m = (𝓞 K ⧸ m.finitePart)ˣ × (m.infinitePart → ℤˣ)` records residues and prescribed
signs.  It also retains the useful coarser exact tail
`primeToSubgroup m → RayClassGroup m → ClassGroup (𝓞 K) → 1`.

In the coarser tail, the first map sends an element of `Kˣ` that is a unit at the finite part to
the ray class of its principal ideal.  The second map is surjective, and its kernel is exactly the
range of the first.  Surjectivity of the transition maps follows by weak approximation, and
surjectivity onto the ordinary class group follows by transition to the trivial modulus.

The kernel of `A m → RayClassGroup m` is the image of the integer units, while the kernel of the
map from integer units to `A m` is `unitsCongruenceSubgroup m`.  The resulting exact sequence is
the input to the ray class number formula.

## Main definitions

* `TauCeti.GlobalNumberFields.principalRayClass`: the ray class of a principal fractional ideal
  whose generator is a unit at the finite part.
* `TauCeti.GlobalNumberFields.rayClassToClassGroup`: the ordinary ideal class underlying a ray
  class.
* `TauCeti.GlobalNumberFields.unitsResidueSignHom`: the residues and signs of the integer units.
* `TauCeti.GlobalNumberFields.residueSignRayClass`: the principal ray class of a residue unit and
  sign pattern.

## Main results

* `TauCeti.GlobalNumberFields.rayClassToClassGroup_surjective`: every ordinary ideal class lifts
  to a ray class.
* `TauCeti.GlobalNumberFields.ker_rayClassToClassGroup`: the kernel consists exactly of ray
  classes of principal ideals generated by elements in `primeToSubgroup m`.
* `TauCeti.GlobalNumberFields.mulExact_principalRayClass_rayClassToClassGroup`: the corresponding
  multiplicative exactness statement.
* `TauCeti.GlobalNumberFields.classMap_surjective`: every transition between ray class groups is
  surjective.
* `TauCeti.GlobalNumberFields.ker_unitsResidueSignHom`,
  `TauCeti.GlobalNumberFields.ker_residueSignRayClass` and
  `TauCeti.GlobalNumberFields.range_residueSignRayClass`: the three nontrivial exactness statements
  in the full sequence.
* `TauCeti.GlobalNumberFields.mulExact_unitsCongruenceSubgroup_unitsResidueSignHom`,
  `TauCeti.GlobalNumberFields.mulExact_unitsResidueSignHom_residueSignRayClass` and
  `TauCeti.GlobalNumberFields.mulExact_residueSignRayClass_rayClassToClassGroup`: their
  multiplicative exactness forms.
* `TauCeti.GlobalNumberFields.classMap_eq_one_iff_of_finitePart_eq`: the kernel of a transition
  map between moduli with the same finite part consists of the classes of sign patterns trivial at
  the real places of the smaller modulus.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
* S. Lang, *Algebraic Number Theory*, Chapter VI, §1.
-/

public section

open IsDedekindDomain NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.GlobalNumberFields

variable {K : Type*} [Field K] [NumberField K]

/-- The ray class of the principal ideal generated by an element that is a unit at every prime
dividing the finite part of `m`. -/
noncomputable def principalRayClass (m : Modulus K) :
    primeToSubgroup m →* RayClassGroup m :=
  (rayClassMk m).comp (principalIdealPrimeTo m)

/-- The principal ray class is represented by the corresponding principal fractional ideal. -/
@[simp] theorem principalRayClass_apply (m : Modulus K) (x : primeToSubgroup m) :
    principalRayClass m x = rayClassMk m (principalIdealPrimeTo m x) :=
  (rfl)

/-- A generator congruent to one modulo `m` has trivial principal ray class. -/
theorem principalRayClass_eq_one_of_isCongrOne {m : Modulus K} {x : primeToSubgroup m}
    (hx : IsCongrOne m (x : Kˣ)) : principalRayClass m x = 1 := by
  rw [principalRayClass_apply, rayClassMk_eq_one_iff, mem_ray_iff]
  exact ⟨(x : Kˣ), hx, coe_principalIdealPrimeTo m x |>.symm⟩

/-- The map from a ray class to its underlying ordinary ideal class. -/
noncomputable def rayClassToClassGroup (m : Modulus K) :
    RayClassGroup m →* ClassGroup (RingOfIntegers K) :=
  rayClassLift (idealsPrimeToClassGroup m) fun I hI ↦ by
    rw [MonoidHom.mem_ker]
    obtain ⟨x, _, hx⟩ := mem_ray_iff.mp hI
    rw [idealsPrimeToClassGroup_apply, ← hx]
    exact ClassGroup.mk_toPrincipalIdeal x

/-- The ordinary class underlying the ray class of a fractional ideal is its usual ideal class. -/
@[simp] theorem rayClassToClassGroup_rayClassMk (m : Modulus K) (I : idealsPrimeTo m) :
    rayClassToClassGroup m (rayClassMk m I) =
      ClassGroup.mk K (I : (FractionalIdeal (RingOfIntegers K)⁰ K)ˣ) := by
  rw [rayClassToClassGroup, rayClassLift_rayClassMk, idealsPrimeToClassGroup_apply]

/-- Forgetting the modulus agrees with transition to the trivial modulus followed by the canonical
identification of its ray class group with the ordinary class group. -/
theorem rayClassToClassGroup_eq_oneEquivClassGroup_comp_classMap (m : Modulus K) :
    rayClassToClassGroup m =
      oneEquivClassGroup.toMonoidHom.comp (classMap (Modulus.one_dvd m)) := by
  refine MonoidHom.ext fun c ↦ ?_
  obtain ⟨I, rfl⟩ := rayClassMk_surjective m c
  rw [rayClassToClassGroup_rayClassMk, MonoidHom.comp_apply, classMap_rayClassMk,
    MulEquiv.coe_toMonoidHom, oneEquivClassGroup_rayClassMk,
    NumberFieldArithmetic.coe_idealsAwayInclusion]

/-- Transition from a larger modulus to any divisor is surjective. -/
theorem classMap_surjective {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) :
    Function.Surjective (classMap h) := by
  classical
  intro c
  obtain ⟨I, rfl⟩ := rayClassMk_surjective 𝔪 c
  choose p hp using fun v : HeightOneSpectrum (RingOfIntegers K) ↦
    v.valuation_surjective K
      (WithZero.exp (FractionalIdeal.count K v I.1.1))
  let a : HeightOneSpectrum (RingOfIntegers K) → K := fun v ↦
    if v ∈ 𝔪.support then 1 else p v
  let γ := fun v : HeightOneSpectrum (RingOfIntegers K) ↦
    if v ∈ 𝔪.support then WithZero.exp (-(𝔪.exponent v : ℤ))
    else WithZero.exp (FractionalIdeal.count K v I.1.1)
  obtain ⟨x, hx, hsign⟩ := exists_fieldUnit_valuation_sub_lt_and_signHom_eq
    (S := 𝔫.support) a γ (fun v _ ↦ by
      dsimp [γ]
      split <;> exact WithZero.exp_ne_zero) 1
  have hxm : IsCongrOne 𝔪 x := by
    rw [isCongrOne_iff]
    refine ⟨fun v hv ↦ ?_, fun w _ ↦ ?_⟩
    · have hvm : v ∈ 𝔪.support := (Modulus.mem_support_iff 𝔪 v).mpr hv
      simpa only [a, γ, ite_eq_left hvm] using
        (hx v (Modulus.support_mono h hvm)).le
    · rw [← signHom_apply_eq_one_iff x w, hsign]
      rfl
  let J : idealsPrimeTo 𝔫 := ⟨I.1 * toPrincipalIdeal (RingOfIntegers K) K x,
    NumberFieldArithmetic.mem_idealsAway_iff.mpr (by
    intro v hv
    rw [Units.val_mul, FractionalIdeal.count_mul K v (Units.ne_zero I)
      (Units.ne_zero (toPrincipalIdeal (RingOfIntegers K) K x)),
      FractionalIdeal.count_toPrincipalIdeal_eq_neg_log_valuation]
    by_cases hvm : v ∈ 𝔪.support
    · rw [NumberFieldArithmetic.mem_idealsAway_iff.mp I.2 v hvm,
        hxm.valuation_eq_one ((Modulus.mem_support_iff 𝔪 v).mp hvm)]
      simp
    · have hval : v.valuation K (x : K) = WithZero.exp
          (FractionalIdeal.count K v I.1.1) := by
        calc
          v.valuation K (x : K) = v.valuation K (p v) :=
            Valuation.map_eq_of_sub_lt _ (by
              have hlt := hx v hv
              simp only [a, γ, ite_eq_right hvm] at hlt
              rw [hp v]
              exact hlt)
          _ = _ := hp v
      rw [hval, WithZero.log_exp]
      ring)⟩
  refine ⟨rayClassMk 𝔫 J, ?_⟩
  rw [classMap_rayClassMk]
  let xm : primeToSubgroup 𝔪 :=
    ⟨x, congruenceSubgroup_le_primeToSubgroup 𝔪 (mem_congruenceSubgroup.mpr hxm)⟩
  have hJ : NumberFieldArithmetic.idealsAwayInclusion (Modulus.support_mono h) J =
      I * principalIdealPrimeTo 𝔪 xm := by
    apply Subtype.ext
    apply Units.ext
    rw [NumberFieldArithmetic.coe_idealsAwayInclusion, Subgroup.coe_mul,
      coe_principalIdealPrimeTo]
  rw [hJ, map_mul]
  rw [← principalRayClass_apply, principalRayClass_eq_one_of_isCongrOne hxm, mul_one]

/-- Every ordinary ideal class is represented by a ray class. -/
theorem rayClassToClassGroup_surjective (m : Modulus K) :
    Function.Surjective (rayClassToClassGroup m) := by
  rw [rayClassToClassGroup_eq_oneEquivClassGroup_comp_classMap]
  exact oneEquivClassGroup.surjective.comp (classMap_surjective (Modulus.one_dvd m))

/-- The ray classes with trivial ordinary ideal class are exactly the principal ray classes.  This
is exactness at `RayClassGroup m` in the ray-class exact sequence. -/
theorem ker_rayClassToClassGroup (m : Modulus K) :
    (rayClassToClassGroup m).ker = (principalRayClass m).range := by
  rw [rayClassToClassGroup, ker_rayClassLift, ← range_principalIdealPrimeTo,
    principalRayClass, MonoidHom.range_comp]

/-- The principal-ray-class map followed by forgetting the modulus is exact. -/
theorem mulExact_principalRayClass_rayClassToClassGroup (m : Modulus K) :
    Function.MulExact (principalRayClass m) (rayClassToClassGroup m) :=
  MonoidHom.mulExact_iff.mpr (ker_rayClassToClassGroup m)

/-! ### The residue-and-sign presentation of the exact sequence -/

/-- **A principal ray class is trivial exactly when a unit multiple of the generator is congruent
to one.**  Two generators of the same principal fractional ideal differ by a unit of `𝓞 K`, so the
ray only sees an element of `primeToSubgroup 𝔪` up to the integer units. -/
theorem principalRayClass_eq_one_iff {𝔪 : Modulus K} (x : primeToSubgroup 𝔪) :
    principalRayClass 𝔪 x = 1 ↔
      ∃ u : (𝓞 K)ˣ, IsCongrOne 𝔪 (Units.map (algebraMap (𝓞 K) K).toMonoidHom u * x) := by
  rw [principalRayClass_apply, rayClassMk_eq_one_iff, mem_ray_iff, coe_principalIdealPrimeTo]
  refine ⟨fun ⟨y, hy, hyx⟩ ↦ ?_, fun ⟨u, hu⟩ ↦ ⟨_, hu, ?_⟩⟩
  · obtain ⟨u, hu⟩ := (FractionalIdeal.toPrincipalIdeal_eq_one_iff (y * (x : Kˣ)⁻¹)).mp
      (by rw [map_mul, map_inv, hyx, mul_inv_cancel])
    refine ⟨u, ?_⟩
    have hu' : Units.map (algebraMap (𝓞 K) K).toMonoidHom u = y * (x : Kˣ)⁻¹ := hu
    rwa [hu', inv_mul_cancel_right]
  · have hu1 : toPrincipalIdeal (𝓞 K) K (Units.map (algebraMap (𝓞 K) K).toMonoidHom u) = 1 :=
      (FractionalIdeal.toPrincipalIdeal_eq_one_iff _).mpr ⟨u, rfl⟩
    rw [map_mul, hu1, one_mul]

/-- **The residues and signs of the integer units.**  This is the left-hand map of the ray class
exact sequence; its image is the obstruction that is divided out of the residue units and signs
before they embed into the ray class group. -/
noncomputable def unitsResidueSignHom (𝔪 : Modulus K) :
    (𝓞 K)ˣ →* (𝓞 K ⧸ 𝔪.finitePart)ˣ × (𝔪.infinitePart → ℤˣ) :=
  (residueSignHom 𝔪).comp (unitsToPrimeToSubgroup 𝔪)

@[simp] theorem unitsResidueSignHom_apply (𝔪 : Modulus K) (u : (𝓞 K)ˣ) :
    unitsResidueSignHom 𝔪 u = residueSignHom 𝔪 (unitsToPrimeToSubgroup 𝔪 u) := (rfl)

/-- **Exactness at the integer units**: a unit has trivial residue and trivial signs exactly when
it is congruent to one modulo `𝔪`. -/
theorem ker_unitsResidueSignHom (𝔪 : Modulus K) :
    (unitsResidueSignHom 𝔪).ker = unitsCongruenceSubgroup 𝔪 := by
  ext u
  rw [MonoidHom.mem_ker, unitsResidueSignHom_apply, residueSignHom_eq_one_iff,
    coe_unitsToPrimeToSubgroup, mem_unitsCongruenceSubgroup, mem_congruenceSubgroup]

/-- Exactness at the integer units, as a `Function.MulExact` statement. -/
theorem mulExact_unitsCongruenceSubgroup_unitsResidueSignHom (𝔪 : Modulus K) :
    Function.MulExact (unitsCongruenceSubgroup 𝔪).subtype (unitsResidueSignHom 𝔪) :=
  MonoidHom.mulExact_iff.mpr <| by rw [Subgroup.range_subtype, ker_unitsResidueSignHom]

/-- **The principal ray class of a residue unit and a sign pattern.**  The principal ray class of
an element prime to `𝔪` depends only on its residue modulo the finite part and its signs at the
real places of `𝔪`, and every residue unit and sign pattern arises (`residueSignEquiv`); this is
the induced homomorphism. -/
noncomputable def residueSignRayClass (𝔪 : Modulus K) :
    (𝓞 K ⧸ 𝔪.finitePart)ˣ × (𝔪.infinitePart → ℤˣ) →* RayClassGroup 𝔪 :=
  (QuotientGroup.lift _ (principalRayClass 𝔪) fun _ hx ↦ MonoidHom.mem_ker.mpr <|
      principalRayClass_eq_one_of_isCongrOne
        (mem_congruenceSubgroup.mp (Subgroup.mem_subgroupOf.mp hx))).comp
    (residueSignEquiv 𝔪).symm.toMonoidHom

/-- The class attached to the residue and signs of an element is its principal ray class. -/
@[simp] theorem residueSignRayClass_residueSignHom (𝔪 : Modulus K) (x : primeToSubgroup 𝔪) :
    residueSignRayClass 𝔪 (residueSignHom 𝔪 x) = principalRayClass 𝔪 x := by
  rw [residueSignRayClass, MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom,
    (residueSignEquiv 𝔪).symm_apply_eq.mpr (residueSignEquiv_apply_mk 𝔪 x).symm,
    QuotientGroup.lift_mk]

/-- `residueSignRayClass 𝔪` is the factorization of `principalRayClass 𝔪` through the surjection
`residueSignHom 𝔪`. -/
theorem residueSignRayClass_comp_residueSignHom (𝔪 : Modulus K) :
    (residueSignRayClass 𝔪).comp (residueSignHom 𝔪) = principalRayClass 𝔪 :=
  MonoidHom.ext (residueSignRayClass_residueSignHom 𝔪)

/-- **Exactness at the residue units and signs**: a residue unit and sign pattern has trivial ray
class exactly when it is the residue and sign pattern of an integer unit. -/
theorem ker_residueSignRayClass (𝔪 : Modulus K) :
    (residueSignRayClass 𝔪).ker = (unitsResidueSignHom 𝔪).range := by
  ext a
  obtain ⟨x, rfl⟩ := residueSignHom_surjective 𝔪 a
  rw [MonoidHom.mem_ker, residueSignRayClass_residueSignHom, principalRayClass_eq_one_iff,
    MonoidHom.mem_range]
  refine ⟨fun ⟨u, hu⟩ ↦ ⟨u⁻¹, ?_⟩, fun ⟨u, hu⟩ ↦ ⟨u⁻¹, ?_⟩⟩
  · have h := (residueSignHom_eq_one_iff (unitsToPrimeToSubgroup 𝔪 u * x)).mpr
      (by rwa [Subgroup.coe_mul, coe_unitsToPrimeToSubgroup, mem_congruenceSubgroup])
    rw [map_mul] at h
    rw [unitsResidueSignHom_apply, map_inv, map_inv, inv_eq_of_mul_eq_one_right h]
  · have h : residueSignHom 𝔪 (unitsToPrimeToSubgroup 𝔪 u⁻¹ * x) = 1 := by
      rw [map_mul, map_inv, map_inv, ← unitsResidueSignHom_apply, hu, inv_mul_cancel]
    rwa [residueSignHom_eq_one_iff, Subgroup.coe_mul, coe_unitsToPrimeToSubgroup,
      mem_congruenceSubgroup] at h

/-- **Exactness at the ray class group**: the ray classes with trivial ordinary ideal class are
exactly the classes of residue units and sign patterns. -/
theorem range_residueSignRayClass (𝔪 : Modulus K) :
    (residueSignRayClass 𝔪).range = (rayClassToClassGroup 𝔪).ker := by
  rw [ker_rayClassToClassGroup, ← residueSignRayClass_comp_residueSignHom, MonoidHom.range_comp,
    MonoidHom.range_eq_top.mpr (residueSignHom_surjective 𝔪), ← MonoidHom.range_eq_map]

/-- Exactness at the residue units and signs, as a `Function.MulExact` statement. -/
theorem mulExact_unitsResidueSignHom_residueSignRayClass (𝔪 : Modulus K) :
    Function.MulExact (unitsResidueSignHom 𝔪) (residueSignRayClass 𝔪) :=
  MonoidHom.mulExact_iff.mpr (ker_residueSignRayClass 𝔪)

/-- Exactness at the ray class group, as a `Function.MulExact` statement. -/
theorem mulExact_residueSignRayClass_rayClassToClassGroup (𝔪 : Modulus K) :
    Function.MulExact (residueSignRayClass 𝔪) (rayClassToClassGroup 𝔪) :=
  MonoidHom.mulExact_iff.mpr (range_residueSignRayClass 𝔪).symm

/-- The residue and signs of the unit `-1`: residue `-1` and sign `-1` at every real place of the
modulus. -/
theorem unitsResidueSignHom_neg_one (𝔪 : Modulus K) :
    unitsResidueSignHom 𝔪 (-1) = (-1, fun _ ↦ -1) := by
  rw [unitsResidueSignHom_apply]
  refine Prod.ext ?_ (funext fun w ↦ ?_)
  · rw [residueSignHom_fst]
    refine Units.ext ?_
    rw [coe_residueHom, Units.val_neg, Units.val_one,
      residue_eq _ (a := -1) (b := 1) (by simp) (by simp [coe_unitsToPrimeToSubgroup]), map_neg,
      map_one]
  · rw [residueSignHom_snd, modulusSignHom_apply, signHom_apply_eq_neg_one_iff,
      coe_unitsToPrimeToSubgroup]
    simp

/-! ### Transition maps that only forget real places -/

/-- **The kernel of a transition map between moduli with the same finite part consists of sign
classes.**  When `𝔪 ∣ 𝔫` have the same finite part, a ray class of `𝔫` is killed by
`classMap : Cl_𝔫 → Cl_𝔪` exactly when it is the class `residueSignRayClass 𝔫 (1, s)` of the trivial
residue together with a pattern of signs `s` that is trivial at the real places of `𝔪`. -/
theorem classMap_eq_one_iff_of_finitePart_eq {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫)
    (hfin : 𝔪.finitePart = 𝔫.finitePart) (c : RayClassGroup 𝔫) :
    classMap h c = 1 ↔ ∃ s : 𝔫.infinitePart → ℤˣ,
      (∀ w : 𝔫.infinitePart, w.1 ∈ 𝔪.infinitePart → s w = 1) ∧
        residueSignRayClass 𝔫 (1, s) = c := by
  constructor
  · intro hc
    obtain ⟨I, rfl⟩ := rayClassMk_surjective 𝔫 c
    rw [classMap_rayClassMk, rayClassMk_eq_one_iff, mem_ray_iff] at hc
    obtain ⟨x, hx, hxI⟩ := hc
    rw [NumberFieldArithmetic.coe_idealsAwayInclusion] at hxI
    have hxn : x ∈ primeToSubgroup 𝔫 := by
      refine mem_primeToSubgroup.mpr fun v hv ↦ hx.valuation_eq_one ?_
      rwa [hfin]
    obtain ⟨hres, hpos⟩ := (isCongrOne_iff_residueHom_eq_one_of_finitePart_eq hfin hxn).mp hx
    refine ⟨modulusSignHom 𝔫 x, fun w hw ↦ ?_, ?_⟩
    · rw [modulusSignHom_apply, signHom_apply_eq_one_iff]
      exact hpos w.1 hw
    · have hI : principalIdealPrimeTo 𝔫 ⟨x, hxn⟩ = I :=
        Subtype.ext (Units.ext (by rw [coe_principalIdealPrimeTo, hxI]))
      rw [← hI, ← principalRayClass_apply, ← residueSignRayClass_residueSignHom]
      exact congrArg _ (Prod.ext (by rw [residueSignHom_fst, hres]) (by rw [residueSignHom_snd]))
  · rintro ⟨s, hs, rfl⟩
    obtain ⟨x, hx⟩ := residueSignHom_surjective 𝔫 (1, s)
    rw [← hx, residueSignRayClass_residueSignHom, principalRayClass_apply, classMap_rayClassMk,
      rayClassMk_eq_one_iff, mem_ray_iff]
    refine ⟨x, ?_, by rw [NumberFieldArithmetic.coe_idealsAwayInclusion, coe_principalIdealPrimeTo]⟩
    refine (isCongrOne_iff_residueHom_eq_one_of_finitePart_eq hfin x.2).mpr
      ⟨by rw [← residueSignHom_fst, hx], fun w hw ↦ ?_⟩
    have hw' := congrArg (fun p ↦ p.2 ⟨w, (Modulus.dvd_iff.mp h).2 hw⟩) hx
    simp only [residueSignHom_snd, modulusSignHom_apply] at hw'
    rw [← signHom_apply_eq_one_iff, hw']
    exact hs _ hw

end TauCeti.GlobalNumberFields
