/-
Based on Prove2Me node MTT.Cohomology.parabolicH1_finrank_le_levels_two_three_four
(bea24174-e8da-4307-b16f-7f45c945f7dc) by cbirkbeck (2026-09-07).

Proof based on Prove2Me submission 3dc7f114-d709-4d57-b254-abdfa1ff4034
by cbirkbeck (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_ParabolicCohomology
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs

import Theorems.MTT.Thm_MTT_Cohomology_parabolicH1_finrank_le_level_two
import Theorems.MTT.Thm_MTT_Cohomology_parabolicH1_finrank_le_levels_three_four

/-!
# MTT parabolic dimension bound at levels two, three and four

Theorem statement: `MTT.Cohomology.parabolicH1_finrank_le_levels_two_three_four`
(`bea24174-e8da-4307-b16f-7f45c945f7dc`), by cbirkbeck, 2026-09-07.

Proof: submission `3dc7f114-d709-4d57-b254-abdfa1ff4034`, by cbirkbeck, 2026-09-08 (ACCEPTED);
locally adapted.

Let $N\in\{2,3,4\}$ and let $k\ge3$ be a natural number. Then

$$\dim_{\mathbb C}H^1_{\mathrm{par}}(\Gamma_1(N),\mathrm{Sym}^{k-2}\mathbb C^2)\le 2\dim_{\mathbb
C}S_k(\Gamma_1(N)).$$

This isolates the exceptional small levels, where elliptic or irregular-cusp corrections prevent
using the uncorrected N>=5 dimension formula. The assertion remains OPEN and covers odd as well as
even weights.

## Explanation of the source proof

# The level-two case is now discharged

The new closed proof of the level-two bound is theorem
`999c64a3-e1a5-4178-bb53-cb968039bd2d`. It identifies Gamma1(2) with Gamma0(2),
constructs the injective comparison of the two parabolic cohomology models, and
uses the already-Proved Gamma0 Eichler–Shimura decomposition. It applies to all
weights at least two and introduces no assumption on the remaining small levels.

For the present parent, split according to whether N=2. That case is supplied
by the closed proof. Since 2<=N<=4, the other case is precisely N=3 or N=4,
now isolated as child `36b8715f-dd40-4647-a91c-af4224ece24c`. Thus no weight-two,
level-one, or level-two work remains in this branch.

The remaining child is genuinely open: neither the elliptic correction at
level three nor the irregular-cusp behavior in odd weight at level four is
discarded. The intended continuation is the corresponding parabolic cocycle
dimension count and matching cusp-form dimension estimate, or a source-faithful
comparison with an existing coefficient-cohomology theorem. This sketch claims
only the checked case reduction, not a proof of those remaining cases.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

/-! # Removing the proved level-two case from the small-level frontier -/

theorem solution {N k : ℕ} (hN : 2 ≤ N) (hN' : N ≤ 4) (hk : 3 ≤ k) :
    Module.finrank ℂ (MTT.Cohomology.ParabolicH1 N (k - 2)) ≤
      2 * Module.finrank ℂ (CuspForm (MTT.GammaOne N) (k : ℤ)) := by
  by_cases h₂ : N = 2
  · subst N
    exact MTT.Cohomology.parabolicH1_finrank_le_level_two (by omega)
  · exact MTT.Cohomology.parabolicH1_finrank_le_levels_three_four (by omega) hN' hk

end privateSection

public section publicSection

theorem MTT.Cohomology.parabolicH1_finrank_le_levels_two_three_four {N k : ℕ}
    (hN : 2 ≤ N) (hN' : N ≤ 4) (hk : 3 ≤ k) :
    Module.finrank ℂ (MTT.Cohomology.ParabolicH1 N (k - 2)) ≤
      2 * Module.finrank ℂ (CuspForm (MTT.GammaOne N) (k : ℤ)) := _root_.solution hN hN' hk

end publicSection
