/-
Based on Prove2Me node MTT.Cohomology.parabolicH1_finrank_le_levels_three_four
(36b8715f-dd40-4647-a91c-af4224ece24c) by cbirkbeck (2026-09-08).

Proof based on Prove2Me submission 633802b8-f3ab-4398-8f88-1ce7f23f465e
by cbirkbeck (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_ParabolicCohomology
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs

import Theorems.MTT.Thm_MTT_Cohomology_parabolicH1_finrank_le_levels_three_four_even
import Theorems.MTT.Thm_MTT_Cohomology_parabolicH1_finrank_le_levels_three_four_odd

/-!
# MTT parabolic cohomology dimension bound at levels three and four

Theorem statement: `MTT.Cohomology.parabolicH1_finrank_le_levels_three_four`
(`36b8715f-dd40-4647-a91c-af4224ece24c`), by cbirkbeck, 2026-09-08.

Proof: submission `633802b8-f3ab-4398-8f88-1ce7f23f465e`, by cbirkbeck, 2026-09-08 (ACCEPTED);
locally adapted.

Let $N\in\{3,4\}$ and $k\ge3$. Then $$\dim_{\mathbb
C}H^1_{\mathrm{par}}(\Gamma_1(N),\operatorname{Sym}^{k-2}\mathbb C^2)\le 2\dim_{\mathbb
C}S_k(\Gamma_1(N)).$$ Here coefficients are homogeneous binary polynomials with the substitution
action; parabolic cocycles restrict to principal cocycles on all rational-cusp stabilizers, and
cohomology is taken modulo principal cocycles. This is the Eichler–Shimura dimension upper bound in
the two remaining small levels, including odd weights. These levels require their actual elliptic
and irregular-cusp corrections, not the torsion-free large-level dimension formula.

## Explanation of the source proof

# Separate the parity cases at levels three and four

Every natural weight is even or odd. The even-weight bound is supplied by
the verified comparison with Gamma0: adjoining the disjoint central sign
does not change the even-degree coefficient action, so extending cocycles
and then restricting cusp forms gives the dimension inequality.

The odd-weight case remains a separate open input. The Gamma0 argument does
not apply there because the center acts nontrivially, and the large-level
dimension formula does not cover levels three and four. This reduction
connects the proved even-weight result and retains exactly the odd-weight
case as the remaining small-level frontier dependency.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

theorem solution {N k : ℕ} (hN : 3 ≤ N) (hN' : N ≤ 4) (hk : 3 ≤ k) :
    Module.finrank ℂ (MTT.Cohomology.ParabolicH1 N (k - 2)) ≤
      2 * Module.finrank ℂ (CuspForm (MTT.GammaOne N) (k : ℤ)) := by
  rcases Nat.even_or_odd k with hke | hko
  · exact MTT.Cohomology.parabolicH1_finrank_le_levels_three_four_even hN hN' hk hke
  · exact MTT.Cohomology.parabolicH1_finrank_le_levels_three_four_odd hN hN' hk hko

end privateSection

public section publicSection

theorem MTT.Cohomology.parabolicH1_finrank_le_levels_three_four {N k : ℕ}
    (hN : 3 ≤ N) (hN' : N ≤ 4) (hk : 3 ≤ k) :
    Module.finrank ℂ (MTT.Cohomology.ParabolicH1 N (k - 2)) ≤
      2 * Module.finrank ℂ (CuspForm (MTT.GammaOne N) (k : ℤ)) := _root_.solution hN hN' hk

end publicSection
