/-
Based on Prove2Me node MTT.Cohomology.manin_generation_span
(17e6a675-dc2d-4c9c-9962-6c5c0b6b3fd2) by allychan327 (2026-09-07).

Proof based on Prove2Me submission eb93a50f-aa22-4535-bb81-6c09b0d0e8d3
by allychan327 (2026-09-07); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_Cohomology
public import Mathlib.RingTheory.Flat.Basic

/-!
# Manin's unimodular paths span: every value of a modular symbol is an integral combination of its values on unimodular paths

Theorem statement: `MTT.Cohomology.manin_generation_span` (`17e6a675-dc2d-4c9c-9962-6c5c0b6b3fd2`),
by allychan327, 2026-09-07.

Proof: submission `eb93a50f-aa22-4535-bb81-6c09b0d0e8d3`, by allychan327, 2026-09-07 (ACCEPTED);
locally adapted.

Manin's unimodular-path theorem, in the form that is actually used when one needs to *produce*
elements rather than merely detect them.

Let $\Gamma \subseteq \mathrm{SL}_2(\mathbf Z)$ and let $\mathrm{Div}^0(\mathbf P^1(\mathbf Q))$ be
the group of degree-zero divisors on the cusps, with $(x,y)$ denoting $[x]-[y]$. A **unimodular
path** is a divisor of the form $g \cdot ([0]-[\infty])$ with $g \in \mathrm{SL}_2(\mathbf Z)$, i.e.
a path joining $g\cdot 0$ to $g\cdot\infty$; equivalently, a path between two cusps $a/c$ and $b/d$
with $ad-bc=\pm 1$. Manin's continued-fraction trick shows that these generate
$\mathrm{Div}^0(\mathbf P^1(\mathbf Q))$ as an abelian group: writing $r = p_m/q_m$ as the last
convergent of its continued fraction expansion, the successive convergents $p_{i-1}/q_{i-1}$ and
$p_i/q_i$ satisfy $p_iq_{i-1}-p_{i-1}q_i = \pm 1$, so the path from $\infty$ to $r$ telescopes into
finitely many unimodular pieces.

The statement here is the consequence of that for a modular symbol. If
$$\varphi \in \mathrm{Hom}_\Gamma\big(\mathrm{Div}^0(\mathbf P^1(\mathbf Q)),\
\mathrm{Sym}^n(R^2)\big)$$
then applying $\varphi$ to such a decomposition expresses **every** value $\varphi(x,y)$ as a
$\mathbf Z$-linear combination of the values of $\varphi$ on unimodular paths:
$$\varphi(x,y) \in \Big\langle\ \varphi\big(g\cdot 0,\ g\cdot\infty\big)\ :\ g \in
\mathrm{SL}_2(\mathbf Z)\ \Big\rangle_{\mathbf Z}.$$

Note that the subgroup on the right is generated by the values of the *same* $\varphi$, so no
auxiliary object appears in the statement, and no equivariance is used in it — the equivariance of
$\varphi$ enters only in the proof, and only through $\mathrm{Div}^0$.

**Relation to the vanishing form.** This statement strictly implies
`MTT.Cohomology.manin_generation` (if all the generators vanish, the subgroup is trivial and
$\varphi = 0$), but it is genuinely stronger, and the difference matters. The vanishing form says
only that a class is *determined* by its unimodular values; it gives an injection into a
finite-dimensional coordinate space but says nothing about which coefficients actually occur. The
spanning form says the values are *built from* the unimodular values, which is what lets one bound
the subgroup of $R$ generated by all coefficients of all values of a single class — a finiteness
statement no injectivity result can supply, and the input to flat base change.

## Explanation of the source proof

Manin's unimodular-path theorem, by Euclidean descent on the denominator. The proof is
elementary and finite: no continued fractions, no geometry of the modular curve, and — perhaps
surprisingly — **no use of the $\Gamma$-equivariance of $\varphi$**. Only the cocycle relation is
used, so the statement holds for any $\varphi$ satisfying it.

## Reduction to paths out of infinity

Let $H \le \mathrm{Sym}^n(R^2)$ be the subgroup generated by the values
$\varphi(g\cdot 0,\ g\cdot\infty)$, $g\in\mathrm{SL}_2(\mathbf Z)$. The cocycle relation gives
$\varphi(x,x)=0$ (`diag_zero`) and hence
$$\varphi(x,y)=\varphi(\infty,y)-\varphi(\infty,x)$$
(`val_sub`), so it suffices to show $\varphi(\infty,z)\in H$ for every cusp $z$. For $z=\infty$
this is $0$, and $\mathbf P^1(\mathbf Q)=\mathbf Q\cup\{\infty\}$, so only $z=r\in\mathbf Q$
remains. Writing $r = p/q$ with $q = \mathrm{den}(r) > 0$ and $\gcd(p,q)=1$
(`Rat.num_div_den`), everything reduces to:

> for all $q \ge 1$ and $p$ with $\gcd(p,q)=1$: $\varphi(\infty, p/q) \in H$.

## The descent

Strong induction on $q$ (`main`).

*Base $q=1$.* The matrix $\begin{pmatrix}1&p\\0&1\end{pmatrix}$ has determinant $1$, sends
$\infty\mapsto\infty$ and $0\mapsto p$, so $\varphi(p,\infty)$ is a generator; then
$\varphi(\infty,p) = -\varphi(p,\infty)\in H$ (`int_path_mem`).

*Step $q\ge 2$.* Since $\gcd(p,q)=1$, Bézout gives $s,t$ with $ps+qt=1$. Put
$q' = s \bmod q \in [0,q)$ and $p' = -t - p\lfloor s/q\rfloor$; a one-line computation using
$s \bmod q = s - q\lfloor s/q\rfloor$ gives
$$p\,q' - p'\,q \;=\; ps + qt \;=\; 1 .$$
Then $q'\ne 0$: otherwise $q \mid 1$, contradicting $q\ge2$. And $\gcd(p',q')=1$, because
$(-q)p' + p\,q' = 1$ is a Bézout relation for the pair $(p',q')$ — this is the same identity
read the other way. So $1 \le q' < q$ and the inductive hypothesis applies to $p'/q'$.

Finally the matrix $\begin{pmatrix}p&p'\\q&q'\end{pmatrix}$ has determinant $1$; it sends
$\infty\mapsto p/q$ and $0\mapsto p'/q'$, so $\varphi(p'/q',\,p/q)$ is a generator
(`path_mem`). The cocycle relation
$$\varphi(\infty,\ p/q) \;=\; \varphi(\infty,\ p'/q') \;+\; \varphi(p'/q',\ p/q)$$
exhibits the left side as a sum of an element supplied by induction and a generator.

## Formalization notes

The only real friction is computing the Möbius action on $\mathbf P^1(\mathbf Q)$, which in this
environment is the `OnePoint` compactification acting through
`Matrix.SpecialLinearGroup.mapGL`. The lemma `ent`, that the $(i,j)$ entry of the image of an
integral matrix in $\mathrm{GL}_2(\mathbf Q)$ is the cast of the $(i,j)$ entry, holds by `rfl`;
with it, `OnePoint.smul_infty_eq_ite` and `OnePoint.smul_some_eq_ite` evaluate
$g\cdot\infty = a/c$ and $g\cdot 0 = b/d$ (`cuspAct_infty`, `cuspAct_zero`), with the degenerate
case $c=0$, needed for the base of the induction, handled separately (`cuspAct_infty_of_zero`).

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 1000000
noncomputable section
open scoped BigOperators TensorProduct
open MTT.Cohomology

namespace P2MMGS

variable {N n : ℕ} {R : Type*} [CommRing R]

/-! ### Explicit unimodular matrices and their action on the two base cusps -/

def mk2 (a b c d : ℤ) (h : a * d - b * c = 1) : Matrix.SpecialLinearGroup (Fin 2) ℤ :=
  ⟨!![a, b; c, d], by simp [Matrix.det_fin_two_of]; linarith⟩

theorem ent (g : Matrix.SpecialLinearGroup (Fin 2) ℤ) (i j : Fin 2) :
    ((Matrix.SpecialLinearGroup.mapGL ℚ g : Matrix.GeneralLinearGroup (Fin 2) ℚ) :
      Matrix (Fin 2) (Fin 2) ℚ) i j = ((g.val i j : ℤ) : ℚ) := rfl

theorem e00 (a b c d : ℤ) (h : a * d - b * c = 1) : ((mk2 a b c d h).val 0 0 : ℤ) = a := rfl
theorem e01 (a b c d : ℤ) (h : a * d - b * c = 1) : ((mk2 a b c d h).val 0 1 : ℤ) = b := rfl
theorem e10 (a b c d : ℤ) (h : a * d - b * c = 1) : ((mk2 a b c d h).val 1 0 : ℤ) = c := rfl
theorem e11 (a b c d : ℤ) (h : a * d - b * c = 1) : ((mk2 a b c d h).val 1 1 : ℤ) = d := rfl

theorem cuspAct_infty (a b c d : ℤ) (h : a * d - b * c = 1) (hc : (c : ℚ) ≠ 0) :
    cuspAct (mk2 a b c d h) OnePoint.infty = (((a : ℚ) / (c : ℚ) : ℚ) : Cusp) := by
  rw [cuspAct, OnePoint.smul_infty_eq_ite]
  simp only [ent, e00, e10]
  simp [hc]

theorem cuspAct_infty_of_zero (a b d : ℤ) (h : a * d - b * 0 = 1) :
    cuspAct (mk2 a b 0 d h) OnePoint.infty = OnePoint.infty := by
  rw [cuspAct, OnePoint.smul_infty_eq_ite]
  simp only [ent, e10]
  simp

theorem cuspAct_zero (a b c d : ℤ) (h : a * d - b * c = 1) (hd : (d : ℚ) ≠ 0) :
    cuspAct (mk2 a b c d h) ((0 : ℚ) : Cusp) = (((b : ℚ) / (d : ℚ) : ℚ) : Cusp) := by
  rw [cuspAct, OnePoint.smul_some_eq_ite]
  simp only [ent, e00, e01, e10, e11]
  simp [hd]

/-! ### The subgroup generated by the unimodular values -/

def Gens (φ : Hc N n R) : Set (Binary R) :=
  Set.range fun g : Matrix.SpecialLinearGroup (Fin 2) ℤ =>
    φ.val (cuspAct g ((0 : ℚ) : Cusp), cuspAct g OnePoint.infty)

theorem gen_mem (φ : Hc N n R) (g : Matrix.SpecialLinearGroup (Fin 2) ℤ) :
    φ.val (cuspAct g ((0 : ℚ) : Cusp), cuspAct g OnePoint.infty)
      ∈ AddSubgroup.closure (Gens φ) :=
  AddSubgroup.subset_closure ⟨g, rfl⟩

theorem diag_zero (φ : Hc N n R) (x : Cusp) : φ.val (x, x) = 0 := by
  have h := φ.2.2.1 x x x
  have h2 : φ.val (x, x) + φ.val (x, x) - φ.val (x, x) = 0 := by rw [h]; simp
  simpa using h2

theorem val_sub (φ : Hc N n R) (c a b : Cusp) :
    φ.val (a, b) = φ.val (c, b) - φ.val (c, a) := by
  have h := φ.2.2.1 c a b
  rw [← h]; ring

/-- The value on the unimodular path joining `b/d` to `a/c`. -/
theorem path_mem (φ : Hc N n R) (a b c d : ℤ) (h : a * d - b * c = 1)
    (hc : (c : ℚ) ≠ 0) (hd : (d : ℚ) ≠ 0) :
    φ.val ((((b : ℚ) / (d : ℚ) : ℚ) : Cusp), (((a : ℚ) / (c : ℚ) : ℚ) : Cusp))
      ∈ AddSubgroup.closure (Gens φ) := by
  have hg := gen_mem φ (mk2 a b c d h)
  rwa [cuspAct_zero a b c d h hd, cuspAct_infty a b c d h hc] at hg

/-- The path from infinity to an integer. -/
theorem int_path_mem (φ : Hc N n R) (p : ℤ) :
    φ.val (OnePoint.infty, (((p : ℚ) / ((1 : ℕ) : ℚ) : ℚ) : Cusp))
      ∈ AddSubgroup.closure (Gens φ) := by
  have hdet : (1 : ℤ) * 1 - p * 0 = 1 := by ring
  have hg := gen_mem φ (mk2 1 p 0 1 hdet)
  rw [cuspAct_zero 1 p 0 1 hdet (by norm_num), cuspAct_infty_of_zero] at hg
  have hsplit := φ.2.2.1 OnePoint.infty (((p : ℚ) / ((1 : ℤ) : ℚ) : ℚ) : Cusp) OnePoint.infty
  rw [diag_zero] at hsplit
  have hval : φ.val (OnePoint.infty, (((p : ℚ) / ((1 : ℤ) : ℚ) : ℚ) : Cusp))
      = -φ.val ((((p : ℚ) / ((1 : ℤ) : ℚ) : ℚ) : Cusp), OnePoint.infty) := by
    rw [eq_neg_iff_add_eq_zero, hsplit]
  have hcast : (((1 : ℕ) : ℚ)) = (((1 : ℤ) : ℚ)) := by norm_num
  rw [hcast, hval]
  exact neg_mem hg

/-! ### Euclidean descent -/

theorem main (φ : Hc N n R) : ∀ d : ℕ, ∀ p : ℤ, 0 < d → Int.gcd p (d : ℤ) = 1 →
    φ.val (OnePoint.infty, (((p : ℚ) / (d : ℚ) : ℚ) : Cusp))
      ∈ AddSubgroup.closure (Gens φ) := by
  intro d
  induction d using Nat.strong_induction_on with
  | _ d ih =>
    intro p hd hgcd
    rcases eq_or_lt_of_le (Nat.one_le_iff_ne_zero.mpr hd.ne') with h1 | h1
    · subst h1
      exact int_path_mem φ p
    · obtain ⟨q', p', hq'0, hq'd, hdet⟩ :
          ∃ q' p' : ℤ, 0 ≤ q' ∧ q' < (d : ℤ) ∧ p * q' - p' * (d : ℤ) = 1 := by
        refine ⟨Int.gcdA p (d : ℤ) % (d : ℤ),
          -(Int.gcdB p (d : ℤ)) - p * (Int.gcdA p (d : ℤ) / (d : ℤ)), ?_, ?_, ?_⟩
        · exact Int.emod_nonneg _ (by exact_mod_cast hd.ne')
        · exact Int.emod_lt_of_pos _ (by exact_mod_cast hd)
        · have hbez : (1 : ℤ) = p * Int.gcdA p (d : ℤ) + (d : ℤ) * Int.gcdB p (d : ℤ) := by
            have hg := Int.gcd_eq_gcd_ab p (d : ℤ)
            rw [hgcd] at hg
            exact_mod_cast hg
          have hq : Int.gcdA p (d : ℤ) % (d : ℤ)
              = Int.gcdA p (d : ℤ) - (d : ℤ) * (Int.gcdA p (d : ℤ) / (d : ℤ)) :=
            Int.emod_def _ _
          rw [hq]
          have hring : p * (Int.gcdA p (d : ℤ) - (d : ℤ) * (Int.gcdA p (d : ℤ) / (d : ℤ)))
              - (-(Int.gcdB p (d : ℤ)) - p * (Int.gcdA p (d : ℤ) / (d : ℤ))) * (d : ℤ)
              = p * Int.gcdA p (d : ℤ) + (d : ℤ) * Int.gcdB p (d : ℤ) := by ring
          rw [hring, ← hbez]
      have hdpos : (0 : ℤ) < (d : ℤ) := by exact_mod_cast hd
      have hq'ne : q' ≠ 0 := by
        rintro rfl
        have hdvd : (d : ℤ) ∣ 1 := ⟨-p', by linarith⟩
        have hle := Int.le_of_dvd one_pos hdvd
        omega
      have hgcd' : Int.gcd p' q' = 1 := by
        rw [← Int.isCoprime_iff_gcd_eq_one]
        exact ⟨-(d : ℤ), p, by linear_combination hdet⟩
      have heq : ((q'.toNat : ℕ) : ℤ) = q' := Int.toNat_of_nonneg hq'0
      have hepos : 0 < q'.toNat := by omega
      have helt : q'.toNat < d := by omega
      have hIH := ih q'.toNat helt p' hepos (by rw [heq]; exact hgcd')
      have hqQ : ((q'.toNat : ℕ) : ℚ) = ((q' : ℤ) : ℚ) := by exact_mod_cast heq
      rw [hqQ] at hIH
      have hq'Q : ((q' : ℤ) : ℚ) ≠ 0 := Int.cast_ne_zero.mpr hq'ne
      have hdQ : (((d : ℕ) : ℤ) : ℚ) ≠ 0 := by
        simpa using (Nat.cast_ne_zero (R := ℚ)).mpr hd.ne'
      have hpath := path_mem φ p p' (d : ℤ) q' hdet hdQ hq'Q
      have hdQ' : (((d : ℕ) : ℤ) : ℚ) = ((d : ℕ) : ℚ) := by push_cast; ring
      rw [hdQ'] at hpath
      have hsplit := φ.2.2.1 OnePoint.infty
        ((((p' : ℚ) / ((q' : ℤ) : ℚ) : ℚ)) : Cusp) (((p : ℚ) / ((d : ℕ) : ℚ) : ℚ) : Cusp)
      rw [← hsplit]
      exact add_mem hIH hpath

end P2MMGS

open P2MMGS in
theorem solution {N n : ℕ} {R : Type*} [CommRing R] (φ : Hc N n R) (x y : Cusp) :
    φ.val (x, y) ∈ AddSubgroup.closure
      (Set.range fun g : Matrix.SpecialLinearGroup (Fin 2) ℤ =>
        φ.val (cuspAct g ((0 : ℚ) : Cusp), cuspAct g OnePoint.infty)) := by
  have hall : ∀ z : Cusp, φ.val (OnePoint.infty, z) ∈ AddSubgroup.closure (Gens φ) := by
    intro z
    induction z using OnePoint.rec with
    | infty => rw [diag_zero]; exact zero_mem _
    | coe r =>
        have hco : Int.gcd r.num (r.den : ℤ) = 1 := by
          simpa [Int.gcd] using r.reduced
        have hm := main φ r.den r.num r.pos hco
        rwa [Rat.num_div_den] at hm
  rw [val_sub φ OnePoint.infty x y]
  exact sub_mem (hall y) (hall x)
end

end privateSection

public section publicSection

noncomputable section
open scoped BigOperators TensorProduct
open MTT.Cohomology

theorem MTT.Cohomology.manin_generation_span
    {N n : ℕ} {R : Type*} [CommRing R] (φ : Hc N n R) (x y : Cusp) :
    φ.val (x, y) ∈ AddSubgroup.closure
      (Set.range fun g : Matrix.SpecialLinearGroup (Fin 2) ℤ =>
        φ.val (cuspAct g ((0 : ℚ) : Cusp), cuspAct g OnePoint.infty)) := _root_.solution φ x y
end

end publicSection
