/-
Based on Prove2Me node MTT.Cohomology.mixed_period_test_functions_wirtinger_data_of_pos_level
(d646c8e8-a4eb-4769-9781-07ca47564125) by davidloeffler (2026-09-08).

Proof based on Prove2Me submission e0c42735-ff3f-4268-8af1-6d8d282f3c9e
by davidloeffler (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_PeriodPairing
public import Mathlib.NumberTheory.ModularForms.Bounds

import Theorems.MTT.Thm_MTT_Cohomology_mixed_period_test_functions_local_equivariant
import Theorems.MTT.Thm_MTT_Cohomology_mixed_period_test_functions_cusp_decay_of_pos_level
import Theorems.MTT.Thm_MTT_Cohomology_mixed_period_test_functions_tile_integrable_of_pos_level

/-!
# Wirtinger data for mixed-period test functions at positive level

Theorem statement: `MTT.Cohomology.mixed_period_test_functions_wirtinger_data_of_pos_level`
(`d646c8e8-a4eb-4769-9781-07ca47564125`), by davidloeffler, 2026-09-08.

Proof: submission `e0c42735-ff3f-4268-8af1-6d8d282f3c9e`, by davidloeffler, 2026-09-08 (ACCEPTED);
locally adapted.

Let $N>0$ and $k\ge 2$. For cusp forms $g,v,q$ of level $\Gamma_1(N)$ and weight $k$, and a
mixed-period primitive $U$ for $(g,v)$, there are two scalar test functions $A_1,A_2$ on $\mathbb
C$. They are $C^1$ on the upper half-plane, transform with antiholomorphic weight $2$, vanish in
every normalized cusp chart, have integrable Wirtinger derivatives on each translated standard tile
indexed by a finite set $R$, and their Wirtinger derivatives are the $(g,q)$ period density and
minus the conjugate of the $(q,v)$ period density, respectively.

The hypotheses $N>0$ and $k\ge2$ are the level and weight assumptions used by the main cohomological
vanishing theorem.

## Explanation of the source proof

Let $N>0$ and $k\ge2$. Given cusp forms $g,v,q$ of level $\Gamma_1(N)$, a mixed-period primitive
$U$, and a finite collection of translated standard tiles, form the two canonical scalar
contractions

$$A_1(z)=B_{k-2}\big(U(z),\overline{q(z)}(\bar zX+Y)^{k-2}\big),\qquad
A_2(z)=\overline{B_{k-2}\big(q(z)(zX+Y)^{k-2},U(z)\big)}.$$

The desired Wirtinger-data package follows by combining three open lemmas about these same
functions. `mixed_period_test_functions_local_equivariant` supplies their local regularity,
transformation laws, and derivative identities; it uses $k\ge2$ and does not require positive level.
`mixed_period_test_functions_cusp_decay_of_pos_level` supplies decay in every normalized cusp chart,
using both $N>0$ and $k\ge2$. `mixed_period_test_functions_tile_integrable_of_pos_level` supplies
integrability of both Wirtinger derivatives on the prescribed tiles, again with both hypotheses
explicit.

The reduction chooses these canonical functions and assembles the corresponding clauses. No analytic
child is proved by this submission. This replaces the former sketch, which applied a cusp-decay
lemma without a positive-level hypothesis.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section
open UpperHalfPlane MeasureTheory
open scoped MatrixGroups Modular ComplexConjugate
open MTT.Cohomology

theorem solution
    {N k : ℕ} (hN : 0 < N) (hk : 2 ≤ k)
    (g v q : CuspForm (MTT.GammaOne N) (k : ℤ))
    (U : ℂ → Binary ℂ) (hU : IsMixedPeriodPrimitive g v U)
    (R : Finset (Matrix.SpecialLinearGroup (Fin 2) ℤ)) :
    ∃ A₁ A₂ : ℂ → ℂ,
      ContDiffOn ℝ 1 A₁ upperHalfPlaneSet ∧
      (∀ γ ∈ CongruenceSubgroup.Gamma1 N, ∀ τ : ℍ,
        A₁ ((γ • τ : ℍ) : ℂ) =
          (starRingEnd ℂ (denom γ τ)) ^ 2 * A₁ τ) ∧
      (∀ σ : Matrix.SpecialLinearGroup (Fin 2) ℤ, IsZeroAtImInfty
        fun τ : ℍ ↦ A₁ ((σ • τ : ℍ) : ℂ) *
          ((starRingEnd ℂ (denom σ τ)) ^ 2)⁻¹) ∧
      (∀ σ ∈ R, IntegrableOn
        (fun z ↦ (1 / 2 : ℂ) *
          (fderiv ℝ A₁ z 1 - Complex.I * fderiv ℝ A₁ z Complex.I))
        ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) ∧
      (∀ z : ℍ,
        (1 / 2 : ℂ) *
            (fderiv ℝ A₁ z 1 - Complex.I * fderiv ℝ A₁ z Complex.I) =
          periodContraction (k - 2)
            (g z • periodPower (k - 2) (z : ℂ))
            (conj (q z) • periodPower (k - 2) (conj (z : ℂ)))) ∧
      ContDiffOn ℝ 1 A₂ upperHalfPlaneSet ∧
      (∀ γ ∈ CongruenceSubgroup.Gamma1 N, ∀ τ : ℍ,
        A₂ ((γ • τ : ℍ) : ℂ) =
          (starRingEnd ℂ (denom γ τ)) ^ 2 * A₂ τ) ∧
      (∀ σ : Matrix.SpecialLinearGroup (Fin 2) ℤ, IsZeroAtImInfty
        fun τ : ℍ ↦ A₂ ((σ • τ : ℍ) : ℂ) *
          ((starRingEnd ℂ (denom σ τ)) ^ 2)⁻¹) ∧
      (∀ σ ∈ R, IntegrableOn
        (fun z ↦ (1 / 2 : ℂ) *
          (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I))
        ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) ∧
      (∀ z : ℍ,
        (1 / 2 : ℂ) *
            (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I) =
          -conj (periodContraction (k - 2)
            (q z • periodPower (k - 2) (z : ℂ))
            (conj (v z) • periodPower (k - 2) (conj (z : ℂ))))) := by
  let A₁ : ℂ → ℂ := fun z =>
    periodContraction (k - 2) (U z)
      (conj ((↑ₕ(fun τ : ℍ ↦ q τ)) z) • periodPower (k - 2) (conj z))
  let A₂ : ℂ → ℂ := fun z => conj <|
    periodContraction (k - 2)
      (((↑ₕ(fun τ : ℍ ↦ q τ)) z) • periodPower (k - 2) z) (U z)
  have hlocal :=
    MTT.Cohomology.mixed_period_test_functions_local_equivariant hk g v q U hU
  have hdecay :=
    MTT.Cohomology.mixed_period_test_functions_cusp_decay_of_pos_level hN hk g v q U hU
  have hint :=
    MTT.Cohomology.mixed_period_test_functions_tile_integrable_of_pos_level
      hN hk g v q U hU R
  dsimp only at hlocal hdecay hint
  rcases hlocal with ⟨hC₁, hE₁, hD₁, hC₂, hE₂, hD₂⟩
  rcases hdecay with ⟨hZ₁, hZ₂⟩
  rcases hint with ⟨hI₁, hI₂⟩
  exact ⟨A₁, A₂, hC₁, hE₁, hZ₁, hI₁, hD₁,
    hC₂, hE₂, hZ₂, hI₂, hD₂⟩
end

end privateSection

public section publicSection

noncomputable section
open UpperHalfPlane MeasureTheory
open scoped MatrixGroups Modular ComplexConjugate
open MTT.Cohomology
theorem MTT.Cohomology.mixed_period_test_functions_wirtinger_data_of_pos_level
    {N k : ℕ} (hN : 0 < N) (hk : 2 ≤ k)
    (g v q : CuspForm (MTT.GammaOne N) (k : ℤ))
    (U : ℂ → Binary ℂ) (hU : IsMixedPeriodPrimitive g v U)
    (R : Finset (Matrix.SpecialLinearGroup (Fin 2) ℤ)) :
    ∃ A₁ A₂ : ℂ → ℂ,
      ContDiffOn ℝ 1 A₁ upperHalfPlaneSet ∧
      (∀ γ ∈ CongruenceSubgroup.Gamma1 N, ∀ τ : ℍ,
        A₁ ((γ • τ : ℍ) : ℂ) =
          (starRingEnd ℂ (denom γ τ)) ^ 2 * A₁ τ) ∧
      (∀ σ : Matrix.SpecialLinearGroup (Fin 2) ℤ, IsZeroAtImInfty
        fun τ : ℍ ↦ A₁ ((σ • τ : ℍ) : ℂ) *
          ((starRingEnd ℂ (denom σ τ)) ^ 2)⁻¹) ∧
      (∀ σ ∈ R, IntegrableOn
        (fun z ↦ (1 / 2 : ℂ) *
          (fderiv ℝ A₁ z 1 - Complex.I * fderiv ℝ A₁ z Complex.I))
        ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) ∧
      (∀ z : ℍ,
        (1 / 2 : ℂ) *
            (fderiv ℝ A₁ z 1 - Complex.I * fderiv ℝ A₁ z Complex.I) =
          periodContraction (k - 2)
            (g z • periodPower (k - 2) (z : ℂ))
            (conj (q z) • periodPower (k - 2) (conj (z : ℂ)))) ∧
      ContDiffOn ℝ 1 A₂ upperHalfPlaneSet ∧
      (∀ γ ∈ CongruenceSubgroup.Gamma1 N, ∀ τ : ℍ,
        A₂ ((γ • τ : ℍ) : ℂ) =
          (starRingEnd ℂ (denom γ τ)) ^ 2 * A₂ τ) ∧
      (∀ σ : Matrix.SpecialLinearGroup (Fin 2) ℤ, IsZeroAtImInfty
        fun τ : ℍ ↦ A₂ ((σ • τ : ℍ) : ℂ) *
          ((starRingEnd ℂ (denom σ τ)) ^ 2)⁻¹) ∧
      (∀ σ ∈ R, IntegrableOn
        (fun z ↦ (1 / 2 : ℂ) *
          (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I))
        ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) ∧
      (∀ z : ℍ,
        (1 / 2 : ℂ) *
            (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I) =
          -conj (periodContraction (k - 2)
            (q z • periodPower (k - 2) (z : ℂ))
            (conj (v z) • periodPower (k - 2) (conj (z : ℂ))))) := _root_.solution hN hk g v q U hU R
end

end publicSection
