/-
Based on Prove2Me node MTT.Cohomology.mixed_period_test_functions_tile_integrable_of_pos_level
(f0601e56-4f52-48c8-ae5a-ba3362c8cf93) by davidloeffler (2026-09-08).

Proof based on Prove2Me submission 30a0b499-420b-4f59-8046-d4e48e7d0aef
by cbirkbeck (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_PeriodPairing
public import Mathlib.NumberTheory.ModularForms.Bounds

import Theorems.MTT.Thm_MTT_Cohomology_periodDensity_integrableOn_tile
import Theorems.MTT.Thm_MTT_Cohomology_mixed_period_test_functions_local_equivariant

/-!
# Tile integrability of mixed-period Wirtinger densities at positive level

Theorem statement: `MTT.Cohomology.mixed_period_test_functions_tile_integrable_of_pos_level`
(`f0601e56-4f52-48c8-ae5a-ba3362c8cf93`), by davidloeffler, 2026-09-08.

Proof: submission `30a0b499-420b-4f59-8046-d4e48e7d0aef`, by cbirkbeck, 2026-09-08 (ACCEPTED);
locally adapted.

Let $N>0$ and $k\ge 2$. Given cusp forms $g,v,q$ of level $\Gamma_1(N)$ and weight $k$, a
mixed-period primitive $U$, and a finite set $R\subseteq\mathrm{SL}_2(\mathbb Z)$, form the two
canonical scalar contractions $A_1$ and $A_2$. The Wirtinger derivatives of both functions are
integrable over every translated standard modular domain $\sigma\mathcal D$ with $\sigma\in R$.

The positive-level hypothesis is explicit because the surrounding finite-index quotient argument
assumes $N>0$. This theorem supplies the analytic integrability input for the mixed-period Stokes
argument.

## Explanation of the source proof

# Integrability from the local Wirtinger identities

Write $D_j=\partial A_j/\partial z$ for the two scalar test functions in the
statement. The existing local-calculus theorem identifies these derivatives:

$$
D_1(z)=B_{k-2}\bigl(g(z)(zX+Y)^{k-2},
  \overline{q(z)}(\bar zX+Y)^{k-2}\bigr),
$$

and

$$
D_2(z)=-\overline{
B_{k-2}\bigl(q(z)(zX+Y)^{k-2},
  \overline{v(z)}(\bar zX+Y)^{k-2}\bigr)}.
$$

At positive level and weight at least two, the proved theorem
`MTT.Cohomology.periodDensity_integrableOn_tile` shows that either
period-contraction density is integrable on every translated modular tile.
Applying it directly to $D_1$ gives the first conclusion. Applying it to
$-\overline{D_2}$ gives the second after using the preservation of Bochner
integrability under complex conjugation and negation. This works separately
for every $\sigma\in R$, with no condition on the finite set beyond its type.

The imported integrability theorem is already Proved
(`c95e86db-3af6-472f-a6c6-b5e66cc93073`, accepted proof
`4e220e2d-304d-4539-8c8d-bf0b6e830be6`). Its proof uses finite hyperbolic
area, boundedness of the Petersson density, and the hyperbolic-to-Euclidean
integrability equivalence. The finite-area step is a verified AINTLIB port
with attribution in the accepted supporting proof.

This submission is a reduction, not yet a closed proof: its only Open input
is `MTT.Cohomology.mixed_period_test_functions_local_equivariant`
(`8fc536be-fe46-412d-a002-781234edc48e`). No new child is introduced, and the
existing derivative-identity theorem has no dependency on tile integrability,
so the reduction is non-circular. The corrected positive-level hypothesis
is retained explicitly. The exact target and proof compile at the pinned
revision with default resource limits and no placeholders in the submitted code.

The mixed-period pairing construction is described in the
[Columbia seminar notes, §1.2, Theorem 1, pp.
8–10](https://www.math.columbia.edu/~dmarcil/Seminars/2021_Spring/Notes/Week4-5.pdf).

<!-- Generated by add_prove2me_provenance.py -->
-/

/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/

section privateSection

/-! # Reducing mixed-period integrability to the local calculus identities -/

noncomputable section
open UpperHalfPlane MeasureTheory
open scoped MatrixGroups Modular ComplexConjugate
open MTT.Cohomology

theorem solution
    {N k : ℕ} (hN : 0 < N) (hk : 2 ≤ k)
    (g v q : CuspForm (MTT.GammaOne N) (k : ℤ))
    (U : ℂ → Binary ℂ) (hU : IsMixedPeriodPrimitive g v U)
    (R : Finset (Matrix.SpecialLinearGroup (Fin 2) ℤ)) :
    let A₁ : ℂ → ℂ := fun z =>
      periodContraction (k - 2) (U z)
        (conj ((↑ₕ(fun τ : ℍ ↦ q τ)) z) • periodPower (k - 2) (conj z))
    let A₂ : ℂ → ℂ := fun z => conj <|
      periodContraction (k - 2)
        (((↑ₕ(fun τ : ℍ ↦ q τ)) z) • periodPower (k - 2) z) (U z)
    (∀ σ ∈ R, IntegrableOn
      (fun z ↦ (1 / 2 : ℂ) *
        (fderiv ℝ A₁ z 1 - Complex.I * fderiv ℝ A₁ z Complex.I))
      ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) ∧
    (∀ σ ∈ R, IntegrableOn
      (fun z ↦ (1 / 2 : ℂ) *
        (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I))
      ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) := by
  intro A₁ A₂
  have h := mixed_period_test_functions_local_equivariant hk g v q U hU
  constructor
  · intro σ _
    exact periodDensity_integrableOn_tile hN hk g q σ _ h.2.2.1
  · intro σ _
    have hi := periodDensity_integrableOn_tile hN hk q v σ
      (fun z => -conj ((1 / 2 : ℂ) *
        (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I)))
      (fun z => by rw [h.2.2.2.2.2]; simp)
    simpa [IntegrableOn, sub_eq_add_neg] using
      ((Complex.conjCLE : ℂ →L[ℝ] ℂ).integrable_comp hi).neg
end

end privateSection

public section publicSection

noncomputable section
open UpperHalfPlane MeasureTheory
open scoped MatrixGroups Modular ComplexConjugate
open MTT.Cohomology
theorem MTT.Cohomology.mixed_period_test_functions_tile_integrable_of_pos_level
    {N k : ℕ} (hN : 0 < N) (hk : 2 ≤ k)
    (g v q : CuspForm (MTT.GammaOne N) (k : ℤ))
    (U : ℂ → Binary ℂ) (hU : IsMixedPeriodPrimitive g v U)
    (R : Finset (Matrix.SpecialLinearGroup (Fin 2) ℤ)) :
    let A₁ : ℂ → ℂ := fun z =>
      periodContraction (k - 2) (U z)
        (conj ((↑ₕ(fun τ : ℍ ↦ q τ)) z) • periodPower (k - 2) (conj z))
    let A₂ : ℂ → ℂ := fun z => conj <|
      periodContraction (k - 2)
        (((↑ₕ(fun τ : ℍ ↦ q τ)) z) • periodPower (k - 2) z) (U z)
    (∀ σ ∈ R, IntegrableOn
      (fun z ↦ (1 / 2 : ℂ) *
        (fderiv ℝ A₁ z 1 - Complex.I * fderiv ℝ A₁ z Complex.I))
      ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) ∧
    (∀ σ ∈ R, IntegrableOn
      (fun z ↦ (1 / 2 : ℂ) *
        (fderiv ℝ A₂ z 1 - Complex.I * fderiv ℝ A₂ z Complex.I))
      ((fun τ : ℍ ↦ ((σ • τ : ℍ) : ℂ)) '' 𝒟) volume) := _root_.solution hN hk g v q U hU R
end

end publicSection
