/-
Based on Prove2Me node MTT.interpolation_of_moments
(c3f324df-83ea-4494-b244-0d3669dd1f39) by davidloeffler (2026-09-05).

Proof based on Prove2Me submission b43b739d-2923-402c-9e5b-edf420e6f20a
by davidloeffler (2026-09-06); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_Measures

import Theorems.MTT.Thm_MTT_interpolation_conductor_one_of_moments
import Theorems.MTT.Thm_MTT_interpolation_positive_conductor_of_moments

/-!
# MTT interpolation from the two signed moment measures

Theorem statement: `MTT.interpolation_of_moments` (`c3f324df-83ea-4494-b244-0d3669dd1f39`), by
davidloeffler, 2026-09-05.

Proof: submission `b43b739d-2923-402c-9e5b-edf420e6f20a`, by davidloeffler, 2026-09-06 (ACCEPTED);
locally adapted.

If the two signed bounded measures realize every prescribed critical polynomial disk moment, their
sum satisfies the full scalar period-normalized MTT interpolation identity for every primitive
p-power-conductor character and critical exponent. The conductor-one case retains both Euler
factors; positive conductor has multiplier α^(−n). Algebraic values bridge the two fixed embeddings.

## Explanation of the source proof

We reduce the interpolation theorem to its two mathematically distinct conductor cases.

For positive conductor $p^n$ with $n>0$, the first child theorem asserts the complete interpolation
identity obtained by summing the prescribed residue-disk moments against the primitive character.
The parity relation selects the signed period indexed by $\chi(-1)(-1)^j$, while the character
vanishes at $p$ in this conductor range.

For $n=0$, the second child theorem supplies the conductor-one identity. This boundary case is
recovered from the positive-depth hypotheses by partitioning $\mathbf Z_p^\times$ into residue disks
of depth one; unlike the positive-conductor case, both Euler factors remain visible.

The definition of `Interpolates` universally quantifies the conductor exponent $n$. Splitting $n$
into zero and successor cases therefore reduces every required interpolation datum exactly to one of
these two child theorems. No analytic or algebraic assertion beyond those children is used in the
reduction.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section
open scoped BigOperators

open MTT in
theorem solution
    {p N k : ℕ} [Fact p.Prime] (hN : 0 < N) (hk : 2 ≤ k)
    (ι : Qbar →+* ℂ) (ιp : Qbar →+* ℂ_[p]) (f : Eigenform N k ι)
    (P : Periods k ι f.form) (α : ℂ_[p]) (hα : IsOrdinaryRoot f ιp α)
    (μ : Bool → UnitMeasure p)
    (hμ : ∀ s, RealizesMoments f ιp P α s (μ s)) :
    Interpolates f ιp P.omega α (μ true + μ false) := by
  unfold Interpolates
  intro n χ hχ j hj
  cases n with
  | zero =>
      exact MTT.interpolation_conductor_one_of_moments
        hN hk ι ιp f P α hα μ hμ χ hχ j hj
  | succ n =>
      exact MTT.interpolation_positive_conductor_of_moments
        hN hk ι ιp f P α hα μ hμ (n + 1) (Nat.zero_lt_succ n) χ hχ j hj
end

end privateSection

public section publicSection

noncomputable section
open scoped BigOperators

open MTT in
theorem MTT.interpolation_of_moments
    {p N k : ℕ} [Fact p.Prime] (hN : 0 < N) (hk : 2 ≤ k)
    (ι : Qbar →+* ℂ) (ιp : Qbar →+* ℂ_[p]) (f : Eigenform N k ι)
    (P : Periods k ι f.form) (α : ℂ_[p]) (hα : IsOrdinaryRoot f ιp α)
    (μ : Bool → UnitMeasure p)
    (hμ : ∀ s, RealizesMoments f ιp P α s (μ s)) :
    Interpolates f ιp P.omega α (μ true + μ false) := _root_.solution hN hk ι ιp f P α hα μ hμ
end

end publicSection
