/-
Based on Prove2Me node MTT.Cohomology.parabolicH1_dimension_upper_bound_large_level
(bbf1733c-a53f-457f-9833-e93668f4b5b0) by cbirkbeck (2026-09-07).

Proof based on Prove2Me submission 102aac04-53c0-4160-af7a-612ba4520f9e
by cbirkbeck (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_ParabolicCohomology
public import Mathlib.GroupTheory.DoubleCoset
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs

import Theorems.MTT.Thm_MTT_Cohomology_parabolicH1_finrank_le_centralCoinduced
import Theorems.MTT.Thm_MTT_Cohomology_centralCoinduced_parabolicH1_dimension_upper_bound

/-!
# Large-level parabolic cohomology: the index-minus-cusps dimension bound

Theorem statement: `MTT.Cohomology.parabolicH1_dimension_upper_bound_large_level`
(`bbf1733c-a53f-457f-9833-e93668f4b5b0`), by cbirkbeck, 2026-09-07.

Proof: submission `102aac04-53c0-4160-af7a-612ba4520f9e`, by cbirkbeck, 2026-09-08 (ACCEPTED);
locally adapted.

Let $N\ge5$ and $k\ge3$. Put $\mu=[\mathrm{SL}_2(\mathbb Z):\langle\Gamma_1(N),-I\rangle]$ and
$c=\#(\Gamma_1(N)\backslash\mathrm{SL}_2(\mathbb Z)/\langle T,-I\rangle)$. Then

$$6\dim_{\mathbb C}H^1_{\mathrm{par}}(\Gamma_1(N),\mathrm{Sym}^{k-2}\mathbb C^2)+6c\le(k-1)\mu.$$

This is the purely cohomological upper-bound half of the torsion-free, regular-cusp dimension
comparison. The intended route uses parabolic Shapiro and the fixed spaces of S, ST and T in the
central-positive coinduced representation. This theorem is explicitly OPEN; the independent
cusp-form lower bound does not prove it.

## Explanation of the source proof

# Reduction to the central-fixed coinduced dimension count

Let $W^+$ be the $-I$-fixed subrepresentation of the coinduction of
$\operatorname{Sym}^{k-2}\mathbb C^2$ from $\Gamma_1(N)$ to
$\mathrm{SL}_2(\mathbb Z)$. The new closed comparison theorem
`f7d52bf4-45cb-48e0-bad8-d2c3eeb2269f` proves

$$\dim H^1_{\mathrm{par}}(\Gamma_1(N),\operatorname{Sym}^{k-2}\mathbb C^2)
\le \dim H^1_{\mathrm{par}}(\mathrm{SL}_2(\mathbb Z),W^+).$$

The remaining child `0c63643a-996a-4912-8a0d-34924c75dff7` bounds six times the
right-hand dimension plus six times the cusp count by $(k-1)\mu$, where
$\mu=[\mathrm{SL}_2(\mathbb Z):\langle\Gamma_1(N),-I\rangle]$.
The parent follows immediately by multiplication and addition of inequalities.

The reduction is substantive: the comparison independently proves parabolic
Shapiro compatibility and the central-fixed reduction, so the child is solely
a full-group coefficient count. It also connects the earlier accepted
parabolic coinduced cocycle lift to the mission dependency graph.

The count remains open. An intended algebraic route evaluates cocycles on
$S$ and $ST$, applies their order-two and order-three relations on $W^+$,
and imposes the parabolic $T$ condition. For $N\ge5$, there are no elliptic
or irregular-cusp corrections. The required fixed-space dimensions and
vanishing invariant/coinvariant contributions must still be proved; this
submission assumes none of them outside the explicit child. In particular,
it does not assert trivial central action on the entire coinduced module.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

/-! # Reduction to the full-group central-fixed coefficient count -/

open scoped MatrixGroups

theorem solution {N k : ℕ} (hN : 5 ≤ N) (hk : 3 ≤ k) :
    6 * Module.finrank ℂ (MTT.Cohomology.ParabolicH1 N (k - 2)) +
        6 * Nat.card (DoubleCoset.Quotient (CongruenceSubgroup.Gamma1 N : Set SL(2, ℤ))
          ((Subgroup.zpowers ModularGroup.T ⊔ Subgroup.zpowers (-1) : Subgroup SL(2, ℤ)) :
            Set SL(2, ℤ))) ≤
      (k - 1) * (CongruenceSubgroup.Gamma1 N ⊔ Subgroup.zpowers (-1 : SL(2, ℤ))).index := by
  have hcomp := MTT.Cohomology.parabolicH1_finrank_le_centralCoinduced
    (n := k - 2) (show 0 < N by omega)
  have hcount := MTT.Cohomology.centralCoinduced_parabolicH1_dimension_upper_bound hN hk
  omega

end privateSection

public section publicSection

open scoped MatrixGroups


theorem MTT.Cohomology.parabolicH1_dimension_upper_bound_large_level {N k : ℕ}
    (hN : 5 ≤ N) (hk : 3 ≤ k) :
    6 * Module.finrank ℂ (MTT.Cohomology.ParabolicH1 N (k - 2)) +
        6 * Nat.card (DoubleCoset.Quotient (CongruenceSubgroup.Gamma1 N : Set SL(2, ℤ))
          ((Subgroup.zpowers ModularGroup.T ⊔ Subgroup.zpowers (-1) : Subgroup SL(2, ℤ)) :
            Set SL(2, ℤ))) ≤
      (k - 1) * (CongruenceSubgroup.Gamma1 N ⊔ Subgroup.zpowers (-1 : SL(2, ℤ))).index := _root_.solution hN hk

end publicSection
