/-
Based on Prove2Me node MTT.Cohomology.reflection_involutive
(25a23635-6ccf-4ee7-ac1a-b58d5bb97b9d) by cbirkbeck (2026-09-06).

Proof based on Prove2Me submission ff41fc8e-aa00-43c1-9c32-d0c7291b0e6f
by cbirkbeck (2026-09-06); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_Cohomology

/-!
# The reflection on modular-symbol cochains is an involution

Theorem statement: `MTT.Cohomology.reflection_involutive` (`25a23635-6ccf-4ee7-ac1a-b58d5bb97b9d`),
by cbirkbeck, 2026-09-06.

Proof: submission `ff41fc8e-aa00-43c1-9c32-d0c7291b0e6f`, by cbirkbeck, 2026-09-06 (ACCEPTED);
locally adapted.

Let $R$ be a commutative ring and let
$\phi:\operatorname{Div}\text{-pairs}\to\operatorname{Sym}^n(R^2)$ be any
$\operatorname{Sym}^n$-valued cochain on pairs of cusps. The reflection $\mathcal R$ is induced by
the matrix $\operatorname{diag}(-1,1)$: it acts on cusps by $x\mapsto -x$ and on binary polynomials
by $X\mapsto -X$. Then

$$
\mathcal R(\mathcal R\,\phi)=\phi .
$$

That is, the reflection is an involution on cochains. This is the fact that makes the signed
projectors $\tfrac12(1\pm\mathcal R)$ idempotent and lets one decompose Hecke eigenspaces of modular
symbols into their $\pm$ parts.

**Formalization Note** The statement is about the underlying cochains `(Cusp × Cusp) → Binary R`;
combined with `MTT.Cohomology.reflection_class`, which shows the reflection preserves the
modular-symbol submodule, it gives the involution on $H_c(N,n;R)$.

## Explanation of the source proof

# The reflection is an involution on modular-symbol cochains

We prove that for every commutative ring $R$ and every cochain $\phi$ on pairs of cusps with values
in binary polynomials of degree $n$ over $R$,

$$
\mathcal R(\mathcal R\,\phi)=\phi ,
$$

where $\mathcal R$ is the reflection induced by $\epsilon=\operatorname{diag}(-1,1)$: it acts on
cusps by the fractional-linear action of $\epsilon$ and on the values by the coefficient action of
$\epsilon$.

The idea is that both ingredients of $\mathcal R$ are themselves involutions, and $\mathcal R$ is
their composite: $(\mathcal R\phi)(x,y)=\epsilon\cdot\phi(\epsilon x,\epsilon y)$, so $\mathcal
R(\mathcal R\phi)(x,y)=\epsilon\cdot(\epsilon\cdot\phi(\epsilon\epsilon x,\epsilon\epsilon y))$.

**Step 1 (cusps).** The fractional-linear action of $\epsilon$ sends $\infty\mapsto\infty$ (the
lower-left entry is $0$) and a rational cusp $r\mapsto(-r+0)/(0\cdot r+1)=-r$. Applying it twice
returns $\infty$ and $r$ respectively.

**Step 2 (coefficients).** The coefficient action of a matrix $\gamma$ is the algebra substitution
$X_i\mapsto\sum_a\gamma_{ai}X_a$. For $\gamma=\epsilon$ this is $X\mapsto -X$, $Y\mapsto Y$. The
composite of two substitutions is the substitution by the composite, and $X\mapsto-(-X)=X$,
$Y\mapsto Y$ is the identity substitution, which acts as the identity on polynomials.

**Step 3.** Combining the two steps pointwise in $(x,y)$ gives $\mathcal R(\mathcal R\phi)=\phi$.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section
open scoped BigOperators
open MTT.Cohomology

namespace P2MRefl

/-- The fractional-linear action of `diag(-1,1)` on cusps is an involution. -/
theorem fractional_refl_refl (x : Cusp) :
    fractional !![-1, 0; 0, 1] (fractional !![-1, 0; 0, 1] x) = x := by
  cases x <;> simp [fractional, OnePoint.infty] <;> rfl

/-- The coefficient action of `diag(-1,1)` on binary polynomials is an involution. -/
theorem act_refl_refl {R : Type*} [CommRing R] (P : Binary R) :
    act !![-1, 0; 0, 1] (act !![-1, 0; 0, 1] P) = P := by
  simp only [act, AlgHom.toLinearMap_apply]
  rw [← AlgHom.comp_apply, MvPolynomial.comp_aeval]
  convert MvPolynomial.aeval_X_left_apply P using 2
  congr 1
  funext i
  fin_cases i <;> simp [Fin.sum_univ_two]

end P2MRefl

open P2MRefl in
theorem solution {R : Type*} [CommRing R]
    (φ : (Cusp × Cusp) → Binary R) : reflection (reflection φ) = φ := by
  funext D
  simp only [reflection, fractional_refl_refl]
  exact act_refl_refl _
end

end privateSection

public section publicSection

noncomputable section
open scoped BigOperators TensorProduct
open MTT.Cohomology

theorem MTT.Cohomology.reflection_involutive {R : Type*} [CommRing R]
    (φ : (Cusp × Cusp) → Binary R) : reflection (reflection φ) = φ := _root_.solution φ
end

end publicSection
