/-
Based on Prove2Me node MTT.Cohomology.centralCoinduced_fixed_dimensions_large_level
(bb6b5766-fb31-4de5-9462-40a64feda1a8) by cbirkbeck (2026-09-08).

Proof based on Prove2Me submission 50b58249-1134-4834-a2b0-8759613a5765
by cbirkbeck (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_FullParabolicCohomology
public import Mathlib.GroupTheory.DoubleCoset
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs

import Theorems.MTT.Thm_MTT_Cohomology_centralCoinduced_elliptic_dimensions
import Theorems.MTT.Thm_MTT_Cohomology_centralCoinduced_T_fixed_cusp_lower_bound

/-!
# Large-level dimensions of central-fixed coinduction and its S, ST, T fixed spaces

Theorem statement: `MTT.Cohomology.centralCoinduced_fixed_dimensions_large_level`
(`bb6b5766-fb31-4de5-9462-40a64feda1a8`), by cbirkbeck, 2026-09-08.

Proof: submission `50b58249-1134-4834-a2b0-8759613a5765`, by cbirkbeck, 2026-09-08 (ACCEPTED);
locally adapted.

Let $N\ge5$ and $n>0$, and let $W=(\operatorname{Coind}_{\Gamma_1(N)}^{\mathrm{SL}_2(\mathbb
Z)}\operatorname{Sym}^n\mathbb C^2)^{-I=1}$. Set $\mu=[\mathrm{SL}_2(\mathbb
Z):\langle\Gamma_1(N),-I\rangle]$ and $c=\#(\Gamma_1(N)\backslash\mathrm{SL}_2(\mathbb Z)/\langle
T,-I\rangle)$. For the standard modular generators $S,T$, the following four assertions hold: $$\dim
W=(n+1)\mu,\qquad 2\dim W^S=\dim W,\qquad 3\dim W^{ST}=\dim W,\qquad c\le\dim W^T.$$ Here
$W^g=\ker(\rho(g)-1)$, and all dimensions are over $\mathbb C$. These finite-coset counts supply the
numerical input to the full-group parabolic-cohomology estimate. The restriction $N\ge5$ excludes
elliptic stabilizers and irregular cusps; no parity condition is imposed on $n$.

## Explanation of the source proof

# Separate the elliptic identities from the cusp bound

The coefficient dimension and the two elliptic fixed-space identities are
provided by `MTT.Cohomology.centralCoinduced_elliptic_dimensions`. Its proof
uses cyclic averaging, vanishing traces of fixed-point-free coset permutations,
and the index change on adjoining the central involution. It is valid for all
symmetric powers, without a parity restriction.

The fourth conjunct is precisely the separate cusp lower bound for the
$T$-fixed space. This remains an open mathematical input in this proof-sketch:
the number of cusp double cosets must be bounded by the dimension of the
central-fixed coinduced $T$-invariants. No conclusion about that count is
inferred from the elliptic calculation alone.

Combining these four statements gives the requested conjunction. Thus this
reduction records the proved coefficient/elliptic portion and isolates only
the parabolic cusp calculation as the remaining frontier dependency.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

open scoped MatrixGroups

theorem solution {N n : ℕ} (hN : 5 ≤ N) (hn : 0 < n) :
    let W := MTT.Cohomology.centralCoinduced N n
    Module.finrank ℂ W =
        (n + 1) * (CongruenceSubgroup.Gamma1 N ⊔ Subgroup.zpowers (-1 : SL(2, ℤ))).index ∧
      2 * Module.finrank ℂ (W.ρ ModularGroup.S - LinearMap.id).ker = Module.finrank ℂ W ∧
      3 * Module.finrank ℂ (W.ρ (ModularGroup.S * ModularGroup.T) - LinearMap.id).ker =
        Module.finrank ℂ W ∧
      Nat.card (DoubleCoset.Quotient (CongruenceSubgroup.Gamma1 N : Set SL(2, ℤ))
        ((Subgroup.zpowers ModularGroup.T ⊔ Subgroup.zpowers (-1) : Subgroup SL(2, ℤ)) :
          Set SL(2, ℤ))) ≤ Module.finrank ℂ (W.ρ ModularGroup.T - LinearMap.id).ker := by
  obtain ⟨hd, hS, hU⟩ := MTT.Cohomology.centralCoinduced_elliptic_dimensions (n := n) hN
  exact ⟨hd, hS, hU, MTT.Cohomology.centralCoinduced_T_fixed_cusp_lower_bound hN hn⟩

end privateSection

public section publicSection

open scoped MatrixGroups

theorem MTT.Cohomology.centralCoinduced_fixed_dimensions_large_level {N n : ℕ}
    (hN : 5 ≤ N) (hn : 0 < n) :
    let W := MTT.Cohomology.centralCoinduced N n
    Module.finrank ℂ W =
        (n + 1) * (CongruenceSubgroup.Gamma1 N ⊔ Subgroup.zpowers (-1 : SL(2, ℤ))).index ∧
      2 * Module.finrank ℂ (W.ρ ModularGroup.S - LinearMap.id).ker = Module.finrank ℂ W ∧
      3 * Module.finrank ℂ (W.ρ (ModularGroup.S * ModularGroup.T) - LinearMap.id).ker =
        Module.finrank ℂ W ∧
      Nat.card (DoubleCoset.Quotient (CongruenceSubgroup.Gamma1 N : Set SL(2, ℤ))
        ((Subgroup.zpowers ModularGroup.T ⊔ Subgroup.zpowers (-1) : Subgroup SL(2, ℤ)) :
          Set SL(2, ℤ))) ≤ Module.finrank ℂ (W.ρ ModularGroup.T - LinearMap.id).ker := _root_.solution hN hn

end publicSection
