/-
Based on Prove2Me node PadicMeasure.compatible_disk_values_vanish_of_decay
(b819a5f2-8721-445d-9057-6727d36c1e56) by Wenqian (2026-09-06).

Proof based on Prove2Me submission 0227c600-58d8-4413-9a41-26e08f730029
by Wenqian (2026-09-06); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.Padics.Complex

import Mathlib.RingTheory.Coprime.Lemmas
import Mathlib.Analysis.SpecificLimits.Basic

/-!
# Compatible disk values with uniform depth decay vanish

Theorem statement: `PadicMeasure.compatible_disk_values_vanish_of_decay`
(`b819a5f2-8721-445d-9057-6727d36c1e56`), by Wenqian, 2026-09-06.

Proof: submission `0227c600-58d8-4413-9a41-26e08f730029`, by Wenqian, 2026-09-06 (ACCEPTED); locally
adapted.

Let $p$ be prime and let $D(n,a)\in\mathbf C_p$ be values on positive-depth unit residue disks.
Suppose

$$D(n,a)=\sum_{b=0}^{p-1}D(n+1,a+bp^n).$$

Assume there is a real sequence $B(n)\to0$ such that $|D(n,a)|_p\le B(n)$ for every positive $n$ and
every integer $a$ prime to $p$. Then $D(n,a)=0$ for all these disks.

This is the vanishing mechanism used to identify prescribed higher moments with those of the measure
constructed from degree-zero masses in the Colmez order-zero extension theorem.

## Explanation of the source proof

Fix a unit disk of depth $n$. Iterating refinement and applying the nonarchimedean triangle
inequality gives, for every $r\ge0$,

$$|D(n,a)|_p\le B(n+r).$$

The induction step rewrites the parent value as the sum of its $p$ child values. Each child centre
$a+bp^n$ remains prime to $p$, since $n>0$. The ultrametric norm of the sum is bounded by the
largest norm of its terms, so no factor counting the children is introduced. This is why the same
bound $B(n+r)$ survives arbitrarily many refinements.

As $r\to\infty$, the right side tends to zero. Nonnegativity of the norm then forces $D(n,a)=0$.

The theorem requires no monotonicity of $B$. It is the vanishing step for a compatible error between
prescribed higher moments and the moments of a measure constructed from the degree-zero masses. The
complete Lean proof uses no platform theorem imports, sorry terms, or added axioms and passes in
Lean 4.33.1 with Mathlib 0df444a360eaa60ab8c11dca51a86af692955474.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

open scoped BigOperators
open Filter

lemma child_coprime {p n : ℕ} (hn : 0 < n) {a : ℤ}
    (ha : IsCoprime a p) (b : ℕ) :
    IsCoprime (a + b * p ^ n) p := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  simpa [pow_succ, mul_assoc] using ha.add_mul_right_left (b * (p : ℤ) ^ m)

/-- Compatible residue-disk values that decay uniformly with depth vanish. -/
theorem solution {p : ℕ} [Fact p.Prime] (D : ℕ → ℤ → ℂ_[p])
    (hadd : ∀ n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) →
      (∑ b ∈ Finset.range p, D (n+1) (a+(b : ℤ)*(p : ℤ)^n)) = D n a)
    (B : ℕ → ℝ) (hB : Filter.Tendsto B Filter.atTop (nhds 0))
    (hbound : ∀ n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) → ‖D n a‖ ≤ B n) :
    ∀ n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) → D n a = 0 := by
  have hiter : ∀ r n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) →
      ‖D n a‖ ≤ B (n+r) := by
    intro r
    induction r with
    | zero => simpa using hbound
    | succ r ih =>
      intro n hn a ha
      rw [← hadd n hn a ha]
      apply IsUltrametricDist.norm_sum_le_of_forall_le_of_nonempty
        (Finset.nonempty_range_iff.mpr (Fact.out : p.Prime).ne_zero)
      intro b _
      simpa only [Nat.add_assoc,Nat.add_comm 1] using
        ih (n+1) (by omega) (a+(b : ℤ)*(p : ℤ)^n) (child_coprime hn ha b)
  intro n hn a ha
  apply norm_eq_zero.mp
  apply le_antisymm _ (norm_nonneg _)
  have ht : Filter.Tendsto (fun r : ℕ => B (n+r)) Filter.atTop (nhds 0) :=
    hB.comp (by simpa only [Nat.add_comm] using tendsto_add_atTop_nat n)
  exact ge_of_tendsto ht (Filter.Eventually.of_forall (fun r => hiter r n hn a ha))

end privateSection

public section publicSection
open scoped BigOperators
open Filter

theorem PadicMeasure.compatible_disk_values_vanish_of_decay {p : ℕ} [Fact p.Prime] (D : ℕ → ℤ → ℂ_[p])
    (hadd : ∀ n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) →
      (∑ b ∈ Finset.range p, D (n+1) (a+(b : ℤ)*(p : ℤ)^n)) = D n a)
    (B : ℕ → ℝ) (hB : Filter.Tendsto B Filter.atTop (nhds 0))
    (hbound : ∀ n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) → ‖D n a‖ ≤ B n) :
    ∀ n : ℕ, 0 < n → ∀ a : ℤ, IsCoprime a (p : ℤ) → D n a = 0 :=
  solution D hadd B hB hbound

end publicSection
