/-
Based on Prove2Me node MTT.Cohomology.cuspForm_finrank_lower_bound_level_four_odd
(95cbc152-c054-48f1-a94f-c99cda423e6c) by cbirkbeck (2026-09-08).

Proof based on Prove2Me submission 35b13247-c141-46e1-9f24-550ff43062a5
by cbirkbeck (2026-09-08); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.MTT.Def_MTT_ParabolicCohomology
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs

import Theorems.MTT.Thm_CuspForm_finrank_lower_bound_of_weighted_forms
import Theorems.MTT.Thm_MTT_Cohomology_exists_weighted_cusp_seeds_level_four
import Theorems.FLT.Thm_ModularForm_finiteDimensional_of_isArithmetic
import Mathlib.NumberTheory.ModularForms.CuspFormSubmodule
import Mathlib.RingTheory.PowerSeries.Order
import Mathlib.Tactic

/-!
# Odd-weight cusp-form lower bound at level four

Theorem statement: `MTT.Cohomology.cuspForm_finrank_lower_bound_level_four_odd`
(`95cbc152-c054-48f1-a94f-c99cda423e6c`), by cbirkbeck, 2026-09-08.

Proof: submission `35b13247-c141-46e1-9f24-550ff43062a5`, by cbirkbeck, 2026-09-08 (ACCEPTED);
locally adapted.

For every odd integer $k\ge3$, the space $S_k(\Gamma_1(4))$ of holomorphic cusp forms satisfies

$$k-3\le 2\dim_{\mathbf C}S_k(\Gamma_1(4)).$$

This is the lower-bound consequence of the level-four odd-weight dimension formula $\dim
S_k=(k-3)/2$. The irregular-cusp correction is essential at this level. Together with the
two-generator cohomology estimate, this completes the level-four odd-weight dimension comparison
needed by MTT.

## Explanation of the source proof

## Reduction to three low-weight forms

The case $k=3$ is immediate. For odd $k\ge5$, take forms $A\in M_1(\Gamma_1(4))$, $B\in
M_2(\Gamma_1(4))$, and nonzero $D\in S_5(\Gamma_1(4))$ with q-orders zero and one for $A$ and $B$.

The proved weighted-monomial theorem supplies

$$\dim S_k(\Gamma_1(4))\ge\left\lfloor\frac{k-5}{2}\right\rfloor+1=\frac{k-3}{2}.$$

The existing arithmetic modular-form theorem supplies finite-dimensionality, and mathlib supplies
strict period one. All remaining arithmetic is proved in Lean at default resource limits. The sole
remaining analytic input is the explicit seed theorem
[9af94959-aa50-47b9-85f6-e2ab387a3d8e](p2m:theorem/9af94959-aa50-47b9-85f6-e2ab387a3d8e).

Candidate eta exponent vectors, indexed by $1,2,4$, are $(-4,10,-4)$ for $A$, $(0,-4,8)$ for $B$,
and $(4,2,4)$ for $D$. Their divisibility sums are $(0,0)$, $(24,0)$ and $(24,24)$. Their orders at
the three cusps $0,1/2,\infty$ are $(0,1/2,0)$, $(0,0,1)$ and $(1,1/2,1)$. Thus the first two forms
are holomorphic and the last is cuspidal, by Theorems 1.2 and 1.4 of [Allen et
al.](https://arxiv.org/pdf/1901.10511), pp. 2–3. Odd-weight character factors restrict trivially to
$\Gamma_1(4)$; no trivial-character claim on $\Gamma_0(4)$ is made. The coprime-to-six corollary is
not used. Formalizing these analytic seed facts remains open; this submission proves their
implication for every odd weight.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

open UpperHalfPlane

theorem solution {k : ℕ} (hk : 3 ≤ k) (hko : Odd k) :
    k - 3 ≤ 2 * Module.finrank ℂ (CuspForm (MTT.GammaOne 4) (k : ℤ)) := by
  by_cases hr : 5 ≤ k
  · obtain ⟨A, B, D, hA, hB, hD⟩ := MTT.Cohomology.exists_weighted_cusp_seeds_level_four
    have := ModularForm.finiteDimensional_of_isArithmetic (MTT.GammaOne 4) (k : ℤ)
    have : FiniteDimensional ℂ (CuspForm (MTT.GammaOne 4) (k : ℤ)) :=
      FiniteDimensional.of_injective CuspForm.toModularFormₗ CuspForm.toModularFormₗ_injective
    have hΓ : (1 : ℝ) ∈ (MTT.GammaOne 4).strictPeriods := by
      change (1 : ℝ) ∈ (CongruenceSubgroup.Gamma1 4 : Subgroup (GL (Fin 2) ℝ)).strictPeriods
      rw [CongruenceSubgroup.strictPeriods_Gamma1]
      exact AddSubgroup.mem_zmultiples 1
    have hd := CuspForm.finrank_lower_bound_of_weighted_forms
      (by decide : 0 < 2) hr A B D 1 (by norm_num) hΓ
      (PowerSeries.order_eq_order.trans hA) (PowerSeries.order_eq_order.trans hB) hD
    obtain ⟨m, hm⟩ := hko
    omega
  · obtain ⟨m, hm⟩ := hko
    have : k - 3 = 0 := by omega
    rw [this]
    exact Nat.zero_le _

end privateSection

public section publicSection

theorem MTT.Cohomology.cuspForm_finrank_lower_bound_level_four_odd {k : ℕ}
    (hk : 3 ≤ k) (hko : Odd k) :
    k - 3 ≤ 2 * Module.finrank ℂ (CuspForm (MTT.GammaOne 4) (k : ℤ)) := _root_.solution hk hko

end publicSection
