/-
Based on Prove2Me node MTT.Cohomology.gammaOne_cuspForm_dimension_lower_bound
(d82b9cd5-a47c-4f45-bb73-6d8ba3678666) by cbirkbeck (2026-09-07).

Proof based on Prove2Me submission 1f695e97-6a94-492b-9687-a4f864e641f3
by cbirkbeck (2026-09-07); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.GroupTheory.DoubleCoset
public import Mathlib.NumberTheory.ModularForms.Basic

import Theorems.MTT.Thm_MTT_Cohomology_finrank_modularForm_le_cuspForm_add_doubleCosets
import Theorems.FLT.Thm_ModularForm_finiteDimensional_of_isArithmetic
import Theorems.FLT.Thm_ModularForm_exists_linearIndependent_gamma1_dimFormula_le_card

/-!
# Higher-weight Gamma1 cusp forms satisfy the dimension-formula lower bound

Theorem statement: `MTT.Cohomology.gammaOne_cuspForm_dimension_lower_bound`
(`d82b9cd5-a47c-4f45-bb73-6d8ba3678666`), by cbirkbeck, 2026-09-07.

Proof: submission `1f695e97-6a94-492b-9687-a4f864e641f3`, by cbirkbeck, 2026-09-07 (ACCEPTED);
locally adapted.

Let $N\ge 5$ and $k\ge 3$ be natural numbers. Put $\mu=[\mathrm{SL}_2(\mathbb
Z):\langle\Gamma_1(N),-I\rangle]$ and let $c$ be the cardinality of
$\Gamma_1(N)\backslash\mathrm{SL}_2(\mathbb Z)/\langle T,-I\rangle$, where $T$ is the translation
matrix. Then the complex vector space of weight-$k$ cusp forms satisfies

$$(k-1)\mu\le 12\dim_{\mathbb C}S_k(\Gamma_1(N))+6c.$$

This is the lower-bound direction of the torsion-free, regular-cusp dimension formula. It is
independent of the MTT period-map injectivity proof and supplies the analytic dimension input for
the higher-level parabolic-cohomology upper-bound strategy. No cohomology bound or equality of
dimensions is asserted.

## Explanation of the source proof

Write μ for the index of the subgroup generated by Γ₁(N) and -I, and c for the cusp double-coset
count. The existing PROVED theorem ModularForm.exists_linearIndependent_gamma1_dimFormula_le_card
(e52e7754-dd59-54dc-8282-e638ce354cfe; accepted proof 938c3173-ee4f-5f3a-bbcb-7e51cd60b0e7) supplies
d linearly independent modular forms with (k-1)μ + 6c ≤ 12d, for N≥5 and k≥3. Hence d≤dim M_k. The
new cusp-codimension theorem 9f6c61f4-df4d-4542-88d1-63a18b965ed7 gives dim M_k≤dim S_k+c. Combining
and cancelling 6c gives precisely (k-1)μ≤12 dim S_k+6c.

This is the lower-bound direction of Stein, Modular Forms: A Computational Approach, Chapter 6,
Proposition 6.6, N≥5 case, with the preceding genus formula substituted and denominators cleared:
https://wstein.org/books/modform/modform/dimension_formulas.html. The Riemann–Roch modular-form
input is explicitly reused from the platform, not claimed as a new proof. Finite dimensionality is
supplied by the already-PROVED ModularForm.finiteDimensional_of_isArithmetic
(fec292ab-0757-5b48-a9bc-a13e34bc1b49).

The standalone proof imports only these three theorem modules and uses default Lean resource limits.
Local theorem mirrors contain the expected by-sorry statements; the submitted proof itself contains
no sorry, custom axiom, native_decide or resource override. The cohomological upper bound and levels
2, 3 and 4 remain separate work.

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

open scoped MatrixGroups

theorem solution {N k : ℕ} (hN : 5 ≤ N) (hk : 3 ≤ k) :
    (k - 1) * (CongruenceSubgroup.Gamma1 N ⊔ Subgroup.zpowers (-1 : SL(2, ℤ))).index ≤
      12 * Module.finrank ℂ (CuspForm (CongruenceSubgroup.Gamma1 N) (k : ℤ)) +
        6 * Nat.card (DoubleCoset.Quotient (CongruenceSubgroup.Gamma1 N : Set SL(2, ℤ))
          ((Subgroup.zpowers ModularGroup.T ⊔ Subgroup.zpowers (-1) : Subgroup SL(2, ℤ)) :
            Set SL(2, ℤ))) := by
  have : NeZero N := ⟨by omega⟩
  have := ModularForm.finiteDimensional_of_isArithmetic
    ((CongruenceSubgroup.Gamma1 N).map (Matrix.SpecialLinearGroup.mapGL ℝ)) (k : ℤ)
  obtain ⟨d, f, hli, hd⟩ :=
    ModularForm.exists_linearIndependent_gamma1_dimFormula_le_card N hN k hk
  have hf : d ≤ Module.finrank ℂ (ModularForm (CongruenceSubgroup.Gamma1 N) (k : ℤ)) := by
    simpa only [Fintype.card_fin] using hli.fintype_card_le_finrank
  have hc := MTT.Cohomology.finrank_modularForm_le_cuspForm_add_doubleCosets
    (CongruenceSubgroup.Gamma1 N) (k : ℤ)
  omega
end

end privateSection

public section publicSection

open scoped MatrixGroups

theorem MTT.Cohomology.gammaOne_cuspForm_dimension_lower_bound {N k : ℕ} (hN : 5 ≤ N) (hk : 3 ≤ k) :
    (k - 1) * (CongruenceSubgroup.Gamma1 N ⊔ Subgroup.zpowers (-1 : SL(2, ℤ))).index ≤
      12 * Module.finrank ℂ (CuspForm (CongruenceSubgroup.Gamma1 N) (k : ℤ)) +
        6 * Nat.card (DoubleCoset.Quotient (CongruenceSubgroup.Gamma1 N : Set SL(2, ℤ))
          ((Subgroup.zpowers ModularGroup.T ⊔ Subgroup.zpowers (-1) : Subgroup SL(2, ℤ)) :
            Set SL(2, ℤ))) := _root_.solution hN hk

end publicSection
