import Definitions.MTT.Def_MTT_ParabolicCohomology
import Mathlib.RepresentationTheory.Homological.GroupCohomology.LowDegree
import Mathlib.GroupTheory.Finiteness
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.GroupTheory.Schreier
import Mathlib.LinearAlgebra.Matrix.FixedDetMatrices
import Mathlib.LinearAlgebra.Dimension.Constructions

section

/-!
# Finite-dimensional one-cocycles

A one-cocycle is determined by its values on group generators. Restriction to
a finite generating set therefore embeds the cocycle space into a finite power
of the coefficient module. This is the finite-generation input for the MTT
parabolic-cohomology dimension argument; it assumes no Eichler–Shimura theorem.
-/

noncomputable section

universe u

namespace groupCohomology

variable {K G : Type u} [Field K] [Group G] {A : Rep K G}

/-- One-cocycles agreeing on a generating set agree everywhere. -/
theorem cocycles₁_ext_of_generators {s : Set G} (hs : Subgroup.closure s = ⊤)
    {f g : cocycles₁ A} (hfg : ∀ x ∈ s, f x = g x) : f = g := by
  apply cocycles₁_ext
  intro x
  have hx : x ∈ Subgroup.closure s := hs ▸ Subgroup.mem_top x
  induction hx using Subgroup.closure_induction with
  | mem x hx => exact hfg x hx
  | one => simp only [cocycles₁_map_one]
  | mul x y _ _ hx hy =>
      rw [(mem_cocycles₁_iff f).1 f.property,
        (mem_cocycles₁_iff g).1 g.property, hx, hy]
  | inv x _ hx =>
      have hf := (mem_cocycles₁_iff f).1 f.property x⁻¹ x
      have hg := (mem_cocycles₁_iff g).1 g.property x⁻¹ x
      simp only [inv_mul_cancel, cocycles₁_map_one, hx] at hf hg
      exact add_left_cancel (hf.symm.trans hg)

/-- Finite generation of the group bounds the dimension of the one-cocycle space. -/
theorem finiteDimensional_cocycles₁ [Group.FG G] [FiniteDimensional K A] :
    FiniteDimensional K (cocycles₁ A) := by
  classical
  obtain ⟨s, hs, hfin⟩ := Group.fg_iff.mp (inferInstance : Group.FG G)
  let : Fintype s := hfin.fintype
  let ev : cocycles₁ A →ₗ[K] (s → A) :=
    LinearMap.pi fun x => (LinearMap.proj (x : G)).comp (cocycles₁ A).subtype
  apply FiniteDimensional.of_injective ev
  intro f g hfg
  apply cocycles₁_ext_of_generators hs
  intro x hx
  exact congrFun hfg ⟨x, hx⟩

end groupCohomology

end
end

section

/-!
# Finite-dimensional parabolic cohomology for Gamma1(N)

SL2(Z) is generated by S and T; Schreier's theorem gives finite generation of
Gamma1(N) for positive N. Its homogeneous binary coefficient module is finite,
and the cocycle space embeds in a finite product of that module. Subspaces and
quotients preserve finite-dimensionality. No cusp-form dimension formula is used.
-/

noncomputable section

namespace MTT.Cohomology

open groupCohomology

theorem finiteDimensional_parabolicCocycles (N n : ℕ) [NeZero N] :
    FiniteDimensional ℂ (parabolicCocycles N n) := by
  have : Group.FG (Matrix.SpecialLinearGroup (Fin 2) ℤ) :=
    Group.fg_iff.mpr ⟨{ModularGroup.S, ModularGroup.T},
      SpecialLinearGroup.SL2Z_generators, Set.toFinite _⟩
  have : FiniteDimensional ℂ (gammaOneRep N n) :=
    Module.Finite.of_fg (MvPolynomial.homogeneousSubmodule_fg (Fin 2) ℂ n)
  have : FiniteDimensional ℂ (cocycles₁ (gammaOneRep N n)) := finiteDimensional_cocycles₁
  let ι : parabolicCocycles N n →ₗ[ℂ] cocycles₁ (gammaOneRep N n) :=
    Submodule.inclusion (show parabolicCocycles N n ≤ cocycles₁ (gammaOneRep N n)
      from inf_le_left)
  exact FiniteDimensional.of_injective ι (Submodule.inclusion_injective _)

theorem finiteDimensional_parabolicH1 (N n : ℕ) [NeZero N] :
    FiniteDimensional ℂ (ParabolicH1 N n) := by
  have := finiteDimensional_parabolicCocycles N n
  infer_instance

end MTT.Cohomology

end
end

noncomputable section

theorem solution {N n : ℕ} (hN : 0 < N) :
    FiniteDimensional ℂ (MTT.Cohomology.ParabolicH1 N n) := by
  have : NeZero N := ⟨Nat.ne_of_gt hN⟩
  exact MTT.Cohomology.finiteDimensional_parabolicH1 N n

