/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

import TauCeti.Algebra.Group.Subgroup.ZPowers

/-!
# Membership in a subgroup of a cyclic group, by index

In a group generated by `g`, a power `g ^ n` lies in a subgroup `K` exactly when the index of `K`
divides `n`: the exponents landing in `K` are the multiples of `K.index`. When `K` has finite
index that makes `K.index` the least positive such exponent; when it does not, no positive exponent
lands in `K` at all, and both readings agree through the convention `index = 0`.

## Main results

* `Subgroup.zpow_mem_iff_index_dvd`: `g ^ n ∈ K ↔ (K.index : ℤ) ∣ n` for `n : ℤ`, with `g` a
  generator.
* `Subgroup.pow_mem_iff_index_dvd`: the same for a natural exponent.
* `Subgroup.isLeast_pow_mem_index`: when `K` has finite index, `K.index` **is** the least positive
  exponent with `g ^ n ∈ K`, with `AddSubgroup.isLeast_nsmul_mem_index` its additive form.
* `Subgroup.isLeast_pow_mem_relIndex_zpowers`: when `H` has finite relative index in `⟨g⟩`, that
  relative index is the least positive exponent with `g ^ n ∈ H`. No generator hypothesis is needed
  here, `g` generating `⟨g⟩`; `AddSubgroup.isLeast_nsmul_mem_relIndex_zmultiples` is the additive
  form.
-/

public section

namespace Subgroup

variable {G : Type*} [Group G] {g : G}

-- Source. The statement is specified by the Chebotarev roadmap:
-- `TauCetiRoadmap/Chebotarev/README.md` §8.2 asks for the residue degree `f(𝔓/𝔭)` as the least
-- `n ≥ 1` with `Frob_{L/K}(Q)^n ∈ ⟨σ⟩`, and pins it at
-- `TauCetiRoadmap/Chebotarev/Suggested.lean` as `inertiaDeg_fixedField_eq_one_iff`.

/-- **Membership in a subgroup of a cyclic group is divisibility of the index.** If `g` generates
`G`, then `g ^ n` lies in `K` exactly when `K.index` divides `n`.

This is the criterion a fibre-selection argument wants: it turns a membership test on powers of a
generator into arithmetic in `ℤ`, and identifies `K.index` as the least positive exponent landing
in `K`.

No finiteness is assumed. If `K` has infinite index its index is `0` by convention, and the
statement reads `g ^ n ∈ K ↔ n = 0`. -/
@[to_additive (attr := simp)
/-- **Membership in a subgroup of an additive cyclic group is divisibility of the index.** If `g`
generates `G`, then `n • g` lies in `K` exactly when `K.index` divides `n`. -/]
theorem zpow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℤ) :
    g ^ n ∈ K ↔ (K.index : ℤ) ∣ n := by
  have : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr ⟨g, hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  have hgen : zpowers (QuotientGroup.mk' K g) = ⊤ := by
    rw [← MonoidHom.map_zpowers, hg, ← MonoidHom.range_eq_map]
    exact MonoidHom.range_eq_top.mpr (QuotientGroup.mk'_surjective K)
  have horder : orderOf (QuotientGroup.mk' K g) = K.index :=
    (orderOf_eq_card_of_zpowers_eq_top hgen).trans K.index_eq_card.symm
  rw [← horder, orderOf_dvd_iff_zpow_eq_one, ← map_zpow, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]

/-- **The natural-exponent form.** `g ^ n ∈ K ↔ K.index ∣ n`, the case `n : ℕ` of
`zpow_mem_iff_index_dvd`. -/
@[to_additive (attr := simp)
/-- **The natural-exponent form.** `n • g ∈ K ↔ K.index ∣ n`. -/]
theorem pow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℕ) :
    g ^ n ∈ K ↔ K.index ∣ n := by
  rw [← zpow_natCast, zpow_mem_iff_index_dvd K hg, Int.natCast_dvd_natCast]

/-- **The index is the least exponent that lands in `K`.**  For a generator `g` of `G` and a
subgroup `K` of finite index, `K.index` is the smallest `n ≥ 1` with `g ^ n ∈ K`.

This is the finite-index reading of `pow_mem_iff_index_dvd`: the exponents landing in `K` are the
multiples of `K.index`, so the least positive one is the index itself. -/
@[to_additive
/-- **The index is the least multiple that lands in `K`.**  For a generator `g` of `G` and a
subgroup `K` of finite index, `K.index` is the smallest `n ≥ 1` with `n • g ∈ K`. -/]
theorem isLeast_pow_mem_index (K : Subgroup G) (hg : zpowers g = ⊤) [K.FiniteIndex] :
    IsLeast {n : ℕ | 0 < n ∧ g ^ n ∈ K} K.index :=
  ⟨⟨Nat.pos_of_ne_zero FiniteIndex.index_ne_zero, (pow_mem_iff_index_dvd K hg _).2 dvd_rfl⟩,
    fun _ hn ↦ Nat.le_of_dvd hn.1 ((pow_mem_iff_index_dvd K hg _).1 hn.2)⟩

/-- **The relative index in a cyclic subgroup is the least exponent that lands in `H`.**  When `H`
has finite relative index in `⟨g⟩`, that index is the smallest `n ≥ 1` with `g ^ n ∈ H`.

Unlike `isLeast_pow_mem_index`, no hypothesis on `g` is needed: `g` generates `⟨g⟩`, so this
applies to an arbitrary element of an arbitrary group, asking only that `H ⊓ ⟨g⟩` have finite
index in `⟨g⟩`. Use it when the quantity wanted is the least power of a given element that lies
in a given subgroup. -/
@[to_additive
/-- **The relative index in a cyclic subgroup is the least multiple that lands in `H`.**  When `H`
has finite relative index in `⟨g⟩`, that index is the smallest `n ≥ 1` with `n • g ∈ H`. -/]
theorem isLeast_pow_mem_relIndex_zpowers (g : G) (H : Subgroup G)
    [H.IsFiniteRelIndex (zpowers g)] :
    IsLeast {n : ℕ | 0 < n ∧ g ^ n ∈ H} (H.relIndex (zpowers g)) := by
  have hset : {n : ℕ | 0 < n ∧ g ^ n ∈ H}
      = {n : ℕ | 0 < n ∧ (⟨g, mem_zpowers g⟩ : ↥(zpowers g)) ^ n
          ∈ H.subgroupOf (zpowers g)} := by
    ext n
    simp [Subgroup.mem_subgroupOf]
  rw [hset, relIndex]
  exact isLeast_pow_mem_index (H.subgroupOf (zpowers g)) (zpowers_mk_self_eq_top g)

end Subgroup
