/-
Based on Prove2Me node AlgebraicCurve.Place.adicValuation_isTrivialOn
(5ca17c5e-d2aa-5bb0-ad8c-7d8e397d95c6) by Claude (2026-09-05).

Proof based on Prove2Me submission 7d141da6-77db-5781-be8b-2fb2cd60d7ba
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_P2M_Util

/-!
# The adic valuation of a place is trivial on the base field

Theorem statement: `AlgebraicCurve.Place.adicValuation_isTrivialOn`
(`5ca17c5e-d2aa-5bb0-ad8c-7d8e397d95c6`), by Claude, 2026-09-05.

Proof: submission `7d141da6-77db-5781-be8b-2fb2cd60d7ba`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of the structure [`AlgebraicCurve.Place`](def/AlgebraicCurve_DivisorClassGroup.html#L22): a
valuation subring $\mathcal{O}_v \subseteq F$ which contains $\mathrm{algebraMap}\,K\,F(a)$ for
every $a \in K$, which is not the whole of $F$, and whose ideals are all principal (so that
$\mathcal{O}_v$ is a discrete valuation ring). Attached to $v$ is its height one prime
[`AlgebraicCurve.Place.heightOneSpectrum`](def/AlgebraicCurve_DivisorClassGroup.html#L95), namely
the maximal ideal of $\mathcal{O}_v$ viewed as a point of the height one spectrum, and the
associated $\mathbb{Z}^{m0}$-valued adic valuation
[`AlgebraicCurve.Place.adicValuation`](def/AlgebraicCurve_DivisorClassGroup.html#L102) on the
fraction field $F$, i.e. the normalised valuation whose value group is $\mathbb{Z}$ with a zero
adjoined. The theorem asserts that this valuation satisfies `Valuation.IsTrivialOn K`, that is, it
is trivial on the image of the base field $K$ in $F$: no element of $K$ has a zero or a pole at $v$.

This is the standard fact, in the language of algebraic function fields, that a place of $F/K$ is a
place over $K$, so that the base field consists of $v$-units; it records the triviality of $v$ on
$K$ in a form usable as an instance or hypothesis elsewhere. It is used in the analysis of valuation
subrings of a rational function field, via
[`AlgebraicCurve.RationalFunctionField.toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum`](thm.html#AlgebraicCurve.RationalFunctionField.toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_adicValuation_isTrivialOn.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_adicValuation_isTrivialOn

open IsDedekindDomain WithZero IsLocalRing

noncomputable section

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ext heightOneSpectrum adicValuation algebraMap_mem' toValuationSubring"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

private theorem _root_.AlgebraicCurve.Place.adicValuation_valuationSubring :
    v.adicValuation.valuationSubring = v.toValuationSubring := by
  ext x
  rw [Valuation.mem_valuationSubring_iff]
  constructor
  · intro hx
    obtain ⟨a, rfl⟩ := IsDiscreteValuationRing.exists_lift_of_le_one hx
    exact a.2
  · intro hx
    exact v.heightOneSpectrum.valuation_le_one (⟨x, hx⟩ : v.toValuationSubring)

p2m_export "AlgebraicCurve.Place" "adicValuation_valuationSubring"
private theorem _root_.AlgebraicCurve.Place.mem_iff_adicValuation_le_one {f : F} :
    f ∈ v.toValuationSubring ↔ v.adicValuation f ≤ 1 := by
  rw [← v.adicValuation_valuationSubring]
  exact Valuation.mem_valuationSubring_iff _ _

p2m_export "AlgebraicCurve.Place" "mem_iff_adicValuation_le_one"
private theorem rowMain : v.adicValuation.IsTrivialOn K :=
  Valuation.IsTrivialOn.of_le_one v.adicValuation fun a =>
    v.mem_iff_adicValuation_le_one.mp (v.algebraMap_mem' a)

end Place

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_Place_adicValuation_isTrivialOn.AlgebraicCurve in
theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) :
    v.adicValuation.IsTrivialOn K :=
  AlgebraicCurve.Place.rowMain v

end S_AlgebraicCurve_Place_adicValuation_isTrivialOn
end P2MW
export P2MW.S_AlgebraicCurve_Place_adicValuation_isTrivialOn (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Place.adicValuation_isTrivialOn {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) :
    v.adicValuation.IsTrivialOn K := _root_.P2MW.S_AlgebraicCurve_Place_adicValuation_isTrivialOn.solution v

end publicSection
