/-
Based on Prove2Me node AlgebraicCurve.Divisor.pushforwardAlong_pushforwardAlong
(bd1d7d23-52ed-54d1-b5fa-449c84c904d3) by Claude (2026-09-05).

Proof based on Prove2Me submission 1c9fc3ae-866c-5271-b3b3-14d688758cdc
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_Correspondence

import Theorems.FLT.Thm_AlgebraicCurve_Place_inertiaDegAlong_comp
import Theorems.FLT.Thm_AlgebraicCurve_Place_restrictAlong_restrictAlong
import Definitions.FLT.Def_P2M_Util

/-!
# Functoriality of divisor push-forward along composites

Theorem statement: `AlgebraicCurve.Divisor.pushforwardAlong_pushforwardAlong`
(`bd1d7d23-52ed-54d1-b5fa-449c84c904d3`), by Claude, 2026-09-05.

Proof: submission `1c9fc3ae-866c-5271-b3b3-14d688758cdc`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$, $F$, $F'$, $F''$ be fields, each of $F$, $F'$, $F''$ equipped with a $K$-algebra structure,
let $\varphi \colon F \to F'$ and $\chi \colon F' \to F''$ be $K$-algebra homomorphisms, and assume
that the underlying ring homomorphisms of $\varphi$, of $\chi$, and of the composite $\chi \circ
\varphi$ are integral (the last being assumed separately, not deduced). Let $D$ be a divisor of
$F''$ over $K$, that is, a finitely supported function with values in $\mathbb{Z}$ on the set of
places of $F''$ over $K$, a place being a valuation subring of $F''$ that contains the image of $K$,
is not all of $F''$, and is a principal ideal ring. Then pushing $D$ forward along $\chi$ and then
pushing the result forward along $\varphi$ gives the same divisor of $F$ over $K$ as pushing $D$
forward along $\chi \circ \varphi$. Here the push-forward along an integral $K$-algebra map is the
additive map that sends a place $W$ of the larger field, with multiplicity $n$, to its restriction
to the smaller field with multiplicity $n$ times the inertia degree of $W$ over that restriction.

This is the transitivity (functoriality) of the push-forward of divisors in a tower of integral
extensions of function fields over $K$, reflecting the multiplicativity of residue degrees in
towers. It is used throughout the theory of divisor correspondences, for instance in the composition
law for correspondences and in comparisons of a correspondence with a scalar multiple of another.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Divisor_pushforwardAlong_pushforwardAlong.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Divisor_pushforwardAlong_pushforwardAlong

open IsDedekindDomain AlgebraicCurve

theorem solution {K F F' F'' : Type*} [Field K] [Field F] [Field F'] [Field F''] [Algebra K F] [Algebra K F'] [Algebra K F''] (φ : F →ₐ[K] F') (χ : F' →ₐ[K] F'') (hφ : φ.toRingHom.IsIntegral) (hχ : χ.toRingHom.IsIntegral) (hχφ : (χ.comp φ).toRingHom.IsIntegral) (D : Divisor K F'') : Divisor.pushforwardAlong φ hφ (Divisor.pushforwardAlong χ hχ D) = Divisor.pushforwardAlong (χ.comp φ) hχφ D := by
  have key : (Divisor.pushforwardAlong φ hφ).comp (Divisor.pushforwardAlong χ hχ)
      = Divisor.pushforwardAlong (χ.comp φ) hχφ := by
    refine Finsupp.addHom_ext fun W n => ?_
    show Divisor.pushforwardAlong φ hφ (Divisor.pushforwardAlong χ hχ (Finsupp.single W n))
        = Divisor.pushforwardAlong (χ.comp φ) hχφ (Finsupp.single W n)
    rw [Divisor.pushforwardAlong_single, Divisor.pushforwardAlong_single, Divisor.pushforwardAlong_single,
      AlgebraicCurve.Place.restrictAlong_restrictAlong φ χ hφ hχ hχφ,
      AlgebraicCurve.Place.inertiaDegAlong_comp φ χ hφ hχ hχφ W]
    refine congrArg (Finsupp.single _) ?_
    push_cast
    ring
  exact DFunLike.congr_fun key D

end S_AlgebraicCurve_Divisor_pushforwardAlong_pushforwardAlong
end P2MW
export P2MW.S_AlgebraicCurve_Divisor_pushforwardAlong_pushforwardAlong (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Divisor.pushforwardAlong_pushforwardAlong {K F F' F'' : Type*} [Field K] [Field F] [Field F'] [Field F''] [Algebra K F] [Algebra K F'] [Algebra K F''] (φ : F →ₐ[K] F') (χ : F' →ₐ[K] F'') (hφ : φ.toRingHom.IsIntegral) (hχ : χ.toRingHom.IsIntegral) (hχφ : (χ.comp φ).toRingHom.IsIntegral) (D : Divisor K F'') : Divisor.pushforwardAlong φ hφ (Divisor.pushforwardAlong χ hχ D) = Divisor.pushforwardAlong (χ.comp φ) hχφ D := _root_.P2MW.S_AlgebraicCurve_Divisor_pushforwardAlong_pushforwardAlong.solution φ χ hφ hχ hχφ D

end publicSection
