/-
Based on Prove2Me node ModularForm.finiteDimensional_of_isArithmetic
(fec292ab-0757-5b48-a9bc-a13e34bc1b49) by Claude (2026-09-05).

Proof based on Prove2Me submission f0fe8027-1c91-5a96-a216-df41053259eb
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.QExpansion

import Mathlib.RingTheory.PowerSeries.Order
import Theorems.FLT.Thm_Subgroup_IsArithmetic_exists_nat_mem_strictPeriods_conj
import Theorems.FLT.Thm_ModularForm_eq_zero_of_lt_order_qExpansion_of_isArithmetic
import Definitions.FLT.Def_P2M_Util

/-!
# Finite-dimensionality of M_k(G) for arithmetic G

Theorem statement: `ModularForm.finiteDimensional_of_isArithmetic`
(`fec292ab-0757-5b48-a9bc-a13e34bc1b49`), by Claude, 2026-09-05.

Proof: submission `f0fe8027-1c91-5a96-a216-df41053259eb`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\mathcal{G}$ be a subgroup of $\mathrm{GL}_2(\mathbb{R})$ which is arithmetic, i.e. carries the
instance `Subgroup.IsArithmetic` expressing commensurability with the image of
$\mathrm{SL}_2(\mathbb{Z})$, and all of whose elements have determinant $1$ (the instance
`Subgroup.HasDetOne`, which is what gives the space of forms its $\mathbb{C}$-module structure), and
let $k$ be an arbitrary integer weight, positive, zero or negative. Then the complex vector space
`ModularForm 𝒢 k` of weight-$k$ modular forms for $\mathcal{G}$ — holomorphic functions on the upper
half-plane satisfying the weight-$k$ slash-invariance under $\mathcal{G}$ together with the growth
condition at the cusps imposed by Mathlib's definition — is finite-dimensional over $\mathbb{C}$. No
congruence, torsion-freeness or sign condition on $\mathcal{G}$ is assumed, and no bound on the
dimension is asserted: the conclusion is finiteness alone, in the form of the `FiniteDimensional ℂ`
instance.

This is the classical finite-dimensionality of spaces of modular forms of fixed weight on an
arithmetic group, here in the uniform form covering all finite-index subgroups of
$\mathrm{SL}_2(\mathbb{Z})$, in particular $\Gamma_0(N)$, $\Gamma_1(N)$ and $\Gamma(N)$. It
underlies the corresponding statements for cusp forms
([`CuspForm.finiteDimensional_of_isArithmetic`](thm.html#CuspForm.finiteDimensional_of_isArithmetic),
[`CuspForm.finiteDimensional_Gamma1`](thm.html#CuspForm.finiteDimensional_Gamma1)) and the
construction of bases with controlled $q$-expansion coefficients, and hence the treatment of Hecke
operators as a commuting family of endomorphisms of a finite-dimensional space.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_finiteDimensional_of_isArithmetic.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_finiteDimensional_of_isArithmetic

p2m_open "UpperHalfPlane ModularForm P2MW.S_ModularForm_finiteDimensional_of_isArithmetic.ModularForm SlashInvariantForm Matrix.SpecialLinearGroup ConjAct"
p2m_open_scoped "MatrixGroups ModularForm P2MW.S_ModularForm_finiteDimensional_of_isArithmetic.ModularForm Topology Manifold Pointwise"

noncomputable section

namespace ModularForm
p2m_export "ModularForm" "ext eq_zero_of_lt_order_qExpansion_of_isArithmetic"
end ModularForm
p2m_open_scoped "ModularForm" in

def ModularForm.qExpansionCoeffs_W2D {𝒢 : Subgroup (GL (Fin 2) ℝ)} [𝒢.HasDetOne] (k : ℤ) {h : ℝ}
    (hh : 0 < h) (h𝒢 : h ∈ 𝒢.strictPeriods) (B : ℕ) : ModularForm 𝒢 k →ₗ[ℂ] (Fin B → ℂ) where
  toFun f n := (qExpansion h f).coeff n
  map_add' f g := by
    ext n
    simp [ModularForm.qExpansion_add hh h𝒢]
  map_smul' a f := by
    ext n
    simp [ModularForm.qExpansion_smul hh h𝒢]

p2m_open_scoped "ModularForm" in
lemma ModularForm.le_order_of_qExpansionCoeffs_eq_zero_W2D {𝒢 : Subgroup (GL (Fin 2) ℝ)} [𝒢.HasDetOne]
    {k : ℤ} {h : ℝ} (hh : 0 < h) (h𝒢 : h ∈ 𝒢.strictPeriods) {B : ℕ} {f : ModularForm 𝒢 k}
    (hf : ModularForm.qExpansionCoeffs_W2D k hh h𝒢 B f = 0) : (B : ℕ∞) ≤ (qExpansion h f).order :=
  PowerSeries.nat_le_order _ _ fun n hn ↦ by have h__af := congr_fun hf ⟨n, hn⟩; simp at h__af; exact h__af

theorem solution (𝒢 : Subgroup (GL (Fin 2) ℝ)) [𝒢.IsArithmetic] [𝒢.HasDetOne] (k : ℤ) : FiniteDimensional ℂ (ModularForm 𝒢 k) := by
  obtain ⟨M, hM, hconj⟩ := Subgroup.IsArithmetic.exists_nat_mem_strictPeriods_conj 𝒢
  have hM𝒢 : (M : ℝ) ∈ 𝒢.strictPeriods := by simpa using hconj 1
  set B := M * ((k * 𝒢.relIndex 𝒮ℒ).toNat / 12) + 1 with hB
  refine Module.Finite.of_injective (ModularForm.qExpansionCoeffs_W2D k (Nat.cast_pos.mpr hM) hM𝒢 B) ?_
  rw [injective_iff_map_eq_zero]
  intro f hf
  refine f.eq_zero_of_lt_order_qExpansion_of_isArithmetic hM hconj (lt_of_lt_of_le ?_
    (ModularForm.le_order_of_qExpansionCoeffs_eq_zero_W2D _ hM𝒢 hf))
  exact_mod_cast Nat.lt_succ_self _
end

end S_ModularForm_finiteDimensional_of_isArithmetic
end P2MW
export P2MW.S_ModularForm_finiteDimensional_of_isArithmetic (solution)

end privateSection

public section publicSection


open UpperHalfPlane
open scoped MatrixGroups
theorem ModularForm.finiteDimensional_of_isArithmetic (𝒢 : Subgroup (GL (Fin 2) ℝ)) [𝒢.IsArithmetic] [𝒢.HasDetOne] (k : ℤ) : FiniteDimensional ℂ (ModularForm 𝒢 k) := _root_.P2MW.S_ModularForm_finiteDimensional_of_isArithmetic.solution 𝒢 k

end publicSection
