/-
Based on Prove2Me node ModularCurve.exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces
(d9c59f6a-f97d-52a7-8ac4-7a0df55b14f2) by Claude (2026-09-05).

Proof based on Prove2Me submission c5ebd8ec-b1d8-5444-a630-0a1a2eea9ae0
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
public import Definitions.FLT.Def_ModularCurve_JLinePlaces

import Mathlib.Analysis.Normed.Field.Lemmas
import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceClassification
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_ofHeightOneSpectrum_of_span
import Definitions.FLT.Def_P2M_Util

/-!
# Ramification index equals ord_w(p(j)) away from 0,1728,∞

Theorem statement:
`ModularCurve.exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces`
(`d9c59f6a-f97d-52a7-8ac4-7a0df55b14f2`), by Claude, 2026-09-05.

Proof: submission `c5ebd8ec-b1d8-5444-a630-0a1a2eea9ae0`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix $N\ge 1$ and let $j\in\mathbb{Q}((q))$ denote the Laurent series
[`ModularCurve.jq`](def/ModularCurve_X0.html#L157); the field $F_N=$
[`ModularCurve.modularFunctionField N`](def/ModularCurve_X0.html#L250) is the subfield of
$\mathbb{Q}((q))$ generated over $\mathbb{Q}$ by $j$ and by its $N$-fold $q$-rescaling, viewed as an
algebra over the intermediate field $\mathbb{Q}\langle j\rangle$ via
[`ModularCurve.jAdjoinAlgebra`](def/ModularCurve_JLinePlaces.html#L19), and it is assumed that $F_N$
is integral over $\mathbb{Q}\langle j\rangle$. Let $w$ be a place of $F_N$ over $\mathbb{Q}$, that
is, a proper valuation subring of $F_N$ containing the image of $\mathbb{Q}$ whose ring is a
principal ideal ring. Suppose the restriction of $w$ to $\mathbb{Q}\langle j\rangle$ (the preimage
valuation subring) is none of the three places `jLinePlace1728`, `jLinePlaceZero`,
`jLinePlaceInfty`, obtained by transporting along the isomorphism
$\mathbb{Q}(T)\cong\mathbb{Q}\langle j\rangle$, $T\mapsto j$, the places of $\mathbb{Q}(T)$ attached
to $T-1728$, to $T$, and to the point at infinity. Then there is a monic irreducible
$p\in\mathbb{Q}[X]$ with $p(0)\neq 0$ and $p(1728)\neq 0$ such that $\mathrm{ord}_w(p(j))>0$ and the
ramification index of $w$ over $\mathbb{Q}\langle j\rangle$ — the least $n>0$ of the form
$\mathrm{ord}_w(f)$ for some nonzero $f$ in the base field — equals $\mathrm{ord}_w(p(j))$, where
$\mathrm{ord}_w$ is the normalised additive valuation of $w$ and $p(j)$ denotes the evaluation of
$p$ at $j\in F_N$.

This identifies, for a place of the function field of $X_0(N)$ lying over a closed point of the
$j$-line other than $j=0$, $j=1728$ or $j=\infty$, a uniformiser of the base obtained from the monic
irreducible polynomial cutting out that closed point, so that the local ramification index is
computed as $\mathrm{ord}_w(p(j))$. It is the input used in counting the places where
$\mathrm{ord}_w(j)=1$ and where $\mathrm{ord}_w(j-1728)=1$, i.e. in the computations of the elliptic
point counts $\nu_3$ and $\nu_2$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces
p2m_attr_erase "instance" "AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

set_option synthInstance.maxHeartbeats 1600000

open IntermediateField AlgebraicCurve AlgebraicCurve.RationalFunctionField Polynomial

attribute [local instance 2000] RatFunc.instAlgebraOfPolynomial
attribute [local instance] ModularCurve.instDecidableEqRatFuncRat

namespace ModularCurve
p2m_export "ModularCurve" "jAdjoinAlgebra algebraMap_jGen_val jLineRingEquiv jLineRingEquiv_X instDecidableEqRatFuncRat jLinePlace1728 jLinePlaceZero jLinePlaceInfty jq modularFunctionField jq_mem jGen"
namespace JLineFiniteAux
p2m_open "ModularCurve"

theorem exists_eq_congr (v : Place ℚ ↥ℚ⟮ModularCurve.jq⟯) :
    ∃ v' : Place ℚ (RatFunc ℚ), v = Place.congrRingEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) v' :=
  ⟨(Place.congrEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom)).symm v,
    ((Place.congrEquiv _ _).apply_symm_apply v).symm⟩

theorem equiv_algebraMap (p : ℚ[X]) :
    ModularCurve.jLineRingEquiv (algebraMap ℚ[X] (RatFunc ℚ) p)
      = Polynomial.aeval ModularCurve.jGen p := by
  have key : ModularCurve.jLineRingEquiv.toRingHom.comp (algebraMap ℚ[X] (RatFunc ℚ))
      = (Polynomial.aeval (R := ℚ) ModularCurve.jGen).toRingHom := by
    refine Polynomial.ringHom_ext (fun c => ?_) ?_
    · rw [RingHom.comp_apply, RatFunc.algebraMap_C, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
        Polynomial.aeval_C]
      exact RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom c
    · rw [RingHom.comp_apply, RatFunc.algebraMap_X, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
        Polynomial.aeval_X]
      exact ModularCurve.jLineRingEquiv_X
  exact RingHom.congr_fun key p

end ModularCurve.JLineFiniteAux

open ModularCurve.JLineFiniteAux in
theorem solution (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)),
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ ≠ ModularCurve.jLinePlace1728 →
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ ≠ ModularCurve.jLinePlaceZero →
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ ≠ ModularCurve.jLinePlaceInfty →
      ∃ p : Polynomial ℚ, Irreducible p ∧ p.Monic ∧ p.eval 0 ≠ 0 ∧ p.eval 1728 ≠ 0 ∧
        0 < w.ord (Polynomial.aeval (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) p) ∧
        (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) = w.ord (Polynomial.aeval (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) p) := by
  let := ModularCurve.jAdjoinAlgebra N
  intro _ w h1728 h0 hinf
  obtain ⟨v', hv'⟩ := exists_eq_congr (w.restrict ↥ℚ⟮ModularCurve.jq⟯)
  have hinf' : v' ≠ placeInfty ℚ := by
    rintro rfl; exact hinf hv'
  have h0' : v' ≠ placeOfPoint ℚ 0 := by
    rintro rfl; exact h0 hv'
  have h1728' : v' ≠ placeOfPoint ℚ 1728 := by
    rintro rfl; exact h1728 hv'
  obtain ⟨P, rfl⟩ : ∃ P : IsDedekindDomain.HeightOneSpectrum ℚ[X], v' = Place.ofHeightOneSpectrum P := by
    rcases eq_ofHeightOneSpectrum_or_eq_placeInfty v' with h | h
    · exact h
    · exact absurd h hinf'
  obtain ⟨g, hgirr, hPg⟩ := exists_irreducible_span ℚ P
  have hg0 : g ≠ 0 := hgirr.ne_zero
  set p : ℚ[X] := normalize g with hp
  have hpg : Associated g p := (associated_normalize g)
  have hpirr : Irreducible p := hpg.irreducible hgirr
  have hpmon : p.Monic := Polynomial.monic_normalize hg0
  have hp0 : p ≠ 0 := hpirr.ne_zero
  have hPp : P.asIdeal = Ideal.span {p} := by
    rw [hPg]; exact Ideal.span_singleton_eq_span_singleton.mpr hpg
  have hordv : (w.restrict ↥ℚ⟮ModularCurve.jq⟯).ord (Polynomial.aeval ModularCurve.jGen p) = 1 := by
    rw [hv', ← equiv_algebraMap, Place.ord_congrRingEquiv]
    exact ord_ofHeightOneSpectrum_of_span P hp0 hPp
  have hj : algebraMap ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N) ModularCurve.jGen
      = (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) :=
    Subtype.ext (ModularCurve.algebraMap_jGen_val N)
  have haeval : Polynomial.aeval (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) p
      = algebraMap ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N) (Polynomial.aeval ModularCurve.jGen p) := by
    rw [← hj, Polynomial.aeval_algebraMap_apply]
  have hordw : w.ord (Polynomial.aeval (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) p)
      = (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) := by
    rw [haeval, w.ord_restrict (F := ↥ℚ⟮ModularCurve.jq⟯), hordv, mul_one]
  have hepos : 0 < (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) := by
    exact_mod_cast w.ramificationIndex_pos (F := ↥ℚ⟮ModularCurve.jq⟯)
  have hroot : ∀ a : ℚ, Place.ofHeightOneSpectrum (K := ℚ) (F := RatFunc ℚ) P ≠ placeOfPoint ℚ a →
      p.eval a ≠ 0 := by
    intro a hne hpa
    apply hne
    have hdvd : (X - C a) ∣ p := dvd_iff_isRoot.mpr hpa
    have hass : Associated (X - C a) p := (irreducible_X_sub_C a).associated_of_dvd hpirr hdvd
    rw [placeOfPoint_eq_ofHeightOneSpectrum]
    congr 1
    ext1
    rw [hPp, heightOneSpectrumOfIrreducible_asIdeal]
    exact Ideal.span_singleton_eq_span_singleton.mpr hass.symm
  refine ⟨p, hpirr, hpmon, hroot 0 h0', hroot 1728 h1728', ?_, hordw.symm⟩
  rw [hordw]; exact hepos

end S_ModularCurve_exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces
end P2MW
export P2MW.S_ModularCurve_exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open IntermediateField AlgebraicCurve
theorem ModularCurve.exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)),
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ ≠ ModularCurve.jLinePlace1728 →
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ ≠ ModularCurve.jLinePlaceZero →
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ ≠ ModularCurve.jLinePlaceInfty →
      ∃ p : Polynomial ℚ, Irreducible p ∧ p.Monic ∧ p.eval 0 ≠ 0 ∧ p.eval 1728 ≠ 0 ∧
        0 < w.ord (Polynomial.aeval (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) p) ∧
        (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) = w.ord (Polynomial.aeval (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) p) := _root_.P2MW.S_ModularCurve_exists_irreducible_ramificationIndex_eq_ord_aeval_of_restrict_ne_jLinePlaces.solution N

end publicSection
