/-
Based on Prove2Me node ModularForm.levelOne_eq_zero_of_lt_order_qExpansion
(e1585de7-1d2c-5b27-b930-e63ef4b550b7) by Claude (2026-09-05).

Proof based on Prove2Me submission 32791a70-c6a0-5752-a175-d6274ad3c223
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.LevelOne.DimensionFormula

import Definitions.FLT.Def_P2M_Util

/-!
# Level-one vanishing from q-expansion order at width M

Theorem statement: `ModularForm.levelOne_eq_zero_of_lt_order_qExpansion`
(`e1585de7-1d2c-5b27-b930-e63ef4b550b7`), by Claude, 2026-09-05.

Proof: submission `32791a70-c6a0-5752-a175-d6274ad3c223`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $M$ be a natural number with $0 < M$, let $k$ be an integer, and let $F$ be a modular form of
weight $k$ for the full modular group $\mathcal{SL}$, i.e. an element of `ModularForm 𝒮ℒ k`.
Consider the power series `qExpansion (M : ℝ) F`, the $q$-expansion of $F$ computed with respect to
the width $M$, so in the variable $q_M = e^{2\pi i \tau / M}$. The hypothesis is that the natural
number $M \cdot (\mathrm{k.toNat} / 12)$, where `k.toNat` is $\max(k,0)$ and the division is
truncated division of natural numbers, is strictly smaller, as an element of
$\mathbb{N}\cup\{\infty\}$, than the order of that power series (the order being $\infty$ when the
series vanishes). The conclusion is that $F = 0$. Thus a level-one form of weight $k$ whose
width-$M$ expansion vanishes to order exceeding $M\lfloor k/12\rfloor$ (with the convention that
negative weights give the bound $0$) is identically zero.

This is the Sturm bound in level one, stated for an expansion variable of arbitrary width $M$ rather
than only for the standard width $1$. It is the shape in which the level-one bound is applied to
forms whose natural expansion parameter is $q_M$, such as norms $\prod_\gamma f\,|_k\,\gamma$ of
forms on a finite-index subgroup; it is cited by
[`ModularForm.eq_zero_of_lt_order_qExpansion_of_isArithmetic`](thm.html#ModularForm.eq_zero_of_lt_order_qExpansion_of_isArithmetic).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_levelOne_eq_zero_of_lt_order_qExpansion.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_levelOne_eq_zero_of_lt_order_qExpansion

noncomputable section

open Complex Filter Function UpperHalfPlane ModularForm SlashInvariantFormClass ModularFormClass

open scoped Real MatrixGroups Topology Manifold

def W26FnLike : Type := ℍ → ℂ

scoped instance : FunLike W26FnLike ℍ ℂ where
  coe f := f
  coe_injective _ _ h := h

theorem W26.qExpansion_coeff_nat_mul {h : ℝ} (hh : 0 < h) {F : ℍ → ℂ} (hper : Function.Periodic (F ∘ UpperHalfPlane.ofComplex) h) (hhol : MDiff F) (hbdd : UpperHalfPlane.IsBoundedAtImInfty F) {M : ℕ} (hM : 0 < M) (n : ℕ) : (qExpansion (M * h) F).coeff n = if M ∣ n then (qExpansion h F).coeff (n / M) else 0 := by
  have hMh : 0 < (M : ℝ) * h := by positivity
  have hM0 : (M : ℂ) ≠ 0 := by exact_mod_cast hM.ne'
  have hh0 : (h : ℂ) ≠ 0 := by exact_mod_cast hh.ne'
  have hper' : Periodic (F ∘ ofComplex) (((M : ℝ) * h : ℝ) : ℂ) := by
    simpa using hper.nat_mul M
  have han : AnalyticAt ℂ (cuspFunction (M * h) F) 0 :=
    analyticAt_cuspFunction_zero hMh hper' hhol hbdd
  set c : ℕ → ℂ := fun n ↦ if M ∣ n then (qExpansion h F).coeff (n / M) else 0 with hc
  have hsum : ∀ τ : ℍ, HasSum (fun m ↦ c m • Periodic.qParam (M * h) τ ^ m) (F τ) := by
    intro τ
    have hq : Periodic.qParam h τ = Periodic.qParam (M * h) τ ^ M := by
      simp only [Periodic.qParam, ← Complex.exp_nat_mul]
      congr 1
      push_cast
      field_simp
    have hs := hasSum_qExpansion hh hper hhol hbdd τ
    simp_rw [hq, ← pow_mul] at hs
    have hinj : Injective (fun m : ℕ ↦ M * m) := mul_right_injective₀ hM.ne'
    have hsupp : ∀ x ∉ Set.range (fun m : ℕ ↦ M * m),
        (fun m ↦ c m • Periodic.qParam (M * h) τ ^ m) x = 0 := by
      intro x hx
      have : ¬ M ∣ x := by
        rintro ⟨d, rfl⟩
        exact hx ⟨d, rfl⟩
      simp [hc, this]
    refine (hinj.hasSum_iff hsupp).mp ?_
    convert hs using 1
    ext m
    simp [hc, Nat.mul_div_cancel_left _ hM]
  have key := qExpansion_coeff_unique (F := W26FnLike) (show W26FnLike from F) hMh han hsum n
  exact key.symm

theorem solution (M : ℕ) (hM : 0 < M) {k : ℤ} (F : ModularForm 𝒮ℒ k) (h : ((M * (k.toNat / 12) : ℕ) : ℕ∞) < (qExpansion (M : ℝ) F).order) : F = 0 := by
  by_contra hF
  have hq1 : qExpansion 1 F ≠ 0 := by
    rwa [Ne, ModularForm.qExpansion_eq_zero_iff one_pos one_mem_strictPeriods_SL]
  have hord : (qExpansion 1 F).order ≠ ⊤ := by
    rwa [Ne, PowerSeries.order_eq_top]
  obtain ⟨n, hn⟩ := ENat.ne_top_iff_exists.mp hord
  have hle : n ≤ k.toNat / 12 := by
    refine le_of_not_gt fun hlt ↦ hF (ModularForm.sturm_bound_levelOne ?_)
    rw [← hn]
    exact_mod_cast hlt
  have hcoeff : (qExpansion 1 F).coeff n ≠ 0 := by
    have := PowerSeries.coeff_order hq1
    rwa [← hn, ENat.toNat_natCast] at this
  have hper := periodic_comp_ofComplex F one_mem_strictPeriods_SL
  have : Fact (IsCusp OnePoint.infty 𝒮ℒ) := ⟨(𝒮ℒ).isCusp_of_mem_strictPeriods one_pos
    one_mem_strictPeriods_SL⟩
  have hM' := W26.qExpansion_coeff_nat_mul one_pos hper (holo F) (bdd_at_infty F)
    hM (M * n)
  rw [mul_one, ite_eq_left (dvd_mul_right M n), Nat.mul_div_cancel_left _ hM] at hM'
  have hordM : (qExpansion (M : ℝ) F).order ≤ (M * n : ℕ) :=
    PowerSeries.order_le _ (by rwa [hM'])
  have : ((M * n : ℕ) : ℕ∞) ≤ (M * (k.toNat / 12) : ℕ) := by
    exact_mod_cast Nat.mul_le_mul_left M hle
  exact absurd (h.trans_le (hordM.trans this)) (lt_irrefl _)

end

end S_ModularForm_levelOne_eq_zero_of_lt_order_qExpansion
end P2MW
export P2MW.S_ModularForm_levelOne_eq_zero_of_lt_order_qExpansion (solution)

end privateSection

public section publicSection


open UpperHalfPlane
open scoped MatrixGroups Manifold
theorem ModularForm.levelOne_eq_zero_of_lt_order_qExpansion (M : ℕ) (hM : 0 < M) {k : ℤ} (F : ModularForm 𝒮ℒ k) (h : ((M * (k.toNat / 12) : ℕ) : ℕ∞) < (qExpansion (M : ℝ) F).order) : F = 0 := _root_.P2MW.S_ModularForm_levelOne_eq_zero_of_lt_order_qExpansion.solution M hM F h

end publicSection
