/-
Based on Prove2Me node WeierstrassCurve.exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries
(64da0625-6b80-5664-87ab-528cc176dc80) by Claude (2026-09-05).

Proof based on Prove2Me submission ad741ddb-39a7-5a28-9878-3532ace3d732
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Weierstrass
public import Mathlib.RingTheory.PowerSeries.Basic

import Mathlib.RingTheory.PowerSeries.Inverse
import Mathlib.RingTheory.SimpleRing.Principal
import Definitions.FLT.Def_P2M_Util

/-!
# Good-reduction Weierstrass model over K[[t]] with j-1728=t²

Theorem statement: `WeierstrassCurve.exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries`
(`64da0625-6b80-5664-87ab-528cc176dc80`), by Claude, 2026-09-05.

Proof: submission `ad741ddb-39a7-5a28-9878-3532ace3d732`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field in which $2 \ne 0$ and $3 \ne 0$ (so $\operatorname{char} K \nmid 6$). The
assertion is that there exists a Weierstrass curve $E$ over the power series ring $K[[X]]$ — that
is, a tuple of coefficients $a_1, a_2, a_3, a_4, a_6 \in K[[X]]$ in the sense of Mathlib's
`WeierstrassCurve` — such that two conditions hold: the discriminant $\Delta(E)$, formed from the
usual quantities $b_2, b_4, b_6, b_8$, is a unit of $K[[X]]$, and the invariant $c_6(E)$ satisfies
$c_6(E)^2 = \Delta(E)\cdot X^2$. Since $c_4^3 - c_6^2 = 1728\,\Delta$ identically and $\Delta$ is
invertible, the second condition says exactly that the $j$-invariant of $E$ satisfies $j(E) - 1728 =
X^2$ in $K[[X]]$. No minimality, non-singularity in the Mathlib sense, or further normalisation of
$E$ is asserted beyond these two equations.

This provides an elliptic curve over $K[[t]]$ with good reduction whose $j$-invariant has $j - 1728$
equal to the uniformiser squared, i.e. a local model at the elliptic point $j = 1728$ of the
$j$-line. It is used in the analysis of ramification of modular coverings above $j = 1728$, namely
by
[`ModularCurve.ModularPolynomialData.hasRamBound_two_of_isRoot_at_1728_of_odd`](thm.html#ModularCurve.ModularPolynomialData.hasRamBound_two_of_isRoot_at_1728_of_odd)
and [`ModularCurve.ord_jBar_sub_1728_dvd_two`](thm.html#ModularCurve.ord_jBar_sub_1728_dvd_two).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries

open PowerSeries

namespace P2MWs13
namespace GoodRedModels

variable (K : Type*) [Field K]

theorem isUnit_1728_sub_X_cube (h2 : (2 : K) ≠ 0) (h3 : (3 : K) ≠ 0) :
    IsUnit ((1728 : PowerSeries K) - PowerSeries.X ^ 3) := by
  refine PowerSeries.isUnit_iff_constantCoeff.mpr (isUnit_iff_ne_zero.mpr ?_)
  simp only [map_sub, map_ofNat, map_pow, PowerSeries.constantCoeff_X]
  have hfac : (1728 : K) = 2 ^ 6 * 3 ^ 3 := by norm_num
  norm_num
  rw [hfac]; exact mul_ne_zero (pow_ne_zero _ h2) (pow_ne_zero _ h3)

theorem isUnit_1728_add_X_sq (h2 : (2 : K) ≠ 0) (h3 : (3 : K) ≠ 0) :
    IsUnit ((1728 : PowerSeries K) + PowerSeries.X ^ 2) := by
  refine PowerSeries.isUnit_iff_constantCoeff.mpr (isUnit_iff_ne_zero.mpr ?_)
  simp only [map_add, map_ofNat, map_pow, PowerSeries.constantCoeff_X]
  have hfac : (1728 : K) = 2 ^ 6 * 3 ^ 3 := by norm_num
  norm_num
  rw [hfac]; exact mul_ne_zero (pow_ne_zero _ h2) (pow_ne_zero _ h3)

theorem isUnit_const (h2 : (2 : K) ≠ 0) (h3 : (3 : K) ≠ 0) (a b : ℕ) :
    IsUnit ((2 : PowerSeries K) ^ a * 3 ^ b) := by
  refine PowerSeries.isUnit_iff_constantCoeff.mpr (isUnit_iff_ne_zero.mpr ?_)
  simp only [map_mul, map_pow, map_ofNat]
  exact mul_ne_zero (pow_ne_zero _ h2) (pow_ne_zero _ h3)

end P2MWs13.GoodRedModels

open P2MWs13.GoodRedModels in
theorem solution
    (K : Type*) [Field K] (h2 : (2 : K) ≠ 0) (h3 : (3 : K) ≠ 0) :
    ∃ E : WeierstrassCurve (PowerSeries K), IsUnit E.Δ ∧ E.c₆ ^ 2 = E.Δ * PowerSeries.X ^ 2 := by
  set u : PowerSeries K := 1728 + PowerSeries.X ^ 2 with hu
  let E : WeierstrassCurve (PowerSeries K) := ⟨0, 0, 0, -3 * u, 2 * PowerSeries.X * u⟩
  have hΔ : E.Δ = (2 ^ 12 * 3 ^ 6) * u ^ 2 := by
    simp only [E, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
      WeierstrassCurve.b₆, WeierstrassCurve.b₈]
    rw [hu]; ring
  have hc₆ : E.c₆ = -1728 * PowerSeries.X * u := by
    simp only [E, WeierstrassCurve.c₆, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
      WeierstrassCurve.b₆]; ring
  refine ⟨E, ?_, ?_⟩
  · rw [hΔ]
    exact (isUnit_const K h2 h3 12 6).mul ((isUnit_1728_add_X_sq K h2 h3).pow 2)
  · rw [hc₆, hΔ]; ring

end S_WeierstrassCurve_exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries
end P2MW
export P2MW.S_WeierstrassCurve_exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem WeierstrassCurve.exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries
    (K : Type*) [Field K] (h2 : (2 : K) ≠ 0) (h3 : (3 : K) ≠ 0) :
    ∃ E : WeierstrassCurve (PowerSeries K), IsUnit E.Δ ∧ E.c₆ ^ 2 = E.Δ * PowerSeries.X ^ 2 := _root_.P2MW.S_WeierstrassCurve_exists_isUnit_discriminant_and_c6_sq_eq_mul_X_sq_powerSeries.solution K h2 h3

end publicSection
