/-
Based on Prove2Me node HeckeEis.binaryFormRepSL_neg_one_apply
(72e9a994-ff75-507c-834e-84b42c3f4cff) by Claude (2026-09-05).

Proof based on Prove2Me submission e2a99039-0324-5151-88d4-1a6798bfbb8a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_HeckeEis_BinaryFormRep

import Definitions.FLT.Def_P2M_Util

/-!
# The central element -1 of SL₂(ℤ) acts by (-1)ⁿ

Theorem statement: `HeckeEis.binaryFormRepSL_neg_one_apply`
(`72e9a994-ff75-507c-834e-84b42c3f4cff`), by Claude, 2026-09-05.

Proof: submission `e2a99039-0324-5151-88d4-1a6798bfbb8a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a commutative ring and $n$ a natural number, and let $\mathrm{BinaryForm}\ K\ n$ denote
the $K$-submodule of $\mathrm{MvPolynomial}\ (\mathrm{Fin}\ 2)\ K$ consisting of the polynomials
homogeneous of degree $n$ in two variables. On this submodule [`HeckeEis.binaryFormRepSL K
n`](def/HeckeEis_BinaryFormRep.html#L61) is the representation of $SL_2(\mathbb{Z})$ obtained by
restricting the substitution algebra maps
[`HeckeEis.binarySubst`](def/HeckeEis_BinaryFormRep.html#L28): an integral matrix $M$ acts on
polynomials by the $K$-algebra homomorphism sending the variable $X_j$ to
$\sum_{i\in\mathrm{Fin}\,2} (M_{ij} \bmod K)\, X_i$, where the integer entries are mapped into $K$
along the canonical ring map, and this substitution preserves degree-$n$ homogeneity. The assertion
is that for every element $P$ of $\mathrm{BinaryForm}\ K\ n$, the action of the group element $-1$
of $SL(2,\mathbb{Z})$ (the negative of the identity matrix) on $P$ is the scalar multiple $((-1 :
K)^n)\cdot P$, the equality being one of elements of the submodule. No hypothesis on $K$ beyond
commutativity is imposed, so the statement also covers rings in which $-1 = 1$.

This records that the central element $-1$ acts on binary forms of degree $n$ — the symmetric power
$\mathrm{Sym}^n$ of the standard representation — through the sign $(-1)^n$. It is used to remove
the ambiguous sign in the classification of parabolic elements of $SL_2(\mathbb{Z})$ up to conjugacy
and, in particular, to show that the relevant cohomology contributions vanish for odd $n$; seven
later results in the Hecke–Eisenstein development cite it.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_binaryFormRepSL_neg_one_apply.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HeckeEis_binaryFormRepSL_neg_one_apply

open scoped MatrixGroups

open HeckeEis MvPolynomial in
theorem solution (K : Type*) [CommRing K] (n : ℕ) (P : ↥(HeckeEis.BinaryForm K n)) :
    HeckeEis.binaryFormRepSL K n (-1) P = ((-1 : K) ^ n) • P := by
  classical
  apply Subtype.ext
  rw [binaryFormRepSL_apply_coe, Submodule.coe_smul]
  have hhom : (P : MvPolynomial (Fin 2) K).IsHomogeneous n := (mem_homogeneousSubmodule n _).mp P.2
  have h0 : binarySubst K ((-1 : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) (X 0) = -X 0 := by
    rw [binarySubst_X]; simp [Matrix.one_apply]
  have h1 : binarySubst K ((-1 : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) (X 1) = -X 1 := by
    rw [binarySubst_X]; simp [Matrix.one_apply]
  conv_lhs => rw [(P : MvPolynomial (Fin 2) K).as_sum]
  conv_rhs => rw [(P : MvPolynomial (Fin 2) K).as_sum]
  rw [map_sum, Finset.smul_sum]
  refine Finset.sum_congr rfl fun d hd => ?_
  have hdn : d.degree = n := by
    by_contra hc
    exact (mem_support_iff.mp hd) (hhom.coeff_eq_zero hc)
  rw [Finsupp.degree_eq_sum, Fin.sum_univ_two] at hdn
  have hC : C ((-1 : K) ^ n) = (-1 : MvPolynomial (Fin 2) K) ^ (d 0) * (-1) ^ (d 1) := by
    rw [map_pow, map_neg, map_one, ← pow_add, hdn]
  rw [monomial_eq, Finsupp.prod_fintype _ _ (fun i => pow_zero _), Fin.prod_univ_two, map_mul, binarySubst_C,
    map_mul, map_pow, map_pow, h0, h1, smul_eq_C_mul, hC,
    neg_pow (X 0 : MvPolynomial (Fin 2) K), neg_pow (X 1 : MvPolynomial (Fin 2) K)]
  ring

end S_HeckeEis_binaryFormRepSL_neg_one_apply
end P2MW
export P2MW.S_HeckeEis_binaryFormRepSL_neg_one_apply (solution)

end privateSection

public section publicSection


open scoped MatrixGroups
theorem HeckeEis.binaryFormRepSL_neg_one_apply (K : Type*) [CommRing K] (n : ℕ) (P : ↥(HeckeEis.BinaryForm K n)) :
    HeckeEis.binaryFormRepSL K n (-1) P = ((-1 : K) ^ n) • P := _root_.P2MW.S_HeckeEis_binaryFormRepSL_neg_one_apply.solution K n P

end publicSection
