/-
Based on Prove2Me node AlgebraicCurve.Place.exists_ord_mul_eq_order_of_algHom_laurentSeries
(a09cc34f-f4eb-5951-b5ff-76663dc0215e) by Claude (2026-09-05).

Proof based on Prove2Me submission 5ac54bb6-05b5-58e2-8b90-e04fa9444456
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_AtkinLehner

import Mathlib.RingTheory.LaurentSeries
import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_ord_mul_eq_order_of_hasRamBound

/-!
# Places from K-algebra embeddings into Laurent series

Theorem statement: `AlgebraicCurve.Place.exists_ord_mul_eq_order_of_algHom_laurentSeries`
(`a09cc34f-f4eb-5951-b5ff-76663dc0215e`), by Claude, 2026-09-05.

Proof: submission `5ac54bb6-05b5-58e2-8b90-e04fa9444456`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, $F$ a field equipped with a $K$-algebra structure, and $\iota : F \to K((T))$ a
$K$-algebra homomorphism into the Laurent series field over $K$ (Hahn series with value group
$\mathbb{Z}$). Assume the non-triviality hypothesis that some $x \in F$ has $\mathrm{order}(\iota x)
\neq 0$, i.e. the $T$-adic order pulled back along $\iota$ is not identically zero. The conclusion
asserts the existence of a place $w$ of $F$ over $K$ — that is, a valuation subring of $F$ which
contains $\mathrm{algebraMap}\,K\,F(a)$ for every $a \in K$, is not all of $F$, and is a principal
ideal ring — together with a natural number $\gamma$ with $0 < \gamma$, such that for every $x \in
F$ one has $\mathrm{ord}_w(x)\cdot\gamma = \mathrm{order}(\iota x)$ in $\mathbb{Z}$, where
$\mathrm{ord}_w(x)$ is minus the logarithm of the value of $x$ under the height-one-spectrum adic
valuation attached to $w$. Thus the $T$-adic order of $\iota$ is a positive integral multiple of a
normalised discrete valuation of $F$ trivial on $K$; $\gamma$ plays the role of the ramification
index of the embedding.

This is the standard device by which an analytic (Laurent-series) expansion of a function field
determines a place of that field over the base field, with the expansion order equal to the
valuation up to a positive integer factor. It is used to produce places of function fields of
modular curves and of their base changes to Laurent series, and is cited in the analysis of orders
of $j$ and of cusp counting.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_exists_ord_mul_eq_order_of_algHom_laurentSeries.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

open AlgebraicCurve

namespace CD

section Transport

variable {K : Type*} [Field K]

theorem hasRamBound_puiseuxRamEmb {e : ℕ} (he : 0 < e) (x : LaurentSeries K) :
    HahnSeries.HasRamBound e (HahnSeries.puiseuxRamEmb he x) := by
  intro q hq
  have hq' : q ∈ ⇑(HahnSeries.ramScale e) '' x.support := by
    simpa [HahnSeries.puiseuxRamEmb, HahnSeries.embDomainRingHom] using
      HahnSeries.support_embDomain_subset hq
  obtain ⟨k, -, rfl⟩ := hq'
  exact ⟨k, rfl⟩

theorem order_puiseuxRamEmb {e : ℕ} (he : 0 < e) (x : LaurentSeries K) :
    (HahnSeries.puiseuxRamEmb he x).order = HahnSeries.ramScale e x.order := by
  rcases eq_or_ne x 0 with rfl | hx
  · simp
  · have hx' : HahnSeries.puiseuxRamEmb (K := K) he x ≠ 0 := by
      intro h0
      exact hx ((HahnSeries.puiseuxRamEmb (K := K) he).injective (by rw [h0, map_zero]))
    have h2 : (HahnSeries.puiseuxRamEmb (K := K) he x).orderTop
        = WithTop.map (⇑(HahnSeries.ramScale e)) x.orderTop :=
      HahnSeries.orderTop_embDomain
    have h1 := HahnSeries.order_eq_orderTop_of_ne_zero hx'
    rw [h2, ← HahnSeries.order_eq_orderTop_of_ne_zero hx, WithTop.map_coe] at h1
    exact_mod_cast h1

theorem laurentAlgebraMap_eq_C (c : K) :
    algebraMap K (LaurentSeries K) c = HahnSeries.C c := by
  rw [HahnSeries.algebraMap_apply', PowerSeries.algebraMap_apply]
  simp [HahnSeries.ofPowerSeries_C]

theorem hahnQAlgebraMap_eq_C (c : K) :
    algebraMap K (HahnSeries ℚ K) c = HahnSeries.C c := by
  rw [HahnSeries.algebraMap_apply']
  simp [HahnSeries.ofPowerSeries_C]

end Transport

section Lift

variable {K : Type*} [Field K] {F : Type*} [Field F] [Algebra K F]

def liftToHahn (ι : F →ₐ[K] LaurentSeries K) : F →ₐ[K] HahnSeries ℚ K where
  toRingHom := (HahnSeries.puiseuxRamEmb one_pos).comp ι.toRingHom
  commutes' := by
    intro c
    show HahnSeries.puiseuxRamEmb one_pos (ι (algebraMap K F c))
        = algebraMap K (HahnSeries ℚ K) c
    rw [ι.commutes c, laurentAlgebraMap_eq_C, hahnQAlgebraMap_eq_C]
    exact HahnSeries.embDomainRingHom_C

@[scoped simp] theorem liftToHahn_apply (ι : F →ₐ[K] LaurentSeries K) (x : F) :
    liftToHahn ι x = HahnSeries.puiseuxRamEmb one_pos (ι x) := rfl

theorem order_liftToHahn (ι : F →ₐ[K] LaurentSeries K) (x : F) :
    (liftToHahn ι x).order = ((ι x).order : ℚ) := by
  rw [liftToHahn_apply, order_puiseuxRamEmb one_pos, HahnSeries.ramScale_apply]
  simp

end Lift

section Generic

variable (K : Type*) [Field K]

private theorem _root_.AlgebraicCurve.Place.exists_ord_mul_eq_order_of_algHom_laurentSeries' {F : Type*} [Field F] [Algebra K F] (ι : F →ₐ[K] LaurentSeries K)
    (h : ∃ x : F, (ι x).order ≠ 0) :
    ∃ (w : Place K F) (γ : ℕ), 0 < γ ∧ ∀ x : F, w.ord x * (γ : ℤ) = (ι x).order := by
  obtain ⟨x₀, hx₀⟩ := h
  have hnt : ∃ x : F, ((liftToHahn ι) x).order ≠ 0 :=
    ⟨x₀, by rw [order_liftToHahn]; exact_mod_cast hx₀⟩
  have hRB : ∀ x : F, HahnSeries.HasRamBound 1 ((liftToHahn ι) x) :=
    fun x => hasRamBound_puiseuxRamEmb one_pos (ι x)
  obtain ⟨w, g, hg, hgw⟩ :=
    Place.exists_ord_mul_eq_order_of_hasRamBound (liftToHahn ι) one_pos hRB hnt
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible w.toValuationSubring
  have hordπ : w.ord (π : F) = 1 := w.ord_coe_irreducible hπ
  have hgval : g = ((ι (π : F)).order : ℚ) := by
    have h1 := hgw (π : F)
    rw [hordπ, order_liftToHahn] at h1
    simpa using h1
  have hpos : 0 < (ι (π : F)).order := by
    rw [hgval] at hg
    exact_mod_cast hg
  refine ⟨w, ((ι (π : F)).order).toNat, by omega, fun x => ?_⟩
  have h1 := hgw x
  rw [hgval, order_liftToHahn] at h1
  have h2 : w.ord x * (ι (π : F)).order = (ι x).order := by exact_mod_cast h1
  rw [Int.toNat_of_nonneg hpos.le]
  exact h2

end Generic

end CD

open AlgebraicCurve.Place

theorem solution (K : Type*) [Field K] {F : Type*} [Field F] [Algebra K F] (ι : F →ₐ[K] LaurentSeries K)
    (h : ∃ x : F, (ι x).order ≠ 0) :
    ∃ (w : Place K F) (γ : ℕ), 0 < γ ∧ ∀ x : F, w.ord x * (γ : ℤ) = (ι x).order :=
  AlgebraicCurve.Place.exists_ord_mul_eq_order_of_algHom_laurentSeries' K ι h

end

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.Place.exists_ord_mul_eq_order_of_algHom_laurentSeries (K : Type*) [Field K] {F : Type*} [Field F] [Algebra K F] (ι : F →ₐ[K] LaurentSeries K)
    (h : ∃ x : F, (ι x).order ≠ 0) :
    ∃ (w : Place K F) (γ : ℕ), 0 < γ ∧ ∀ x : F, w.ord x * (γ : ℤ) = (ι x).order := _root_.solution K ι h

end publicSection
