/-
Based on Prove2Me node ModularCurve.HahnSpecialise.specialiseCycSub_injective
(319e24b6-63cc-58e9-887d-b11e3471b436) by Claude (2026-09-05).

Proof based on Prove2Me submission 97ee1c07-1f56-536a-818d-4f73d536eb44
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_HahnSpecialise

import Definitions.FLT.Def_P2M_Util

/-!
# Specialisation is injective on cyclic subgroups of order N

Theorem statement: `ModularCurve.HahnSpecialise.specialiseCycSub_injective`
(`319e24b6-63cc-58e9-887d-b11e3471b436`), by Claude, 2026-09-05.

Proof: submission `97ee1c07-1f56-536a-818d-4f73d536eb44`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let `H` be the Hahn-series field fixed in this development (its elements carry an order function
`orderTop` and coefficients, so that `coeff 0` is defined) and let $\bar{\mathbb Q}$ denote `Qbar`,
the algebraic closure of $\mathbb Q$. Let $E$ be a Weierstrass curve over `H` satisfying
`IntegralCoeffs`, that is, each of $a_1,a_2,a_3,a_4,a_6$ has nonnegative `orderTop`; let
`specialFibre E` be the Weierstrass curve over $\bar{\mathbb Q}$ whose coefficients are the $0$-th
coefficients $a_i(0)$, and assume its discriminant $\Delta$ is nonzero. Let $N$ be a natural number
with `NeZero N`, i.e. $N \neq 0$. The assertion is that the map `specialiseCycSub E hE hΔ N` is
injective. Its source `CycSubH E N` consists of the subgroups $S$ of the affine point group
$E(\,$`H`$)$ for which there is a point $g$ of additive order exactly $N$ with $S = \langle
g\rangle$ (the group of integer multiples of $g$), its target `CycSub (specialFibre E) N` is the
analogous set of subgroups of $(\mathrm{specialFibre}\,E)(\bar{\mathbb Q})$, and the map sends $S$
to its image under the specialisation homomorphism `specialise E hE hΔ` $: E(\,$`H`$) \to
(\mathrm{specialFibre}\,E)(\bar{\mathbb Q})$, this image again being cyclic of order $N$ because
that homomorphism is injective on pairs of $N$-torsion points.

This is the injectivity half of the comparison of $\Gamma_0(N)$-level structures — cyclic subgroups
of order $N$ — on a Weierstrass curve with good special fibre and on that special fibre, the
classical source being the injectivity of reduction on torsion of order prime to the residue
characteristic. It feeds the bijectivity statement
[`ModularCurve.HahnSpecialise.specialiseCycSub_bijective`](thm.html#ModularCurve.HahnSpecialise.specialiseCycSub_bijective).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_HahnSpecialise_specialiseCycSub_injective.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_HahnSpecialise_specialiseCycSub_injective

noncomputable section

open ModularCurve ModularCurve.B3 ModularCurve.HahnSpecialise
open ModularCurve.TatePoint (Qbar H CycSubH)
open scoped Classical

namespace CycSubOf
p2m_export "CycSubOf" "map coe_map"
p2m_open "CycSubOf"

variable {G G' : Type*} [AddCommGroup G] [AddCommGroup G'] (f : G →+ G') {N : ℕ}
variable (hf : ∀ ⦃P Q : G⦄, N • P = 0 → N • Q = 0 → f P = f Q → P = Q)

include hf in
theorem mem_zmultiples_of_map_eq {g g' : G} (hg : addOrderOf g = N) (hg' : addOrderOf g' = N)
    (heq : (AddSubgroup.zmultiples g).map f = (AddSubgroup.zmultiples g').map f) :
    g ∈ AddSubgroup.zmultiples g' := by
  have hmem : f g ∈ (AddSubgroup.zmultiples g').map f := by
    rw [← heq]; exact AddSubgroup.mem_map_of_mem _ (AddSubgroup.mem_zmultiples g)
  rw [AddMonoidHom.map_zmultiples, AddSubgroup.mem_zmultiples_iff] at hmem
  obtain ⟨k, hk⟩ := hmem
  have hgk : g = k • g' := by
    refine hf ?_ ?_ (by rw [map_zsmul, hk])
    · rw [← hg]; exact addOrderOf_nsmul_eq_zero g
    · rw [smul_comm, ← hg', addOrderOf_nsmul_eq_zero, smul_zero]
  rw [hgk]; exact AddSubgroup.zsmul_mem _ (AddSubgroup.mem_zmultiples g') k

theorem map_injective : Function.Injective (map f hf) := by
  intro S T hST
  obtain ⟨g, hg, hS⟩ := S.2
  obtain ⟨g', hg', hT⟩ := T.2
  have hST' : (AddSubgroup.zmultiples g).map f = (AddSubgroup.zmultiples g').map f := by
    have := congrArg Subtype.val hST
    simpa [coe_map, hS, hT] using this
  apply Subtype.ext
  rw [hS, hT]
  apply le_antisymm
  · rw [AddSubgroup.zmultiples_le]
    exact mem_zmultiples_of_map_eq f hf hg hg' hST'
  · rw [AddSubgroup.zmultiples_le]
    exact mem_zmultiples_of_map_eq f hf hg' hg hST'.symm

end CycSubOf

theorem solution (E : WeierstrassCurve H) (hE : IntegralCoeffs E)
    (hΔ : (specialFibre E).Δ ≠ 0) (N : ℕ) [NeZero N] :
    Function.Injective (specialiseCycSub E hE hΔ N) :=
  CycSubOf.map_injective _ _

end

end S_ModularCurve_HahnSpecialise_specialiseCycSub_injective
end P2MW
export P2MW.S_ModularCurve_HahnSpecialise_specialiseCycSub_injective (solution)

end privateSection

public section publicSection


open ModularCurve ModularCurve.B3 ModularCurve.HahnSpecialise
open ModularCurve.TatePoint (Qbar H CycSubH)
open scoped Classical
theorem ModularCurve.HahnSpecialise.specialiseCycSub_injective (E : WeierstrassCurve H) (hE : IntegralCoeffs E)
    (hΔ : (specialFibre E).Δ ≠ 0) (N : ℕ) [NeZero N] :
    Function.Injective (specialiseCycSub E hE hΔ N) := _root_.P2MW.S_ModularCurve_HahnSpecialise_specialiseCycSub_injective.solution E hE hΔ N

end publicSection
