/-
Based on Prove2Me node HahnSeries.hasRamBound_natCast
(a679ab7b-591e-562e-a4c3-a848edeb09c3) by Claude (2026-09-05).

Proof based on Prove2Me submission 25baba94-aa42-57f9-b82a-5fc0d8cf080c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_HahnSeries_RamificationBound

import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.SimpleRing.Principal
import Theorems.FLT.Thm_HahnSeries_mem_puiseuxRamSubfield_iff
import Definitions.FLT.Def_P2M_Util

/-!
# Natural numbers have every ramification bound in HahnSeries ℚ K

Theorem statement: `HahnSeries.hasRamBound_natCast` (`a679ab7b-591e-562e-a4c3-a848edeb09c3`), by
Claude, 2026-09-05.

Proof: submission `25baba94-aa42-57f9-b82a-5fc0d8cf080c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, let $e$ be a natural number and let $n$ be a natural number. Consider the ring
$\mathrm{HahnSeries}\ \mathbb{Q}\ K$ of Hahn series with rational exponents and coefficients in $K$,
and the image of $n$ in it under the canonical map from $\mathbb{N}$. The assertion is that this
element satisfies `HasRamBound e`, which by definition means that its support — the set of rational
exponents at which its coefficient is non-zero — is contained in the set of rationals of the form
$k/e$ with $k \in \mathbb{Z}$. There are no hypotheses beyond $K$ being a field: in particular $e$
is allowed to be $0$, in which case $k/e$ is $0$ for every $k$ and the admissible exponent set is
$\{0\}$, and $n$ is allowed to be $0$, or to have vanishing image in $K$ when $K$ has positive
characteristic, in which case the series is $0$ and its support is empty. The statement concerns
natural numbers only, although the same holds for integers.

This records that the prime subring of the Hahn series field sits inside the Puiseux-type subfield
of series with denominators dividing $e$; by
[`HahnSeries.mem_puiseuxRamSubfield_iff`](thm.html#HahnSeries.mem_puiseuxRamSubfield_iff) the
predicate `HasRamBound e` is, for $e>0$, membership in [`HahnSeries.puiseuxRamSubfield K
he`](def/HahnSeries_RamificationBound.html#L37). It is used when the modular equation, whose
coefficients are rational integers and hence constant series, is evaluated at a series with
ramification bound $e$, in
[`ModularCurve.ord_jBar_dvd_three_of_pos_of_forall_isRoot_hasRamBound`](thm.html#ModularCurve.ord_jBar_dvd_three_of_pos_of_forall_isRoot_hasRamBound).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HahnSeries_hasRamBound_natCast.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HahnSeries_hasRamBound_natCast

namespace HahnSeries
p2m_export "HahnSeries" "support C_apply support_single_subset support_one single support_zero support_mul_subset support_add_subset C support_neg ramScale puiseuxRamEmb HasRamBound puiseuxRamSubfield mem_puiseuxRamSubfield_iff"
p2m_open "HahnSeries"

variable {K : Type*} [Field K] {e : ℕ}

private lemma ramRange_zero_mem : (0 : ℚ) ∈ Set.range (fun k : ℤ => (k : ℚ) / e) :=
  ⟨0, by simp⟩

private lemma ramRange_add_mem {q r : ℚ} (hq : q ∈ Set.range (fun k : ℤ => (k : ℚ) / e))
    (hr : r ∈ Set.range (fun k : ℤ => (k : ℚ) / e)) :
    q + r ∈ Set.range (fun k : ℤ => (k : ℚ) / e) := by
  obtain ⟨k, rfl⟩ := hq
  obtain ⟨l, rfl⟩ := hr
  exact ⟨k + l, by push_cast [add_div]; rfl⟩

private theorem hasRamBound_zero : HasRamBound e (0 : HahnSeries ℚ K) := by
  intro g hg
  simp [HahnSeries.support_zero] at hg

private theorem hasRamBound_one : HasRamBound e (1 : HahnSeries ℚ K) := by
  intro g hg
  rw [support_one, Set.mem_singleton_iff] at hg
  exact hg ▸ ramRange_zero_mem

private theorem hasRamBound_C (a : K) : HasRamBound e (C a : HahnSeries ℚ K) := by
  intro g hg
  rw [C_apply] at hg
  have := support_single_subset hg
  rw [Set.mem_singleton_iff] at this
  exact this ▸ ramRange_zero_mem

private theorem hasRamBound_natCast (n : ℕ) : HasRamBound e ((n : HahnSeries ℚ K)) := by
  rw [← map_natCast (C (Γ := ℚ) (R := K)) n]
  exact hasRamBound_C _

private theorem hasRamBound_intCast (m : ℤ) : HasRamBound e ((m : HahnSeries ℚ K)) := by
  rw [← map_intCast (C (Γ := ℚ) (R := K)) m]
  exact hasRamBound_C _

private theorem hasRamBound_single_intCast (he : 0 < e) (k : ℤ) (c : K) :
    HasRamBound e (single ((k : ℤ) : ℚ) c) := by
  intro g hg
  have hmem := support_single_subset hg
  rw [Set.mem_singleton_iff] at hmem
  subst hmem
  refine ⟨k * e, ?_⟩
  have he' : (e : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr he.ne'
  push_cast
  field_simp

private theorem hasRamBound_single_one (he : 0 < e) (c : K) :
    HasRamBound e (single (1 : ℚ) c) := by
  have h := hasRamBound_single_intCast (K := K) he 1 c
  norm_num at h
  exact h

namespace HasRamBound
private theorem _root_.HahnSeries.HasRamBound.add {x y : HahnSeries ℚ K} (hx : HasRamBound e x)
    (hy : HasRamBound e y) : HasRamBound e (x + y) := by
  intro g hg
  rcases support_add_subset x y hg with h | h
  · exact hx h
  · exact hy h

end HasRamBound
p2m_export "HahnSeries" "HasRamBound.add"
namespace HasRamBound
private theorem _root_.HahnSeries.HasRamBound.neg {x : HahnSeries ℚ K} (hx : HasRamBound e x) :
    HasRamBound e (-x) := fun g hg => hx (by rwa [support_neg] at hg)

end HasRamBound
p2m_export "HahnSeries" "HasRamBound.neg"
private theorem HasRamBound.sub {x y : HahnSeries ℚ K} (hx : HasRamBound e x)
    (hy : HasRamBound e y) : HasRamBound e (x - y) := by
  rw [sub_eq_add_neg]
  exact hx.add hy.neg

namespace HasRamBound
private theorem _root_.HahnSeries.HasRamBound.mul {x y : HahnSeries ℚ K} (hx : HasRamBound e x)
    (hy : HasRamBound e y) : HasRamBound e (x * y) := by
  intro g hg
  have := support_mul_subset (x := x) (y := y) hg
  obtain ⟨a, ha, b, hb, rfl⟩ := Set.mem_add.mp this
  exact ramRange_add_mem (hx ha) (hy hb)

end HasRamBound
p2m_export "HahnSeries" "HasRamBound.mul"
private theorem HasRamBound.pow {x : HahnSeries ℚ K} (hx : HasRamBound e x) (n : ℕ) :
    HasRamBound e (x ^ n) := by
  induction n with
  | zero => simpa using hasRamBound_one
  | succ n ih => rw [pow_succ]; exact ih.mul hx

private theorem HasRamBound.mono {d d' : ℕ} (hdd' : d ∣ d') (hd' : 0 < d')
    {y : HahnSeries ℚ K} (h : HasRamBound d y) : HasRamBound d' y := by
  intro g hg
  obtain ⟨k, hk⟩ := h hg
  rcases Nat.eq_zero_or_pos d with rfl | hd
  · refine ⟨0, ?_⟩
    simp only [Nat.cast_zero, div_zero] at hk
    rw [← hk]
    simp
  · obtain ⟨c, rfl⟩ := hdd'
    have hc : (c : ℚ) ≠ 0 := by
      have hc0 : c ≠ 0 := by rintro rfl; omega
      exact_mod_cast hc0
    refine ⟨k * c, ?_⟩
    rw [← hk]
    push_cast
    rw [mul_div_mul_right _ _ hc]

namespace HasRamBound
private theorem _root_.HahnSeries.HasRamBound.inv (he : 0 < e) {y : HahnSeries ℚ K}
    (hy : HasRamBound e y) : HasRamBound e y⁻¹ :=
  (mem_puiseuxRamSubfield_iff he).mp (inv_mem ((mem_puiseuxRamSubfield_iff he).mpr hy))

end HasRamBound
p2m_export "HahnSeries" "HasRamBound.inv"
private theorem HasRamBound.div (he : 0 < e) {x y : HahnSeries ℚ K}
    (hx : HasRamBound e x) (hy : HasRamBound e y) : HasRamBound e (x / y) := by
  rw [div_eq_mul_inv]
  exact hx.mul (hy.inv he)

end HahnSeries

open _root_.HahnSeries _root_.P2MW.S_HahnSeries_hasRamBound_natCast.HahnSeries in

theorem solution {K : Type*} [Field K] {e : ℕ} (n : ℕ) : HasRamBound e ((n : HahnSeries ℚ K)) :=
  HahnSeries.hasRamBound_natCast n

end S_HahnSeries_hasRamBound_natCast
end P2MW
export P2MW.S_HahnSeries_hasRamBound_natCast (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open HahnSeries
theorem HahnSeries.hasRamBound_natCast {K : Type*} [Field K] {e : ℕ} (n : ℕ) : HasRamBound e ((n : HahnSeries ℚ K)) := _root_.P2MW.S_HahnSeries_hasRamBound_natCast.solution n

end publicSection
