/-
Based on Prove2Me node ModularCurve.ord_qInftyPlaceBar
(9fbf2f4a-fbc2-51f0-9678-51ab98df3e7d) by Claude (2026-09-05).

Proof based on Prove2Me submission 8b418c51-75fc-5767-98c3-33d4ee81f38e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_QAdicPlace

import Definitions.FLT.Def_P2M_Util

/-!
# Order at the q-adic place equals q-expansion order

Theorem statement: `ModularCurve.ord_qInftyPlaceBar` (`9fbf2f4a-fbc2-51f0-9678-51ab98df3e7d`), by
Claude, 2026-09-05.

Proof: submission `8b418c51-75fc-5767-98c3-33d4ee81f38e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $L$ be a field and let $F$ be an intermediate field of the extension $L((q))/L$, where $L((q))$
is the field of formal Laurent series over $L$; for $f \in F$ write $\overline{f} \in L((q))$ for
its image, denoted `qSeriesBar L F f`. Assume the hypothesis $h$: some $j \in F$ satisfies
$\operatorname{order}(\overline{j}) = -1$, the order of a Hahn series being the index of its lowest
nonzero coefficient (with the convention $\operatorname{order}(0)=0$). Under $h$ the set $\{f \in F
: \operatorname{order}(\overline{f}) \ge 0\}$ is a valuation subring of $F$ containing $L$, distinct
from $F$ and a principal ideal ring, hence defines a place `qInftyPlaceBar L F h` of $F$ over $L$ in
the sense of the project's structure `Place`. The assertion is that for every $f \in F$ the
associated normalised order, namely minus the logarithm of the value of $f$ under the
$\mathbb{Z}^{m0}$-valued adic valuation attached to the height-one prime of that valuation ring,
equals $\operatorname{order}(\overline{f})$. In particular both sides vanish at $f = 0$.

This identifies the valuation attached to the cusp $\infty$ on a curve presented through
$q$-expansions with the elementary order of vanishing of the $q$-series, with no ramification
factor, the hypothesis $h$ providing an element of $q$-order $-1$ whose inverse is a uniformiser. It
is used in the computation of the order of $j$-type functions at the cusp and in the comparison of
$\infty$ with its translates under field automorphisms.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_ord_qInftyPlaceBar.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_ord_qInftyPlaceBar

open ModularCurve AlgebraicCurve

theorem solution (L : Type*) [Field L] {F : IntermediateField L (LaurentSeries L)} (h : ∃ j : F, (qSeriesBar L F j).order = -1) (f : F) : (qInftyPlaceBar L F h).ord f = (qSeriesBar L F f).order := by
  obtain ⟨j, hj⟩ := h
  rcases eq_or_ne f 0 with rfl | hf
  · rw [Place.ord_zero, qSeriesBar_zero, HahnSeries.order_zero]
  set n : ℤ := (qSeriesBar L F f).order with hn
  have hπ0 : (j⁻¹ : F) ≠ 0 := inv_ne_zero (ne_zero_of_order_eq_neg_one hj)
  have hπn : (j⁻¹ : F) ^ n ≠ 0 := zpow_ne_zero _ hπ0
  have huord : (qSeriesBar L F (f / (j⁻¹) ^ n)).order = 0 := by
    rw [qSeriesBar_div, qSeriesBar_zpow,
      order_div_of_ne_zero_bar (qSeriesBar_ne_zero hf)
        (zpow_ne_zero _ (qSeriesBar_ne_zero hπ0)),
      order_zpow_of_ne_zero_bar (qSeriesBar_ne_zero hπ0), order_inv_of_order_eq_neg_one hj,
      mul_one, ← hn]
    ring
  have humem : f / (j⁻¹) ^ n ∈ qIntegersBar L F := by
    rw [mem_qIntegersBar_iff, huord]
  have hune : f / (j⁻¹) ^ n ≠ 0 := div_ne_zero hf hπn
  have huu : IsUnit (⟨f / (j⁻¹) ^ n, humem⟩ : qIntegersBar L F) :=
    (isUnit_qIntegersBar_iff hune).mpr huord
  have hdecomp : f = ((huu.unit : qIntegersBar L F) : F)
      * (((uniformizerBar hj : qIntegersBar L F) : F) ^ n) := by
    have hcoe : ((huu.unit : qIntegersBar L F) : F) = f / (j⁻¹) ^ n := by
      rw [IsUnit.unit_spec]
    rw [hcoe, coe_uniformizerBar]
    exact (div_mul_cancel₀ f hπn).symm
  rw [hdecomp]
  exact (qInftyPlaceBar L F ⟨j, hj⟩).ord_unit_smul_zpow huu.unit (irreducible_uniformizerBar hj) n

end S_ModularCurve_ord_qInftyPlaceBar
end P2MW
export P2MW.S_ModularCurve_ord_qInftyPlaceBar (solution)

end privateSection

public section publicSection


open ModularCurve AlgebraicCurve
theorem ModularCurve.ord_qInftyPlaceBar (L : Type*) [Field L] {F : IntermediateField L (LaurentSeries L)} (h : ∃ j : F, (qSeriesBar L F j).order = -1) (f : F) : (qInftyPlaceBar L F h).ord f = (qSeriesBar L F f).order := _root_.P2MW.S_ModularCurve_ord_qInftyPlaceBar.solution L h f

end publicSection
