/-
Based on Prove2Me node WLight.frickeFunction_orbit_package
(31f08140-fc87-5825-b66a-596acddc0651) by Claude (2026-09-05).

Proof based on Prove2Me submission 02c0902c-521b-59f3-addb-0ce0260a94dd
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Analysis.SpecialFunctions.Elliptic.Weierstrass
public import Mathlib.NumberTheory.ModularForms.EisensteinSeries.Basic
public import Mathlib.NumberTheory.ModularForms.Discriminant
public import Mathlib.NumberTheory.ModularForms.QExpansion
public import Mathlib.Analysis.Complex.UpperHalfPlane.Manifold
public import Mathlib.Geometry.Manifold.Notation
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

import Theorems.FLT.Thm_ModularForm_weierstrassP_torsion_qExpansion_package
import Theorems.FLT.Thm_WLight_frickeFunction_modularity_package
import Theorems.FLT.Thm_WLight_levelOne_hauptmodul_package
import Definitions.FLT.Def_P2M_Util

/-!
# Polar growth of j and Fricke functions, and their orbit polynomial

Theorem statement: `WLight.frickeFunction_orbit_package` (`31f08140-fc87-5825-b66a-596acddc0651`),
by Claude, 2026-09-05.

Proof: submission `02c0902c-521b-59f3-addb-0ce0260a94dd`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a nonzero natural number. Let $L$ assign to each point $\tau$ of the upper half-plane a
period pair, pinned by the hypothesis that its first period is $\tau$ and its second period is $1$.
Let $W$ be a family of functions on the upper half-plane indexed by $v \in (\mathbb{Z}/N)^2$, pinned
by $W_v(\tau) = (2\pi i)^{-2}\,\wp_{L(\tau)}\big((\tilde v_0 \tau + \tilde v_1)/N\big)$, where
$\tilde v_i$ denotes the canonical representative in $\{0,\dots,N-1\}$ of $v_i$ and $\wp$ is the
Weierstrass function of the period pair; let $\mathrm{fricke}$ be pinned by $\mathrm{fricke}_v(\tau)
= -\big(E_4(\tau)E_6(\tau)/\Delta(\tau)\big)/2592 \cdot W_v(\tau)$; and let $jf$ be pinned by
$jf(\tau) = E_4(\tau)^3/\Delta(\tau)$. The conclusion is a threefold conjunction: (i) $jf$ is
holomorphic on the upper half-plane and there is an $m \in \mathbb{N}$ with $jf \cdot \Delta^m$
bounded at $i\infty$; (ii) for every $v \neq 0$, $\mathrm{fricke}_v$ is holomorphic and there is an
$m \in \mathbb{N}$ with $\mathrm{fricke}_v \cdot \Delta^m$ bounded at $i\infty$; (iii) there is a
family of polynomials $P_k \in \mathbb{C}[X]$, $k \in \mathbb{N}$, all of whose coefficients lie in
the subfield $\mathbb{Q}(e^{2\pi i/N})$ of $\mathbb{C}$, such that for every $v \neq 0$ and every
$\tau$, $\mathrm{fricke}_v(\tau)^{N^2-1} + \sum_{k<N^2-1} P_k(jf(\tau))\,\mathrm{fricke}_v(\tau)^k =
0$; that is, a single monic relation of degree $N^2-1$ over $\mathbb{C}[jf]$, with coefficient
polynomials having cyclotomic coefficients, annihilates all the Fricke functions of nonzero index
simultaneously.

This is the integrality statement for the Fricke functions of level $N$: the $N^2-1$ functions of
nonzero index form a single orbit under the index action of the modular group, so the elementary
symmetric functions of the orbit are level-one invariants of finite polar growth and hence
polynomials in $j$, with coefficients in $\mathbb{Q}(e^{2\pi i/N})$. It is used in the construction
of the function field of the modular curve of level $N$ and of its $q$-expansion and valuation data.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WLight_frickeFunction_orbit_package.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

namespace P2MW.S_WLight_frickeFunction_orbit_package

noncomputable section

open Complex Real
namespace WLight
p2m_export "WLight" "levelOne_hauptmodul_package frickeFunction_modularity_package"
p2m_open "WLight"

section R4bFloor
open scoped UpperHalfPlane Manifold MatrixGroups
p2m_open "UpperHalfPlane~I"
p2m_open "ModularForm ModularFormClass CuspForm ModularForm.CuspForm Polynomial Real.Polynomial Filter"
variable {N : ℕ}

def periodPairOfTau (τ : ℍ) : PeriodPair where
  ω₁ := (τ : ℂ)
  ω₂ := 1
  indep := LinearIndependent.pair_iff.mpr fun s t hst ↦ by
    have him : s * (τ : ℂ).im = 0 := by
      have := congrArg Complex.im hst
      simpa [Complex.add_im, Complex.smul_im, smul_eq_mul] using this
    have hs : s = 0 :=
      (mul_eq_zero.mp him).resolve_right (UpperHalfPlane.coe_im τ ▸ τ.im_ne_zero)
    subst hs
    simpa using hst

@[scoped simp] lemma periodPairOfTau_ω₁ (τ : ℍ) : (periodPairOfTau τ).ω₁ = (τ : ℂ) := rfl
@[scoped simp] lemma periodPairOfTau_ω₂ (τ : ℍ) : (periodPairOfTau τ).ω₂ = 1 := rfl

def zetaN (N : ℕ) : ℂ := cexp (2 * π * I / N)

def wpTorsion (N a₁ a₂ : ℕ) (τ : ℍ) : ℂ :=
  PeriodPair.weierstrassP (periodPairOfTau τ) (((a₁ : ℂ) * τ + a₂) / N)

def kN (N : ℕ) : IntermediateField ℚ ℂ := IntermediateField.adjoin ℚ {zetaN N}

def wpNorm (N a₁ a₂ : ℕ) (τ : ℍ) : ℂ := ((2 * π * I) ^ 2)⁻¹ * wpTorsion N a₁ a₂ τ

def j : ℍ → ℂ := fun z => E₄ z ^ 3 / ModularForm.discriminant z

def vecMulSL (N : ℕ) (a : Fin 2 → ZMod N) (γ : SL(2, ℤ)) : Fin 2 → ZMod N :=
  Matrix.vecMul a ((γ : Matrix (Fin 2) (Fin 2) ℤ).map ((↑) : ℤ → ZMod N))

def wpNormZ (N : ℕ) (a : Fin 2 → ZMod N) (τ : ℍ) : ℂ := wpNorm N (a 0).val (a 1).val τ

def frickeF (N : ℕ) (a : Fin 2 → ZMod N) (τ : ℍ) : ℂ :=
  -(ModularForm.E₄ τ * ModularForm.E₆ τ / ModularForm.discriminant τ) / 2592 * wpNormZ N a τ

abbrev FrickeIdx (N : ℕ) : Type := {a : Fin 2 → ZMod N // a ≠ 0}

def KPoleAt (K : IntermediateField ℚ ℂ) (N m : ℕ) (f : ℍ → ℂ) : Prop :=
  Function.Periodic ((f * ⇑CuspForm.discriminant ^ m) ∘ ofComplex) N ∧
    IsBoundedAtImInfty (f * ⇑CuspForm.discriminant ^ m) ∧
    ∀ n : ℕ, (qExpansion N (f * ⇑CuspForm.discriminant ^ m)).coeff n ∈ K

def KPole (K : IntermediateField ℚ ℂ) (N : ℕ) (f : ℍ → ℂ) : Prop :=
  MDiff f ∧ ∃ m : ℕ, KPoleAt K N m f

p2m_open "UpperHalfPlane~I"

def levelGen (N : ℕ) : Set (ℍ → ℂ) := insert j (Set.range fun i : FrickeIdx N ↦ frickeF N i.1)

private lemma hppT : ∀ τ : ℍ, (periodPairOfTau τ).ω₁ = (τ : ℂ) ∧ (periodPairOfTau τ).ω₂ = 1 :=
  fun τ => ⟨periodPairOfTau_ω₁ τ, periodPairOfTau_ω₂ τ⟩

private lemma coe_cuspDisc : ⇑CuspForm.discriminant = ModularForm.discriminant := rfl

private lemma frickeF_eq (N : ℕ) (a : Fin 2 → ZMod N) :
    frickeF N a = fun τ =>
      -(ModularForm.E₄ τ * ModularForm.E₆ τ / ModularForm.discriminant τ) / 2592 *
        (((2 * π * I) ^ 2)⁻¹ *
          PeriodPair.weierstrassP (periodPairOfTau τ)
            ((((a 0).val : ℂ) * (τ : ℂ) + ((a 1).val : ℂ)) / (N : ℂ))) := by
  funext τ
  simp only [frickeF, wpNormZ, wpNorm, wpTorsion]

theorem kPole_invariant_eq_polynomial_j_mem {K : IntermediateField ℚ ℂ} [NeZero N]
    {a : ℍ → ℂ} (hk : KPole K N a) (hinv : ∀ γ : SL(2, ℤ), a ∣[(0 : ℤ)] γ = a) :
    ∃ P : Polynomial ℂ, (∀ i, P.coeff i ∈ K) ∧ a = fun τ => Polynomial.eval (j τ) P := by
  obtain ⟨hmd, m, hper, hbd, hcoef⟩ := hk
  rw [coe_cuspDisc] at hper hbd hcoef
  obtain ⟨P, _, hcoefP, heq⟩ :=
    levelOne_hauptmodul_package.2.1 K N (NeZero.ne N) m a hmd hinv hper hbd hcoef
  exact ⟨P, hcoefP, by simpa only [j] using heq⟩

theorem mdifferentiable_frickeF {N : ℕ} [NeZero N] (i : FrickeIdx N) :
    MDifferentiable 𝓘(ℂ) 𝓘(ℂ) (frickeF N i.1) := by
  rw [frickeF_eq]
  exact (frickeFunction_modularity_package N periodPairOfTau hppT).2.2.1 i.1 i.2

theorem isBoundedAtImInfty_frickeF_mul_discriminant {N : ℕ} [NeZero N] (i : FrickeIdx N) :
    IsBoundedAtImInfty (frickeF N i.1 * ⇑CuspForm.discriminant) := by
  rw [frickeF_eq, coe_cuspDisc]
  exact (frickeFunction_modularity_package N periodPairOfTau hppT).2.2.2.1 i.1 i.2

private lemma vecMulSL_mul (N : ℕ) (a : Fin 2 → ZMod N) (γ δ : SL(2, ℤ)) :
    vecMulSL N (vecMulSL N a γ) δ = vecMulSL N a (γ * δ) := by
  simp only [vecMulSL, Matrix.vecMul_vecMul]
  congr 1
  ext i k
  simp [Matrix.map_apply, Matrix.mul_apply, Matrix.SpecialLinearGroup.coe_mul]

private lemma vecMulSL_one (N : ℕ) (a : Fin 2 → ZMod N) : vecMulSL N a 1 = a := by
  simp only [vecMulSL, Matrix.SpecialLinearGroup.coe_one,
    Matrix.map_one ((↑) : ℤ → ZMod N) Int.cast_zero Int.cast_one, Matrix.vecMul_one]

private lemma vecMulSL_zero (N : ℕ) (γ : SL(2, ℤ)) : vecMulSL N (0 : Fin 2 → ZMod N) γ = 0 := by
  simp [vecMulSL]

lemma vecMulSL_ne_zero {N : ℕ} {a : Fin 2 → ZMod N} (ha : a ≠ 0) (γ : SL(2, ℤ)) :
    vecMulSL N a γ ≠ 0 := by
  intro h0
  apply ha
  have h1 : vecMulSL N (vecMulSL N a γ) γ⁻¹ = a := by
    rw [vecMulSL_mul, mul_inv_cancel, vecMulSL_one]
  rw [← h1, h0, vecMulSL_zero]

theorem frickeF_hperm {N : ℕ} [NeZero N] (γ : SL(2, ℤ)) :
    ∃ σ : Equiv.Perm (FrickeIdx N), ∀ (i : FrickeIdx N) (τ : ℍ),
      frickeF N i.1 (γ • τ) = frickeF N (σ i).1 τ := by
  refine ⟨⟨fun i => ⟨vecMulSL N i.1 γ, vecMulSL_ne_zero i.2 γ⟩,
          fun i => ⟨vecMulSL N i.1 γ⁻¹, vecMulSL_ne_zero i.2 γ⁻¹⟩, ?_, ?_⟩, ?_⟩
  · intro i
    apply Subtype.ext
    simp only [vecMulSL_mul, mul_inv_cancel, vecMulSL_one]
  · intro i
    apply Subtype.ext
    simp only [vecMulSL_mul, inv_mul_cancel, vecMulSL_one]
  · intro i τ
    have h1 := (frickeFunction_modularity_package N periodPairOfTau hppT).1 i.1 γ τ
    rw [frickeF_eq, frickeF_eq]
    exact h1

section KPoleClosure

private lemma ratCast_mem_K (K : IntermediateField ℚ ℂ) (q : ℚ) : (q : ℂ) ∈ K :=
  eq_ratCast (algebraMap ℚ ℂ) q ▸ IntermediateField.algebraMap_mem K q

private lemma hNposR (N : ℕ) [NeZero N] : (0 : ℝ) < N := by
  exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne N)

private lemma disc_hol : MDiff (⇑CuspForm.discriminant : ℍ → ℂ) := CuspForm.discriminant.holo'

private lemma disc_bdd : IsBoundedAtImInfty (⇑CuspForm.discriminant : ℍ → ℂ) :=
  (CuspFormClass.zero_at_infty CuspForm.discriminant).isBoundedAtImInfty

private lemma disc_per1 :
    Function.Periodic ((⇑CuspForm.discriminant : ℍ → ℂ) ∘ ofComplex) 1 := by
  simpa using SlashInvariantFormClass.periodic_comp_ofComplex CuspForm.discriminant one_mem_strictPeriods_SL

private lemma E4_per1 :
    Function.Periodic ((⇑ModularForm.E₄ : ℍ → ℂ) ∘ ofComplex) 1 := by
  simpa using SlashInvariantFormClass.periodic_comp_ofComplex ModularForm.E₄ one_mem_strictPeriods_SL

private lemma E4_hol : MDiff (⇑ModularForm.E₄ : ℍ → ℂ) := ModularForm.E₄.holo'

private lemma E4_bdd : IsBoundedAtImInfty (⇑ModularForm.E₄ : ℍ → ℂ) :=
  ModularFormClass.bdd_at_infty ModularForm.E₄

private def NiceK (K : IntermediateField ℚ ℂ) (N : ℕ) (f : ℍ → ℂ) : Prop :=
  Function.Periodic (f ∘ ofComplex) (N : ℂ) ∧ MDiff f ∧ IsBoundedAtImInfty f ∧
    ∀ n, (qExpansion N f).coeff n ∈ K

private lemma NiceK.analytic {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f : ℍ → ℂ}
    (hf : NiceK K N f) : AnalyticAt ℂ (cuspFunction N f) 0 :=
  analyticAt_cuspFunction_zero (hNposR N) (by exact_mod_cast hf.1) hf.2.1 hf.2.2.1

private lemma perN_of_per1 {f : ℍ → ℂ} (hp : Function.Periodic (f ∘ ofComplex) 1) (N : ℕ) :
    Function.Periodic (f ∘ ofComplex) (N : ℂ) := by
  simpa using hp.nat_mul N

private lemma NiceK.mul {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f g : ℍ → ℂ}
    (hf : NiceK K N f) (hg : NiceK K N g) : NiceK K N (f * g) := by
  refine ⟨hf.1.mul hg.1, hf.2.1.mul hg.2.1, hf.2.2.1.mul hg.2.2.1, fun n => ?_⟩
  rw [qExpansion_mul hf.analytic hg.analytic, PowerSeries.coeff_mul]
  exact sum_mem fun p _ => mul_mem (hf.2.2.2 p.1) (hg.2.2.2 p.2)

private lemma NiceK.pow {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f : ℍ → ℂ}
    (hf : NiceK K N f) : ∀ k : ℕ, k ≠ 0 → NiceK K N (f ^ k)
  | 1, _ => by simpa using hf
  | (k + 2), _ => by
      rw [pow_succ]
      exact (NiceK.pow hf (k + 1) k.succ_ne_zero).mul hf

private lemma NiceK.add {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f g : ℍ → ℂ}
    (hf : NiceK K N f) (hg : NiceK K N g) : NiceK K N (f + g) := by
  refine ⟨hf.1.add hg.1, hf.2.1.add hg.2.1, hf.2.2.1.add hg.2.2.1, fun n => ?_⟩
  rw [qExpansion_add hf.analytic hg.analytic, map_add]
  exact add_mem (hf.2.2.2 n) (hg.2.2.2 n)

private lemma NiceK.disc {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] :
    NiceK K N (⇑CuspForm.discriminant : ℍ → ℂ) := by
  refine ⟨perN_of_per1 disc_per1 N, disc_hol, disc_bdd, fun n => ?_⟩
  have hd := (weierstrassP_torsion_qExpansion_package N (NeZero.ne N) periodPairOfTau
      hppT).2.2.2.1 (⇑CuspForm.discriminant : ℍ → ℂ) (by simpa using disc_per1) disc_hol disc_bdd n
  rw [hd]
  split_ifs
  · obtain ⟨q, hq⟩ := (weierstrassP_torsion_qExpansion_package N (NeZero.ne N) periodPairOfTau
        hppT).2.2.2.2.2.2 (n / N)
    rw [show (⇑CuspForm.discriminant : ℍ → ℂ) = (ModularForm.discriminant : ℍ → ℂ) from
      coe_cuspDisc, hq]
    exact ratCast_mem_K K q
  · exact zero_mem K

private lemma NiceK.E4 {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] :
    NiceK K N (⇑ModularForm.E₄ : ℍ → ℂ) := by
  refine ⟨perN_of_per1 E4_per1 N, E4_hol, E4_bdd, fun n => ?_⟩
  have hd := (weierstrassP_torsion_qExpansion_package N (NeZero.ne N) periodPairOfTau
      hppT).2.2.2.1 (⇑ModularForm.E₄ : ℍ → ℂ) (by simpa using E4_per1) E4_hol E4_bdd n
  rw [hd]
  split_ifs
  · obtain ⟨q, hq⟩ := (weierstrassP_torsion_qExpansion_package N (NeZero.ne N) periodPairOfTau
        hppT).2.2.2.2.1 (n / N)
    rw [hq]
    exact ratCast_mem_K K q
  · exact zero_mem K

private lemma cuspFunction_const (N : ℕ) (c : ℂ) :
    cuspFunction N (fun _ : ℍ => c) = fun _ => c := by
  funext q
  rcases eq_or_ne q 0 with rfl | hq
  · show Function.Periodic.cuspFunction N ((fun _ : ℍ => c) ∘ ofComplex) 0 = c
    rw [Function.Periodic.cuspFunction_zero_eq_limUnder_nhds_ne]
    refine Filter.Tendsto.limUnder_eq ?_
    refine Filter.Tendsto.congr' ?_ (tendsto_const_nhds :
      Filter.Tendsto (fun _ : ℂ => (c : ℂ)) (nhdsWithin (0 : ℂ) {(0 : ℂ)}ᶜ) (nhds (c : ℂ)))
    filter_upwards [self_mem_nhdsWithin] with q hq
    exact (Function.Periodic.cuspFunction_eq_of_nonzero (N : ℝ)
      ((fun _ : ℍ => (c : ℂ)) ∘ ofComplex) hq).symm
  · show Function.Periodic.cuspFunction N ((fun _ : ℍ => c) ∘ ofComplex) q = c
    rw [Function.Periodic.cuspFunction_eq_of_nonzero _ _ hq]
    rfl

private lemma NiceK.const {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] (c : ↥K) :
    NiceK K N (fun _ : ℍ => (c : ℂ)) := by
  refine ⟨fun x => rfl, ?_, ?_, fun n => ?_⟩
  · exact mdifferentiable_const
  · exact Filter.const_boundedAtFilter _ _
  · have hq : qExpansion N (fun _ : ℍ => (c : ℂ)) = PowerSeries.C (c : ℂ) := by
      ext m
      simp only [qExpansion_coeff, cuspFunction_const, iteratedDeriv_const, PowerSeries.coeff_C]
      rcases eq_or_ne m 0 with rfl | hm
      · simp
      · simp [hm]
    rw [hq]
    rcases eq_or_ne n 0 with rfl | hn
    · simp
    · simp [PowerSeries.coeff_C, hn]

private lemma kPoleAt_of_niceK {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f : ℍ → ℂ} {m : ℕ}
    (h : NiceK K N (f * ⇑CuspForm.discriminant ^ m)) : KPoleAt K N m f :=
  ⟨by exact_mod_cast h.1, h.2.2.1, h.2.2.2⟩

private lemma niceK_mul_disc_pow {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f : ℍ → ℂ} {m : ℕ}
    (hmd : MDiff f) (hf : KPoleAt K N m f) : NiceK K N (f * ⇑CuspForm.discriminant ^ m) :=
  ⟨by exact_mod_cast hf.1, hmd.mul (disc_hol.pow m), hf.2.1, hf.2.2⟩

private lemma kPole_const {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] (c : ↥K) :
    KPole K N (algebraMap ↥K (ℍ → ℂ) c) := by
  have hc : algebraMap ↥K (ℍ → ℂ) c = fun _ : ℍ => (c : ℂ) := rfl
  rw [hc]
  refine ⟨mdifferentiable_const, 0, kPoleAt_of_niceK ?_⟩
  simpa using NiceK.const c

private lemma kPole_add {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f g : ℍ → ℂ}
    (hf : KPole K N f) (hg : KPole K N g) : KPole K N (f + g) := by
  obtain ⟨hfm, mf, hfa⟩ := hf
  obtain ⟨hgm, mg, hga⟩ := hg
  have hf' : NiceK K N (f * ⇑CuspForm.discriminant ^ (mf + mg)) := by
    have : f * ⇑CuspForm.discriminant ^ (mf + mg)
        = (f * ⇑CuspForm.discriminant ^ mf) * ⇑CuspForm.discriminant ^ mg := by
      rw [mul_assoc, ← pow_add]
    rcases Nat.eq_zero_or_pos mg with rfl | hmg
    · simpa using niceK_mul_disc_pow hfm hfa
    · rw [this]
      exact (niceK_mul_disc_pow hfm hfa).mul (NiceK.disc.pow mg hmg.ne')
  have hg' : NiceK K N (g * ⇑CuspForm.discriminant ^ (mf + mg)) := by
    have : g * ⇑CuspForm.discriminant ^ (mf + mg)
        = (g * ⇑CuspForm.discriminant ^ mg) * ⇑CuspForm.discriminant ^ mf := by
      rw [mul_assoc, ← pow_add, Nat.add_comm]
    rcases Nat.eq_zero_or_pos mf with rfl | hmf
    · simpa using niceK_mul_disc_pow hgm hga
    · rw [this]
      exact (niceK_mul_disc_pow hgm hga).mul (NiceK.disc.pow mf hmf.ne')
  refine ⟨hfm.add hgm, mf + mg, kPoleAt_of_niceK ?_⟩
  have : (f + g) * ⇑CuspForm.discriminant ^ (mf + mg)
      = f * ⇑CuspForm.discriminant ^ (mf + mg) + g * ⇑CuspForm.discriminant ^ (mf + mg) :=
    add_mul f g _
  rw [this]
  exact hf'.add hg'

private lemma kPole_mul {K : IntermediateField ℚ ℂ} {N : ℕ} [NeZero N] {f g : ℍ → ℂ}
    (hf : KPole K N f) (hg : KPole K N g) : KPole K N (f * g) := by
  obtain ⟨hfm, mf, hfa⟩ := hf
  obtain ⟨hgm, mg, hga⟩ := hg
  refine ⟨hfm.mul hgm, mf + mg, kPoleAt_of_niceK ?_⟩
  have : (f * g) * ⇑CuspForm.discriminant ^ (mf + mg)
      = (f * ⇑CuspForm.discriminant ^ mf) * (g * ⇑CuspForm.discriminant ^ mg) := by
    rw [pow_add]; ring
  rw [this]
  exact (niceK_mul_disc_pow hfm hfa).mul (niceK_mul_disc_pow hgm hga)

theorem kPole_of_mem_adjoin {K : IntermediateField ℚ ℂ} [NeZero N] {S : Set (ℍ → ℂ)}
    (hS : ∀ f ∈ S, KPole K N f) {a : ℍ → ℂ} (ha : a ∈ Algebra.adjoin ↥K S) : KPole K N a := by
  induction ha using Algebra.adjoin_induction with
  | mem f hf => exact hS f hf
  | algebraMap c => exact kPole_const c
  | add f g _ _ ihf ihg => exact kPole_add ihf ihg
  | mul f g _ _ ihf ihg => exact kPole_mul ihf ihg

lemma kPole_j (K : IntermediateField ℚ ℂ) [NeZero N] : KPole K N j := by
  have hmd : MDiff j := by
    intro τ
    exact (((E4_hol τ).pow 3).div (disc_hol τ) (ModularForm.discriminant_ne_zero τ))
  refine ⟨hmd, 1, kPoleAt_of_niceK ?_⟩
  have hjd : j * ⇑CuspForm.discriminant ^ 1 = (⇑ModularForm.E₄ : ℍ → ℂ) ^ 3 := by
    funext τ
    simp only [Pi.mul_apply, Pi.pow_apply, pow_one, j, coe_cuspDisc]
    field_simp [ModularForm.discriminant_ne_zero τ]
  rw [hjd]
  exact NiceK.E4.pow 3 (by norm_num)

lemma kPole_frickeF {K : IntermediateField ℚ ℂ} [NeZero N] (hK : kN N ≤ K) (i : FrickeIdx N) :
    KPole K N (frickeF N i.1) := by
  have pkg := frickeFunction_modularity_package N periodPairOfTau hppT
  have hmd : MDiff (frickeF N i.1) := mdifferentiable_frickeF i
  refine ⟨hmd, 1, ?_, ?_, ?_⟩
  · have hper := (pkg.2.2.2.2.1 i.1 i.2).1
    rw [frickeF_eq, coe_cuspDisc]
    simpa [pow_one] using hper
  · have hbd := pkg.2.2.2.1 i.1 i.2
    rw [frickeF_eq, coe_cuspDisc]
    simpa [pow_one] using hbd
  · intro n
    have hco := (pkg.2.2.2.2.1 i.1 i.2).2 n
    rw [frickeF_eq, coe_cuspDisc]
    refine hK ?_
    simpa [pow_one, kN, zetaN] using hco

end KPoleClosure

end R4bFloor

section B6Engine

p2m_open "UpperHalfPlane ModularForm SlashInvariantForm ModularFormClass CuspForm ModularForm.CuspForm Polynomial Real.Polynomial"
open scoped MatrixGroups Manifold

variable {I : Type*} [Fintype I] (h : I → ℍ → ℂ) (m : ℕ)

def orbitCoeff (k : ℕ) : ℍ → ℂ := fun τ => (∏ i, (X - C (h i τ))).coeff k

lemma coeff_X_sub_C_mul (a : ℂ) (p : Polynomial ℂ) (k : ℕ) :
    ((X - C a) * p).coeff k = (if k = 0 then 0 else p.coeff (k - 1)) - a * p.coeff k := by
  rw [sub_mul, Polynomial.coeff_sub, Polynomial.coeff_C_mul]
  congr 1
  cases k with
  | zero => simp [Polynomial.mul_coeff_zero]
  | succ k' => simp [Polynomial.coeff_X_mul]

theorem orbitCoeff_slash_invariant
    (hperm : ∀ γ : SL(2, ℤ), ∃ σ : Equiv.Perm I, ∀ i τ, h i (γ • τ) = h (σ i) τ)
    (k : ℕ) (γ : SL(2, ℤ)) : orbitCoeff h k ∣[(0 : ℤ)] γ = orbitCoeff h k := by
  obtain ⟨σ, hσ⟩ := hperm γ
  funext τ
  simp only [SL_slash_apply, neg_zero, zpow_zero, mul_one]
  show (∏ i, (X - C (h i (γ • τ)))).coeff k = (∏ i, (X - C (h i τ))).coeff k
  congr 2
  calc ∏ i, (X - C (h i (γ • τ)))
    _ = ∏ i, (X - C (h (σ i) τ)) := by
      refine Finset.prod_congr rfl fun i _ => ?_
      rw [hσ i τ]
    _ = ∏ i, (X - C (h i τ)) := Equiv.prod_comp σ (fun i' => X - C (h i' τ))

end B6Engine

section B6Ring

p2m_open "UpperHalfPlane ModularForm SlashInvariantForm ModularFormClass CuspForm ModularForm.CuspForm Polynomial Real.Polynomial Filter"
open scoped MatrixGroups Manifold

def PoleBounded (f : ℍ → ℂ) : Prop :=
  MDiff f ∧ ∃ m : ℕ, IsBoundedAtImInfty (f * ⇑CuspForm.discriminant ^ m)

lemma poleBounded_j : PoleBounded j := by
  constructor
  · exact (ModularForm.E₄.holo'.pow 3).div CuspForm.discriminant.holo'
      ModularForm.discriminant_ne_zero
  · refine ⟨1, ?_⟩
    have hshape : (j * ⇑CuspForm.discriminant ^ 1 : ℍ → ℂ) = ⇑ModularForm.E₄ ^ 3 := by
      funext τ
      simp only [Pi.mul_apply, Pi.pow_apply, pow_one, j]
      rw [congrFun CuspForm.coe_discriminant τ]
      exact div_mul_cancel₀ _ (ModularForm.discriminant_ne_zero τ)
    rw [hshape]
    have h4 : IsBoundedAtImInfty (⇑ModularForm.E₄ : ℍ → ℂ) := ModularFormClass.bdd_at_infty _
    have hpow : (⇑ModularForm.E₄ ^ 3 : ℍ → ℂ) =
        ⇑ModularForm.E₄ * (⇑ModularForm.E₄ * ⇑ModularForm.E₄) := by
      funext τ
      simp only [Pi.pow_apply, Pi.mul_apply]
      ring
    rw [hpow]
    exact h4.mul (h4.mul h4)

lemma poleBounded_frickeF {N : ℕ} [NeZero N] (i : FrickeIdx N) :
    PoleBounded (frickeF N i.1) := by
  refine ⟨mdifferentiable_frickeF i, 1, ?_⟩
  have hshape : (frickeF N i.1 * ⇑CuspForm.discriminant ^ 1 : ℍ → ℂ) =
      frickeF N i.1 * ⇑CuspForm.discriminant := by
    funext τ
    simp
  rw [hshape]
  exact isBoundedAtImInfty_frickeF_mul_discriminant i

end B6Ring

section LevelRingK

p2m_open "UpperHalfPlane ModularForm CuspForm ModularForm.CuspForm Polynomial Real.Polynomial"
open scoped MatrixGroups Manifold

variable {N : ℕ}

noncomputable def levelRingK (K : IntermediateField ℚ ℂ) (N : ℕ) : Subalgebra ↥K (ℍ → ℂ) :=
  Algebra.adjoin ↥K (levelGen N)

lemma frickeF_mem_levelRingK {K : IntermediateField ℚ ℂ} [NeZero N] (i : FrickeIdx N) :
    frickeF N i.1 ∈ levelRingK K N :=
  Algebra.subset_adjoin (Set.mem_insert_iff.mpr (Or.inr ⟨i, rfl⟩))

theorem kPole_of_mem_levelRingK {K : IntermediateField ℚ ℂ} [NeZero N] (hK : kN N ≤ K)
    {f : ℍ → ℂ} (hf : f ∈ levelRingK K N) : KPole K N f :=
  kPole_of_mem_adjoin (fun g hg => by
    rcases hg with rfl | ⟨i, rfl⟩
    · exact kPole_j K
    · exact kPole_frickeF hK i) hf

end LevelRingK

section B6InstanceK

p2m_open "UpperHalfPlane ModularForm CuspForm ModularForm.CuspForm Polynomial Real.Polynomial"
open scoped MatrixGroups Manifold

variable {N : ℕ}

lemma orbitCoeffOn_frickeF_mem_levelRingK [NeZero N] (s : Finset (FrickeIdx N)) (k : ℕ) :
    (fun τ : ℍ => (∏ i ∈ s, (X - C (frickeF N i.1 τ))).coeff k) ∈ levelRingK (kN N) N := by
  induction s using Finset.cons_induction generalizing k with
  | empty =>
    simp only [Finset.prod_empty, Polynomial.coeff_one]
    cases k with
    | zero => exact one_mem (levelRingK (kN N) N)
    | succ k' => exact zero_mem (levelRingK (kN N) N)
  | cons a s ha ih =>
    cases k with
    | zero =>
      have hrw : (fun τ : ℍ =>
          (∏ i ∈ Finset.cons a s ha, (X - C (frickeF N i.1 τ))).coeff 0) =
          -(frickeF N a.1 * fun τ : ℍ => (∏ i ∈ s, (X - C (frickeF N i.1 τ))).coeff 0) := by
        funext τ
        simp only [Finset.prod_cons, coeff_X_sub_C_mul, ite_true, Pi.neg_apply, Pi.mul_apply]
        ring
      rw [hrw]
      exact neg_mem (mul_mem (frickeF_mem_levelRingK a) (ih 0))
    | succ k' =>
      have hrw : (fun τ : ℍ =>
          (∏ i ∈ Finset.cons a s ha, (X - C (frickeF N i.1 τ))).coeff (k' + 1)) =
          ((fun τ : ℍ => (∏ i ∈ s, (X - C (frickeF N i.1 τ))).coeff k') -
            frickeF N a.1 * fun τ : ℍ =>
              (∏ i ∈ s, (X - C (frickeF N i.1 τ))).coeff (k' + 1)) := by
        funext τ
        simp only [Finset.prod_cons, coeff_X_sub_C_mul, ite_eq_right (Nat.succ_ne_zero k'),
          Nat.add_sub_cancel, Pi.sub_apply, Pi.mul_apply]
      rw [hrw]
      exact sub_mem (ih k') (mul_mem (frickeF_mem_levelRingK a) (ih (k' + 1)))

theorem frickeF_integral_over_j_mem_kN (N : ℕ) [NeZero N] :
    ∃ P : ℕ → Polynomial ℂ,
      (∀ k i, (P k).coeff i ∈ kN N) ∧
      ∀ (i : FrickeIdx N) (τ : ℍ),
        frickeF N i.1 τ ^ Fintype.card (FrickeIdx N) +
          ∑ k ∈ Finset.range (Fintype.card (FrickeIdx N)),
            Polynomial.eval (j τ) (P k) * frickeF N i.1 τ ^ k = 0 := by
  have hdesc : ∀ k : ℕ, ∃ P : Polynomial ℂ, (∀ i, P.coeff i ∈ kN N) ∧
      orbitCoeff (fun i : FrickeIdx N => frickeF N i.1) k =
        fun τ => Polynomial.eval (j τ) P := by
    intro k
    have hmem : orbitCoeff (fun i : FrickeIdx N => frickeF N i.1) k ∈ levelRingK (kN N) N := by
      have h1 := orbitCoeffOn_frickeF_mem_levelRingK (N := N) Finset.univ k
      simp [] at h1
      exact h1
    exact kPole_invariant_eq_polynomial_j_mem (kPole_of_mem_levelRingK le_rfl hmem)
      (orbitCoeff_slash_invariant (fun i : FrickeIdx N => frickeF N i.1)
        (fun γ => frickeF_hperm γ) k)
  choose P hPmem hP using hdesc
  refine ⟨P, hPmem, fun i τ => ?_⟩
  set Q : Polynomial ℂ := ∏ i' : FrickeIdx N, (X - C (frickeF N i'.1 τ)) with hQ
  have hQmonic : Q.Monic := monic_prod_of_monic _ _ fun i' _ => monic_X_sub_C _
  have hQdeg : Q.natDegree = Fintype.card (FrickeIdx N) := by
    rw [hQ, natDegree_prod_of_monic _ _ (fun i' _ => monic_X_sub_C _)]
    simp
  have hroot : Polynomial.eval (frickeF N i.1 τ) Q = 0 := by
    rw [hQ, Polynomial.eval_prod]
    exact Finset.prod_eq_zero (Finset.mem_univ i) (by simp)
  have hexp := Polynomial.eval_eq_sum_range' (n := Fintype.card (FrickeIdx N) + 1)
    (by rw [hQdeg]; exact Nat.lt_succ_self _) (frickeF N i.1 τ) (p := Q)
  rw [Finset.sum_range_succ] at hexp
  have hlead : Q.coeff (Fintype.card (FrickeIdx N)) = 1 := by
    have h1 := hQmonic.coeff_natDegree
    rwa [hQdeg] at h1
  have hcoeffs : ∀ k, Q.coeff k = Polynomial.eval (j τ) (P k) := by
    intro k
    have h1 := congrFun (hP k) τ
    simpa [orbitCoeff, hQ] using h1
  rw [hroot.symm, hexp, hlead, one_mul, add_comm]
  congr 1
  exact Finset.sum_congr rfl fun k _ => by rw [hcoeffs k]

end B6InstanceK

section R4bBridge

p2m_open "WLight P2MW.S_WLight_frickeFunction_orbit_package.WLight"
p2m_open "UpperHalfPlane~I"
open scoped Manifold MatrixGroups ModularForm

private lemma periodPair_ext'' {L₁ L₂ : PeriodPair} (h₁ : L₁.ω₁ = L₂.ω₁)
    (h₂ : L₁.ω₂ = L₂.ω₂) : L₁ = L₂ := by
  cases L₁; cases L₂; simp_all

end R4bBridge

end WLight
p2m_reactivate "P2MW.S_WLight_frickeFunction_orbit_package.WLight"

p2m_open "UpperHalfPlane~I" in
open scoped UpperHalfPlane Manifold MatrixGroups ModularForm in
open _root_.WLight _root_.P2MW.S_WLight_frickeFunction_orbit_package.WLight in
theorem solution
    (N : ℕ) [NeZero N]
    (L : ℍ → PeriodPair) (hL : ∀ τ : ℍ, (L τ).ω₁ = (τ : ℂ) ∧ (L τ).ω₂ = 1)
    (W : (Fin 2 → ZMod N) → ℍ → ℂ)
    (hW : ∀ (v : Fin 2 → ZMod N) (τ : ℍ), W v τ = ((2 * (Real.pi : ℂ) * Complex.I) ^ 2)⁻¹ *
      PeriodPair.weierstrassP (L τ) ((((v 0).val : ℂ) * (τ : ℂ) + ((v 1).val : ℂ)) / (N : ℂ)))
    (fricke : (Fin 2 → ZMod N) → ℍ → ℂ)
    (hfricke : ∀ (v : Fin 2 → ZMod N) (τ : ℍ), fricke v τ =
      -(ModularForm.E₄ τ * ModularForm.E₆ τ / ModularForm.discriminant τ) / 2592 * W v τ)
    (jf : ℍ → ℂ)
    (hjf : ∀ τ : ℍ, jf τ = ModularForm.E₄ τ ^ 3 / ModularForm.discriminant τ) :
    (MDifferentiable 𝓘(ℂ) 𝓘(ℂ) jf ∧
      ∃ m : ℕ, IsBoundedAtImInfty (jf * ModularForm.discriminant ^ m)) ∧
    (∀ v : Fin 2 → ZMod N, v ≠ 0 → MDifferentiable 𝓘(ℂ) 𝓘(ℂ) (fricke v) ∧
      ∃ m : ℕ, IsBoundedAtImInfty (fricke v * ModularForm.discriminant ^ m)) ∧
    (∃ P : ℕ → Polynomial ℂ,
      (∀ k i, (P k).coeff i ∈
        IntermediateField.adjoin ℚ {Complex.exp (2 * (Real.pi : ℂ) * Complex.I / N)}) ∧
      ∀ v : Fin 2 → ZMod N, v ≠ 0 → ∀ τ : ℍ,
        fricke v τ ^ (N ^ 2 - 1) + ∑ k ∈ Finset.range (N ^ 2 - 1),
          (P k).eval (jf τ) * fricke v τ ^ k = 0) := by
  have hLpp : ∀ τ : ℍ, L τ = periodPairOfTau τ := fun τ =>
    periodPair_ext'' ((hL τ).1.trans (periodPairOfTau_ω₁ τ).symm)
      ((hL τ).2.trans (periodPairOfTau_ω₂ τ).symm)
  have hfr : ∀ v : Fin 2 → ZMod N, fricke v = frickeF N v := by
    intro v
    funext τ
    rw [hfricke v τ, hW v τ, hLpp τ]
    with_unfolding_all rfl
  have hjeq : jf = j := by
    funext τ
    rw [hjf τ]
    rfl
  have hcard : Fintype.card (FrickeIdx N) = N ^ 2 - 1 := by
    have h1 : Fintype.card (Fin 2 → ZMod N) = N ^ 2 := by
      rw [Fintype.card_fun, ZMod.card, Fintype.card_fin]
    have h2 : Fintype.card {a : Fin 2 → ZMod N // a = 0} = 1 := Fintype.card_subtype_eq 0
    have h3 := Fintype.card_subtype_compl (fun a : Fin 2 → ZMod N => a = 0)
    rw [h1, h2] at h3
    exact h3
  refine ⟨?_, ?_, ?_⟩
  · obtain ⟨h1, m, h2⟩ := poleBounded_j
    refine ⟨by rw [hjeq]; exact h1, m, ?_⟩
    rw [hjeq, ← CuspForm.coe_discriminant]
    exact h2
  · intro v hv
    obtain ⟨h1, m, h2⟩ := poleBounded_frickeF (⟨v, hv⟩ : FrickeIdx N)
    refine ⟨by rw [hfr]; exact h1, m, ?_⟩
    rw [hfr, ← CuspForm.coe_discriminant]
    exact h2
  · obtain ⟨P, hPmem, hPrel⟩ := frickeF_integral_over_j_mem_kN N
    refine ⟨P, fun k i => hPmem k i, fun v hv τ => ?_⟩
    have h := hPrel ⟨v, hv⟩ τ
    rw [hfr v, hjeq, ← hcard]
    exact h

end
end S_WLight_frickeFunction_orbit_package
end P2MW
export P2MW.S_WLight_frickeFunction_orbit_package (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open Complex Real UpperHalfPlane
open scoped Manifold MatrixGroups ModularForm
theorem WLight.frickeFunction_orbit_package
    (N : ℕ) [NeZero N]
    (L : ℍ → PeriodPair) (hL : ∀ τ : ℍ, (L τ).ω₁ = (τ : ℂ) ∧ (L τ).ω₂ = 1)
    (W : (Fin 2 → ZMod N) → ℍ → ℂ)
    (hW : ∀ (v : Fin 2 → ZMod N) (τ : ℍ), W v τ = ((2 * (Real.pi : ℂ) * Complex.I) ^ 2)⁻¹ *
      PeriodPair.weierstrassP (L τ) ((((v 0).val : ℂ) * (τ : ℂ) + ((v 1).val : ℂ)) / (N : ℂ)))
    (fricke : (Fin 2 → ZMod N) → ℍ → ℂ)
    (hfricke : ∀ (v : Fin 2 → ZMod N) (τ : ℍ), fricke v τ =
      -(ModularForm.E₄ τ * ModularForm.E₆ τ / ModularForm.discriminant τ) / 2592 * W v τ)
    (jf : ℍ → ℂ)
    (hjf : ∀ τ : ℍ, jf τ = ModularForm.E₄ τ ^ 3 / ModularForm.discriminant τ) :
    (MDifferentiable 𝓘(ℂ) 𝓘(ℂ) jf ∧
      ∃ m : ℕ, IsBoundedAtImInfty (jf * ModularForm.discriminant ^ m)) ∧
    (∀ v : Fin 2 → ZMod N, v ≠ 0 → MDifferentiable 𝓘(ℂ) 𝓘(ℂ) (fricke v) ∧
      ∃ m : ℕ, IsBoundedAtImInfty (fricke v * ModularForm.discriminant ^ m)) ∧
    (∃ P : ℕ → Polynomial ℂ,
      (∀ k i, (P k).coeff i ∈
        IntermediateField.adjoin ℚ {Complex.exp (2 * (Real.pi : ℂ) * Complex.I / N)}) ∧
      ∀ v : Fin 2 → ZMod N, v ≠ 0 → ∀ τ : ℍ,
        fricke v τ ^ (N ^ 2 - 1) + ∑ k ∈ Finset.range (N ^ 2 - 1),
          (P k).eval (jf τ) * fricke v τ ^ k = 0) := _root_.P2MW.S_WLight_frickeFunction_orbit_package.solution N L hL W hW fricke hfricke jf hjf

end publicSection
