/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.deg_placeInfty
(7dae8346-786a-5cde-b729-973c2fb2060b) by Claude (2026-09-05).

Proof based on Prove2Me submission 760195a1-b9a3-5915-8ee2-38787c67d16c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceInfty

import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceClassification
import Theorems.FLT.Thm_P2M_Dup_AlgebraicCurve_RationalFunctionField_placeInfty_ne_ofHeightOneSpectrum
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_deg_eq_one_of_forall_ne_ofHeightOneSpectrum
import Definitions.FLT.Def_P2M_Util

/-!
# The place at infinity of K(t) has degree one

Theorem statement: `AlgebraicCurve.RationalFunctionField.deg_placeInfty`
(`7dae8346-786a-5cde-b729-973c2fb2060b`), by Claude, 2026-09-05.

Proof: submission `760195a1-b9a3-5915-8ee2-38787c67d16c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field. Consider the rational function field $\mathrm{RatFunc}\,K$ and the place
$\mathtt{placeInfty}\ K$ of $\mathrm{RatFunc}\,K$ over $K$, that is, the datum consisting of the
valuation subring attached to the infinity valuation `RatFunc.inftyValuation K` of
$\mathrm{RatFunc}\,K$, together with the verifications required by the structure `Place`: that every
element $\mathrm{algebraMap}\,K\,(\mathrm{RatFunc}\,K)(a)$, $a \in K$, lies in this subring (the
infinity valuation is trivial on the constants), that the subring is not all of
$\mathrm{RatFunc}\,K$, and that it is a principal ideal ring (being a discrete valuation ring). The
degree of a place $v$ is by definition $\mathrm{Module.finrank}$ over $K$ of its residue field, the
residue field of the local ring $v.\mathtt{toValuationSubring}$. The assertion is that
$(\mathtt{placeInfty}\ K).\deg = 1$, i.e. the residue field of the infinity valuation ring of $K(t)$
is one-dimensional as a $K$-vector space, so that the place at infinity is a rational place. No
hypothesis on $K$ beyond being a field is imposed.

This is the classical fact that, among the places of the rational function field $K(t)$ — the monic
irreducible polynomials together with $\infty$ — the place at infinity is rational, its residue
field being $K$ itself. It identifies the named place at infinity as a degree-one point of
$\mathbb{P}^1$ and is used throughout the function-field foundations, for instance in the
Riemann–Roch-style computations for $K(t)$ such as
[`AlgebraicCurve.RationalFunctionField.ell_sub_ell_eq_genus_zero`](thm.html#AlgebraicCurve.RationalFunctionField.ell_sub_ell_eq_genus_zero)
and the finite-dimensionality of the space attached to the zero divisor.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_deg_placeInfty.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_deg_placeInfty
p2m_attr_erase "instance" "AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

open IsDedekindDomain AlgebraicCurve AlgebraicCurve.RationalFunctionField

theorem solution (K : Type*) [Field K] [DecidableEq (RatFunc K)] : (placeInfty K).deg = 1 :=
  AlgebraicCurve.RationalFunctionField.deg_eq_one_of_forall_ne_ofHeightOneSpectrum (placeInfty K)
    (AlgebraicCurve.RationalFunctionField.placeInfty_ne_ofHeightOneSpectrum K)

end S_AlgebraicCurve_RationalFunctionField_deg_placeInfty
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_deg_placeInfty (solution)

end privateSection

public section publicSection


open AlgebraicCurve AlgebraicCurve.RationalFunctionField
theorem AlgebraicCurve.RationalFunctionField.deg_placeInfty (K : Type*) [Field K] [DecidableEq (RatFunc K)] : (placeInfty K).deg = 1 := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_deg_placeInfty.solution K

end publicSection
