/-
Based on Prove2Me node ModularForm.qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne
(fb6ad152-fbff-5727-97a8-4508cee47650) by Claude (2026-09-05).

Proof based on Prove2Me submission 32fbc617-cc1d-5356-a450-bbd4c87d5116
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularForm_HeckeOperator
public import Definitions.FLT.Def_ModularCurve_X0
public import Mathlib.NumberTheory.ModularForms.QExpansion

import Theorems.FLT.Thm_ModularForm_exists_degeneracy_Gamma0
import Theorems.FLT.Thm_ModularCurve_laurent_qParam_coeff_unique
import Definitions.FLT.Def_P2M_Util

/-!
# q-expansion of τ↦ F(Nτ) for level-one F

Theorem statement: `ModularForm.qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne`
(`fb6ad152-fbff-5727-97a8-4508cee47650`), by Claude, 2026-09-05.

Proof: submission `32fbc617-cc1d-5356-a450-bbd4c87d5116`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number that is nonzero, let $k$ be an integer, and let $F$ be a modular form of
weight $k$ for the subgroup $\mathcal{SL} \le \mathrm{GL}(2,\mathbb{R})$ (the image of
$\mathrm{SL}(2,\mathbb{Z})$), acting on the upper half-plane $\mathbb{H}$. Here
[`ModularForm.heckeDiagMatrix N`](def/ModularForm_HeckeOperator.html#L21) is, for $N \neq 0$, the
element of $\mathrm{GL}(2,\mathbb{R})$ given by the upper triangular matrix $\begin{pmatrix} N & 0
\\ 0 & 1\end{pmatrix}$, whose action on $\mathbb{H}$ is $\tau \mapsto N\tau$; and
[`ModularCurve.qExpand ℂ N`](def/ModularCurve_X0.html#L25) is the ring endomorphism of the Laurent
series field $\mathbb{C}(\!(q)\!)$ obtained by embedding the exponent group $\mathbb{Z}$ along
multiplication by $N$, i.e. the substitution $q \mapsto q^{N}$, which sends the coefficient of index
$m$ to the coefficient of index $Nm$ and sets all coefficients of index not divisible by $N$ to
zero. The assertion is that the width-one $q$-expansion of the dilated function $\tau \mapsto
F(N\tau)$, viewed as a power series and then as a Laurent series, equals the image under this
substitution of the width-one $q$-expansion of $F$; in the classical notation, the expansion of
$F(N\tau)$ is $\tilde F(q^{N})$.

This identifies the $q$-expansion of the degeneracy (dilation) image of a level-one form, the basic
compatibility between the map $\tau \mapsto N\tau$ on $\mathbb{H}$ and the substitution $q \mapsto
q^{N}$ on Laurent expansions. It is used in the analytic study of modular curves and their cusps,
for instance in the computations with modular polynomial data and Tate-type expansions that invoke
it downstream.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne

open UpperHalfPlane
open scoped MatrixGroups

namespace SolDILAux

private theorem gamma0_one_eq_top : CongruenceSubgroup.Gamma0 1 = ⊤ := by
  ext A
  simp [CongruenceSubgroup.Gamma0_mem, eq_iff_true_of_subsingleton]

private theorem gamma0_one_coe :
    ((CongruenceSubgroup.Gamma0 1 : Subgroup SL(2, ℤ)) : Subgroup (GL (Fin 2) ℝ)) = 𝒮ℒ := by
  simp [gamma0_one_eq_top, MonoidHom.range_eq_map]

private theorem one_mem_sp (M : ℕ) : (1 : ℝ) ∈
    ((CongruenceSubgroup.Gamma0 M : Subgroup SL(2, ℤ)) :
      Subgroup (GL (Fin 2) ℝ)).strictPeriods := by
  rw [CongruenceSubgroup.strictPeriods_Gamma0]
  exact AddSubgroup.mem_zmultiples 1

private theorem hasSum_int {Γ : Subgroup (GL (Fin 2) ℝ)} {k : ℤ} {F : Type*} [FunLike F ℍ ℂ]
    [ModularFormClass F Γ k] (f : F) (hΓ : (1 : ℝ) ∈ Γ.strictPeriods) (τ : ℍ) :
    HasSum (fun m : ℤ =>
      ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ).coeff m *
        Function.Periodic.qParam 1 (τ : ℂ) ^ m) (f τ) := by
  have : Fact (IsCusp OnePoint.infty Γ) := ⟨Γ.isCusp_of_mem_strictPeriods one_pos hΓ⟩
  have h0 := UpperHalfPlane.hasSum_qExpansion (f := (f : ℍ → ℂ)) one_pos
    (SlashInvariantFormClass.periodic_comp_ofComplex f hΓ) (ModularFormClass.holo f)
    (ModularFormClass.bdd_at_infty f) τ
  refine (Function.Injective.hasSum_iff Nat.cast_injective ?_).mp ?_
  · intro m hm
    rcases m with n | n
    · exact absurd ⟨n, rfl⟩ hm
    · rw [ModularCurve.ofPowerSeries_coeff_of_neg _ (Int.negSucc_lt_zero n), zero_mul]
  · have hcomp : ((fun m : ℤ =>
        ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ).coeff m *
          Function.Periodic.qParam 1 (τ : ℂ) ^ m) ∘ (Nat.cast : ℕ → ℤ)) =
        fun n : ℕ => (qExpansion 1 (f : ℍ → ℂ)).coeff n •
          Function.Periodic.qParam 1 (τ : ℂ) ^ n := by
      funext n
      simp only [Function.comp_apply, smul_eq_mul, zpow_natCast,
        LaurentSeries.coeff_coe_powerSeries]
    rw [hcomp]
    exact h0

private theorem hasSum_qExpand (N : ℕ) [NeZero N] {A : LaurentSeries ℂ} {S : ℂ} {τ : ℍ}
    (h : HasSum (fun m : ℤ => A.coeff m *
      Function.Periodic.qParam 1 (((ModularForm.heckeDiagMatrix N • τ : ℍ)) : ℂ) ^ m) S) :
    HasSum (fun m : ℤ => (ModularCurve.qExpand ℂ N A).coeff m *
      Function.Periodic.qParam 1 (τ : ℂ) ^ m) S := by
  have hq : Function.Periodic.qParam 1 (((ModularForm.heckeDiagMatrix N • τ : ℍ)) : ℂ) =
      Function.Periodic.qParam 1 (τ : ℂ) ^ (N : ℕ) := by
    rw [ModularForm.coe_heckeDiagMatrix_smul (NeZero.ne N) τ]
    unfold Function.Periodic.qParam
    rw [← Complex.exp_nat_mul]
    congr 1
    ring
  rw [hq] at h
  have hinj : Function.Injective (fun m : ℤ => (N : ℤ) * m) :=
    mul_right_injective₀ (by exact_mod_cast NeZero.ne N)
  refine (Function.Injective.hasSum_iff hinj ?_).mp ?_
  · intro m hm
    have hnd : ¬ ((N : ℕ) : ℤ) ∣ m := by
      rintro ⟨c, rfl⟩
      exact hm ⟨c, rfl⟩
    rw [ModularCurve.qExpand_coeff_of_not_dvd N A hnd, zero_mul]
  · have hcomp : ((fun m : ℤ => (ModularCurve.qExpand ℂ N A).coeff m *
        Function.Periodic.qParam 1 (τ : ℂ) ^ m) ∘ (fun m : ℤ => (N : ℤ) * m)) =
        fun m : ℤ => A.coeff m *
          (Function.Periodic.qParam 1 (τ : ℂ) ^ (N : ℕ)) ^ m := by
      funext m
      simp only [Function.comp_apply]
      rw [ModularCurve.qExpand_coeff_mul, zpow_mul, zpow_natCast]
    rw [hcomp]
    exact h

private theorem qExpansion_coe_dilate {N : ℕ} [NeZero N] {k : ℤ}
    (f : ModularForm (CongruenceSubgroup.Gamma0 1) k)
    (g : ModularForm (CongruenceSubgroup.Gamma0 N) k)
    (hg : ⇑g = fun τ => f (ModularForm.heckeDiagMatrix N • τ)) :
    ((qExpansion 1 (g : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
      ModularCurve.qExpand ℂ N
        ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) := by
  refine ModularCurve.laurent_qParam_coeff_unique 1 one_pos (g : ℍ → ℂ) _ _
    (hasSum_int g (one_mem_sp N)) ?_
  intro τ
  have h := hasSum_qExpand N (hasSum_int f (one_mem_sp 1) (ModularForm.heckeDiagMatrix N • τ))
  rw [show f (ModularForm.heckeDiagMatrix N • τ) = g τ from by rw [hg]] at h
  exact h

end SolDILAux

theorem solution (N : ℕ) [NeZero N] {k : ℤ} (F : ModularForm 𝒮ℒ k) :
    ((qExpansion 1 (fun τ : ℍ => (F : ℍ → ℂ) (ModularForm.heckeDiagMatrix N • τ)) :
      PowerSeries ℂ) : LaurentSeries ℂ) =
    ModularCurve.qExpand ℂ N ((qExpansion 1 (F : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) := by
  obtain ⟨G, hG⟩ := ModularForm.exists_degeneracy_Gamma0 (show N * 1 ∣ N by simp)
    (ModularForm.mcast rfl F SolDILAux.gamma0_one_coe)
  have h1 : (fun τ : ℍ => (F : ℍ → ℂ) (ModularForm.heckeDiagMatrix N • τ)) = ⇑G := by
    rw [hG]
    simp only [ModularForm.coe_mcast]
  rw [h1]
  exact SolDILAux.qExpansion_coe_dilate (ModularForm.mcast rfl F SolDILAux.gamma0_one_coe) G hG

end S_ModularForm_qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne
end P2MW
export P2MW.S_ModularForm_qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open UpperHalfPlane
open scoped MatrixGroups
theorem ModularForm.qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne (N : ℕ) [NeZero N] {k : ℤ} (F : ModularForm 𝒮ℒ k) : ((qExpansion 1 (fun τ : ℍ => (F : ℍ → ℂ) (ModularForm.heckeDiagMatrix N • τ)) : PowerSeries ℂ) : LaurentSeries ℂ) = ModularCurve.qExpand ℂ N ((qExpansion 1 (F : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) := _root_.P2MW.S_ModularForm_qExpansion_heckeDiagMatrix_smul_eq_qExpand_of_levelOne.solution N F

end publicSection
