/-
Based on Prove2Me node AlgebraicCurve.normFormulaAlong
(0a836ca9-bde8-5a32-b34d-1f0bf43c2174) by Claude (2026-09-05).

Proof based on Prove2Me submission 9c76cc3b-ad4f-5f4a-9873-dbbcc0897fb8
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_Correspondence

import Theorems.FLT.Thm_AlgebraicCurve_Divisor_pushforwardNormFormula
import Definitions.FLT.Def_P2M_Util

/-!
# Pushforward norm formula along a finite separable K-morphism

Theorem statement: `AlgebraicCurve.normFormulaAlong` (`0a836ca9-bde8-5a32-b34d-1f0bf43c2174`), by
Claude, 2026-09-05.

Proof: submission `9c76cc3b-ad4f-5f4a-9873-dbbcc0897fb8`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$, $F$, $F'$ be fields, with $F$ and $F'$ algebras over $K$ and $F$ of characteristic zero,
and let $\varphi : F \to F'$ be a $K$-algebra homomorphism. Assume $F'$ has principal divisors over
$K$, i.e. every nonzero $f \in F'$ admits a divisor $D$ (a finitely supported $\mathbb{Z}$-valued
function on the places of $F'$ over $K$, a place being a valuation subring containing the image of
$K$, distinct from the whole field, and a principal ideal ring) with $D(w) = \operatorname{ord}_w f$
at every place $w$ and $\deg D = 0$. Assume further that, when $F'$ is regarded as an $F$-algebra
through $\varphi$, it is a finite $F$-module (`FiniteAlong`) and a separable $F$-algebra
(`SeparableAlong`). The conclusion is `NormFormulaAlong K φ hfin`, which unfolds to the assertion
that, with respect to this $F$-algebra structure on $F'$, for every nonzero $f \in F'$, every
divisor $D$ on $F'$ satisfying $D(w) = \operatorname{ord}_w f$ at all places $w$ of $F'$, and every
place $v$ of $F$, the pushforward of $D$ to the divisors of $F$ takes at $v$ the value
$\operatorname{ord}_v\bigl(N_{F'/F}(f)\bigr)$.

This is the compatibility of the divisor pushforward with the field norm,
$\varphi_*(\operatorname{div} f) = \operatorname{div}(N_{F'/F} f)$, in the form required for a
morphism of curves presented as an explicit $K$-algebra map rather than by an ambient tower of
algebras. It supplies the norm-formula hypothesis used in the construction of correspondences and
their action on Picard groups and Tate modules.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_normFormulaAlong.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_normFormulaAlong
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.qExpand_coeff_mul ModularCurve.qExpandₐ_apply ModularCurve.jqN_one ModularCurve.qExpand_single ModularCurve.dedekindPsi_one ModularCurve.ModularPolynomialData.mk.sizeOf_spec ModularCurve.evalAtJ_X ModularCurve.ModularPolynomialData.mk.injEq ModularCurve.constantCoeff_jNum ModularCurve.constantCoeff_eisenstein4 ModularCurve.qExpand_C ModularCurve.coeff_jq_neg_one ModularCurve.constantCoeff_jNumQ ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X"
p2m_attr_erase "simp" "ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply"

open AlgebraicCurve AlgebraicCurve.SemilinearAut
open scoped Pointwise

noncomputable section

theorem solution {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [CharZero F] (φ : F →ₐ[K] F') [HasPrincipalDivisors K F'] (hfin : FiniteAlong K φ) (hsep : SeparableAlong K φ) : NormFormulaAlong K φ hfin := by
  let := algebraAlong φ
  have := isScalarTower_along φ
  have : Module.Finite F F' := hfin
  have : Algebra.IsSeparable F F' := hsep
  exact Divisor.pushforwardNormFormula

end

end S_AlgebraicCurve_normFormulaAlong
end P2MW
export P2MW.S_AlgebraicCurve_normFormulaAlong (solution)

end privateSection

public section publicSection


open AlgebraicCurve AlgebraicCurve.SemilinearAut
theorem AlgebraicCurve.normFormulaAlong {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [CharZero F] (φ : F →ₐ[K] F') [HasPrincipalDivisors K F'] (hfin : FiniteAlong K φ) (hsep : SeparableAlong K φ) : NormFormulaAlong K φ hfin := _root_.P2MW.S_AlgebraicCurve_normFormulaAlong.solution φ hfin hsep

end publicSection
