/-
Based on Prove2Me node ValuationSubring.exists_liesOverPrime_algebraicClosure_rat
(795b03fc-3cbd-5c73-b6fd-dece3e952452) by Claude (2026-09-05).

Proof based on Prove2Me submission b4096d24-db4c-5f89-a827-0e0e0df72678
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_FLTPrelim_Ramification

import Mathlib.RingTheory.Valuation.LocalSubring
import Definitions.FLT.Def_P2M_Util

/-!
# Existence of a place of ℚ̄ above each prime p

Theorem statement: `ValuationSubring.exists_liesOverPrime_algebraicClosure_rat`
(`795b03fc-3cbd-5c73-b6fd-dece3e952452`), by Claude, 2026-09-05.

Proof: submission `b4096d24-db4c-5f89-a827-0e0e0df72678`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $p$ be a prime number (an element of `Nat.Primes`, so a natural number together with the witness
that it is prime). The assertion is that there exists a valuation subring $A$ of the field
$\mathrm{AlgebraicClosure}\ \mathbb{Q}$, i.e. a subring $A \subseteq \overline{\mathbb{Q}}$ such
that for every $x \in \overline{\mathbb{Q}}$ either $x \in A$ or $x^{-1} \in A$, satisfying the
project's predicate [`ValuationSubring.LiesOverPrime`](def/FLTPrelim_Ramification.html#L16) for the
natural number underlying $p$. By definition this predicate says that the image of $p$ under the
canonical map $\mathbb{N} \to \overline{\mathbb{Q}}$ lies in the set of nonunits of $A$: that is,
$p$ belongs to $A$ and is not invertible in $A$, equivalently $p$ lies in the maximal ideal of the
valuation ring $A$. No hypotheses beyond the primality of $p$ are imposed, and nothing is asserted
about the value group of $A$, its residue field, or uniqueness of $A$.

This is the existence of a place of $\overline{\mathbb{Q}}$ extending the $p$-adic place of
$\mathbb{Q}$, in the weak form needed downstream: a valuation subring of $\overline{\mathbb{Q}}$ in
whose maximal ideal $p$ lies. It serves as the source of $p$-adic places in the
ramification-theoretic parts of the development, and is invoked widely (for instance in the
conductor and Čerednik–Drinfel'd strands).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ValuationSubring_exists_liesOverPrime_algebraicClosure_rat.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ValuationSubring_exists_liesOverPrime_algebraicClosure_rat

theorem solution (p : Nat.Primes) :
    ∃ A : ValuationSubring (AlgebraicClosure ℚ), A.LiesOverPrime (p : ℕ) := by
  have hq : (p : ℕ).Prime := p.2
  set R : Subring (AlgebraicClosure ℚ) := ⊥ with hR
  have hqR : ¬IsUnit (((p : ℕ) : ℕ) : R) := by
    rw [isUnit_iff_exists_inv]
    rintro ⟨y, hy⟩
    have hy' : ((p : ℕ) : AlgebraicClosure ℚ) * (y : AlgebraicClosure ℚ) = 1 := by
      have := congrArg (R.subtype) hy
      simpa using this
    obtain ⟨n, hn⟩ := Subring.mem_bot.mp y.2
    rw [← hn] at hy'
    have hqn : ((p : ℕ) : ℤ) * n = 1 := by
      have : ((((p : ℕ) : ℤ) * n : ℤ) : AlgebraicClosure ℚ) = ((1 : ℤ) : AlgebraicClosure ℚ) := by
        push_cast
        linear_combination hy'
      exact_mod_cast this
    have h1 : ((p : ℕ) : ℤ) ≤ 1 := Int.le_of_dvd one_pos ⟨n, hqn.symm⟩
    have h2 : 2 ≤ (p : ℕ) := hq.two_le
    omega
  obtain ⟨B, -, hB⟩ :=
    Ideal.image_subset_nonunits_valuationSubring (Ideal.span {(((p : ℕ) : ℕ) : R)})
      (fun h => hqR (Ideal.span_singleton_eq_top.mp h))
  refine ⟨B, hB ⟨(((p : ℕ) : ℕ) : R), Ideal.subset_span rfl, ?_⟩⟩
  simp

end S_ValuationSubring_exists_liesOverPrime_algebraicClosure_rat
end P2MW
export P2MW.S_ValuationSubring_exists_liesOverPrime_algebraicClosure_rat (solution)

end privateSection

public section publicSection

theorem ValuationSubring.exists_liesOverPrime_algebraicClosure_rat (p : Nat.Primes) :
    ∃ A : ValuationSubring (AlgebraicClosure ℚ), A.LiesOverPrime (p : ℕ) := _root_.P2MW.S_ValuationSubring_exists_liesOverPrime_algebraicClosure_rat.solution p

end publicSection
