/-
Based on Prove2Me node ModularCurve.tendsto_atImInfty_of_hasSum_qParam
(99e3990b-a664-51c3-aced-4302ef14c172) by Claude (2026-09-05).

Proof based on Prove2Me submission f78ca6b2-75b2-5d34-b8df-4d0ef380ad0f
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Analysis.Complex.UpperHalfPlane.Exp
public import Mathlib.Analysis.Complex.UpperHalfPlane.Manifold
public import Mathlib.Analysis.Complex.UpperHalfPlane.FunctionsBoundedAtInfty

import Mathlib.NumberTheory.ModularForms.QExpansion
import Definitions.FLT.Def_P2M_Util

/-!
# Convergent q-expansion tends to its constant term at i∞

Theorem statement: `ModularCurve.tendsto_atImInfty_of_hasSum_qParam`
(`99e3990b-a664-51c3-aced-4302ef14c172`), by Claude, 2026-09-05.

Proof: submission `f78ca6b2-75b2-5d34-b8df-4d0ef380ad0f`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $h$ be a real number with $0 < h$, let $F \colon \mathfrak{H} \to \mathbb{C}$ be an arbitrary
function on the upper half-plane, and let $(c_m)_{m \in \mathbb{N}}$ be a sequence of complex
numbers. Assume that for every $\tau \in \mathfrak{H}$ the series $\sum_{m \ge 0} c_m\, q^m$, where
$q = \mathrm{qParam}\,h\,\tau = e^{2\pi i \tau / h}$ is Mathlib's $q$-parameter of period $h$, is
summable with sum exactly $F(\tau)$ (the hypothesis is `HasSum`, i.e. unconditional summability of
the family indexed by $m \in \mathbb{N}$ together with the identification of its sum with $F(\tau)$;
no hypothesis of local uniformity or of holomorphy of $F$ is imposed). The conclusion is that $F$
converges to $c_0$ along the filter `UpperHalfPlane.atImInfty`, the filter generated by the sets on
which $\operatorname{Im} \tau$ exceeds a given bound: that is, $F(\tau) \to c_0$ as
$\operatorname{Im} \tau \to \infty$.

This is the standard statement that a function on the upper half-plane given by a convergent
$q$-expansion of period $h$ is holomorphic-at-the-cusp-style bounded at $i\infty$, with limiting
value the constant term $c_0$; in particular such an $F$ is bounded near $i\infty$. It is used in
the treatment of Siegel units and in the estimates bounding slashed modular functions in terms of
$q$-parameters.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_tendsto_atImInfty_of_hasSum_qParam.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_tendsto_atImInfty_of_hasSum_qParam

noncomputable section

open UpperHalfPlane Complex Filter Topology Function
open scoped MatrixGroups ModularForm

local notation "𝕢" => Function.Periodic.qParam

namespace ModularCurve

namespace Realized

variable {h : ℝ} {F : ℍ → ℂ} {c : ℕ → ℂ}

lemma norm_qParam_lt_one_of_pos (hh : 0 < h) (τ : ℍ) : ‖𝕢 h (τ : ℂ)‖ < 1 := by
  rw [Periodic.norm_qParam, Real.exp_lt_one_iff, neg_mul, coe_im, neg_mul, neg_div, neg_lt_zero]
  exact div_pos (by positivity [τ.im_pos]) hh

lemma hasSum_cuspFunction_punctured (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) {q : ℂ} (hq : ‖q‖ < 1)
    (hq1 : q ≠ 0) : HasSum (fun m : ℕ => c m * q ^ m) (cuspFunction h F q) := by
  have h1 := Periodic.im_invQParam_pos_of_norm_lt_one hh hq hq1
  let τ : ℍ := ⟨Periodic.invQParam h q, h1⟩
  have h2 := Periodic.cuspFunction_eq_of_nonzero h (F ∘ ofComplex) hq1
  have h3 : cuspFunction h F q = F τ := by
    simp [UpperHalfPlane.ofComplex_apply_of_im_pos h1] at h2
    exact h2
  have h4 : 𝕢 h (τ : ℂ) = q := Periodic.qParam_right_inv hh.ne' hq1
  rw [h3, ← h4]
  exact hF τ

lemma hasFPowerSeriesOnBall_update (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) :
    HasFPowerSeriesOnBall (update (cuspFunction h F) 0 (c 0)) (.ofScalars ℂ c) 0 1 := by
  constructor
  · refine le_of_forall_lt_imp_le_of_dense fun r hr ↦ ?_
    rcases eq_or_ne r 0 with rfl | hr'
    · simp
    · lift r to NNReal using hr.ne_top
      let : FiniteDimensional ℝ ℂ := basisOneI.finiteDimensional_of_finite
      apply FormalMultilinearSeries.le_radius_of_summable
      simpa [norm_mul, mul_comm] using
        (hasSum_cuspFunction_punctured hh hF (q := r) (by simpa using hr)
          (mod_cast hr')).summable.norm
  · simp
  · intro y hy
    rw [zero_add]
    rw [← ENNReal.coe_one, Metric.eball_coe, NNReal.coe_one, mem_ball_zero_iff] at hy
    rcases eq_or_ne y 0 with rfl | hy'
    · simpa +contextual [zero_pow_eq] using hasSum_ite_eq 0 (c 0)
    · simpa [update_of_ne hy', mul_comm] using hasSum_cuspFunction_punctured hh hF hy hy'

def discFun (h : ℝ) (F : ℍ → ℂ) (c : ℕ → ℂ) : ℂ → ℂ := update (cuspFunction h F) 0 (c 0)

lemma hasSum_discFun (hh : 0 < h) (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ))
    {q : ℂ} (hq : ‖q‖ < 1) : HasSum (fun m : ℕ => c m * q ^ m) (discFun h F c q) := by
  have hy : q ∈ Metric.eball (0 : ℂ) 1 := by
    rw [← ENNReal.coe_one, Metric.eball_coe]; simpa using hq
  have h := (hasFPowerSeriesOnBall_update hh hF).hasSum hy
  rw [zero_add] at h
  simpa [discFun, mul_comm] using h

lemma apply_eq_discFun (hh : 0 < h) (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ))
    (τ : ℍ) : F τ = discFun h F c (𝕢 h (τ : ℂ)) :=
  (hF τ).unique (hasSum_discFun hh hF (norm_qParam_lt_one_of_pos hh τ))

lemma differentiableOn_discFun (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) :
    DifferentiableOn ℂ (discFun h F c) (Metric.ball 0 1) := by
  have h1 := (hasFPowerSeriesOnBall_update hh hF).differentiableOn
  rwa [← ENNReal.coe_one, Metric.eball_coe, NNReal.coe_one] at h1

lemma continuousAt_discFun (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) {q : ℂ} (hq : ‖q‖ < 1) :
    ContinuousAt (discFun h F c) q :=
  ((differentiableOn_discFun hh hF).differentiableAt
    (Metric.isOpen_ball.mem_nhds (by simpa using hq))).continuousAt

lemma discFun_zero : discFun h F c 0 = c 0 := by simp [discFun]

theorem mdifferentiable (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) :
    MDifferentiable (modelWithCornersSelf ℂ ℂ) (modelWithCornersSelf ℂ ℂ) F := by
  rw [UpperHalfPlane.mdifferentiable_iff]
  have h1 : DifferentiableOn ℂ (fun z : ℂ => discFun h F c (𝕢 h z)) {z : ℂ | 0 < z.im} := by
    intro z hz
    have hzq : ‖𝕢 h z‖ < 1 := by
      have := norm_qParam_lt_one_of_pos hh ⟨z, hz⟩
      simpa using this
    exact (((differentiableOn_discFun hh hF).differentiableAt
      (Metric.isOpen_ball.mem_nhds (by simpa using hzq))).comp z
      ((Periodic.differentiable_qParam (h := h)) z)).differentiableWithinAt
  refine h1.congr fun z hz => ?_
  simp only [Function.comp_apply, apply_eq_discFun hh hF, ofComplex_apply_of_im_pos hz]

theorem tendsto_atImInfty (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) :
    Tendsto F atImInfty (𝓝 (c 0)) := by
  have h1 : Tendsto (fun τ : ℍ => discFun h F c (𝕢 h (τ : ℂ))) atImInfty (𝓝 (discFun h F c 0)) :=
    (continuousAt_discFun hh hF (q := 0) (by simp)).tendsto.comp (qParam_tendsto_atImInfty hh)
  rw [discFun_zero] at h1
  exact h1.congr fun τ => (apply_eq_discFun hh hF τ).symm

theorem isBoundedAtImInfty (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) :
    IsBoundedAtImInfty F :=
  (tendsto_atImInfty hh hF).isBigO_one ℝ

theorem periodic (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ)) :
    Periodic (F ∘ ofComplex) h := by
  intro w
  by_cases hw : 0 < w.im
  · have hw' : 0 < (w + h).im := by simpa using hw
    simp only [Function.comp_apply, apply_eq_discFun hh hF, ofComplex_apply_of_im_pos hw,
      ofComplex_apply_of_im_pos hw']
    congr 1
    simp only [Periodic.qParam]
    rw [show 2 * ↑Real.pi * Complex.I * (w + ↑h) / ↑h = 2 * ↑Real.pi * Complex.I * w / ↑h + 2 * ↑Real.pi * Complex.I by
      field_simp [(Complex.ofReal_ne_zero.mpr hh.ne')]]
    rw [Complex.exp_add, Complex.exp_two_pi_mul_I, mul_one]
  · push Not at hw
    have hw' : (w + h).im ≤ 0 := by simpa using hw
    simp only [Function.comp_apply, ofComplex_apply_eq_of_im_nonpos hw' hw]

theorem coeff_unique {d : ℕ → ℂ} (hh : 0 < h)
    (hF : ∀ τ : ℍ, HasSum (fun m : ℕ => c m * 𝕢 h (τ : ℂ) ^ m) (F τ))
    (hF' : ∀ τ : ℍ, HasSum (fun m : ℕ => d m * 𝕢 h (τ : ℂ) ^ m) (F τ)) : c = d := by
  have hc := hasFPowerSeriesOnBall_update hh hF
  have hd := hasFPowerSeriesOnBall_update hh hF'
  have hlim : ∀ {e : ℕ → ℂ}, HasFPowerSeriesOnBall (update (cuspFunction h F) 0 (e 0)) (.ofScalars ℂ e) 0 1 →
      Tendsto (cuspFunction h F) (𝓝[≠] 0) (𝓝 (e 0)) := by
    intro e he
    have h1 : Tendsto (update (cuspFunction h F) 0 (e 0)) (𝓝[≠] 0) (𝓝 (e 0)) := by
      have := he.hasFPowerSeriesAt.continuousAt.tendsto
      rw [update_self] at this
      exact this.mono_left nhdsWithin_le_nhds
    refine h1.congr' ?_
    filter_upwards [self_mem_nhdsWithin] with z hz using update_of_ne hz ..
  have h0 : c 0 = d 0 := tendsto_nhds_unique (hlim hc) (hlim hd)
  have hd' : HasFPowerSeriesOnBall (update (cuspFunction h F) 0 (c 0)) (.ofScalars ℂ d) 0 1 := h0 ▸ hd
  have heq := hc.hasFPowerSeriesAt.eq_formalMultilinearSeries hd'.hasFPowerSeriesAt
  funext m
  simpa using congr_arg (FormalMultilinearSeries.coeff · m) heq

end Realized

end ModularCurve

theorem solution (h : ℝ) (hh : 0 < h) (F : UpperHalfPlane → ℂ) (c : ℕ → ℂ) (hc : ∀ τ : UpperHalfPlane, HasSum (fun m : ℕ => c m * Function.Periodic.qParam h (τ : ℂ) ^ m) (F τ)) : Filter.Tendsto F UpperHalfPlane.atImInfty (nhds (c 0)) :=
  ModularCurve.Realized.tendsto_atImInfty hh hc

end

end S_ModularCurve_tendsto_atImInfty_of_hasSum_qParam
end P2MW
export P2MW.S_ModularCurve_tendsto_atImInfty_of_hasSum_qParam (solution)

end privateSection

public section publicSection

theorem ModularCurve.tendsto_atImInfty_of_hasSum_qParam (h : ℝ) (hh : 0 < h) (F : UpperHalfPlane → ℂ) (c : ℕ → ℂ) (hc : ∀ τ : UpperHalfPlane, HasSum (fun m : ℕ => c m * Function.Periodic.qParam h (τ : ℂ) ^ m) (F τ)) : Filter.Tendsto F UpperHalfPlane.atImInfty (nhds (c 0)) := _root_.P2MW.S_ModularCurve_tendsto_atImInfty_of_hasSum_qParam.solution h hh F c hc

end publicSection
