/-
Based on Prove2Me node Matrix.SpecialLinearGroup.exists_eq_mul_diagonal_mul_of_gcd_eq_one
(c8bce8b0-edd5-5602-b497-0ee5560f503b) by Claude (2026-09-05).

Proof based on Prove2Me submission 6746b6bf-ecd5-5ff9-bc35-1d12e96aca37
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup

import Mathlib.Algebra.BigOperators.Associated
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.LinearCombination.Lemmas
import Definitions.FLT.Def_P2M_Util

/-!
# Primitive upper-triangular matrices of determinant N in one double coset

Theorem statement: `Matrix.SpecialLinearGroup.exists_eq_mul_diagonal_mul_of_gcd_eq_one`
(`c8bce8b0-edd5-5602-b497-0ee5560f503b`), by Claude, 2026-09-05.

Proof: submission `6746b6bf-ecd5-5ff9-bc35-1d12e96aca37`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N,a,b,d$ be natural numbers such that $N \neq 0$, $a d = N$, and $\gcd(a,\gcd(b,d)) = 1$. Then
there exist $\gamma_1,\gamma_2 \in \mathrm{SL}_2(\mathbb{Z})$, i.e. elements of
`Matrix.SpecialLinearGroup (Fin 2) ℤ`, such that, after casting $a,b,d,N$ into $\mathbb{Z}$ and
coercing $\gamma_1,\gamma_2$ to their underlying $2 \times 2$ integer matrices, the equality of
matrices in `Matrix (Fin 2) (Fin 2) ℤ`
$$\begin{pmatrix} a & b \\ 0 & d\end{pmatrix} \;=\; \gamma_1 \begin{pmatrix} N & 0 \\ 0 &
1\end{pmatrix} \gamma_2$$
holds. Thus a primitive upper-triangular integer matrix with non-negative entries and determinant $N
> 0$ lies in the double coset $\mathrm{SL}_2(\mathbb{Z}) \, \mathrm{diag}(N,1) \,
\mathrm{SL}_2(\mathbb{Z})$. Note that the usual normalisation $0 \le b < d$ of coset representatives
is not assumed, only the coprimality condition; the entries are natural numbers rather than
arbitrary integers; and the orientation of the factorisation is with $\mathrm{diag}(N,1)$ (not
$\mathrm{diag}(1,N)$) in the middle.

This is the $\mathrm{SL}_2$ refinement of the elementary-divisor (Smith) normal form in rank two:
the elementary divisors of a primitive integer matrix of determinant $N$ are $1$ and $N$, and the
reduction can be carried out on both sides inside $\mathrm{SL}_2(\mathbb{Z})$ rather than
$\mathrm{GL}_2(\mathbb{Z})$. It is used in the study of the modular equation, where a level-one
modular function is evaluated along the cosets $\mathrm{SL}_2(\mathbb{Z})\binom{a\;b}{0\;d}$ with
$ad = N$; it is cited by
[`ModularCurve.ModularPolynomialData.eval_E4_cube_div_discriminant_coset_eq_zero`](thm.html#ModularCurve.ModularPolynomialData.eval_E4_cube_div_discriminant_coset_eq_zero).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_Matrix_SpecialLinearGroup_exists_eq_mul_diagonal_mul_of_gcd_eq_one.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_Matrix_SpecialLinearGroup_exists_eq_mul_diagonal_mul_of_gcd_eq_one

namespace Matrix
p2m_export "Matrix" "ext diag SpecialLinearGroup det_fin_two_of of mul_fin_two"
namespace SpecialLinearGroup
p2m_export "Matrix.SpecialLinearGroup" "ext"
namespace PrimitiveSmith
p2m_open "Matrix.SpecialLinearGroup Matrix"

theorem exists_coprime_mul_add {a b d : ℕ} (hd : d ≠ 0) (hgcd : Nat.gcd a (Nat.gcd b d) = 1) :
    ∃ p : ℕ, Nat.Coprime (a * p + b) d := by
  classical
  refine ⟨∏ q ∈ d.primeFactors.filter (fun q => ¬ q ∣ b), q, ?_⟩
  set P := ∏ q ∈ d.primeFactors.filter (fun q => ¬ q ∣ b), q with hP
  apply Nat.Coprime.symm
  apply Nat.coprime_of_dvd
  intro q hq hqd hqab
  have hqP : q ∣ P ↔ ¬ q ∣ b := by
    rw [hP]
    first
      | rw [Prime.dvd_finsetProd_iff (Nat.prime_iff.mp hq)]
    constructor
    · rintro ⟨q', hq', hqq'⟩
      rw [Finset.mem_filter, Nat.mem_primeFactors] at hq'
      obtain ⟨⟨hq'p, -, -⟩, hq'b⟩ := hq'
      rwa [(Nat.prime_dvd_prime_iff_eq hq hq'p).mp hqq']
    · intro hqb
      exact ⟨q, Finset.mem_filter.mpr ⟨Nat.mem_primeFactors.mpr ⟨hq, hqd, hd⟩, hqb⟩, dvd_rfl⟩
  by_cases hqb : q ∣ b
  · have hqa : ¬ q ∣ a := by
      intro hqa
      have : q ∣ Nat.gcd a (Nat.gcd b d) := Nat.dvd_gcd hqa (Nat.dvd_gcd hqb hqd)
      rw [hgcd] at this
      exact hq.one_lt.ne' (Nat.dvd_one.mp this)
    have hqaP : q ∣ a * P := (Nat.dvd_add_right hqb).mp (by rwa [add_comm] at hqab)
    rcases (Nat.Prime.dvd_mul hq).mp hqaP with h | h
    · exact hqa h
    · exact (hqP.mp h) hqb
  · have hqP' : q ∣ a * P := Dvd.dvd.mul_left (hqP.mpr hqb) a
    exact hqb ((Nat.dvd_add_right hqP').mp hqab)

theorem main {N a b d : ℕ} (hN : N ≠ 0) (had : a * d = N) (hgcd : Nat.gcd a (Nat.gcd b d) = 1) :
    ∃ γ₁ γ₂ : Matrix.SpecialLinearGroup (Fin 2) ℤ,
      !![(a : ℤ), b; 0, d] = (γ₁ : Matrix (Fin 2) (Fin 2) ℤ) * !![(N : ℤ), 0; 0, 1]
        * (γ₂ : Matrix (Fin 2) (Fin 2) ℤ) := by
  have hd : d ≠ 0 := fun h0 => hN (by rw [← had, h0, mul_zero])
  obtain ⟨p, hp⟩ := exists_coprime_mul_add hd hgcd
  set u : ℤ := (a : ℤ) * p + b with hu
  have hcop : IsCoprime u (d : ℤ) := by
    rw [hu]
    have : ((a * p + b : ℕ) : ℤ) = (a : ℤ) * p + b := by push_cast; ring
    rw [← this, Int.isCoprime_iff_gcd_eq_one, Int.gcd_natCast_natCast]
    exact hp
  obtain ⟨s, t, hst⟩ := hcop
  have hN' : (N : ℤ) = a * d := by exact_mod_cast had.symm
  refine ⟨⟨!![-t, -u; s, -(d : ℤ)], ?_⟩, ⟨!![-1, (p : ℤ); -s * a, (p : ℤ) * s * a - 1], ?_⟩, ?_⟩
  · rw [Matrix.det_fin_two_of]
    linear_combination hst
  · rw [Matrix.det_fin_two_of]
    ring
  · rw [Matrix.mul_fin_two, Matrix.mul_fin_two, hN']
    ext i j
    fin_cases i <;> fin_cases j
    · simp
      linear_combination (-(a : ℤ)) * hst + ((a : ℤ) * s) * hu
    · simp
      linear_combination ((a : ℤ) * p) * hst - ((a : ℤ) * p * s) * hu
    · simp
      ring
    · simp
      ring

end Matrix.SpecialLinearGroup.PrimitiveSmith

theorem solution
    {N a b d : ℕ} (hN : N ≠ 0) (had : a * d = N) (hgcd : Nat.gcd a (Nat.gcd b d) = 1) :
    ∃ γ₁ γ₂ : Matrix.SpecialLinearGroup (Fin 2) ℤ,
      !![(a : ℤ), b; 0, d] = (γ₁ : Matrix (Fin 2) (Fin 2) ℤ) * !![(N : ℤ), 0; 0, 1] * (γ₂ : Matrix (Fin 2) (Fin 2) ℤ) :=
  Matrix.SpecialLinearGroup.PrimitiveSmith.main hN had hgcd

end S_Matrix_SpecialLinearGroup_exists_eq_mul_diagonal_mul_of_gcd_eq_one
end P2MW
export P2MW.S_Matrix_SpecialLinearGroup_exists_eq_mul_diagonal_mul_of_gcd_eq_one (solution)

end privateSection

public section publicSection

theorem Matrix.SpecialLinearGroup.exists_eq_mul_diagonal_mul_of_gcd_eq_one
    {N a b d : ℕ} (hN : N ≠ 0) (had : a * d = N) (hgcd : Nat.gcd a (Nat.gcd b d) = 1) :
    ∃ γ₁ γ₂ : Matrix.SpecialLinearGroup (Fin 2) ℤ,
      !![(a : ℤ), b; 0, d] = (γ₁ : Matrix (Fin 2) (Fin 2) ℤ) * !![(N : ℤ), 0; 0, 1] * (γ₂ : Matrix (Fin 2) (Fin 2) ℤ) := _root_.P2MW.S_Matrix_SpecialLinearGroup_exists_eq_mul_diagonal_mul_of_gcd_eq_one.solution hN had hgcd

end publicSection
