/-
Based on Prove2Me node WeierstrassCurve.nonempty_torsionBy_addEquiv_zmod_prod_of_isAlgClosed
(a6ae4475-f68f-5bc7-a365-f1642a586e13) by Claude (2026-09-05).

Proof based on Prove2Me submission a9593ece-5c12-570d-92a5-17eb0595667e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.FieldTheory.IsAlgClosed.Basic

import Theorems.FLT.Thm_AddCommGroup_nonempty_zmod_prod_addEquiv_torsionBy_of_card_torsionBy_eq_sq
import Theorems.FLT.Thm_WeierstrassCurve_card_torsion_of_isAlgClosed

/-!
# E[n](K)≅(ℤ/n)² over an algebraically closed field

Theorem statement: `WeierstrassCurve.nonempty_torsionBy_addEquiv_zmod_prod_of_isAlgClosed`
(`a6ae4475-f68f-5bc7-a365-f1642a586e13`), by Claude, 2026-09-05.

Proof: submission `a9593ece-5c12-570d-92a5-17eb0595667e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra, $K$ algebraically closed, and let $W$ be a
Weierstrass curve over $F$ which is elliptic (invertible discriminant). Let $n$ be a natural number
whose image in $K$ is nonzero, i.e. the characteristic of $K$ does not divide $n$ (this also forces
$n \neq 0$). The assertion is that the type of additive group isomorphisms $\mathbb Z/n \times
\mathbb Z/n \simeq \mathbb{Z}/n$-free of rank two is nonempty: concretely, `Nonempty (ZMod n × ZMod
n ≃+ Submodule.torsionBy ℤ (W⁄K).Point n)`, where $(W⁄K)$ denotes the base change of $W$ to $K$,
$(W⁄K).\mathrm{Point}$ its group of points, and `Submodule.torsionBy ℤ _ n` the subgroup of elements
killed by $n$. Thus $W(K)[n] \cong \mathbb Z/n \times \mathbb Z/n$ as abelian groups. The statement
is an existence assertion (a `Nonempty` of the type of isomorphisms), not a specified isomorphism,
so it provides no canonical choice of basis of the $n$-torsion.

This is the classical structure theorem for the $n$-torsion of an elliptic curve over an
algebraically closed field of characteristic not dividing $n$ (Silverman, Corollary III.6.4(b)),
i.e. the geometric existence of a full level-$n$ structure. It underlies the construction of mod-$n$
Galois representations attached to elliptic curves and the counting of cyclic $n$-subgroups, and is
cited widely in the modular-curve and Galois-representation parts of the development.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_nonempty_torsionBy_addEquiv_zmod_prod_of_isAlgClosed.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point

theorem solution
    {F K : Type*} [Field F] [Field K] [Algebra F K] [IsAlgClosed K] [DecidableEq K]
    (W : WeierstrassCurve F) [W.IsElliptic] {n : ℕ} (hn : (n : K) ≠ 0) :
    Nonempty (ZMod n × ZMod n ≃+ Submodule.torsionBy ℤ (W⁄K).Point n) := by
  have hn0 : n ≠ 0 := by rintro rfl; exact hn Nat.cast_zero
  refine AddCommGroup.nonempty_zmod_prod_addEquiv_torsionBy_of_card_torsionBy_eq_sq hn0 ?_
  intro d hd
  have hdK : (d : K) ≠ 0 := by
    obtain ⟨c, rfl⟩ := hd
    intro h; apply hn; push_cast; rw [h, zero_mul]
  exact W.card_torsion_of_isAlgClosed hdK

end privateSection

public section publicSection

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point

theorem WeierstrassCurve.nonempty_torsionBy_addEquiv_zmod_prod_of_isAlgClosed
    {F K : Type*} [Field F] [Field K] [Algebra F K] [IsAlgClosed K] [DecidableEq K]
    (W : WeierstrassCurve F) [W.IsElliptic] {n : ℕ} (hn : (n : K) ≠ 0) :
    Nonempty (ZMod n × ZMod n ≃+ Submodule.torsionBy ℤ (W⁄K).Point n) :=
  solution W hn

end publicSection
