/-
Based on Prove2Me node ModularCurve.coe_frickeInvolutionFull_modularUnitSeries
(79408102-26d3-5260-b18d-9dc1e6671f44) by Claude (2026-09-05).

Proof based on Prove2Me submission 870e3474-6437-5122-8229-fc8052e94490
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ModularUnit
public import Definitions.FLT.Def_ModularCurve_AtkinLehner

import Definitions.FLT.Def_ModularForm_HeckeOperator
import Mathlib.NumberTheory.ModularForms.Discriminant
import Theorems.FLT.Thm_ModularCurve_hasSum_modularUnitSeries_qParam
import Theorems.FLT.Thm_ModularCurve_hasSum_smul_modularUnitSeries_inv_qParam
import Theorems.FLT.Thm_ModularCurve_discriminant_div_discriminant_heckeDiagMatrix_smul
import Theorems.FLT.Thm_ModularCurve_coe_frickeInvolutionFull_eq_of_hasSum_of_gamma0_invariant
import Definitions.FLT.Def_P2M_Util

/-!
# Fricke involution sends Ogg's unit to ℓ¹²u_ℓ⁻¹

Theorem statement: `ModularCurve.coe_frickeInvolutionFull_modularUnitSeries`
(`79408102-26d3-5260-b18d-9dc1e6671f44`), by Claude, 2026-09-05.

Proof: submission `870e3474-6437-5122-8229-fc8052e94490`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\ell$ be a prime. Inside the field $\mathbb{Q}((q))$ of rational Laurent series,
[`ModularCurve.modularUnitSeries`](def/ModularCurve_ModularUnit.html#L127) $\ell$ denotes the series
$u_\ell = \Delta \cdot (\Delta^{(\ell)})^{-1}$, where $\Delta$ is the Laurent series $q\prod_{n\ge
1}(1-q^n)^{24}$ built from the single term $q$ and the power series `dedekindEtaUnitQ`, and
$\Delta^{(\ell)}$ is its image under the substitution $q \mapsto q^{\ell}$ given by `qExpand ℚ ℓ`.
Let `modularFunctionFieldFull ℓ` be the intermediate field of $\mathbb{Q}((q))$ over $\mathbb{Q}$
generated by the set of series `qExpand ℚ d jq` for the nonzero divisors $d$ of $\ell$, and let
`hmem` be a witness that $u_\ell$ lies in that field. Let `frickeInvolutionFull ℓ` be the
$\mathbb{Q}$-algebra automorphism of this field chosen, if one exists, to satisfy `IsFrickeAutFull
ℓ`, i.e. to interchange `qExpand ℚ a jq` and `qExpand ℚ b jq` whenever $ab=\ell$ (and the identity
automorphism otherwise). The assertion is that the image of the element $u_\ell$ of
`modularFunctionFieldFull ℓ` under this automorphism, regarded again as a Laurent series, is
$\ell^{12}$ times $u_\ell^{-1}$, the scalar acting coefficientwise.

This is the classical behaviour of Ogg's modular unit $u_\ell = \Delta(q)/\Delta(q^{\ell})$ under
the Fricke involution $w_\ell$ on the modular function field of level $\ell$, namely $w_\ell(u_\ell)
= \ell^{12} u_\ell^{-1}$, recorded here at the level of $q$-expansions. It feeds the construction of
models and of residue/specialisation data for the curves $X_0(\ell)$ used further on.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_coe_frickeInvolutionFull_modularUnitSeries.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_coe_frickeInvolutionFull_modularUnitSeries
p2m_attr_erase "instance" "ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ"

theorem solution (ℓ : ℕ) [Fact (Nat.Prime ℓ)] (hmem : ModularCurve.modularUnitSeries ℓ ∈ ModularCurve.modularFunctionFieldFull ℓ) : ((ModularCurve.frickeInvolutionFull ℓ ⟨ModularCurve.modularUnitSeries ℓ, hmem⟩ : ModularCurve.modularFunctionFieldFull ℓ) : LaurentSeries ℚ) = (ℓ : ℚ) ^ 12 • (ModularCurve.modularUnitSeries ℓ)⁻¹ := by
  have : NeZero ℓ := ⟨(Fact.out : Nat.Prime ℓ).ne_zero⟩
  exact ModularCurve.coe_frickeInvolutionFull_eq_of_hasSum_of_gamma0_invariant ℓ
    (ModularCurve.modularUnitSeries ℓ) ((ℓ : ℚ) ^ 12 • (ModularCurve.modularUnitSeries ℓ)⁻¹)
    (fun τ => ModularForm.discriminant τ
      / ModularForm.discriminant (ModularForm.heckeDiagMatrix ℓ • τ))
    (fun τ => ModularCurve.hasSum_modularUnitSeries_qParam ℓ τ)
    (fun τ => ModularCurve.hasSum_smul_modularUnitSeries_inv_qParam ℓ τ)
    (fun γ hγ τ => ModularCurve.discriminant_div_discriminant_heckeDiagMatrix_smul ℓ γ hγ τ) hmem

end S_ModularCurve_coe_frickeInvolutionFull_modularUnitSeries
end P2MW
export P2MW.S_ModularCurve_coe_frickeInvolutionFull_modularUnitSeries (solution)

end privateSection

public section publicSection

theorem ModularCurve.coe_frickeInvolutionFull_modularUnitSeries (ℓ : ℕ) [Fact (Nat.Prime ℓ)] (hmem : ModularCurve.modularUnitSeries ℓ ∈ ModularCurve.modularFunctionFieldFull ℓ) : ((ModularCurve.frickeInvolutionFull ℓ ⟨ModularCurve.modularUnitSeries ℓ, hmem⟩ : ModularCurve.modularFunctionFieldFull ℓ) : LaurentSeries ℚ) = (ℓ : ℚ) ^ 12 • (ModularCurve.modularUnitSeries ℓ)⁻¹ := _root_.P2MW.S_ModularCurve_coe_frickeInvolutionFull_modularUnitSeries.solution ℓ hmem

end publicSection
