/-
Based on Prove2Me node WeierstrassCurve.Affine.exists_transEquiv_weilFun_eq
(2444aae1-be93-5d1a-b696-00e31bad4857) by Claude (2026-09-05).

Proof based on Prove2Me submission 1455fb5f-e52c-5d9c-9e81-84decbf6b318
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_EllipticCurve_WeilPairingFun

import Theorems.FLT.Thm_WeierstrassCurve_Affine_valuation_transEquiv_weilFun
import Theorems.FLT.Thm_WeierstrassCurve_Affine_valuation_weilFun
import Theorems.FLT.Thm_WeierstrassCurve_Affine_weilFun_ne_zero
import Theorems.FLT.Thm_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one
import Definitions.FLT.Def_P2M_Util

/-!
# Translation invariance of the Weil function g_T up to a constant

Theorem statement: `WeierstrassCurve.Affine.exists_transEquiv_weilFun_eq`
(`2444aae1-be93-5d1a-b696-00e31bad4857`), by Claude, 2026-09-05.

Proof: submission `1455fb5f-e52c-5d9c-9e81-84decbf6b318`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra, $K$ algebraically closed, and let $W$ be a
Weierstrass curve over $F$ which is elliptic; assume the coordinate ring of the affine base-changed
curve $W\!\!\upharpoonright\! K$ is a Dedekind domain. Let $n$ be a natural number whose image in
$K$ is nonzero, and let $S$ and $T$ be points of the group of $K$-points of the affine curve with
$(n : \mathbb{Z}) \cdot S = 0$ and $(n : \mathbb{Z}) \cdot T = 0$. Write $g_T$ for `weilFun W K n
T`, the element of the function field obtained as the quotient of the image of `weilNum W K n T` by
the image of `weilNum W K n 0`, where `weilNum W K n T` is a chosen generator of the ideal `fibIdeal
W K n T` when that ideal is principal and $1$ otherwise; and write $\tau_S^*$ for `transEquiv W K
S`, the $K$-algebra automorphism of the function field given by `transPull W K S` with inverse
`transPull W K (-S)`. The conclusion asserts the existence of a unit $c \in K^\times$ with
$\tau_S^*(g_T) = \iota(c)\, g_T$, where $\iota$ is the structure map $K \to (W\!\!\upharpoonright\!
K).\mathrm{FunctionField}$.

This is the invariance step in the construction of the Weil pairing: the function $g_T$ with divisor
$[n]^*(T) - [n]^*(O)$ is, up to a multiplicative constant, unchanged by translation by an
$n$-torsion point $S$, and that constant is the pairing value $e_n(S,T)$. It is used by the
statements establishing the basic properties of `weilPairing0`, including bilinearity in the first
variable and nondegeneracy.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_exists_transEquiv_weilFun_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_exists_transEquiv_weilFun_eq
p2m_attr_erase "instance" "instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly"
p2m_attr_erase "simp" "compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two"

open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain WithZero

theorem solution {F : Type*} {K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] [IsDedekindDomain (W⁄K).CoordinateRing] {n : ℕ} (hn : (n : K) ≠ 0) (S T : (W⁄K).Point) (hS : (n : ℤ) • S = 0) (hT : (n : ℤ) • T = 0) : ∃ c : Kˣ, transEquiv W K S (weilFun W K n T) = algebraMap K (W⁄K).FunctionField (c : K) * weilFun W K n T := by
  have hg0 := weilFun_ne_zero W hn hT
  have hval : ∀ v : HeightOneSpectrum (W⁄K).CoordinateRing,
      v.valuation (W⁄K).FunctionField (transEquiv W K S (weilFun W K n T) / weilFun W K n T) = 1 := by
    intro v
    obtain ⟨P, hP, rfl⟩ := placeOf_surjective W K v
    rw [map_div₀, valuation_transEquiv_weilFun W hn S hT P hP, valuation_weilFun W hn hT P hP, smul_add, hS,
      add_zero, div_self]
    refine div_ne_zero ?_ ?_ <;> split_ifs <;> simp
  obtain ⟨c, hc0, hc⟩ :=
    WeierstrassCurve.Affine.FunctionField.exists_eq_algebraMap_of_valuation_eq_one (W := W.baseChange K) hval
  exact ⟨Units.mk0 c hc0, by rw [Units.val_mk0, ← hc, div_mul_cancel₀ _ hg0]⟩

end S_WeierstrassCurve_Affine_exists_transEquiv_weilFun_eq
end P2MW
export P2MW.S_WeierstrassCurve_Affine_exists_transEquiv_weilFun_eq (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain WithZero

theorem WeierstrassCurve.Affine.exists_transEquiv_weilFun_eq {F : Type*} {K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] [IsDedekindDomain (W⁄K).CoordinateRing] {n : ℕ} (hn : (n : K) ≠ 0) (S T : (W⁄K).Point) (hS : (n : ℤ) • S = 0) (hT : (n : ℤ) • T = 0) : ∃ c : Kˣ, transEquiv W K S (weilFun W K n T) = algebraMap K (W⁄K).FunctionField (c : K) * weilFun W K n T := _root_.P2MW.S_WeierstrassCurve_Affine_exists_transEquiv_weilFun_eq.solution W hn S T hS hT

end publicSection
