/-
Based on Prove2Me node AlgebraicCurve.finiteDimensional_adjoin_of_transcendental
(685f0eca-c73f-571c-b627-994c1364dfe4) by Claude (2026-09-05).

Proof based on Prove2Me submission bc4e1e56-5766-5df9-8200-673eaab4dc84
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Defs
public import Mathlib.RingTheory.Algebraic.Defs
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs

import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.AlgebraicIndependent.Transcendental
import Mathlib.RingTheory.AlgebraicIndependent.AlgebraicClosure
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.LinearAlgebra.Dimension.FreeAndStrongRankCondition
import Definitions.FLT.Def_P2M_Util

/-!
# Finiteness over K(t) for every transcendental t

Theorem statement: `AlgebraicCurve.finiteDimensional_adjoin_of_transcendental`
(`685f0eca-c73f-571c-b627-994c1364dfe4`), by Claude, 2026-09-05.

Proof: submission `bc4e1e56-5766-5df9-8200-673eaab4dc84`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $x \in F$ be an element such that $F$ is
finite-dimensional as a vector space over the intermediate field $K(x) =$ `IntermediateField.adjoin
K {x}`. Let $t \in F$ be transcendental over $K$, that is, $t$ is not algebraic over $K$
(`Transcendental K t`). The conclusion is that $F$ is finite-dimensional over the intermediate field
$K(t) =$ `IntermediateField.adjoin K {t}`. The hypothesis on $x$ is an instance assumption, and no
relation between $x$ and $t$ is required: $x$ is an arbitrary element witnessing finiteness over
some simple intermediate extension, and the assertion is that finiteness then holds over the
subfield generated by any transcendental element. (If $x$ happens to be algebraic over $K$ the
hypothesis forces $F$ to be algebraic over $K$, so no transcendental $t$ exists and the statement is
empty; the substantive case is $F$ a function field in one variable over $K$.)

This is the intermediate-field form of the standard fact that a function field of one variable is
finite over $K(t)$ for every $t$ transcendental over the constant field, independently of the chosen
generator. It is used throughout the curve-theoretic part of the development, for instance in the
treatment of reductions and of places, where a transcendental element is produced by other means and
finiteness over the field it generates is then needed.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_finiteDimensional_adjoin_of_transcendental.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_finiteDimensional_adjoin_of_transcendental

open Set Cardinal

namespace AlgebraicCurve
namespace FF2KE3

variable {K F : Type*} [Field K] [Field F] [Algebra K F]

theorem isAlgebraic_adjoin_of_transcendental' (x : F)
    [halg : Algebra.IsAlgebraic (IntermediateField.adjoin K ({x} : Set F)) F]
    {t : F} (ht : Transcendental K t) :
    Algebra.IsAlgebraic (IntermediateField.adjoin K ({t} : Set F)) F := by
  have hx : Transcendental K x := by
    intro hxalg
    have : Algebra.IsAlgebraic K (IntermediateField.adjoin K ({x} : Set F)) :=
      IntermediateField.isAlgebraic_adjoin_simple hxalg.isIntegral
    have : Algebra.IsAlgebraic K F :=
      Algebra.IsAlgebraic.trans K (IntermediateField.adjoin K ({x} : Set F)) F
    exact ht (Algebra.IsAlgebraic.isAlgebraic t)
  have hbx : IsTranscendenceBasis K ![x] := by
    rw [isTranscendenceBasis_iff_algebraicIndependent_isAlgebraic]
    refine ⟨algebraicIndependent_iff_transcendental.mpr hx, ?_⟩
    have : Set.range ![x] = {x} := by simp
    rw [this]
    exact (IntermediateField.isAlgebraic_adjoin_iff_top (F := K) (s := ({x} : Set F))).mp halg
  have hind : AlgebraicIndepOn K id ({t} : Set F) := by
    rw [AlgebraicIndepOn, algebraicIndependent_unique_type_iff]
    simpa using ht
  obtain ⟨S, htS, hS⟩ := exists_isTranscendenceBasis_superset hind
  have hcard := hS.lift_cardinalMk_eq hbx
  simp only [Cardinal.mk_fin, Nat.cast_one, Cardinal.lift_one, Cardinal.lift_eq_one] at hcard
  have hS_eq : S = {t} :=
    (Cardinal.mk_le_one_iff_set_subsingleton.mp hcard.le).eq_singleton_of_mem (htS rfl)
  subst hS_eq
  have h := hS.isAlgebraic_field
  rwa [Subtype.range_coe] at h

theorem finiteDimensional_adjoin_of_transcendental' (x : F)
    [hfin : FiniteDimensional (IntermediateField.adjoin K ({x} : Set F)) F]
    {t : F} (ht : Transcendental K t) :
    FiniteDimensional (IntermediateField.adjoin K ({t} : Set F)) F := by
  have halg : Algebra.IsAlgebraic (IntermediateField.adjoin K ({t} : Set F)) F :=
    isAlgebraic_adjoin_of_transcendental' x ht
  set E := IntermediateField.adjoin K ({t} : Set F)
  set Kx := IntermediateField.adjoin K ({x} : Set F)
  let b := Module.finBasis Kx F
  let S : Set F := insert x (Set.range b)
  have : Finite S := Set.Finite.insert x (Set.finite_range b) |>.to_subtype
  have hM : FiniteDimensional E (IntermediateField.adjoin E S) :=
    IntermediateField.finiteDimensional_adjoin fun y _ => (halg.isAlgebraic y).isIntegral
  have htop : IntermediateField.adjoin E S = ⊤ := by
    rw [eq_top_iff]
    intro y _
    have hKx : ∀ c : Kx, (c : F) ∈ IntermediateField.adjoin E S := by
      intro c
      have hle : Kx ≤ (IntermediateField.adjoin E S).restrictScalars K := by
        rw [IntermediateField.adjoin_le_iff]
        intro z hz
        rw [Set.mem_singleton_iff] at hz
        subst hz
        exact IntermediateField.subset_adjoin E S (Set.mem_insert _ _)
      exact hle c.2
    rw [← b.sum_repr y]
    refine Subfield.sum_mem _ fun i _ => ?_
    rw [IntermediateField.smul_def]
    exact mul_mem (hKx _) (IntermediateField.subset_adjoin E S (Set.mem_insert_of_mem _ ⟨i, rfl⟩))
  rw [htop] at hM
  exact (IntermediateField.topEquiv (F := E) (E := F)).toLinearEquiv.finiteDimensional

end AlgebraicCurve.FF2KE3

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (x : F)
    [FiniteDimensional (IntermediateField.adjoin K ({x} : Set F)) F] {t : F} (ht : Transcendental K t) :
    FiniteDimensional (IntermediateField.adjoin K ({t} : Set F)) F :=
  AlgebraicCurve.FF2KE3.finiteDimensional_adjoin_of_transcendental' x ht

end S_AlgebraicCurve_finiteDimensional_adjoin_of_transcendental
end P2MW
export P2MW.S_AlgebraicCurve_finiteDimensional_adjoin_of_transcendental (solution)

end privateSection

public section publicSection

theorem AlgebraicCurve.finiteDimensional_adjoin_of_transcendental {K F : Type*} [Field K] [Field F] [Algebra K F] (x : F)
    [FiniteDimensional (IntermediateField.adjoin K ({x} : Set F)) F] {t : F} (ht : Transcendental K t) :
    FiniteDimensional (IntermediateField.adjoin K ({t} : Set F)) F := _root_.P2MW.S_AlgebraicCurve_finiteDimensional_adjoin_of_transcendental.solution x ht

end publicSection
