/-
Based on Prove2Me node WeierstrassCurve.Affine.finiteDimensional_ratFunc_functionField
(005f46f1-5de1-5f0a-9742-e0301c6626cf) by Claude (2026-09-05).

Proof based on Prove2Me submission e9326b09-441a-502b-b043-42a3e6456029
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_WeierstrassCurve_FunctionFieldQuadratic

import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Theorems.FLT.Thm_WeierstrassCurve_Affine_adjoin_yCoord_eq_top
import Definitions.FLT.Def_P2M_Util

/-!
# The function field of a Weierstrass curve is finite over F(x)

Theorem statement: `WeierstrassCurve.Affine.finiteDimensional_ratFunc_functionField`
(`005f46f1-5de1-5f0a-9742-e0301c6626cf`), by Claude, 2026-09-05.

Proof: submission `e9326b09-441a-502b-b043-42a3e6456029`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be a field and let $W$ be an affine Weierstrass curve over $F$, that is, a tuple of
coefficients $a_1,a_2,a_3,a_4,a_6 \in F$ presenting the affine equation $Y^2 + a_1XY + a_3Y = X^3 +
a_2X^2 + a_4X + a_6$. Its function field $W.FunctionField$ is the fraction field of the coordinate
ring of $W$, the quotient of $F[X][Y]$ by the Weierstrass polynomial; it carries an algebra
structure over the rational function field $RatFunc F$ in one variable, induced by sending the
variable to the class of the $x$-coordinate. The assertion is that $W.FunctionField$ is
finite-dimensional as a vector space over $RatFunc F$, i.e. that $F(W)$ is a finite extension of
$F(x)$. Only finiteness is asserted: no bound on the degree is part of the conclusion, in particular
the classical statement that the degree is at most $2$, with $F(W) = F(x)(y)$ and $y$ satisfying a
quadratic equation over $F(x)$, is stronger than what is stated here.

This is the standard finiteness of the function field of a plane Weierstrass model over the rational
function field in the $x$-coordinate; in the development it supplies the finite-extension hypothesis
used to produce principal divisors on $F(W)$, and it is invoked in the treatment of norms along the
extension and in the construction of countable intermediate fields with prescribed finrank.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_finiteDimensional_ratFunc_functionField.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_finiteDimensional_ratFunc_functionField

set_option synthInstance.maxHeartbeats 800000

open WeierstrassCurve.Affine in
theorem solution {F : Type*} [Field F] (W : WeierstrassCurve.Affine F) :
    FiniteDimensional (RatFunc F) W.FunctionField := by
  have h1 : FiniteDimensional (RatFunc F)
      (IntermediateField.adjoin (RatFunc F) {yCoord W}) :=
    IntermediateField.adjoin.finiteDimensional isIntegral_yCoord
  rw [WeierstrassCurve.Affine.adjoin_yCoord_eq_top] at h1
  exact (IntermediateField.topEquiv
    (F := RatFunc F) (E := W.FunctionField)).toLinearEquiv.finiteDimensional

end S_WeierstrassCurve_Affine_finiteDimensional_ratFunc_functionField
end P2MW
export P2MW.S_WeierstrassCurve_Affine_finiteDimensional_ratFunc_functionField (solution)

end privateSection

public section publicSection

theorem WeierstrassCurve.Affine.finiteDimensional_ratFunc_functionField {F : Type*} [Field F] (W : WeierstrassCurve.Affine F) :
    FiniteDimensional (RatFunc F) W.FunctionField := _root_.P2MW.S_WeierstrassCurve_Affine_finiteDimensional_ratFunc_functionField.solution W

end publicSection
