/-
Based on Prove2Me node WeierstrassCurve.Affine.Point.exists_zsmul_some_eq_some_baseChange
(2098c45a-1264-59ac-a1e4-8401808ef3c9) by Claude (2026-09-05).

Proof based on Prove2Me submission c6f43190-738e-5d94-8e4d-f66649925800
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Basic

import Definitions.FLT.Def_WeierstrassCurve_EDSEngine
import Mathlib.NumberTheory.EllipticDivisibilitySequence
import Mathlib.Algebra.Ring.NegOnePow
import Mathlib.Data.Fin.VecNotation
import Mathlib.Data.Fin.Tuple.Sort
import Mathlib.Algebra.GroupWithZero.NonZeroDivisors
import Mathlib.Algebra.MvPolynomial.CommRing
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Tactic.Abel
import Mathlib.Tactic.IntervalCases
import Mathlib.Tactic.FieldSimp
import Mathlib.GroupTheory.Perm.Basic
import Mathlib.GroupTheory.Perm.Sign
import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.Algebra.Polynomial.Bivariate
import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.AlgebraicGeometry.EllipticCurve.Jacobian.Point
import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Degree
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.Data.Nat.Factorization.Induction
import Mathlib.Logic.Embedding.Set
import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.Data.Set.Card
import Mathlib.Algebra.Module.Torsion.Basic
import Definitions.FLT.Def_P2M_Util

/-!
# Universal two-coordinate multiplication-by-n formula for Weierstrass curves

Theorem statement: `WeierstrassCurve.Affine.Point.exists_zsmul_some_eq_some_baseChange`
(`2098c45a-1264-59ac-a1e4-8401808ef3c9`), by Claude, 2026-09-05.

Proof: submission `c6f43190-738e-5d94-8e4d-f66649925800`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$ be a commutative ring, $W$ a Weierstrass curve over $R$, and $n$ an integer. The assertion
is that there exists a single bivariate polynomial $\omega \in R[X][Y]$, depending only on $W$ and
$n$, with the following property: for every field $F$ (with decidable equality) carrying an
$R$-algebra structure, and all $x, y \in F$ such that $(x,y)$ is a nonsingular point of the affine
model of the base change $W_F =$ `W.baseChange F`, and such that the value $\psi_n(x,y)$ of the
$n$-th division polynomial of $W_F$ at $(x,y)$ is nonzero, the pair
$$\left(\frac{\Phi_n(x)}{\Psi_n^2(x)},\ \frac{\omega_F(x,y)}{\psi_n(x,y)^3}\right)$$ is again a
nonsingular point of the affine model of $W_F$ — the existence of the nonsingularity witness is part
of the conclusion — and the $n$-fold multiple $n \cdot \mathtt{some}\,x\,y\,h$ in the group of
affine points of $W_F$ equals the point with these coordinates. Here $\Phi_n$, $\Psi_n^2$ are the
univariate division polynomials of $W_F$ evaluated at $x$, and $\omega_F$ denotes the image of
$\omega$ under the coefficientwise map induced by `algebraMap R F`. Thus $\omega$ is universal: one
polynomial over the base ring serves all $R$-algebra fields $F$ simultaneously.

This is the classical two-coordinate multiplication-by-$n$ formula $nP = (\phi_n/\psi_n^2,
\omega_n/\psi_n^3)$ for a Weierstrass curve, in the form $n(x:y:1) = (\phi_n : \omega_n : \psi_n)$
in Jacobian coordinates read affinely, with the third family $\omega_n$ of division polynomials
produced over the base ring so that it specialises compatibly to every field extension. The
universality in $F$ is what makes the formula usable both for points over a fixed field and for the
generic point over the function field; it is used in the analysis of valuations of the coordinates
of $nP$, in
[`WeierstrassCurve.Affine.valuation_mulPull_le_of_ne_zero`](thm.html#WeierstrassCurve.Affine.valuation_mulPull_le_of_ne_zero).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_Point_exists_zsmul_some_eq_some_baseChange.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_Point_exists_zsmul_some_eq_some_baseChange

section PortCardMulXY

namespace PortCard

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point Polynomial
open scoped Polynomial.Bivariate

theorem zsmul_some_eq_some_jac {F : Type*} [Field F] [DecidableEq F] (V : WeierstrassCurve F)
    {x y : F} (h : V.toAffine.Nonsingular x y) {n : ℤ} (hψ : (V.ψ n).evalEval x y ≠ 0) :
    ∃ h' : V.toAffine.Nonsingular ((V.φ n).evalEval x y / (V.ψ n).evalEval x y ^ 2)
        ((V.ωe n).evalEval x y / (V.ψ n).evalEval x y ^ 3),
      n • Point.some x y h = Point.some ((V.φ n).evalEval x y / (V.ψ n).evalEval x y ^ 2)
        ((V.ωe n).evalEval x y / (V.ψ n).evalEval x y ^ 3) h' := by
  have key := zsmul_eq_smulEval V h n
  have hVz : smulEval V x y n 2 ≠ 0 := hψ
  have hV := key ▸ (n • Jacobian.Point.fromAffine (Point.some x y h)).nonsingular
  have hQeq : (n • Jacobian.Point.fromAffine (Point.some x y h)) =
      Jacobian.Point.mk hV := Jacobian.Point.ext key
  refine ⟨(Jacobian.nonsingular_of_Z_ne_zero hVz).mp hV, ?_⟩
  calc n • Point.some x y h
      = Jacobian.Point.toAffineAddEquiv V
          (n • Jacobian.Point.fromAffine (Point.some x y h)) := by
        rw [map_zsmul, ← Jacobian.Point.toAffineAddEquiv_symm_apply,
          AddEquiv.apply_symm_apply]
    _ = _ := by
        rw [hQeq, Jacobian.Point.toAffineAddEquiv_apply]
        exact Jacobian.Point.toAffineLift_of_Z_ne_zero hVz

theorem some_congr {F : Type*} [CommRing F] {V : Affine F} {x₁ x₂ y₁ y₂ : F} (ex : x₁ = x₂)
    (ey : y₁ = y₂) (h₁ : V.Nonsingular x₁ y₁) :
    ∃ h₂ : V.Nonsingular x₂ y₂, Point.some x₁ y₁ h₁ = Point.some x₂ y₂ h₂ := by
  subst ex ey; exact ⟨h₁, rfl⟩

universe u v in

theorem exists_zsmul_some_eq_some_baseChange {R : Type u} [CommRing R] (W : WeierstrassCurve R)
    (n : ℤ) : ∃ ω : R[X][Y], ∀ {F : Type v} [Field F] [DecidableEq F] [Algebra R F] {x y : F}
      (h : (W.baseChange F).toAffine.Nonsingular x y),
      ((W.baseChange F).ψ n).evalEval x y ≠ 0 →
        ∃ h' : (W.baseChange F).toAffine.Nonsingular
            (((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x)
            ((ω.map (mapRingHom (algebraMap R F))).evalEval x y /
              ((W.baseChange F).ψ n).evalEval x y ^ 3),
          n • Point.some x y h =
            Point.some (((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x)
              ((ω.map (mapRingHom (algebraMap R F))).evalEval x y /
                ((W.baseChange F).ψ n).evalEval x y ^ 3) h' := by
  refine ⟨W.ωe n, ?_⟩
  intro F _ _ _ x y h hψ
  have hω : (W.baseChange F).ωe n = (W.ωe n).map (mapRingHom (algebraMap R F)) := by
    rw [WeierstrassCurve.baseChange, map_ωe]
  obtain ⟨h₁, e₁⟩ := zsmul_some_eq_some_jac (W.baseChange F) h hψ
  have ex : ((W.baseChange F).φ n).evalEval x y / ((W.baseChange F).ψ n).evalEval x y ^ 2 =
      ((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x := by
    rw [(W.baseChange F).evalEval_φ h.left n, (W.baseChange F).evalEval_ψ_sq h.left n]
  have ey : ((W.baseChange F).ωe n).evalEval x y / ((W.baseChange F).ψ n).evalEval x y ^ 3 =
      ((W.ωe n).map (mapRingHom (algebraMap R F))).evalEval x y /
        ((W.baseChange F).ψ n).evalEval x y ^ 3 := by
    rw [hω]
  obtain ⟨h₂, e₂⟩ := some_congr ex ey h₁
  exact ⟨h₂, e₁.trans e₂⟩

end PortCard

end PortCardMulXY

universe u v

theorem solution {R : Type u} [CommRing R] (W : WeierstrassCurve R) (n : ℤ) : ∃ ω : Polynomial (Polynomial R), ∀ {F : Type v} [Field F] [DecidableEq F] [Algebra R F] {x y : F} (h : (W.baseChange F).toAffine.Nonsingular x y), ((W.baseChange F).ψ n).evalEval x y ≠ 0 → ∃ h' : (W.baseChange F).toAffine.Nonsingular (((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x) ((ω.map (Polynomial.mapRingHom (algebraMap R F))).evalEval x y / ((W.baseChange F).ψ n).evalEval x y ^ 3), n • WeierstrassCurve.Affine.Point.some x y h = WeierstrassCurve.Affine.Point.some (((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x) ((ω.map (Polynomial.mapRingHom (algebraMap R F))).evalEval x y / ((W.baseChange F).ψ n).evalEval x y ^ 3) h' :=
  PortCard.exists_zsmul_some_eq_some_baseChange W n

end S_WeierstrassCurve_Affine_Point_exists_zsmul_some_eq_some_baseChange
end P2MW
export P2MW.S_WeierstrassCurve_Affine_Point_exists_zsmul_some_eq_some_baseChange (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

universe u v

theorem WeierstrassCurve.Affine.Point.exists_zsmul_some_eq_some_baseChange {R : Type u} [CommRing R] (W : WeierstrassCurve R) (n : ℤ) : ∃ ω : Polynomial (Polynomial R), ∀ {F : Type v} [Field F] [DecidableEq F] [Algebra R F] {x y : F} (h : (W.baseChange F).toAffine.Nonsingular x y), ((W.baseChange F).ψ n).evalEval x y ≠ 0 → ∃ h' : (W.baseChange F).toAffine.Nonsingular (((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x) ((ω.map (Polynomial.mapRingHom (algebraMap R F))).evalEval x y / ((W.baseChange F).ψ n).evalEval x y ^ 3), n • WeierstrassCurve.Affine.Point.some x y h = WeierstrassCurve.Affine.Point.some (((W.baseChange F).Φ n).eval x / ((W.baseChange F).ΨSq n).eval x) ((ω.map (Polynomial.mapRingHom (algebraMap R F))).evalEval x y / ((W.baseChange F).ψ n).evalEval x y ^ 3) h' := _root_.P2MW.S_WeierstrassCurve_Affine_Point_exists_zsmul_some_eq_some_baseChange.solution W n

end publicSection
