/-
Based on Prove2Me node ModularCurve.restrict_eq_jLinePlaceZero_iff
(7d50d614-5cbb-5eb3-b5b5-e72bcb066e77) by Claude (2026-09-05).

Proof based on Prove2Me submission 27f578db-2387-5377-bc9f-08ac4de3ba3d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
public import Definitions.FLT.Def_ModularCurve_JLinePlaces

import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.Star
import Theorems.FLT.Thm_ModularCurve_eq_jLinePlaceZero_iff_ord_jGen_pos
import Definitions.FLT.Def_P2M_Util

/-!
# Place of X₀(N) lies over j=0 iff ord_w(j)>0

Theorem statement: `ModularCurve.restrict_eq_jLinePlaceZero_iff`
(`7d50d614-5cbb-5eb3-b5b5-e72bcb066e77`), by Claude, 2026-09-05.

Proof: submission `27f578db-2387-5377-bc9f-08ac4de3ba3d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix a natural number $N \neq 0$ and let $F_N$ denote [`ModularCurve.modularFunctionField
N`](def/ModularCurve_X0.html#L250), the intermediate field of $\mathbb{Q} \subseteq \mathbb{Q}((q))$
(Laurent series over $\mathbb{Q}$) generated by the $q$-expansion $jq$ of the modular $j$-function
and by its $N$-fold substitution $q \mapsto q^N$; $F_N$ is regarded as an algebra over the simple
extension $\mathbb{Q}\langle jq\rangle$ by way of the inclusion of subfields of $\mathbb{Q}((q))$.
Assume $F_N$ is integral over $\mathbb{Q}\langle jq \rangle$, and let $w$ be a place of $F_N$ over
$\mathbb{Q}$, that is, a valuation subring of $F_N$ which contains the image of $\mathbb{Q}$, is not
all of $F_N$, and is a principal ideal ring. Then the restriction of $w$ to $\mathbb{Q}\langle
jq\rangle$ — the valuation subring obtained by pulling $w$ back along the inclusion
$\mathbb{Q}\langle jq\rangle \hookrightarrow F_N$ — equals
[`ModularCurve.jLinePlaceZero`](def/ModularCurve_JLinePlaces.html#L54), the place of the $j$-line
obtained by transporting the finite place of $\mathbb{Q}(T)$ cut out by $T - 0$ along the
isomorphism $\mathbb{Q}(T) \cong \mathbb{Q}\langle jq \rangle$ sending $T$ to $jq$ (available since
$jq$ is transcendental over $\mathbb{Q}$), if and only if $\mathrm{ord}_w$ of the element $jq$ of
$F_N$ is strictly positive, where $\mathrm{ord}_w$ is minus the logarithm of the adic valuation
attached to the height-one prime of $w$.

This is the statement that a place of the function field of $X_0(N)$ lies over the point $j = 0$ of
the $j$-line exactly when the $j$-invariant vanishes there, one of the lemmas pinning down places of
$F_N$ by the order of vanishing of $j$ (and of $j - 1728$) at them. It is used in the computations
of the numbers of points of $X_0(N)$ above $j = 0$ and $j = 1728$, namely in
[`ModularCurve.natCard_ord_jBar_eq_one_eq_nuThree`](thm.html#ModularCurve.natCard_ord_jBar_eq_one_eq_nuThree)
and
[`ModularCurve.natCard_ord_jBar_sub_1728_eq_one_eq_nuTwo`](thm.html#ModularCurve.natCard_ord_jBar_sub_1728_eq_one_eq_nuTwo).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_restrict_eq_jLinePlaceZero_iff.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_restrict_eq_jLinePlaceZero_iff
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero"
p2m_attr_erase "simp" "ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

set_option synthInstance.maxHeartbeats 1600000

open IntermediateField AlgebraicCurve

namespace ModularCurve
p2m_export "ModularCurve" "jAdjoinAlgebra jLinePlaceZero jq modularFunctionField jq_mem jGen eq_jLinePlaceZero_iff_ord_jGen_pos"
namespace RestrictAux
end ModularCurve.RestrictAux
p2m_open_scoped "ModularCurve" in

theorem ModularCurve.RestrictAux.ord_algebraMap_pos_iff (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)) (x : ↥ℚ⟮ModularCurve.jq⟯),
      (0 < w.ord (algebraMap ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N) x) ↔
          0 < (w.restrict ↥ℚ⟮ModularCurve.jq⟯).ord x) ∧
      (w.ord (algebraMap ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N) x) < 0 ↔
          (w.restrict ↥ℚ⟮ModularCurve.jq⟯).ord x < 0) := by
  let := ModularCurve.jAdjoinAlgebra N
  intro _ w x
  have he : (0 : ℤ) < (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) :=
    Int.natCast_pos.mpr (w.ramificationIndex_pos (F := ↥ℚ⟮ModularCurve.jq⟯))
  rw [w.ord_restrict (F := ↥ℚ⟮ModularCurve.jq⟯) x]
  constructor
  · constructor
    · intro h; by_contra hle; rw [not_lt] at hle; nlinarith
    · intro h; positivity
  · constructor
    · intro h; by_contra hle; rw [not_lt] at hle; nlinarith
    · intro h; nlinarith

theorem solution (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)),
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ = ModularCurve.jLinePlaceZero ↔
        0 < w.ord (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) := by
  let := ModularCurve.jAdjoinAlgebra N
  intro _ w
  rw [ModularCurve.eq_jLinePlaceZero_iff_ord_jGen_pos,
    ← (ModularCurve.RestrictAux.ord_algebraMap_pos_iff N w ModularCurve.jGen).1]
  rfl

end S_ModularCurve_restrict_eq_jLinePlaceZero_iff
end P2MW
export P2MW.S_ModularCurve_restrict_eq_jLinePlaceZero_iff (solution)

end privateSection

public section publicSection


open IntermediateField AlgebraicCurve
theorem ModularCurve.restrict_eq_jLinePlaceZero_iff (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)),
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ = ModularCurve.jLinePlaceZero ↔
        0 < w.ord (⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) := _root_.P2MW.S_ModularCurve_restrict_eq_jLinePlaceZero_iff.solution N

end publicSection
