/-
Based on Prove2Me node HeckeEis.existsEichlerShimuraMapLinear
(0df9c703-9190-57ad-9fd3-324c5ce3ec81) by Claude (2026-09-05).

Proof based on Prove2Me submission ac66899a-e5f4-51ed-b477-7f8271e0cfc5
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.Basic
public import Definitions.FLT.Def_HeckeEis_EichlerIntegral

import Theorems.FLT.Thm_HeckeEis_eichlerShimuraMap_add
import Theorems.FLT.Thm_HeckeEis_eichlerShimuraMap_smul
import Definitions.FLT.Def_P2M_Util

/-!
# ℂ-linearity of the Eichler–Shimura map

Theorem statement: `HeckeEis.existsEichlerShimuraMapLinear`
(`0df9c703-9190-57ad-9fd3-324c5ce3ec81`), by Claude, 2026-09-05.

Proof: submission `ac66899a-e5f4-51ed-b477-7f8271e0cfc5`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix natural numbers $n$ and $N$ with $N \neq 0$. Let $\rho$ denote the representation of
$\Gamma_0(N)$ obtained by restricting [`HeckeEis.binaryFormRepSL ℂ
n`](def/HeckeEis_BinaryFormRep.html#L61) along the inclusion of $\Gamma_0(N)$ into
$\mathrm{SL}(2,\mathbb{Z})$, that is, the action of $\mathrm{SL}(2,\mathbb{Z})$ on the space of
degree-$n$ homogeneous polynomials in $\mathbb{C}[X_0,X_1]$ by the substitution $X_j \mapsto \sum_i
M_{ij} X_i$ for $M$ the integral matrix underlying the group element. Let
[`HeckeEis.coeffH1par`](def/Gamma0CoeffCohomology.html#L100) $\rho$ be the quotient of the submodule
of parabolic cocycles (those cocycles $z : \Gamma_0(N) \to \mathrm{BinaryForm}\,\mathbb{C}\,n$ with
$z\gamma$ in the range of $\rho\gamma - 1$ whenever the trace of $\gamma$ has square $4$) by the
submodule of coboundaries. The assertion is that there exists a $\mathbb{C}$-linear map $ES$ from
the space of cusp forms of weight $(n : \mathbb{Z}) + 2$ for $\Gamma_0(N)$ to this parabolic
cohomology module such that for every such cusp form $f$ one has $ES\,f =$
[`HeckeEis.eichlerShimuraMap`](def/HeckeEis_EichlerIntegral.html#L114) $n\,N$ applied to the
underlying function $\mathbb{H} \to \mathbb{C}$ of $f$; the latter is, by definition, the class of
the cocycle $\gamma \mapsto F(\gamma \cdot i) - \rho\gamma(F(i))$ of a chosen equivariant primitive
$F$ that is an Eichler integral of $f$ with parabolic cocycle, when such an $F$ exists, and $0$
otherwise. The conclusion is a bare existential statement, so no particular linear map is named.

This is the linearity of the classical Eichler–Shimura map $S_{n+2}(\Gamma_0(N)) \to
H^1_{\mathrm{par}}(\Gamma_0(N), \mathrm{Sym}^n)$, here realised with coefficients in binary forms of
degree $n$ and with the class of a cusp form defined through a choice of admissible Eichler
integral. It is used downstream in the injectivity of the Eichler–Shimura map and in the
construction of integral and mod-$p$ eigenclasses in parabolic cohomology attached to Hecke
eigenforms.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_existsEichlerShimuraMapLinear.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HeckeEis_existsEichlerShimuraMapLinear

noncomputable section

namespace HeckeEis
p2m_export "HeckeEis" "binaryFormRepSL coeffH1par eichlerShimuraMap eichlerShimuraMap_add eichlerShimuraMap_smul"
p2m_open "HeckeEis"

open UpperHalfPlane MvPolynomial CongruenceSubgroup
open scoped MatrixGroups ModularForm

theorem SolMain.lin (n N : ℕ) [NeZero N] :
    ∃ ES : CuspForm (Gamma0 N) ((n : ℤ) + 2) →ₗ[ℂ] coeffH1par ((binaryFormRepSL ℂ n).comp (Gamma0 N).subtype),
      ∀ f : CuspForm (Gamma0 N) ((n : ℤ) + 2), ES f = eichlerShimuraMap n N f :=
  ⟨{ toFun := fun f => eichlerShimuraMap n N ⇑f,
      map_add' := fun f g => eichlerShimuraMap_add n N f g,
      map_smul' := fun c f => by rw [RingHom.id_apply]; exact eichlerShimuraMap_smul n N c f },
    fun _ => rfl⟩

end HeckeEis

end

open scoped MatrixGroups ModularForm in
theorem solution (n N : ℕ) [NeZero N] :
    ∃ ES : CuspForm (CongruenceSubgroup.Gamma0 N) ((n : ℤ) + 2) →ₗ[ℂ] HeckeEis.coeffH1par ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype),
      ∀ f : CuspForm (CongruenceSubgroup.Gamma0 N) ((n : ℤ) + 2), ES f = HeckeEis.eichlerShimuraMap n N f :=
  HeckeEis.SolMain.lin n N

end S_HeckeEis_existsEichlerShimuraMapLinear
end P2MW
export P2MW.S_HeckeEis_existsEichlerShimuraMapLinear (solution)

end privateSection

public section publicSection


open scoped MatrixGroups ModularForm
theorem HeckeEis.existsEichlerShimuraMapLinear (n N : ℕ) [NeZero N] :
    ∃ ES : CuspForm (CongruenceSubgroup.Gamma0 N) ((n : ℤ) + 2) →ₗ[ℂ] HeckeEis.coeffH1par ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype),
      ∀ f : CuspForm (CongruenceSubgroup.Gamma0 N) ((n : ℤ) + 2), ES f = HeckeEis.eichlerShimuraMap n N f := _root_.P2MW.S_HeckeEis_existsEichlerShimuraMapLinear.solution n N

end publicSection
