/-
Based on Prove2Me node ModularCurve.dedekindPsi_prime_pow
(42b5757b-a2d0-5c42-9ab9-c8450d39a549) by Claude (2026-09-05).

Proof based on Prove2Me submission c9b681dd-26eb-582b-acc2-c2e8fb075045
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0

import Mathlib.Data.Nat.Squarefree
import Mathlib.NumberTheory.Divisors
import Mathlib.Tactic.IntervalCases
import Definitions.FLT.Def_P2M_Util

/-!
# Dedekind ψ at a prime power

Theorem statement: `ModularCurve.dedekindPsi_prime_pow` (`42b5757b-a2d0-5c42-9ab9-c8450d39a549`), by
Claude, 2026-09-05.

Proof: submission `c9b681dd-26eb-582b-acc2-c2e8fb075045`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $p$ and $k$ be natural numbers, with $p$ prime and $k \neq 0$. The function `dedekindPsi` is
defined on a natural number $N$ by $\mathrm{dedekindPsi}(N) = \sum_{d} N/d$, the sum being over
those $d$ in the finite set of divisors of $N$ that are squarefree, with $N/d$ the natural-number
quotient. The assertion is the equality of natural numbers $$\mathrm{dedekindPsi}(p^k) = p^k +
p^{k-1},$$ where $k-1$ denotes truncated subtraction in $\mathbb{N}$ (harmless here, since $k \neq
0$). Equivalently, $\mathrm{dedekindPsi}(p^k) = p^{k-1}(p+1)$: only the divisors $1$ and $p$ of
$p^k$ are squarefree, so the defining sum has exactly the two terms $p^k/1$ and $p^k/p$.

This is the single Euler factor of the Dedekind $\psi$ function, $\psi(N) = N \prod_{p \mid N}(1 +
1/p)$, which records the index $[\mathrm{SL}_2(\mathbb{Z}) : \Gamma_0(N)]$ and hence the degree of
the covering $X_0(N) \to X(1)$. Together with multiplicativity of $\psi$ on coprime arguments it
pins down $\psi$ at every positive integer, and it is used throughout the numerical work on indices,
orbit counts and genus formulas for modular curves in this development.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_dedekindPsi_prime_pow.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_dedekindPsi_prime_pow

p2m_open "ModularCurve Finset Nat Finset.Nat"

theorem solution (p k : ℕ) (hp : p.Prime) (hk : k ≠ 0) :
    dedekindPsi (p ^ k) = p ^ k + p ^ (k - 1) := by
  have hsqfree : ∀ j, Squarefree (p ^ j) ↔ j ≤ 1 := fun j => by
    constructor
    · intro hsq
      by_contra hj
      exact hp.one_lt.ne'
        (Nat.isUnit_iff.mp (hsq p (by rw [← pow_two]; exact pow_dvd_pow p (by omega))))
    · intro hj
      interval_cases j
      · simp
      · simpa using hp.prime.squarefree
  have hfilter : {d ∈ (p ^ k).divisors | Squarefree d} = {1, p} := by
    ext d
    simp only [Finset.mem_filter, Nat.mem_divisors, Finset.mem_insert, Finset.mem_singleton]
    constructor
    · rintro ⟨⟨hdvd, -⟩, hsq⟩
      obtain ⟨j, hj, rfl⟩ := (Nat.dvd_prime_pow hp).mp hdvd
      have : j ≤ 1 := (hsqfree j).mp hsq
      interval_cases j
      · exact Or.inl (pow_zero p)
      · exact Or.inr (pow_one p)
    · rintro (rfl | rfl)
      · exact ⟨⟨one_dvd _, pow_ne_zero _ hp.pos.ne'⟩, squarefree_one⟩
      · exact ⟨⟨dvd_pow_self _ hk, pow_ne_zero _ hp.pos.ne'⟩, hp.prime.squarefree⟩
  have hdiv : p ^ k / p = p ^ (k - 1) := by
    conv_lhs => rw [show k = (k - 1) + 1 by omega, pow_succ]
    exact Nat.mul_div_cancel _ hp.pos
  rw [dedekindPsi, hfilter, Finset.sum_pair hp.one_lt.ne, Nat.div_one, hdiv]

end S_ModularCurve_dedekindPsi_prime_pow
end P2MW
export P2MW.S_ModularCurve_dedekindPsi_prime_pow (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve
theorem ModularCurve.dedekindPsi_prime_pow (p k : ℕ) (hp : p.Prime) (hk : k ≠ 0) : dedekindPsi (p ^ k) = p ^ k + p ^ (k - 1) := _root_.P2MW.S_ModularCurve_dedekindPsi_prime_pow.solution p k hp hk

end publicSection
