/-
Based on Prove2Me node ModularCurve.exists_emb_equiv_rootsAt
(82b1c70d-b8c9-54ff-b13e-5bf0adee5677) by Claude (2026-09-05).

Proof based on Prove2Me submission 43d1e757-df44-5e53-9740-90f84f9087dc
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_EMD
public import Definitions.FLT.Def_ModularCurve_TatePoint

import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.SimpleRing.Principal
import Theorems.FLT.Thm_ModularCurve_adjoin_jBar_jNBar_eq_top
import Theorems.FLT.Thm_ModularCurve_exists_algHom_of_isRoot
import Definitions.FLT.Def_P2M_Util

/-!
# Normalised embeddings at j₀ versus roots of Φ_N(j₀+t,Y)

Theorem statement: `ModularCurve.exists_emb_equiv_rootsAt` (`82b1c70d-b8c9-54ff-b13e-5bf0adee5677`),
by Claude, 2026-09-05.

Proof: submission `43d1e757-df44-5e53-9740-90f84f9087dc`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix a natural number $N$ with $N \neq 0$, a datum `data` consisting of a monic $\Phi \in
\mathbb{Z}[X][Y]$ of degree $\psi(N) = \sum_{d \mid N,\ d \text{ squarefree}} N/d$ satisfying
$\Phi(j, j_N) = 0$ for the $q$-expansions, and an element $j_0$ of $\overline{\mathbb{Q}} =$
`AlgebraicClosure ℚ`. Write $H =$ `HahnSeries ℚ (AlgebraicClosure ℚ)` for the Hahn series with
rational exponents, and let $\overline{F}_N$ be the intermediate field of $H$ obtained by adjoining
to $\overline{\mathbb{Q}}$ the images under coefficientwise base change `coeffEmb` of the elements
of `modularFunctionFieldFull N`. Then there is a bijection $e$ between `Emb N j₀`, the set of
$\overline{\mathbb{Q}}$-algebra homomorphisms $\psi : \overline{F}_N \to H$ with $\psi(\bar{\jmath})
= j_0 + t$, where $\bar{\jmath}$ is the base change of the Laurent series `jq` and $j_0 + t$ denotes
`HahnSeries.C j₀ + HahnSeries.single 1 1`, and `RootsAt data (jNear j₀)`, the set of $y \in H$ that
are roots of the polynomial obtained from $\Phi$ by substituting $j_0 + t$ for $X$; moreover $e$
satisfies $e(\psi) = \psi(\bar{\jmath}_N)$ for all $\psi$, where $\bar{\jmath}_N$ is the base change
of `qExpand ℚ N jq`, the series `jq` with $q$ replaced by $q^N$.

This is the dictionary between normalised Puiseux-type embeddings of the function field of $X_0(N)$
over $\overline{\mathbb{Q}}$ sending $j$ to $j_0 + t$ and roots of the specialised modular
polynomial $\Phi_N(j_0 + t, Y)$, the bijection being evaluation at $j(q^N)$. It feeds the
construction of elliptic models with a distinguished cyclic subgroup, being used by
[`ModularCurve.exists_elliptic_cycSub_orbitMap_of_props`](thm.html#ModularCurve.exists_elliptic_cycSub_orbitMap_of_props)
and
[`ModularCurve.exists_elliptic_cycSub_orbitMap_prime_of_ne_two`](thm.html#ModularCurve.exists_elliptic_cycSub_orbitMap_prime_of_ne_two).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_emb_equiv_rootsAt.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_emb_equiv_rootsAt
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "HahnSeries.ramScale_apply ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X"
p2m_attr_erase "simp" "ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ ModularCurve.coe_towerInclBar ModularCurve.coe_towerSubstBar"

set_option synthInstance.maxHeartbeats 1600000
set_option maxHeartbeats 6400000

noncomputable section

open ModularCurve AlgebraicCurve IntermediateField Polynomial

namespace S12E

variable (N : ℕ) [NeZero N]

abbrev jb : ↥(modularFunctionFieldBar N) :=
  ⟨coeffEmb (AlgebraicClosure ℚ) jq, coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jq_mem_full N)⟩

abbrev jNb : ↥(modularFunctionFieldBar N) :=
  ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ N jq),
    coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (dvd_refl N))⟩

abbrev PhiAt (data : ModularPolynomialData N) (j₀ : AlgebraicClosure ℚ) : Polynomial (HahnSeries ℚ (AlgebraicClosure ℚ)) :=
  data.Φ.map (Polynomial.eval₂RingHom (Int.castRingHom (HahnSeries ℚ (AlgebraicClosure ℚ)))
    (HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)))

theorem eval₂_Phi_jb_jNb (data : ModularPolynomialData N) :
    data.Φ.eval₂ (Polynomial.eval₂RingHom (Int.castRingHom ↥(modularFunctionFieldBar N)) (jb N)) (jNb N)
      = 0 := by
  apply Subtype.ext
  have hval : ((modularFunctionFieldBar N).toSubfield.subtype).comp
      (Polynomial.eval₂RingHom (Int.castRingHom ↥(modularFunctionFieldBar N)) (jb N))
      = (coeffEmb (AlgebraicClosure ℚ)).comp evalAtJ := by
    refine Polynomial.ringHom_ext (fun z => by simp) ?_
    show ((Polynomial.eval₂RingHom (Int.castRingHom ↥(modularFunctionFieldBar N)) (jb N) X :
        ↥(modularFunctionFieldBar N)) : LaurentSeries (AlgebraicClosure ℚ)) = coeffEmb (AlgebraicClosure ℚ) (evalAtJ X)
    rw [Polynomial.coe_eval₂RingHom, Polynomial.eval₂_X, evalAtJ_X]
  have h0 := congrArg (coeffEmb (AlgebraicClosure ℚ)) data.eval_eq_zero
  rw [map_zero, Polynomial.hom_eval₂, ← hval] at h0
  rw [ZeroMemClass.coe_zero, ← h0]
  show ((modularFunctionFieldBar N).toSubfield.subtype) _ = _
  rw [Polynomial.hom_eval₂]
  rfl

theorem isRoot_apply_jNb' (data : ModularPolynomialData N) (j₀ : AlgebraicClosure ℚ)
    (ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ] HahnSeries ℚ (AlgebraicClosure ℚ))
    (hψ : ψ (jb N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)) :
    (PhiAt N data j₀).IsRoot (ψ (jNb N)) := by
  rw [Polynomial.IsRoot, Polynomial.eval_map, ← hψ]
  have hcomp : Polynomial.eval₂RingHom (Int.castRingHom (HahnSeries ℚ (AlgebraicClosure ℚ))) (ψ (jb N))
      = (ψ.toRingHom).comp (Polynomial.eval₂RingHom (Int.castRingHom ↥(modularFunctionFieldBar N)) (jb N)) := by
    refine Polynomial.ringHom_ext (fun z => by simp) ?_
    simp
  rw [hcomp]
  have h := (Polynomial.hom_eval₂ data.Φ
    (Polynomial.eval₂RingHom (Int.castRingHom ↥(modularFunctionFieldBar N)) (jb N)) ψ.toRingHom (jNb N)).symm
  rw [eval₂_Phi_jb_jNb N data, map_zero] at h
  simpa using h

theorem isRoot_apply_jNb (data : ModularPolynomialData N) (j₀ : AlgebraicClosure ℚ) (ψ : Emb N j₀) :
    (PhiAt N data j₀).IsRoot (ψ.1 (jNb N)) :=
  isRoot_apply_jNb' N data j₀ ψ.1 ψ.2

theorem ext_of_apply_jNb_eq (j₀ : AlgebraicClosure ℚ) (ψ ψ' : Emb N j₀)
    (h : ψ.1 (jNb N) = ψ'.1 (jNb N)) : ψ = ψ' := by
  apply Subtype.ext
  apply AlgHom.ext
  intro z
  have hz : z ∈ (⊤ : IntermediateField (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)) := mem_top
  rw [← ModularCurve.adjoin_jBar_jNBar_eq_top (AlgebraicClosure ℚ) N] at hz
  induction hz using IntermediateField.adjoin_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact ψ.2.trans ψ'.2.symm
    · exact h
  | algebraMap x => rw [AlgHom.commutes, AlgHom.commutes]
  | add x y _ _ hx hy => rw [map_add, map_add, hx, hy]
  | inv x _ hx => rw [map_inv₀, map_inv₀, hx]
  | mul x y _ _ hx hy => rw [map_mul, map_mul, hx, hy]

theorem algebraMap_hahn_eq_C (a : AlgebraicClosure ℚ) :
    algebraMap (AlgebraicClosure ℚ) (HahnSeries ℚ (AlgebraicClosure ℚ)) a = HahnSeries.C a := by
  rw [HahnSeries.algebraMap_apply']; simp

theorem aeval_single_eq (p : Polynomial (AlgebraicClosure ℚ)) :
    Polynomial.aeval (HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)) p
      = HahnSeries.ofPowerSeries ℚ (AlgebraicClosure ℚ) (p : PowerSeries (AlgebraicClosure ℚ)) := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add, Polynomial.coe_add, map_add, hp, hq]
  | monomial n a =>
    rw [← Polynomial.C_mul_X_pow_eq_monomial, map_mul, map_pow, Polynomial.aeval_C, Polynomial.aeval_X,
      algebraMap_hahn_eq_C, Polynomial.coe_mul, Polynomial.coe_pow, Polynomial.coe_C, Polynomial.coe_X,
      map_mul, map_pow, HahnSeries.ofPowerSeries_C, HahnSeries.ofPowerSeries_X]

theorem transcendental_single : Transcendental (AlgebraicClosure ℚ)
    (HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)) := by
  rw [transcendental_iff]
  intro q hq
  rw [aeval_single_eq, ← map_zero (HahnSeries.ofPowerSeries ℚ (AlgebraicClosure ℚ))] at hq
  have := HahnSeries.ofPowerSeries_injective hq
  exact_mod_cast this

theorem transcendental_C_add_single (j₀ : AlgebraicClosure ℚ) : Transcendental (AlgebraicClosure ℚ)
    (HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)) := by
  intro halg
  apply transcendental_single
  have hC : IsAlgebraic (AlgebraicClosure ℚ) (HahnSeries.C j₀ : HahnSeries ℚ (AlgebraicClosure ℚ)) := by
    rw [← algebraMap_hahn_eq_C]
    exact isAlgebraic_algebraMap (R := AlgebraicClosure ℚ) (A := HahnSeries ℚ (AlgebraicClosure ℚ)) j₀
  simpa using halg.sub hC

theorem exists_equiv (data : ModularPolynomialData N) (j₀ : AlgebraicClosure ℚ) :
    ∃ e : Emb N j₀ ≃ ModularCurve.TatePoint.RootsAt data (ModularCurve.TatePoint.jNear j₀),
      ∀ ψ : Emb N j₀, (e ψ).1 = ψ.1 (jNb N) := by
  classical
  let f : Emb N j₀ → ModularCurve.TatePoint.RootsAt data (ModularCurve.TatePoint.jNear j₀) :=
    fun ψ => ⟨ψ.1 (jNb N), isRoot_apply_jNb N data j₀ ψ⟩
  have hinj : Function.Injective f := fun ψ ψ' h =>
    ext_of_apply_jNb_eq N j₀ ψ ψ' (congrArg Subtype.val h)
  have hsurj : Function.Surjective f := by
    rintro ⟨r, hr⟩
    obtain ⟨ψ, h1, h2⟩ := ModularCurve.exists_algHom_of_isRoot (AlgebraicClosure ℚ) N data
      (HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)) r
      (transcendental_C_add_single j₀) hr
    exact ⟨⟨ψ, h1⟩, Subtype.ext h2⟩
  exact ⟨Equiv.ofBijective f ⟨hinj, hsurj⟩, fun ψ => rfl⟩

end S12E

end

theorem solution (N : ℕ) [NeZero N] (data : ModularCurve.ModularPolynomialData N)
    (j₀ : AlgebraicClosure ℚ) :
    ∃ e : ModularCurve.Emb N j₀ ≃ ModularCurve.TatePoint.RootsAt data (ModularCurve.TatePoint.jNear j₀),
      ∀ ψ : ModularCurve.Emb N j₀, (e ψ).1 = ψ.1 ⟨ModularCurve.coeffEmb (AlgebraicClosure ℚ) (ModularCurve.qExpand ℚ N ModularCurve.jq),
        ModularCurve.coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.jqd_mem_full N (dvd_refl N))⟩ := by
  exact S12E.exists_equiv N data j₀

end S_ModularCurve_exists_emb_equiv_rootsAt
end P2MW
export P2MW.S_ModularCurve_exists_emb_equiv_rootsAt (solution)

end privateSection

public section publicSection

theorem ModularCurve.exists_emb_equiv_rootsAt (N : ℕ) [NeZero N] (data : ModularCurve.ModularPolynomialData N)
    (j₀ : AlgebraicClosure ℚ) :
    ∃ e : ModularCurve.Emb N j₀ ≃ ModularCurve.TatePoint.RootsAt data (ModularCurve.TatePoint.jNear j₀),
      ∀ ψ : ModularCurve.Emb N j₀, (e ψ).1 = ψ.1 ⟨ModularCurve.coeffEmb (AlgebraicClosure ℚ) (ModularCurve.qExpand ℚ N ModularCurve.jq),
        ModularCurve.coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.jqd_mem_full N (dvd_refl N))⟩ := _root_.P2MW.S_ModularCurve_exists_emb_equiv_rootsAt.solution N data j₀

end publicSection
