/-
Based on Prove2Me node AlgebraicCurve.Place.restrict_ofAlgAut_smul
(2e110162-9aa0-5bc2-a7ac-8b8e54efc63f) by Claude (2026-09-05).

Proof based on Prove2Me submission c0826770-116c-5481-b13d-8997f74b15fc
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
public import Definitions.FLT.Def_AlgebraicCurve_BaseChangeGalois

import Definitions.FLT.Def_P2M_Util

/-!
# F'-automorphisms fix restrictions of places to F'

Theorem statement: `AlgebraicCurve.Place.restrict_ofAlgAut_smul`
(`2e110162-9aa0-5bc2-a7ac-8b8e54efc63f`), by Claude, 2026-09-05.

Proof: submission `c0826770-116c-5481-b13d-8997f74b15fc`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K \subseteq F' \subseteq M$ be fields, given as a field $K$, a field $F'$ with a $K$-algebra
structure, a field $M$ with $K$- and $F'$-algebra structures forming a scalar tower over $K$, with
$M$ integral over $F'$. Let $\sigma$ be an $F'$-algebra automorphism of $M$, and let $W$ be a place
of $M$ over $K$ in the project's sense: a valuation subring $\mathcal{O}_W \subseteq M$ containing
the image of $K$, different from $M$ itself, and whose underlying ring is a principal ideal ring.
Viewing $\sigma$ as a $K$-algebra automorphism and hence, via `SemilinearAut.ofAlgAut`, as the
semilinear automorphism given by the pair $(\sigma, \mathrm{id}_K)$ of ring automorphisms of $M$ and
of $K$ compatible with $K \to M$, let $\sigma \cdot W$ be the place whose valuation subring is the
pointwise image $\sigma(\mathcal{O}_W)$. The assertion is that the restrictions to $F'$ of $\sigma
\cdot W$ and of $W$ coincide as places of $F'$ over $K$, i.e. $\sigma(\mathcal{O}_W)$ and
$\mathcal{O}_W$ have the same preimage in $F'$ under $F' \to M$.

This is the standard fact that an automorphism of $M$ fixing an intermediate field $F'$ carries each
place of $M$ to a place lying over the same place of $F'$, so that the fibres of restriction are
unions of orbits. It is used in the treatment of the Galois action on places and divisors, notably
in the identity expressing the sum of the Galois translates of a divisor as a pullback of a
pushforward and in the injectivity results for the divisorial Weil pairing.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_restrict_ofAlgAut_smul.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_restrict_ofAlgAut_smul

noncomputable section
p2m_open "AlgebraicCurve P2MW.S_AlgebraicCurve_Place_restrict_ofAlgAut_smul.AlgebraicCurve IsDedekindDomain"
open scoped Pointwise

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place Place.ext SemilinearAut SemilinearAut.inv_smul_def SemilinearAut.ofAlgAut SemilinearAut.toRingAut_ofAlgAut SemilinearAut.smul_toValuationSubring"
p2m_open "AlgebraicCurve"
namespace Place
p2m_export "AlgebraicCurve.Place" "restrict restrict_toValuationSubring ext smul_toValuationSubring"
end Place
end AlgebraicCurve

open _root_.AlgebraicCurve.Place _root_.P2MW.S_AlgebraicCurve_Place_restrict_ofAlgAut_smul.AlgebraicCurve.Place in
theorem solution {K F' M : Type*} [Field K] [Field F'] [Field M]
    [Algebra K F'] [Algebra K M] [Algebra F' M] [IsScalarTower K F' M]
    [Algebra.IsIntegral F' M] (σ : M ≃ₐ[F'] M) (W : Place K M) :
    (SemilinearAut.ofAlgAut (σ.restrictScalars K) • W).restrict F' = W.restrict F' := by
  refine Place.ext ?_
  ext x
  rw [restrict_toValuationSubring, restrict_toValuationSubring, ValuationSubring.mem_comap,
    ValuationSubring.mem_comap, SemilinearAut.smul_toValuationSubring,
    ValuationSubring.mem_pointwise_smul_iff_inv_smul_mem, SemilinearAut.inv_smul_def,
    SemilinearAut.toRingAut_ofAlgAut]
  have : ((σ.restrictScalars K : M ≃+* M).symm (algebraMap F' M x)) = algebraMap F' M x := by
    rw [RingEquiv.symm_apply_eq]
    exact (σ.commutes x).symm
  rw [this]

end

end S_AlgebraicCurve_Place_restrict_ofAlgAut_smul
end P2MW
export P2MW.S_AlgebraicCurve_Place_restrict_ofAlgAut_smul (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.Place.restrict_ofAlgAut_smul {K F' M : Type*} [Field K] [Field F'] [Field M]
    [Algebra K F'] [Algebra K M] [Algebra F' M] [IsScalarTower K F' M]
    [Algebra.IsIntegral F' M] (σ : M ≃ₐ[F'] M) (W : Place K M) :
    (SemilinearAut.ofAlgAut (σ.restrictScalars K) • W).restrict F' = W.restrict F' := _root_.P2MW.S_AlgebraicCurve_Place_restrict_ofAlgAut_smul.solution σ W

end publicSection
