/-
Based on Prove2Me node MulAction.card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime
(066fb680-60a4-5e46-ac13-417af1e630b1) by Claude (2026-09-05).

Proof based on Prove2Me submission 23344518-361b-5787-9abb-031c6df7519d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Data.Nat.Prime.Defs
public import Mathlib.GroupTheory.GroupAction.Defs
public import Mathlib.SetTheory.Cardinal.Finite

import Mathlib.Data.ZMod.QuotientGroup
import Definitions.FLT.Def_P2M_Util

/-!
# Orbit count for an action of a group of prime order

Theorem statement: `MulAction.card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime`
(`066fb680-60a4-5e46-ac13-417af1e630b1`), by Claude, 2026-09-05.

Proof: submission `23344518-361b-5787-9abb-031c6df7519d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $G$ be a group and $X$ a type carrying a multiplicative $G$-action, with both $G$ and $X$
finite, and let $p$ be a prime natural number such that the number of elements of $G$ equals $p$.
The conclusion is the identity of natural numbers $$p \cdot
\#\bigl(\mathrm{MulAction.orbitRel.Quotient}\ G\ X\bigr) \;=\; \#X + (p-1)\cdot
\#\bigl(\mathrm{MulAction.fixedPoints}\ G\ X\bigr),$$ where each $\#$ denotes the natural-number
cardinality of a finite type: the first of the quotient of $X$ by the orbit equivalence relation,
i.e. of the set of $G$-orbits; the second of $X$ itself; the third of the subtype of those $x \in X$
with $g \bullet x = x$ for every $g \in G$. The subtraction $p-1$ is truncated subtraction in
$\mathbb{N}$, which is harmless since $p \ge 2$. Equivalently, since every orbit has size $1$ or $p$
and the singleton orbits are exactly the points fixed by all of $G$, the number of orbits equals
$\#X^G + (\#X - \#X^G)/p$.

This is Burnside's orbit-counting lemma specialised to a group of prime order, where the only
possible orbit sizes are $1$ and $p$. It is used in the counting of elliptic points on modular
curves, for instance in the double counts relating the number of moduli points with $j = 0$ to the
Dedekind $\psi$ function and $\nu_3(N)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_MulAction_card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_MulAction_card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime

open MulAction in
theorem solution
    (G : Type*) {X : Type*} [Group G] [MulAction G X] [Finite G] [Finite X]
    {p : ℕ} (hp : p.Prime) (hG : Nat.card G = p) :
    p * Nat.card (MulAction.orbitRel.Quotient G X)
      = Nat.card X + (p - 1) * Nat.card (MulAction.fixedPoints G X) := by
  classical
  have : Fintype G := Fintype.ofFinite G
  have : Fintype X := Fintype.ofFinite X
  have hGc : Fintype.card G = p := by rw [← Nat.card_eq_fintype_card]; exact hG
  have hfix : ∀ g : G, g ≠ 1 → fixedBy X g = fixedPoints G X := by
    intro g hg
    have hord : orderOf g = p := by
      have hdvd : orderOf g ∣ p := hG ▸ orderOf_dvd_natCard g
      rcases (Nat.dvd_prime hp).mp hdvd with h1 | h
      · exact absurd (orderOf_eq_one_iff.mp h1) hg
      · exact h
    have hgen : Subgroup.zpowers g = ⊤ := by
      apply Subgroup.eq_top_of_card_eq
      rw [Nat.card_zpowers, hord, hG]
    ext x
    simp only [mem_fixedBy, mem_fixedPoints]
    constructor
    · intro hx h
      have hle : Subgroup.zpowers g ≤ stabilizer G x := by
        rw [Subgroup.zpowers_le]; exact hx
      exact hle (by rw [hgen]; exact Subgroup.mem_top h)
    · intro hx; exact hx g
  have c1 : Fintype.card (fixedBy X (1 : G)) = Fintype.card X :=
    Fintype.card_congr (Equiv.subtypeUnivEquiv (fun x => show x ∈ fixedBy X (1 : G) from one_smul G x))
  have cg : ∀ g : G, g ≠ 1 → Fintype.card (fixedBy X g) = Fintype.card (fixedPoints G X) :=
    fun g hg => Fintype.card_congr (Set.equivOfEq (hfix g hg))
  have hB := sum_card_fixedBy_eq_card_orbits_mul_card_group G X
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ (1 : G)), c1,
    Finset.sum_congr rfl (fun g hg => cg g (Finset.ne_of_mem_erase hg)),
    Finset.sum_const, smul_eq_mul, Finset.card_erase_of_mem (Finset.mem_univ _),
    Finset.card_univ, hGc] at hB
  rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card, Nat.card_eq_fintype_card]
  convert hB.symm using 1
  all_goals (first | exact mul_comm _ _  )

end S_MulAction_card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime
end P2MW
export P2MW.S_MulAction_card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime (solution)

end privateSection

public section publicSection

theorem MulAction.card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime
    (G : Type*) {X : Type*} [Group G] [MulAction G X] [Finite G] [Finite X]
    {p : ℕ} (hp : p.Prime) (hG : Nat.card G = p) :
    p * Nat.card (MulAction.orbitRel.Quotient G X)
      = Nat.card X + (p - 1) * Nat.card (MulAction.fixedPoints G X) := _root_.P2MW.S_MulAction_card_mul_natCard_orbitRel_quotient_eq_of_natCard_eq_prime.solution G hp hG

end publicSection
