/-
Based on Prove2Me node ModularCurve.functionFieldGeneration_of_prime
(2cc5d6b3-de60-5d55-aac9-721826fd0e9a) by Claude (2026-09-05).

Proof based on Prove2Me submission 7a079f9e-bd2a-5642-9fa5-7766ff31fd78
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0

import Definitions.FLT.Def_P2M_Util

/-!
# Function field generation at prime level

Theorem statement: `ModularCurve.functionFieldGeneration_of_prime`
(`2cc5d6b3-de60-5d55-aac9-721826fd0e9a`), by Claude, 2026-09-05.

Proof: submission `7a079f9e-bd2a-5642-9fa5-7766ff31fd78`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\ell$ be a natural number, nonzero, and assume $\ell$ is prime. The assertion is the predicate
`FunctionFieldGeneration ℓ`, which unfolds as follows: for every natural number $d$ dividing $\ell$
and nonzero, the Laurent series $\mathrm{qExpand}\,\mathbb{Q}\,d\,\mathrm{jq}$ lies in the
intermediate field $\mathbb{Q}(\mathrm{jq},\ \mathrm{qExpand}\,\mathbb{Q}\,\ell\,\mathrm{jq})$, that
is, in the subfield of the field of rational Laurent series generated over $\mathbb{Q}$ by the
two-element set consisting of the series `jq` and of
$\mathrm{qExpand}\,\mathbb{Q}\,\ell\,\mathrm{jq}$. Here, for a nonzero $N$,
$\mathrm{qExpand}\,\mathbb{Q}\,N$ is the ring endomorphism of $\mathbb{Q}$-Laurent series obtained
by pushing the support forward along multiplication by $N$ on the exponent group $\mathbb{Z}$ (an
injective, order-preserving map, since $N>0$); thus it is the substitution $q \mapsto q^{N}$, and
`jq` is the project's Laurent series attached to the modular invariant $j$. So the conclusion states
that all the series $j(q^{d})$ for $d \mid \ell$ lie in the field generated by $j(q)$ and
$j(q^{\ell})$.

This is the generation statement, at prime level, for the function field of the algebraic model of
$X_0(N)$: the full field $\mathbb{Q}(j(q^{d}) : d \mid N)$ coincides with the field generated by the
two distinguished elements $j(q)$ and $j(q^{N})$. It is used in the curve layer of the $X_0(\ell)$
construction, being cited by
[`ModularCurve.full_eq_of_prime`](thm.html#ModularCurve.full_eq_of_prime) and by
[`ModularCurve.NodeLocalized.place_eq_of_forall_hasValue_iff_of_mem_fieldOver`](thm.html#ModularCurve.NodeLocalized.place_eq_of_forall_hasValue_iff_of_mem_fieldOver).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_functionFieldGeneration_of_prime.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_functionFieldGeneration_of_prime

open ModularCurve IntermediateField

noncomputable section

theorem solution {ℓ : ℕ} [NeZero ℓ] (hℓ : ℓ.Prime) : FunctionFieldGeneration ℓ :=by
  intro d hd hne
  have := hne
  rcases (Nat.dvd_prime hℓ).mp hd with rfl | rfl
  · rw [qExpand_one_apply]
    exact subset_adjoin ℚ _ (Set.mem_insert _ _)
  · exact subset_adjoin ℚ _ (Set.mem_insert_of_mem _ rfl)

end

end S_ModularCurve_functionFieldGeneration_of_prime
end P2MW
export P2MW.S_ModularCurve_functionFieldGeneration_of_prime (solution)

end privateSection

public section publicSection


open ModularCurve IntermediateField
theorem ModularCurve.functionFieldGeneration_of_prime {ℓ : ℕ} [NeZero ℓ] (hℓ : ℓ.Prime) : FunctionFieldGeneration ℓ := _root_.P2MW.S_ModularCurve_functionFieldGeneration_of_prime.solution hℓ

end publicSection
