/-
Based on Prove2Me node ModularCurve.place_eq_of_induces
(3e5b60a8-b53e-5a31-b5d0-fd9932faeef9) by Claude (2026-09-05).

Proof based on Prove2Me submission a98c9cd9-76a7-563b-aa3e-7afe08026cfa
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_EMD
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Rat.Star
import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaces
import Definitions.FLT.Def_P2M_Util

/-!
# A Hahn-series embedding induces at most one place

Theorem statement: `ModularCurve.place_eq_of_induces` (`3e5b60a8-b53e-5a31-b5d0-fd9932faeef9`), by
Claude, 2026-09-05.

Proof: submission `a98c9cd9-76a7-563b-aa3e-7afe08026cfa`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix a natural number $N \neq 0$ and write $\bar F_N$ for `modularFunctionFieldBar N`, the
intermediate field of the Laurent series field $\overline{\mathbb{Q}}((q))$ obtained by adjoining to
$\overline{\mathbb{Q}}$ the coefficientwise image of the subfield
$\mathbb{Q}(\mathrm{divisorExpansions}\,N) \subseteq \mathbb{Q}((q))$. Let $\psi : \bar F_N \to
\mathrm{HahnSeries}\ \mathbb{Q}\ \overline{\mathbb{Q}}$ be an $\overline{\mathbb{Q}}$-algebra
homomorphism into the Hahn series over $\overline{\mathbb{Q}}$ with exponents in $\mathbb{Q}$, and
let $w, w'$ be places of $\bar F_N$ over $\overline{\mathbb{Q}}$, that is, valuation subrings of
$\bar F_N$ containing the image of $\overline{\mathbb{Q}}$, different from the whole field, and
which are principal ideal rings. Assume that $\psi$ induces $w$ and that $\psi$ induces $w'$, where
`Induces ψ w` means: there is a rational number $g > 0$ such that for every $x \in \bar F_N$ one has
$(\mathrm{ord}_w x)\, g = \mathrm{order}(\psi x)$, the order of the Hahn series $\psi x$. The
conclusion is $w = w'$: the scaling factors may differ, but the place is unique.

This is the uniqueness half of the correspondence between embeddings of the level-$N$ modular
function field into Hahn series and places of that field, the existence half being a separate
statement. It is used in the computation of the orders of vanishing of $j$ and $j - 1728$ at the
relevant places, hence in the verification of the Eichler–Selberg/mass-type count of elliptic
points, and in [`ModularCurve.emd_holds`](thm.html#ModularCurve.emd_holds).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_place_eq_of_induces.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_place_eq_of_induces

open ModularCurve AlgebraicCurve

namespace S12Q

variable (N : ℕ) [NeZero N]

omit [NeZero N] in
theorem mem_iff_ord_nonneg (w : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N))
    {x : ↥(modularFunctionFieldBar N)} (hx : x ≠ 0) :
    x ∈ w.toValuationSubring ↔ 0 ≤ w.ord x := by
  rw [Place.mem_iff_adicValuation_le_one, Place.ord, neg_nonneg,
    WithZero.log_le_iff_le_exp (w.adicValuation_ne_zero hx), WithZero.exp_zero]

theorem induces_unique
    {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ] HahnSeries ℚ (AlgebraicClosure ℚ)}
    {w w' : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)}
    (hw : Induces ψ w) (hw' : Induces ψ w') : w = w' := by
  obtain ⟨g, hg, h⟩ := hw
  obtain ⟨g', hg', h'⟩ := hw'
  have key : ∀ x, 0 ≤ w.ord x ↔ 0 ≤ w'.ord x := by
    intro x
    have hx := h x
    rw [← h' x] at hx
    constructor
    · intro h0
      have : 0 ≤ (w'.ord x : ℚ) * g' := by rw [← hx]; positivity
      exact_mod_cast nonneg_of_mul_nonneg_left this hg'
    · intro h0
      have : 0 ≤ (w.ord x : ℚ) * g := by rw [hx]; positivity
      exact_mod_cast nonneg_of_mul_nonneg_left this hg
  apply Place.ext
  ext x
  rcases eq_or_ne x 0 with rfl | hx
  · simp [zero_mem]
  · rw [mem_iff_ord_nonneg N w hx, mem_iff_ord_nonneg N w' hx, key]

end S12Q

theorem solution {N : ℕ} [NeZero N]
    {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ] HahnSeries ℚ (AlgebraicClosure ℚ)}
    {w w' : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)}
    (h : Induces ψ w) (h' : Induces ψ w') : w = w' := by
  exact S12Q.induces_unique N h h'

end S_ModularCurve_place_eq_of_induces
end P2MW
export P2MW.S_ModularCurve_place_eq_of_induces (solution)

end privateSection

public section publicSection


open AlgebraicCurve ModularCurve IsDedekindDomain WithZero
theorem ModularCurve.place_eq_of_induces {N : ℕ} [NeZero N]
    {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ] HahnSeries ℚ (AlgebraicClosure ℚ)}
    {w w' : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)}
    (h : Induces ψ w) (h' : Induces ψ w') : w = w' := _root_.P2MW.S_ModularCurve_place_eq_of_induces.solution h h'

end publicSection
