/-
Based on Prove2Me node WeierstrassCurve.veluQuotient2_Delta_eq
(35e01041-be58-5e74-b79d-340fff99fa98) by Claude (2026-09-05).

Proof based on Prove2Me submission 18408a7d-4df7-513f-b981-4c3e770f7944
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_WeierstrassCurve_VeluOrderTwo

import Definitions.FLT.Def_P2M_Util

/-!
# Discriminant of the order-two Vélu quotient

Theorem statement: `WeierstrassCurve.veluQuotient2_Delta_eq`
(`35e01041-be58-5e74-b79d-340fff99fa98`), by Claude, 2026-09-05.

Proof: submission `18408a7d-4df7-513f-b981-4c3e770f7944`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$ be a commutative ring and let $W$ be a Weierstrass curve over $R$ with coefficients
$a_1,a_2,a_3,a_4,a_6$. Let $x_0,y_0\in R$ satisfy the affine Weierstrass equation of $W$ at
$(x_0,y_0)$, and assume moreover that $\mathrm{veluGy}(x_0,y_0) = -(2y_0 + a_1x_0 + a_3) = 0$, so
that the point is fixed by the involution of the curve. Write $g_x = \mathrm{veluGx}(x_0,y_0) =
3x_0^2 + 2a_2x_0 + a_4 - a_1y_0$, and let $W' = \mathrm{veluQuotient2}\,x_0\,y_0$ be the Weierstrass
curve over $R$ with the same $a_1,a_2,a_3$ as $W$, with $a_4$ replaced by $a_4 - 5g_x$ and with
$a_6$ replaced by $a_6 - b_2 g_x - 7x_0 g_x$, where $b_2 = a_1^2 + 4a_2$. Then the discriminant of
$W'$ satisfies $$\Delta(W') = g_x \cdot \bigl(b_2^2 - 8b_2x_0 - 48x_0^2 - 32b_4\bigr)^2,$$ the
second factor being $\mathrm{velu2QuadDisc}\,x_0$ (with $b_4 = 2a_4 + a_1a_3$).

This is the discriminant formula for the quotient of a Weierstrass curve by the subgroup generated
by a point of order two in Vélu's explicit form: one factor of $g_x$ is traded for one factor of the
quadratic cofactor $\mathrm{velu2QuadDisc}$ relative to the corresponding factorisation of
$\Delta(W)$. It is used to show that the order-two Vélu quotient is again elliptic
([`WeierstrassCurve.veluQuotient2_Delta_ne_zero`](thm.html#WeierstrassCurve.veluQuotient2_Delta_ne_zero)),
to compute its $j$-invariant
([`WeierstrassCurve.veluQuotient2_j`](thm.html#WeierstrassCurve.veluQuotient2_j)), and in the
construction of the induced map on points
([`WeierstrassCurve.exists_addMonoidHom_coe_eq_veluPointMap2`](thm.html#WeierstrassCurve.exists_addMonoidHom_coe_eq_veluPointMap2)).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_veluQuotient2_Delta_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_veluQuotient2_Delta_eq

open WeierstrassCurve WeierstrassCurve.Affine in
theorem solution {R : Type*} [CommRing R] {W : WeierstrassCurve R} {x₀ y₀ : R}
    (hQ : W.toAffine.Equation x₀ y₀) (hgy : W.veluGy x₀ y₀ = 0) :
    (W.veluQuotient2 x₀ y₀).Δ = W.veluGx x₀ y₀ * W.velu2QuadDisc x₀ ^ 2 := by
  rw [Affine.equation_iff] at hQ
  simp only [veluGy] at hgy
  simp only [Δ, b₂, b₄, b₆, b₈, veluQuotient2, veluGx, velu2QuadDisc]
  linear_combination
    (W.a₁^6 + 12*W.a₁^4*W.a₂ - 36*W.a₁^3*W.a₃ + 504*W.a₁^3*y₀ + 48*W.a₁^2*W.a₂^2 - 1008*W.a₁^2*W.a₂*x₀ - 576*W.a₁^2*W.a₄ - 1512*W.a₁^2*x₀^2 - 144*W.a₁*W.a₂*W.a₃ + 2016*W.a₁*W.a₂*y₀ + 6480*W.a₁*x₀*y₀ + 64*W.a₂^3 - 4032*W.a₂^2*x₀ - 2304*W.a₂*W.a₄ - 18576*W.a₂*x₀^2 + 216*W.a₃^2 + 432*W.a₃*y₀ - 6480*W.a₄*x₀ + 432*W.a₆ - 18576*x₀^3 + 432*y₀^2) * hQ
    + (24*W.a₁^6*y₀ - 47*W.a₁^5*W.a₂*x₀ - 24*W.a₁^5*W.a₄ - 70*W.a₁^5*x₀^2 + W.a₁^4*W.a₂*W.a₃ + 194*W.a₁^4*W.a₂*y₀ + W.a₁^4*W.a₃*x₀ - 110*W.a₁^4*x₀*y₀ - 376*W.a₁^3*W.a₂^2*x₀ - 192*W.a₁^3*W.a₂*W.a₄ - 340*W.a₁^3*W.a₂*x₀^2 - W.a₁^3*W.a₃^2 - 692*W.a₁^3*W.a₃*y₀ + 112*W.a₁^3*W.a₄*x₀ + 327*W.a₁^3*x₀^3 + 4252*W.a₁^3*y₀^2 + 8*W.a₁^2*W.a₂^2*W.a₃ + 400*W.a₁^2*W.a₂^2*y₀ + 1352*W.a₁^2*W.a₂*W.a₃*x₀ - 16944*W.a₁^2*W.a₂*x₀*y₀ + 688*W.a₁^2*W.a₃*W.a₄ + 2001*W.a₁^2*W.a₃*x₀^2 - 9888*W.a₁^2*W.a₄*y₀ - 24606*W.a₁^2*x₀^2*y₀ - 752*W.a₁*W.a₂^3*x₀ - 384*W.a₁*W.a₂^2*W.a₄ + 15760*W.a₁*W.a₂^2*x₀^2 - 36*W.a₁*W.a₂*W.a₃^2 + 432*W.a₁*W.a₂*W.a₃*y₀ + 19648*W.a₁*W.a₂*W.a₄*x₀ + 49008*W.a₁*W.a₂*x₀^3 + 1008*W.a₁*W.a₂*y₀^2 - 27*W.a₁*W.a₃^2*x₀ + 1620*W.a₁*W.a₃*x₀*y₀ + 5632*W.a₁*W.a₄^2 + 28608*W.a₁*W.a₄*x₀^2 + 35568*W.a₁*x₀^4 + 3348*W.a₁*x₀*y₀^2 + 16*W.a₂^3*W.a₃ + 32*W.a₂^3*y₀ - 1008*W.a₂^2*W.a₃*x₀ - 2016*W.a₂^2*x₀*y₀ - 576*W.a₂*W.a₃*W.a₄ - 4752*W.a₂*W.a₃*x₀^2 - 1152*W.a₂*W.a₄*y₀ - 9504*W.a₂*x₀^2*y₀ + 27*W.a₃^3 + 162*W.a₃^2*y₀ - 1728*W.a₃*W.a₄*x₀ - 4752*W.a₃*x₀^3 + 324*W.a₃*y₀^2 - 3456*W.a₄*x₀*y₀ - 9504*x₀^3*y₀ + 216*y₀^3) * hgy

end S_WeierstrassCurve_veluQuotient2_Delta_eq
end P2MW
export P2MW.S_WeierstrassCurve_veluQuotient2_Delta_eq (solution)

end privateSection

public section publicSection


namespace WeierstrassCurve
variable {R : Type*} [CommRing R] {W : WeierstrassCurve R}
theorem veluQuotient2_Delta_eq {x₀ y₀ : R}
    (hQ : W.toAffine.Equation x₀ y₀) (hgy : W.veluGy x₀ y₀ = 0) :
    (W.veluQuotient2 x₀ y₀).Δ = W.veluGx x₀ y₀ * W.velu2QuadDisc x₀ ^ 2 := _root_.P2MW.S_WeierstrassCurve_veluQuotient2_Delta_eq.solution hQ hgy
end WeierstrassCurve

end publicSection
