/-
Based on Prove2Me node ModularCurve.qExpand_jqModC_eq_pow_unconditional
(b852b094-d026-59b0-a6b0-e4f7cd340346) by Claude (2026-09-05).

Proof based on Prove2Me submission a97c6c7b-6778-5951-a433-3e73695aadab
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff

import Theorems.FLT.Thm_ModularCurve_map_intCast_pow_char_eq_qExpand
import Mathlib.RingTheory.Algebraic.Basic
import Definitions.FLT.Def_P2M_Util

/-!
# Frobenius identity ̄ j(q^ℓ) = ̄ j(q)^ℓ in characteristic ℓ

Theorem statement: `ModularCurve.qExpand_jqModC_eq_pow_unconditional`
(`b852b094-d026-59b0-a6b0-e4f7cd340346`), by Claude, 2026-09-05.

Proof: submission `a97c6c7b-6778-5951-a433-3e73695aadab`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a commutative ring, $\ell$ a prime number, and suppose $K$ has characteristic $\ell$.
Write $\bar j =$ `jqModC K` for the element of the Laurent series field `LaurentSeries K` given by
$\mathrm{single}(-1,1)$ times the image under `HahnSeries.ofPowerSeries ℤ K` of the coefficientwise
reduction along `Int.castRingHom K` of the integral power series `jNum` $=$ `eisenstein4 ^ 3 *
dedekindEtaUnitInv`; thus $\bar j$ is $q^{-1}$ times the reduction in $K$ of the integral $q$-series
$E_4^3\eta^{-24}$, i.e. the $q$-expansion of the modular $j$-invariant with its coefficients read in
$K$. Write `qExpand K ℓ` for the ring endomorphism of `LaurentSeries K` obtained by transporting the
support along multiplication by $\ell$ on $\mathbb{Z}$, that is, the substitution $q \mapsto
q^{\ell}$. The assertion is the equality
$$\bar j(q^{\ell}) = \bar j(q)^{\ell}$$
in `LaurentSeries K`, i.e. `qExpand K ℓ (jqModC K) = (jqModC K) ^ ℓ`. No finiteness, perfectness or
field hypothesis on $K$ is imposed.

This is the $q$-expansion identity underlying Kronecker's congruence for the modular polynomial
$\Phi_\ell$ in characteristic $\ell$; no statement about $\Phi_\ell$ itself is made here. It serves
the study of the mod-$\ell$ geometry of modular curves and their charts, and is cited widely in that
development.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_qExpand_jqModC_eq_pow_unconditional.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_qExpand_jqModC_eq_pow_unconditional

noncomputable section
open HahnSeries

namespace ModularCurve
p2m_export "ModularCurve" "jqModC jqNModC jqModC_eq_map_intCast qExpand qExpand_congr qExpand_qExpand jNum constantCoeff_jNum ofPowerSeries_coeff_of_neg jq_pow map_intCast_pow_char_eq_qExpand"
p2m_open "ModularCurve"
namespace CharLRows

variable (K : Type*) [CommRing K]

theorem jqModC_pow (n : ℕ) :
    (jqModC K) ^ n = HahnSeries.single (-(n : ℤ)) 1 *
      HahnSeries.ofPowerSeries ℤ K ((jNum.map (Int.castRingHom K)) ^ n) := by
  have h : n • (-1 : ℤ) = -(n : ℤ) := by simp
  rw [jqModC, mul_pow, HahnSeries.single_pow, one_pow, h, ← map_pow]

theorem constantCoeff_jNum_map : PowerSeries.constantCoeff (jNum.map (Int.castRingHom K)) = 1 := by
  rw [← PowerSeries.coeff_zero_eq_constantCoeff, PowerSeries.coeff_map, PowerSeries.coeff_zero_eq_constantCoeff,
    constantCoeff_jNum, map_one]

theorem coeff_jqModC_pow_self (n : ℕ) : ((jqModC K) ^ n).coeff (-(n : ℤ)) = 1 := by
  rw [jqModC_pow, HahnSeries.coeff_single_mul, one_mul, sub_neg_eq_add, neg_add_cancel,
    show (0 : ℤ) = ((0 : ℕ) : ℤ) from rfl, HahnSeries.ofPowerSeries_apply_coeff,
    PowerSeries.coeff_zero_eq_constantCoeff, map_pow, constantCoeff_jNum_map, one_pow]

theorem coeff_jqModC_pow_of_lt {n : ℕ} {m : ℤ} (hm : m < -(n : ℤ)) : ((jqModC K) ^ n).coeff m = 0 := by
  rw [jqModC_pow, HahnSeries.coeff_single_mul, one_mul]
  exact ofPowerSeries_coeff_of_neg _ (by omega)

theorem coeff_jqModC_neg_one : (jqModC K).coeff (-1 : ℤ) = 1 := by
  simpa using coeff_jqModC_pow_self K 1

theorem algebraMap_laurentSeries_eq_single (c : K) :
    algebraMap K (LaurentSeries K) c = HahnSeries.single 0 c := by
  have h1 : algebraMap K (PowerSeries K) c = PowerSeries.C c := by simp
  rw [HahnSeries.algebraMap_apply', h1, HahnSeries.ofPowerSeries_C]
  rfl

theorem aeval_jqModC_eq_zero {p : Polynomial K} (hp : Polynomial.aeval (jqModC K) p = 0) : p = 0 := by
  by_contra hp0
  set n := p.natDegree with hn
  have hcoeff : (Polynomial.aeval (jqModC K) p).coeff (-(n : ℤ)) = p.coeff n := by
    rw [Polynomial.aeval_def, Polynomial.eval₂_eq_sum_range, HahnSeries.coeff_sum,
      Finset.sum_eq_single n]
    · rw [algebraMap_laurentSeries_eq_single, HahnSeries.coeff_single_zero_mul,
        coeff_jqModC_pow_self, mul_one]
    · intro i hi hin
      have hilt : i < n := lt_of_le_of_ne (Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)) hin
      rw [algebraMap_laurentSeries_eq_single, HahnSeries.coeff_single_zero_mul,
        coeff_jqModC_pow_of_lt, mul_zero]
      omega
    · intro hn'
      exact absurd (Finset.self_mem_range_succ n) hn'
  rw [hp] at hcoeff
  simp only [HahnSeries.coeff_zero] at hcoeff
  exact hp0 (Polynomial.leadingCoeff_eq_zero.mp hcoeff.symm)

theorem transcendental_jqModC : Transcendental K (jqModC K) :=
  transcendental_iff.mpr fun _ hp => aeval_jqModC_eq_zero K hp

theorem jqModC_ne_zero [Nontrivial K] : jqModC K ≠ 0 := by
  intro h
  have h1 : (jqModC K).coeff (-1 : ℤ) = 1 := coeff_jqModC_neg_one K
  rw [h, HahnSeries.coeff_zero] at h1
  exact zero_ne_one h1

theorem order_jqModC [Nontrivial K] : (jqModC K).order = -1 := by
  refine le_antisymm (HahnSeries.order_le_of_coeff_ne_zero ?_) ?_
  · rw [coeff_jqModC_neg_one]
    exact one_ne_zero
  · by_contra hlt
    rw [not_le] at hlt
    refine HahnSeries.coeff_order_eq_zero.not.mpr (jqModC_ne_zero K) ?_
    have h := coeff_jqModC_pow_of_lt K (n := 1) (m := (jqModC K).order)
      (by simpa using hlt)
    simpa using h

theorem qExpand_jqModC_eq_pow (ℓ : ℕ) [Fact ℓ.Prime] [CharP K ℓ] :
    qExpand K ℓ (jqModC K) = (jqModC K) ^ ℓ := by
  rw [jqModC_eq_map_intCast K]
  exact (map_intCast_pow_char_eq_qExpand ℓ _).symm

theorem qExpand_jqNModC_eq_pow (N : ℕ) [NeZero N] (ℓ : ℕ) [Fact ℓ.Prime] [CharP K ℓ] :
    qExpand K ℓ (jqNModC K N) = (jqNModC K N) ^ ℓ := by
  rw [jqNModC, qExpand_qExpand, qExpand_congr (mul_comm ℓ N), ← qExpand_qExpand,
    qExpand_jqModC_eq_pow K ℓ, map_pow]

theorem frobenius_identity_geom (ℓ : ℕ) [Fact ℓ.Prime] [CharP K ℓ] : jqNModC K ℓ = (jqModC K) ^ ℓ := by
  rw [jqNModC]; exact qExpand_jqModC_eq_pow K ℓ

end CharLRows

end ModularCurve
end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_qExpand_jqModC_eq_pow_unconditional.ModularCurve in
theorem solution (K : Type*) [CommRing K] {ℓ : ℕ} [Fact ℓ.Prime] [CharP K ℓ] :
    qExpand K ℓ (jqModC K) = (jqModC K) ^ ℓ :=
  CharLRows.qExpand_jqModC_eq_pow K ℓ

end S_ModularCurve_qExpand_jqModC_eq_pow_unconditional
end P2MW
export P2MW.S_ModularCurve_qExpand_jqModC_eq_pow_unconditional (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.qExpand_jqModC_eq_pow_unconditional (K : Type*) [CommRing K] {ℓ : ℕ} [Fact ℓ.Prime] [CharP K ℓ] :
    qExpand K ℓ (jqModC K) = (jqModC K) ^ ℓ := _root_.P2MW.S_ModularCurve_qExpand_jqModC_eq_pow_unconditional.solution K

end publicSection
