/-
Based on Prove2Me node ModularCurve.hasSum_modularUnitSeries_qParam
(d56465a1-e65d-5b62-b228-0badbdd944c2) by Claude (2026-09-05).

Proof based on Prove2Me submission fa5c4c51-c0ac-56b9-ac7f-8fce506223d4
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ModularUnit
public import Definitions.FLT.Def_ModularForm_HeckeOperator
public import Mathlib.NumberTheory.ModularForms.Discriminant

import Mathlib.NumberTheory.ModularForms.QExpansion
import Mathlib.NumberTheory.ModularForms.LevelOne.Basic
import Mathlib.Analysis.Complex.TaylorSeries
import Theorems.FLT.Thm_ModularCurve_qExpansion_discriminant_eq_map_X_mul_dedekindEtaUnit
import Theorems.FLT.Thm_ModularCurve_hasSum_qParam_mul_laurent
import Theorems.FLT.Thm_ModularCurve_laurent_qParam_coeff_unique
import Definitions.FLT.Def_P2M_Util

/-!
# q-expansion of Δ(τ)/Δ(Nτ) at the cusp ∞

Theorem statement: `ModularCurve.hasSum_modularUnitSeries_qParam`
(`d56465a1-e65d-5b62-b228-0badbdd944c2`), by Claude, 2026-09-05.

Proof: submission `fa5c4c51-c0ac-56b9-ac7f-8fce506223d4`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a positive natural number and let $\tau$ lie in the upper half-plane. Write $u =$
[`ModularCurve.modularUnitSeries N`](def/ModularCurve_ModularUnit.html#L127) for the element $\delta
\cdot (\mathrm{qExpand}_{\mathbb Q,N}\,\delta)^{-1}$ of the field $\mathbb Q((q))$ of formal Laurent
series over $\mathbb Q$, where $\delta =$
[`ModularCurve.deltaSeries`](def/ModularCurve_ModularUnit.html#L107) is $q$ times the power series
`dedekindEtaUnitQ` with its coefficients viewed in $\mathbb Q$, and $\mathrm{qExpand}_{\mathbb Q,N}$
is the substitution $q \mapsto q^N$; thus $u$ is the formal quotient $\Delta(q)/\Delta(q^N)$. The
assertion is that the family indexed by $m \in \mathbb Z$ whose $m$-th term is the complex number
$u_m \, \mathfrak q^m$, with $u_m \in \mathbb Q$ the $m$-th coefficient of $u$ cast into $\mathbb C$
and $\mathfrak q =$ `Function.Periodic.qParam 1 (τ : ℂ)` $= e^{2\pi i \tau}$ (integer powers being
taken in $\mathbb C$), is summable with sum
$$\frac{\Delta(\tau)}{\Delta\big(\mathrm{heckeDiagMatrix}(N) \cdot \tau\big)},$$
where $\Delta$ is Mathlib's discriminant cusp form and $\mathrm{heckeDiagMatrix}(N)$ is the element
$\begin{pmatrix} N & 0 \\ 0 & 1\end{pmatrix}$ of $\mathrm{GL}_2(\mathbb R)$, acting on the upper
half-plane by Möbius transformation, so that the denominator is $\Delta(N\tau)$.

This identifies the formal Laurent series $\Delta(q)/\Delta(q^N)$ with the analytic modular unit
$\tau \mapsto \Delta(\tau)/\Delta(N\tau)$ on $X_0(N)$, Ogg's unit, realised at period $1$ at the
cusp $\infty$; no primality of $N$ is required. It is the bridge between the formal and analytic
descriptions used in the computation of the Fricke involution on this unit and in the descent
placing the relevant functions in $\mathbb Q(j, j_N)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_hasSum_modularUnitSeries_qParam.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_hasSum_modularUnitSeries_qParam

noncomputable section

open UpperHalfPlane Complex Filter Topology Function HahnSeries
open scoped MatrixGroups ModularForm

local notation "𝕢" => Function.Periodic.qParam

namespace ModularCurve
p2m_export "ModularCurve" "dedekindEtaUnitQ deltaSeries isMonicOfOrder_deltaSeries deltaSeriesN isMonicOfOrder_deltaSeriesN modularUnitSeries modularUnitSeries_mul_deltaSeriesN qExpand_coeff_mul qExpand_coeff_of_not_dvd dedekindEtaUnit ofPowerSeries_coeff_of_neg qExpansion_discriminant_eq_map_X_mul_dedekindEtaUnit hasSum_qParam_mul_laurent laurent_qParam_coeff_unique"
p2m_open "ModularCurve"

namespace QexpN

private def ratNRH : ℚ →ₙ+* ℂ := (Rat.castHom ℂ).toNonUnitalRingHom

private def theta (x : LaurentSeries ℚ) : LaurentSeries ℂ := x.map ratNRH

private theorem theta_coeff (x : LaurentSeries ℚ) (m : ℤ) :
    (theta x).coeff m = ((x.coeff m : ℚ) : ℂ) := rfl

private theorem theta_mul (x y : LaurentSeries ℚ) : theta (x * y) = theta x * theta y :=
  HahnSeries.map_mul ratNRH

private def gfun (q : ℂ) : ℂ := ∏' n : ℕ, (1 - q ^ (n + 1)) ^ 24

private lemma differentiableOn_gfun : DifferentiableOn ℂ gfun (Metric.ball (0 : ℂ) 1) :=
  ModularForm.differentiableOn_tprod_one_sub_pow_pow 24

private lemma gfun_ne_zero {q : ℂ} (hq : ‖q‖ < 1) : gfun q ≠ 0 := by
  rw [gfun, (ModularForm.multipliable_one_sub_pow hq).tprod_pow]
  refine pow_ne_zero _ (tprod_one_add_ne_zero_of_summable (f := fun n => -q ^ (n + 1)) ?_ ?_)
  · intro i
    have h1 : ‖q ^ (i + 1)‖ < 1 := by
      rw [norm_pow]; exact pow_lt_one₀ (norm_nonneg _) hq (Nat.succ_ne_zero i)
    intro h
    rw [add_neg_eq_zero] at h
    rw [← h, norm_one] at h1
    exact lt_irrefl _ h1
  · simpa [summable_nat_add_iff 1] using summable_geometric_of_lt_one (norm_nonneg _) hq

private lemma discriminant_eq_qParam_mul_gfun (τ : ℍ) :
    ModularForm.discriminant τ = 𝕢 1 (τ : ℂ) * gfun (𝕢 1 (τ : ℂ)) := by
  rw [ModularForm.discriminant_eq_q_prod, gfun]

private theorem hasSum_single_mul_coe_iff (k : ℤ) (P : PowerSeries ℂ) {q : ℂ} (hq : q ≠ 0) (t : ℂ) :
    HasSum (fun m : ℤ => (HahnSeries.single k (1 : ℂ) * (P : LaurentSeries ℂ)).coeff m * q ^ m) (t * q ^ k) ↔
      HasSum (fun n : ℕ => PowerSeries.coeff n P * q ^ n) t := by
  have hinj : Function.Injective (fun n : ℕ => (n : ℤ) + k) := fun a b hab => by simpa using hab
  rw [← hinj.hasSum_iff]
  · have hfg : (fun m : ℤ => (HahnSeries.single k (1 : ℂ) * (P : LaurentSeries ℂ)).coeff m * q ^ m) ∘
        (fun n : ℕ => (n : ℤ) + k) = fun n : ℕ => (PowerSeries.coeff n P * q ^ n) * q ^ k := by
      funext n
      simp only [Function.comp_apply]
      rw [HahnSeries.coeff_single_mul_add, one_mul, LaurentSeries.coeff_coe_powerSeries, zpow_add₀ hq,
        zpow_natCast]
      ring
    rw [hfg]
    exact hasSum_mul_right_iff (zpow_ne_zero k hq)
  · intro m hm
    have hmk : m - k < 0 := by
      by_contra hge
      push Not at hge
      exact hm ⟨(m - k).toNat, by simp only; omega⟩
    rw [← sub_add_cancel m k, HahnSeries.coeff_single_mul_add, one_mul, PowerSeries.coeff_coe, ite_eq_left hmk,
      zero_mul]

private theorem hasSum_theta_deltaSeries (τ : ℍ) :
    HasSum (fun m : ℤ => (theta deltaSeries).coeff m * 𝕢 1 (τ : ℂ) ^ m)
      (ModularForm.discriminant τ) := by
  have hper : Function.Periodic (ModularForm.discriminant ∘ UpperHalfPlane.ofComplex) 1 :=
    SlashInvariantFormClass.periodic_comp_ofComplex CuspForm.discriminant one_mem_strictPeriods_SL
  have hmdiff := ModularFormClass.holo CuspForm.discriminant
  have hbdd : IsBoundedAtImInfty ModularForm.discriminant :=
    ModularForm.discriminant_isZeroAtImInfty.boundedAtFilter
  have h := hasSum_qExpansion one_pos hper hmdiff hbdd τ
  rw [ModularCurve.qExpansion_discriminant_eq_map_X_mul_dedekindEtaUnit] at h
  have hinj : Function.Injective ((↑) : ℕ → ℤ) := fun a b hab => by exact_mod_cast hab
  rw [← hinj.hasSum_iff]
  · refine h.congr_fun fun n => ?_
    simp only [Function.comp_apply, theta_coeff, smul_eq_mul]
    rcases n with - | k
    · rw [show ((0 : ℕ) : ℤ) = (0 : ℤ) from rfl, deltaSeries, HahnSeries.coeff_single_mul, one_mul,
        ModularCurve.ofPowerSeries_coeff_of_neg _ (by norm_num), PowerSeries.coeff_map,
        PowerSeries.coeff_zero_X_mul]
      norm_num
    · rw [deltaSeries, HahnSeries.coeff_single_mul, one_mul,
        show ((k + 1 : ℕ) : ℤ) - 1 = ((k : ℕ) : ℤ) by push_cast; ring,
        HahnSeries.ofPowerSeries_apply_coeff, dedekindEtaUnitQ, PowerSeries.coeff_map,
        PowerSeries.coeff_map, PowerSeries.coeff_succ_X_mul, zpow_natCast, eq_intCast,
        eq_intCast, Rat.cast_intCast]
  · intro m hm
    have hm' : m < 0 := by
      by_contra hge
      push Not at hge
      exact hm ⟨m.toNat, by simp; omega⟩
    rw [theta_coeff, ModularCurve.isMonicOfOrder_deltaSeries.coeff_of_lt (by omega),
      Rat.cast_zero, zero_mul]

private theorem qParam_heckeDiagMatrix_smul {N : ℕ} (hN : N ≠ 0) (τ : ℍ) :
    𝕢 1 ((ModularForm.heckeDiagMatrix N • τ : ℍ) : ℂ) = 𝕢 1 (τ : ℂ) ^ N := by
  rw [ModularForm.coe_heckeDiagMatrix_smul hN, Periodic.qParam, Periodic.qParam,
    ← Complex.exp_nat_mul]
  congr 1
  push_cast
  ring

private theorem hasSum_theta_deltaSeriesN (N : ℕ) [NeZero N] (τ : ℍ) :
    HasSum (fun m : ℤ => (theta (deltaSeriesN N)).coeff m * 𝕢 1 (τ : ℂ) ^ m)
      (ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)) := by
  have hN : N ≠ 0 := NeZero.ne N
  have hNZ : ((N : ℕ) : ℤ) ≠ 0 := by exact_mod_cast hN
  have h := hasSum_theta_deltaSeries (ModularForm.heckeDiagMatrix N • τ)
  have e : 𝕢 1 ((ModularForm.heckeDiagMatrix N • τ : ℍ) : ℂ) = 𝕢 1 (τ : ℂ) ^ ((N : ℕ) : ℤ) := by
    rw [qParam_heckeDiagMatrix_smul hN, zpow_natCast]
  have hinj : Function.Injective (fun m : ℤ => ((N : ℕ) : ℤ) * m) := mul_right_injective₀ hNZ
  rw [← hinj.hasSum_iff]
  · have hfg : (fun m : ℤ => (theta (deltaSeriesN N)).coeff m * 𝕢 1 (τ : ℂ) ^ m) ∘
        (fun m : ℤ => ((N : ℕ) : ℤ) * m)
        = fun m : ℤ => (theta deltaSeries).coeff m * 𝕢 1 ((ModularForm.heckeDiagMatrix N • τ : ℍ) : ℂ) ^ m := by
      funext m
      simp only [Function.comp_apply, theta_coeff, deltaSeriesN]
      rw [ModularCurve.qExpand_coeff_mul, e, ← zpow_mul]
    rw [hfg]
    exact h
  · intro m hm
    rw [theta_coeff, deltaSeriesN,
      ModularCurve.qExpand_coeff_of_not_dvd N deltaSeries (fun ⟨c, hc⟩ => hm ⟨c, hc.symm⟩),
      Rat.cast_zero, zero_mul]

private theorem theta_deltaSeriesN_ne_zero (N : ℕ) [NeZero N] : theta (deltaSeriesN N) ≠ 0 := by
  have h1 : (theta (deltaSeriesN N)).coeff ((N : ℕ) : ℤ) = 1 := by
    rw [theta_coeff, (ModularCurve.isMonicOfOrder_deltaSeriesN N).coeff_self, Rat.cast_one]
  exact HahnSeries.ne_zero_of_coeff_ne_zero (h1 ▸ one_ne_zero)

private theorem theta_deltaSeries_ne_zero : theta deltaSeries ≠ 0 := by
  have h1 : (theta deltaSeries).coeff (1 : ℤ) = 1 := by
    rw [theta_coeff, ModularCurve.isMonicOfOrder_deltaSeries.coeff_self, Rat.cast_one]
  exact HahnSeries.ne_zero_of_coeff_ne_zero (h1 ▸ one_ne_zero)

private def phiFun (N : ℕ) : ℂ → ℂ := fun w => gfun w / gfun (w ^ N)

private def psiFun (N : ℕ) : ℂ → ℂ := fun w => gfun (w ^ N) / gfun w

private lemma pow_mem_ball {N : ℕ} [NeZero N] {w : ℂ} (hw : w ∈ Metric.ball (0 : ℂ) 1) :
    w ^ N ∈ Metric.ball (0 : ℂ) 1 := by
  rw [Metric.mem_ball, dist_zero_right] at hw ⊢
  rw [norm_pow]
  exact pow_lt_one₀ (norm_nonneg _) hw (NeZero.ne N)

private lemma differentiableOn_gfun_pow (N : ℕ) [NeZero N] :
    DifferentiableOn ℂ (fun w : ℂ => gfun (w ^ N)) (Metric.ball (0 : ℂ) 1) :=
  differentiableOn_gfun.comp ((differentiable_pow N).differentiableOn)
    fun _ hw => pow_mem_ball hw

private lemma differentiableOn_phiFun (N : ℕ) [NeZero N] :
    DifferentiableOn ℂ (phiFun N) (Metric.ball (0 : ℂ) 1) := by
  refine DifferentiableOn.div differentiableOn_gfun (differentiableOn_gfun_pow N)
    fun w hw => gfun_ne_zero ?_
  have := pow_mem_ball (N := N) hw
  rwa [Metric.mem_ball, dist_zero_right] at this

private lemma differentiableOn_psiFun (N : ℕ) [NeZero N] :
    DifferentiableOn ℂ (psiFun N) (Metric.ball (0 : ℂ) 1) := by
  refine DifferentiableOn.div (differentiableOn_gfun_pow N) differentiableOn_gfun
    fun w hw => gfun_ne_zero ?_
  rwa [Metric.mem_ball, dist_zero_right] at hw

private def taylorCoeff (f : ℂ → ℂ) (n : ℕ) : ℂ := ((n.factorial : ℂ))⁻¹ * iteratedDeriv n f 0

private lemma hasSum_taylorCoeff {f : ℂ → ℂ}
    (hf : DifferentiableOn ℂ f (Metric.ball (0 : ℂ) 1)) {q : ℂ} (hq : ‖q‖ < 1) :
    HasSum (fun n : ℕ => taylorCoeff f n * q ^ n) (f q) := by
  have h := Complex.hasSum_taylorSeries_on_ball hf
    (show q ∈ Metric.ball (0 : ℂ) 1 by rwa [Metric.mem_ball, dist_zero_right])
  refine h.congr_fun fun n => ?_
  rw [taylorCoeff, sub_zero, smul_eq_mul, smul_eq_mul]
  ring

private theorem hasSum_modularUnit (N : ℕ) [NeZero N] (τ₀ : ℍ) :
    HasSum (fun m : ℤ => (((ModularCurve.modularUnitSeries N).coeff m : ℚ) : ℂ)
        * 𝕢 1 (τ₀ : ℂ) ^ m)
      (ModularForm.discriminant τ₀
        / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ₀)) := by
  have hq0 : ∀ τ : ℍ, 𝕢 1 (τ : ℂ) ≠ 0 := fun τ => Periodic.qParam_ne_zero _
  have hqlt : ∀ τ : ℍ, ‖𝕢 1 (τ : ℂ)‖ < 1 := fun τ => by
    exact_mod_cast UpperHalfPlane.norm_qParam_lt_one 1 τ
  set A : LaurentSeries ℂ := HahnSeries.single ((1 : ℤ) - N) 1
    * ((PowerSeries.mk (taylorCoeff (phiFun N)) : PowerSeries ℂ) : LaurentSeries ℂ) with hA
  have hval : ∀ τ : ℍ, ModularForm.discriminant τ
      / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)
      = phiFun N (𝕢 1 (τ : ℂ)) * 𝕢 1 (τ : ℂ) ^ ((1 : ℤ) - N) := by
    intro τ
    have hq := hq0 τ
    have hgq : gfun (𝕢 1 (τ : ℂ)) ≠ 0 := gfun_ne_zero (hqlt τ)
    have hgN : gfun (𝕢 1 (τ : ℂ) ^ N) ≠ 0 := gfun_ne_zero (by
      rw [norm_pow]; exact pow_lt_one₀ (norm_nonneg _) (hqlt τ) (NeZero.ne N))
    have hqN : 𝕢 1 (τ : ℂ) ^ N ≠ 0 := pow_ne_zero _ hq
    rw [discriminant_eq_qParam_mul_gfun τ,
      discriminant_eq_qParam_mul_gfun (ModularForm.heckeDiagMatrix N • τ),
      qParam_heckeDiagMatrix_smul (NeZero.ne N), phiFun, zpow_sub₀ hq, zpow_one, zpow_natCast]
    field_simp
  have hAsum : ∀ τ : ℍ, HasSum (fun m : ℤ => A.coeff m * 𝕢 1 (τ : ℂ) ^ m)
      (ModularForm.discriminant τ
        / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)) := by
    intro τ
    rw [hval τ, hA]
    refine (hasSum_single_mul_coe_iff ((1 : ℤ) - N) _ (hq0 τ) _).mpr ?_
    refine (hasSum_taylorCoeff (differentiableOn_phiFun N) (hqlt τ)).congr_fun fun n => ?_
    rw [PowerSeries.coeff_mk]
  have hprod : ∀ τ : ℍ, HasSum
      (fun m : ℤ => (A * theta (deltaSeriesN N)).coeff m * 𝕢 1 (τ : ℂ) ^ m)
      (ModularForm.discriminant τ) := by
    intro τ
    have h := ModularCurve.hasSum_qParam_mul_laurent 1 one_pos A (theta (deltaSeriesN N))
      (fun τ => ModularForm.discriminant τ
        / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ))
      (fun τ => ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ))
      hAsum (hasSum_theta_deltaSeriesN N) τ
    have h2 : HasSum (fun m : ℤ => (A * theta (deltaSeriesN N)).coeff m * 𝕢 1 (τ : ℂ) ^ m)
        (ModularForm.discriminant τ
            / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)
          * ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)) := h
    rwa [div_mul_cancel₀ _ (ModularForm.discriminant_ne_zero _)] at h2
  have huniq : A * theta (deltaSeriesN N) = theta deltaSeries :=
    ModularCurve.laurent_qParam_coeff_unique 1 one_pos ModularForm.discriminant _ _ hprod
      hasSum_theta_deltaSeries
  have hTheta : theta (ModularCurve.modularUnitSeries N) * theta (deltaSeriesN N)
      = theta deltaSeries := by
    rw [← theta_mul, ModularCurve.modularUnitSeries_mul_deltaSeriesN]
  have hAu : A = theta (ModularCurve.modularUnitSeries N) :=
    mul_right_cancel₀ (theta_deltaSeriesN_ne_zero N) (huniq.trans hTheta.symm)
  have h := hAsum τ₀
  rw [hAu] at h
  refine h.congr_fun fun m => ?_
  rw [theta_coeff]

end QexpN

end ModularCurve

end

theorem solution (N : ℕ) [NeZero N] (τ : UpperHalfPlane) : HasSum (fun m : ℤ => (((ModularCurve.modularUnitSeries N).coeff m : ℚ) : ℂ) * Function.Periodic.qParam 1 (τ : ℂ) ^ m) (ModularForm.discriminant τ / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)) :=
  ModularCurve.QexpN.hasSum_modularUnit N τ

end S_ModularCurve_hasSum_modularUnitSeries_qParam
end P2MW
export P2MW.S_ModularCurve_hasSum_modularUnitSeries_qParam (solution)

end privateSection

public section publicSection

theorem ModularCurve.hasSum_modularUnitSeries_qParam (N : ℕ) [NeZero N] (τ : UpperHalfPlane) : HasSum (fun m : ℤ => (((ModularCurve.modularUnitSeries N).coeff m : ℚ) : ℂ) * Function.Periodic.qParam 1 (τ : ℂ) ^ m) (ModularForm.discriminant τ / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ)) := _root_.P2MW.S_ModularCurve_hasSum_modularUnitSeries_qParam.solution N τ

end publicSection
