/-
Based on Prove2Me node WeierstrassCurve.Affine.Point.some_zero_add_self_eq_neg_of_a6_model
(d439f6e7-8f94-5d50-843c-e6b0444e5bf0) by Claude (2026-09-05).

Proof based on Prove2Me submission 8bc78b3a-8f54-5ff0-add9-07be06f2f223
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point

import Mathlib.RingTheory.SimpleRing.Principal
import Definitions.FLT.Def_P2M_Util

/-!
# The points (0,y) on y²=x³+B are flexes

Theorem statement: `WeierstrassCurve.Affine.Point.some_zero_add_self_eq_neg_of_a6_model`
(`d439f6e7-8f94-5d50-843c-e6b0444e5bf0`), by Claude, 2026-09-05.

Proof: submission `8bc78b3a-8f54-5ff0-add9-07be06f2f223`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $k$ be a field with decidable equality, let $B \in k$, and assume $2 \neq 0$ in $k$. Let $y \in
k$ be nonzero, and suppose $(0,y)$ is a nonsingular point of the affine Weierstrass curve with
coefficients $a_1 = a_2 = a_3 = a_4 = 0$ and $a_6 = B$, i.e. of $y^2 = x^3 + B$; here `Nonsingular`
means that the Weierstrass equation holds at $(0,y)$ and that the two partial derivatives of the
defining polynomial do not both vanish there. Writing $P$ for the corresponding element `Point.some
0 y h` of the group of points of this affine curve (rational points together with the point at
infinity), the assertion is $P + P = -P$ in that group. Equivalently, $P$ is a point of order
dividing three, although the statement is phrased purely as the displayed identity between the
double of $P$ and the negative of $P$, not as a torsion statement.

This is the classical fact that the points with $x = 0$ on a curve $y^2 = x^3 + B$ are inflection
points, hence three-torsion: the tangent there is horizontal and meets the curve at the same point
again. It is used in the analysis of the three-torsion and of the action of the cube-root-of-unity
automorphism on curves with $j = 0$, in particular by
[`WeierstrassCurve.exists_j_eq_zero_torsion_basis_heq_vcInvFun_of_order_three`](thm.html#WeierstrassCurve.exists_j_eq_zero_torsion_basis_heq_vcInvFun_of_order_three)
and the two counting statements
[`WeierstrassCurve.natCard_isAddCyclic_addSubgroup_card_eq_fixed_vcInvFun_eq_nuThree`](thm.html#WeierstrassCurve.natCard_isAddCyclic_addSubgroup_card_eq_fixed_vcInvFun_eq_nuThree)
and its variant.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_Point_some_zero_add_self_eq_neg_of_a6_model.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_Point_some_zero_add_self_eq_neg_of_a6_model

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point

theorem ws13_some_congr' {k : Type*} [Field k] {V : Affine k} {x₁ x₂ y₁ y₂ : k}
    {h₁ : V.Nonsingular x₁ y₁} {h₂ : V.Nonsingular x₂ y₂} (hx : x₁ = x₂) (hy : y₁ = y₂) :
    (Point.some x₁ y₁ h₁ : V.Point) = Point.some x₂ y₂ h₂ := by
  subst hx; subst hy; rfl

theorem solution
    {k : Type*} [Field k] [DecidableEq k] (B : k) (h2 : (2 : k) ≠ 0) {y : k} (hy0 : y ≠ 0)
    (h : (⟨0, 0, 0, 0, B⟩ : WeierstrassCurve k).toAffine.Nonsingular 0 y) :
    (WeierstrassCurve.Affine.Point.some 0 y h : (⟨0, 0, 0, 0, B⟩ : WeierstrassCurve k).toAffine.Point)
      + WeierstrassCurve.Affine.Point.some 0 y h
      = -(WeierstrassCurve.Affine.Point.some 0 y h) := by
  have hyne : y ≠ Affine.negY (⟨0, 0, 0, 0, B⟩ : WeierstrassCurve k) 0 y := by
    simp only [Affine.negY]
    intro heq
    have : (2 : k) * y = 0 := by linear_combination heq
    rcases mul_eq_zero.mp this with h' | h'
    · exact h2 h'
    · exact hy0 h'
  rw [Point.add_of_Y_ne hyne, Point.neg_some]
  refine ws13_some_congr' ?_ ?_
  · rw [slope_of_Y_ne rfl hyne]
    simp only [Affine.addX, Affine.negY]
    ring
  · rw [slope_of_Y_ne rfl hyne]
    simp only [Affine.addY, Affine.negY, Affine.negAddY, Affine.addX]
    ring

end S_WeierstrassCurve_Affine_Point_some_zero_add_self_eq_neg_of_a6_model
end P2MW
export P2MW.S_WeierstrassCurve_Affine_Point_some_zero_add_self_eq_neg_of_a6_model (solution)

end privateSection

public section publicSection

theorem WeierstrassCurve.Affine.Point.some_zero_add_self_eq_neg_of_a6_model
    {k : Type*} [Field k] [DecidableEq k] (B : k) (h2 : (2 : k) ≠ 0) {y : k} (hy0 : y ≠ 0)
    (h : (⟨0, 0, 0, 0, B⟩ : WeierstrassCurve k).toAffine.Nonsingular 0 y) :
    (WeierstrassCurve.Affine.Point.some 0 y h : (⟨0, 0, 0, 0, B⟩ : WeierstrassCurve k).toAffine.Point)
      + WeierstrassCurve.Affine.Point.some 0 y h
      = -(WeierstrassCurve.Affine.Point.some 0 y h) := _root_.P2MW.S_WeierstrassCurve_Affine_Point_some_zero_add_self_eq_neg_of_a6_model.solution B h2 hy0 h

end publicSection
