/-
Based on Prove2Me node ModularCurve.dedekindPsi_of_squarefree
(7d026fe4-23a4-5b1a-9f86-5ecdcf6436bc) by Claude (2026-09-05).

Proof based on Prove2Me submission a9fedc75-775a-59ea-9cd9-0296dc065c0d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0

import Theorems.FLT.Thm_ModularCurve_dedekindPsi_mul_of_coprime
import Theorems.FLT.Thm_ModularCurve_dedekindPsi_prime
import Mathlib.Data.Nat.Factorization.Induction
import Definitions.FLT.Def_P2M_Util

/-!
# Dedekind ψ at squarefree level

Theorem statement: `ModularCurve.dedekindPsi_of_squarefree`
(`7d026fe4-23a4-5b1a-9f86-5ecdcf6436bc`), by Claude, 2026-09-05.

Proof: submission `a9fedc75-775a-59ea-9cd9-0296dc065c0d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number which is squarefree. Here $\psi(N)$ is defined as the natural-number sum
$\sum_{d} N/d$, taken over those $d$ in the finset of divisors of $N$ which are themselves
squarefree, the quotient being natural division (for $N = 0$ the divisor finset is empty, so
$\psi(0) = 0$; squarefreeness of $N$ in any case forces $N \neq 0$). The assertion is the equality
of natural numbers $$\psi(N) = \prod_{p \in \mathrm{primeFactors}(N)} (p + 1),$$ the product running
over the finset of prime factors of $N$. In particular the right-hand side is the empty product $1$
when $N = 1$, matching $\psi(1) = 1$. Thus for squarefree $N$ the sum over squarefree divisors
collapses to the familiar product formula $N \prod_{p \mid N} (1 + 1/p)$, stated here in the
integral form $\prod_{p \mid N}(p+1)$.

The function $\psi$ is Dedekind's psi function, the degree of the modular equation of level $N$,
i.e. the expected degree of the function field of $X_0(N)$ over $\mathbb{Q}(j)$. This closed formula
at squarefree levels is used by the statements on the degree of $\mathbb{Q}(j)(j_N)$ over
$\mathbb{Q}(j)$ and on generation of the function field at squarefree level, such as
[`ModularCurve.finrank_adjoin_jqN_eq_of_squarefree`](thm.html#ModularCurve.finrank_adjoin_jqN_eq_of_squarefree),
[`ModularCurve.functionFieldGeneration_of_squarefree`](thm.html#ModularCurve.functionFieldGeneration_of_squarefree)
and [`ModularCurve.relfinrank_adjoin_primes`](thm.html#ModularCurve.relfinrank_adjoin_primes).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_dedekindPsi_of_squarefree.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_dedekindPsi_of_squarefree

namespace ModularCurve
p2m_export "ModularCurve" "dedekindPsi dedekindPsi_one dedekindPsi_mul_of_coprime dedekindPsi_prime"
namespace W1
p2m_open "ModularCurve"

private theorem psi_prime_pow_aux {p : ℕ} (hp : p.Prime) (k : ℕ) :
    ModularCurve.dedekindPsi (p ^ (k + 1)) = p ^ (k + 1) + p ^ k := by
  unfold ModularCurve.dedekindPsi
  have hfil : Finset.filter (fun d => Squarefree d) (p ^ (k + 1)).divisors = {1, p} := by
    ext x
    simp only [Finset.mem_filter, Nat.mem_divisors_prime_pow hp, Finset.mem_insert,
      Finset.mem_singleton]
    constructor
    · rintro ⟨⟨j, -, rfl⟩, hsq⟩
      rcases Nat.eq_zero_or_pos j with rfl | hj0
      · exact Or.inl (pow_zero p)
      · have hj1 : j = 1 := ((Nat.squarefree_pow_iff hp.ne_one hj0.ne').mp hsq).2
        subst hj1
        exact Or.inr (pow_one p)
    · rintro (rfl | rfl)
      · exact ⟨⟨0, Nat.zero_le _, (pow_zero p).symm⟩, squarefree_one⟩
      · exact ⟨⟨1, by omega, (pow_one _).symm⟩, hp.prime.squarefree⟩
  rw [hfil, Finset.sum_pair hp.one_lt.ne, Nat.div_one, pow_succ,
    Nat.mul_div_cancel _ hp.pos]

end ModularCurve.W1

namespace ModularCurve
p2m_export "ModularCurve" "dedekindPsi dedekindPsi_one dedekindPsi_mul_of_coprime dedekindPsi_prime"
end ModularCurve
p2m_open_scoped "ModularCurve" in
private theorem ModularCurve.dedekindPsi_prime_pow {p : ℕ} (hp : p.Prime) (k : ℕ) :
    dedekindPsi (p ^ (k + 1)) = (p + 1) * p ^ k := by
  rw [ModularCurve.W1.psi_prime_pow_aux hp k, Nat.add_mul, Nat.one_mul, ← pow_succ']

p2m_open_scoped "ModularCurve" in
private theorem ModularCurve.dedekindPsi_of_squarefree {N : ℕ} (hN : Squarefree N) :
    dedekindPsi N = ∏ p ∈ N.primeFactors, (p + 1) := by
  revert hN
  induction N using Nat.recOnPosPrimePosCoprime with
  | prime_pow p n hp hn =>
    intro hsq
    have hn1 : n = 1 := ((Nat.squarefree_pow_iff hp.ne_one hn.ne').mp hsq).2
    subst hn1
    rw [pow_one, ModularCurve.dedekindPsi_prime hp, hp.primeFactors, Finset.prod_singleton]
  | zero => exact fun h => absurd h not_squarefree_zero
  | one =>
    intro _
    rw [ModularCurve.dedekindPsi_one, Nat.primeFactors_one, Finset.prod_empty]
  | coprime a b ha hb hab iha ihb =>
    intro hsq
    obtain ⟨-, hsa, hsb⟩ := Nat.squarefree_mul_iff.mp hsq
    rw [ModularCurve.dedekindPsi_mul_of_coprime a b hab,
      Nat.primeFactors_mul (by omega : a ≠ 0) (by omega : b ≠ 0),
      Finset.prod_union hab.disjoint_primeFactors, iha hsa, ihb hsb]

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_dedekindPsi_of_squarefree.ModularCurve in

theorem solution {N : ℕ} (hN : Squarefree N) : dedekindPsi N = ∏ p ∈ N.primeFactors, (p + 1) :=
  ModularCurve.dedekindPsi_of_squarefree hN

end S_ModularCurve_dedekindPsi_of_squarefree
end P2MW
export P2MW.S_ModularCurve_dedekindPsi_of_squarefree (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.dedekindPsi_of_squarefree {N : ℕ} (hN : Squarefree N) : dedekindPsi N = ∏ p ∈ N.primeFactors, (p + 1) := _root_.P2MW.S_ModularCurve_dedekindPsi_of_squarefree.solution hN

end publicSection
