/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.exists_forall_ne_ofHeightOneSpectrum
(5e0bdace-46ac-5793-8044-fe6a2fce8738) by Claude (2026-09-05).

Proof based on Prove2Me submission 5addb35a-f141-57bc-abe6-0203591829a6
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.RatFunc.Basic
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Mathlib.NumberTheory.RatFunc.Ostrowski
import Mathlib.RingTheory.DedekindDomain.Factorization
import Definitions.FLT.Def_P2M_Util

/-!
# Existence of a place of K(t)/K that is not a finite place

Theorem statement: `AlgebraicCurve.RationalFunctionField.exists_forall_ne_ofHeightOneSpectrum`
(`5e0bdace-46ac-5793-8044-fe6a2fce8738`), by Claude, 2026-09-05.

Proof: submission `5addb35a-f141-57bc-abe6-0203591829a6`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $\mathrm{RatFunc}\,K$ be the rational function field in one variable over
$K$. A `Place K (RatFunc K)` consists of a valuation subring $\mathcal{O}$ of $\mathrm{RatFunc}\,K$
such that the image of every element of $K$ under the structure map $K \to \mathrm{RatFunc}\,K$ lies
in $\mathcal{O}$, such that $\mathcal{O} \neq \top$, and such that $\mathcal{O}$ is a principal
ideal ring; for a height-one prime $w$ of the polynomial ring $K[X]$, the place
`Place.ofHeightOneSpectrum w` is the one whose valuation subring is the valuation subring of the
$w$-adic valuation of $\mathrm{RatFunc}\,K$ (regarded as the fraction field of $K[X]$), the three
defining conditions holding because $w$-adic valuations are $\le 1$ on polynomials, are nontrivial,
and have principal-ideal valuation subrings. The theorem asserts: there exists a place $v$ of $K(t)$
over $K$ in this sense such that for every height-one prime $w$ of $K[X]$ one has $v \neq$
`Place.ofHeightOneSpectrum w`. No hypotheses beyond $K$ being a field are imposed.

This is the existence half of the classification of the places of the projective line: besides the
finite places, attached to the height-one primes of $K[X]$, there is the place at infinity. It is
used in the development of places and orders on a rational function field, for instance in the
results on elements with a pole at some place, on elements regular at every place, and on degrees of
divisors of rational functions.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_exists_forall_ne_ofHeightOneSpectrum.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_exists_forall_ne_ofHeightOneSpectrum

noncomputable section

open IsDedekindDomain WithZero IsLocalRing
open scoped Polynomial

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place Place.ofHeightOneSpectrum Place.ofHeightOneSpectrum_toValuationSubring Place.toValuationSubring"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ext heightOneSpectrum adicValuation adicValuation_ne_zero ord ofHeightOneSpectrum ofHeightOneSpectrum_toValuationSubring ne_top' algebraMap_mem' toValuationSubring isPrincipalIdealRing'"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

private theorem _root_.AlgebraicCurve.Place.adicValuation_valuationSubring' :
    v.adicValuation.valuationSubring = v.toValuationSubring := by
  ext x
  rw [Valuation.mem_valuationSubring_iff]
  constructor
  · intro hx
    obtain ⟨a, rfl⟩ := IsDiscreteValuationRing.exists_lift_of_le_one hx
    exact a.2
  · intro hx
    exact v.heightOneSpectrum.valuation_le_one (⟨x, hx⟩ : v.toValuationSubring)

p2m_export "AlgebraicCurve.Place" "adicValuation_valuationSubring'"
private theorem _root_.AlgebraicCurve.Place.mem_iff_adicValuation_le_one' {f : F} :
    f ∈ v.toValuationSubring ↔ v.adicValuation f ≤ 1 := by
  rw [← v.adicValuation_valuationSubring']
  exact Valuation.mem_valuationSubring_iff _ _

p2m_export "AlgebraicCurve.Place" "mem_iff_adicValuation_le_one'"
private theorem adicValuation_isRankOneDiscrete' : v.adicValuation.IsRankOneDiscrete :=
  IsDiscreteValuationRing.isRankOneDiscrete v.toValuationSubring F

private theorem adicValuation_isTrivialOn' : v.adicValuation.IsTrivialOn K :=
  Valuation.IsTrivialOn.of_le_one v.adicValuation fun a =>
    v.mem_iff_adicValuation_le_one'.mp (v.algebraMap_mem' a)

private theorem _root_.AlgebraicCurve.Place.isEquiv_adicValuation_of_valuationSubring_eq' {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] {w : Valuation F Γ}
    (h : w.valuationSubring = v.toValuationSubring) : w.IsEquiv v.adicValuation :=
  (Valuation.isEquiv_iff_valuationSubring _ _).mpr
    (h.trans v.adicValuation_valuationSubring'.symm)

p2m_export "AlgebraicCurve.Place" "isEquiv_adicValuation_of_valuationSubring_eq'"
private theorem ord_eq_zero_iff_adicValuation_eq_one' {f : F} (hf : f ≠ 0) :
    v.ord f = 0 ↔ v.adicValuation f = 1 := by
  simp only [ord, neg_eq_zero]
  constructor
  · intro h
    have h2 := exp_log (v.adicValuation_ne_zero hf)
    rw [h, exp_zero] at h2
    exact h2.symm
  · intro h
    rw [h, log_one]

section OfHeightOneSpectrum

variable {R : Type*} [CommRing R] [IsDedekindDomain R] [Algebra R F] [IsFractionRing R F]
  [Algebra K R] [IsScalarTower K R F]

private theorem isEquiv_adicValuation_ofHeightOneSpectrum' (w : HeightOneSpectrum R) :
    (w.valuation F).IsEquiv (ofHeightOneSpectrum (K := K) w).adicValuation :=
  (ofHeightOneSpectrum (K := K) w).isEquiv_adicValuation_of_valuationSubring_eq' rfl

end OfHeightOneSpectrum

end Place

namespace RationalFunctionField

variable (K : Type*) [Field K]

section PlaceInfty

variable [DecidableEq (RatFunc K)]

private theorem nontrivial_valueGroup_inftyValuation :
    Nontrivial (MonoidWithZeroHom.valueGroup (.ofClass (RatFunc.inftyValuation K))) := by
  rw [Subgroup.nontrivial_iff_exists_ne_one]
  refine ⟨Units.mk0 (RatFunc.inftyValuation K RatFunc.X)
    (by rw [RatFunc.inftyValuation.X]; exact exp_ne_zero), ?_, ?_⟩
  · exact MonoidWithZeroHom.mem_valueGroup _ ⟨RatFunc.X, rfl⟩
  · rw [ne_eq, Units.ext_iff, Units.val_mk0, Units.val_one, RatFunc.inftyValuation.X]
    simp

private def placeInfty' : Place K (RatFunc K) where
  toValuationSubring := (RatFunc.inftyValuation K).valuationSubring
  algebraMap_mem' a := by
    rw [Valuation.mem_valuationSubring_iff]
    exact Valuation.IsTrivialOn.valuation_algebraMap_le_one (v := RatFunc.inftyValuation K) a
  ne_top' := by
    have := nontrivial_valueGroup_inftyValuation K
    simp only [ne_eq, Valuation.valuationSubring_eq_top_iff, not_not]
    infer_instance
  isPrincipalIdealRing' :=
    haveI := nontrivial_valueGroup_inftyValuation K
    (Valuation.valuationSubring_isDiscreteValuationRing
      (RatFunc.inftyValuation K)).toIsPrincipalIdealRing

private theorem placeInfty'_ne_ofHeightOneSpectrum (w : HeightOneSpectrum K[X]) :
    placeInfty' K ≠ Place.ofHeightOneSpectrum w := by
  intro h
  refine RatFunc.adicValuation_not_isEquiv_infty_valuation w
    ((Valuation.isEquiv_iff_valuationSubring _ _).mpr ?_)
  have h2 := congrArg Place.toValuationSubring h
  rw [Place.ofHeightOneSpectrum_toValuationSubring] at h2
  exact h2.symm

end PlaceInfty

variable {K}

theorem rowMain :
    ∃ v : Place K (RatFunc K), ∀ w : HeightOneSpectrum K[X], v ≠ Place.ofHeightOneSpectrum w := by
  classical
  exact ⟨placeInfty' K, placeInfty'_ne_ofHeightOneSpectrum K⟩

end RationalFunctionField

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_exists_forall_ne_ofHeightOneSpectrum.AlgebraicCurve in
theorem solution {K : Type*} [Field K] :
    ∃ v : Place K (RatFunc K), ∀ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v ≠ Place.ofHeightOneSpectrum w :=
  AlgebraicCurve.RationalFunctionField.rowMain

end S_AlgebraicCurve_RationalFunctionField_exists_forall_ne_ofHeightOneSpectrum
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_exists_forall_ne_ofHeightOneSpectrum (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.RationalFunctionField.exists_forall_ne_ofHeightOneSpectrum {K : Type*} [Field K] : ∃ v : Place K (RatFunc K), ∀ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v ≠ Place.ofHeightOneSpectrum w := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_exists_forall_ne_ofHeightOneSpectrum.solution

end publicSection
