/-
Based on Prove2Me node ModularCurve.TatePoint.fullKernelIsRootAt
(23ca53b5-f2e7-5cd2-8741-b29b81da83dd) by Claude (2026-09-05).

Proof based on Prove2Me submission 27b7bf19-a294-502e-95d7-4a5853cff1d7
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_CycSubRootBridgeN

import Definitions.FLT.Def_Isogeny_ConditionalCurrency
import Definitions.FLT.Def_WeierstrassCurve_GenusOnePlaceGateCentred
import Definitions.FLT.Def_WeierstrassCurve_FullKernelQuotient
import Definitions.FLT.Def_ModularCurve_X0
import Theorems.FLT.Thm_WeierstrassCurve_Affine_eval_modularPolynomial_map_j_eq_zero_of_isAddCyclic_ker_pointMapOfPushforward
import Theorems.FLT.Thm_WeierstrassCurve_Affine_exists_genusOnePlaceGate_isCentred_abelTheorem
import Theorems.FLT.Thm_WeierstrassCurve_exists_functionFieldHom_fullKernelQuotient_pointMapOfPushforward_ker_eq_zmultiples
import Theorems.FLT.Thm_WeierstrassCurve_Affine_hasPrincipalDivisors_of_isAlgClosed
import Theorems.FLT.Thm_AlgebraicCurve_normFormulaAlong
import Theorems.FLT.Thm_AlgebraicCurve_separableAlong_of_charZero
import Theorems.FLT.Thm_ModularCurve_TatePoint_fullKernelIsRootAt_of_odd
import Theorems.FLT.Thm_ModularCurve_TatePoint_fullKernelDiscAt_of_odd
import Definitions.FLT.Def_P2M_Util

/-!
# Root property of the full-kernel quotient at every level

Theorem statement: `ModularCurve.TatePoint.fullKernelIsRootAt`
(`23ca53b5-f2e7-5cd2-8741-b29b81da83dd`), by Claude, 2026-09-05.

Proof: submission `27b7bf19-a294-502e-95d7-4a5853cff1d7`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a nonzero natural number. The assertion is the predicate `FullKernelIsRootAt N`, which
says the following. Write $H$ for the field of Hahn series with rational exponents and coefficients
in an algebraic closure of $\mathbb{Q}$. For every Weierstrass curve $W$ over $H$ that is elliptic,
every point $Q$ of the associated affine curve whose additive order is exactly $N$, and under the
hypothesis $h\Delta$ that the discriminant of `W.fullKernelQuotient Q N` is nonzero — so that this
curve is itself elliptic, the relevant instance being produced from $h\Delta$ — and for every datum
`data : ModularCurve.ModularPolynomialData N`, consisting of a polynomial $\Phi \in
\mathbb{Z}[X][Y]$ that is monic, of degree $\psi(N)$ (Dedekind's $\psi$) in $Y$, and satisfies
$\Phi(j(q), j(q^N)) = 0$ as a $q$-expansion identity: the one-variable polynomial over $H$ obtained
from $\Phi$ by applying to each coefficient the evaluation of integer polynomials at $j(W)$ has $j$
of `W.fullKernelQuotient Q N` as a root. Here `fullKernelQuotient` is the Vélu quotient formed from
the sums $\sum G_x(P)$ and $\sum (x_P G_x(P) - y_P G_y(P))$ over the set `W.oddOrderSummingSet Q (N
- 1)`.

This is the classical statement that the modular polynomial of level $N$ vanishes at the pair
$(j(E), j(E/C))$ for $C$ the cyclic subgroup of order $N$ generated by a point, in the form needed
over the Hahn-series field used for the Tate-curve analysis, with the quotient given by Vélu's
explicit formulae for the full kernel. It is one of the hypotheses entering the level-$N$ dictionary
between roots of the modular polynomial and cyclic subgroups of order $N$, and is used by
[`ModularCurve.ModularPolynomialData.fibrePoly_j_eq_prod_fullKernelQuotient_j_of_transcendental_of_charZero`](thm.html#ModularCurve.ModularPolynomialData.fibrePoly_j_eq_prod_fullKernelQuotient_j_of_transcendental_of_charZero)
and by
[`ModularCurve.exists_elliptic_cycSub_orbitMap`](thm.html#ModularCurve.exists_elliptic_cycSub_orbitMap).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_TatePoint_fullKernelIsRootAt.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_TatePoint_fullKernelIsRootAt
p2m_attr_erase "simp" "WeierstrassCurve.veluPointMap2_zero"

open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve

noncomputable section

namespace ModularCurve
p2m_export "ModularCurve" "TatePoint.FullKernelIsRootAt"
namespace TatePoint
p2m_export "ModularCurve.TatePoint" "FullKernelIsRootAt FullKernelDiscAt isAlgClosed_H charZero_H H fullKernelIsRootAt_of_odd fullKernelDiscAt_of_odd"
p2m_open "ModularCurve.TatePoint ModularCurve"

attribute [local instance] isAlgClosed_H charZero_H

local notation "H" => HahnSeries ℚ (AlgebraicClosure ℚ)

theorem fullKernelIsRootAt_of_tower
    (N : ℕ) [NeZero N] : FullKernelIsRootAt N := by
  rcases Nat.even_or_odd N with hE | hO
  · intro _ W _ Q hQ hΔ data
    let : (W.fullKernelQuotient Q N).IsElliptic := ⟨isUnit_iff_ne_zero.mpr hΔ⟩
    obtain ⟨gW, hgWc, hgWa⟩ :=
      WeierstrassCurve.Affine.exists_genusOnePlaceGate_isCentred_abelTheorem W.toAffine
    let := gW
    have : GenusOnePlaceGate.IsCentred W.toAffine := hgWc
    have : AbelTheorem W.toAffine := hgWa
    obtain ⟨gV, hgVc, hgVa⟩ :=
      WeierstrassCurve.Affine.exists_genusOnePlaceGate_isCentred_abelTheorem
        (W.fullKernelQuotient Q N).toAffine
    let := gV
    have : GenusOnePlaceGate.IsCentred (W.fullKernelQuotient Q N).toAffine := hgVc
    have : AbelTheorem (W.fullKernelQuotient Q N).toAffine := hgVa
    obtain ⟨ι, hι, hfin, hker⟩ :=
      WeierstrassCurve.exists_functionFieldHom_fullKernelQuotient_pointMapOfPushforward_ker_eq_zmultiples
        hQ hΔ
    have : HasPrincipalDivisors H W.toAffine.FunctionField :=
      WeierstrassCurve.Affine.hasPrincipalDivisors_of_isAlgClosed W.toAffine
    have : CharZero ((W.fullKernelQuotient Q N).toAffine.FunctionField) :=
      charZero_of_injective_algebraMap (algebraMap H _).injective
    have hsep : SeparableAlong H ι := AlgebraicCurve.separableAlong_of_charZero ι hι
    have hN : NormFormulaAlong H ι hfin := AlgebraicCurve.normFormulaAlong ι hfin hsep
    have hkerQ := hker hN
    have hcyc : IsAddCyclic (pointMapOfPushforward ι hι hfin hN).ker := by
      rw [hkerQ]; infer_instance
    have hcard : Nat.card (pointMapOfPushforward ι hι hfin hN).ker = N := by
      rw [hkerQ, Nat.card_zmultiples]; exact hQ
    exact WeierstrassCurve.Affine.eval_modularPolynomial_map_j_eq_zero_of_isAddCyclic_ker_pointMapOfPushforward
      H W.toAffine (W.fullKernelQuotient Q N).toAffine ι hι hfin hN N hcyc hcard data
  · exact fullKernelIsRootAt_of_odd N hO

theorem fullKernelDiscAt_of_tower
    (hevD : ∀ (N : ℕ) [NeZero N], Even N → FullKernelDiscAt N) (N : ℕ) [NeZero N] :
    FullKernelDiscAt N := by
  rcases Nat.even_or_odd N with hE | hO
  · exact hevD N hE
  · exact fullKernelDiscAt_of_odd N hO

end ModularCurve.TatePoint

end

namespace ModularCurve
p2m_export "ModularCurve" "TatePoint.FullKernelIsRootAt"
namespace TatePoint
p2m_export "ModularCurve.TatePoint" "FullKernelIsRootAt FullKernelDiscAt isAlgClosed_H charZero_H H fullKernelIsRootAt_of_odd fullKernelDiscAt_of_odd"
end ModularCurve.TatePoint
p2m_open_scoped "ModularCurve ModularCurve.TatePoint" in

private theorem ModularCurve.TatePoint.fullKernelIsRootAt_aux
    (N : ℕ) [NeZero N] : ModularCurve.TatePoint.FullKernelIsRootAt N :=
  ModularCurve.TatePoint.fullKernelIsRootAt_of_tower N

open scoped Classical
open _root_.ModularCurve _root_.P2MW.S_ModularCurve_TatePoint_fullKernelIsRootAt.ModularCurve _root_.ModularCurve.TatePoint _root_.P2MW.S_ModularCurve_TatePoint_fullKernelIsRootAt.ModularCurve.TatePoint in

theorem solution (N : ℕ) [NeZero N] : FullKernelIsRootAt N :=
  ModularCurve.TatePoint.fullKernelIsRootAt_aux N

end S_ModularCurve_TatePoint_fullKernelIsRootAt
end P2MW
export P2MW.S_ModularCurve_TatePoint_fullKernelIsRootAt (solution)

end privateSection

public section publicSection


open scoped Classical
theorem ModularCurve.TatePoint.fullKernelIsRootAt (N : ℕ) [NeZero N] : FullKernelIsRootAt N := _root_.P2MW.S_ModularCurve_TatePoint_fullKernelIsRootAt.solution N

end publicSection
