/-
Based on Prove2Me node HeckeEis.exists_isEichlerIntegral
(5099303c-73dd-5949-90e0-b6c69197a54e) by Claude (2026-09-05).

Proof based on Prove2Me submission 25a8e27a-56dc-5fce-bf8e-304fe712d843
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Analysis.Complex.UpperHalfPlane.Manifold
public import Definitions.FLT.Def_HeckeEis_EichlerIntegral

import Mathlib.Analysis.Calculus.Deriv.Polynomial
import Theorems.FLT.Thm_Complex_exists_hasDerivAt_of_starConvex
import Definitions.FLT.Def_P2M_Util

/-!
# Existence of Eichler integrals for holomorphic functions on H

Theorem statement: `HeckeEis.exists_isEichlerIntegral` (`5099303c-73dd-5949-90e0-b6c69197a54e`), by
Claude, 2026-09-05.

Proof: submission `25a8e27a-56dc-5fce-bf8e-304fe712d843`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix a natural number $n$ and a function $f$ on the upper half-plane $\mathfrak H$ with values in
$\mathbb C$ which is holomorphic in the sense of being $\mathrm{MDifferentiable}$ for the model with
corners $\mathcal I(\mathbb C)$ on source and target. The assertion is that there exists a function
$F$ on $\mathfrak H$ with values in the submodule [`HeckeEis.BinaryForm ℂ
n`](def/HeckeEis_BinaryFormRep.html#L25) of $\mathbb C$-valued polynomials in two variables $X_0,
X_1$ which are homogeneous of degree $n$, such that [`HeckeEis.IsEichlerIntegral n f
F`](def/HeckeEis_EichlerIntegral.html#L105) holds. Unfolded, the latter says: for every exponent
vector $d : \mathrm{Fin}\,2 \to_0 \mathbb N$ and every $\tau \in \mathfrak H$, the complex function
$z \mapsto \operatorname{coeff}_d\bigl(F(\mathrm{ofComplex}\,z)\bigr)$, defined on all of $\mathbb
C$ via the retraction $\mathrm{ofComplex} : \mathbb C \to \mathfrak H$, has derivative at the point
$\tau$ equal to $f(\tau)\cdot \operatorname{coeff}_d\bigl((\tau X_0 + X_1)^n\bigr)$, where $(\tau
X_0+X_1)^n$ is [`HeckeEis.linePow n τ`](def/HeckeEis_EichlerIntegral.html#L22). Thus $F$ is,
coefficient by coefficient, a primitive of the $\operatorname{Sym}^n$-valued function $\tau \mapsto
f(\tau)(\tau X_0+X_1)^n$, with the derivative condition recorded in the strong form of `HasDerivAt`
at every point of $\mathfrak H$.

This is the existence statement for Eichler integrals in weight $n+2$: a holomorphic function on
$\mathfrak H$ admits a $\operatorname{Sym}^n(\mathbb C^2)$-valued primitive of $f(\tau)(\tau
X_0+X_1)^n$. It is the purely analytic input to the Eichler–Shimura construction, used downstream to
attach (parabolic) cocycles to modular forms and to compare Hecke actions on cohomology with Hecke
actions on forms.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_exists_isEichlerIntegral.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HeckeEis_exists_isEichlerIntegral

open scoped Manifold MatrixGroups

noncomputable section

namespace HeckeEis
p2m_export "HeckeEis" "BinaryForm isHomogeneous_linePow linePow coe_linePow IsEichlerIntegral"
p2m_open "HeckeEis"

open UpperHalfPlane MvPolynomial
open scoped Manifold Polynomial

namespace EichlerIntegralExistence

variable (n : ℕ)

def degExps : Finset (Fin 2 →₀ ℕ) :=
  (Finset.range (n + 1)).image fun k => Finsupp.single 0 k + Finsupp.single 1 (n - k)

theorem mem_degExps_iff (d : Fin 2 →₀ ℕ) : d ∈ degExps n ↔ d.degree = n := by
  rw [Finsupp.degree_eq_sum, Fin.sum_univ_two]
  simp only [degExps, Finset.mem_image, Finset.mem_range]
  constructor
  · rintro ⟨k, hk, rfl⟩
    simp
    omega
  · intro h
    refine ⟨d 0, by omega, ?_⟩
    ext i
    fin_cases i
    · simp
    · simp
      omega

def linePowPoly : MvPolynomial (Fin 2) ℂ[X] :=
  (C Polynomial.X * X 0 + X 1) ^ n

theorem coeff_linePow_eq_eval (d : Fin 2 →₀ ℕ) (z : ℂ) :
    AddMonoidAlgebra.coeff ((C z * X 0 + X 1 : MvPolynomial (Fin 2) ℂ) ^ n) d
      = Polynomial.eval z (AddMonoidAlgebra.coeff (linePowPoly n) d) := by
  have h : ((C z * X 0 + X 1 : MvPolynomial (Fin 2) ℂ) ^ n)
      = MvPolynomial.map (Polynomial.evalRingHom z) (linePowPoly n) := by
    simp [linePowPoly, MvPolynomial.map_X, MvPolynomial.map_C]
  rw [h, MvPolynomial.coeff_map]
  rfl

def assemble (g : (Fin 2 →₀ ℕ) → ℂ → ℂ) (τ : ℍ) : ↥(BinaryForm ℂ n) :=
  ⟨∑ d ∈ degExps n, monomial d (g d (τ : ℂ)), Submodule.sum_mem _ fun d hd =>
    (mem_homogeneousSubmodule n _).mpr (isHomogeneous_monomial _ ((mem_degExps_iff n d).mp hd))⟩

theorem coeff_assemble (g : (Fin 2 →₀ ℕ) → ℂ → ℂ) (τ : ℍ) (d : Fin 2 →₀ ℕ) :
    AddMonoidAlgebra.coeff (assemble n g τ : MvPolynomial (Fin 2) ℂ) d = if d ∈ degExps n then g d (τ : ℂ) else 0 := by
  show AddMonoidAlgebra.coeff (∑ e ∈ degExps n, monomial e (g e (τ : ℂ))) d = _
  simp only [coeff_sum, coeff_monomial, Finset.sum_ite_eq']

end EichlerIntegralExistence

end HeckeEis

open _root_.HeckeEis _root_.P2MW.S_HeckeEis_exists_isEichlerIntegral.HeckeEis HeckeEis.EichlerIntegralExistence UpperHalfPlane MvPolynomial in
theorem solution (n : ℕ) {f : UpperHalfPlane → ℂ}
    (hf : MDifferentiable 𝓘(ℂ) 𝓘(ℂ) f) :
    ∃ F : UpperHalfPlane → ↥(HeckeEis.BinaryForm ℂ n), HeckeEis.IsEichlerIntegral n f F := by
  let U : Set ℂ := {z | 0 < z.im}
  have hU : IsOpen U := isOpen_upperHalfPlaneSet
  have hI : ((I : ℍ) : ℂ) ∈ U := (I : ℍ).im_pos
  have hstar : StarConvex ℝ ((I : ℍ) : ℂ) U := (convex_halfSpace_im_gt 0).starConvex hI
  have hfd : DifferentiableOn ℂ (f ∘ ofComplex) U := UpperHalfPlane.mdifferentiable_iff.mp hf
  have key : ∀ d : Fin 2 →₀ ℕ, ∃ g : ℂ → ℂ, ∀ z ∈ U,
      HasDerivAt g ((f ∘ ofComplex) z * (AddMonoidAlgebra.coeff (linePowPoly n) d).eval z) z := by
    intro d
    obtain ⟨g, -, hg⟩ := Complex.exists_hasDerivAt_of_starConvex hU hI hstar
      (hfd.mul (Polynomial.differentiable _).differentiableOn)
    exact ⟨g, hg⟩
  choose g hg using key
  refine ⟨assemble n g, fun d τ => ?_⟩
  simp only [coeff_assemble]
  by_cases hd : d ∈ degExps n
  · simp only [ite_eq_left hd]
    have h2 : (f ∘ ofComplex) (τ : ℂ) * (AddMonoidAlgebra.coeff (linePowPoly n) d).eval (τ : ℂ)
        = f τ * AddMonoidAlgebra.coeff ((linePow n (τ : ℂ) : ↥(BinaryForm ℂ n)) : MvPolynomial (Fin 2) ℂ) d := by
      rw [Function.comp_apply, ofComplex_apply, coe_linePow, coeff_linePow_eq_eval]
    rw [← h2]
    refine (hg d (τ : ℂ) τ.im_pos).congr_of_eventuallyEq ?_
    filter_upwards [hU.mem_nhds τ.im_pos] with z hz
    rw [ofComplex_apply_of_im_pos hz]
  · simp only [ite_eq_right hd]
    have h0 : AddMonoidAlgebra.coeff ((linePow n (τ : ℂ) : ↥(BinaryForm ℂ n)) : MvPolynomial (Fin 2) ℂ) d = 0 :=
      (isHomogeneous_linePow n τ).coeff_eq_zero (by rwa [mem_degExps_iff] at hd)
    rw [h0, mul_zero]
    exact hasDerivAt_const _ _

end

end S_HeckeEis_exists_isEichlerIntegral
end P2MW
export P2MW.S_HeckeEis_exists_isEichlerIntegral (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open scoped Manifold MatrixGroups
theorem HeckeEis.exists_isEichlerIntegral (n : ℕ) {f : UpperHalfPlane → ℂ}
    (hf : MDifferentiable 𝓘(ℂ) 𝓘(ℂ) f) :
    ∃ F : UpperHalfPlane → ↥(HeckeEis.BinaryForm ℂ n), HeckeEis.IsEichlerIntegral n f F := _root_.P2MW.S_HeckeEis_exists_isEichlerIntegral.solution n hf

end publicSection
