/-
Based on Prove2Me node AlgebraicCurve.functionFieldRiemannRoch_of_isAlgClosed
(b4ac021e-cbea-59f4-abb3-092663a1778d) by Claude (2026-09-05).

Proof based on Prove2Me submission 2254a18a-8fc5-56c0-8fbb-b9a37eb766a0
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.RatFunc.Basic
public import Definitions.FLT.Def_AlgebraicCurve_LocalResidue
public import Definitions.FLT.Def_AlgebraicCurve_RiemannRochRows

import Theorems.FLT.Thm_AlgebraicCurve_residueTheoremK_of_isAlgClosed
import Theorems.FLT.Thm_AlgebraicCurve_functionFieldRiemannRoch_of_residueTheoremK_of_isAlgClosed
import Definitions.FLT.Def_P2M_Util

/-!
# Riemann–Roch over an algebraically closed base field

Theorem statement: `AlgebraicCurve.functionFieldRiemannRoch_of_isAlgClosed`
(`b4ac021e-cbea-59f4-abb3-092663a1778d`), by Claude, 2026-09-05.

Proof: submission `2254a18a-8fc5-56c0-8fbb-b9a37eb766a0`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be an algebraically closed field (no restriction on characteristic), with decidable equality
on $\mathrm{RatFunc}\,K$, and let $F$ be a field and a $K$-algebra which is moreover an algebra over
$\mathrm{RatFunc}\,K$ compatibly with $K$ (scalar tower), integral, module-finite and
finite-dimensional over $\mathrm{RatFunc}\,K$, and separable over it. Assume: `HasCanonicalDivisor`,
i.e. for every nonzero $\omega \in \Omega_{F/K}$ the function $v \mapsto
v.\mathrm{ordDifferential}\,\omega$ on places is given by a finitely supported divisor; at every
place of $F$ and of $\mathrm{RatFunc}\,K$ the element `dCoord` spans $\Omega$ over the field
(`DCoordGenerates`) and the residue field is finite-dimensional over $K$ (`FiniteResidue`);
$\Omega_{F/K}$ and $\Omega_{\mathrm{RatFunc}\,K/K}$ are nontrivial; `HasLocalResidue K F`, i.e.
every place carries a $K$-linear residue map on $F$ vanishing on the valuation subring and sending
$f$ with $\pi f$ integral to the residue class of $\pi f$; `HasCanonicalLocalResidueKStar K F`, a
choice of canonical local residue datum over $K$ at each place; `HasPrincipalDivisors K F`, i.e.
each nonzero $f \in F$ has a divisor of valuations of total degree $0$; `IsCurveOver K F` and
$\mathrm{IsCurveOver}\,K\,(\mathrm{RatFunc}\,K)$ (principal divisors, finite residue fields,
$\Omega$ free of rank one); and `HasSeparableResidue K F`, i.e. the trace form
$\mathrm{Tr}_{\kappa(v)/K}$ is nonzero at every place. Then `FunctionFieldRiemannRoch K F` holds:
granted the curve, canonical-divisor and `DCoordGenerates` structures, for every nonzero $\omega \in
\Omega_{F/K}$ and every divisor $D$ of $F/K$, $\ell(D) - \ell\bigl((\omega) - D\bigr) = \deg D + 1 -
g$, with $(\omega)$ the chosen canonical divisor of $\omega$ and $g$ the genus as defined from the
degree of a canonical divisor.

This is the Riemann–Roch theorem for the function field $F/K$ of a curve over an algebraically
closed field, in Tate's residue-theoretic formulation. It is the form used downstream to compute
$\deg(\omega) = 2g-2$, to identify $\ell((\omega)) = g$, and in the ramification count
[`AlgebraicCurve.finsum_ramificationIndexAlong_sub_one_eq`](thm.html#AlgebraicCurve.finsum_ramificationIndexAlong_sub_one_eq).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_functionFieldRiemannRoch_of_isAlgClosed.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_functionFieldRiemannRoch_of_isAlgClosed
p2m_attr_erase "instance" "AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instDimensionLEOneSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.instLiesOverSubtypeAdicCompletionMemValuationSubringAdicCompletionIntegersCompletionIdealAsIdeal IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsPrincipalIdealRingSubtypeMemValuationSubringAdicCompletionIntegers_definitions IsDedekindDomain.HeightOneSpectrum.adicCompletion.instIsDiscreteValuationRingSubtypeMemSubringIntegerWithZeroMultiplicativeInt_definitions IsDedekindDomain.HeightOneSpectrum.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicCompletionV_definitions AlgebraicCurve.Place.kw_ffgc_finiteDimensional_adicCompletion instAlgebraSubtypeMemValuationSubring_definitions AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersIntegersCompletion ModularCurve.KwF4gRRTate.instAlgebraKAdicCompletionIntegers AlgebraicCurve.Place.kw_ffgc_continuousSMul_adicCompletionComap AlgebraicCurve.Place.kw_ffgc_isScalarTower_integersCompletionCompletion AlgebraicCurve.instHasCanonicalLocalResidueK AlgebraicCurve.Place.instAlgebra_restrictResidueField AlgebraicCurve.Place.instIsScalarTower_restrictResidueField AlgebraicCurve.instHasLocalResidue AlgebraicCurve.HasSeparableResidue.of_perfectField_of_isCurveOver AlgebraicCurve.HasSeparableResidue.of_perfectField AlgebraicCurve.Place.instIsLocalHom_restrictSubringHom AlgebraicCurve.instHasCanonicalLocalResidueKStar ModularCurve.KwNo6Pin.isLocalRing_completion"
p2m_attr_erase "simp" "AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Place.kw_ffgc_adicCompletionComapIntegers_coe AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.sizeOf_spec AlgebraicCurve.Place.mem_simplePoleSubmodule AlgebraicCurve.Place.coe_uniformizerSubring ModularCurve.Lg37.Lg37CompletionSection.mk.injEq AlgebraicCurve.Place.CoefficientFieldSection.mk.injEq AlgebraicCurve.Place.CanonicalLocalResidueDataS.mk.injEq ModularCurve.Lg37.Lg37CompletionSection.mk.sizeOf_spec AlgebraicCurve.Place.CoefficientFieldSection.mk.sizeOf_spec AlgebraicCurve.Place.poleSubmodule_one AlgebraicCurve.Place.mem_poleSubmodule"

theorem solution
    {K F : Type*} [Field K] [IsAlgClosed K] [DecidableEq (RatFunc K)]
    [Field F] [Algebra K F]
    [Algebra (RatFunc K) F] [IsScalarTower K (RatFunc K) F]
    [Algebra.IsIntegral (RatFunc K) F]
    [AlgebraicCurve.HasLocalResidue K F]
    [∀ w : AlgebraicCurve.Place K F, w.FiniteResidue]
    [Nontrivial Ω[F⁄K]]
    [AlgebraicCurve.IsCurveOver K (RatFunc K)]
    [∀ u : AlgebraicCurve.Place K (RatFunc K), u.FiniteResidue]
    [AlgebraicCurve.HasCanonicalLocalResidueKStar K F]
    [Algebra.IsSeparable (RatFunc K) F]
    [Nontrivial Ω[(RatFunc K)⁄K]] [∀ v : AlgebraicCurve.Place K (RatFunc K), v.DCoordGenerates]
    [FiniteDimensional (RatFunc K) F] [AlgebraicCurve.HasSeparableResidue K F] :
    AlgebraicCurve.FunctionFieldRiemannRoch K F :=
  AlgebraicCurve.functionFieldRiemannRoch_of_residueTheoremK_of_isAlgClosed
    (hRTK := AlgebraicCurve.residueTheoremK_of_isAlgClosed)

end S_AlgebraicCurve_functionFieldRiemannRoch_of_isAlgClosed
end P2MW
export P2MW.S_AlgebraicCurve_functionFieldRiemannRoch_of_isAlgClosed (solution)

end privateSection

public section publicSection

theorem AlgebraicCurve.functionFieldRiemannRoch_of_isAlgClosed
    {K F : Type*} [Field K] [IsAlgClosed K] [DecidableEq (RatFunc K)]
    [Field F] [Algebra K F]
    [Algebra (RatFunc K) F] [IsScalarTower K (RatFunc K) F]
    [Algebra.IsIntegral (RatFunc K) F]
    [AlgebraicCurve.HasLocalResidue K F]
    [∀ w : AlgebraicCurve.Place K F, w.FiniteResidue]
    [Nontrivial Ω[F⁄K]]
    [AlgebraicCurve.IsCurveOver K (RatFunc K)]
    [∀ u : AlgebraicCurve.Place K (RatFunc K), u.FiniteResidue]
    [AlgebraicCurve.HasCanonicalLocalResidueKStar K F]
    [Algebra.IsSeparable (RatFunc K) F]
    [Nontrivial Ω[(RatFunc K)⁄K]] [∀ v : AlgebraicCurve.Place K (RatFunc K), v.DCoordGenerates]
    [FiniteDimensional (RatFunc K) F] [AlgebraicCurve.HasSeparableResidue K F] :
    AlgebraicCurve.FunctionFieldRiemannRoch K F := _root_.P2MW.S_AlgebraicCurve_functionFieldRiemannRoch_of_isAlgClosed.solution

end publicSection
