/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.ord_placeInfty
(3c1d2f21-1efb-5e11-a4c3-ce8ddea9179b) by Claude (2026-09-05).

Proof based on Prove2Me submission 74ae96fc-9bfe-59aa-954f-25e3933b067d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceInfty

import Mathlib.FieldTheory.RatFunc.Degree
import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceClassification
import Theorems.FLT.Thm_P2M_Dup_AlgebraicCurve_RationalFunctionField_placeInfty_ne_ofHeightOneSpectrum
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_eq_neg_intDegree_of_forall_ne_ofHeightOneSpectrum
import Definitions.FLT.Def_P2M_Util

/-!
# Order at the infinite place is minus the degree

Theorem statement: `AlgebraicCurve.RationalFunctionField.ord_placeInfty`
(`3c1d2f21-1efb-5e11-a4c3-ce8ddea9179b`), by Claude, 2026-09-05.

Proof: submission `74ae96fc-9bfe-59aa-954f-25e3933b067d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $f$ be a nonzero element of the rational function field
$\mathrm{RatFunc}\,K$. Consider the place $\mathrm{placeInfty}\,K$ of $\mathrm{RatFunc}\,K$ over
$K$: in the project's sense a place of $F$ over $K$ is a valuation subring of $F$ containing the
image of $K$ under the structure map, different from all of $F$, and a principal ideal ring; for
$\mathrm{placeInfty}\,K$ the valuation subring is the one attached to the infinity valuation
$\mathrm{RatFunc.inftyValuation}\,K$ on $K(t)$, whose containment of the constants comes from the
triviality of that valuation on $K$, whose non-triviality gives that it is not everything, and whose
principality comes from the fact that the valuation ring is a discrete valuation ring. For a place
$v$ the integer $v.\mathrm{ord}\,g$ is defined as $-\log$ of the value at $g$ of the adic valuation
of the height-one prime of the valuation subring, with values in $\mathbb{Z}^{m0}$. The assertion is
the equality $(\mathrm{placeInfty}\,K).\mathrm{ord}\,f = -f.\mathrm{intDegree}$, where the integer
degree of $f$ is the degree of its numerator minus that of its denominator.

This identifies the normalised order function at the place at infinity of $\mathbb{P}^1_K$ with
minus the degree of a rational function; in particular a polynomial of degree $d$ has a pole of
order $d$ there, and $1/t$ is a uniformiser. It is used throughout the function-field foundations of
the project, for instance in determining which rational functions lie in $K[t]$ away from infinity
and in the finiteness and Riemann–Roch computations for the rational function field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_ord_placeInfty.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_ord_placeInfty
p2m_attr_erase "instance" "AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

open IsDedekindDomain AlgebraicCurve AlgebraicCurve.RationalFunctionField

theorem solution {K : Type*} [Field K] [DecidableEq (RatFunc K)] {f : RatFunc K} (hf : f ≠ 0) : (placeInfty K).ord f = -f.intDegree :=
  AlgebraicCurve.RationalFunctionField.ord_eq_neg_intDegree_of_forall_ne_ofHeightOneSpectrum (placeInfty K)
    (AlgebraicCurve.RationalFunctionField.placeInfty_ne_ofHeightOneSpectrum K) hf

end S_AlgebraicCurve_RationalFunctionField_ord_placeInfty
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_ord_placeInfty (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve AlgebraicCurve.RationalFunctionField
theorem AlgebraicCurve.RationalFunctionField.ord_placeInfty {K : Type*} [Field K] [DecidableEq (RatFunc K)] {f : RatFunc K} (hf : f ≠ 0) : (placeInfty K).ord f = -f.intDegree := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_ord_placeInfty.solution hf

end publicSection
