/-
Based on Prove2Me node ModularCurve.isIntegral_jqNModC_all
(7b602140-edbb-5016-8c95-50c78314d067) by Claude (2026-09-05).

Proof based on Prove2Me submission 2514932a-9210-58ac-b027-81358136b2f5
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff

import Definitions.FLT.Def_ModularCurve_PhiGen
import Theorems.FLT.Thm_ModularCurve_isIntegral_jqNModC_all_of_modularPolynomialFamily
import Theorems.FLT.Thm_ModularCurve_modularPolynomialFamily
import Definitions.FLT.Def_P2M_Util

/-!
# Integrality of ̄ j(q^N) over K(̄ j(q))

Theorem statement: `ModularCurve.isIntegral_jqNModC_all` (`7b602140-edbb-5016-8c95-50c78314d067`),
by Claude, 2026-09-05.

Proof: submission `2514932a-9210-58ac-b027-81358136b2f5`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $N$ be a natural number with $N \neq 0$. Inside the field of Laurent
series $K((q))$ (`LaurentSeries K`, Hahn series over $K$ with integer exponents) consider the
element $\bar j =$ `jqModC K`, defined as the monomial $q^{-1}$ times the image in $K[[q]]$ of the
integral power series `jNum` $=$ `eisenstein4`$^3 \cdot$ `dedekindEtaUnitInv` under the
coefficientwise map $\mathbb{Z} \to K$; this is the $q$-expansion of the modular invariant $j$ read
in $K$. Let $\bar j_N =$ `jqNModC K N` be its image under `qExpand K N`, the ring homomorphism of
$K((q))$ obtained by pushing exponents forward along multiplication by $N$ on $\mathbb{Z}$, that is,
the substitution $q \mapsto q^N$. The assertion is that $\bar j_N$ is integral over the intermediate
field `IntermediateField.adjoin K {jqModC K}` of $K((q))$, i.e. over $K(\bar j)$: it satisfies a
monic polynomial equation with coefficients in $K(\bar j)$. No hypothesis on $K$ (characteristic,
size) or on $N$ beyond $N \neq 0$ is imposed.

This is the $q$-expansion form, valid over an arbitrary field of coefficients, of the classical
integrality of $j(N\tau)$ over $\mathbb{Z}[j(\tau)]$ furnished by the modular polynomial $\Phi_N$.
It is the unconditional input to the construction of models of the modular curves $X_0(N)$ and their
Hecke correspondences used later, and is cited throughout the work on place specialisations and
prolongation tuples.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_isIntegral_jqNModC_all.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_isIntegral_jqNModC_all
p2m_attr_erase "simp" "ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

open ModularCurve

theorem solution (K : Type*) [Field K] (N : ℕ) [NeZero N] :
    IsIntegral (IntermediateField.adjoin K ({jqModC K} : Set (LaurentSeries K))) (jqNModC K N) :=
  isIntegral_jqNModC_all_of_modularPolynomialFamily K modularPolynomialFamily N

end S_ModularCurve_isIntegral_jqNModC_all
end P2MW
export P2MW.S_ModularCurve_isIntegral_jqNModC_all (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.isIntegral_jqNModC_all (K : Type*) [Field K] (N : ℕ) [NeZero N] :
    IsIntegral (IntermediateField.adjoin K ({jqModC K} : Set (LaurentSeries K))) (jqNModC K N) := _root_.P2MW.S_ModularCurve_isIntegral_jqNModC_all.solution K N

end publicSection
