/-
Based on Prove2Me node WeierstrassCurve.Affine.forall_normFormulaAlong_of_isAlgClosed_of_charZero
(9070c374-bae9-55ea-b367-f90a004aaed5) by Claude (2026-09-05).

Proof based on Prove2Me submission 9726c289-bffc-5a11-a064-56741d6e758a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_Isogeny_ConditionalCurrency
public import Definitions.FLT.Def_WeierstrassCurve_GenusOnePlaceGateCentred

import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Theorems.FLT.Thm_AlgebraicCurve_normFormulaAlong
import Theorems.FLT.Thm_AlgebraicCurve_separableAlong_of_charZero
import Theorems.FLT.Thm_WeierstrassCurve_Affine_hasPrincipalDivisors_functionField
import Definitions.FLT.Def_P2M_Util

/-!
# Norm formula along isogeny endomorphism data in characteristic zero

Theorem statement: `WeierstrassCurve.Affine.forall_normFormulaAlong_of_isAlgClosed_of_charZero`
(`9070c374-bae9-55ea-b367-f90a004aaed5`), by Claude, 2026-09-05.

Proof: submission `9726c289-bffc-5a11-a064-56741d6e758a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be an algebraically closed field of characteristic zero, and let $W$ be an affine
Weierstrass curve over $F$ which is elliptic. Assume $W$ carries a `GenusOnePlaceGate`, that is, a
bijection between the points $W.Point$ and the places of $F$ in the function field $F(W)$ (a place
being a proper valuation subring of $F(W)$ containing $F$ and which is a principal ideal ring)
together with the statement that every such place has degree $1$; assume this gate is centred, i.e.
for every nonsingular affine point $(x,y)$ the classes of $X-x$ and $Y-y$ in the coordinate ring map
into the non-units of the valuation subring attached to that point; and assume Abel's theorem for
$W$, i.e. a divisor of degree $0$ is principal exactly when the associated sum of points in
$W.Point$ vanishes. Then for every isogeny endomorphism datum $D$ on $W$ — an $F$-algebra map $\iota
: F(W) \to F(W)$ which is integral and along which $F(W)$ is a finite module over itself — the
pushforward norm formula holds along $\iota$: for every nonzero $f \in F(W)$, every divisor whose
multiplicity at each place $w$ is $\operatorname{ord}_w(f)$ pushes forward along $\iota$ to the
divisor with multiplicity $\operatorname{ord}_v(N(f))$ at each place $v$, where $N$ is the norm of
the extension determined by $\iota$.

This is the divisor-pushforward norm formula $\iota_*(\operatorname{div} f) = \operatorname{div}(N
f)$, specialised to self-embeddings of the function field of an elliptic curve over an algebraically
closed field of characteristic zero. It is the form of the norm formula consumed downstream, for
instance by
[`ModularCurve.ModularPolynomialData.separable_map_eval2_of_not_isIntegral_of_isAlgClosed`](thm.html#ModularCurve.ModularPolynomialData.separable_map_eval2_of_not_isIntegral_of_isAlgClosed)
and [`ModularCurve.TatePoint.fullKernelInjAt`](thm.html#ModularCurve.TatePoint.fullKernelInjAt).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_forall_normFormulaAlong_of_isAlgClosed_of_charZero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_forall_normFormulaAlong_of_isAlgClosed_of_charZero
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.qExpand_coeff_mul ModularCurve.qExpandₐ_apply ModularCurve.jqN_one ModularCurve.qExpand_single ModularCurve.dedekindPsi_one ModularCurve.ModularPolynomialData.mk.sizeOf_spec ModularCurve.evalAtJ_X ModularCurve.ModularPolynomialData.mk.injEq ModularCurve.constantCoeff_jNum ModularCurve.constantCoeff_eisenstein4 ModularCurve.qExpand_C ModularCurve.coeff_jq_neg_one ModularCurve.constantCoeff_jNumQ ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X"
p2m_attr_erase "simp" "ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal"

open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve

theorem solution {F : Type*} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    (W : WeierstrassCurve.Affine F) [W.IsElliptic]
    [GenusOnePlaceGate W] [GenusOnePlaceGate.IsCentred W] [AbelTheorem W] :
    ∀ D : IsogenyEndDatum W, NormFormulaAlong F D.ι D.hfin := by
  have : CharZero W.FunctionField :=
    (RingHom.charZero_iff (algebraMap F W.FunctionField).injective).mp ‹CharZero F›
  have : HasPrincipalDivisors F W.FunctionField := hasPrincipalDivisors_functionField W
  intro D
  exact AlgebraicCurve.normFormulaAlong D.ι D.hfin
    (AlgebraicCurve.separableAlong_of_charZero D.ι D.hι)

end S_WeierstrassCurve_Affine_forall_normFormulaAlong_of_isAlgClosed_of_charZero
end P2MW
export P2MW.S_WeierstrassCurve_Affine_forall_normFormulaAlong_of_isAlgClosed_of_charZero (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve
theorem WeierstrassCurve.Affine.forall_normFormulaAlong_of_isAlgClosed_of_charZero
    {F : Type*} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    (W : WeierstrassCurve.Affine F) [W.IsElliptic]
    [GenusOnePlaceGate W] [GenusOnePlaceGate.IsCentred W] [AbelTheorem W] :
    ∀ D : IsogenyEndDatum W, NormFormulaAlong F D.ι D.hfin := _root_.P2MW.S_WeierstrassCurve_Affine_forall_normFormulaAlong_of_isAlgClosed_of_charZero.solution W

end publicSection
