/-
Based on Prove2Me node CuspForm.heckeTLin_heckeULin_comm
(ec98f7b8-bb6c-565e-8a22-659275b8f372) by Claude (2026-09-05).

Proof based on Prove2Me submission 84800b90-33d8-5727-83e3-b99766941ba4
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularForm_HeckeOperatorForms

import Theorems.FLT.Thm_ModularFormClass_heckeT_heckeU_comm
import Definitions.FLT.Def_P2M_Util

/-!
# Tₚ and U_q commute on S_k(Γ₀(N))

Theorem statement: `CuspForm.heckeTLin_heckeULin_comm` (`ec98f7b8-bb6c-565e-8a22-659275b8f372`), by
Claude, 2026-09-05.

Proof: submission `84800b90-33d8-5727-83e3-b99766941ba4`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number, assumed nonzero, let $k$ be an integer, and let $p,q$ be natural
numbers with $p$ prime, $p \nmid N$ and $q \mid N$. The assertion is that the two
$\mathbb{C}$-linear endomorphisms [`CuspForm.heckeTLin k hp
hpN`](def/ModularForm_HeckeOperatorForms.html#L69) and [`CuspForm.heckeULin k
hqN`](def/ModularForm_HeckeOperatorForms.html#L83) of the space $S_k(\Gamma_0(N))$ of weight-$k$
cusp forms for `CongruenceSubgroup.Gamma0 N` commute, i.e. their two composites in either order are
equal as linear maps. Here [`CuspForm.heckeULin k hqN`](def/ModularForm_HeckeOperatorForms.html#L83)
is the map sending a cusp form $f$ to the cusp form with underlying function
$\mathrm{heckeU}\,k\,q\,f = \sum_{j<q} f \mid[k]\,(\mathrm{heckeMatrix}\, q\,j)$, the weight-$k$
slash action applied to the $q$ matrices `heckeMatrix q j` for $j$ in `Finset.range q` and summed;
and [`CuspForm.heckeTLin k hp hpN`](def/ModularForm_HeckeOperatorForms.html#L69) sends $f$ to the
cusp form with underlying function $\mathrm{heckeT}\,k\,p\,f = \mathrm{heckeU}\,k\,p\,f + f
\mid[k]\,(\mathrm{heckeDiagMatrix}\, p)$, the same sum of $p$ slashes together with one further
slash by the diagonal matrix `heckeDiagMatrix p`. In both cases the hypotheses on $p$ and on $q$
enter in verifying that the resulting function is again $\Gamma_0(N)$-invariant of weight $k$,
holomorphic and vanishing at the cusps.

This is the coprime case of the commutativity of the Hecke algebra acting on cusp forms, in the
mixed form pairing a good Hecke operator $T_p$ with $p \nmid N$ against a $U_q$ with $q \mid N$. It
is used downstream wherever a family of Hecke operators must be diagonalised simultaneously or
generate a commutative subalgebra of $\mathrm{End}_{\mathbb{C}} S_k(\Gamma_0(N))$, for instance in
the construction of normalised eigenforms from systems of $T_p$-eigenvalues and in the analysis of
$U_q$ on newforms.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_CuspForm_heckeTLin_heckeULin_comm.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_CuspForm_heckeTLin_heckeULin_comm

theorem solution {N : ℕ} [NeZero N] (k : ℤ) {p q : ℕ} (hp : p.Prime) (hpN : ¬ p ∣ N) (hqN : q ∣ N) :
    Commute (CuspForm.heckeTLin k hp hpN) (CuspForm.heckeULin k hqN) := by
  rw [commute_iff_eq]; ext f τ
  simpa using congrFun (ModularFormClass.heckeT_heckeU_comm f (by simp)
    ((Nat.Prime.coprime_iff_not_dvd hp).mpr fun h => hpN (h.trans hqN))) τ

end S_CuspForm_heckeTLin_heckeULin_comm
end P2MW
export P2MW.S_CuspForm_heckeTLin_heckeULin_comm (solution)

end privateSection

public section publicSection

theorem CuspForm.heckeTLin_heckeULin_comm {N : ℕ} [NeZero N] (k : ℤ) {p q : ℕ} (hp : p.Prime) (hpN : ¬ p ∣ N) (hqN : q ∣ N) :
    Commute (CuspForm.heckeTLin k hp hpN) (CuspForm.heckeULin k hqN) := _root_.P2MW.S_CuspForm_heckeTLin_heckeULin_comm.solution k hp hpN hqN

end publicSection
