/-
Based on Prove2Me node WeierstrassCurve.Affine.pointMapOfPushforward_surjective
(da89fd8d-d346-53a0-8175-51c3792e69dc) by Claude (2026-09-05).

Proof based on Prove2Me submission 288e189f-bc82-5ffd-85ae-5c9ae8f204d1
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_Isogeny_ConditionalCurrency

import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Theorems.FLT.Thm_AlgebraicCurve_Place_restrictAlong_surjective
import Definitions.FLT.Def_P2M_Util

/-!
# Pushforward map on points of an elliptic curve is surjective

Theorem statement: `WeierstrassCurve.Affine.pointMapOfPushforward_surjective`
(`da89fd8d-d346-53a0-8175-51c3792e69dc`), by Claude, 2026-09-05.

Proof: submission `288e189f-bc82-5ffd-85ae-5c9ae8f204d1`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be an algebraically closed field of characteristic zero and let $E$, $E'$ be affine
Weierstrass curves over $F$, both elliptic, and both equipped with the two genus-one gates: a
bijection of the point set with the set of places of the function field over $F$ (a place being a
proper valuation subring of the function field which contains the image of $F$ and is a principal
ideal ring) under which every place has degree $1$, and the Abel-type property that a divisor of
degree $0$ is principal, i.e. of the form $v \mapsto v.\mathrm{ord}(f)$ for some $f \neq 0$, exactly
when the sum in the group of points of its places, weighted by their multiplicities, vanishes. Let
$\iota \colon F(E') \to F(E)$ be an $F$-algebra map whose underlying ring map is integral, assume
$F(E)$ is a finite module over $F(E')$ via $\iota$, and assume the pushforward norm formula along
$\iota$: for every nonzero $f \in F(E)$ and every divisor $D$ on $F(E)$ with $D(w) =
w.\mathrm{ord}(f)$ at all places $w$, and every place $v$ of $F(E')$, the pushforward of $D$ takes
at $v$ the value $v.\mathrm{ord}(\mathrm{N}_{F(E)/F(E')}(f))$. Then the group homomorphism $E(F) \to
E'(F)$ obtained by transporting the pushforward of degree-zero divisor classes along $\iota$ through
the genus-one identifications $\mathrm{Pic}^0 \cong \mathrm{Point}$ is surjective.

This is the function-field form of the statement that a nonconstant morphism of elliptic curves over
an algebraically closed field is surjective on points (Silverman, III.4.10(a)), here for the map on
points induced by divisor pushforward along an embedding of function fields. It feeds the
computation of the kernel of that map, in particular its cardinality in terms of the degree of
$F(E)/F(E')$, and thence the comparison of isogeny kernels used downstream.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_pointMapOfPushforward_surjective.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_pointMapOfPushforward_surjective
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy"
p2m_attr_erase "simp" "AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.qExpand_coeff_mul ModularCurve.qExpandₐ_apply ModularCurve.jqN_one ModularCurve.qExpand_single ModularCurve.dedekindPsi_one ModularCurve.ModularPolynomialData.mk.sizeOf_spec ModularCurve.evalAtJ_X ModularCurve.ModularPolynomialData.mk.injEq ModularCurve.constantCoeff_jNum ModularCurve.constantCoeff_eisenstein4 ModularCurve.qExpand_C"
p2m_attr_erase "simp" "ModularCurve.coeff_jq_neg_one ModularCurve.constantCoeff_jNumQ ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply"

open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve

universe u

theorem solution
    {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    (E E' : WeierstrassCurve.Affine F) [E.IsElliptic] [GenusOnePlaceGate E] [AbelTheorem E]
    [E'.IsElliptic] [GenusOnePlaceGate E'] [AbelTheorem E']
    (ι : E'.FunctionField →ₐ[F] E.FunctionField) (hι : ι.toRingHom.IsIntegral)
    (hfin : FiniteAlong F ι) (hN : NormFormulaAlong F ι hfin) :
    Function.Surjective (pointMapOfPushforward ι hι hfin hN) := by
  classical
  have hsep : SeparableAlong F ι := by
    let := algebraAlong ι
    have : Module.Finite E'.FunctionField E.FunctionField := hfin
    have : CharZero E'.FunctionField :=
      charZero_of_injective_algebraMap (algebraMap F E'.FunctionField).injective
    show Algebra.IsSeparable E'.FunctionField E.FunctionField
    exact Algebra.IsSeparable.of_integral E'.FunctionField E.FunctionField
  choose s hs using AlgebraicCurve.Place.restrictAlong_surjective ι hι hfin hsep
  have hpush : Function.Surjective (Pic0.pushforwardAlongHom ι hι hfin hN) := by
    intro c'
    obtain ⟨D', rfl⟩ := Pic0.mk_surjective c'
    let D : Divisor F E.FunctionField := Finsupp.mapDomain s (D' : Divisor F E'.FunctionField)
    have hD : Divisor.pushforwardAlong ι hι D = (D' : Divisor F E'.FunctionField) := by
      show Divisor.pushforwardAlong ι hι (Finsupp.mapDomain s (D' : Divisor F E'.FunctionField)) = _
      rw [Finsupp.mapDomain, map_finsuppSum]
      conv_rhs => rw [← Finsupp.sum_single (D' : Divisor F E'.FunctionField)]
      refine Finsupp.sum_congr (fun v _ => ?_)
      have hsv : (s v).restrictAlong ι hι = v := hs v
      rw [pushforwardAlong_single_eq ι hι (s v), hsv]
    have hD0 : D ∈ Divisor.degZero (K := F) (F := E.FunctionField) := by
      rw [Divisor.mem_degZero, ← Divisor.degree_pushforwardAlong ι hι D, hD]
      exact Divisor.mem_degZero.mp D'.2
    refine ⟨Pic0.mk ⟨D, hD0⟩, ?_⟩
    rw [Pic0.pushforwardAlongHom_mk]
    congr 1
    exact Subtype.ext (by rw [Pic0.coe_pushforwardAlongDegZero]; exact hD)
  intro Q
  obtain ⟨c, hc⟩ := hpush ((genusOnePic0Equiv E').symm Q)
  refine ⟨genusOnePic0Equiv E c, ?_⟩
  rw [pointMapOfPushforward_apply, ← genusOnePic0Equiv_symm_apply, AddEquiv.symm_apply_apply, hc,
    AddEquiv.apply_symm_apply]

end S_WeierstrassCurve_Affine_pointMapOfPushforward_surjective
end P2MW
export P2MW.S_WeierstrassCurve_Affine_pointMapOfPushforward_surjective (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve

universe u
theorem WeierstrassCurve.Affine.pointMapOfPushforward_surjective
    {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    (E E' : WeierstrassCurve.Affine F) [E.IsElliptic] [GenusOnePlaceGate E] [AbelTheorem E]
    [E'.IsElliptic] [GenusOnePlaceGate E'] [AbelTheorem E']
    (ι : E'.FunctionField →ₐ[F] E.FunctionField) (hι : ι.toRingHom.IsIntegral)
    (hfin : FiniteAlong F ι) (hN : NormFormulaAlong F ι hfin) :
    Function.Surjective (pointMapOfPushforward ι hι hfin hN) := _root_.P2MW.S_WeierstrassCurve_Affine_pointMapOfPushforward_surjective.solution E E' ι hι hfin hN

end publicSection
