/-
Based on Prove2Me node P2M.Dup.AlgebraicCurve.RationalFunctionField.eq_ofHeightOneSpectrum_or_eq_placeInfty
(c0f27816-d641-5c01-9328-7eb6d67b8805) by Claude (2026-09-05).

Proof based on Prove2Me submission 246310e9-5f60-5eb0-b628-f6f18800d82c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceInfty

import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_eq_placeInfty_iff_forall_ne_ofHeightOneSpectrum
import Definitions.FLT.Def_P2M_Util

/-!
# Places of K(t): the finite places and ∞

Theorem statement:
`P2M.Dup.AlgebraicCurve.RationalFunctionField.eq_ofHeightOneSpectrum_or_eq_placeInfty`
(`c0f27816-d641-5c01-9328-7eb6d67b8805`), by Claude, 2026-09-05.

Proof: submission `246310e9-5f60-5eb0-b628-f6f18800d82c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and consider the rational function field $\mathrm{RatFunc}\,K$ as a $K$-algebra.
A `Place K (RatFunc K)` is a valuation subring of $\mathrm{RatFunc}\,K$ which contains the image of
$K$ under the structure map, is not the whole field, and is a principal ideal ring. The assertion is
that every such place $v$ satisfies one of two alternatives: either there is a height-one prime $w$
of the polynomial ring $K[X]$ with $v =$ `Place.ofHeightOneSpectrum w`, that is, $v$ is the
valuation subring of the $w$-adic valuation of $K[X]$ extended to its fraction field
$\mathrm{RatFunc}\,K$; or $v =$ `placeInfty K`, the place whose valuation subring is that of
`RatFunc.inftyValuation K`, the valuation attached to the degree function at infinity. The
disjunction is stated as an inclusive `Or`, with the first alternative an existential over
height-one primes; no hypothesis beyond $v$ being a place is imposed.

This is Ostrowski's classification of the places of a rational function field over $K$
(equivalently, of the valuations of $K(t)$ trivial on $K$): the points of $\mathbb{P}^1$, namely the
closed points of the affine line together with the point at infinity. It is the basic enumeration
underlying the divisor-theoretic and local-analytic work with places of $K(t)$ in the development,
and is cited by results on orders at places and on integrality of polynomials away from infinity.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_eq_ofHeightOneSpectrum_or_eq_placeInfty.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_eq_ofHeightOneSpectrum_or_eq_placeInfty
p2m_attr_erase "instance" "AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

open IsDedekindDomain AlgebraicCurve AlgebraicCurve.RationalFunctionField

theorem solution {K : Type*} [Field K] [DecidableEq (RatFunc K)] (v : Place K (RatFunc K)) : (∃ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v = Place.ofHeightOneSpectrum w) ∨ v = placeInfty K := by
  by_cases h : ∀ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v ≠ Place.ofHeightOneSpectrum w
  · exact Or.inr ((AlgebraicCurve.RationalFunctionField.eq_placeInfty_iff_forall_ne_ofHeightOneSpectrum v).2 h)
  · push Not at h
    exact Or.inl h

end S_AlgebraicCurve_RationalFunctionField_eq_ofHeightOneSpectrum_or_eq_placeInfty
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_eq_ofHeightOneSpectrum_or_eq_placeInfty (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve AlgebraicCurve.RationalFunctionField
theorem P2M.Dup.AlgebraicCurve.RationalFunctionField.eq_ofHeightOneSpectrum_or_eq_placeInfty {K : Type*} [Field K] [DecidableEq (RatFunc K)] (v : Place K (RatFunc K)) : (∃ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v = Place.ofHeightOneSpectrum w) ∨ v = placeInfty K := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_eq_ofHeightOneSpectrum_or_eq_placeInfty.solution v

end publicSection
