/-
Based on Prove2Me node ModularForm.exists_gamma0_qExpansion_eq_of_levelOne
(de6d7e36-aff6-5cb4-ae4c-3871257781e3) by Claude (2026-09-05).

Proof based on Prove2Me submission e837a47a-7fc4-5078-8494-19044c10edd3
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.LevelOne.DimensionFormula
public import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
public import Mathlib.NumberTheory.ModularForms.QExpansion
public import Mathlib.RingTheory.LaurentSeries

import Theorems.FLT.Thm_ModularForm_exists_degeneracy_Gamma0
import Definitions.FLT.Def_P2M_Util

/-!
# A level-one form is a form for Γ₀(N)

Theorem statement: `ModularForm.exists_gamma0_qExpansion_eq_of_levelOne`
(`de6d7e36-aff6-5cb4-ae4c-3871257781e3`), by Claude, 2026-09-05.

Proof: submission `e837a47a-7fc4-5078-8494-19044c10edd3`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number that is nonzero, let $k$ be an integer, and let $F$ be a modular form of
weight $k$ for the subgroup $\mathcal{SL}$ of $\mathrm{GL}(2,\mathbb{R})$, i.e. for the image of
$\mathrm{SL}(2,\mathbb{Z})$ under the canonical map into $\mathrm{GL}(2,\mathbb{R})$ (the level-one
case). The assertion is that there exists a modular form $G$ of the same weight $k$ for the
congruence subgroup $\Gamma_0(N)$, in Mathlib's sense `CongruenceSubgroup.Gamma0 N`, whose
underlying function $\mathbb{H}\to\mathbb{C}$ is equal to that of $F$. Thus the conclusion is an
equality of functions on the upper half-plane, not merely an agreement of $q$-expansions as the name
might suggest; it says that an $\mathrm{SL}(2,\mathbb{Z})$-form, regarded as a holomorphic function
on $\mathbb{H}$, is in the image of the set of $\Gamma_0(N)$-forms under passage to the underlying
function. No hypothesis relating $N$ to $k$ or to $F$ is imposed beyond $N \neq 0$.

This is the restriction (trivial degeneracy) map from level $1$ to level $N$, stated existentially
so that subsequent statements never have to name a restriction operator; it lets level-one forms
such as $E_6^2$ and $E_4^2E_6$ be fed into statements formulated for $\Gamma_0(N)$. It is used by
the statements on $q$-expansion coefficients of cusp forms at various levels, in particular those
comparing Atkin–Lehner and Hecke operators with integrality hypotheses.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne

open UpperHalfPlane
open scoped MatrixGroups

namespace SolRESTRAux

private theorem gamma0_one_eq_top : CongruenceSubgroup.Gamma0 1 = ⊤ := by
  ext A
  simp [CongruenceSubgroup.Gamma0_mem, eq_iff_true_of_subsingleton]

private theorem gamma0_one_coe :
    ((CongruenceSubgroup.Gamma0 1 : Subgroup SL(2, ℤ)) : Subgroup (GL (Fin 2) ℝ)) = 𝒮ℒ := by
  simp [gamma0_one_eq_top, MonoidHom.range_eq_map]

private theorem heckeDiagMatrix_one : ModularForm.heckeDiagMatrix 1 = 1 := by
  apply Units.ext
  simp [Matrix.one_fin_two]

end SolRESTRAux

theorem solution (N : ℕ) [NeZero N] {k : ℤ} (F : ModularForm 𝒮ℒ k) :
    ∃ G : ModularForm (CongruenceSubgroup.Gamma0 N) k, (G : ℍ → ℂ) = (F : ℍ → ℂ) := by
  obtain ⟨G, hG⟩ := ModularForm.exists_degeneracy_Gamma0 (show 1 * 1 ∣ N by simp)
    (ModularForm.mcast rfl F SolRESTRAux.gamma0_one_coe)
  refine ⟨G, ?_⟩
  rw [hG, SolRESTRAux.heckeDiagMatrix_one]
  funext τ
  rw [one_smul]
  rfl

end S_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne
end P2MW
export P2MW.S_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne (solution)

end privateSection

public section publicSection


open UpperHalfPlane
open scoped MatrixGroups
theorem ModularForm.exists_gamma0_qExpansion_eq_of_levelOne (N : ℕ) [NeZero N] {k : ℤ} (F : ModularForm 𝒮ℒ k) : ∃ G : ModularForm (CongruenceSubgroup.Gamma0 N) k, (G : ℍ → ℂ) = (F : ℍ → ℂ) := _root_.P2MW.S_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne.solution N F

end publicSection
