/-
Based on Prove2Me node ModularCurve.ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728
(5f1a5448-3887-5ed9-a629-23d9fbc58e72) by Claude (2026-09-05).

Proof based on Prove2Me submission 63381d0b-f86d-5012-83d1-8e9a2a773211
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
public import Definitions.FLT.Def_ModularCurve_JLinePlaces

import Theorems.FLT.Thm_ModularCurve_ord_jLinePlace1728_jGen_sub
import Definitions.FLT.Def_P2M_Util

/-!
# Ramification index over j=1728 equals ord_w(j-1728)

Theorem statement: `ModularCurve.ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728`
(`5f1a5448-3887-5ed9-a629-23d9fbc58e72`), by Claude, 2026-09-05.

Proof: submission `63381d0b-f86d-5012-83d1-8e9a2a773211`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix $N \ge 1$ and let $F_N = \mathbb{Q}(j_q, j_{q^N})$ be the modular function field, i.e. the
intermediate field of $\mathbb{Q} \subseteq \mathrm{LaurentSeries}\,\mathbb{Q}$ generated by the
Laurent series $j_q = q^{-1}\cdot j\mathrm{NumQ}$ and by its image under the $q \mapsto q^N$
substitution homomorphism; regard $F_N$ as an algebra over the simple extension $\mathbb{Q}\langle
j_q\rangle$ via the inclusion of $\mathbb{Q}\langle j_q\rangle$ into $F_N$, and assume this
extension is integral. Let $w$ be a place of $F_N$ over $\mathbb{Q}$, that is, a valuation subring
of $F_N$ which contains the image of $\mathbb{Q}$, is not the whole of $F_N$, and is a principal
ideal ring. Suppose that the restriction of $w$ to $\mathbb{Q}\langle j_q\rangle$ — the valuation
subring obtained as the preimage of $w$ under the inclusion — equals
[`ModularCurve.jLinePlace1728`](def/ModularCurve_JLinePlaces.html#L50), the place of
$\mathbb{Q}\langle j_q\rangle$ transported along the isomorphism $\mathrm{RatFunc}\,\mathbb{Q} \cong
\mathbb{Q}\langle j_q\rangle$ (sending the variable to $j_q$) from the place of
$\mathrm{RatFunc}\,\mathbb{Q}$ attached to the irreducible polynomial $X - 1728$. Then the
ramification index of $w$ over $\mathbb{Q}\langle j_q\rangle$, defined as the least positive integer
of the form $\operatorname{ord}_w(\iota f)$ with $f \in \mathbb{Q}\langle j_q\rangle$ nonzero,
equals, as an integer, $\operatorname{ord}_w(j_q - 1728)$, where $j_q$ is viewed as an element of
$F_N$ and $\operatorname{ord}_w$ is minus the logarithm of the associated $\mathbb{Z}^{m0}$-valued
adic valuation.

This is the standard identification, for a place of the function field of $X_0(N)$ lying over the
point $j = 1728$ of the $j$-line, of the ramification index with the order of vanishing of $j -
1728$; it is the computational form in which ramification above the elliptic point of order $2$ is
handled. It is used in the counting of fibres over $j = 0$ and $j = 1728$, in the determination of
$\nu_2$ and $\nu_3$ for $X_0(N)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero"
p2m_attr_erase "simp" "ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

set_option synthInstance.maxHeartbeats 1600000

open IntermediateField AlgebraicCurve

theorem solution (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)),
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ = ModularCurve.jLinePlace1728 →
      (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) = w.ord ((⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) - 1728) := by
  let := ModularCurve.jAdjoinAlgebra N
  intro _ w hres
  have h := w.ord_restrict (F := ↥ℚ⟮ModularCurve.jq⟯) (ModularCurve.jGen - 1728)
  rw [map_sub, map_ofNat] at h
  rw [hres, ModularCurve.ord_jLinePlace1728_jGen_sub, mul_one] at h
  exact h.symm

end S_ModularCurve_ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728
end P2MW
export P2MW.S_ModularCurve_ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728 (solution)

end privateSection

public section publicSection


open IntermediateField AlgebraicCurve
theorem ModularCurve.ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728 (N : ℕ) [NeZero N] :
    letI := ModularCurve.jAdjoinAlgebra N
    ∀ [Algebra.IsIntegral ↥ℚ⟮ModularCurve.jq⟯ ↥(ModularCurve.modularFunctionField N)]
      (w : AlgebraicCurve.Place ℚ ↥(ModularCurve.modularFunctionField N)),
      w.restrict ↥ℚ⟮ModularCurve.jq⟯ = ModularCurve.jLinePlace1728 →
      (w.ramificationIndex ↥ℚ⟮ModularCurve.jq⟯ : ℤ) = w.ord ((⟨ModularCurve.jq, ModularCurve.jq_mem N⟩ : ↥(ModularCurve.modularFunctionField N)) - 1728) := _root_.P2MW.S_ModularCurve_ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728.solution N

end publicSection
