/-
Based on Prove2Me node CuspForm.finiteDimensional_of_isArithmetic
(3eaacdc5-f6ba-524f-b5f6-1207ebd87fc8) by Claude (2026-09-05).

Proof based on Prove2Me submission ada4bc9f-6bd1-5efa-bc1b-27ad499b21b8
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.QExpansion

import Mathlib.NumberTheory.ModularForms.CuspFormSubmodule
import Theorems.FLT.Thm_ModularForm_finiteDimensional_of_isArithmetic

/-!
# Finite-dimensionality of cusp forms for arithmetic G

Theorem statement: `CuspForm.finiteDimensional_of_isArithmetic`
(`3eaacdc5-f6ba-524f-b5f6-1207ebd87fc8`), by Claude, 2026-09-05.

Proof: submission `ada4bc9f-6bd1-5efa-bc1b-27ad499b21b8`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\mathcal{G}$ be a subgroup of $\mathrm{GL}_2(\mathbb{R})$ which is arithmetic (the Mathlib
predicate `Subgroup.IsArithmetic`) and all of whose elements have determinant one (the predicate
`Subgroup.HasDetOne`, which is what provides the $\mathbb{C}$-module structure on the space of
forms), and let $k$ be an arbitrary integer, with no positivity or parity restriction. Then the
space `CuspForm 𝒢 k` of weight-$k$ cusp forms on $\mathcal{G}$, that is, of holomorphic functions on
the upper half-plane satisfying the weight-$k$ slash invariance under $\mathcal{G}$ together with
the cuspidal decay condition at the cusps, is a finite-dimensional complex vector space. No
dimension formula, and no nonvanishing or vanishing statement for particular $k$, is asserted: the
conclusion is exactly the `FiniteDimensional ℂ (CuspForm 𝒢 k)` instance.

This is the classical finite-dimensionality theorem for spaces of cusp forms on an arithmetic group,
in the form of a typeclass instance usable for arbitrary arithmetic $\mathcal{G}$ of determinant
one. It is what makes the Hecke operators on cusp forms of level $\Gamma_0(N)$ a commuting family of
endomorphisms of a finite-dimensional space, and is invoked throughout the treatment of eigenforms,
of Eichler–Shimura cohomology and of the $q$-expansion arguments used in level changing.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_CuspForm_finiteDimensional_of_isArithmetic.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

theorem solution (𝒢 : Subgroup (GL (Fin 2) ℝ)) [𝒢.IsArithmetic] [𝒢.HasDetOne] (k : ℤ) : FiniteDimensional ℂ (CuspForm 𝒢 k) := by
  have := ModularForm.finiteDimensional_of_isArithmetic 𝒢 k
  exact Module.Finite.of_injective CuspForm.toModularFormₗ CuspForm.toModularFormₗ_injective

end privateSection

public section publicSection

open UpperHalfPlane
open scoped MatrixGroups
theorem CuspForm.finiteDimensional_of_isArithmetic (𝒢 : Subgroup (GL (Fin 2) ℝ)) [𝒢.IsArithmetic] [𝒢.HasDetOne] (k : ℤ) : FiniteDimensional ℂ (CuspForm 𝒢 k) :=
  solution 𝒢 k

end publicSection
