/-
Based on Prove2Me node ModularCurve.qExpansion_E6_eq_map_mk
(927fc600-c5bf-52bb-9838-92e6faf0f968) by Claude (2026-09-05).

Proof based on Prove2Me submission cec48452-744c-5462-9081-67e7c0622c1f
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0
public import Mathlib.NumberTheory.ModularForms.EisensteinSeries.QExpansion

import Mathlib.NumberTheory.Bernoulli
import Definitions.FLT.Def_P2M_Util

/-!
# Integral q-expansion of E₆

Theorem statement: `ModularCurve.qExpansion_E6_eq_map_mk` (`927fc600-c5bf-52bb-9838-92e6faf0f968`),
by Claude, 2026-09-05.

Proof: submission `cec48452-744c-5462-9081-67e7c0622c1f`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

The assertion is an identity of formal power series over $\mathbb{C}$. On the left is
`UpperHalfPlane.qExpansion 1` applied to the underlying function of `ModularForm.E₆`, i.e. the
$q$-expansion of width $1$ (so $q = e^{2\pi i \tau}$) of the normalised weight-$6$ Eisenstein series
for the full modular group $\mathrm{SL}_2(\mathbb{Z})$, whose $n$-th coefficient is the $n$-th
Taylor coefficient at $0$ of the function on the punctured disc induced by $E_6$. On the right is
the image, under the coefficient-wise map induced by the ring homomorphism $\mathbb{Z} \to
\mathbb{C}$, of the power series in $\mathbb{Z}[[q]]$ whose $n$-th coefficient is $1$ for $n = 0$
and $-504 \sum_{d \mid n} d^5$ for $n \ge 1$, the sum being over the divisors of $n$. Thus $E_6$ has
constant term $1$ and all coefficients integral, namely $E_6 = 1 - 504\sum_{n \ge 1}\sigma_5(n)q^n$;
there are no hypotheses or variables.

This is the classical integral $q$-expansion of the weight-$6$ normalised Eisenstein series.
Together with the analogous expansions for $E_4$ and $\Delta$ it supplies integral series with
constant term $1$ by which forms of low weight may be multiplied into weight $12$; it is invoked in
the construction of weight-one Tate-curve base changes and cusp data on modular curves of full
level.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_qExpansion_E6_eq_map_mk.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_qExpansion_E6_eq_map_mk

open UpperHalfPlane ModularForm Finset

private lemma bernoulli'_five_s18 : bernoulli' 5 = 0 :=
  bernoulli'_eq_zero_of_odd (by decide) (by norm_num)

private lemma bernoulli'_six_s18 : bernoulli' 6 = 1 / 42 := by
  rw [bernoulli'_def]
  norm_num [Finset.sum_range_succ, bernoulli'_zero, bernoulli'_one, bernoulli'_two,
    bernoulli'_three, bernoulli'_four, bernoulli'_five_s18, Nat.choose]

private lemma bernoulli_six_s18 : bernoulli 6 = 1 / 42 := by
  rw [bernoulli_eq_bernoulli'_of_ne_one (by norm_num), bernoulli'_six_s18]

theorem solution :
    UpperHalfPlane.qExpansion 1 ⇑ModularForm.E₆ =
      PowerSeries.map (Int.castRingHom ℂ)
        (PowerSeries.mk fun n => if n = 0 then 1 else -504 * ∑ d ∈ n.divisors, (d : ℤ) ^ 5) := by
  ext m
  rw [show (ModularForm.E₆ : ModularForm _ 6) = E (by norm_num : 3 ≤ 6) from rfl]
  rw [EisensteinSeries.E_qExpansion_coeff (by norm_num : 3 ≤ 6) (by decide) m]
  simp only [PowerSeries.coeff_map, PowerSeries.coeff_mk]
  split_ifs with hm
  · simp
  · have hB : (bernoulli 6 : ℂ) = 1 / 42 := by
      rw [bernoulli_six_s18]; push_cast; ring
    rw [ArithmeticFunction.sigma_apply]
    push_cast
    rw [hB]
    norm_num

end S_ModularCurve_qExpansion_E6_eq_map_mk
end P2MW
export P2MW.S_ModularCurve_qExpansion_E6_eq_map_mk (solution)

end privateSection

public section publicSection


open UpperHalfPlane ModularForm Finset
theorem ModularCurve.qExpansion_E6_eq_map_mk :
    UpperHalfPlane.qExpansion 1 ⇑ModularForm.E₆ =
      PowerSeries.map (Int.castRingHom ℂ)
        (PowerSeries.mk fun n => if n = 0 then 1 else -504 * ∑ d ∈ n.divisors, (d : ℤ) ^ 5) := _root_.P2MW.S_ModularCurve_qExpansion_E6_eq_map_mk.solution

end publicSection
