/-
Based on Prove2Me node ModularCurve.modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0
(7e38264d-3162-5273-927a-09b2aee32a0c) by Claude (2026-09-05).

Proof based on Prove2Me submission 4a58e2b3-294f-54a9-9f1f-a5c43f23a383
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0ModL
public import Definitions.FLT.Def_ModularCurve_X1

import Theorems.FLT.Thm_ModularCurve_jqModC_mem_intFormRatiosC
import Theorems.FLT.Thm_ModularCurve_qExpand_image_intFormRatiosC_subset
import Definitions.FLT.Def_P2M_Util

/-!
# Divisor expansions j(qᵈ) lie in the Γ₀(M) q-expansion field

Theorem statement: `ModularCurve.modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0`
(`7e38264d-3162-5273-927a-09b2aee32a0c`), by Claude, 2026-09-05.

Proof: submission `4a58e2b3-294f-54a9-9f1f-a5c43f23a383`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $M$ be a positive natural number. Inside the field $K((q))$ of Laurent
series over $K$ two intermediate fields over $K$ are compared. The first,
[`ModularCurve.modularFunctionFieldFullC K M`](def/ModularCurve_X0ModL.html#L100), is the subfield
generated over $K$ by the set `divisorExpansionsC K M`, namely by those Laurent series of the form
`qExpand K d (jqModC K)` for some positive divisor $d$ of $M$, where `jqModC K` is the distinguished
Laurent series attached to the modular invariant read over $K$ and `qExpand K d` is the $d$-th
$q$-substitution operator on $K((q))$. The second, [`ModularCurve.qExpFunctionFieldC K
(CongruenceSubgroup.Gamma0 M)`](def/ModularCurve_X1.html#L101), is the subfield generated over $K$
by the set `intFormRatiosC K (CongruenceSubgroup.Gamma0 M)`, consisting of all quotients `intSeriesC
K pf / intSeriesC K pg` arising from a weight $k \in \mathbb{Z}$, two modular forms $f,g$ of weight
$k$ for the image of $\Gamma_0(M)$ in $\mathrm{GL}_2(\mathbb{R})$, and integral power series $pf, pg
\in \mathbb{Z}[[q]]$ with `IsIntegralQExp f pf`, `IsIntegralQExp g pg` and `intSeriesC K pg ≠ 0`.
The assertion is the inclusion of the first field in the second.

This is the inclusion of the classical presentation of the function field of $X_0(M)$ by the divisor
expansions $j(q^d)$, $d \mid M$, into its presentation by $q$-expansions of ratios of modular forms
with integral coefficients, valid over an arbitrary coefficient field $K$. It is used throughout the
treatment of modular curves at full level and of the Diamond-type comparisons built on it.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0
p2m_attr_erase "instance" "WeierstrassCurve.Affine.Point.instFinite"
p2m_attr_erase "simp" "ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

theorem solution
    (K : Type*) [Field K] (M : ℕ) [NeZero M] :
    ModularCurve.modularFunctionFieldFullC K M ≤
      ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M) := by
  rw [ModularCurve.modularFunctionFieldFullC, IntermediateField.adjoin_le_iff]
  rintro x ⟨d, hd, hdM, rfl⟩
  have := hd
  refine ModularCurve.intFormRatiosC_subset K _ ?_
  have hle : CongruenceSubgroup.Gamma0 M ≤ CongruenceSubgroup.Gamma0 d := by
    intro γ hγ
    rw [CongruenceSubgroup.Gamma0_mem, ZMod.intCast_zmod_eq_zero_iff_dvd] at hγ ⊢
    exact (Int.natCast_dvd_natCast.mpr hdM).trans hγ
  refine ModularCurve.intFormRatiosC_mono K hle ?_
  refine ModularCurve.qExpand_image_intFormRatiosC_subset K (Γ := ⊤)
    (Γ' := CongruenceSubgroup.Gamma0 d) (Subgroup.mem_top _) d ?_
    ⟨_, ModularCurve.jqModC_mem_intFormRatiosC K ⊤, rfl⟩
  intro γ hγ
  rw [CongruenceSubgroup.Gamma0_mem, ZMod.intCast_zmod_eq_zero_iff_dvd] at hγ
  obtain ⟨c, hc⟩ := hγ
  have hdet : (γ 0 0 : ℤ) * γ 1 1 - γ 0 1 * γ 1 0 = 1 := by
    rw [← Matrix.det_fin_two]
    exact Matrix.SpecialLinearGroup.det_coe γ
  rw [hc] at hdet
  refine ⟨⟨!![γ 0 0, (d : ℤ) * γ 0 1; c, γ 1 1], ?_⟩, Subgroup.mem_top _, rfl, rfl, ?_, rfl⟩
  · rw [Matrix.det_fin_two_of]
    linear_combination hdet
  · show (d : ℤ) * c = γ 1 0
    rw [hc]

end S_ModularCurve_modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0
end P2MW
export P2MW.S_ModularCurve_modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0 (solution)

end privateSection

public section publicSection

theorem ModularCurve.modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0
    (K : Type*) [Field K] (M : ℕ) [NeZero M] :
    ModularCurve.modularFunctionFieldFullC K M ≤
      ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M) := _root_.P2MW.S_ModularCurve_modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0.solution K M

end publicSection
