/-
Based on Prove2Me node WeierstrassCurve.Affine.weilFun_ne_zero
(999c93b5-5236-5294-9ada-65ba22f44d87) by Claude (2026-09-05).

Proof based on Prove2Me submission e65112f7-f540-5cfd-8a71-dd2eefdb600b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_EllipticCurve_WeilPairingFun

import Mathlib.Data.Set.Card
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FieldSimp
import Theorems.FLT.Thm_WeierstrassCurve_Affine_weilNum_ne_zero
import Definitions.FLT.Def_P2M_Util

/-!
# Nonvanishing of the Weil function g_T for T ∈ E[n]

Theorem statement: `WeierstrassCurve.Affine.weilFun_ne_zero`
(`999c93b5-5236-5294-9ada-65ba22f44d87`), by Claude, 2026-09-05.

Proof: submission `e65112f7-f540-5cfd-8a71-dd2eefdb600b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra, $K$ algebraically closed, and let $W$ be a
Weierstrass curve over $F$ which is elliptic, such that the affine coordinate ring of the base
change $W⁄K$ is a Dedekind domain. Let $n$ be a natural number whose image in $K$ is nonzero, and
let $T$ be a point of $W⁄K$ annihilated by $n$, i.e. $(n : \mathbb{Z}) \bullet T = 0$. The assertion
is that the element `weilFun W K n T` of the function field of $W⁄K$ is nonzero. By definition this
element is the quotient, in the function field, of the images of `weilNum W K n T` and `weilNum W K
n 0` under the map from the coordinate ring, where for an integer $m$ and a point $S$ the element
`weilNum W K m S` is a chosen generator of the ideal `fibIdeal W K m S` of the coordinate ring when
that ideal is principal, and $1$ otherwise. Thus the conclusion says that the numerator attached to
$T$ and the denominator attached to the zero point are both nonzero, so that their ratio is a
nonzero element of $K(E)$.

This is the first step in the construction of the Weil pairing on $n$-torsion: the function $g_T =
P_T/P_O$ of Silverman's treatment is a well-defined nonzero element of the function field, so that
its divisor and its behaviour under translation and under field automorphisms can be analysed. It is
used by the statements comparing `weilFun` along algebra homomorphisms, under translation by torsion
points, and under isomorphisms of the underlying curve.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_weilFun_ne_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_weilFun_ne_zero
p2m_attr_erase "instance" "instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly"
p2m_attr_erase "simp" "compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two"

open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain IsDedekindDomain.HeightOneSpectrum WithZero
open scoped nonZeroDivisors

theorem solution {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] [IsDedekindDomain (W⁄K).CoordinateRing] {n : ℕ} (hn : (n : K) ≠ 0) {T : (W⁄K).Point} (hT : (n : ℤ) • T = 0) : weilFun W K n T ≠ 0 := by
  rw [weilFun]
  exact div_ne_zero
    ((map_ne_zero_iff _ (IsFractionRing.injective _ _)).mpr
      (WeierstrassCurve.Affine.weilNum_ne_zero W hn hT))
    ((map_ne_zero_iff _ (IsFractionRing.injective _ _)).mpr
      (WeierstrassCurve.Affine.weilNum_ne_zero W hn (smul_zero _)))

end S_WeierstrassCurve_Affine_weilFun_ne_zero
end P2MW
export P2MW.S_WeierstrassCurve_Affine_weilFun_ne_zero (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain WithZero

theorem WeierstrassCurve.Affine.weilFun_ne_zero {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] [IsDedekindDomain (W⁄K).CoordinateRing] {n : ℕ} (hn : (n : K) ≠ 0) {T : (W⁄K).Point} (hT : (n : ℤ) • T = 0) : weilFun W K n T ≠ 0 := _root_.P2MW.S_WeierstrassCurve_Affine_weilFun_ne_zero.solution W hn hT

end publicSection
