/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.degree_eq_zero_of_forall_eq_ord
(f5bb46d2-4a6d-59d3-a6b3-9b660446d26c) by Claude (2026-09-05).

Proof based on Prove2Me submission b7b39db5-4b47-5f92-aa17-01d45c4af7a5
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.RatFunc.Basic
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_degree_eq_zero_of_forall_eq_ord_algebraMap
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_finite_setOf_ord_ne_zero
import Definitions.FLT.Def_P2M_Util

/-!
# Divisors of rational functions on P¹ have degree zero

Theorem statement: `AlgebraicCurve.RationalFunctionField.degree_eq_zero_of_forall_eq_ord`
(`f5bb46d2-4a6d-59d3-a6b3-9b660446d26c`), by Claude, 2026-09-05.

Proof: submission `b7b39db5-4b47-5f92-aa17-01d45c4af7a5`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $f$ be an element of the rational function field $\mathrm{RatFunc}\,K$.
Here a place of $\mathrm{RatFunc}\,K$ over $K$ is a valuation subring of $\mathrm{RatFunc}\,K$ that
contains the image of $K$, is not the whole field, and is a principal ideal ring; for such a place
$v$ and an element $g$, $v.\mathrm{ord}\,g$ is the integer $-\log$ of the value of $g$ under the
$\mathbb{Z}^{m0}$-valued adic valuation attached to $v$, i.e. the order of vanishing of $g$ at $v$.
A divisor is a finitely supported function $D$ from the set of such places to $\mathbb{Z}$, and its
degree is the finite sum $\sum_v D(v)\cdot \deg v$, where $\deg v$ is the degree attached to the
place $v$. The assertion is: if $D$ is a divisor such that $D(v) = v.\mathrm{ord}\,f$ for every
place $v$ of $\mathrm{RatFunc}\,K$ over $K$, then $\mathrm{Divisor.degree}\,D = 0$. No nonvanishing
hypothesis on $f$ is imposed; for $f = 0$ the hypothesis forces $D = 0$.

This is the degree-zero property of principal divisors (the sum, or product, formula) for the
rational function field $K(t)$, that is, for $\mathbb{P}^1_K$. It underlies the computation of the
divisor class group of the rational function field and is used, among other things, to show that
places of $K(t)$ have degree one when $K$ is algebraically closed and to evaluate divisors at the
place at infinity.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_degree_eq_zero_of_forall_eq_ord.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_degree_eq_zero_of_forall_eq_ord
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation"
p2m_attr_erase "simp" "AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint"

open AlgebraicCurve
open IsDedekindDomain WithZero IsLocalRing
open scoped Polynomial

theorem solution {K : Type*} [Field K] {f : RatFunc K} (D : Divisor K (RatFunc K)) (hD : ∀ v : Place K (RatFunc K), D v = v.ord f) : Divisor.degree D = 0 := by
  rcases eq_or_ne f 0 with rfl | hf
  · have hzero : D = 0 := by
      ext v
      simp [hD v]
    rw [hzero, map_zero]
  · have hden : f.denom ≠ 0 := f.denom_ne_zero
    have hdenF : algebraMap K[X] (RatFunc K) f.denom ≠ 0 := RatFunc.algebraMap_ne_zero hden
    set Dden : Divisor K (RatFunc K) :=
      Finsupp.ofSupportFinite
        (fun v : Place K (RatFunc K) => v.ord (algebraMap K[X] (RatFunc K) f.denom))
        (AlgebraicCurve.RationalFunctionField.finite_setOf_ord_ne_zero hdenF) with hDden_def
    have hDden : ∀ v : Place K (RatFunc K),
        Dden v = v.ord (algebraMap K[X] (RatFunc K) f.denom) := fun v => rfl
    have hsplit : ∀ v : Place K (RatFunc K),
        (D + Dden) v = v.ord (algebraMap K[X] (RatFunc K) f.num) := by
      intro v
      rw [Finsupp.add_apply, hD v, hDden v]
      have hmul : f * algebraMap K[X] (RatFunc K) f.denom
          = algebraMap K[X] (RatFunc K) f.num :=
        ((div_eq_iff hdenF).mp f.num_div_denom).symm
      have h2 := v.ord_mul hf hdenF
      rw [hmul] at h2
      exact h2.symm
    have h1 := AlgebraicCurve.RationalFunctionField.degree_eq_zero_of_forall_eq_ord_algebraMap
      f.num (D + Dden) hsplit
    have h2 := AlgebraicCurve.RationalFunctionField.degree_eq_zero_of_forall_eq_ord_algebraMap
      f.denom Dden hDden
    rw [map_add, h2, add_zero] at h1
    exact h1

end S_AlgebraicCurve_RationalFunctionField_degree_eq_zero_of_forall_eq_ord
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_degree_eq_zero_of_forall_eq_ord (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.RationalFunctionField.degree_eq_zero_of_forall_eq_ord {K : Type*} [Field K] {f : RatFunc K} (D : Divisor K (RatFunc K)) (hD : ∀ v : Place K (RatFunc K), D v = v.ord f) : Divisor.degree D = 0 := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_degree_eq_zero_of_forall_eq_ord.solution D hD

end publicSection
