/-
Based on Prove2Me node WeierstrassCurve.Affine.valuation_placeOf_smul_of_algEquiv
(960a1d3b-121f-50c9-9eb3-f6901fc02dd5) by Claude (2026-09-05).

Proof based on Prove2Me submission 32603808-d20e-5b0d-bffb-52ec0361467e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.RingTheory.SimpleRing.Principal
public import Definitions.FLT.Def_EllipticCurve_FunctionFieldPullback
public import Definitions.FLT.Def_FLTPrelim_GaloisRep

import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
import Definitions.FLT.Def_P2M_Util

/-!
# Galois equivariance of the valuations v_P on K(E)

Theorem statement: `WeierstrassCurve.Affine.valuation_placeOf_smul_of_algEquiv`
(`960a1d3b-121f-50c9-9eb3-f6901fc02dd5`), by Claude, 2026-09-05.

Proof: submission `32603808-d20e-5b0d-bffb-52ec0361467e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra, let $W$ be a Weierstrass curve over $F$, and
write $W\!\!⁄K$ for its base change to $K$, with coordinate ring $(W⁄K).\mathrm{CoordinateRing}$ and
function field $(W⁄K).\mathrm{FunctionField}$. Let $\sigma$ be an $F$-algebra automorphism of $K$
and let $\Phi$ be a ring endomorphism of $(W⁄K).\mathrm{FunctionField}$ which is assumed to act on
the image of the coordinate ring by applying $\sigma$ to coefficients: for every bivariate
polynomial $p \in K[X][Y]$, $\Phi$ sends the image of the class
$\mathrm{CoordinateRing.mk}\,(W⁄K)\,p$ in the function field to the image of the class of the
polynomial obtained from $p$ by mapping all coefficients through $\sigma$. Assume the coordinate
ring of $W⁄K$ is a Dedekind domain. Let $P$ be a point of $W⁄K$ with $P \neq 0$ and with $\sigma
\bullet P \neq 0$, and let $f$ be any element of the function field. Here, for a nonzero point $Q$,
$\mathrm{placeOf}\,W\,K\,Q$ denotes the height-one prime of the coordinate ring given by the ideal
$\mathrm{XYIdeal}\,(W⁄K)\,x_Q\,(C\,y_Q)$, that is $(X - x_Q,\ Y - y_Q)$, which is maximal and
nonzero. The conclusion is that the valuation of the function field attached to the place of $\sigma
\bullet P$, evaluated at $\Phi f$, equals the valuation attached to the place of $P$, evaluated at
$f$.

This is the Galois equivariance of the orders of vanishing on an affine Weierstrass curve,
$\operatorname{ord}_{\sigma P}(f^{\sigma}) = \operatorname{ord}_{P}(f)$, i.e. the statement that a
semilinear substitution of coefficients permutes the places $\mathfrak m_P = (X - x_P, Y - y_P)$
compatibly with the action on points. It is used in
[`WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul`](thm.html#WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul),
where it shows that the conjugate of a function with prescribed divisor and the corresponding
function attached to the translated point have the same divisor, as in the proof of Galois
invariance of the Weil pairing.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv

p2m_open "Polynomial WeierstrassCurve P2MW.S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv.WeierstrassCurve WeierstrassCurve.Affine P2MW.S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv.WeierstrassCurve.Affine"
open scoped Polynomial.Bivariate
open scoped nonZeroDivisors

section GalRing

variable {F K : Type*} [Field F] [Field K] [Algebra F K] (W : WeierstrassCurve F)

theorem galRing_polynomial_map (σ : K ≃ₐ[F] K) :
    (W⁄K).polynomial.map (mapRingHom (σ : K →+* K)) = (W⁄K).polynomial := by
  have h := (baseChange_polynomial (W := W) (f := (σ : K →ₐ[F] K))).symm
  convert h using 2
  rfl

private noncomputable def galRingHom (σ : K ≃ₐ[F] K) :
    (W⁄K).CoordinateRing →+* (W⁄K).CoordinateRing :=
  AdjoinRoot.lift ((AdjoinRoot.of _).comp <| mapRingHom (σ : K →+* K))
    (AdjoinRoot.root (W⁄K).polynomial) <| by
      rw [← eval₂_map, galRing_polynomial_map, AdjoinRoot.eval₂_root]

private theorem galRingHom_mk (σ : K ≃ₐ[F] K) (p : K[X][Y]) :
    galRingHom W σ (CoordinateRing.mk (W⁄K) p) =
      CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K))) := by
  rw [galRingHom, CoordinateRing.mk, AdjoinRoot.lift_mk, ← eval₂_map]
  exact AdjoinRoot.aeval_eq <| p.map <| mapRingHom (σ : K →+* K)

private theorem galRingHom_comp (σ τ : K ≃ₐ[F] K) (z : (W⁄K).CoordinateRing) :
    galRingHom W σ (galRingHom W τ z) = galRingHom W (σ * τ) z := by
  induction z using AdjoinRoot.induction_on with
  | ih p =>
    change galRingHom W σ (galRingHom W τ (CoordinateRing.mk (W⁄K) p)) =
      galRingHom W (σ * τ) (CoordinateRing.mk (W⁄K) p)
    rw [galRingHom_mk, galRingHom_mk, galRingHom_mk, Polynomial.map_map, Polynomial.mapRingHom_comp]
    rfl

private theorem galRingHom_one (z : (W⁄K).CoordinateRing) : galRingHom W 1 z = z := by
  induction z using AdjoinRoot.induction_on with
  | ih p =>
    change galRingHom W 1 (CoordinateRing.mk (W⁄K) p) = CoordinateRing.mk (W⁄K) p
    have h1 : ((1 : K ≃ₐ[F] K) : K →+* K) = RingHom.id K := RingHom.ext fun _ => rfl
    rw [galRingHom_mk, h1, Polynomial.mapRingHom_id, Polynomial.map_id]

theorem galRing_exists (σ : K ≃ₐ[F] K) :
    ∃ φ : (W⁄K).CoordinateRing ≃+* (W⁄K).CoordinateRing, ∀ p : K[X][Y],
      φ (CoordinateRing.mk (W⁄K) p) = CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K))) := by
  refine ⟨RingEquiv.ofRingHom (galRingHom W σ) (galRingHom W σ⁻¹) ?_ ?_, galRingHom_mk W σ⟩
  · refine RingHom.ext fun z => ?_
    rw [RingHom.comp_apply, RingHom.id_apply, galRingHom_comp, mul_inv_cancel, galRingHom_one]
  · refine RingHom.ext fun z => ?_
    rw [RingHom.comp_apply, RingHom.id_apply, galRingHom_comp, inv_mul_cancel, galRingHom_one]

theorem galRing_map_XYIdeal (σ : K ≃ₐ[F] K) (φ : (W⁄K).CoordinateRing →+* (W⁄K).CoordinateRing)
    (hφ : ∀ p : K[X][Y], φ (CoordinateRing.mk (W⁄K) p) =
      CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K)))) (x y : K) :
    (CoordinateRing.XYIdeal (W⁄K) x (C y)).map φ = CoordinateRing.XYIdeal (W⁄K) (σ x) (C (σ y)) := by
  rw [CoordinateRing.XYIdeal, Ideal.map_span, Set.image_pair, CoordinateRing.XClass,
    CoordinateRing.YClass, hφ, hφ]
  simp only [Polynomial.map_sub, Polynomial.map_C, Polynomial.map_X, coe_mapRingHom, RingHom.coe_coe]
  rfl

end GalRing

namespace IsDedekindDomain
p2m_export "IsDedekindDomain" "HeightOneSpectrum.comap HeightOneSpectrum.comap_asIdeal HeightOneSpectrum.ext mk HeightOneSpectrum"
namespace HeightOneSpectrum
p2m_export "IsDedekindDomain.HeightOneSpectrum" "valuation_of_algebraMap intValuation_le_pow_iff_mem mk asIdeal comap valuation comap_asIdeal intValuation_if_neg prime intValuation"
p2m_open "IsDedekindDomain.HeightOneSpectrum IsDedekindDomain"

variable {R S K L : Type*} [CommRing R] [IsDedekindDomain R] [CommRing S] [IsDedekindDomain S]
  [Field K] [Field L] [Algebra R K] [IsFractionRing R K] [Algebra S L] [IsFractionRing S L]

omit [IsDedekindDomain R] [IsDedekindDomain S] in
theorem mem_comap_pow_iff (e : R ≃+* S) (v : HeightOneSpectrum S) (r : R) (n : ℕ) :
    r ∈ (v.comap (e : R →+* S) e.surjective).asIdeal ^ n ↔ e r ∈ v.asIdeal ^ n := by
  show r ∈ (v.asIdeal.comap e) ^ n ↔ e r ∈ v.asIdeal ^ n
  rw [← Ideal.map_symm, ← Ideal.map_pow, Ideal.map_symm, Ideal.mem_comap]

theorem intValuation_comap_ringEquiv (e : R ≃+* S) (v : HeightOneSpectrum S) (r : R) :
    (v.comap (e : R →+* S) e.surjective).intValuation r = v.intValuation (e r) := by
  by_cases hr : r = 0
  · simp [hr]
  have her : e r ≠ 0 := (map_ne_zero_iff e e.injective).mpr hr
  set w := v.comap (e : R →+* S) e.surjective
  classical

  obtain ⟨m₁, hm₁⟩ : ∃ m : ℕ, w.intValuation r = WithZero.exp (-(m : ℤ)) :=
    ⟨_, w.intValuation_if_neg hr⟩
  obtain ⟨m₂, hm₂⟩ : ∃ m : ℕ, v.intValuation (e r) = WithZero.exp (-(m : ℤ)) :=
    ⟨_, v.intValuation_if_neg her⟩
  apply le_antisymm
  · rw [hm₂, intValuation_le_pow_iff_mem, mem_comap_pow_iff, ← intValuation_le_pow_iff_mem, ← hm₂]
  · rw [hm₁, intValuation_le_pow_iff_mem, ← mem_comap_pow_iff, ← intValuation_le_pow_iff_mem, ← hm₁]

theorem valuation_comap_ringEquiv (e : R ≃+* S) (ψ : K →+* L)
    (hψ : ∀ r : R, ψ (algebraMap R K r) = algebraMap S L (e r)) (v : HeightOneSpectrum S) (x : K) :
    v.valuation L (ψ x) = (v.comap (e : R →+* S) e.surjective).valuation K x := by
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := R) x
  rw [map_div₀, hψ, hψ, map_div₀, map_div₀, valuation_of_algebraMap, valuation_of_algebraMap,
    valuation_of_algebraMap, valuation_of_algebraMap, intValuation_comap_ringEquiv,
    intValuation_comap_ringEquiv]

end IsDedekindDomain.HeightOneSpectrum

namespace WeierstrassCurve
p2m_export "WeierstrassCurve" "Affine map_map map mk map_id"
namespace Affine
p2m_export "WeierstrassCurve.Affine" "CoordinateRing.XYIdeal CoordinateRing map CoordinateRing.YClass FunctionField Point CoordinateRing.mk CoordinateRing.XClass baseChange_polynomial polynomial placeOf placeOf_asIdeal"
p2m_open "WeierstrassCurve.Affine WeierstrassCurve"

section GalA2

variable {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] (W : WeierstrassCurve F)
  (σ : K ≃ₐ[F] K) (Φ : (W⁄K).FunctionField →+* (W⁄K).FunctionField)
  (hΦ : ∀ p : K[X][Y], Φ (algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) p)) =
    algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField
      (CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K)))))

include hΦ

omit hΦ in

theorem xc_smul (P : (W⁄K).Point) : (σ • P).xc = σ P.xc := by
  rcases P with _ | ⟨x, y, h⟩
  · exact (map_zero σ).symm
  · rfl

omit hΦ in
theorem yc_smul (P : (W⁄K).Point) : (σ • P).yc = σ P.yc := by
  rcases P with _ | ⟨x, y, h⟩
  · exact (map_zero σ).symm
  · rfl

end GalA2

end WeierstrassCurve.Affine

open _root_.WeierstrassCurve.Affine _root_.P2MW.S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv.WeierstrassCurve.Affine in
theorem solution {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] (W : WeierstrassCurve F) (σ : K ≃ₐ[F] K) (Φ : (W⁄K).FunctionField →+* (W⁄K).FunctionField) (hΦ : ∀ p : K[X][Y], Φ (algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) p)) = algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K))))) [IsDedekindDomain (W⁄K).CoordinateRing] {P : (W⁄K).Point} (hP : P ≠ 0) (hσP : σ • P ≠ 0) (f : (W⁄K).FunctionField) : (placeOf W K (σ • P) hσP).valuation (W⁄K).FunctionField (Φ f) = (placeOf W K P hP).valuation (W⁄K).FunctionField f := by
  obtain ⟨φ, hφ⟩ := galRing_exists W σ

  have hΦφ : ∀ a : (W⁄K).CoordinateRing, Φ (algebraMap _ (W⁄K).FunctionField a) =
      algebraMap _ (W⁄K).FunctionField (φ a) := by
    intro a
    induction a using AdjoinRoot.induction_on with
    | ih g => exact (hΦ g).trans (congrArg _ (hφ g).symm)
  have hv : (placeOf W K (σ • P) hσP).comap (φ : (W⁄K).CoordinateRing →+* (W⁄K).CoordinateRing)
      φ.surjective = placeOf W K P hP := by
    apply IsDedekindDomain.HeightOneSpectrum.ext
    rw [IsDedekindDomain.HeightOneSpectrum.comap_asIdeal, placeOf_asIdeal, placeOf_asIdeal, xc_smul W σ,
      yc_smul W σ, ← galRing_map_XYIdeal W σ (φ : (W⁄K).CoordinateRing →+* (W⁄K).CoordinateRing) hφ]
    exact Ideal.comap_map_of_bijective _ φ.bijective
  rw [IsDedekindDomain.HeightOneSpectrum.valuation_comap_ringEquiv φ Φ hΦφ, hv]

end S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv
end P2MW
export P2MW.S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv (solution)

end privateSection

public section publicSection


open Polynomial WeierstrassCurve WeierstrassCurve.Affine
open scoped Polynomial.Bivariate

theorem WeierstrassCurve.Affine.valuation_placeOf_smul_of_algEquiv {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] (W : WeierstrassCurve F) (σ : K ≃ₐ[F] K) (Φ : (W⁄K).FunctionField →+* (W⁄K).FunctionField) (hΦ : ∀ p : K[X][Y], Φ (algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) p)) = algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K))))) [IsDedekindDomain (W⁄K).CoordinateRing] {P : (W⁄K).Point} (hP : P ≠ 0) (hσP : σ • P ≠ 0) (f : (W⁄K).FunctionField) : (placeOf W K (σ • P) hσP).valuation (W⁄K).FunctionField (Φ f) = (placeOf W K P hP).valuation (W⁄K).FunctionField f := _root_.P2MW.S_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv.solution W σ Φ hΦ hP hσP f

end publicSection
