/-
Based on Prove2Me node ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar_unconditional
(40b3b606-783f-5e60-aab1-b951a2e6ec77) by Claude (2026-09-05).

Proof based on Prove2Me submission aea74966-fcd9-50d1-bc1c-bcf730c6bbd1
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ArithmeticGalois

import Definitions.FLT.Def_ModularCurve_PhiGen
import Theorems.FLT.Thm_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar
import Theorems.FLT.Thm_ModularCurve_modularPolynomialFamily
import Definitions.FLT.Def_P2M_Util

/-!
# Unconditional principal divisors on ℚ̄-modular function fields

Theorem statement: `ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar_unconditional`
(`40b3b606-783f-5e60-aab1-b951a2e6ec77`), by Claude, 2026-09-05.

Proof: submission `aea74966-fcd9-50d1-bc1c-bcf730c6bbd1`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $M$ be a natural number, assumed nonzero. Consider the field $F = \overline{\mathbb{Q}}((q))$ of
Laurent series over an algebraic closure of $\mathbb{Q}$ and inside it the intermediate field
$\overline{\mathbb{Q}}$-generated by the image, under the coefficientwise embedding $\mathbb{Q}((q))
\to \overline{\mathbb{Q}}((q))$, of the field `modularFunctionFieldFull M`, the subfield of
$\mathbb{Q}((q))$ obtained by adjoining to $\mathbb{Q}$ the family of Laurent series
`divisorExpansions M`; this intermediate field is `modularFunctionFieldBar M`. The assertion is that
the pair $(\overline{\mathbb{Q}}, \mathtt{modularFunctionFieldBar } M)$ satisfies
`HasPrincipalDivisors`: for every nonzero element $f$ of `modularFunctionFieldBar M` there is a
finitely supported function $D$ from the places of this field over $\overline{\mathbb{Q}}$ to
$\mathbb{Z}$ — a place being a valuation subring, different from the whole field, which contains the
image of $\overline{\mathbb{Q}}$ and is a principal ideal ring — such that $D(v) =
\operatorname{ord}_v(f)$ for every place $v$, and such that $\sum_v D(v)\cdot \deg v = 0$. In
particular $f$ has only finitely many zeros and poles, and its divisor has degree zero. There are no
hypotheses beyond $M \neq 0$.

This is the function-field statement that a principal divisor is well defined and has degree zero,
in the form needed for the modular function fields of level $M$ realised as $q$-expansion fields
over $\overline{\mathbb{Q}}$. It is the hypothesis-free version of the corresponding conditional
result, and serves as the principal-divisors input to the constructions of places, divisor class
groups and Hecke operators on modular curves further along in the development.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar_unconditional.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar_unconditional
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy"
p2m_attr_erase "simp" "ModularCurve.jqNModC_one AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

open ModularCurve AlgebraicCurve

theorem solution (M : ℕ) [NeZero M] :
    HasPrincipalDivisors (AlgebraicClosure ℚ) (modularFunctionFieldBar M) :=
  hasPrincipalDivisors_modularFunctionFieldBar modularPolynomialFamily M

end S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar_unconditional
end P2MW
export P2MW.S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar_unconditional (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve AlgebraicCurve
theorem ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar_unconditional (M : ℕ) [NeZero M] :
    HasPrincipalDivisors (AlgebraicClosure ℚ) (modularFunctionFieldBar M) := _root_.P2MW.S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar_unconditional.solution M

end publicSection
