/-
Based on Prove2Me node Polynomial.irreducible_of_transitive_ringAut
(763351d7-5da4-5854-bb26-2f75fc84e0e7) by Claude (2026-09-05).

Proof based on Prove2Me submission d7f4eaeb-1dc2-5c76-9fab-2dcba212579a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Algebra.Polynomial.Splits

import Mathlib.Algebra.Polynomial.FieldDivision
import Definitions.FLT.Def_P2M_Util

/-!
# Irreducibility from an automorphism cycling all but one root

Theorem statement: `Polynomial.irreducible_of_transitive_ringAut`
(`763351d7-5da4-5854-bb26-2f75fc84e0e7`), by Claude, 2026-09-05.

Proof: submission `d7f4eaeb-1dc2-5c76-9fab-2dcba212579a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $L$ be fields with $L$ an $F$-algebra, and let $P \in F[X]$ be monic and such that its
image $P^{L}$ under the coefficient map $F \to L$ splits over $L$. Let $\sigma : L \to L$ be a ring
automorphism of $L$ fixing every element of the image of $F$ in $L$, i.e.
$\sigma(\mathrm{algebraMap}\,a) = \mathrm{algebraMap}\,a$ for all $a \in F$. Suppose given $y_0 \in
L$, a sequence $r : \mathbb{N} \to L$ and a natural number $n$ such that the multiset of roots of
$P^{L}$ is exactly $y_0$ together with $r(0), \dots, r(n-1)$ (the image of $\{0,\dots,n-1\}$ under
$r$), that this multiset of roots has no repetitions, that $\sigma(r(i)) = r((i+1) \bmod n)$ for
every $i < n$, so that $\sigma$ permutes $r(0), \dots, r(n-1)$ cyclically, and that $y_0$ does not
lie in the image of $F$ in $L$. Then $P$ is irreducible in $F[X]$.

This is the standard orbit argument for irreducibility: a monic polynomial split with simple roots
over $L$, whose roots other than a distinguished one form a single cycle under an $F$-fixing
automorphism of $L$, cannot factor nontrivially once the distinguished root is irrational over $F$.
It is applied in the algebraic theory of the modular curve $X_0(N)$, where it supplies the
irreducibility input for the computations of $\mathrm{finrank}$ of fields generated by values
$j(q^N)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_Polynomial_irreducible_of_transitive_ringAut.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_Polynomial_irreducible_of_transitive_ringAut

p2m_open "Polynomial P2MW.S_Polynomial_irreducible_of_transitive_ringAut.Polynomial"

namespace Polynomial
p2m_export "Polynomial" "C Splits.of_dvd card_roots' coeff_map natDegree_mul coeff unique aeval coeff_C_zero Splits.of_natDegree_eq_one degree factor IsRoot.def map_map Splits map mem_roots eq_zero_of_natDegree_lt_card_of_eval_eq_zero' Monic comp roots natDegree_eq_card_roots roots.le_of_dvd natDegree eval_C natDegree_sub_le eval_sub natDegree_map map_dvd natDegree_C mod eval_map_algebraMap ext roots_map IsRoot ring roots_mul"
end Polynomial
p2m_open_scoped "Polynomial" in

private theorem Polynomial.mem_range_of_unique_common_root {F L : Type*} [Field F] [Field L] [Algebra F L]
    (A B : Polynomial F) (hA : A ≠ 0) (hAs : (A.map (algebraMap F L)).Splits)
    (hAnd : (A.map (algebraMap F L)).roots.Nodup) (x : L) (hxA : Polynomial.aeval x A = 0)
    (hxB : Polynomial.aeval x B = 0) (huniq : ∀ y : L, Polynomial.aeval y A = 0 → Polynomial.aeval y B = 0 → y = x) :
    x ∈ (algebraMap F L).range := by
  classical
  set i := algebraMap F L with hi
  set g := EuclideanDomain.gcd A B with hg
  have hg0 : g ≠ 0 := fun h => hA (EuclideanDomain.gcd_eq_zero_iff.mp h).1
  have hgA : g ∣ A := EuclideanDomain.gcd_dvd_left _ _
  have hgB : g ∣ B := EuclideanDomain.gcd_dvd_right _ _
  have hAm0 : A.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hA
  have hgm0 : g.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hg0
  have hxg : Polynomial.aeval x g = 0 := by
    rw [hg, EuclideanDomain.gcd_eq_gcd_ab A B, map_add, map_mul, map_mul, hxA, hxB, zero_mul, zero_mul,
      add_zero]
  have hroot_eq : ∀ y ∈ (g.map i).roots, y = x := by
    intro y hy
    rw [Polynomial.mem_roots hgm0, Polynomial.IsRoot.def, Polynomial.eval_map_algebraMap] at hy
    refine huniq y ?_ ?_
    · obtain ⟨c, hc⟩ := hgA
      rw [hc, map_mul, hy, zero_mul]
    · obtain ⟨c, hc⟩ := hgB
      rw [hc, map_mul, hy, zero_mul]
  have hxmem : x ∈ (g.map i).roots := by
    rw [Polynomial.mem_roots hgm0, Polynomial.IsRoot.def, Polynomial.eval_map_algebraMap]; exact hxg
  have hle : (g.map i).roots ≤ (A.map i).roots := Polynomial.roots.le_of_dvd hAm0 (Polynomial.map_dvd i hgA)
  have hnd : (g.map i).roots.Nodup := Multiset.nodup_of_le hle hAnd
  have hcount : (g.map i).roots.count x = Multiset.card (g.map i).roots :=
    Multiset.count_eq_card.mpr fun y hy => (hroot_eq y hy).symm
  have hcard : Multiset.card (g.map i).roots = 1 := by
    have h1 : (g.map i).roots.count x ≤ 1 := Multiset.nodup_iff_count_le_one.mp hnd x
    have h2 : 0 < (g.map i).roots.count x := Multiset.count_pos.mpr hxmem
    omega
  have hgs : (g.map i).Splits := Polynomial.Splits.of_dvd hAs hAm0 (Polynomial.map_dvd i hgA)
  have hdeg : g.natDegree = 1 := by
    rw [← Polynomial.natDegree_map i, hgs.natDegree_eq_card_roots, hcard]
  have hgsF : g.Splits := Polynomial.Splits.of_natDegree_eq_one hdeg
  exact hgsF.mem_range_of_isRoot hg0 ((Polynomial.mem_roots hgm0).mp hxmem)

p2m_open_scoped "Polynomial" in

private theorem Polynomial.mem_range_of_eval_eq_const {F L : Type*} [Field F] [Field L] [Algebra F L]
    (g : Polynomial F) (x : L) (s : Finset L) (hcard : g.natDegree < s.card)
    (hval : ∀ y ∈ s, Polynomial.aeval y g = x) : x ∈ (algebraMap F L).range := by
  classical
  set i := algebraMap F L
  set Q : Polynomial L := g.map i - Polynomial.C x with hQ
  have hQdeg : Q.natDegree ≤ g.natDegree := by
    refine (Polynomial.natDegree_sub_le _ _).trans ?_
    rw [Polynomial.natDegree_map, Polynomial.natDegree_C, max_eq_left (Nat.zero_le _)]
  have hQ0 : Q = 0 := by
    refine Polynomial.eq_zero_of_natDegree_lt_card_of_eval_eq_zero' Q s (fun y hy => ?_) (hQdeg.trans_lt hcard)
    rw [hQ, Polynomial.eval_sub, Polynomial.eval_C, Polynomial.eval_map_algebraMap, hval y hy, sub_self]
  have hconst : g.map i = Polynomial.C x := sub_eq_zero.mp hQ0
  refine ⟨g.coeff 0, ?_⟩
  have := congrArg (fun P : Polynomial L => P.coeff 0) hconst
  simpa only [Polynomial.coeff_map, Polynomial.coeff_C_zero] using this

p2m_open_scoped "Polynomial" in

private theorem Polynomial.irreducible_of_transitive_ringAut {F L : Type*} [Field F] [Field L] [Algebra F L]
    (P : Polynomial F) (hP : P.Monic) (hPs : (P.map (algebraMap F L)).Splits) (σ : L ≃+* L)
    (hσ : ∀ a : F, σ (algebraMap F L a) = algebraMap F L a) (y₀ : L) (r : ℕ → L) (n : ℕ)
    (hroots : (P.map (algebraMap F L)).roots = y₀ ::ₘ (Multiset.range n).map r)
    (hnodup : (P.map (algebraMap F L)).roots.Nodup) (hcycle : ∀ i < n, σ (r i) = r ((i + 1) % n))
    (hy₀ : y₀ ∉ (algebraMap F L).range) : Irreducible P := by
  classical
  set i := algebraMap F L with hi
  have hσi : (σ : L →+* L).comp i = i := RingHom.ext fun a => hσ a
  have hPm0 : P.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hP.ne_zero
  have hPdeg : P.natDegree = n + 1 := by
    rw [← Polynomial.natDegree_map i, hPs.natDegree_eq_card_roots, hroots, Multiset.card_cons, Multiset.card_map,
      Multiset.card_range]
  have hy₀_notin : y₀ ∉ (Multiset.range n).map r := by
    rw [hroots] at hnodup; exact (Multiset.nodup_cons.mp hnodup).1
  have hr_nodup : ((Multiset.range n).map r).Nodup := by
    rw [hroots] at hnodup; exact (Multiset.nodup_cons.mp hnodup).2
  have key : ∀ f g : Polynomial F, f.Monic → g.Monic → f * g = P → y₀ ∈ (f.map i).roots → g.natDegree = 0 := by
    intro f g hf hg hfg hyf
    have hfm0 : f.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hf.ne_zero
    have hgm0 : g.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hg.ne_zero
    have hsplit : (P.map i).roots = (f.map i).roots + (g.map i).roots := by
      rw [← hfg, Polynomial.map_mul, Polynomial.roots_mul (mul_ne_zero hfm0 hgm0)]
    have hgle : (g.map i).roots ≤ (P.map i).roots := by rw [hsplit]; exact Multiset.le_add_left _ _
    have hg_nd : (g.map i).roots.Nodup := Multiset.nodup_of_le hgle hnodup
    have hy₀g : y₀ ∉ (g.map i).roots := by
      intro hyg
      have h2 : 2 ≤ (P.map i).roots.count y₀ := by
        rw [hsplit, Multiset.count_add]
        have := Multiset.count_pos.mpr hyf; have := Multiset.count_pos.mpr hyg; omega
      have h1 := Multiset.nodup_iff_count_le_one.mp hnodup y₀
      omega
    have hgsub : ∀ y ∈ (g.map i).roots, y ∈ (Multiset.range n).map r := by
      intro y hy
      have : y ∈ (P.map i).roots := Multiset.mem_of_le hgle hy
      rw [hroots, Multiset.mem_cons] at this
      rcases this with rfl | h
      · exact absurd hy hy₀g
      · exact h
    have hgs : (g.map i).Splits := Polynomial.Splits.of_dvd hPs hPm0 (by rw [← hfg, Polynomial.map_mul]; exact dvd_mul_left _ _)
    have hstable : ((g.map i).roots).map (σ : L →+* L) = (g.map i).roots := by
      rw [← hgs.roots_map (σ : L →+* L), Polynomial.map_map, hσi]
    have hmemσ : ∀ y ∈ (g.map i).roots, σ y ∈ (g.map i).roots := by
      intro y hy
      rw [← hstable]; exact Multiset.mem_map.mpr ⟨y, hy, rfl⟩
    by_contra hgdeg
    have hgroots_ne : (g.map i).roots ≠ 0 := by
      intro h0
      apply hgdeg
      rw [← Polynomial.natDegree_map i, hgs.natDegree_eq_card_roots, h0, Multiset.card_zero]
    obtain ⟨y, hy⟩ := Multiset.exists_mem_of_ne_zero hgroots_ne
    obtain ⟨j₀, hj₀, rfl⟩ := Multiset.mem_map.mp (hgsub y hy)
    rw [Multiset.mem_range] at hj₀
    have hnpos : 0 < n := lt_of_le_of_lt (Nat.zero_le _) hj₀
    have horbit : ∀ k : ℕ, r ((j₀ + k) % n) ∈ (g.map i).roots := by
      intro k
      induction k with
      | zero => rwa [add_zero, Nat.mod_eq_of_lt hj₀]
      | succ k ih =>
        have h1 := hmemσ _ ih
        rw [hcycle _ (Nat.mod_lt _ hnpos), Nat.mod_add_mod, add_assoc] at h1
        exact h1
    have hall : ∀ j < n, r j ∈ (g.map i).roots := by
      intro j hj
      have := horbit (j + n - j₀)
      have e : (j₀ + (j + n - j₀)) % n = j := by
        rw [show j₀ + (j + n - j₀) = j + n by omega, Nat.add_mod_right, Nat.mod_eq_of_lt hj]
      rwa [e] at this
    have hle : (Multiset.range n).map r ≤ (g.map i).roots := by
      rw [Multiset.le_iff_subset hr_nodup]
      intro y hy
      obtain ⟨j, hj, rfl⟩ := Multiset.mem_map.mp hy
      exact hall j (Multiset.mem_range.mp hj)
    have hgdeg_ge : n ≤ g.natDegree := by
      rw [← Polynomial.natDegree_map i, hgs.natDegree_eq_card_roots]
      simpa using Multiset.card_le_card hle
    have hsum : f.natDegree + g.natDegree = n + 1 := by rw [← hf.natDegree_mul hg, hfg, hPdeg]
    have hfdeg_pos : 1 ≤ f.natDegree := by
      rw [← Polynomial.natDegree_map i]
      have := Polynomial.card_roots' (f.map i)
      have hpos : 0 < Multiset.card (f.map i).roots := Multiset.card_pos_iff_exists_mem.mpr ⟨y₀, hyf⟩
      omega
    have hfdeg : f.natDegree = 1 := by omega
    have hfs : f.Splits := Polynomial.Splits.of_natDegree_eq_one hfdeg
    exact hy₀ (hfs.mem_range_of_isRoot hf.ne_zero ((Polynomial.mem_roots hfm0).mp hyf))
  rw [hP.irreducible_iff_natDegree]
  refine ⟨fun h1 => by simp [h1] at hPdeg, fun f g hf hg hfg => ?_⟩
  have hfm0 : f.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hf.ne_zero
  have hgm0 : g.map i ≠ 0 := (Polynomial.map_ne_zero_iff i.injective).mpr hg.ne_zero
  have hy₀P : y₀ ∈ (P.map i).roots := by rw [hroots]; exact Multiset.mem_cons_self _ _
  rw [← hfg, Polynomial.map_mul, Polynomial.roots_mul (mul_ne_zero hfm0 hgm0), Multiset.mem_add] at hy₀P
  rcases hy₀P with h | h
  · exact Or.inr (key f g hf hg hfg h)
  · exact Or.inl (key g f hg hf (by rw [mul_comm]; exact hfg) h)

theorem solution {F L : Type*} [Field F] [Field L] [Algebra F L] (P : Polynomial F) (hP : P.Monic) (hPs : (P.map (algebraMap F L)).Splits) (σ : L ≃+* L) (hσ : ∀ a : F, σ (algebraMap F L a) = algebraMap F L a) (y₀ : L) (r : ℕ → L) (n : ℕ) (hroots : (P.map (algebraMap F L)).roots = y₀ ::ₘ (Multiset.range n).map r) (hnodup : (P.map (algebraMap F L)).roots.Nodup) (hcycle : ∀ i < n, σ (r i) = r ((i + 1) % n)) (hy₀ : y₀ ∉ (algebraMap F L).range) : Irreducible P :=
  Polynomial.irreducible_of_transitive_ringAut P hP hPs σ hσ y₀ r n hroots hnodup hcycle hy₀

end S_Polynomial_irreducible_of_transitive_ringAut
end P2MW
export P2MW.S_Polynomial_irreducible_of_transitive_ringAut (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem Polynomial.irreducible_of_transitive_ringAut {F L : Type*} [Field F] [Field L] [Algebra F L] (P : Polynomial F) (hP : P.Monic) (hPs : (P.map (algebraMap F L)).Splits) (σ : L ≃+* L) (hσ : ∀ a : F, σ (algebraMap F L a) = algebraMap F L a) (y₀ : L) (r : ℕ → L) (n : ℕ) (hroots : (P.map (algebraMap F L)).roots = y₀ ::ₘ (Multiset.range n).map r) (hnodup : (P.map (algebraMap F L)).roots.Nodup) (hcycle : ∀ i < n, σ (r i) = r ((i + 1) % n)) (hy₀ : y₀ ∉ (algebraMap F L).range) : Irreducible P := _root_.P2MW.S_Polynomial_irreducible_of_transitive_ringAut.solution P hP hPs σ hσ y₀ r n hroots hnodup hcycle hy₀

end publicSection
