/-
Based on Prove2Me node HeckeEis.exists_isEichlerIntegral_isParabolicCocycle
(a51d2af1-1c2b-53cc-b2bc-fe0a19f583c2) by Claude (2026-09-05).

Proof based on Prove2Me submission 8cc46642-0fa3-54b4-9912-76cccdb56d44
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.Basic
public import Definitions.FLT.Def_HeckeEis_EichlerIntegral

import Theorems.FLT.Thm_HeckeEis_exists_isEichlerIntegral
import Theorems.FLT.Thm_HeckeEis_isEquivariantPrimitiveWith_of_isEichlerIntegral
import Theorems.FLT.Thm_HeckeEis_isParabolicCocycle_cocycle_of_isEichlerIntegral
import Definitions.FLT.Def_P2M_Util

/-!
# Existence of a parabolic Eichler integral for Γ₀(N) cusp forms

Theorem statement: `HeckeEis.exists_isEichlerIntegral_isParabolicCocycle`
(`a51d2af1-1c2b-53cc-b2bc-fe0a19f583c2`), by Claude, 2026-09-05.

Proof: submission `8cc46642-0fa3-54b4-9912-76cccdb56d44`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N\ge 1$ and $n\ge 0$ be natural numbers and let $f$ be a cusp form of weight $n+2$ for
$\Gamma_0(N)$. Write $\mathrm{BinaryForm}\,\mathbb{C}\,n$ for the submodule of homogeneous
polynomials of degree $n$ in $\mathbb{C}[X_0,X_1]$, and let $\rho$ be the representation
`binaryFormRepSL` of $\mathrm{SL}_2(\mathbb{Z})$ on it by the substitution $X_j\mapsto\sum_i
g_{ij}X_i$, restricted along the inclusion of $\Gamma_0(N)$. The assertion is that there is a
function $F$ from the upper half-plane to $\mathrm{BinaryForm}\,\mathbb{C}\,n$ which is an Eichler
integral of $f$ in the sense that for every exponent vector $d$ and every $\tau\in\mathfrak{H}$ the
coefficient function $z\mapsto \mathrm{coeff}_d\,F(z)$ is complex differentiable at $\tau$ with
derivative $f(\tau)\cdot\mathrm{coeff}_d\big((\tau X_0+X_1)^n\big)$; that $F$ is an equivariant
primitive for $\rho$, i.e. for each $\gamma\in\Gamma_0(N)$ the difference
$F(\gamma\tau)-\rho(\gamma)F(\tau)$ is independent of $\tau$; and that the resulting cocycle
$z(\gamma)=F(\gamma\cdot i)-\rho(\gamma)F(i)$ is parabolic, meaning
$z(\gamma)\in\mathrm{range}(\rho(\gamma)-1)$ for every $\gamma\in\Gamma_0(N)$ with
$(\operatorname{tr}\gamma)^2=4$. In Lean the equivariance is existentially quantified as a proof
term $hF$ whose associated cocycle is required to be parabolic; the definition of the cocycle
ignores that proof argument.

This is the existence statement underlying the Eichler–Shimura construction: every cusp form of
weight $n+2$ on $\Gamma_0(N)$ has an Eichler integral whose period cocycle is a parabolic
$1$-cocycle with values in the space of binary forms of degree $n$. It is what guarantees that the
Eichler–Shimura map sends $f$ to the class of its period cocycle in parabolic cohomology, and it is
used in the lemmas describing that map's additivity and its compatibility with the Hecke operators
$T_\ell$ and $U_\ell$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_exists_isEichlerIntegral_isParabolicCocycle.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HeckeEis_exists_isEichlerIntegral_isParabolicCocycle

open scoped Manifold MatrixGroups ModularForm

theorem solution (N n : ℕ) [NeZero N]
    (f : CuspForm (CongruenceSubgroup.Gamma0 N) ((n : ℤ) + 2)) :
    ∃ F : UpperHalfPlane → ↥(HeckeEis.BinaryForm ℂ n), HeckeEis.IsEichlerIntegral n f F ∧
      ∃ hF : HeckeEis.IsEquivariantPrimitiveWith
          ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) F,
        HeckeEis.IsParabolicCocycle
          ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) hF.cocycle := by
  obtain ⟨F, hEI⟩ := HeckeEis.exists_isEichlerIntegral n (f := (f : UpperHalfPlane → ℂ)) (CuspFormClass.holo f)
  have hF : HeckeEis.IsEquivariantPrimitiveWith
      ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) F :=
    HeckeEis.isEquivariantPrimitiveWith_of_isEichlerIntegral hEI
      (fun γ hγ => SlashInvariantFormClass.slash_action_eq f _ (Subgroup.mem_map_of_mem _ hγ))
  exact ⟨F, hEI, hF, HeckeEis.isParabolicCocycle_cocycle_of_isEichlerIntegral N n f hEI hF⟩

end S_HeckeEis_exists_isEichlerIntegral_isParabolicCocycle
end P2MW
export P2MW.S_HeckeEis_exists_isEichlerIntegral_isParabolicCocycle (solution)

end privateSection

public section publicSection


open scoped Manifold MatrixGroups
theorem HeckeEis.exists_isEichlerIntegral_isParabolicCocycle (N n : ℕ) [NeZero N]
    (f : CuspForm (CongruenceSubgroup.Gamma0 N) ((n : ℤ) + 2)) :
    ∃ F : UpperHalfPlane → ↥(HeckeEis.BinaryForm ℂ n), HeckeEis.IsEichlerIntegral n f F ∧
      ∃ hF : HeckeEis.IsEquivariantPrimitiveWith
          ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) F,
        HeckeEis.IsParabolicCocycle
          ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) hF.cocycle := _root_.P2MW.S_HeckeEis_exists_isEichlerIntegral_isParabolicCocycle.solution N n f

end publicSection
