/-
Based on Prove2Me node AlgebraicCurve.Divisor.evalFun_ne_zero
(29cc4c02-b576-5ba0-87c4-3dccf09e4ec9) by Claude (2026-09-05).

Proof based on Prove2Me submission 014767c6-0e15-5ccc-b2df-7916e0dca41e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_PlaceEvaluation

import Definitions.FLT.Def_P2M_Util

/-!
# Non-vanishing of f(D) when f avoids the support of D

Theorem statement: `AlgebraicCurve.Divisor.evalFun_ne_zero`
(`29cc4c02-b576-5ba0-87c4-3dccf09e4ec9`), by Claude, 2026-09-05.

Proof: submission `014767c6-0e15-5ccc-b2df-7916e0dca41e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, let $f \in F$, and let $D$ be a divisor of $F/K$,
i.e. a finitely supported function from the type `Place K F` of places to $\mathbb{Z}$; here a place
$v$ is a valuation subring of $F$ which contains $\operatorname{algebraMap} K F(a)$ for every $a \in
K$, is not all of $F$, and is a principal ideal ring. For a place $v$, the evaluation
$\operatorname{evalAt} v f \in K$ is defined to be the image of the residue class of $f$ in the
residue field of $v$ under a fixed set-theoretic inverse (`Function.invFun`) of the structure map $K
\to v$'s residue field, when $f$ lies in the valuation subring of $v$, and $0$ otherwise. The
hypothesis is that $\operatorname{evalAt} v f \neq 0$ for every $v$ in the (finite) support of $D$.
The conclusion is that $\operatorname{evalFun} f D \neq 0$, where $\operatorname{evalFun} f D =
\prod_{v \in \operatorname{supp} D} (\operatorname{evalAt} v f)^{D(v)}$, the exponents being
integers.

This is the basic non-degeneracy statement for the evaluation $f(D)$ of a function at a divisor (the
local symbol underlying Weil reciprocity), in the form needed to know that $f(D)$ lies in $K^\times$
once $f$ is regular and non-vanishing at each place in the support of $D$. It is used in the
function-field layer on which the rational function field computations rest, for instance in
identifying evaluations at the place at infinity and at places coming from points, and in the degree
computation over an algebraically closed field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Divisor_evalFun_ne_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Divisor_evalFun_ne_zero

open AlgebraicCurve

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] {f : F} {D : Divisor K F} (h : ∀ v ∈ D.support, Place.evalAt v f ≠ 0) : Divisor.evalFun f D ≠ 0 := by
  rw [Divisor.evalFun_def]
  exact Finset.prod_ne_zero_iff.mpr fun v hv => zpow_ne_zero _ (h v hv)

end S_AlgebraicCurve_Divisor_evalFun_ne_zero
end P2MW
export P2MW.S_AlgebraicCurve_Divisor_evalFun_ne_zero (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Divisor.evalFun_ne_zero {K F : Type*} [Field K] [Field F] [Algebra K F] {f : F} {D : Divisor K F} (h : ∀ v ∈ D.support, Place.evalAt v f ≠ 0) : Divisor.evalFun f D ≠ 0 := _root_.P2MW.S_AlgebraicCurve_Divisor_evalFun_ne_zero.solution h

end publicSection
