/-
Based on Prove2Me node AlgebraicCurve.isIntegral_adjoin_of_forall_mem_toValuationSubring
(ec854fae-ead3-5215-b9ae-f4ef7f1f629d) by Claude (2026-09-05).

Proof based on Prove2Me submission 1c32ddb7-91c8-5b09-90d0-3a34c3d2ac4b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Mathlib.RingTheory.Valuation.LocalSubring
import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_of_valuationSubring_of_isSeparable
import Definitions.FLT.Def_P2M_Util

/-!
# Integrality over K[t] from membership in all places containing t

Theorem statement: `AlgebraicCurve.isIntegral_adjoin_of_forall_mem_toValuationSubring`
(`ec854fae-ead3-5215-b9ae-f4ef7f1f629d`), by Claude, 2026-09-05.

Proof: submission `1c32ddb7-91c8-5b09-90d0-3a34c3d2ac4b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and suppose there is an element $x \in F$ such
that $F$ is finite-dimensional and separable over the intermediate field $K(x) =$
`IntermediateField.adjoin K {x}`. Let $t, z \in F$, and assume that for every place $v$ of $F$ over
$K$ — that is, for every structure consisting of a valuation subring $\mathcal{O}_v \subseteq F$
which contains $\mathrm{algebraMap}\,K\,F\,a$ for all $a \in K$, is not the whole of $F$, and is a
principal ideal ring — the implication $t \in \mathcal{O}_v \Rightarrow z \in \mathcal{O}_v$ holds.
Then $z$ is integral over the $K$-subalgebra $K[t] =$ `Algebra.adjoin K {t}` of $F$, i.e. $z$
satisfies a monic polynomial with coefficients in $K[t]$. No hypothesis on the characteristic of $K$
is imposed, and the hypothesis on places is phrased by membership in the valuation subrings rather
than by inequalities between valuations.

This is the standard characterisation of the integral closure of $K[t]$ in a function field as the
intersection of the valuation rings of the places at which $t$ is regular, in the form needed for
the project's theory of algebraic curves. It is used in the construction of regular prolongations
and in the characteristic-$p$ models of modular curves, where integrality over a coordinate ring
must be deduced from local regularity at all places.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_isIntegral_adjoin_of_forall_mem_toValuationSubring.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_isIntegral_adjoin_of_forall_mem_toValuationSubring

open AlgebraicCurve Polynomial

set_option maxHeartbeats 800000
set_option synthInstance.maxHeartbeats 80000

namespace INTGlue

theorem isIntegral_of_mem_adjoin_inv {A F : Type*} [CommRing A] [Field F] [Algebra A F]
    {z : F} (hz0 : z ≠ 0) (hmem : z ∈ Algebra.adjoin A ({z⁻¹} : Set F)) : IsIntegral A z := by
  classical
  rw [Algebra.adjoin_singleton_eq_range_aeval] at hmem
  obtain ⟨p, hp⟩ := hmem
  have hp' : aeval z⁻¹ p = z := hp
  have hdeg : (∑ i ∈ Finset.range (p.natDegree + 1), C (p.coeff i) * X ^ (p.natDegree - i)).degree ≤
      (p.natDegree : WithBot ℕ) := by
    refine (Polynomial.degree_sum_le _ _).trans (Finset.sup_le fun i _ => ?_)
    exact (Polynomial.degree_C_mul_X_pow_le _ _).trans (by exact_mod_cast Nat.sub_le _ _)
  refine ⟨X ^ (p.natDegree + 1) - ∑ i ∈ Finset.range (p.natDegree + 1), C (p.coeff i) * X ^ (p.natDegree - i),
    Polynomial.monic_X_pow_sub (hdeg.trans_lt (by exact_mod_cast Nat.lt_succ_self _)), ?_⟩
  have hz : z = ∑ i ∈ Finset.range (p.natDegree + 1), algebraMap A F (p.coeff i) * z⁻¹ ^ i := by
    conv_lhs => rw [← hp']
    rw [Polynomial.aeval_eq_sum_range]
    simp only [Algebra.smul_def]
  have hzpow : ∀ i ∈ Finset.range (p.natDegree + 1), z ^ p.natDegree * z⁻¹ ^ i = z ^ (p.natDegree - i) := by
    intro i hi
    have hi' : i ≤ p.natDegree := Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)
    obtain ⟨k, hk⟩ := Nat.exists_eq_add_of_le hi'
    rw [hk, Nat.add_sub_cancel_left, pow_add, mul_comm (z ^ i) (z ^ k), mul_assoc, ← mul_pow,
      mul_inv_cancel₀ hz0, one_pow, mul_one]
  rw [eval₂_sub, sub_eq_zero, eval₂_pow, eval₂_X, eval₂_finsetSum]
  simp only [eval₂_mul, eval₂_C, eval₂_pow, eval₂_X]
  rw [pow_succ]
  conv_lhs => arg 2; rw [hz]
  rw [Finset.mul_sum]
  refine Finset.sum_congr rfl fun i hi => ?_
  rw [mul_left_comm, hzpow i hi]

theorem isIntegral_of_forall_valuationSubring {F : Type*} [Field F] (A : Subring F) (z : F)
    (h : ∀ V : ValuationSubring F, A ≤ V.toSubring → z ∈ V) : IsIntegral A z := by
  classical
  by_contra hnot
  have hz0 : z ≠ 0 := by rintro rfl; exact hnot isIntegral_zero
  set y : F := z⁻¹ with hy
  let B : Subalgebra A F := Algebra.adjoin A ({y} : Set F)
  have hyB : y ∈ B := Algebra.subset_adjoin (Set.mem_singleton y)
  have hzB : z ∉ B := fun hzB => hnot (isIntegral_of_mem_adjoin_inv hz0 hzB)
  have hyu : (⟨y, hyB⟩ : B) ∈ nonunits B := by
    intro hu
    obtain ⟨u, hu⟩ := hu
    have hinv : ((u⁻¹ : Bˣ) : B).1 = z := by
      have h1 : ((u : B) : F) * ((u⁻¹ : Bˣ) : B) = 1 := by
        rw [← Subalgebra.coe_mul, Units.mul_inv]; rfl
      rw [hu] at h1
      have : y⁻¹ = ((u⁻¹ : Bˣ) : B).1 := inv_eq_of_mul_eq_one_right h1
      rw [← this, hy, inv_inv]
    exact hzB (hinv ▸ ((u⁻¹ : Bˣ) : B).2)
  obtain ⟨m, hm, hym⟩ := exists_max_ideal_of_mem_nonunits hyu
  let Bs : Subring F := B.toSubring
  let m' : Ideal Bs := m
  have : m'.IsMaximal := hm
  let L : LocalSubring F := LocalSubring.ofPrime Bs m'
  obtain ⟨V, hV⟩ := L.exists_le_valuationSubring
  obtain ⟨hLV, hloc⟩ := LocalSubring.le_def.mp hV
  have hBL : Bs ≤ L.toSubring := LocalSubring.le_ofPrime Bs m'
  have hAV : A ≤ V.toSubring := by
    intro a ha
    have : (a : F) ∈ Bs := by
      show a ∈ B
      exact Subalgebra.algebraMap_mem B ⟨a, ha⟩
    exact hLV (hBL this)
  have hzV : z ∈ V := h V hAV
  have hyL : (algebraMap Bs L.toSubring ⟨y, hyB⟩) ∈ IsLocalRing.maximalIdeal L.toSubring :=
    (IsLocalization.AtPrime.to_map_mem_maximal_iff L.toSubring m' ⟨y, hyB⟩).mpr hym
  have hcoe : ((algebraMap Bs L.toSubring ⟨y, hyB⟩ : L.toSubring) : F) = y := by
    show algebraMap L.toSubring F (algebraMap Bs L.toSubring ⟨y, hyB⟩) = y
    rw [← IsScalarTower.algebraMap_apply Bs L.toSubring F]
    rfl
  have hyV' : ¬ IsUnit (Subring.inclusion hLV (algebraMap Bs L.toSubring ⟨y, hyB⟩)) := by
    intro hu
    have := (IsLocalRing.mem_maximalIdeal _).mp hyL
    exact this (hloc.map_nonunit _ hu)
  apply hyV'
  have hyVmem : y ∈ V := by
    have := (Subring.inclusion hLV (algebraMap Bs L.toSubring ⟨y, hyB⟩)).2
    rwa [Subring.coe_inclusion, hcoe] at this
  refine isUnit_iff_exists_inv.mpr ⟨⟨z, hzV⟩, ?_⟩
  ext
  simp only [Subring.coe_mul, Subring.coe_inclusion, hcoe, Subring.coe_one]
  rw [hy, inv_mul_cancel₀ hz0]

end INTGlue

theorem solution
    {K F : Type*} [Field K] [Field F] [Algebra K F] (x : F)
    [FiniteDimensional (IntermediateField.adjoin K ({x} : Set F)) F]
    [Algebra.IsSeparable (IntermediateField.adjoin K ({x} : Set F)) F]
    (t z : F)
    (h : ∀ v : AlgebraicCurve.Place K F, t ∈ v.toValuationSubring → z ∈ v.toValuationSubring) :
    IsIntegral (Algebra.adjoin K ({t} : Set F)) z := by
  classical
  have key : IsIntegral (Algebra.adjoin K ({t} : Set F)).toSubring z := by
    refine INTGlue.isIntegral_of_forall_valuationSubring _ z fun V hV => ?_
    by_cases htop : V = ⊤
    · rw [htop]; exact ValuationSubring.mem_top z
    have hK : ∀ a : K, algebraMap K F a ∈ V := fun a =>
      hV (Subalgebra.algebraMap_mem (Algebra.adjoin K ({t} : Set F)) a)
    obtain ⟨v, hv⟩ := AlgebraicCurve.Place.exists_of_valuationSubring_of_isSeparable x V hK htop
    have htV : t ∈ v.toValuationSubring := by
      rw [hv]; exact hV (Algebra.subset_adjoin (Set.mem_singleton t))
    have h2 := h v htV
    rwa [hv] at h2
  exact key

end S_AlgebraicCurve_isIntegral_adjoin_of_forall_mem_toValuationSubring
end P2MW
export P2MW.S_AlgebraicCurve_isIntegral_adjoin_of_forall_mem_toValuationSubring (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.isIntegral_adjoin_of_forall_mem_toValuationSubring
    {K F : Type*} [Field K] [Field F] [Algebra K F] (x : F)
    [FiniteDimensional (IntermediateField.adjoin K ({x} : Set F)) F]
    [Algebra.IsSeparable (IntermediateField.adjoin K ({x} : Set F)) F]
    (t z : F)
    (h : ∀ v : AlgebraicCurve.Place K F, t ∈ v.toValuationSubring → z ∈ v.toValuationSubring) :
    IsIntegral (Algebra.adjoin K ({t} : Set F)) z := _root_.P2MW.S_AlgebraicCurve_isIntegral_adjoin_of_forall_mem_toValuationSubring.solution x t z h

end publicSection
