/-
Based on Prove2Me node ModularCurve.ord_jLinePlace1728_jGen_sub
(072344ea-db1b-58f9-8f2e-461269728261) by Claude (2026-09-05).

Proof based on Prove2Me submission 63891d12-67e2-592c-b503-7d0520ead616
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JLinePlaces

import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceClassification
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_X_sub_C
import Definitions.FLT.Def_P2M_Util

/-!
# ord of j-1728 at the place j=1728 is 1

Theorem statement: `ModularCurve.ord_jLinePlace1728_jGen_sub`
(`072344ea-db1b-58f9-8f2e-461269728261`), by Claude, 2026-09-05.

Proof: submission `63891d12-67e2-592c-b503-7d0520ead616`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Work in the simple extension $\mathbb{Q}\langle j_q\rangle$ of $\mathbb{Q}$ generated by the
transcendental element [`ModularCurve.jq`](def/ModularCurve_X0.html#L157), a field which is
therefore a rational function field in one variable over $\mathbb{Q}$;
[`ModularCurve.jGen`](def/ModularCurve_X0.html#L268) denotes the generator $j_q$ regarded as an
element of this field. The place
[`ModularCurve.jLinePlace1728`](def/ModularCurve_JLinePlaces.html#L50) is the place of
$\mathbb{Q}\langle j_q\rangle$ over $\mathbb{Q}$ — that is, a valuation subring containing
$\mathbb{Q}$, distinct from the whole field and a principal ideal ring — obtained by transporting,
along the ring isomorphism [`ModularCurve.jLineRingEquiv : RatFunc ℚ ≃+*
ℚ⟮jq⟯`](def/ModularCurve_JLinePlaces.html#L36) which carries the variable to $j_q$ and fixes
$\mathbb{Q}$, the finite place of $\mathbb{Q}(T)$ attached to the irreducible polynomial $T - 1728$.
For a place $v$ and an element $f$, $v.\mathrm{ord}(f)$ is minus the logarithm of the value of $f$
under the adic valuation of the height-one prime of the valuation subring of $v$. The assertion is
that the order of $j_q - 1728$ at this place equals $1$: the function $j - 1728$ has a simple zero
at the point $j = 1728$ of the $j$-line.

This records one of the standard local normalisations on the $j$-line: $j-1728$ is a uniformiser at
the point $j=1728$, the point below which the covering $X_0(N)\to X(1)$ has its ramification of
order dividing $2$. It is used in
[`ModularCurve.ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728`](thm.html#ModularCurve.ramificationIndex_eq_ord_sub_of_restrict_eq_jLinePlace1728),
where ramification indices above $j=1728$ are computed as orders of $j-1728$ at places of the larger
function field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_ord_jLinePlace1728_jGen_sub.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_ord_jLinePlace1728_jGen_sub
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X"
p2m_attr_erase "simp" "ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

open IntermediateField AlgebraicCurve AlgebraicCurve.RationalFunctionField

attribute [local instance 2000] RatFunc.instAlgebraOfPolynomial
attribute [local instance] ModularCurve.instDecidableEqRatFuncRat

namespace ModularCurve
p2m_export "ModularCurve" "jLineRingEquiv jLineRingEquiv_X instDecidableEqRatFuncRat jLinePlace1728 jq jGen"
namespace JLineOrdAux
p2m_open "ModularCurve"

theorem equiv_X_sub_C (b : ℚ) :
    ModularCurve.jLineRingEquiv (algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.X - Polynomial.C b))
      = ModularCurve.jGen - algebraMap ℚ ↥ℚ⟮ModularCurve.jq⟯ b := by
  rw [map_sub, RatFunc.algebraMap_X, map_sub, ModularCurve.jLineRingEquiv_X, RatFunc.algebraMap_C]
  congr 1
  exact RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom b

theorem exists_eq_congr (v : Place ℚ ↥ℚ⟮ModularCurve.jq⟯) :
    ∃ v' : Place ℚ (RatFunc ℚ), v = Place.congrRingEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) v' :=
  ⟨(Place.congrEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom)).symm v,
    ((Place.congrEquiv _ _).apply_symm_apply v).symm⟩

theorem ord_congr_jGen_sub (b : ℚ) (v' : Place ℚ (RatFunc ℚ)) :
    (Place.congrRingEquiv ModularCurve.jLineRingEquiv
        (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) v').ord
      (ModularCurve.jGen - algebraMap ℚ ↥ℚ⟮ModularCurve.jq⟯ b)
    = (Finsupp.single (placeOfPoint ℚ b) (1 : ℤ) + Finsupp.single (placeInfty ℚ) (-1 : ℤ)) v' := by
  rw [← equiv_X_sub_C, Place.ord_congrRingEquiv]
  exact ord_X_sub_C ℚ b v'

theorem injective_congr : Function.Injective (Place.congrRingEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) : Place ℚ (RatFunc ℚ) → _) :=
  (Place.congrEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom)).injective

end ModularCurve.JLineOrdAux

open ModularCurve.JLineOrdAux

theorem solution : ModularCurve.jLinePlace1728.ord (ModularCurve.jGen - 1728) = 1 := by
  have h := ord_congr_jGen_sub 1728 (placeOfPoint ℚ 1728)
  rw [show algebraMap ℚ ↥ℚ⟮ModularCurve.jq⟯ 1728 = 1728 from map_ofNat _ 1728] at h
  have h01 := placeOfPoint_ne_placeInfty ℚ 1728
  unfold ModularCurve.jLinePlace1728
  rw [h]
  simp [h01]

end S_ModularCurve_ord_jLinePlace1728_jGen_sub
end P2MW
export P2MW.S_ModularCurve_ord_jLinePlace1728_jGen_sub (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open IntermediateField AlgebraicCurve
theorem ModularCurve.ord_jLinePlace1728_jGen_sub : ModularCurve.jLinePlace1728.ord (ModularCurve.jGen - 1728) = 1 := _root_.P2MW.S_ModularCurve_ord_jLinePlace1728_jGen_sub.solution

end publicSection
