/-
Based on Prove2Me node ModularCurve.samePlace_iff_exists_monodromy
(e7630490-b841-57a1-ad5b-d275ba655cec) by Claude (2026-09-05).

Proof based on Prove2Me submission 17b854de-b789-501e-85f0-1cb724820173
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_EMD
public import Definitions.FLT.Def_HahnSeries_Monodromy

import Theorems.FLT.Thm_ModularCurve_samePlace_iff_exists_hahnTwist
import Definitions.FLT.Def_P2M_Util

/-!
# Places of normalised Hahn-series embeddings differ by monodromy

Theorem statement: `ModularCurve.samePlace_iff_exists_monodromy`
(`e7630490-b841-57a1-ad5b-d275ba655cec`), by Claude, 2026-09-05.

Proof: submission `17b854de-b789-501e-85f0-1cb724820173`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number with $N \neq 0$, let $j_0 \in \overline{\mathbb{Q}}$, and let $\psi,
\psi'$ be elements of `Emb N j₀`, that is, $\overline{\mathbb{Q}}$-algebra homomorphisms from the
field `modularFunctionFieldBar N` (the base change to $\overline{\mathbb{Q}}$ of the full level-$N$
modular function field, an intermediate field of the Laurent series over $\overline{\mathbb{Q}}$)
into the Hahn series $\mathrm{HahnSeries}\,\mathbb{Q}\,\overline{\mathbb{Q}}$ with rational
exponents, each sending the distinguished element `jBar N` to $j_0 + t$, where $t$ is the monomial
`single 1 1` of exponent $1$ and coefficient $1$. The theorem asserts the equivalence of two
conditions. First, `SamePlace ψ.1 ψ'.1`: there is a place $w$ of `modularFunctionFieldBar N` over
$\overline{\mathbb{Q}}$ (a proper valuation subring containing the image of $\overline{\mathbb{Q}}$
and a principal ideal ring) which both $\psi$ and $\psi'$ induce, where $\psi$ induces $w$ when
there is a rational $g > 0$ with $(\mathrm{ord}_w x)\,g = \mathrm{order}(\psi\,x)$ for every $x$
(the scaling factor $g$ may differ for $\psi$ and $\psi'$). Second: there is an element $m$ of the
subgroup `monodromy` of $\overline{\mathbb{Q}}$-algebra automorphisms of
$\mathrm{HahnSeries}\,\mathbb{Q}\,\overline{\mathbb{Q}}$, namely the image under `hahnTwistHom` of
the group `MonoChar` of monoid homomorphisms $\chi : \mathbb{Q} \to \overline{\mathbb{Q}}^{\times}$
(written multiplicatively) with $\chi(1) = 1$, each such $\chi$ acting by scaling the coefficient of
exponent $a$ by $\chi(a)$, such that $\psi$ followed by $m$ equals $\psi'$ as algebra homomorphisms.

This identifies the fibres of the map from normalised Hahn-series expansions at $j_0$ to places of
the level-$N$ modular function field: two normalised embeddings induce the same place exactly when
they differ by a coefficientwise twist fixing the exponent-$1$ coefficient. It is used in the
construction of elliptic points and cyclic-subgroup orbit maps on the modular curve, through
[`ModularCurve.exists_elliptic_cycSub_orbitMap_of_props`](thm.html#ModularCurve.exists_elliptic_cycSub_orbitMap_of_props)
and
[`ModularCurve.exists_elliptic_cycSub_orbitMap_prime_of_ne_two`](thm.html#ModularCurve.exists_elliptic_cycSub_orbitMap_prime_of_ne_two).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_samePlace_iff_exists_monodromy.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_samePlace_iff_exists_monodromy
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation ModularCurve.PhiGen.instNeZeroPhiGenCosetA AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "ModularCurve.cuspCount_one HahnSeries.ramScale_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe"
p2m_attr_erase "simp" "ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ"

open HahnSeries ModularCurve AlgebraicCurve

theorem solution (N : ℕ) [NeZero N] (j₀ : AlgebraicClosure ℚ)
    (ψ ψ' : Emb N j₀) :
    SamePlace ψ.1 ψ'.1 ↔
      ∃ m ∈ monodromy (AlgebraicClosure ℚ),
        (↑m : HahnSeries ℚ (AlgebraicClosure ℚ) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ)).comp ψ.1 = ψ'.1 := by
  rw [ModularCurve.samePlace_iff_exists_hahnTwist]
  constructor
  · rintro ⟨χ, hχ, h⟩
    refine ⟨hahnTwistHom χ, Subgroup.mem_map_of_mem _ hχ, AlgHom.ext fun x => ?_⟩
    simpa only [AlgHom.comp_apply, hahnTwistHom_apply, AlgEquiv.toAlgHom_apply] using
      (h x).symm
  · rintro ⟨m, hm, h⟩
    obtain ⟨χ, hχ, rfl⟩ := Subgroup.mem_map.mp hm
    refine ⟨χ, hχ, fun x => ?_⟩
    simpa only [AlgHom.comp_apply, hahnTwistHom_apply, AlgEquiv.toAlgHom_apply] using
      (AlgHom.congr_fun h x).symm

end S_ModularCurve_samePlace_iff_exists_monodromy
end P2MW
export P2MW.S_ModularCurve_samePlace_iff_exists_monodromy (solution)

end privateSection

public section publicSection


open HahnSeries ModularCurve AlgebraicCurve
theorem ModularCurve.samePlace_iff_exists_monodromy (N : ℕ) [NeZero N] (j₀ : AlgebraicClosure ℚ)
    (ψ ψ' : Emb N j₀) :
    SamePlace ψ.1 ψ'.1 ↔
      ∃ m ∈ monodromy (AlgebraicClosure ℚ),
        (↑m : HahnSeries ℚ (AlgebraicClosure ℚ) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ)).comp ψ.1 = ψ'.1 := _root_.P2MW.S_ModularCurve_samePlace_iff_exists_monodromy.solution N j₀ ψ ψ'

end publicSection
