/-
Based on Prove2Me node ModularCurve.modularUnitSeries_mem_modularFunctionFieldFull
(55ba7334-be8a-5179-a36e-7862c943490d) by Claude (2026-09-05).

Proof based on Prove2Me submission bbb00a88-70a0-5648-8976-119669fb911b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ModularUnit

import Theorems.FLT.Thm_ModularCurve_modularUnitSeries_mem_modularFunctionField
import Definitions.FLT.Def_P2M_Util

/-!
# Ogg's modular unit lies in the full level-N function field

Theorem statement: `ModularCurve.modularUnitSeries_mem_modularFunctionFieldFull`
(`55ba7334-be8a-5179-a36e-7862c943490d`), by Claude, 2026-09-05.

Proof: submission `bbb00a88-70a0-5648-8976-119669fb911b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a nonzero natural number. Write $\Delta =$
[`ModularCurve.deltaSeries`](def/ModularCurve_ModularUnit.html#L107) for the Laurent series over
$\mathbb{Q}$ given by $q$ (the Hahn series $q^{1}$ with coefficient $1$) times the power series
`dedekindEtaUnitQ`, and for $d \ge 1$ let `qExpand ℚ d` denote the substitution $q \mapsto q^{d}$ on
`LaurentSeries ℚ`. The theorem asserts that the element
[`ModularCurve.modularUnitSeries N`](def/ModularCurve_ModularUnit.html#L127) $= \Delta(q)\cdot
\Delta(q^{N})^{-1}$, the product of $\Delta$ with the inverse of its $N$-th $q$-expansion
`deltaSeriesN N`, belongs to [`ModularCurve.modularFunctionFieldFull
N`](def/ModularCurve_X0.html#L305), namely the intermediate field of `LaurentSeries ℚ` over
$\mathbb{Q}$ generated by the set of all series $\mathrm{qExpand}_{\mathbb{Q},d}(\mathtt{jq})$ for
nonzero divisors $d$ of $N$, i.e. by the $q$-expansions $j(q^{d})$, $d \mid N$. No primality or
other hypothesis on $N$ is imposed: the assertion is unconditional in the level.

This is the statement that Ogg's modular unit $\Delta(q)/\Delta(q^{N})$ is a rational function of
the expansions $j(q^{d})$, $d \mid N$, at arbitrary, not merely prime, level; in the formalisation
it supplies the unit used to produce functions with prescribed divisors on the modular curve of
level $N$. It is cited throughout the construction of Deligne–Rapoport-style models and charts at
general level.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_modularUnitSeries_mem_modularFunctionFieldFull.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_modularUnitSeries_mem_modularFunctionFieldFull
p2m_attr_erase "instance" "ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularCurve.coeffEmb_coeff ModularCurve.coeffMap_coeff ModularCurve.coeffMap_id ModularCurve.coeffMap_single"

theorem solution (N : ℕ) [NeZero N] : ModularCurve.modularUnitSeries N ∈ ModularCurve.modularFunctionFieldFull N := by
  suffices H : ∀ n : ℕ, ∀ _ : NeZero n,
      ModularCurve.modularUnitSeries n ∈ ModularCurve.modularFunctionFieldFull n from
    H N ‹NeZero N›
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro hNZ
    have := hNZ
    have hn : n ≠ 0 := NeZero.ne n
    rcases eq_or_ne n 1 with rfl | hn1
    · rw [ModularCurve.modularUnitSeries_one]
      exact one_mem _
    · obtain ⟨p, hp, hdvd⟩ := Nat.exists_prime_and_dvd hn1
      obtain ⟨M, rfl⟩ := hdvd
      have hM : M ≠ 0 := by rintro rfl; exact hn (mul_zero p)
      have hp0 : p ≠ 0 := hp.ne_zero
      have : NeZero p := ⟨hp0⟩
      have : NeZero M := ⟨hM⟩
      have : NeZero (p * M) := ⟨mul_ne_zero hp0 hM⟩
      have : Fact p.Prime := ⟨hp⟩
      rw [ModularCurve.modularUnitSeries_mul p M]
      refine mul_mem ?_ ?_
      · exact ModularCurve.full_degeneracy_le (dvd_mul_right p M)
          (ModularCurve.modularFunctionField_le_full p
            (ModularCurve.modularUnitSeries_mem_modularFunctionField p))
      · have hMlt : M < p * M :=
          (lt_mul_iff_one_lt_left (Nat.pos_of_ne_zero hM)).mpr hp.one_lt
        have hmem := ih M hMlt ⟨hM⟩
        have h2 : ModularCurve.qExpandₐ p (ModularCurve.modularUnitSeries M)
            ∈ (ModularCurve.modularFunctionFieldFull M).map (ModularCurve.qExpandₐ p) :=
          ⟨_, hmem, rfl⟩
        have h3 := ModularCurve.full_degeneracy_map_le M p h2
        rw [ModularCurve.qExpandₐ_apply] at h3
        exact ModularCurve.full_degeneracy_le (dvd_of_eq (mul_comm M p)) h3

end S_ModularCurve_modularUnitSeries_mem_modularFunctionFieldFull
end P2MW
export P2MW.S_ModularCurve_modularUnitSeries_mem_modularFunctionFieldFull (solution)

end privateSection

public section publicSection

theorem ModularCurve.modularUnitSeries_mem_modularFunctionFieldFull (N : ℕ) [NeZero N] : ModularCurve.modularUnitSeries N ∈ ModularCurve.modularFunctionFieldFull N := _root_.P2MW.S_ModularCurve_modularUnitSeries_mem_modularFunctionFieldFull.solution N

end publicSection
