/-
Based on Prove2Me node AlgebraicCurve.Place.evalAt_algebraMap
(530bce27-196e-589d-a3d0-19d0844fb39d) by Claude (2026-09-05).

Proof based on Prove2Me submission 65a760dc-d291-5a56-972f-85ebaf7b8b07
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_PlaceEvaluation

import Definitions.FLT.Def_P2M_Util

/-!
# Evaluation of a constant at a place returns the constant

Theorem statement: `AlgebraicCurve.Place.evalAt_algebraMap`
(`530bce27-196e-589d-a3d0-19d0844fb39d`), by Claude, 2026-09-05.

Proof: submission `65a760dc-d291-5a56-972f-85ebaf7b8b07`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of this development: a valuation subring $v.\mathrm{toValuationSubring}$ of $F$ which contains
$\mathrm{algebraMap}_{K,F}(a)$ for every $a \in K$, is not all of $F$, and is a principal ideal
ring. For $f \in F$ the evaluation $v.\mathrm{evalAt}(f) \in K$ is defined to be $0$ when $f$ does
not lie in $v.\mathrm{toValuationSubring}$, and otherwise the image of the residue class of $f$ in
the residue field of the local ring $v.\mathrm{toValuationSubring}$ under `residueInv`, the chosen
inverse function (`Function.invFun`) of the structure map $K \to v.\mathrm{ResidueField}$. The
assertion is that for every $a \in K$ one has $v.\mathrm{evalAt}(\mathrm{algebraMap}_{K,F}(a)) = a$;
that is, the evaluation of the constant $a$, viewed as an element of $F$, recovers $a$ itself. No
hypothesis beyond the place structure is required, in particular no assumption that the residue
field equals $K$.

This is the statement that constants are evaluated to themselves at any place of $F/K$, the base
case of the evaluation-of-functions layer used in the treatment of divisors, Weil reciprocity and
the Weil pairing; it is invoked throughout that layer, for instance in the computations on annuli
and component charts.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_evalAt_algebraMap.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_evalAt_algebraMap

open IsLocalRing AlgebraicCurve

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) (a : K) : v.evalAt (algebraMap K F a) = a := by
  rw [v.evalAt_of_mem (v.algebraMap_mem' a)]
  have ha : (⟨algebraMap K F a, v.algebraMap_mem' a⟩ : v.toValuationSubring)
      = algebraMap K v.toValuationSubring a := Subtype.ext (v.coe_algebraMap a).symm
  rw [ha, ← ResidueField.algebraMap_eq,
    ← IsScalarTower.algebraMap_apply K v.toValuationSubring v.ResidueField,
    v.residueInv_algebraMap]

end S_AlgebraicCurve_Place_evalAt_algebraMap
end P2MW
export P2MW.S_AlgebraicCurve_Place_evalAt_algebraMap (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.Place.evalAt_algebraMap {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) (a : K) : v.evalAt (algebraMap K F a) = a := _root_.P2MW.S_AlgebraicCurve_Place_evalAt_algebraMap.solution v a

end publicSection
