/-
Based on Prove2Me node KaehlerDifferential.D_ne_zero_of_transcendental
(0df85775-aaa5-5911-8954-96e03b12839a) by Claude (2026-09-05).

Proof based on Prove2Me submission 95ed7aea-228a-552c-bed7-c51720bd6f7e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.RingTheory.Kaehler.Basic
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.FieldTheory.Separable
public import Mathlib.RingTheory.Algebraic.Defs

import Mathlib.RingTheory.Etale.Kaehler
import Mathlib.RingTheory.Etale.Field
import Mathlib.RingTheory.Kaehler.Polynomial
import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Mathlib.LinearAlgebra.TensorProduct.Basis
import Definitions.FLT.Def_P2M_Util

/-!
# Nonvanishing of dx for a separating transcendental element

Theorem statement: `KaehlerDifferential.D_ne_zero_of_transcendental`
(`0df85775-aaa5-5911-8954-96e03b12839a`), by Claude, 2026-09-05.

Proof: submission `95ed7aea-228a-552c-bed7-c51720bd6f7e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, $F$ a field, and let $F$ be a $K$-algebra. Let $x \in F$ be transcendental over
$K$, i.e. `Transcendental K x`: $x$ is not a root of any nonzero polynomial over $K$. Assume further
that $F$ is a separable algebra over the intermediate field $K(x) =$ `IntermediateField.adjoin K
{x}` generated by $x$, that is, every element of $F$ is algebraic with separable minimal polynomial
over $K(x)$. The conclusion is that the universal derivation applied to $x$, namely
`KaehlerDifferential.D K F x` $= dx$, is nonzero in the module of Kähler differentials
$\Omega_{F/K}$ of $F$ over $K$. This is the nonvanishing half only: the statement asserts $dx \neq
0$, not that $dx$ is an $F$-basis of $\Omega_{F/K}$, although the proof establishes the stronger
fact along the way.

This is the classical nonvanishing of the differential of a separating element of a function field,
underlying the fact that $\Omega_{F/K}$ is one-dimensional over $F$ with basis $dx$. It is used
throughout the treatment of differentials on curves, for instance in defining and computing the
order of a differential at a place and in the study of torsion in the degree-zero part of the Picard
group.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_KaehlerDifferential_D_ne_zero_of_transcendental.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_KaehlerDifferential_D_ne_zero_of_transcendental

noncomputable section
p2m_open "Polynomial KaehlerDifferential P2MW.S_KaehlerDifferential_D_ne_zero_of_transcendental.KaehlerDifferential"

namespace KaehlerDifferential
p2m_export "KaehlerDifferential" "tensorKaehlerEquivOfFormallyEtale polynomialEquiv tensorKaehlerEquivOfFormallyEtale_apply mapBaseChange_tmul D map_D map"
namespace FF2
p2m_open "KaehlerDifferential"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] {x : F} (hx : Transcendental K x)
  [Algebra.IsSeparable (IntermediateField.adjoin K ({x} : Set F)) F]

include hx in

private theorem exists_basis : ∃ b : Module.Basis Unit F Ω[F⁄K], b () = D K F x := by
  let e : RatFunc K ≃ₐ[K] IntermediateField.adjoin K ({x} : Set F) := RatFunc.algEquivOfTranscendental x hx
  let algKx : Algebra K[X] (IntermediateField.adjoin K ({x} : Set F)) := (e.toAlgHom.toRingHom.comp (algebraMap K[X] (RatFunc K))).toAlgebra
  let algF : Algebra K[X] F := ((algebraMap (IntermediateField.adjoin K ({x} : Set F)) F).comp (algebraMap K[X] (IntermediateField.adjoin K ({x} : Set F)))).toAlgebra
  have : IsScalarTower K[X] (IntermediateField.adjoin K ({x} : Set F)) F := IsScalarTower.of_algebraMap_eq (fun _ => rfl)
  have : IsScalarTower K K[X] (IntermediateField.adjoin K ({x} : Set F)) := IsScalarTower.of_algebraMap_eq (fun c => by
    change _ = (e.toAlgHom.toRingHom.comp (algebraMap K[X] (RatFunc K))) (C c)
    simp only [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, RingHom.coe_coe, AlgEquiv.coe_toAlgHom]
    rw [← Polynomial.algebraMap_eq, ← IsScalarTower.algebraMap_apply K K[X] (RatFunc K), AlgEquiv.commutes])
  have : IsScalarTower K K[X] F := IsScalarTower.of_algebraMap_eq (fun c => by
    rw [IsScalarTower.algebraMap_apply K (IntermediateField.adjoin K ({x} : Set F)) F, IsScalarTower.algebraMap_apply K[X] (IntermediateField.adjoin K ({x} : Set F)) F,
      ← IsScalarTower.algebraMap_apply K K[X] (IntermediateField.adjoin K ({x} : Set F))])
  have : Algebra.FormallyEtale K[X] (RatFunc K) :=
    Algebra.FormallyEtale.of_isLocalization (nonZeroDivisors K[X])
  have : Algebra.FormallyEtale K[X] (IntermediateField.adjoin K ({x} : Set F)) :=
    Algebra.FormallyEtale.of_equiv (R := K[X]) (A := RatFunc K) { e with commutes' := fun _ => rfl }
  have : Algebra.FormallyEtale (IntermediateField.adjoin K ({x} : Set F)) F := Algebra.FormallyEtale.of_isSeparable (IntermediateField.adjoin K ({x} : Set F)) F
  have : Algebra.FormallyEtale K[X] F := Algebra.FormallyEtale.comp K[X] (IntermediateField.adjoin K ({x} : Set F)) F
  let b₀ : Module.Basis Unit K[X] Ω[K[X]⁄K] :=
    (Module.Basis.singleton Unit K[X]).map (polynomialEquiv K).symm
  have hb₀ : b₀ () = D K K[X] X := by simp [b₀]
  let ψ := tensorKaehlerEquivOfFormallyEtale K K[X] F
  refine ⟨(b₀.baseChange F).map ψ, ?_⟩
  have hX : algebraMap K[X] F X = x := by
    change algebraMap (IntermediateField.adjoin K ({x} : Set F)) F (e (algebraMap K[X] (RatFunc K) X)) = x
    rw [RatFunc.algebraMap_X]
    exact RatFunc.algEquivOfTranscendental_X x hx
  simp only [Module.Basis.map_apply, Module.Basis.baseChange_apply, hb₀, ψ,
    tensorKaehlerEquivOfFormallyEtale_apply, mapBaseChange_tmul, one_smul, map_D, hX]

end KaehlerDifferential.FF2

theorem solution (K : Type*) [Field K] {F : Type*} [Field F] [Algebra K F] (x : F) (hx : Transcendental K x)
    [Algebra.IsSeparable (IntermediateField.adjoin K ({x} : Set F)) F] :
    KaehlerDifferential.D K F x ≠ 0 := by
  obtain ⟨b, hb⟩ := KaehlerDifferential.FF2.exists_basis hx
  simpa [hb] using b.ne_zero ()

end

end S_KaehlerDifferential_D_ne_zero_of_transcendental
end P2MW
export P2MW.S_KaehlerDifferential_D_ne_zero_of_transcendental (solution)

end privateSection

public section publicSection

theorem KaehlerDifferential.D_ne_zero_of_transcendental (K : Type*) [Field K] {F : Type*} [Field F] [Algebra K F] (x : F) (hx : Transcendental K x)
    [Algebra.IsSeparable (IntermediateField.adjoin K ({x} : Set F)) F] :
    KaehlerDifferential.D K F x ≠ 0 := _root_.P2MW.S_KaehlerDifferential_D_ne_zero_of_transcendental.solution K x hx

end publicSection
