/-
Based on Prove2Me node P2M.Dup.AlgebraicCurve.Place.isEquiv_adicValuation_of_valuationSubring_eq
(10c978df-0cda-523d-ad8c-b753a669abe3) by Claude (2026-09-05).

Proof based on Prove2Me submission bbf8958b-b703-5410-8970-74399f7ccbdd
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup
public import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaces

import Definitions.FLT.Def_P2M_Util

/-!
# Equivalence with v's adic valuation from equal valuation rings

Theorem statement: `P2M.Dup.AlgebraicCurve.Place.isEquiv_adicValuation_of_valuationSubring_eq`
(`10c978df-0cda-523d-ad8c-b753a669abe3`), by Claude, 2026-09-05.

Proof: submission `bbf8958b-b703-5410-8970-74399f7ccbdd`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of the project's structure `Place K F`: a valuation subring $\mathcal{O}_v \subseteq F$
(recorded as `v.toValuationSubring`) which contains the image of $K$ under the structure map, is not
all of $F$, and is a principal ideal ring. Attached to $v$ is the height-one prime of
$\mathcal{O}_v$ given by its maximal ideal, and `v.adicValuation` is the associated
$\mathbb{Z}^{m0}$-valued valuation on $F$, i.e. the valuation of $F$ determined by that height-one
prime, with values in $\mathbb{Z}^{m0} = \mathbb{Z}^{\mathrm{multiplicative}}$ adjoined zero. The
theorem asserts: for any linearly ordered commutative group with zero $\Gamma$ and any valuation $w
: F \to \Gamma$ whose valuation subring $\{x \in F : w(x) \le 1\}$ coincides with $\mathcal{O}_v$,
the valuation $w$ is equivalent to `v.adicValuation` in Mathlib's sense (`Valuation.IsEquiv`), that
is, the two induce the same order relation on $F$, hence differ only by a rescaling of value groups.

This is the standard fact that a valuation on a field is determined up to equivalence by its
valuation ring, specialised to the normalised (discrete, $\mathbb{Z}$-valued) valuation attached to
a place of $F/K$. It is used to identify arbitrary valuations with the normalised one, feeding into
the computation of the order function of a place and into the degree-one criterion for places of a
rational function field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_isEquiv_adicValuation_of_valuationSubring_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_isEquiv_adicValuation_of_valuationSubring_eq

open IsDedekindDomain WithZero IsLocalRing

noncomputable section

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ext heightOneSpectrum adicValuation toValuationSubring"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

p2m_export "AlgebraicCurve.Place" "adicValuation_valuationSubring"
private theorem rowMain {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] {w : Valuation F Γ}
    (h : w.valuationSubring = v.toValuationSubring) : w.IsEquiv v.adicValuation :=
  (Valuation.isEquiv_iff_valuationSubring _ _).mpr
    (h.trans v.adicValuation_valuationSubring.symm)

end Place

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_Place_isEquiv_adicValuation_of_valuationSubring_eq.AlgebraicCurve in
theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] {w : Valuation F Γ}
    (h : w.valuationSubring = v.toValuationSubring) :
    w.IsEquiv v.adicValuation :=
  AlgebraicCurve.Place.rowMain v h

end S_AlgebraicCurve_Place_isEquiv_adicValuation_of_valuationSubring_eq
end P2MW
export P2MW.S_AlgebraicCurve_Place_isEquiv_adicValuation_of_valuationSubring_eq (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem P2M.Dup.AlgebraicCurve.Place.isEquiv_adicValuation_of_valuationSubring_eq {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {Γ : Type*}
    [LinearOrderedCommGroupWithZero Γ] {w : Valuation F Γ}
    (h : w.valuationSubring = v.toValuationSubring) :
    w.IsEquiv v.adicValuation := _root_.P2MW.S_AlgebraicCurve_Place_isEquiv_adicValuation_of_valuationSubring_eq.solution v h

end publicSection
