/-
Based on Prove2Me node P2M.Dup.AlgebraicCurve.Place.mem_of_ord_nonneg
(ca37e605-477f-5084-ad18-3b7e34e8f02e) by Claude (2026-09-05).

Proof based on Prove2Me submission 0bf989c1-a311-581e-9cc2-ca7143ec471a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup
public import Definitions.FLT.Def_ModularCurve_CharLFrobeniusGeomLevel

import Definitions.FLT.Def_P2M_Util

/-!
# Nonnegative order implies membership in the valuation ring

Theorem statement: `P2M.Dup.AlgebraicCurve.Place.mem_of_ord_nonneg`
(`ca37e605-477f-5084-ad18-3b7e34e8f02e`), by Claude, 2026-09-05.

Proof: submission `0bf989c1-a311-581e-9cc2-ca7143ec471a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of the project's structure `Place K F`: a valuation subring $v.\mathrm{toValuationSubring}$ of
$F$ which contains the image of $K$ under the structure map, which is not the whole of $F$, and
whose underlying ring is a principal ideal ring. Let $f \in F$ be nonzero and suppose that the
integer $v.\mathrm{ord}\,f$ is nonnegative, where $v.\mathrm{ord}$ is defined as minus the logarithm
(in the sense of `WithZero.log`, with values in $\mathbb{Z}$) of the value
$v.\mathrm{adicValuation}\,f \in \mathbb{Z}^{m0}$, and $v.\mathrm{adicValuation}$ is the adic
valuation on $F$ attached to the height-one prime `v.heightOneSpectrum` associated with the place.
The conclusion is that $f$ belongs to the valuation subring $v.\mathrm{toValuationSubring}$.

This is the elementary compatibility between the integer-valued order function attached to a place
and membership in its valuation ring: an element with no pole at $v$ is regular at $v$. It serves as
a basic tool throughout the divisor-theoretic part of the development, being invoked in the
treatment of annuli, residues and divisors on curves.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_mem_of_ord_nonneg.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_mem_of_ord_nonneg

open IsDedekindDomain WithZero IsLocalRing

noncomputable section

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ord exists_unit_mul_zpow toValuationSubring"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

private theorem rowMain {f : F} (hf : f ≠ 0) (h : 0 ≤ v.ord f) :
    f ∈ v.toValuationSubring := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  obtain ⟨u, hu⟩ := v.exists_unit_mul_zpow hf hπ
  rw [hu, show v.ord f = (((v.ord f).toNat : ℕ) : ℤ) from (Int.toNat_of_nonneg h).symm,
    zpow_natCast]
  exact mul_mem (u : v.toValuationSubring).2 (pow_mem (π : v.toValuationSubring).2 _)

end Place

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_Place_mem_of_ord_nonneg.AlgebraicCurve in
theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {f : F} (hf : f ≠ 0) (h : 0 ≤ v.ord f) :
    f ∈ v.toValuationSubring :=
  AlgebraicCurve.Place.rowMain v hf h

end S_AlgebraicCurve_Place_mem_of_ord_nonneg
end P2MW
export P2MW.S_AlgebraicCurve_Place_mem_of_ord_nonneg (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem P2M.Dup.AlgebraicCurve.Place.mem_of_ord_nonneg {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {f : F} (hf : f ≠ 0) (h : 0 ≤ v.ord f) :
    f ∈ v.toValuationSubring := _root_.P2MW.S_AlgebraicCurve_Place_mem_of_ord_nonneg.solution v hf h

end publicSection
