/-
Based on Prove2Me node WeierstrassCurve.sum_eq_zero_of_forall_mem_iff_smul_eq_zero
(c1433814-ee33-55c0-8518-c7e80d81fa07) by Claude (2026-09-05).

Proof based on Prove2Me submission d98f4e3a-933d-5d16-ad74-2cdd66956caf
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.FieldTheory.IsAlgClosed.Basic

import Theorems.FLT.Thm_WeierstrassCurve_card_torsion_of_isAlgClosed
import Definitions.FLT.Def_P2M_Util

/-!
# The n-torsion points of an elliptic curve sum to O

Theorem statement: `WeierstrassCurve.sum_eq_zero_of_forall_mem_iff_smul_eq_zero`
(`c1433814-ee33-55c0-8518-c7e80d81fa07`), by Claude, 2026-09-05.

Proof: submission `d98f4e3a-933d-5d16-ad74-2cdd66956caf`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra and $K$ algebraically closed, and let $W$ be a
Weierstrass curve over $F$ which is elliptic (invertible discriminant). Let $n$ be a natural number
whose image in $K$ is nonzero, and let $s$ be a finite set of points of the affine elliptic curve
obtained from $W$ by base change to $K$, i.e. of the group $(W_{/K})(K)$ in Mathlib's `Point`
presentation (the nonsingular affine points together with the point at infinity, with the
chord–tangent group law). Assume that $s$ consists exactly of the $n$-torsion: for every point $P$,
one has $P \in s$ if and only if $n \cdot P = 0$. Then the sum of all elements of $s$, taken in the
group $(W_{/K})(K)$, is the identity $0$. Since $n$ is nonzero in $K$, the hypothesis in particular
forces $n \geq 1$, so $s$ is the full group $(W_{/K})(K)[n]$ of $n$-division points.

This is the classical assertion that the sum of all $n$-division points of an elliptic curve over an
algebraically closed field of residue characteristic not dividing $n$ is the origin; it underlies
the verification that the divisor $\sum_{R \in E[n]} (T'+R) - \sum_{R \in E[n]} (R)$ is principal in
Silverman's construction of the Weil pairing. Within the present development it is used in the
computation of the valuation of the Weil numerator,
[`WeierstrassCurve.Affine.valuation_weilNum`](thm.html#WeierstrassCurve.Affine.valuation_weilNum).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_sum_eq_zero_of_forall_mem_iff_smul_eq_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_sum_eq_zero_of_forall_mem_iff_smul_eq_zero
p2m_attr_erase "instance" "WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly"
p2m_attr_erase "simp" "compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two"

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point

theorem sum_eq_zero_of_two_torsion_card_four {M : Type*} [AddCommGroup M] [DecidableEq M]
    (T : Finset M) (hT : ∀ P, P ∈ T ↔ 2 • P = 0) (hcard : T.card = 4) : ∑ P ∈ T, P = 0 := by
  obtain ⟨A, hA, hA0⟩ : ∃ A ∈ T, A ≠ 0 := by
    by_contra! hall
    have hsub : T ⊆ {0} := fun P hP => Finset.mem_singleton.mpr (hall P hP)
    have := Finset.card_le_card hsub
    rw [Finset.card_singleton] at this
    omega
  obtain ⟨B, hB, hB0, hBA⟩ : ∃ B ∈ T, B ≠ 0 ∧ B ≠ A := by
    by_contra! hall
    have hsub : T ⊆ {0, A} := fun P hP => by
      rw [Finset.mem_insert, Finset.mem_singleton]
      by_cases hP0 : P = 0
      · exact Or.inl hP0
      · exact Or.inr (hall P hP hP0)
    have := (Finset.card_le_card hsub).trans Finset.card_le_two
    omega
  have h2A : 2 • A = 0 := (hT A).mp hA
  have h2B : 2 • B = 0 := (hT B).mp hB
  have hAB : A + B ∈ T := (hT _).mpr (by rw [smul_add, h2A, h2B, add_zero])
  have hAB0 : A + B ≠ 0 := fun h => hBA <| by
    rw [two_nsmul] at h2A

    calc B = -A := eq_neg_of_add_eq_zero_right h
      _ = A := neg_eq_of_add_eq_zero_left h2A
  have hABA : A + B ≠ A := fun h => hB0 (add_eq_left.mp h)
  have hABB : A + B ≠ B := fun h => hA0 (add_eq_right.mp h)
  have h0 : (0 : M) ∈ T := (hT 0).mpr (smul_zero 2)
  have hsub : ({0, A, B, A + B} : Finset M) ⊆ T := by
    intro P hP
    simp only [Finset.mem_insert, Finset.mem_singleton] at hP
    rcases hP with rfl | rfl | rfl | rfl <;> assumption
  have hcard4 : ({0, A, B, A + B} : Finset M).card = 4 := by
    rw [Finset.card_insert_of_notMem, Finset.card_insert_of_notMem, Finset.card_pair hABB.symm]
    · simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
      exact ⟨hBA.symm, hABA.symm⟩
    · simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
      exact ⟨hA0.symm, hB0.symm, hAB0.symm⟩
  have heq : ({0, A, B, A + B} : Finset M) = T :=
    Finset.eq_of_subset_of_card_le hsub (by rw [hcard, hcard4])
  rw [← heq, Finset.sum_insert, Finset.sum_insert, Finset.sum_pair hABB.symm]
  · have : (0 : M) + (A + (B + (A + B))) = 2 • A + 2 • B := by abel
    rw [this, h2A, h2B, add_zero]
  · simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
    exact ⟨hBA.symm, hABA.symm⟩
  · simp only [Finset.mem_insert, Finset.mem_singleton, not_or]
    exact ⟨hA0.symm, hB0.symm, hAB0.symm⟩

theorem solution {F K : Type*} [Field F] [Field K] [Algebra F K] [IsAlgClosed K] [DecidableEq K] (W : WeierstrassCurve F) [W.IsElliptic] {n : ℕ} (hnK : (n : K) ≠ 0) (s : Finset (W⁄K).Point) (hs : ∀ P, P ∈ s ↔ n • P = 0) : ∑ P ∈ s, P = 0 := by
  classical
  rw [← Finset.sum_filter_add_sum_filter_not s (fun P => 2 • P = 0)]

  have hrest : ∑ P ∈ s.filter (fun P => ¬2 • P = 0), P = 0 := by
    refine Finset.sum_involution (fun P _ => -P) (fun P _ => add_neg_cancel P)
      (fun P hP _ => ?_) (fun P hP => ?_) (fun P _ => neg_neg P)
    · rw [Finset.mem_filter] at hP
      intro h
      apply hP.2
      rw [two_nsmul]
      nth_rw 1 [← h]
      exact neg_add_cancel P
    · rw [Finset.mem_filter] at hP ⊢
      refine ⟨(hs _).mpr ?_, ?_⟩
      · rw [smul_neg, (hs _).mp hP.1, _root_.neg_zero]
      · rw [smul_neg, neg_eq_zero]
        exact hP.2
  rw [hrest, add_zero]
  rcases Nat.even_or_odd n with ⟨k, rfl⟩ | ⟨k, rfl⟩
  ·
    have h2K : (2 : K) ≠ 0 := by
      intro h
      apply hnK
      push_cast
      rw [← two_mul, h, zero_mul]
    set T := s.filter (fun P => 2 • P = 0) with hTdef
    have hT : ∀ P, P ∈ T ↔ 2 • P = 0 := fun P => by
      rw [hTdef, Finset.mem_filter, and_iff_right_iff_imp]
      intro h2P
      rw [hs, ← two_mul, mul_nsmul, h2P, smul_zero]
    have hcard : T.card = 4 := by
      have hc := WeierstrassCurve.card_torsion_of_isAlgClosed (K := K) W (n := 2)
        (by exact_mod_cast h2K)
      rw [← Nat.card_eq_finsetCard, show (4 : ℕ) = 2 ^ 2 by norm_num, ← hc]
      refine Nat.card_congr (Equiv.subtypeEquivRight fun P => ?_)
      rw [hT, Submodule.mem_torsionBy_iff]
      push_cast
      rw [ofNat_zsmul]
    exact sum_eq_zero_of_two_torsion_card_four T hT hcard
  ·
    refine Finset.sum_eq_zero fun P hP => ?_
    rw [Finset.mem_filter] at hP
    obtain ⟨hPs, h2P⟩ := hP
    have hnP := (hs P).mp hPs
    rwa [add_nsmul, one_nsmul, mul_nsmul, h2P, smul_zero, zero_add] at hnP

end S_WeierstrassCurve_sum_eq_zero_of_forall_mem_iff_smul_eq_zero
end P2MW
export P2MW.S_WeierstrassCurve_sum_eq_zero_of_forall_mem_iff_smul_eq_zero (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point

theorem WeierstrassCurve.sum_eq_zero_of_forall_mem_iff_smul_eq_zero {F K : Type*} [Field F] [Field K] [Algebra F K] [IsAlgClosed K] [DecidableEq K] (W : WeierstrassCurve F) [W.IsElliptic] {n : ℕ} (hnK : (n : K) ≠ 0) (s : Finset (W⁄K).Point) (hs : ∀ P, P ∈ s ↔ n • P = 0) : ∑ P ∈ s, P = 0 := _root_.P2MW.S_WeierstrassCurve_sum_eq_zero_of_forall_mem_iff_smul_eq_zero.solution W hnK s hs

end publicSection
