/-
Based on Prove2Me node WeierstrassCurve.exists_addEquiv_point_variableChange
(8de1afe9-e422-5510-9234-bbf863be0ba2) by Claude (2026-09-05).

Proof based on Prove2Me submission fcc8ed04-b73e-5162-9920-fae34884feec
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point

import Definitions.FLT.Def_P2M_Util

/-!
# Variable change induces an isomorphism of point groups

Theorem statement: `WeierstrassCurve.exists_addEquiv_point_variableChange`
(`8de1afe9-e422-5510-9234-bbf863be0ba2`), by Claude, 2026-09-05.

Proof: submission `fcc8ed04-b73e-5162-9920-fae34884feec`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, let $W$ be a Weierstrass curve over $K$ (given by coefficients
$a_1,a_2,a_3,a_4,a_6$), and let $C$ be a Weierstrass variable change over $K$, that is a quadruple
consisting of a unit $u \in K^\times$ and scalars $r,s,t \in K$. Write $C \bullet W$ for the
Weierstrass curve obtained from $W$ by the action of $C$. The assertion is that there exists an
isomorphism of additive groups $e \colon W^{\mathrm{aff}}(K) \to (C \bullet W)^{\mathrm{aff}}(K)$
between the groups of points of the associated affine Weierstrass curves (nonsingular $K$-rational
affine points together with the point at infinity, with the chord–tangent addition), with the
following property: for all $x,y \in K$ and every proof $h$ that $(x,y)$ is a nonsingular point of
the affine curve attached to $W$, the pair $$\bigl(u^{-2}(x-r),\; u^{-3}(y - sx + (sr - t))\bigr)$$
is a nonsingular point of the affine curve attached to $C \bullet W$, and $e$ sends the affine point
$(x,y)$ of $W$ to that point of $C \bullet W$. No claim beyond additivity and bijectivity is made
about the behaviour of $e$ at the point at infinity.

This is the elementary statement that two Weierstrass models related by an admissible change of
coordinates $(x,y) = (u^2x' + r,\, u^3y' + u^2sx' + t)$ have isomorphic groups of $K$-rational
points, with the isomorphism written out in coordinates by the inverse substitution. It is used to
transport explicit points and point-group computations between models of one elliptic curve, and is
invoked in the Čerednik–Drinfel'd part of the development when comparing curves differing by a
variable change.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_exists_addEquiv_point_variableChange.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_exists_addEquiv_point_variableChange

p2m_open "WeierstrassCurve P2MW.S_WeierstrassCurve_exists_addEquiv_point_variableChange.WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point"

namespace WeierstrassCurve
p2m_export "WeierstrassCurve" "Affine Affine.Equation Affine.negY Affine.evalEval_polynomial Affine.Y_eq_of_Y_ne Affine.slope_of_X_ne Affine.Point.add_of_Y_eq map variableChange_a₃ Affine.evalEval_polynomialX Affine.Point.some Affine.Point.some.injEq Affine.Nonsingular variableChange_a₆ Affine.negAddY Affine.slope_of_Y_ne_eq_evalEval variableChange_a₂ toAffine Affine.Point Affine.evalEval_polynomialY Affine.addX Affine.Point.add_some variableChange_a₁ variableChange_a₄ VariableChange Affine.addY exists_addEquiv_point_variableChange_dev"
p2m_open "WeierstrassCurve"

namespace VariableChange
p2m_export "WeierstrassCurve.VariableChange" "map u t s r"
p2m_open "WeierstrassCurve.VariableChange"

section Ring

variable {R : Type*} [CommRing R] (C : VariableChange R) (W : WeierstrassCurve R)

private def _root_.WeierstrassCurve.VariableChange.ptX (x : R) : R := (↑C.u⁻¹ : R) ^ 2 * (x - C.r)

p2m_export "WeierstrassCurve.VariableChange" "ptX"

private def _root_.WeierstrassCurve.VariableChange.ptY (x y : R) : R := (↑C.u⁻¹ : R) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))

p2m_export "WeierstrassCurve.VariableChange" "ptY"

private def _root_.WeierstrassCurve.VariableChange.invX (X : R) : R := (C.u : R) ^ 2 * X + C.r

p2m_export "WeierstrassCurve.VariableChange" "invX"

private def _root_.WeierstrassCurve.VariableChange.invY (X Y : R) : R := (C.u : R) ^ 3 * Y + (C.u : R) ^ 2 * C.s * X + C.t

p2m_export "WeierstrassCurve.VariableChange" "invY"
lemma invX_ptX (x : R) : C.invX (C.ptX x) = x := by
  simp only [invX, ptX]
  linear_combination (x - C.r) * pow_mul_pow_eq_one 2 C.u.mul_inv

lemma invY_ptY (x y : R) : C.invY (C.ptX x) (C.ptY x y) = y := by
  simp only [invY, ptX, ptY]
  linear_combination (y - C.s * x + (C.s * C.r - C.t)) * pow_mul_pow_eq_one 3 C.u.mul_inv
    + C.s * (x - C.r) * pow_mul_pow_eq_one 2 C.u.mul_inv

lemma ptX_invX (X : R) : C.ptX (C.invX X) = X := by
  simp only [invX, ptX]
  linear_combination X * pow_mul_pow_eq_one 2 C.u.inv_mul

lemma ptY_invY (X Y : R) : C.ptY (C.invX X) (C.invY X Y) = Y := by
  simp only [invX, invY, ptY]
  linear_combination Y * pow_mul_pow_eq_one 3 C.u.inv_mul

private lemma _root_.WeierstrassCurve.VariableChange.ptX_injective : Function.Injective C.ptX := fun x₁ x₂ h => by
  simpa only [invX_ptX] using congr_arg C.invX h

p2m_export "WeierstrassCurve.VariableChange" "ptX_injective"
private lemma _root_.WeierstrassCurve.VariableChange.ptY_injective (x : R) : Function.Injective (C.ptY x) := fun y₁ y₂ h => by
  simpa only [invY_ptY] using congr_arg (C.invY (C.ptX x)) h

p2m_export "WeierstrassCurve.VariableChange" "ptY_injective"
lemma negY_pt (x y : R) :
    (C • W).toAffine.negY (C.ptX x) (C.ptY x y) = C.ptY x (W.toAffine.negY x y) := by
  simp only [Affine.negY, ptX, ptY, variableChange_a₁, variableChange_a₃]
  ring

lemma addX_pt (x₁ x₂ ℓ : R) :
    (C • W).toAffine.addX (C.ptX x₁) (C.ptX x₂) (↑C.u⁻¹ * (ℓ - C.s)) =
      C.ptX (W.toAffine.addX x₁ x₂ ℓ) := by
  simp only [Affine.addX, ptX, variableChange_a₁, variableChange_a₂]
  ring

lemma addY_pt (x₁ x₂ y₁ ℓ : R) :
    (C • W).toAffine.addY (C.ptX x₁) (C.ptX x₂) (C.ptY x₁ y₁) (↑C.u⁻¹ * (ℓ - C.s)) =
      C.ptY (W.toAffine.addX x₁ x₂ ℓ) (W.toAffine.addY x₁ x₂ y₁ ℓ) := by
  simp only [Affine.addY, Affine.negAddY, Affine.addX, Affine.negY, ptX, ptY, variableChange_a₁,
    variableChange_a₂, variableChange_a₃]
  ring

lemma evalEval_polynomial_pt (x y : R) :
    (C • W).toAffine.polynomial.evalEval (C.ptX x) (C.ptY x y) =
      ↑C.u⁻¹ ^ 6 * W.toAffine.polynomial.evalEval x y := by
  rw [Affine.evalEval_polynomial, Affine.evalEval_polynomial]
  simp only [ptX, ptY, variableChange_a₁, variableChange_a₂, variableChange_a₃, variableChange_a₄,
    variableChange_a₆]
  ring

lemma evalEval_polynomialX_pt (x y : R) :
    (C • W).toAffine.polynomialX.evalEval (C.ptX x) (C.ptY x y) =
      ↑C.u⁻¹ ^ 4 * (W.toAffine.polynomialX.evalEval x y
        + C.s * W.toAffine.polynomialY.evalEval x y) := by
  rw [Affine.evalEval_polynomialX, Affine.evalEval_polynomialX, Affine.evalEval_polynomialY]
  simp only [ptX, ptY, variableChange_a₁, variableChange_a₂, variableChange_a₄]
  ring

lemma evalEval_polynomialY_pt (x y : R) :
    (C • W).toAffine.polynomialY.evalEval (C.ptX x) (C.ptY x y) =
      ↑C.u⁻¹ ^ 3 * W.toAffine.polynomialY.evalEval x y := by
  rw [Affine.evalEval_polynomialY, Affine.evalEval_polynomialY]
  simp only [ptX, ptY, variableChange_a₁, variableChange_a₃]
  ring

lemma equation_pt_iff (x y : R) :
    (C • W).toAffine.Equation (C.ptX x) (C.ptY x y) ↔ W.toAffine.Equation x y := by
  rw [Affine.Equation, Affine.Equation, evalEval_polynomial_pt,
    (C.u⁻¹.isUnit.pow 6).mul_right_eq_zero]

lemma nonsingular_pt_iff (x y : R) :
    (C • W).toAffine.Nonsingular (C.ptX x) (C.ptY x y) ↔ W.toAffine.Nonsingular x y := by
  rw [Affine.Nonsingular, Affine.Nonsingular, equation_pt_iff, evalEval_polynomialX_pt,
    evalEval_polynomialY_pt]
  simp only [ne_eq, (C.u⁻¹.isUnit.pow 4).mul_right_eq_zero, (C.u⁻¹.isUnit.pow 3).mul_right_eq_zero]
  refine and_congr_right fun _ => ?_
  by_cases hY : W.toAffine.polynomialY.evalEval x y = 0
  · simp only [hY, mul_zero, add_zero, not_true_eq_false, or_false]
  · simp only [hY, not_false_eq_true, or_true]

lemma nonsingular_inv_iff (X Y : R) :
    W.toAffine.Nonsingular (C.invX X) (C.invY X Y) ↔ (C • W).toAffine.Nonsingular X Y := by
  rw [← nonsingular_pt_iff C W, ptX_invX, ptY_invY]

end Ring

section Field

variable {K : Type*} [Field K] [DecidableEq K] (C : VariableChange K) (W : WeierstrassCurve K)

lemma slope_pt {x₁ x₂ y₁ y₂ : K} (h₁ : W.toAffine.Equation x₁ y₁) (h₂ : W.toAffine.Equation x₂ y₂)
    (hxy : ¬(x₁ = x₂ ∧ y₁ = W.toAffine.negY x₂ y₂)) :
    (C • W).toAffine.slope (C.ptX x₁) (C.ptX x₂) (C.ptY x₁ y₁) (C.ptY x₂ y₂) =
      ↑C.u⁻¹ * (W.toAffine.slope x₁ x₂ y₁ y₂ - C.s) := by
  have hu : (↑C.u⁻¹ : K) ≠ 0 := C.u⁻¹.ne_zero
  have hu' : (↑C.u : K) ≠ 0 := C.u.ne_zero
  by_cases hx : x₁ = x₂
  · have hy : y₁ ≠ W.toAffine.negY x₂ y₂ := fun h => hxy ⟨hx, h⟩
    obtain rfl : y₁ = y₂ := Affine.Y_eq_of_Y_ne h₁ h₂ hx hy
    subst hx
    have hy' : C.ptY x₁ y₁ ≠ (C • W).toAffine.negY (C.ptX x₁) (C.ptY x₁ y₁) := by
      rw [negY_pt]
      exact fun h => hy (C.ptY_injective x₁ h)
    have hB : W.toAffine.polynomialY.evalEval x₁ y₁ ≠ 0 := by
      rw [Affine.evalEval_polynomialY]
      intro h
      apply hy
      simp only [Affine.negY]
      linear_combination h
    rw [Affine.slope_of_Y_ne_eq_evalEval rfl hy', Affine.slope_of_Y_ne_eq_evalEval rfl hy,
      evalEval_polynomialX_pt, evalEval_polynomialY_pt]
    field_simp
    ring
  · have hx' : C.ptX x₁ ≠ C.ptX x₂ := fun h => hx (C.ptX_injective h)
    rw [Affine.slope_of_X_ne hx', Affine.slope_of_X_ne hx]
    have hd : x₁ - x₂ ≠ 0 := sub_ne_zero.mpr hx
    have hden : C.ptX x₁ - C.ptX x₂ = ↑C.u⁻¹ ^ 2 * (x₁ - x₂) := by simp only [ptX]; ring
    have hnum : C.ptY x₁ y₁ - C.ptY x₂ y₂ = ↑C.u⁻¹ ^ 3 * ((y₁ - y₂) - C.s * (x₁ - x₂)) := by
      simp only [ptY]; ring
    rw [hden, hnum]
    field_simp

end Field

section SameField

variable {K : Type*} [Field K] [DecidableEq K] (W : WeierstrassCurve K) (C : VariableChange K)

noncomputable def pointFun₀ : W.toAffine.Point → (C • W).toAffine.Point
  | 0 => 0
  | .some x y h => .some (C.ptX x) (C.ptY x y) <| (nonsingular_pt_iff C W x y).mpr h

noncomputable def pointInv₀ : (C • W).toAffine.Point → W.toAffine.Point
  | 0 => 0
  | .some X Y h => .some (C.invX X) (C.invY X Y) <| (nonsingular_inv_iff C W X Y).mpr h

noncomputable def pointEquiv₀ : W.toAffine.Point ≃+ (C • W).toAffine.Point where
  toFun := pointFun₀ W C
  invFun := pointInv₀ W C
  left_inv := by
    rintro (_ | ⟨x, y, h⟩)
    · rfl
    · simp only [pointFun₀, pointInv₀, invX_ptX, invY_ptY]
  right_inv := by
    rintro (_ | ⟨X, Y, h⟩)
    · rfl
    · simp only [pointFun₀, pointInv₀, ptX_invX, ptY_invY]
  map_add' := by
    rintro (_ | ⟨x₁, y₁, h₁⟩) (_ | ⟨x₂, y₂, h₂⟩)
    · rfl
    · rfl
    · rfl
    · by_cases hxy : x₁ = x₂ ∧ y₁ = W.toAffine.negY x₂ y₂
      · rcases hxy with ⟨rfl, rfl⟩
        rw [Affine.Point.add_of_Y_eq rfl rfl]
        simp only [pointFun₀]
        exact (Affine.Point.add_of_Y_eq rfl (negY_pt C W x₁ y₂).symm).symm
      · have hxy' : ¬(C.ptX x₁ = C.ptX x₂ ∧ C.ptY x₁ y₁ =
            (C • W).toAffine.negY (C.ptX x₂) (C.ptY x₂ y₂)) := by
          rintro ⟨hx, hy⟩
          obtain rfl := C.ptX_injective hx
          rw [negY_pt] at hy
          exact hxy ⟨rfl, C.ptY_injective x₁ hy⟩
        rw [Affine.Point.add_some hxy]
        simp only [pointFun₀]
        rw [Affine.Point.add_some hxy', Affine.Point.some.injEq,
          slope_pt C W h₁.1 h₂.1 hxy, addX_pt, addY_pt]
        exact ⟨rfl, rfl⟩

lemma pointEquiv₀_some {x y : K} (h : W.toAffine.Nonsingular x y) :
    pointEquiv₀ W C (.some x y h) = .some (C.ptX x) (C.ptY x y) ((nonsingular_pt_iff C W x y).mpr h) :=
  rfl

private theorem _root_.WeierstrassCurve.exists_addEquiv_point_variableChange_dev :
    ∃ e : W.toAffine.Point ≃+ (C • W).toAffine.Point, ∀ (x y : K) (h : W.toAffine.Nonsingular x y),
      ∃ h' : (C • W).toAffine.Nonsingular ((↑C.u⁻¹ : K) ^ 2 * (x - C.r))
          ((↑C.u⁻¹ : K) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))),
        e (WeierstrassCurve.Affine.Point.some x y h) =
          WeierstrassCurve.Affine.Point.some ((↑C.u⁻¹ : K) ^ 2 * (x - C.r))
            ((↑C.u⁻¹ : K) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))) h' :=
  ⟨pointEquiv₀ W C, fun x y h => ⟨(nonsingular_pt_iff C W x y).mpr h, rfl⟩⟩

p2m_alias "P2MW.S_WeierstrassCurve_exists_addEquiv_point_variableChange.WeierstrassCurve.exists_addEquiv_point_variableChange_dev" "WeierstrassCurve.exists_addEquiv_point_variableChange_dev"
end SameField

end VariableChange

end WeierstrassCurve

theorem solution {K : Type*} [Field K] [DecidableEq K] (W : WeierstrassCurve K) (C : VariableChange K) : ∃ e : W.toAffine.Point ≃+ (C • W).toAffine.Point, ∀ (x y : K) (h : W.toAffine.Nonsingular x y), ∃ h' : (C • W).toAffine.Nonsingular ((↑C.u⁻¹ : K) ^ 2 * (x - C.r)) ((↑C.u⁻¹ : K) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))), e (WeierstrassCurve.Affine.Point.some x y h) = WeierstrassCurve.Affine.Point.some ((↑C.u⁻¹ : K) ^ 2 * (x - C.r)) ((↑C.u⁻¹ : K) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))) h' :=
  ⟨WeierstrassCurve.VariableChange.pointEquiv₀ W C, fun x y h =>
    ⟨(WeierstrassCurve.VariableChange.nonsingular_pt_iff C W x y).mpr h, rfl⟩⟩

end S_WeierstrassCurve_exists_addEquiv_point_variableChange
end P2MW
export P2MW.S_WeierstrassCurve_exists_addEquiv_point_variableChange (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point
theorem WeierstrassCurve.exists_addEquiv_point_variableChange {K : Type*} [Field K] [DecidableEq K] (W : WeierstrassCurve K) (C : VariableChange K) : ∃ e : W.toAffine.Point ≃+ (C • W).toAffine.Point, ∀ (x y : K) (h : W.toAffine.Nonsingular x y), ∃ h' : (C • W).toAffine.Nonsingular ((↑C.u⁻¹ : K) ^ 2 * (x - C.r)) ((↑C.u⁻¹ : K) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))), e (WeierstrassCurve.Affine.Point.some x y h) = WeierstrassCurve.Affine.Point.some ((↑C.u⁻¹ : K) ^ 2 * (x - C.r)) ((↑C.u⁻¹ : K) ^ 3 * (y - C.s * x + (C.s * C.r - C.t))) h' := _root_.P2MW.S_WeierstrassCurve_exists_addEquiv_point_variableChange.solution W C

end publicSection
