/-
Based on Prove2Me node ModularCurve.isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1
(b51596c5-4aed-52ae-9d37-c0c2d6a8e142) by Claude (2026-09-05).

Proof based on Prove2Me submission 570ba626-8652-5ec1-bdbd-fd4a3a226839
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_IsCurveOver
public import Definitions.FLT.Def_ModularCurve_X1

import Theorems.FLT.Thm_AlgebraicCurve_isCurveOver_of_transcendental_of_perfectField
import Theorems.FLT.Thm_ModularCurve_JOneES_exists_transcendental_finiteDimensional_laurentBaseChange
import Definitions.FLT.Def_P2M_Util

/-!
# K·ℚ(X₁(M)) is a curve over K

Theorem statement: `ModularCurve.isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1`
(`b51596c5-4aed-52ae-9d37-c0c2d6a8e142`), by Claude, 2026-09-05.

Proof: submission `570ba626-8652-5ec1-bdbd-fd4a3a226839`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field of characteristic zero (an algebra over $\mathbb{Q}$) that is algebraically
closed, and let $M$ be a positive natural number. Consider first the intermediate field $\mathbb{Q}
\subseteq \mathtt{qExpFunctionFieldC}\ \mathbb{Q}\ \Gamma_1(M) \subseteq \mathbb{Q}((q))$ obtained
by adjoining to $\mathbb{Q}$ the set of all Laurent series of the form
$\mathrm{intSeriesC}\,\mathbb{Q}\,p_f / \mathrm{intSeriesC}\,\mathbb{Q}\,p_g$, where $f,g$ are
modular forms of some common weight $k$ for the image of $\Gamma_1(M)$ in
$\mathrm{GL}_2(\mathbb{R})$ whose $q$-expansions are given by integral power series $p_f,p_g$ (in
the sense of `IsIntegralQExp`) with $\mathrm{intSeriesC}\,\mathbb{Q}\,p_g \neq 0$. Let $F_K :=
\mathtt{laurentBaseChange}\,K$ of this field, namely the intermediate field of $K((q))$ generated
over $K$ by the image of that field under the coefficientwise ring homomorphism $\mathbb{Q}((q)) \to
K((q))$ induced by $\mathbb{Q} \to K$. The assertion is that $F_K$ satisfies
[`AlgebraicCurve.IsCurveOver K`](def/AlgebraicCurve_IsCurveOver.html#L15), i.e.: every nonzero $f
\in F_K$ admits a divisor $D$ with $D(v) = \mathrm{ord}_v(f)$ at every place $v$ of $F_K/K$ (a
proper valuation subring of $F_K$ containing $K$ which is a principal ideal ring) and with $\deg D =
0$; each such place has residue field finite-dimensional over $K$; and the module of Kähler
differentials $\Omega_{F_K/K}$ is free of rank $1$ over $F_K$.

This identifies the base-changed $q$-expansion function field of $X_1(M)$ as a curve in the
project's axiomatic sense, the setting in which places, divisors, degrees and differentials of
$X_1(M)$ over an algebraically closed field of characteristic zero are manipulated. It is the input
to the finiteness of Riemann–Roch spaces for $F_K$, to the construction of the divisor attached to
the weight floor, and to the description of points of $X_1(p)$ in terms of the divisor class group.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1
p2m_attr_erase "instance" "AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero"
p2m_attr_erase "simp" "ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one"

open ModularCurve CongruenceSubgroup AlgebraicCurve
open scoped MatrixGroups

theorem solution
    (K : Type*) [Field K] [Algebra ℚ K] [IsAlgClosed K] (M : ℕ) [NeZero M] :
    AlgebraicCurve.IsCurveOver K ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M))) := by
  obtain ⟨x, htr, hfd⟩ := ModularCurve.JOneES.exists_transcendental_finiteDimensional_laurentBaseChange
    K (CongruenceSubgroup.Gamma1 M) (by rw [CongruenceSubgroup.Gamma1_mem]; simp [ModularGroup.T])
  exact AlgebraicCurve.isCurveOver_of_transcendental_of_perfectField htr hfd

end S_ModularCurve_isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1
end P2MW
export P2MW.S_ModularCurve_isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1 (solution)

end privateSection

public section publicSection


open ModularCurve CongruenceSubgroup AlgebraicCurve
open scoped MatrixGroups
theorem ModularCurve.isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1
    (K : Type*) [Field K] [Algebra ℚ K] [IsAlgClosed K] (M : ℕ) [NeZero M] :
    AlgebraicCurve.IsCurveOver K ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M))) := _root_.P2MW.S_ModularCurve_isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1.solution K M

end publicSection
