/-
Based on Prove2Me node ModularCurve.finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1
(d56581c0-5133-56e9-8c0e-d24c21066309) by Claude (2026-09-05).

Proof based on Prove2Me submission 59b6839b-4777-5db0-8277-3c5fc6216fcd
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_Repartitions
public import Definitions.FLT.Def_ModularCurve_X1

import Theorems.FLT.Thm_AlgebraicCurve_essFiniteType_of_transcendental_of_finiteDimensional
import Theorems.FLT.Thm_AlgebraicCurve_finiteDimensional_lSpace
import Theorems.FLT.Thm_AlgebraicCurve_finiteDimensional_lSpace_zero
import Theorems.FLT.Thm_AlgebraicCurve_nonempty_place_of_transcendental_of_finiteDimensional
import Theorems.FLT.Thm_ModularCurve_JOneES_exists_transcendental_finiteDimensional_laurentBaseChange
import Theorems.FLT.Thm_ModularCurve_isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1
import Definitions.FLT.Def_P2M_Util

/-!
# Riemann–Roch spaces of K·ℚ(X₁(M)) are finite-dimensional

Theorem statement:
`ModularCurve.finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1`
(`d56581c0-5133-56e9-8c0e-d24c21066309`), by Claude, 2026-09-05.

Proof: submission `59b6839b-4777-5db0-8277-3c5fc6216fcd`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be an algebraically closed field equipped with a $\mathbb{Q}$-algebra structure, and let $M$
be a nonzero natural number. Write $F_\mathbb{Q}$ for `qExpFunctionFieldC ℚ (Gamma1 M)`, the
intermediate field of the field $\mathbb{Q}((q))$ of Laurent series over $\mathbb{Q}$ generated over
$\mathbb{Q}$ by all quotients $\iota(p_f)/\iota(p_g)$ of Laurent series attached to integral
$q$-expansions $p_f,p_g\in\mathbb{Z}[[q]]$ of modular forms $f,g$ of some weight $k$ for
$\Gamma_1(M)$ (with $\iota(p_g)\neq 0$), and let $F_K$ be `laurentBaseChange K F_\mathbb{Q}`, the
intermediate field of $K((q))$ generated over $K$ by the image of $F_\mathbb{Q}$ under the
coefficientwise map $\mathbb{Q}((q))\to K((q))$ induced by $\mathbb{Q}\to K$. Let $D$ be a divisor
of $F_K$ over $K$, i.e. a finitely supported $\mathbb{Z}$-valued function on the set of places of
$F_K/K$, a place being a valuation subring of $F_K$ that contains the image of $K$, is not all of
$F_K$, and is a principal ideal ring. Then the Riemann–Roch space $L(D)$, the $K$-submodule of those
$f\in F_K$ with $v(f)\le \exp(D(v))$ in $\mathbb{Z}^{m0}$ for every place $v$, where $v$ denotes the
associated adic valuation, is finite-dimensional over $K$.

This is the finiteness half of the Riemann–Roch theory for the function field
$K\cdot\mathbb{Q}(X_1(M))$ of the modular curve $X_1(M)$ over an algebraically closed field of
characteristic zero. It supplies the finite-dimensionality needed to extract a basis of $L(D)$ when
lower bounds for $\dim_K M_{2m}(\Gamma_1(M))$ are proved, and is cited in both the even and odd
weight cases of the dimension estimate for modular forms on $\Gamma_1(M)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen"
p2m_attr_erase "simp" "ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one"

set_option synthInstance.maxHeartbeats 1600000

open ModularCurve CongruenceSubgroup AlgebraicCurve
open scoped MatrixGroups

set_option maxHeartbeats 6400000 in
theorem solution
    (K : Type*) [Field K] [Algebra ℚ K] [IsAlgClosed K] (M : ℕ) [NeZero M]
    (D : AlgebraicCurve.Divisor K ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M)))) :
    FiniteDimensional K ↥(AlgebraicCurve.riemannRochSpace D) := by
  obtain ⟨x, htr, hfd⟩ : ∃ x : ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M))),
      Transcendental K x ∧ FiniteDimensional ↥(IntermediateField.adjoin K ({x} : Set _)) _ :=
    ModularCurve.JOneES.exists_transcendental_finiteDimensional_laurentBaseChange
      K (CongruenceSubgroup.Gamma1 M) (by rw [CongruenceSubgroup.Gamma1_mem]; simp [ModularGroup.T])
  have := hfd
  have : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ K).injective
  have : Algebra.IsAlgebraic ↥(IntermediateField.adjoin K ({x} : Set _))
      ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M))) :=
    Algebra.IsAlgebraic.of_finite _ _
  have : Algebra.IsSeparable ↥(IntermediateField.adjoin K ({x} : Set _))
      ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M))) :=
    Algebra.IsAlgebraic.isSeparable_of_perfectField
  have := AlgebraicCurve.nonempty_place_of_transcendental_of_finiteDimensional K x htr hfd
  have := ModularCurve.isCurveOver_laurentBaseChange_qExpFunctionFieldC_gamma1 K M
  have := AlgebraicCurve.essFiniteType_of_transcendental_of_finiteDimensional htr hfd
  have := AlgebraicCurve.finiteDimensional_lSpace_zero K
    ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M)))
  exact AlgebraicCurve.finiteDimensional_lSpace D

end S_ModularCurve_finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1
end P2MW
export P2MW.S_ModularCurve_finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1 (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve CongruenceSubgroup
open AlgebraicCurve
open scoped MatrixGroups
theorem ModularCurve.finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1
    (K : Type*) [Field K] [Algebra ℚ K] [IsAlgClosed K] (M : ℕ) [NeZero M]
    (D : AlgebraicCurve.Divisor K ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ (CongruenceSubgroup.Gamma1 M)))) :
    FiniteDimensional K ↥(AlgebraicCurve.riemannRochSpace D) := _root_.P2MW.S_ModularCurve_finiteDimensional_riemannRochSpace_laurentBaseChange_qExpFunctionFieldC_gamma1.solution K M D

end publicSection
