/-
Based on Prove2Me node WeierstrassCurve.Affine.adjoin_yCoord_eq_top
(79d01350-dee8-5e1f-8179-7f315d731441) by Claude (2026-09-05).

Proof based on Prove2Me submission 987c4a87-b02f-5d37-828f-3c45b69ae14c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Defs

public import Definitions.FLT.Def_WeierstrassCurve_FunctionFieldQuadratic

import Definitions.FLT.Def_P2M_Util

/-!
# The function field is generated over F(x) by y

Theorem statement: `WeierstrassCurve.Affine.adjoin_yCoord_eq_top`
(`79d01350-dee8-5e1f-8179-7f315d731441`), by Claude, 2026-09-05.

Proof: submission `987c4a87-b02f-5d37-828f-3c45b69ae14c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be a field and let $W$ be an affine Weierstrass curve over $F$, with coordinate ring
$W.\mathrm{CoordinateRing}$ and function field $W.\mathrm{FunctionField}$, the latter carrying its
algebra structure over the rational function field $\mathrm{RatFunc}\,F$ (the $x$-coordinate
subfield) as set up in the definition module. Write $\mathrm{yCoord}\,W$ for the element of
$W.\mathrm{FunctionField}$ obtained by taking the class of the variable $Y$ in the coordinate ring
and mapping it along the structure map $W.\mathrm{CoordinateRing} \to W.\mathrm{FunctionField}$. The
assertion, with no further hypotheses on $F$ or on $W$, is that the intermediate field of
$W.\mathrm{FunctionField}/\mathrm{RatFunc}\,F$ generated by the single element $\mathrm{yCoord}\,W$
is the top intermediate field, i.e. equals all of $W.\mathrm{FunctionField}$: in classical notation,
$F(W) = F(x)(y)$, so that $F(W)$ is a simple extension of $F(x)$ generated by the $y$-coordinate
function.

This is the standard fact that the function field of a plane Weierstrass curve is generated over the
field of rational functions in $x$ by the coordinate function $y$. Combined with the integrality of
$\mathrm{yCoord}\,W$ over $\mathrm{RatFunc}\,F$, it yields the finite-dimensionality of
$W.\mathrm{FunctionField}$ over $\mathrm{RatFunc}\,F$ (of degree at most $2$), and it is used
further in the construction of principal divisors on the function field and in the descent to a
countable intermediate field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_adjoin_yCoord_eq_top.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_adjoin_yCoord_eq_top

open Polynomial WeierstrassCurve.Affine in
theorem solution {F : Type*} [Field F] {W : WeierstrassCurve.Affine F} :
    IntermediateField.adjoin (RatFunc F) {WeierstrassCurve.Affine.yCoord W} = ⊤ := by
  rw [eq_top_iff]
  rintro z -
  have hpoly : ∀ p : F[X],
      polyToFunctionField W p ∈ IntermediateField.adjoin (RatFunc F) {yCoord W} := by
    intro p
    rw [← algebraMap_polynomial_eq_polyToFunctionField,
      IsScalarTower.algebraMap_apply F[X] (RatFunc F) W.FunctionField]
    exact IntermediateField.algebraMap_mem _ _
  have hcoord : ∀ r : W.CoordinateRing,
      algebraMap W.CoordinateRing W.FunctionField r
        ∈ IntermediateField.adjoin (RatFunc F) {yCoord W} := by
    intro r
    obtain ⟨p, q, rfl⟩ := WeierstrassCurve.Affine.CoordinateRing.exists_smul_basis_eq r
    rw [algebraMap_smul_basis]
    exact add_mem (hpoly p)
      (mul_mem (hpoly q) (IntermediateField.mem_adjoin_simple_self _ _))
  obtain ⟨a, b, hb, hab⟩ := IsFractionRing.div_surjective (A := W.CoordinateRing) z
  rw [← hab]
  exact div_mem (hcoord a) (hcoord b)

end S_WeierstrassCurve_Affine_adjoin_yCoord_eq_top
end P2MW
export P2MW.S_WeierstrassCurve_Affine_adjoin_yCoord_eq_top (solution)

end privateSection

public section publicSection

theorem WeierstrassCurve.Affine.adjoin_yCoord_eq_top {F : Type*} [Field F] {W : WeierstrassCurve.Affine F} :
    IntermediateField.adjoin (RatFunc F) {WeierstrassCurve.Affine.yCoord W} = ⊤ := _root_.P2MW.S_WeierstrassCurve_Affine_adjoin_yCoord_eq_top.solution

end publicSection
