/-
Based on Prove2Me node HeckeEis.IsEquivariantPrimitiveWith.cocycle_sub_cocycle_mem_coeffCoboundaries
(64d2c2a5-369d-5e77-a6c0-6474236248c2) by Claude (2026-09-05).

Proof based on Prove2Me submission b1164faf-7cb9-5165-a40e-c88725ea7200
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_HeckeEis_EichlerIntegral

/-!
# Equivariant primitives differing by a constant: cohomologous cocycles

Theorem statement: `HeckeEis.IsEquivariantPrimitiveWith.cocycle_sub_cocycle_mem_coeffCoboundaries`
(`64d2c2a5-369d-5e77-a6c0-6474236248c2`), by Claude, 2026-09-05.

Proof: submission `b1164faf-7cb9-5165-a40e-c88725ea7200`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a commutative ring, $\Gamma$ a subgroup of $\mathrm{SL}_2(\mathbb{Z})$, and $V$ a
$K$-module carrying a representation $\rho$ of $\Gamma$. Let $F, G \colon \mathfrak{H} \to V$ be
functions on the upper half-plane, each of which is an equivariant primitive for $\rho$ in the sense
of [`HeckeEis.IsEquivariantPrimitiveWith`](def/HeckeEis_EichlerIntegral.html#L68): for every $\gamma
\in \Gamma$ there exists $c \in V$ with $F(\gamma \tau) - \rho(\gamma) F(\tau) = c$ for all $\tau
\in \mathfrak{H}$, and likewise for $G$. Assume further that there is $v \in V$ with $F(\tau) -
G(\tau) = v$ for all $\tau$, i.e. $F$ and $G$ differ by the constant $v$. The associated cocycles
are the functions $\Gamma \to V$ given by $\gamma \mapsto F(\gamma \cdot i) - \rho(\gamma) F(i)$ and
$\gamma \mapsto G(\gamma \cdot i) - \rho(\gamma) G(i)$, evaluated at the point $i$ of
$\mathfrak{H}$. The conclusion is that their difference lies in
[`HeckeEis.coeffCoboundaries`](def/Gamma0CoeffCohomology.html#L45) $\rho$, the image of the
$K$-linear map $V \to (\Gamma \to V)$ sending $w$ to $\gamma \mapsto \rho(\gamma) w - w$;
concretely, the difference is the coboundary attached to $-v$. The proof uses the equivariance
hypotheses only as the arguments needed to form the two cocycles, not their content.

This is the standard independence statement for the cocycle attached to an Eichler integral:
changing the primitive by a constant changes its cocycle by a coboundary, so the class in
coefficient cohomology is well defined. It is used in the identification of the Eichler–Shimura map
with the class map into parabolic cohomology and in the Hecke-equivariance statements for that map.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_IsEquivariantPrimitiveWith_cocycle_sub_cocycle_mem_coeffCoboundaries.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

open UpperHalfPlane HeckeEis
open scoped MatrixGroups

theorem solution
    {K : Type*} [CommRing K] {Γ : Subgroup SL(2, ℤ)} {V : Type*} [AddCommGroup V] [Module K V]
    {ρ : Representation K Γ V} {F G : UpperHalfPlane → V}
    (hF : HeckeEis.IsEquivariantPrimitiveWith ρ F) (hG : HeckeEis.IsEquivariantPrimitiveWith ρ G)
    {v : V} (h : ∀ τ : UpperHalfPlane, F τ - G τ = v) :
    hF.cocycle - hG.cocycle ∈ HeckeEis.coeffCoboundaries ρ := by
  rw [mem_coeffCoboundaries_iff]
  refine ⟨-v, funext fun γ => ?_⟩
  change ρ γ (-v) - -v = (F ((γ : SL(2, ℤ)) • I) - ρ γ (F I)) - (G ((γ : SL(2, ℤ)) • I) - ρ γ (G I))
  rw [map_neg, sub_eq_iff_eq_add.mp (h ((γ : SL(2, ℤ)) • I)), sub_eq_iff_eq_add.mp (h I), map_add]
  abel

end privateSection

public section publicSection

open scoped MatrixGroups
theorem HeckeEis.IsEquivariantPrimitiveWith.cocycle_sub_cocycle_mem_coeffCoboundaries
    {K : Type*} [CommRing K] {Γ : Subgroup SL(2, ℤ)} {V : Type*} [AddCommGroup V] [Module K V]
    {ρ : Representation K Γ V} {F G : UpperHalfPlane → V}
    (hF : HeckeEis.IsEquivariantPrimitiveWith ρ F) (hG : HeckeEis.IsEquivariantPrimitiveWith ρ G)
    {v : V} (h : ∀ τ : UpperHalfPlane, F τ - G τ = v) :
    hF.cocycle - hG.cocycle ∈ HeckeEis.coeffCoboundaries ρ := _root_.solution hF hG h

end publicSection
