/-
Based on Prove2Me node WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul
(4cabc47d-2752-5485-b03e-065ffa2feb5d) by Claude (2026-09-05).

Proof based on Prove2Me submission 3704093c-f9b2-5808-8911-6ab21d347427
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_EllipticCurve_WeilPairingFun
public import Definitions.FLT.Def_FLTPrelim_GaloisRep

import Mathlib.Tactic.Ring
import Theorems.FLT.Thm_WeierstrassCurve_Affine_valuation_placeOf_smul_of_algEquiv
import Theorems.FLT.Thm_WeierstrassCurve_Affine_valuation_weilFun
import Theorems.FLT.Thm_WeierstrassCurve_Affine_weilFun_ne_zero
import Theorems.FLT.Thm_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one
import Definitions.FLT.Def_P2M_Util

/-!
# Galois conjugation of the Weil function up to a constant

Theorem statement: `WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul`
(`4cabc47d-2752-5485-b03e-065ffa2feb5d`), by Claude, 2026-09-05.

Proof: submission `3704093c-f9b2-5808-8911-6ab21d347427`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra, $K$ algebraically closed, and let $W$ be a
Weierstrass curve over $F$ that is elliptic, such that the coordinate ring of the base change
$W\!\restriction_K$ (written `W⁄K`) is a Dedekind domain. Let $n$ be a natural number whose image in
$K$ is nonzero, let $\sigma$ be an $F$-algebra automorphism of $K$, and let $\Phi$ be a ring
endomorphism of the function field of `W⁄K` which, on classes of bivariate polynomials, is
coefficientwise conjugation by $\sigma$: for every $p \in K[X][Y]$, $\Phi$ sends the image in the
function field of the coordinate-ring class of $p$ to the image of the class of the polynomial
obtained by applying $\sigma$ to all coefficients of $p$. Finally let $T$ be a point of `W⁄K` with
$n \cdot T = 0$. The assertion is that there exists a unit $c$ of $K$ with
$\Phi(\mathtt{weilFun}\,W\,K\,n\,T) = c \cdot \mathtt{weilFun}\,W\,K\,n\,(\sigma \bullet T)$, where
$\mathtt{weilFun}\,W\,K\,m\,S$ denotes the quotient, inside the function field, of the images of the
chosen generators of the ideals `fibIdeal W K m S` and `fibIdeal W K m 0` (the generator being taken
when the ideal is principal, and $1$ otherwise), and $\sigma \bullet T$ is the action of $\sigma$ on
points.

This is the statement that the function $g_T$ underlying the construction of the Weil pairing on
$n$-torsion is Galois-equivariant up to a multiplicative constant: conjugating $g_T$ by $\sigma$
yields a constant multiple of $g_{\sigma T}$. It is used in the proof of the Galois equivariance of
the Weil pairing,
[`WeierstrassCurve.Affine.weilPairing0_galois`](thm.html#WeierstrassCurve.Affine.weilPairing0_galois).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_exists_map_weilFun_eq_mul_weilFun_smul.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_exists_map_weilFun_eq_mul_weilFun_smul
p2m_attr_erase "instance" "WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly"
p2m_attr_erase "simp" "compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two"

open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain IsDedekindDomain.HeightOneSpectrum WithZero
open Polynomial
open scoped Polynomial.Bivariate

namespace WeilGal

variable {F : Type*} [Field F] {K : Type*} [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K]
  (W : WeierstrassCurve F) [W.IsElliptic]

omit [IsAlgClosed K] [W.IsElliptic] in
theorem smul_point_ne_zero (σ : K ≃ₐ[F] K) {P : (W⁄K).Point} (hP : P ≠ 0) : σ • P ≠ 0 := by
  intro h
  apply hP
  have : σ • (0 : (W⁄K).Point) = 0 := smul_zero σ
  rw [← this] at h
  exact Point.map_injective _ (by rw [Point.algEquiv_smul_def, Point.algEquiv_smul_def] at h; exact h)

omit [IsAlgClosed K] [W.IsElliptic] in
theorem smul_point_eq_iff (σ : K ≃ₐ[F] K) {P Q : (W⁄K).Point} : σ • P = σ • Q ↔ P = Q :=
  ⟨fun h => Point.map_injective _
    (by rw [Point.algEquiv_smul_def, Point.algEquiv_smul_def] at h; exact h), fun h => by rw [h]⟩

omit [DecidableEq K] in
theorem exists_eq_algebraMap [DecidableEq K] [IsDedekindDomain (W⁄K).CoordinateRing]
    {f : (W⁄K).FunctionField}
    (hf : ∀ (P : (W⁄K).Point) (hP : P ≠ 0), (placeOf W K P hP).valuation (W⁄K).FunctionField f = 1) :
    ∃ c : K, c ≠ 0 ∧ f = algebraMap K (W⁄K).FunctionField c := by
  apply WeierstrassCurve.Affine.FunctionField.exists_eq_algebraMap_of_valuation_eq_one (W := W⁄K)
  intro v
  obtain ⟨P, hP, rfl⟩ := placeOf_surjective W K v
  exact hf P hP

end WeilGal

theorem solution {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] [IsDedekindDomain (W⁄K).CoordinateRing] {n : ℕ} (hn : (n : K) ≠ 0) (σ : K ≃ₐ[F] K) (Φ : (W⁄K).FunctionField →+* (W⁄K).FunctionField) (hΦ : ∀ p : K[X][Y], Φ (algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) p)) = algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K))))) {T : (W⁄K).Point} (hT : (n : ℤ) • T = 0) : ∃ c : Kˣ, Φ (weilFun W K n T) = algebraMap K (W⁄K).FunctionField (c : K) * weilFun W K n (σ • T) := by
  have hσT : (n : ℤ) • (σ • T) = 0 := by rw [← Point.algEquiv_smul_zsmul, hT, smul_zero]
  have hg0 := WeierstrassCurve.Affine.weilFun_ne_zero W hn hσT
  suffices h : ∃ c : K, c ≠ 0 ∧ Φ (weilFun W K n T) / weilFun W K n (σ • T) = algebraMap K _ c by
    obtain ⟨c, hc0, hc⟩ := h
    exact ⟨Units.mk0 c hc0, by rw [Units.val_mk0, ← hc, div_mul_cancel₀ _ hg0]⟩
  apply WeilGal.exists_eq_algebraMap W
  intro Q hQ

  set P := σ⁻¹ • Q with hPdef
  have hP : P ≠ 0 := WeilGal.smul_point_ne_zero W σ⁻¹ hQ
  have hQP : σ • P = Q := smul_inv_smul σ Q
  have hσP : σ • P ≠ 0 := by rw [hQP]; exact hQ
  have hplace : placeOf W K Q hQ = placeOf W K (σ • P) hσP := by
    congr 1; exact hQP.symm
  rw [map_div₀, hplace, WeierstrassCurve.Affine.valuation_placeOf_smul_of_algEquiv W σ Φ hΦ hP hσP,
    WeierstrassCurve.Affine.valuation_weilFun W hn hT P hP,
    WeierstrassCurve.Affine.valuation_weilFun W hn hσT (σ • P) hσP]
  have e1 : ((n : ℤ) • (σ • P) = σ • T) = ((n : ℤ) • P = T) := by
    rw [← Point.algEquiv_smul_zsmul, WeilGal.smul_point_eq_iff]
  have e2 : ((n : ℤ) • (σ • P) = 0) = ((n : ℤ) • P = 0) := by
    rw [← Point.algEquiv_smul_zsmul]
    conv_lhs => rw [← smul_zero σ]
    rw [WeilGal.smul_point_eq_iff]
  simp only [e1, e2]
  have hne : ∀ c : Prop, ∀ [Decidable c], (if c then (exp (-1 : ℤ) : ℤᵐ⁰) else 1) ≠ 0 := by
    intro c _; split_ifs; exacts [WithZero.coe_ne_zero, one_ne_zero]
  exact div_self (div_ne_zero (hne _) (hne _))

end S_WeierstrassCurve_Affine_exists_map_weilFun_eq_mul_weilFun_smul
end P2MW
export P2MW.S_WeierstrassCurve_Affine_exists_map_weilFun_eq_mul_weilFun_smul (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain WithZero
open Polynomial
open scoped Polynomial.Bivariate

theorem WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] [IsDedekindDomain (W⁄K).CoordinateRing] {n : ℕ} (hn : (n : K) ≠ 0) (σ : K ≃ₐ[F] K) (Φ : (W⁄K).FunctionField →+* (W⁄K).FunctionField) (hΦ : ∀ p : K[X][Y], Φ (algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) p)) = algebraMap (W⁄K).CoordinateRing (W⁄K).FunctionField (CoordinateRing.mk (W⁄K) (p.map (mapRingHom (σ : K →+* K))))) {T : (W⁄K).Point} (hT : (n : ℤ) • T = 0) : ∃ c : Kˣ, Φ (weilFun W K n T) = algebraMap K (W⁄K).FunctionField (c : K) * weilFun W K n (σ • T) := _root_.P2MW.S_WeierstrassCurve_Affine_exists_map_weilFun_eq_mul_weilFun_smul.solution W hn σ Φ hΦ hT

end publicSection
