/-
Based on Prove2Me node AlgebraicCurve.lSpace_eq_bot_of_degree_neg
(193c3207-9415-57ea-b35e-c8a7e63242ce) by Claude (2026-09-05).

Proof based on Prove2Me submission 9d0986d2-565d-5075-ac2e-80e33c9c2f69
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_AdelicIndex
public import Definitions.FLT.Def_AlgebraicCurve_IsCurveOver

import Definitions.FLT.Def_P2M_Util

/-!
# L(D)=0 for divisors of negative degree

Theorem statement: `AlgebraicCurve.lSpace_eq_bot_of_degree_neg`
(`193c3207-9415-57ea-b35e-c8a7e63242ce`), by Claude, 2026-09-05.

Proof: submission `9d0986d2-565d-5075-ac2e-80e33c9c2f69`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K \subseteq F$ be fields with $F$ a $K$-algebra, and let $D$ be a divisor of $F/K$, that is, a
finitely supported function from the set of places of $F/K$ to $\mathbb{Z}$; here a place is a
valuation subring $\mathcal{O}_v \subsetneq F$ which contains the image of $K$ and is a principal
ideal ring. Assume $F/K$ satisfies `IsCurveOver`: every nonzero $f \in F$ admits a divisor $P$ with
$P(v) = \operatorname{ord}_v(f)$ at every place $v$ and $\deg P = 0$; every residue field
$\mathcal{O}_v/\mathfrak{m}_v$ is finite-dimensional over $K$; and $\Omega_{F/K}$ is free of rank
$1$ over $F$. Assume further that $\deg D = \sum_v D(v)\,\deg v < 0$. Then the Riemann–Roch space
`LSpace D`, the $K$-submodule of those $f \in F$ with $v(f) \le \exp(D(v))$ for all places $v$, is
the zero submodule. Of the `IsCurveOver` data the proof uses only the existence of degree-zero
principal divisors.

This is the standard first consequence of the degree formalism in the theory of function fields of
one variable: a divisor of negative degree has trivial Riemann–Roch space. It underlies the
computation of $\ell(D) = \dim_K L(D)$ and is invoked throughout the Riemann–Roch development, for
instance in the finiteness and descent statements for Riemann–Roch spaces under reduction and
constant field extension.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_lSpace_eq_bot_of_degree_neg.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_lSpace_eq_bot_of_degree_neg

set_option maxHeartbeats 3200000

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place Divisor Divisor.degree HasPrincipalDivisors HasPrincipalDivisors.exists_divisor IsCurveOver LSpace ell mem_lSpace_iff_ord WeilDifferentialRankOne StichtenothGenusExists"
p2m_open "AlgebraicCurve"
namespace Place
p2m_export "AlgebraicCurve.Place" "deg ord ord_unit_smul_zpow exists_unit_mul_zpow toValuationSubring"
p2m_open "AlgebraicCurve.Place"
variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)
private theorem _root_.AlgebraicCurve.Place.ord_nonneg_of_mem {f : F} (hf : f ∈ v.toValuationSubring) : 0 ≤ v.ord f := by
  rcases eq_or_ne f 0 with rfl | hf0
  · simp
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  obtain ⟨n, u, hu⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible
      (x := (⟨f, hf⟩ : v.toValuationSubring)) (by simpa [Subtype.ext_iff] using hf0) hπ
  have hcoe : f = ((u : v.toValuationSubring) : F) * ((π : F) ^ (n : ℤ)) := by
    have h := congrArg (Subtype.val) hu
    push_cast at h
    rw [zpow_natCast]
    exact h
  rw [hcoe, v.ord_unit_smul_zpow u hπ (n : ℤ)]
  exact Int.natCast_nonneg n
p2m_export "AlgebraicCurve.Place" "ord_nonneg_of_mem"
private theorem _root_.AlgebraicCurve.Place.mem_of_ord_nonneg {f : F} (hf : f ≠ 0) (h : 0 ≤ v.ord f) :
    f ∈ v.toValuationSubring := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  obtain ⟨u, hu⟩ := v.exists_unit_mul_zpow hf hπ
  rw [hu, show v.ord f = (((v.ord f).toNat : ℕ) : ℤ) from (Int.toNat_of_nonneg h).symm,
    zpow_natCast]
  exact mul_mem (u : v.toValuationSubring).2 (pow_mem (π : v.toValuationSubring).2 _)
p2m_export "AlgebraicCurve.Place" "mem_of_ord_nonneg"
theorem mem_iff_ord_nonneg {f : F} (hf : f ≠ 0) :
    f ∈ v.toValuationSubring ↔ 0 ≤ v.ord f :=
  ⟨v.ord_nonneg_of_mem, v.mem_of_ord_nonneg hf⟩
end Place
end AlgebraicCurve

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place Divisor Divisor.degree HasPrincipalDivisors HasPrincipalDivisors.exists_divisor IsCurveOver LSpace ell mem_lSpace_iff_ord WeilDifferentialRankOne StichtenothGenusExists"
p2m_open "AlgebraicCurve"
variable {K F : Type*} [Field K] [Field F] [Algebra K F]
namespace Divisor
p2m_export "AlgebraicCurve.Divisor" "degree"
end Divisor
p2m_open_scoped "AlgebraicCurve.Divisor" in
theorem Divisor.degree_eq_sum_support (D : Divisor K F) :
    Divisor.degree D = ∑ v ∈ D.support, D v * (v.deg : ℤ) := by
  rw [Divisor.degree, Finsupp.liftAddHom_apply, Finsupp.sum]
  rfl
variable {D : Divisor K F}
p2m_open_scoped "AlgebraicCurve.Divisor" in

theorem Divisor.degree_nonneg_of_nonneg [IsCurveOver K F]
    {D : Divisor K F} (hD : ∀ v, 0 ≤ D v) : 0 ≤ Divisor.degree D := by
  rw [Divisor.degree_eq_sum_support]
  exact Finset.sum_nonneg fun v _ => mul_nonneg (hD v) (Int.natCast_nonneg _)
theorem lSpace_eq_bot_of_degree_neg_port [IsCurveOver K F]
    (hD : Divisor.degree D < 0) : LSpace D = ⊥ := by
  rw [eq_bot_iff]
  intro f hf
  rw [Submodule.mem_bot]
  by_contra hf0
  obtain ⟨P, hPord, hPdeg⟩ := HasPrincipalDivisors.exists_divisor (K := K) f hf0
  have heff : ∀ v : Place K F, 0 ≤ (P + D) v := by
    intro v
    rw [Finsupp.add_apply, hPord]
    rcases mem_lSpace_iff_ord.mp hf with rfl | h
    · exact absurd rfl hf0
    · linarith [h v]
  have hdegPD : 0 ≤ Divisor.degree (P + D) := Divisor.degree_nonneg_of_nonneg heff
  rw [map_add, hPdeg, zero_add] at hdegPD
  exact absurd hdegPD (not_le.mpr hD)
theorem ell_eq_zero_of_degree_neg [IsCurveOver K F] (hD : Divisor.degree D < 0) :
    ell D = 0 := by
  rw [ell, lSpace_eq_bot_of_degree_neg_port hD, finrank_bot]
end AlgebraicCurve

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_lSpace_eq_bot_of_degree_neg.AlgebraicCurve in
theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] {D : Divisor K F} [IsCurveOver K F]
    (hD : Divisor.degree D < 0) : LSpace D = ⊥ :=
  AlgebraicCurve.lSpace_eq_bot_of_degree_neg_port (K := K) (F := F) (D := D) (hD := hD)

end S_AlgebraicCurve_lSpace_eq_bot_of_degree_neg
end P2MW
export P2MW.S_AlgebraicCurve_lSpace_eq_bot_of_degree_neg (solution)

end privateSection

public section publicSection


namespace AlgebraicCurve
theorem lSpace_eq_bot_of_degree_neg {K F : Type*} [Field K] [Field F] [Algebra K F] {D : Divisor K F} [IsCurveOver K F]
    (hD : Divisor.degree D < 0) : LSpace D = ⊥ := _root_.P2MW.S_AlgebraicCurve_lSpace_eq_bot_of_degree_neg.solution hD
end AlgebraicCurve

end publicSection
