/-
Based on Prove2Me node ModularCurve.exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange
(f75c7e66-2f67-5579-a0cf-8fd32f6b5493) by Claude (2026-09-05).

Proof based on Prove2Me submission 9e204ab1-42d0-5306-a73d-987999a5db75
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X1

import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_comap_algebraMap_eq_of_constantFieldExtension
import Theorems.FLT.Thm_AlgebraicCurve_isCurveOver_of_transcendental_of_perfectField
import Theorems.FLT.Thm_ModularCurve_JOneES_exists_transcendental_finiteDimensional_laurentBaseChange
import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_toValuationSubring_eq_comap_ringHom
import Definitions.FLT.Def_P2M_Util

/-!
# Places descend along constant field extension of q-expansion fields

Theorem statement: `ModularCurve.exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange`
(`f75c7e66-2f67-5579-a0cf-8fd32f6b5493`), by Claude, 2026-09-05.

Proof: submission `9e204ab1-42d0-5306-a73d-987999a5db75`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be an algebraically closed field equipped with a $\mathbb{Q}$-algebra structure, let $\Gamma
\le \mathrm{SL}_2(\mathbb{Z})$ be a subgroup of finite index containing $T =
\begin{pmatrix}1&1\\0&1\end{pmatrix}$, and let $F(\Gamma) =$ `qExpFunctionFieldC ℚ Γ` be the
subfield of $\mathbb{Q}((q))$ generated over $\mathbb{Q}$ by the quotients $\mathrm{intSeriesC}\,p_f
/ \mathrm{intSeriesC}\,p_g$, where $f,g$ are modular forms of some weight $k$ for $\Gamma$ (viewed
inside $\mathrm{GL}_2(\mathbb{R})$) with integral $q$-expansions $p_f, p_g \in \mathbb{Z}[[q]]$ and
$\mathrm{intSeriesC}\,p_g \ne 0$. For a field $L$ over $\mathbb{Q}$ write $L\cdot F(\Gamma)$ for
`laurentBaseChange L (qExpFunctionFieldC ℚ Γ)`, the subfield of $L((q))$ generated over $L$ by the
image of $F(\Gamma)$ under coefficientwise application of $\mathbb{Q} \to L$. Let $\tau \colon
\overline{\mathbb{Q}} \to K$ be a $\mathbb{Q}$-algebra embedding and let $\Psi \colon
\overline{\mathbb{Q}}\cdot F(\Gamma) \to K\cdot F(\Gamma)$ be a ring homomorphism which, on
underlying Laurent series, acts by applying $\tau$ to each coefficient. Let $P$ be a place of
$K\cdot F(\Gamma)$ over $K$ — that is, a valuation subring of $K\cdot F(\Gamma)$ containing the
image of $K$, distinct from the whole field and a principal ideal ring — and suppose
$\mathrm{ord}_P(\Psi f) \ne 0$ for at least one $f$, where $\mathrm{ord}$ denotes the negative
logarithm of the associated height-one adic valuation. Then there exists a place $P_0$ of
$\overline{\mathbb{Q}}\cdot F(\Gamma)$ over $\overline{\mathbb{Q}}$ with $\mathrm{ord}_P(\Psi f) =
\mathrm{ord}_{P_0}(f)$ for every $f \in \overline{\mathbb{Q}}\cdot F(\Gamma)$.

This is the invariance of orders under a constant field extension of a one-variable function field
with algebraically closed constant field, in the form needed for the function fields of modular
curves: a nontrivial place upstairs restricts along the coefficientwise embedding to a place
downstairs with identical order function, no ramification occurring. It is used in the computations
of orders of functions at places of the base-changed $q$-expansion fields for $\Gamma_0(N)$ and
$\Gamma_1(N)$, and in the counting of places by double cosets.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange
p2m_attr_erase "instance" "AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero"
p2m_attr_erase "simp" "ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeInfty_toValuationSubring AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none AlgebraicCurve.Divisor.evalFun_zero AlgebraicCurve.Place.evalAt_one"

noncomputable section

p2m_open "AlgebraicCurve ModularCurve P2MW.S_ModularCurve_exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange.ModularCurve"
open scoped MatrixGroups

namespace ModularCurve
p2m_export "ModularCurve" "qExpFunctionFieldC coeffMap coeffMap_single coeffMap_coeffMap coeffMap_congr algebraMap_laurentSeries_eq_single coeffEmb laurentBaseChange coeffEmb_mem_laurentBaseChange mem_laurentBaseChange_iff JOneES.exists_transcendental_finiteDimensional_laurentBaseChange"
namespace T1Aux
p2m_open "ModularCurve"

section CoeffLift

variable {L : Type*} [Field L] {Ω : Type*} [Field Ω] [Algebra ℚ L] [Algebra ℚ Ω] (τ : L →ₐ[ℚ] Ω)
  (F₀ : IntermediateField ℚ (LaurentSeries ℚ))

theorem coeffMap_coeffEmb' (x : LaurentSeries ℚ) : coeffMap τ.toRingHom (coeffEmb L x) = coeffEmb Ω x := by
  change coeffMap _ (coeffMap _ x) = coeffMap _ x
  rw [coeffMap_coeffMap]
  exact coeffMap_congr (RingHom.ext_rat _ _) x

theorem coeffMap_algebraMap' (c : L) :
    coeffMap τ.toRingHom (algebraMap L (LaurentSeries L) c) = algebraMap Ω (LaurentSeries Ω) (τ c) := by
  rw [algebraMap_laurentSeries_eq_single, algebraMap_laurentSeries_eq_single, coeffMap_single]
  rfl

theorem coeffMap_mem_laurentBaseChange' {x : LaurentSeries L} (hx : x ∈ laurentBaseChange L F₀) :
    coeffMap τ.toRingHom x ∈ laurentBaseChange Ω F₀ := by
  rw [mem_laurentBaseChange_iff] at hx
  induction hx using Subfield.closure_induction with
  | mem y hy =>
      rcases hy with ⟨a, rfl⟩ | ⟨z, hz, rfl⟩
      · rw [coeffMap_algebraMap']
        exact (laurentBaseChange Ω F₀).algebraMap_mem _
      · rw [coeffMap_coeffEmb']
        exact coeffEmb_mem_laurentBaseChange Ω hz
  | one => simp
  | add _ _ _ _ hx hy => simpa using add_mem hx hy
  | neg _ _ hx => simpa using neg_mem hx
  | inv _ _ hx => simpa using inv_mem hx
  | mul _ _ _ _ hx hy => simpa using mul_mem hx hy

@[reducible] def algebraOfLift : Algebra L ↥(laurentBaseChange Ω F₀) :=
  ((algebraMap Ω ↥(laurentBaseChange Ω F₀)).comp τ.toRingHom).toAlgebra

def liftRingHom : ↥(laurentBaseChange L F₀) →+* ↥(laurentBaseChange Ω F₀) :=
  ((coeffMap τ.toRingHom).comp (laurentBaseChange L F₀).toSubring.subtype).codRestrict
    (laurentBaseChange Ω F₀).toSubring (fun x => coeffMap_mem_laurentBaseChange' τ F₀ x.2)

theorem coe_liftRingHom (x : ↥(laurentBaseChange L F₀)) :
    ((liftRingHom τ F₀ x : ↥(laurentBaseChange Ω F₀)) : LaurentSeries Ω) = coeffMap τ.toRingHom x :=
  rfl

def liftHom : letI := algebraOfLift τ F₀; ↥(laurentBaseChange L F₀) →ₐ[L] ↥(laurentBaseChange Ω F₀) :=
  letI := algebraOfLift τ F₀
  { liftRingHom τ F₀ with
    commutes' := fun c => Subtype.ext (by
      change coeffMap τ.toRingHom (algebraMap L (LaurentSeries L) c) = algebraMap Ω (LaurentSeries Ω) (τ c)
      exact coeffMap_algebraMap' τ c) }

theorem coe_liftHom (x : ↥(laurentBaseChange L F₀)) :
    letI := algebraOfLift τ F₀; ((liftHom τ F₀ x : ↥(laurentBaseChange Ω F₀)) : LaurentSeries Ω) = coeffMap τ.toRingHom x :=
  rfl

theorem liftHom_toRingHom : letI := algebraOfLift τ F₀; (liftHom τ F₀).toRingHom = liftRingHom τ F₀ := rfl

set_option synthInstance.maxHeartbeats 1600000 in

theorem adjoin_range_liftRingHom_eq_top :
    IntermediateField.adjoin Ω (Set.range (liftRingHom τ F₀)) = ⊤ := by
  rw [eq_top_iff]
  intro z _
  let T : IntermediateField Ω ↥(laurentBaseChange Ω F₀) := IntermediateField.adjoin Ω (Set.range (liftRingHom τ F₀))
  let T' : Subfield (LaurentSeries Ω) := T.toSubfield.map (laurentBaseChange Ω F₀).val.toRingHom
  have hgens : Set.range (algebraMap Ω (LaurentSeries Ω)) ∪ (⇑(coeffEmb Ω) '' (F₀ : Set (LaurentSeries ℚ))) ⊆ T' := by
    rintro w (⟨a, rfl⟩ | ⟨x, hx, rfl⟩)
    · exact ⟨algebraMap Ω ↥(laurentBaseChange Ω F₀) a, T.algebraMap_mem a, rfl⟩
    · refine ⟨liftRingHom τ F₀ ⟨coeffEmb L x, coeffEmb_mem_laurentBaseChange L hx⟩,
        IntermediateField.subset_adjoin Ω _ ⟨_, rfl⟩, ?_⟩
      change coeffMap τ.toRingHom (coeffEmb L x) = coeffEmb Ω x
      exact coeffMap_coeffEmb' τ x
  have hle : Subfield.closure (Set.range (algebraMap Ω (LaurentSeries Ω)) ∪
      (⇑(coeffEmb Ω) '' (F₀ : Set (LaurentSeries ℚ)))) ≤ T' := Subfield.closure_le.mpr hgens
  obtain ⟨w, hw, hwz⟩ := hle (mem_laurentBaseChange_iff.mp z.2)
  have : w = z := Subtype.ext hwz
  rw [← this]
  exact hw

end CoeffLift

end ModularCurve.T1Aux

set_option synthInstance.maxHeartbeats 1600000 in
set_option maxHeartbeats 6400000 in
open ModularCurve.T1Aux in
theorem solution
    (K : Type*) [Field K] [Algebra ℚ K] [IsAlgClosed K]
    (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ)) (hT : ModularGroup.T ∈ Γ) [Γ.FiniteIndex]
    (τ : AlgebraicClosure ℚ →ₐ[ℚ] K)
    (Ψ : ↥(ModularCurve.laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) →+*
           ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)))
    (hΨ : ∀ f, ((Ψ f : ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ))) : LaurentSeries K)
             = ModularCurve.coeffMap τ.toRingHom (f : LaurentSeries (AlgebraicClosure ℚ)))
    (P : AlgebraicCurve.Place K ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)))
    (hP : ∃ f, P.ord (Ψ f) ≠ 0) :
    ∃ P₀ : AlgebraicCurve.Place (AlgebraicClosure ℚ)
        ↥(ModularCurve.laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)),
      ∀ f, P.ord (Ψ f) = P₀.ord f := by
  classical
  have hΨeq : Ψ = liftRingHom τ (ModularCurve.qExpFunctionFieldC ℚ Γ) := by
    refine RingHom.ext fun f => Subtype.ext ?_
    rw [hΨ, coe_liftRingHom]
  let algQK : Algebra (AlgebraicClosure ℚ) K := τ.toRingHom.toAlgebra
  let algQF : Algebra (AlgebraicClosure ℚ) ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)) := algebraOfLift τ (ModularCurve.qExpFunctionFieldC ℚ Γ)
  have : IsScalarTower (AlgebraicClosure ℚ) K ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)) := IsScalarTower.of_algebraMap_eq fun _ => rfl
  let algFF : Algebra ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)) := Ψ.toAlgebra
  have : IsScalarTower (AlgebraicClosure ℚ) ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)) := by
    refine IsScalarTower.of_algebraMap_eq fun c => ?_
    show _ = Ψ (algebraMap (AlgebraicClosure ℚ) ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) c)
    rw [hΨeq]
    exact ((liftHom τ (ModularCurve.qExpFunctionFieldC ℚ Γ)).commutes c).symm
  obtain ⟨x₀, hx₀tr, hx₀fd⟩ :=
    ModularCurve.JOneES.exists_transcendental_finiteDimensional_laurentBaseChange (AlgebraicClosure ℚ) Γ hT
  have := hx₀fd
  have : IsCurveOver (AlgebraicClosure ℚ) ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) :=
    isCurveOver_of_transcendental_of_perfectField hx₀tr hx₀fd
  obtain ⟨x₁, hx₁tr, hx₁fd⟩ := ModularCurve.JOneES.exists_transcendental_finiteDimensional_laurentBaseChange K Γ hT
  have hgen : IntermediateField.adjoin K (Set.range (algebraMap ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)))) = ⊤ := by
    show IntermediateField.adjoin K (Set.range Ψ) = ⊤
    rw [hΨeq]
    exact adjoin_range_liftRingHom_eq_top τ (ModularCurve.qExpFunctionFieldC ℚ Γ)
  have hwK : ∀ a : AlgebraicClosure ℚ, Ψ (algebraMap (AlgebraicClosure ℚ) ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) a) ∈ P.toValuationSubring := by
    intro a
    have : Ψ (algebraMap (AlgebraicClosure ℚ) ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) a) = algebraMap K ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)) (τ a) := by
      rw [hΨeq]
      exact (liftHom τ (ModularCurve.qExpFunctionFieldC ℚ Γ)).commutes a
    rw [this]
    exact P.algebraMap_mem' (τ a)
  have hwx : ∃ y : ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)), Ψ y ∉ P.toValuationSubring := by
    obtain ⟨f, hf⟩ := hP
    by_contra hall
    push Not at hall
    apply hf
    have hf0 : Ψ f ≠ 0 := by
      intro h0; apply hf; rw [h0, Place.ord_zero]
    have h1 : Ψ f ∈ P.toValuationSubring := hall f
    have h2 : (Ψ f)⁻¹ ∈ P.toValuationSubring := by rw [← map_inv₀]; exact hall f⁻¹
    let u : (↥P.toValuationSubring)ˣ :=
      ⟨⟨Ψ f, h1⟩, ⟨(Ψ f)⁻¹, h2⟩, Subtype.ext (mul_inv_cancel₀ hf0), Subtype.ext (inv_mul_cancel₀ hf0)⟩
    exact P.ord_coe_unit u
  obtain ⟨P₀, hP₀⟩ := Place.exists_toValuationSubring_eq_comap_ringHom (K := AlgebraicClosure ℚ) x₀ Ψ
    P.toValuationSubring hwK hwx
  obtain ⟨P', -, hP'ord, huniq⟩ := Place.exists_comap_algebraMap_eq_of_constantFieldExtension
    (AlgebraicClosure ℚ) ↥(laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) K ↥(laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ))
    ⟨x₀, hx₀tr, hx₀fd⟩ ⟨x₁, hx₁tr, hx₁fd⟩ hgen P₀
  have hPP' : P = P' := huniq P (by rw [hP₀]; rfl)
  refine ⟨P₀, fun f => ?_⟩
  rw [hPP']
  exact hP'ord f

end

end S_ModularCurve_exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange
end P2MW
export P2MW.S_ModularCurve_exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

theorem ModularCurve.exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange
    (K : Type*) [Field K] [Algebra ℚ K] [IsAlgClosed K]
    (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ)) (hT : ModularGroup.T ∈ Γ) [Γ.FiniteIndex]
    (τ : AlgebraicClosure ℚ →ₐ[ℚ] K)
    (Ψ : ↥(ModularCurve.laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)) →+*
           ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)))
    (hΨ : ∀ f, ((Ψ f : ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ))) : LaurentSeries K)
             = ModularCurve.coeffMap τ.toRingHom (f : LaurentSeries (AlgebraicClosure ℚ)))
    (P : AlgebraicCurve.Place K ↥(ModularCurve.laurentBaseChange K (ModularCurve.qExpFunctionFieldC ℚ Γ)))
    (hP : ∃ f, P.ord (Ψ f) ≠ 0) :
    ∃ P₀ : AlgebraicCurve.Place (AlgebraicClosure ℚ)
        ↥(ModularCurve.laurentBaseChange (AlgebraicClosure ℚ) (ModularCurve.qExpFunctionFieldC ℚ Γ)),
      ∀ f, P.ord (Ψ f) = P₀.ord f := _root_.P2MW.S_ModularCurve_exists_place_algebraicClosure_ord_comp_eq_of_laurentBaseChange.solution K Γ hT τ Ψ hΨ P hP

end publicSection
