/-
Based on Prove2Me node P2M.Dup.WeierstrassCurve.Affine.CoordinateRing.XYIdeal_isMaximal
(c34f4f9a-415c-5aea-a792-c8eee66b2c96) by Claude (2026-09-05).

Proof based on Prove2Me submission 4b288ac9-834e-5672-aed2-e935a73ab4a9
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point

import Definitions.FLT.Def_P2M_Util

/-!
# Maximality of the point ideal at an affine point

Theorem statement: `P2M.Dup.WeierstrassCurve.Affine.CoordinateRing.XYIdeal_isMaximal`
(`c34f4f9a-415c-5aea-a792-c8eee66b2c96`), by Claude, 2026-09-05.

Proof: submission `4b288ac9-834e-5672-aed2-e935a73ab4a9`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, let $W$ be a Weierstrass curve in affine form over $K$, and let $a, b \in K$ be
such that $(a,b)$ satisfies the affine Weierstrass equation of $W$, i.e. $W.\mathrm{Equation}\ a\ b$
holds: $b^2 + a_1ab + a_3b - (a^3 + a_2a^2 + a_4a + a_6) = 0$. The assertion is that the ideal
$\mathtt{XYIdeal}\ W\ a\ (C\,b)$ of the affine coordinate ring $K[W] = K[X][Y]/(W)$ of $W$ — the
ideal generated by the images of $X - a$ and of the constant polynomial $Y - b$ under the quotient
map, that is, the ideal of functions vanishing at the point $(a,b)$ — is a maximal ideal. The second
coordinate of `XYIdeal` is allowed to be an arbitrary element of $K[X]$ in general; here it is
specialised to the constant $C\,b$, so that the ideal really is the point ideal of the rational
point $(a,b)$.

This is the standard fact that the ideal $\mathfrak m_{(a,b)} = (X-a, Y-b)$ of functions vanishing
at a rational affine point of a Weierstrass curve is maximal, with residue field $K$. It serves the
treatment of places of the function field of a Weierstrass curve and of divisors supported at
rational points, and is used downstream in the analytic and function-field parts of the development.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_CoordinateRing_XYIdeal_isMaximal.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_CoordinateRing_XYIdeal_isMaximal

open Polynomial WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.CoordinateRing
open scoped Polynomial.Bivariate

theorem solution {K : Type*} [Field K] {W : Affine K} {a b : K} (h : W.Equation a b) : (XYIdeal W a (C b)).IsMaximal :=
  Ideal.Quotient.maximal_of_isField _ <|
    MulEquiv.isField (Field.toIsField K) (quotientXYIdealEquiv (W' := W) h).toMulEquiv

end S_WeierstrassCurve_Affine_CoordinateRing_XYIdeal_isMaximal
end P2MW
export P2MW.S_WeierstrassCurve_Affine_CoordinateRing_XYIdeal_isMaximal (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open Polynomial WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.CoordinateRing
open scoped Polynomial.Bivariate
theorem P2M.Dup.WeierstrassCurve.Affine.CoordinateRing.XYIdeal_isMaximal {K : Type*} [Field K] {W : Affine K} {a b : K} (h : W.Equation a b) : (XYIdeal W a (C b)).IsMaximal := _root_.P2MW.S_WeierstrassCurve_Affine_CoordinateRing_XYIdeal_isMaximal.solution h

end publicSection
