/-
Based on Prove2Me node TateModule.exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv
(64daf8fe-6f13-5b0e-94db-45282c874d70) by Claude (2026-09-05).

Proof based on Prove2Me submission 66603ac4-11de-59a7-8c10-7ec507634ff6
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup
public import Definitions.FLT.Def_ModularCurve_JZeroTateModule
public import Definitions.FLT.Def_P2M_Util

import Theorems.FLT.Thm_TateModule_exists_linearMap_apply_eq_of_addMonoidHom

/-!
# Functoriality of the rational Tate module under a group isomorphism

Theorem statement:
`TateModule.exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv`
(`64daf8fe-6f13-5b0e-94db-45282c874d70`), by Claude, 2026-09-05.

Proof: submission `66603ac4-11de-59a7-8c10-7ec507634ff6`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $p$ be a prime, let $J$ and $J'$ be abelian groups and let $\Psi : J \simeq J'$ be an
isomorphism of additive groups; let $G$ and $G'$ be monoids acting distributively on $J$ and on $J'$
respectively. Here $T_p J$ denotes the subgroup [`TateModule p
J`](def/EllipticCurve_TateModule.html#L15) of sequences $x : \mathbb{N} \to J$ satisfying $p^n \cdot
x_n = 0$ and $p \cdot x_{n+1} = x_n$ for all $n$, with $\mathbb{Z}_p$-module structure, `proj p J n`
the evaluation $x \mapsto x_n$, and `RationalTateModule p J` the base change $\mathbb{Q}_p
\otimes_{\mathbb{Z}_p} T_p J$; `rationalGaloisRep p J G` is the monoid homomorphism sending $g \in
G$ to the $\mathbb{Q}_p$-linear endomorphism obtained by base change from the levelwise action $x
\mapsto (g \cdot x_n)_n$ of $g$ on $T_p J$. The assertion is that there exists a
$\mathbb{Q}_p$-linear isomorphism $\Theta : \mathbb{Q}_p \otimes_{\mathbb{Z}_p} T_p J \to
\mathbb{Q}_p \otimes_{\mathbb{Z}_p} T_p J'$ such that, first, for every $x \in T_p J$ there is $y
\in T_p J'$ with $\Theta(1 \otimes x) = 1 \otimes y$ and $y_n = \Psi(x_n)$ for all $n$; and second,
for all $g \in G$ and $g' \in G'$ with $\Psi(g \cdot z) = g' \cdot \Psi(z)$ for all $z \in J$, the
underlying linear maps satisfy $\Theta \circ \mathrm{rationalGaloisRep}(g) =
\mathrm{rationalGaloisRep}(g') \circ \Theta$.

This is the functoriality of the rational Tate module $V_p = \mathbb{Q}_p \otimes_{\mathbb{Z}_p}
T_p$ for an isomorphism of the underlying abelian groups, together with the statement that the
induced isomorphism intertwines operators corresponding under $\Psi$; the pinning on pure tensors
identifies $\Theta$ as the map induced levelwise by $\Psi$. It is used to transport representations
on Tate modules of Jacobians along an isomorphism of the groups carrying them, for instance in
[`DrinfeldCurve.exists_linearEquiv_tateProd_comp_tateProdRep_eq_of_algEquiv`](thm.html#DrinfeldCurve.exists_linearEquiv_tateProd_comp_tateProdRep_eq_of_algEquiv).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_TateModule_exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

namespace P2MW.S_TateModule_exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv

set_option autoImplicit false

open scoped TensorProduct

theorem solution
    (p : ℕ) [Fact p.Prime] {J J' : Type} [AddCommGroup J] [AddCommGroup J'] (Ψ : J ≃+ J')
    (G G' : Type) [Monoid G] [Monoid G'] [DistribMulAction G J] [DistribMulAction G' J'] :
    ∃ Θ : ModularCurve.RationalTateModule p J ≃ₗ[ℚ_[p]] ModularCurve.RationalTateModule p J',
      (∀ x : TateModule p J, ∃ y : TateModule p J',
        Θ ((1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] x) = (1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] y ∧
          ∀ n : ℕ, TateModule.proj p J' n y = Ψ (TateModule.proj p J n x)) ∧
      ∀ (g : G) (g' : G'), (∀ x : J, Ψ (g • x) = g' • Ψ x) →
        (Θ : ModularCurve.RationalTateModule p J →ₗ[ℚ_[p]] ModularCurve.RationalTateModule p J') ∘ₗ
            ModularCurve.rationalGaloisRep p J G g =
          ModularCurve.rationalGaloisRep p J' G' g' ∘ₗ
            (Θ : ModularCurve.RationalTateModule p J →ₗ[ℚ_[p]] ModularCurve.RationalTateModule p J') := by
  classical
  obtain ⟨P, hP, -⟩ := TateModule.exists_linearMap_apply_eq_of_addMonoidHom p (Ψ : J →+ J')
  obtain ⟨Q, hQ, -⟩ := TateModule.exists_linearMap_apply_eq_of_addMonoidHom p (Ψ.symm : J' →+ J)
  have hQP : Q ∘ₗ P = LinearMap.id := by
    apply LinearMap.ext; intro x; apply Subtype.ext; funext n
    rw [LinearMap.comp_apply, hQ, hP, LinearMap.id_apply]
    exact Ψ.symm_apply_apply _
  have hPQ : P ∘ₗ Q = LinearMap.id := by
    apply LinearMap.ext; intro y; apply Subtype.ext; funext n
    rw [LinearMap.comp_apply, hP, hQ, LinearMap.id_apply]
    exact Ψ.apply_symm_apply _

  set P' := P.baseChange ℚ_[p] with hP'
  set Q' := Q.baseChange ℚ_[p] with hQ'
  have hQP' : Q' ∘ₗ P' = LinearMap.id := by
    rw [hP', hQ', ← LinearMap.baseChange_comp, hQP, LinearMap.baseChange_id]
  have hPQ' : P' ∘ₗ Q' = LinearMap.id := by
    rw [hP', hQ', ← LinearMap.baseChange_comp, hPQ, LinearMap.baseChange_id]
  refine ⟨LinearEquiv.ofLinearMap P' Q' hPQ' hQP', fun x => ⟨P x, ?_, fun n => ?_⟩, fun g g' hgg' => ?_⟩
  · show P' ((1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] x) = (1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] P x
    rw [hP', LinearMap.baseChange_tmul]
  · show ((P x : TateModule p J') : ℕ → J') n = Ψ ((x : ℕ → J) n)
    exact hP x n

  have hnat : P ∘ₗ TateModule.rep p J G g = TateModule.rep p J' G' g' ∘ₗ P := by
    apply LinearMap.ext; intro x; apply Subtype.ext; funext n
    rw [LinearMap.comp_apply, LinearMap.comp_apply, hP, TateModule.rep_apply, TateModule.rep_apply, hP]
    exact hgg' _
  show P' ∘ₗ ModularCurve.rationalGaloisRep p J G g = ModularCurve.rationalGaloisRep p J' G' g' ∘ₗ P'
  rw [ModularCurve.rationalGaloisRep_apply, ModularCurve.rationalGaloisRep_apply, hP', ← LinearMap.baseChange_comp,
    ← LinearMap.baseChange_comp, hnat]
end S_TateModule_exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv
end P2MW

end privateSection

public section publicSection

set_option autoImplicit false

open AlgebraicCurve

open scoped TensorProduct

theorem TateModule.exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv
    (p : ℕ) [Fact p.Prime] {J J' : Type} [AddCommGroup J] [AddCommGroup J'] (Ψ : J ≃+ J')
    (G G' : Type) [Monoid G] [Monoid G'] [DistribMulAction G J] [DistribMulAction G' J'] :
    ∃ Θ : ModularCurve.RationalTateModule p J ≃ₗ[ℚ_[p]] ModularCurve.RationalTateModule p J',
      (∀ x : TateModule p J, ∃ y : TateModule p J',
        Θ ((1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] x) = (1 : ℚ_[p]) ⊗ₜ[ℤ_[p]] y ∧
          ∀ n : ℕ, TateModule.proj p J' n y = Ψ (TateModule.proj p J n x)) ∧
      ∀ (g : G) (g' : G'), (∀ x : J, Ψ (g • x) = g' • Ψ x) →
        (Θ : ModularCurve.RationalTateModule p J →ₗ[ℚ_[p]] ModularCurve.RationalTateModule p J') ∘ₗ
            ModularCurve.rationalGaloisRep p J G g =
          ModularCurve.rationalGaloisRep p J' G' g' ∘ₗ
            (Θ : ModularCurve.RationalTateModule p J →ₗ[ℚ_[p]] ModularCurve.RationalTateModule p J') := _root_.P2MW.S_TateModule_exists_linearEquiv_rationalTateModule_comp_rationalGaloisRep_eq_of_addEquiv.solution p Ψ G G'

end publicSection
