/-
Based on Prove2Me node ModularCurve.exists_phiIrreducible_of_finrank_eq
(e71af2d3-396a-597b-a0df-2a757b4696b3) by Claude (2026-09-05).

Proof based on Prove2Me submission 8828da09-8db7-553d-af8e-5ef441f6d129
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0
public import Definitions.FLT.Def_ModularCurve_PhiGen
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic

import Theorems.FLT.Thm_ModularCurve_exists_monic_evalAtJ_jqN_eq_zero
import Theorems.FLT.Thm_ModularCurve_PhiGen_evalAtJ_injective
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.RingTheory.Localization.Integral
import Definitions.FLT.Def_P2M_Util

/-!
# Irreducible modular polynomial datum from degree ψ(N)

Theorem statement: `ModularCurve.exists_phiIrreducible_of_finrank_eq`
(`e71af2d3-396a-597b-a0df-2a757b4696b3`), by Claude, 2026-09-05.

Proof: submission `8828da09-8db7-553d-af8e-5ef441f6d129`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number, nonzero as a typeclass hypothesis. Inside the field of Laurent series
$\mathrm{LaurentSeries}\,\mathbb{Q}$ (Hahn series over $\mathbb{Q}$ with integer exponents) consider
the element `jq` $= q^{-1}\cdot j_{\mathrm{num}}$, the product of the Hahn monomial $q^{-1}$ with
the image over $\mathbb{Q}$ of the integral power series `jNum`, and its $N$-th substitution `jqN
N`, the image of `jq` under the ring homomorphism `qExpand` induced by $q \mapsto q^{N}$ (embedding
of exponents along multiplication by $N$ on $\mathbb{Z}$). The hypothesis is that the intermediate
field $\mathbb{Q}(jq)(jqN\,N)$, generated over the subfield $\mathbb{Q}(jq)$ by `jqN N`, has finite
rank exactly `dedekindPsi N` $=\sum_{d\mid N,\ d\ \text{squarefree}} N/d$ as a module over
$\mathbb{Q}(jq)$. The conclusion asserts the existence of a `ModularPolynomialData N`, that is a
polynomial $\Phi \in \mathbb{Z}[X][Y]$ which is monic in $Y$, has $Y$-degree equal to `dedekindPsi
N`, and satisfies $\Phi = 0$ after substituting `jqN N` for $Y$ and applying to the coefficients the
ring homomorphism `evalAtJ : ℤ[X] → LaurentSeries ℚ` sending $X$ to `jq`, together with the property
`PhiIrreducible`: the polynomial obtained from $\Phi$ by mapping its coefficients along `evalAtJGen`
into $\mathbb{Q}(jq)$ is irreducible in $\mathbb{Q}(jq)[Y]$.

This is the existence of the classical modular equation of level $N$: an irreducible modular
polynomial $\Phi_N$ with integral coefficients, monic and of degree $\psi(N)$ in the second
variable, vanishing at $(j(q), j(q^N))$ — obtained here from the degree equality
$[\mathbb{Q}(j)(j(q^N)):\mathbb{Q}(j)] = \psi(N)$, which is established separately level by level.
It feeds the unconditional existence statement
[`ModularCurve.exists_phiIrreducible`](thm.html#ModularCurve.exists_phiIrreducible), the computation
[`ModularCurve.finrank_adjoin_jqN_eq_dedekindPsi`](thm.html#ModularCurve.finrank_adjoin_jqN_eq_dedekindPsi),
and the generation of the function field of $X_0(N)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_phiIrreducible_of_finrank_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_phiIrreducible_of_finrank_eq
p2m_attr_erase "simp" "ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

noncomputable section

namespace ModularCurve
p2m_export "ModularCurve" "jq jqN dedekindPsi evalAtJ ModularPolynomialData evalAtJGen algebraMap_comp_evalAtJGen PhiIrreducible exists_monic_evalAtJ_jqN_eq_zero PhiGen.evalAtJ_injective"
namespace W1
p2m_open "ModularCurve"

open Polynomial IntermediateField

theorem coe_evalAtJGen (g : Polynomial ℤ) :
    ((evalAtJGen g : ℚ⟮jq⟯) : LaurentSeries ℚ) = evalAtJ g :=
  RingHom.congr_fun algebraMap_comp_evalAtJGen g

theorem aeval_map_intCast (g : Polynomial ℤ) :
    Polynomial.aeval jq (g.map (algebraMap ℤ ℚ)) = evalAtJ g := by
  rw [Polynomial.aeval_def, Polynomial.eval₂_map]
  congr 1
  exact RingHom.ext_int _ _

theorem evalAtJ_C (b : ℤ) : evalAtJ (Polynomial.C b) = (b : LaurentSeries ℚ) := by
  simp [evalAtJ]

theorem evalAtJGen_injective : Function.Injective evalAtJGen := by
  have h : Function.Injective ((algebraMap ℚ⟮jq⟯ (LaurentSeries ℚ)) ∘ evalAtJGen) := by
    rw [← RingHom.coe_comp, algebraMap_comp_evalAtJGen]
    exact ModularCurve.PhiGen.evalAtJ_injective
  exact h.of_comp

end ModularCurve.W1

open IntermediateField Polynomial

namespace ModularCurve
p2m_export "ModularCurve" "jq jqN dedekindPsi evalAtJ ModularPolynomialData evalAtJGen algebraMap_comp_evalAtJGen PhiIrreducible exists_monic_evalAtJ_jqN_eq_zero PhiGen.evalAtJ_injective"
end ModularCurve
p2m_open_scoped "ModularCurve" in

private theorem ModularCurve.exists_phiIrreducible_of_finrank_eq (N : ℕ) [NeZero N]
    (h : Module.finrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
      (IntermediateField.adjoin (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ)))
        ({jqN N} : Set (LaurentSeries ℚ))) = dedekindPsi N) :
    ∃ data : ModularPolynomialData N, PhiIrreducible data := by
  let : Algebra (Polynomial ℤ) ℚ⟮jq⟯ := evalAtJGen.toAlgebra
  let : Algebra (Polynomial ℤ) (LaurentSeries ℚ) := evalAtJ.toAlgebra
  have tower : IsScalarTower (Polynomial ℤ) ℚ⟮jq⟯ (LaurentSeries ℚ) :=
    IsScalarTower.of_algebraMap_eq fun x =>
      (RingHom.congr_fun algebraMap_comp_evalAtJGen x).symm
  have : IsFractionRing (Polynomial ℤ) ℚ⟮jq⟯ := by
    refine { map_units := ?_, surj := ?_, exists_of_eq := ?_ }
    · rintro ⟨y, hy⟩
      rw [mem_nonZeroDivisors_iff_ne_zero] at hy
      refine isUnit_iff_ne_zero.mpr fun h0 => hy (W1.evalAtJGen_injective ?_)
      rw [map_zero]
      exact h0
    · intro z
      by_cases hz : (z : LaurentSeries ℚ) = 0
      · refine ⟨(0, 1), ?_⟩
        have hz0 : z = 0 := Subtype.ext hz
        rw [hz0]
        simp
      · obtain ⟨r, s, hrs⟩ :=
          (IntermediateField.mem_adjoin_simple_iff ℚ (z : LaurentSeries ℚ)).mp z.2
        have hs0 : Polynomial.aeval jq s ≠ 0 := by
          intro h0
          apply hz
          rw [hrs, h0, div_zero]
        have hzs : (z : LaurentSeries ℚ) * Polynomial.aeval jq s = Polynomial.aeval jq r := by
          rw [hrs, div_mul_cancel₀ _ hs0]
        obtain ⟨br, hbr, hrn⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors ℤ) r
        obtain ⟨bs, hbs, hsn⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors ℤ) s
        rw [mem_nonZeroDivisors_iff_ne_zero] at hbr hbs
        have hrval : evalAtJ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) r) =
            br • Polynomial.aeval jq r := by
          rw [← W1.aeval_map_intCast, hrn]
          exact map_zsmul _ br r
        have hsval : evalAtJ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) =
            bs • Polynomial.aeval jq s := by
          rw [← W1.aeval_map_intCast, hsn]
          exact map_zsmul _ bs s
        have hs'0 : IsLocalization.integerNormalization (nonZeroDivisors ℤ) s ≠ 0 := by
          intro h0
          have h1 : evalAtJ (IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) = 0 := by
            rw [h0, map_zero]
          rw [hsval] at h1
          have h2 : (bs : LaurentSeries ℚ) * Polynomial.aeval jq s = 0 :=
            (zsmul_eq_mul (Polynomial.aeval jq s) bs).symm.trans h1
          rcases mul_eq_zero.mp h2 with hb | hss
          · apply hbs
            have h3 : algebraMap ℚ (LaurentSeries ℚ) ((bs : ℚ)) =
                algebraMap ℚ (LaurentSeries ℚ) 0 := by
              rw [map_intCast, map_zero]
              exact hb
            have h4 : (bs : ℚ) = 0 := (algebraMap ℚ (LaurentSeries ℚ)).injective h3
            exact_mod_cast h4
          · exact hs0 hss
        have hcoe : ∀ g : Polynomial ℤ,
            ((algebraMap (Polynomial ℤ) ℚ⟮jq⟯ g : ℚ⟮jq⟯) : LaurentSeries ℚ) = evalAtJ g :=
          fun g => RingHom.congr_fun algebraMap_comp_evalAtJGen g
        have key : (z : LaurentSeries ℚ) *
            evalAtJ (Polynomial.C br * IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) =
            evalAtJ (Polynomial.C bs * IsLocalization.integerNormalization (nonZeroDivisors ℤ) r) := by
          rw [map_mul, map_mul, W1.evalAtJ_C, W1.evalAtJ_C, hrval, hsval, zsmul_eq_mul,
            zsmul_eq_mul, ← hzs]
          ring
        refine ⟨(Polynomial.C bs * IsLocalization.integerNormalization (nonZeroDivisors ℤ) r,
          ⟨Polynomial.C br * IsLocalization.integerNormalization (nonZeroDivisors ℤ) s,
            mem_nonZeroDivisors_of_ne_zero
              (mul_ne_zero (Polynomial.C_ne_zero.mpr hbr) hs'0)⟩), Subtype.ext ?_⟩
        show ((z * algebraMap (Polynomial ℤ) ℚ⟮jq⟯
            (Polynomial.C br * IsLocalization.integerNormalization (nonZeroDivisors ℤ) s) :
              ℚ⟮jq⟯) : LaurentSeries ℚ) =
          ((algebraMap (Polynomial ℤ) ℚ⟮jq⟯
            (Polynomial.C bs * IsLocalization.integerNormalization (nonZeroDivisors ℤ) r) :
              ℚ⟮jq⟯) : LaurentSeries ℚ)
        rw [MulMemClass.coe_mul, hcoe, hcoe]
        exact key
    · intro x y hxy
      exact ⟨1, by rw [W1.evalAtJGen_injective hxy]⟩
  have hx : IsIntegral (Polynomial ℤ) (jqN N) := by
    obtain ⟨P, hP, hval⟩ := ModularCurve.exists_monic_evalAtJ_jqN_eq_zero N
    exact ⟨P, hP, hval⟩
  have hxQ : IsIntegral ℚ⟮jq⟯ (jqN N) := hx.tower_top
  have hmin := minpoly.isIntegrallyClosed_eq_field_fractions' ℚ⟮jq⟯ hx
  rw [IntermediateField.adjoin.finrank hxQ] at h
  have hΦm : (minpoly (Polynomial ℤ) (jqN N)).Monic := minpoly.monic hx
  have hdeg : (minpoly (Polynomial ℤ) (jqN N)).natDegree = dedekindPsi N := by
    rw [← hΦm.natDegree_map (algebraMap (Polynomial ℤ) ℚ⟮jq⟯), ← hmin]
    exact h
  have heval : (minpoly (Polynomial ℤ) (jqN N)).eval₂ evalAtJ (jqN N) = 0 := by
    have ha := minpoly.aeval (Polynomial ℤ) (jqN N)
    rw [Polynomial.aeval_def] at ha
    exact ha
  refine ⟨⟨minpoly (Polynomial ℤ) (jqN N), hΦm, hdeg, heval⟩, ?_⟩
  show Irreducible (Polynomial.map evalAtJGen (minpoly (Polynomial ℤ) (jqN N)))
  have hmap : Polynomial.map evalAtJGen (minpoly (Polynomial ℤ) (jqN N)) =
      minpoly ℚ⟮jq⟯ (jqN N) := hmin.symm
  rw [hmap]
  exact minpoly.irreducible hxQ

end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_exists_phiIrreducible_of_finrank_eq.ModularCurve ModularCurve.PhiGen in

theorem solution (N : ℕ) [NeZero N] (h : Module.finrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ))) (IntermediateField.adjoin (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ))) ({jqN N} : Set (LaurentSeries ℚ))) = dedekindPsi N) : ∃ data : ModularPolynomialData N, PhiIrreducible data :=
  ModularCurve.exists_phiIrreducible_of_finrank_eq N h

end S_ModularCurve_exists_phiIrreducible_of_finrank_eq
end P2MW
export P2MW.S_ModularCurve_exists_phiIrreducible_of_finrank_eq (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve ModularCurve.PhiGen
theorem ModularCurve.exists_phiIrreducible_of_finrank_eq (N : ℕ) [NeZero N] (h : Module.finrank (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ))) (IntermediateField.adjoin (IntermediateField.adjoin ℚ ({jq} : Set (LaurentSeries ℚ))) ({jqN N} : Set (LaurentSeries ℚ))) = dedekindPsi N) : ∃ data : ModularPolynomialData N, PhiIrreducible data := _root_.P2MW.S_ModularCurve_exists_phiIrreducible_of_finrank_eq.solution N h

end publicSection
