/-
Based on Prove2Me node AlgebraicCurve.Place.ramificationIndex_eq_of_restrict_eq
(5fbca615-84cc-5e09-9ed6-2b9040ebc83e) by Claude (2026-09-05).

Proof based on Prove2Me submission abf14081-5d7d-557a-b02a-be931aee2080
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
public import Mathlib.FieldTheory.Galois.Basic

import Definitions.FLT.Def_AlgebraicCurve_Correspondence
import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_algEquiv_smul_eq_of_restrict_eq
import Theorems.FLT.Thm_AlgebraicCurve_SemilinearAut_ramificationIndex_smul
import Definitions.FLT.Def_P2M_Util

/-!
# Ramification index is constant on a Galois fibre

Theorem statement: `AlgebraicCurve.Place.ramificationIndex_eq_of_restrict_eq`
(`5fbca615-84cc-5e09-9ed6-2b9040ebc83e`), by Claude, 2026-09-05.

Proof: submission `abf14081-5d7d-557a-b02a-be931aee2080`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$, $F'$ and $M$ be fields with $F'$ and $M$ algebras over $K$ and $M$ an algebra over $F'$,
the three structures forming a scalar tower, and assume $M$ is finite-dimensional over $F'$ and
Galois over $F'$. Let $W$ and $W'$ be places of $M$ over $K$, that is, valuation subrings of $M$
containing the image of $K$ under the structure map, different from all of $M$, and whose underlying
ring is a principal ideal ring. Suppose $W$ and $W'$ have the same restriction to $F'$, where the
restriction of a place of $M$ is the place of $F'$ whose valuation subring is the preimage of the
given valuation subring under $\mathrm{algebraMap}\colon F' \to M$. Then the ramification indices of
$W'$ and of $W$ over $F'$ agree, the ramification index of a place $w$ of $M$ over $F'$ being the
infimum of the set of natural numbers $n$ with $0 < n$ for which there exists $f \in F'$, $f \neq
0$, with $w.\mathrm{ord}$ of the image of $f$ in $M$ equal to $n$.

This is the standard statement that in a finite Galois extension the ramification index is the same
at all places lying over a fixed place of the base field. It feeds into the fundamental identity
$\sum_{W \mid w} e\, f = [M:F']$ in the form
[`AlgebraicCurve.Place.card_fiberOver_mul_ramificationIndex_mul_inertiaDeg`](thm.html#AlgebraicCurve.Place.card_fiberOver_mul_ramificationIndex_mul_inertiaDeg),
and into the results on orders of elements under Hahn series embeddings in the Galois case.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt"
p2m_attr_erase "simp" "AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal"

noncomputable section
p2m_open "AlgebraicCurve P2MW.S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq.AlgebraicCurve IsDedekindDomain"
open scoped Pointwise

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "SemilinearAut.IntertwinesAlong Place SemilinearAut SemilinearAut.ofAlgAut SemilinearAut.ofAlgAut_smul Place.exists_algEquiv_smul_eq_of_restrict_eq SemilinearAut.ramificationIndex_smul"
p2m_open "AlgebraicCurve"
namespace Place
p2m_export "AlgebraicCurve.Place" "ramificationIndex restrict exists_algEquiv_smul_eq_of_restrict_eq"
p2m_open "AlgebraicCurve.Place"

variable {K F' M : Type*} [Field K] [Field F'] [Field M] [Algebra K F'] [Algebra K M]
  [Algebra F' M] [IsScalarTower K F' M]

private theorem intertwinesAlong_one_ofAlgAut (σ : M ≃ₐ[F'] M) :
    SemilinearAut.IntertwinesAlong (algebraMap F' M) (1 : SemilinearAut K F')
      (SemilinearAut.ofAlgAut (σ.restrictScalars K)) := by
  intro x
  rw [one_smul, SemilinearAut.ofAlgAut_smul]
  exact σ.commutes x

end Place
end AlgebraicCurve

open _root_.AlgebraicCurve.Place _root_.P2MW.S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq.AlgebraicCurve.Place in
theorem solution {K F' M : Type*} [Field K] [Field F'] [Field M]
    [Algebra K F'] [Algebra K M] [Algebra F' M] [IsScalarTower K F' M]
    [FiniteDimensional F' M] [IsGalois F' M] (W W' : Place K M)
    (h : W'.restrict F' = W.restrict F') :
    W'.ramificationIndex F' = W.ramificationIndex F' := by
  obtain ⟨σ, rfl⟩ := Place.exists_algEquiv_smul_eq_of_restrict_eq W W' h
  exact SemilinearAut.ramificationIndex_smul (intertwinesAlong_one_ofAlgAut σ) W

end

end S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq
end P2MW
export P2MW.S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Place.ramificationIndex_eq_of_restrict_eq {K F' M : Type*} [Field K] [Field F'] [Field M]
    [Algebra K F'] [Algebra K M] [Algebra F' M] [IsScalarTower K F' M]
    [FiniteDimensional F' M] [IsGalois F' M] (W W' : Place K M)
    (h : W'.restrict F' = W.restrict F') :
    W'.ramificationIndex F' = W.ramificationIndex F' := _root_.P2MW.S_AlgebraicCurve_Place_ramificationIndex_eq_of_restrict_eq.solution W W' h

end publicSection
