/-
Based on Prove2Me node AlgebraicCurve.Place.inertiaDeg_eq_of_restrict_eq
(2babbc8b-41e2-5c0f-acf6-9e3403240472) by Claude (2026-09-05).

Proof based on Prove2Me submission b56f5bef-a420-5ab3-9a1c-8a4dd8a8dd24
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
public import Mathlib.FieldTheory.Galois.Basic

import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_algEquiv_smul_eq_of_restrict_eq
import Theorems.FLT.Thm_AlgebraicCurve_SemilinearAut_inertiaDeg_smul
import Definitions.FLT.Def_P2M_Util

/-!
# Inertia degree is constant on a Galois fibre

Theorem statement: `AlgebraicCurve.Place.inertiaDeg_eq_of_restrict_eq`
(`2babbc8b-41e2-5c0f-acf6-9e3403240472`), by Claude, 2026-09-05.

Proof: submission `b56f5bef-a420-5ab3-9a1c-8a4dd8a8dd24`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$, $F'$ and $M$ be fields with $F'$ and $M$ algebras over $K$ and $M$ an algebra over $F'$,
the three structures forming a scalar tower, and assume $M$ is finite-dimensional over $F'$ and
$M/F'$ is Galois. Let $W$ and $W'$ be places of $M$ over $K$, that is, valuation subrings of $M$
that contain the image of $K$ under the structure map, are distinct from $M$ itself, and are
principal ideal rings. The hypothesis is that $W$ and $W'$ have the same restriction to $F'$: the
preimages of their valuation subrings under $\mathrm{algebraMap}\,F'\,M$, regarded as places of $F'$
over $K$, coincide. The conclusion is the equality of the two inertia degrees over $F'$, where the
inertia degree of a place $w$ of $M$ over $F'$ is the dimension of the residue field of the local
ring $w$ as a vector space over the residue field of the restricted place $w|_{F'}$; thus
$f(W'|_{F'}) = f(W|_{F'})$ as natural numbers.

This is the classical constancy of the residue (inertia) degree among the places of $M$ lying over a
fixed place of $F'$ when $M/F'$ is finite Galois. It feeds the fundamental identity relating the
number of places in a fibre, the ramification indices and the inertia degrees, used in
[`AlgebraicCurve.Place.card_fiberOver_mul_ramificationIndex_mul_inertiaDeg`](thm.html#AlgebraicCurve.Place.card_fiberOver_mul_ramificationIndex_mul_inertiaDeg)
and in the two summation formulas over bifibres.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt"
p2m_attr_erase "simp" "AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal"

noncomputable section
p2m_open "AlgebraicCurve P2MW.S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq.AlgebraicCurve IsDedekindDomain"
open scoped Pointwise

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "SemilinearAut.IntertwinesAlong Place SemilinearAut SemilinearAut.ofAlgAut SemilinearAut.ofAlgAut_smul Place.exists_algEquiv_smul_eq_of_restrict_eq SemilinearAut.inertiaDeg_smul"
p2m_open "AlgebraicCurve"
namespace Place
p2m_export "AlgebraicCurve.Place" "restrict inertiaDeg exists_algEquiv_smul_eq_of_restrict_eq"
p2m_open "AlgebraicCurve.Place"

variable {K F' M : Type*} [Field K] [Field F'] [Field M] [Algebra K F'] [Algebra K M]
  [Algebra F' M] [IsScalarTower K F' M]

private theorem intertwinesAlong_one_ofAlgAut (σ : M ≃ₐ[F'] M) :
    SemilinearAut.IntertwinesAlong (algebraMap F' M) (1 : SemilinearAut K F')
      (SemilinearAut.ofAlgAut (σ.restrictScalars K)) := by
  intro x
  rw [one_smul, SemilinearAut.ofAlgAut_smul]
  exact σ.commutes x

end Place
end AlgebraicCurve

open _root_.AlgebraicCurve.Place _root_.P2MW.S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq.AlgebraicCurve.Place in
theorem solution {K F' M : Type*} [Field K] [Field F'] [Field M]
    [Algebra K F'] [Algebra K M] [Algebra F' M] [IsScalarTower K F' M]
    [FiniteDimensional F' M] [IsGalois F' M] (W W' : Place K M)
    (h : W'.restrict F' = W.restrict F') :
    W'.inertiaDeg F' = W.inertiaDeg F' := by
  obtain ⟨σ, rfl⟩ := Place.exists_algEquiv_smul_eq_of_restrict_eq W W' h
  exact SemilinearAut.inertiaDeg_smul (intertwinesAlong_one_ofAlgAut σ) W

end

end S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq
end P2MW
export P2MW.S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.Place.inertiaDeg_eq_of_restrict_eq {K F' M : Type*} [Field K] [Field F'] [Field M]
    [Algebra K F'] [Algebra K M] [Algebra F' M] [IsScalarTower K F' M]
    [FiniteDimensional F' M] [IsGalois F' M] (W W' : Place K M)
    (h : W'.restrict F' = W.restrict F') :
    W'.inertiaDeg F' = W.inertiaDeg F' := _root_.P2MW.S_AlgebraicCurve_Place_inertiaDeg_eq_of_restrict_eq.solution W W' h

end publicSection
