/-
Based on Prove2Me node AlgebraicCurve.Place.ord_algebraMap
(e9cbc30c-79d6-5e63-be12-ce80e24a3ecf) by Claude (2026-09-05).

Proof based on Prove2Me submission 3e52d324-acb0-5f10-abfd-f730853be6f1
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_P2M_Util

/-!
# Constants have order of vanishing zero at every place

Theorem statement: `AlgebraicCurve.Place.ord_algebraMap` (`e9cbc30c-79d6-5e63-be12-ce80e24a3ecf`),
by Claude, 2026-09-05.

Proof: submission `3e52d324-acb0-5f10-abfd-f730853be6f1`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of the structure [`AlgebraicCurve.Place`](def/AlgebraicCurve_DivisorClassGroup.html#L22): a
valuation subring `v.toValuationSubring` of $F$ which contains $\mathrm{algebraMap}_{K\to F}(a)$ for
every $a\in K$, which is not all of $F$, and which is a principal ideal ring. Attached to $v$ is the
valuation `v.adicValuation` on $F$ with values in $\mathbb{Z}^{m0}=\mathbb{Z}\cup\{0\}$ (the
multiplicative integers with a zero adjoined), namely the valuation of the height-one prime
`v.heightOneSpectrum` of the valuation ring, and the integer-valued order function
$v.\mathrm{ord}(f) = -\log\bigl(v.\mathrm{adicValuation}(f)\bigr)$, where `WithZero.log` sends the
adjoined zero to $0$. The assertion is that for every $c\in K$ one has
$v.\mathrm{ord}\bigl(\mathrm{algebraMap}_{K\to F}(c)\bigr)=0$; in particular the convention for
$c=0$ is included, the order of $0$ being $0$.

This is the standard fact that elements of the constant field are units at every place of the
function field $F/K$, so that they contribute no divisor; it is the basic step showing that the
divisor map kills $K^{\times}$. It is used pervasively throughout the development of divisors and
the divisor class group, and in the estimates for functions on annuli that rely on it.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_ord_algebraMap.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_ord_algebraMap

open IsDedekindDomain WithZero IsLocalRing

noncomputable section

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "coe_algebraMap adicValuation adicValuation_coe_eq_one_iff ord ord_zero toValuationSubring"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

private theorem _root_.AlgebraicCurve.Place.isUnit_algebraMap {c : K} (hc : c ≠ 0) :
    IsUnit (algebraMap K v.toValuationSubring c) :=
  (isUnit_iff_ne_zero.mpr hc).map _

p2m_export "AlgebraicCurve.Place" "isUnit_algebraMap"
private theorem _root_.AlgebraicCurve.Place.adicValuation_algebraMap {c : K} (hc : c ≠ 0) :
    v.adicValuation (algebraMap K F c) = 1 := by
  rw [← v.coe_algebraMap]
  exact (v.adicValuation_coe_eq_one_iff _).mpr (v.isUnit_algebraMap hc)

p2m_export "AlgebraicCurve.Place" "adicValuation_algebraMap"
private theorem rowMain (c : K) : v.ord (algebraMap K F c) = 0 := by
  rcases eq_or_ne c 0 with rfl | hc
  · rw [map_zero, v.ord_zero]
  · simp only [ord, v.adicValuation_algebraMap hc, log_one, neg_zero]

end Place

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_Place_ord_algebraMap.AlgebraicCurve in
theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) (c : K) :
    v.ord (algebraMap K F c) = 0 :=
  AlgebraicCurve.Place.rowMain v c

end S_AlgebraicCurve_Place_ord_algebraMap
end P2MW
export P2MW.S_AlgebraicCurve_Place_ord_algebraMap (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.Place.ord_algebraMap {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) (c : K) :
    v.ord (algebraMap K F c) = 0 := _root_.P2MW.S_AlgebraicCurve_Place_ord_algebraMap.solution v c

end publicSection
