/-
Based on Prove2Me node P2M.Dup.AlgebraicCurve.Place.mem_iff_adicValuation_le_one
(178e8109-545f-5538-87ec-8b136dff080c) by Claude (2026-09-05).

Proof based on Prove2Me submission 2817c4bc-3434-5f96-8550-ad0de37dd8b4
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup
public import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaces

import Definitions.FLT.Def_P2M_Util

/-!
# Membership in a place's valuation ring via v≤ 1

Theorem statement: `P2M.Dup.AlgebraicCurve.Place.mem_iff_adicValuation_le_one`
(`178e8109-545f-5538-87ec-8b136dff080c`), by Claude, 2026-09-05.

Proof: submission `2817c4bc-3434-5f96-8550-ad0de37dd8b4`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of the project's structure `Place K F`: a valuation subring $\mathcal{O}_v \subseteq F$
(recorded as `v.toValuationSubring`) which contains the image of $K$ under the structure map, which
is not the whole of $F$, and which is a principal ideal ring — so that $\mathcal{O}_v$ is a discrete
valuation ring, with `v.heightOneSpectrum` its maximal ideal viewed as a point of the height-one
spectrum and `v.adicValuation` the associated $\mathbb{Z}^{m0}$-valued valuation on the fraction
field $F$, normalised so that a uniformiser has value the image of $-1$ (equivalently, the valuation
attached to that height-one prime). The theorem asserts, for an arbitrary element $f$ of $F$, the
equivalence of the two conditions: $f$ lies in the valuation subring $\mathcal{O}_v$, and
$v.\mathrm{adicValuation}(f) \le 1$ in $\mathbb{Z}^{m0}$. Thus the subring attached to a place
coincides with the set of elements of valuation at most one for the normalised valuation it
determines.

This is the elementary compatibility between the two descriptions of a place of a function field —
as a valuation subring and as a normalised discrete valuation — and it is the bridge used whenever
the order function of a place is computed from ring membership. It is cited throughout the divisor
and divisor-class-group material for places of $F/K$, for instance in the determination of degrees
of points on the rational function field and in the computation of the first cohomology of the
structure sheaf.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_mem_iff_adicValuation_le_one.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_mem_iff_adicValuation_le_one

open IsDedekindDomain WithZero IsLocalRing

noncomputable section

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ext heightOneSpectrum adicValuation toValuationSubring"
p2m_open "AlgebraicCurve.Place"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

p2m_export "AlgebraicCurve.Place" "adicValuation_valuationSubring"
private theorem rowMain {f : F} :
    f ∈ v.toValuationSubring ↔ v.adicValuation f ≤ 1 := by
  rw [← v.adicValuation_valuationSubring]
  exact Valuation.mem_valuationSubring_iff _ _

end Place

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_Place_mem_iff_adicValuation_le_one.AlgebraicCurve in
theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {f : F} :
    f ∈ v.toValuationSubring ↔ v.adicValuation f ≤ 1 :=
  AlgebraicCurve.Place.rowMain v

end S_AlgebraicCurve_Place_mem_iff_adicValuation_le_one
end P2MW
export P2MW.S_AlgebraicCurve_Place_mem_iff_adicValuation_le_one (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem P2M.Dup.AlgebraicCurve.Place.mem_iff_adicValuation_le_one {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {f : F} :
    f ∈ v.toValuationSubring ↔ v.adicValuation f ≤ 1 := _root_.P2MW.S_AlgebraicCurve_Place_mem_iff_adicValuation_le_one.solution v

end publicSection
