/-
Based on Prove2Me node WeierstrassCurve.Affine.FunctionField.exists_eq_algebraMap_of_valuation_eq_one
(3180b122-1bc0-5283-bc24-20ba69c94aeb) by Claude (2026-09-05).

Proof based on Prove2Me submission dbe9c74f-476c-5ddf-badb-85457ebaf495
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
public import Mathlib.RingTheory.SimpleRing.Principal

import Definitions.FLT.Def_P2M_Util

/-!
# Everywhere trivial valuation forces a constant function

Theorem statement: `WeierstrassCurve.Affine.FunctionField.exists_eq_algebraMap_of_valuation_eq_one`
(`3180b122-1bc0-5283-bc24-20ba69c94aeb`), by Claude, 2026-09-05.

Proof: submission `dbe9c74f-476c-5ddf-badb-85457ebaf495`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be a field and $W$ a Weierstrass curve over $F$, and assume the affine coordinate ring
`W.toAffine.CoordinateRing`, i.e. $F[X,Y]$ modulo the Weierstrass polynomial of $W$, is a Dedekind
domain. Let $f$ be an element of the function field `W.toAffine.FunctionField`, the fraction field
of that coordinate ring. Suppose that for every $v$ in the height-one spectrum of the coordinate
ring — that is, every nonzero prime ideal — the associated $v$-adic valuation of $f$, taken in the
multiplicative value group $\mathbb{Z}_{m_0}$ attached to $v$ by
`IsDedekindDomain.HeightOneSpectrum.valuation`, is equal to $1$; equivalently, $f$ has order $0$ at
every such $v$, so neither a zero nor a pole. The conclusion is that there exists $c \in F$ with $c
\neq 0$ and $f$ equal to the image of $c$ under the structure map $F \to$
`W.toAffine.FunctionField`. No condition at the point at infinity is imposed.

This is the form of the classical statement that a rational function on an elliptic curve with
trivial divisor is constant (Silverman, AEC II.1.2, II.3.1), phrased purely in terms of the
height-one valuations of the affine coordinate ring. It is used in the construction of the Weil
pairing, where ratios of translated functions are shown to be constant: among the results citing it
are
[`WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_map_of_algHom`](thm.html#WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_map_of_algHom),
[`WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul`](thm.html#WeierstrassCurve.Affine.exists_map_weilFun_eq_mul_weilFun_smul)
and
[`WeierstrassCurve.Affine.exists_transEquiv_weilFun_eq`](thm.html#WeierstrassCurve.Affine.exists_transEquiv_weilFun_eq).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one

p2m_open "Polynomial WeierstrassCurve P2MW.S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one.WeierstrassCurve WeierstrassCurve.Affine P2MW.S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one.WeierstrassCurve.Affine"
open scoped Polynomial.Bivariate nonZeroDivisors

namespace WeierstrassCurve
p2m_export "WeierstrassCurve" "Affine map Affine.CoordinateRing mk toAffine Affine.Point"
namespace Affine
p2m_export "WeierstrassCurve.Affine" "CoordinateRing.smul_basis_eq_zero CoordinateRing.XClass_ne_zero CoordinateRing.norm_smul_basis CoordinateRing CoordinateRing.smul map FunctionField Point CoordinateRing.mk CoordinateRing.degree_norm_smul_basis CoordinateRing.exists_smul_basis_eq CoordinateRing.XClass"
namespace CoordinateRing
p2m_export "WeierstrassCurve.Affine.CoordinateRing" "smul_basis_eq_zero XClass_ne_zero norm_smul_basis smul mk map degree_norm_smul_basis exists_smul_basis_eq XClass"
namespace DetInfra
p2m_open "WeierstrassCurve.Affine.CoordinateRing WeierstrassCurve.Affine WeierstrassCurve"

theorem isUnit_iff_eq_algebraMap' {F : Type*} [Field F] {W : WeierstrassCurve F} (f : W.toAffine.CoordinateRing) :
    IsUnit f ↔ ∃ c : F, c ≠ 0 ∧ f = algebraMap F W.toAffine.CoordinateRing c := by
  constructor
  · intro hf
    obtain ⟨p, q, rfl⟩ := CoordinateRing.exists_smul_basis_eq f
    have hnu : IsUnit (Algebra.norm F[X] (p • (1 : W.toAffine.CoordinateRing) +
        q • CoordinateRing.mk W.toAffine Y)) := hf.map _
    have hdeg := Polynomial.degree_eq_zero_of_isUnit hnu
    rw [CoordinateRing.degree_norm_smul_basis] at hdeg
    have hq : q = 0 := by
      by_contra hq
      have h3 : (2 • q.degree + 3 : WithBot ℕ) = ((2 * q.natDegree + 3 : ℕ) : WithBot ℕ) := by
        rw [Polynomial.degree_eq_natDegree hq]
        norm_cast
      have hle : ((2 * q.natDegree + 3 : ℕ) : WithBot ℕ) ≤ (0 : WithBot ℕ) := by
        rw [← h3, ← hdeg]
        exact le_max_right _ _
      have hle' : 2 * q.natDegree + 3 ≤ 0 := by exact_mod_cast hle
      omega
    subst hq
    rw [zero_smul, add_zero] at hnu ⊢
    have hnp : Algebra.norm F[X] (p • (1 : W.toAffine.CoordinateRing)) = p ^ 2 := by
      have := CoordinateRing.norm_smul_basis (W' := W.toAffine) p 0
      rw [zero_smul, add_zero] at this
      rw [this]
      ring
    rw [hnp, isUnit_pow_iff two_ne_zero, Polynomial.isUnit_iff] at hnu
    obtain ⟨c, hc, rfl⟩ := hnu
    refine ⟨c, hc.ne_zero, ?_⟩
    rw [CoordinateRing.smul, mul_one]
    rfl
  · rintro ⟨c, hc, rfl⟩
    exact (IsUnit.mk0 c hc).map _

theorem XClass_not_isUnit {F : Type*} [Field F] {W : WeierstrassCurve F} (x : F) :
    ¬IsUnit (CoordinateRing.XClass W.toAffine x) := by
  rw [isUnit_iff_eq_algebraMap']
  rintro ⟨c, -, hc⟩

  have h1 : (X - C x - C c) • (1 : W.toAffine.CoordinateRing) + (0 : F[X]) • CoordinateRing.mk W.toAffine Y = 0 := by
    rw [zero_smul, add_zero, sub_smul, CoordinateRing.smul, mul_one, CoordinateRing.smul, mul_one,
      sub_eq_zero]
    exact hc
  have := (CoordinateRing.smul_basis_eq_zero h1).1
  have h2 := congrArg Polynomial.natDegree this
  rw [sub_sub, ← C_add, natDegree_X_sub_C, natDegree_zero] at h2
  exact one_ne_zero h2

end WeierstrassCurve.Affine.CoordinateRing.DetInfra

open WeierstrassCurve.Affine.CoordinateRing.DetInfra

theorem solution {F : Type*} [Field F] {W : WeierstrassCurve F} [IsDedekindDomain W.toAffine.CoordinateRing] {f : W.toAffine.FunctionField} (hf : ∀ v : IsDedekindDomain.HeightOneSpectrum W.toAffine.CoordinateRing, v.valuation W.toAffine.FunctionField f = 1) : ∃ c : F, c ≠ 0 ∧ f = algebraMap F W.toAffine.FunctionField c := by

  obtain ⟨M, hMmax, hXM⟩ := exists_max_ideal_of_mem_nonunits (XClass_not_isUnit (W := W) 0)
  have hM0 : M ≠ ⊥ := fun h =>
    CoordinateRing.XClass_ne_zero (W' := W.toAffine) 0 (by rwa [h, Ideal.mem_bot] at hXM)
  let v₀ : IsDedekindDomain.HeightOneSpectrum W.toAffine.CoordinateRing := ⟨M, hMmax.isPrime, hM0⟩
  have hf0 : f ≠ 0 := fun h => by simpa [h] using hf v₀

  obtain ⟨g, hg⟩ := IsDedekindDomain.HeightOneSpectrum.mem_integers_of_valuation_le_one
    W.toAffine.FunctionField f (fun v => (hf v).le)
  obtain ⟨g', hg'⟩ := IsDedekindDomain.HeightOneSpectrum.mem_integers_of_valuation_le_one
    W.toAffine.FunctionField f⁻¹ (fun v => by rw [map_inv₀, hf v, inv_one])
  have hgg' : g * g' = 1 := by
    apply IsFractionRing.injective W.toAffine.CoordinateRing W.toAffine.FunctionField
    rw [map_mul, hg, hg', map_one, mul_inv_cancel₀ hf0]
  obtain ⟨c, hc, hgc⟩ := (isUnit_iff_eq_algebraMap' g).mp (IsUnit.of_mul_eq_one g' hgg')
  refine ⟨c, hc, ?_⟩
  rw [← hg, hgc, ← IsScalarTower.algebraMap_apply]

end S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one
end P2MW
export P2MW.S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

theorem WeierstrassCurve.Affine.FunctionField.exists_eq_algebraMap_of_valuation_eq_one {F : Type*} [Field F] {W : WeierstrassCurve F} [IsDedekindDomain W.toAffine.CoordinateRing] {f : W.toAffine.FunctionField} (hf : ∀ v : IsDedekindDomain.HeightOneSpectrum W.toAffine.CoordinateRing, v.valuation W.toAffine.FunctionField f = 1) : ∃ c : F, c ≠ 0 ∧ f = algebraMap F W.toAffine.FunctionField c := _root_.P2MW.S_WeierstrassCurve_Affine_FunctionField_exists_eq_algebraMap_of_valuation_eq_one.solution hf

end publicSection
