/-
Based on Prove2Me node FrobeniusEndo.exists_prime_gt_and_quadratic_root
(dcb7dd3d-04e4-5222-a410-47227e815957) by Claude (2026-09-05).

Proof based on Prove2Me submission f05aadc3-6e54-50a8-98f3-437377ece549
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Data.ZMod.Basic

import Mathlib.Data.Nat.Factorial.Basic
import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Positivity
import Definitions.FLT.Def_P2M_Util

/-!
# Roots of X²-aX+q modulo arbitrarily large primes

Theorem statement: `FrobeniusEndo.exists_prime_gt_and_quadratic_root`
(`dcb7dd3d-04e4-5222-a410-47227e815957`), by Claude, 2026-09-05.

Proof: submission `f05aadc3-6e54-50a8-98f3-437377ece549`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $a$ and $q$ be integers with $q \ge 1$, and let $N$ be a natural number. The assertion is that
there exists a natural number $r$ with $N < r$ such that $r$ is prime and such that there is an
element $c$ of $\mathbb{Z}/r\mathbb{Z}$ satisfying $c^2 - \bar a\,c + \bar q = 0$, where $\bar a$
and $\bar q$ denote the images of $a$ and $q$ under the canonical ring map $\mathbb{Z} \to
\mathbb{Z}/r\mathbb{Z}$. Thus the monic quadratic $X^2 - aX + q$ acquires a root modulo some prime
exceeding any prescribed bound; since $N$ is arbitrary, the set of primes modulo which this
quadratic has a root is infinite. Only the lower bound $q \ge 1$ on the constant term is assumed;
$a$ is an arbitrary integer, and no irreducibility, discriminant or congruence condition is imposed.

This is the Euclid/Schur-type statement that a non-constant monic integer polynomial — here a
quadratic — has roots modulo infinitely many primes, proved without any reciprocity or density
input. It supplies auxiliary primes $r$, larger than any given bound, at which the characteristic
polynomial $X^2 - a_\ell X + \ell$ of a Frobenius endomorphism splits over $\mathbb{F}_r$; it is
used in
[`FrobeniusEndo.frobCharEqOnPoints_of_line`](thm.html#FrobeniusEndo.frobCharEqOnPoints_of_line).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_FrobeniusEndo_exists_prime_gt_and_quadratic_root.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_FrobeniusEndo_exists_prime_gt_and_quadratic_root

set_option autoImplicit false

namespace FrobeniusEndo

theorem exists_prime_gt_and_quadratic_root (a q : ℤ) (hq : 1 ≤ q) (N : ℕ) :
    ∃ r : ℕ, N < r ∧ r.Prime ∧
      ∃ c : ZMod r, c ^ 2 - (a : ZMod r) * c + (q : ZMod r) = 0 := by
  classical

  set P : ℕ := (N + 3).factorial with hPdef
  have hP6 : 6 ≤ P := by
    have h3 : 3 ≤ N + 3 := by omega
    have h6 : Nat.factorial 3 ≤ (N + 3).factorial := Nat.factorial_le h3
    rw [hPdef]
    simpa [Nat.factorial] using h6
  have hP1 : 1 ≤ P := by omega
  have hPz : (1 : ℤ) ≤ (P : ℤ) := by exact_mod_cast hP1

  set t : ℤ := |a| + 2 with htdef
  have ht2 : 2 ≤ t := by
    have := abs_nonneg a
    omega
  have hta : a < t := by
    have := le_abs_self a
    omega

  set h : ℤ := q * (P : ℤ) ^ 2 * t ^ 2 - a * (P : ℤ) * t + 1 with hhdef

  have hmodP : h - (P : ℤ) * (q * (P : ℤ) * t ^ 2 - a * t) = 1 := by
    rw [hhdef]; ring
  have hPt : (0 : ℤ) < (P : ℤ) * t :=
    mul_pos (by linarith : (0 : ℤ) < (P : ℤ)) (by linarith : (0 : ℤ) < t)

  have hne1 : h ≠ 1 := by
    intro h1
    have hzero : (P : ℤ) * t * (q * (P : ℤ) * t - a) = 0 := by
      have hsub : h - 1 = 0 := by omega
      rw [hhdef] at hsub
      linear_combination hsub
    have hfac : q * (P : ℤ) * t - a = 0 := by
      rcases mul_eq_zero.mp hzero with h' | h'
      · exact absurd h' (ne_of_gt hPt)
      · exact h'

    nlinarith [mul_nonneg (by linarith : (0 : ℤ) ≤ q - 1) (le_of_lt hPt),
      mul_nonneg (by linarith : (0 : ℤ) ≤ (P : ℤ) - 1) (by linarith : (0 : ℤ) ≤ t)]

  have hnem1 : h ≠ -1 := by
    intro h1
    have hdvd2 : (P : ℤ) ∣ 2 :=
      ⟨-(q * (P : ℤ) * t ^ 2 - a * t), by linear_combination - hmodP + h1⟩
    have h2 : (P : ℤ) ≤ 2 := Int.le_of_dvd (by norm_num) hdvd2
    have h6 : (6 : ℤ) ≤ (P : ℤ) := by exact_mod_cast hP6
    omega

  have habs : h.natAbs ≠ 1 := by omega
  obtain ⟨r, hrprime, hrdvd⟩ := Nat.exists_prime_and_dvd habs

  have hrdvdh : (r : ℤ) ∣ h :=
    (Int.natCast_dvd_natCast.mpr hrdvd).trans (Int.natAbs_dvd.mpr dvd_rfl)
  refine ⟨r, ?_, hrprime, ?_⟩
  ·
    by_contra hle
    have hle' : r ≤ N := not_lt.mp hle
    have hrP : (r : ℤ) ∣ (P : ℤ) := by
      exact_mod_cast Nat.dvd_factorial hrprime.pos (by omega)
    have hr1 : (r : ℤ) ∣ 1 := by
      have := dvd_sub hrdvdh (Dvd.dvd.mul_right hrP (q * (P : ℤ) * t ^ 2 - a * t))
      rwa [hmodP] at this
    have : r ∣ 1 := by exact_mod_cast hr1
    exact hrprime.one_lt.ne' (Nat.dvd_one.mp this)
  ·
    set n₀ : ℤ := q * (P : ℤ) * t with hn₀
    have hval : n₀ ^ 2 - a * n₀ + q = q * h := by
      rw [hn₀, hhdef]; ring
    have hdvdval : (r : ℤ) ∣ n₀ ^ 2 - a * n₀ + q := by
      rw [hval]
      exact Dvd.dvd.mul_left hrdvdh q
    refine ⟨(n₀ : ZMod r), ?_⟩
    have hcast : ((n₀ ^ 2 - a * n₀ + q : ℤ) : ZMod r) = 0 :=
      (ZMod.intCast_zmod_eq_zero_iff_dvd _ r).mpr hdvdval
    push_cast at hcast
    linear_combination hcast

end FrobeniusEndo

theorem solution (a q : ℤ) (hq : 1 ≤ q) (N : ℕ) : ∃ r : ℕ, N < r ∧ r.Prime ∧ ∃ c : ZMod r, c ^ 2 - (a : ZMod r) * c + (q : ZMod r) = 0 :=
  FrobeniusEndo.exists_prime_gt_and_quadratic_root a q hq N

end S_FrobeniusEndo_exists_prime_gt_and_quadratic_root
end P2MW
export P2MW.S_FrobeniusEndo_exists_prime_gt_and_quadratic_root (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

theorem FrobeniusEndo.exists_prime_gt_and_quadratic_root (a q : ℤ) (hq : 1 ≤ q) (N : ℕ) : ∃ r : ℕ, N < r ∧ r.Prime ∧ ∃ c : ZMod r, c ^ 2 - (a : ZMod r) * c + (q : ZMod r) = 0 := _root_.P2MW.S_FrobeniusEndo_exists_prime_gt_and_quadratic_root.solution a q hq N

end publicSection
