/-
Based on Prove2Me node ModularCurve.exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral
(f3a1f418-a302-5827-af73-77a29cd04522) by Claude (2026-09-05).

Proof based on Prove2Me submission e615e3a5-1af1-5901-9523-3e01fc30dca7
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.QExpansion
public import Definitions.FLT.Def_ModularCurve_LaurentCoeff
public import Definitions.FLT.Def_ModularCurve_QExpansionDiff
public import Definitions.FLT.Def_ModularCurve_X0

import Theorems.FLT.Thm_ModularCurve_analyticOrderAt_le_of_isIntegral_adjoin_coeffEmb_jq_pow
import Theorems.FLT.Thm_ModularCurve_eventually_norm_slash_le_of_isIntegral_adjoin_coeffEmb_jq_inv_pow
import Theorems.FLT.Thm_ModularCurve_exists_modularForm_mul_qExpansion_eq_of_mem_laurentBaseChange
import Theorems.FLT.Thm_ModularCurve_thetaL_coeffMap_eq_coeffMap_single_mul_derivative
import Theorems.FLT.Thm_ModularForm_exists_cuspForm_mul_eq_of_analyticOrderAt_le
import Theorems.FLT.Thm_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne
import Theorems.FLT.Thm_omegaRow_T2
import Definitions.FLT.Def_P2M_Util

/-!
# Weight-2m cusp forms from integrality over ℂ[j] and ℂ[1/j]

Theorem statement: `ModularCurve.exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral`
(`f3a1f418-a302-5827-af73-77a29cd04522`), by Claude, 2026-09-05.

Proof: submission `e615e3a5-1af1-5901-9523-3e01fc30dca7`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N\ge 1$ and let $m\ge 1$ be a natural number. Write $J :=$ [`ModularCurve.coeffEmb ℂ
ModularCurve.jq`](def/ModularCurve_LaurentCoeff.html#L81) for the image in $\mathbb C((q))$, under
the coefficientwise ring map induced by $\mathbb Q\to\mathbb C$, of the Laurent series
$q^{-1}\cdot(\text{the power series } j_{\mathrm{Num}}$ over $\mathbb Q)$, and let $\vartheta$
denote the $\mathbb C$-linear operator
[`ModularCurve.thetaL`](def/ModularCurve_QExpansionDiff.html#L16) on $\mathbb C((q))$ sending $f$ to
$q\cdot f'$. Let $X$ be a Laurent series over $\mathbb C$ lying in [`ModularCurve.laurentBaseChange
ℂ (ModularCurve.modularFunctionFieldFull N)`](def/ModularCurve_LaurentCoeff.html#L103), that is, in
the intermediate field of $\mathbb C((q))/\mathbb C$ generated by the coefficientwise images of the
subfield of $\mathbb Q((q))$ generated over $\mathbb Q$ by the series $q$-expanded along the
divisors $d\mid N$ of $j$. Let $M$ be a natural number, and assume: (i) $X^{6}J^{4m}(J-1728)^{3m}$
is integral over the $\mathbb C$-subalgebra of $\mathbb C((q))$ generated by $J$; (ii)
$X^{2M}J^{mM+1}(J-1728)^{mM}$ is integral over the $\mathbb C$-subalgebra generated by $J^{-1}$.
Then there exists a cusp form $f$ on $\Gamma_0(N)$ of weight $2m$ whose $q$-expansion of width $1$,
regarded as a Laurent series, equals $X\cdot(\vartheta J)^{m}$.

This is the analytic criterion recognising an element of the field of modular functions of level
$N$, multiplied by $(\vartheta j)^m$, as the $q$-expansion of a weight-$2m$ cusp form on
$\Gamma_0(N)$, the two integrality hypotheses encoding holomorphy on the upper half-plane and the
vanishing conditions at the cusps. It is used by
[`ModularCurve.exists_cuspForm_qExpansion_eq_coeffMap_mul_thetaL_pow_of_isIntegral`](thm.html#ModularCurve.exists_cuspForm_qExpansion_eq_coeffMap_mul_thetaL_pow_of_isIntegral),
and rests on the criterion
[`ModularForm.exists_cuspForm_mul_eq_of_analyticOrderAt_le`](thm.html#ModularForm.exists_cuspForm_mul_eq_of_analyticOrderAt_le)
together with the order and growth estimates supplied by the two integrality assumptions.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral
p2m_attr_erase "simp" "ModularCurve.jqNModC_one"

open ModularCurve UpperHalfPlane HahnSeries
open scoped MatrixGroups ModularForm

noncomputable section

namespace ANGlueM

theorem one_mem_strictPeriods_gamma0 (N : ℕ) :
    (1 : ℝ) ∈ (Subgroup.map (Matrix.SpecialLinearGroup.mapGL ℝ) (CongruenceSubgroup.Gamma0 N)).strictPeriods := by
  rw [CongruenceSubgroup.strictPeriods_Gamma0]
  exact AddSubgroup.mem_zmultiples 1

theorem thetaL_coeffEmb_jq :
    thetaL ℂ (coeffEmb ℂ jq) = coeffMap (algebraMap ℚ ℂ) (thetaL ℚ jq) := by
  rw [coeffEmb, ModularCurve.thetaL_coeffMap_eq_coeffMap_single_mul_derivative]
  rfl

noncomputable def powMF {Γ : Subgroup (GL (Fin 2) ℝ)} [Γ.HasDetPlusMinusOne] {w : ℤ} (P : ModularForm Γ w) :
    (m : ℕ) → ModularForm Γ ((m : ℤ) * w)
  | 0 => ModularForm.mcast (by simp) (1 : ModularForm Γ 0)
  | m + 1 => ModularForm.mcast (by push_cast; ring) ((powMF P m).mul P)

theorem coe_powMF {Γ : Subgroup (GL (Fin 2) ℝ)} [Γ.HasDetPlusMinusOne] {w : ℤ} (P : ModularForm Γ w) (m : ℕ) :
    (powMF P m : ℍ → ℂ) = (P : ℍ → ℂ) ^ m := by
  induction m with
  | zero =>
    show ((1 : ModularForm Γ 0) : ℍ → ℂ) = _
    rw [ModularForm.one_coe_eq_one, pow_zero]
  | succ m ih =>
    show (((powMF P m).mul P : ModularForm Γ _) : ℍ → ℂ) = _
    rw [ModularForm.coe_mul, ih, pow_succ]

theorem qExpansion_powMF_succ {Γ : Subgroup (GL (Fin 2) ℝ)} [Γ.HasDetPlusMinusOne] {w : ℤ} (P : ModularForm Γ w)
    (h1 : (1 : ℝ) ∈ Γ.strictPeriods) (m : ℕ) :
    qExpansion 1 (powMF P (m + 1) : ℍ → ℂ) = qExpansion 1 (P : ℍ → ℂ) ^ (m + 1) := by
  induction m with
  | zero =>
    have hc : (powMF P (0 + 1) : ℍ → ℂ) = (P : ℍ → ℂ) := by rw [coe_powMF, zero_add, pow_one]
    rw [hc, zero_add, pow_one]
  | succ m ih =>
    show qExpansion 1 (((powMF P (m + 1)).mul P : ModularForm Γ _) : ℍ → ℂ) = _
    rw [ModularForm.qExpansion_mul one_pos h1, ih, ← pow_succ]

end ANGlueM

set_option maxHeartbeats 3200000 in
open ANGlueM in
theorem solution (N : ℕ) [NeZero N] (m : ℕ) (hm : 1 ≤ m)
    (X : LaurentSeries ℂ)
    (hX : X ∈ ModularCurve.laurentBaseChange ℂ (ModularCurve.modularFunctionFieldFull N)) (M : ℕ)
    (h₁ : IsIntegral (Algebra.adjoin ℂ ({ModularCurve.coeffEmb ℂ ModularCurve.jq} : Set (LaurentSeries ℂ)))
      (X ^ 6 * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ (4 * m) *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ (3 * m)))
    (h₂ : IsIntegral (Algebra.adjoin ℂ ({(ModularCurve.coeffEmb ℂ ModularCurve.jq)⁻¹} : Set (LaurentSeries ℂ)))
      (X ^ (2 * M) * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ (m * M + 1) *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ (m * M))) :
    ∃ f : CuspForm (CongruenceSubgroup.Gamma0 N) (2 * (m : ℤ)),
      HahnSeries.ofPowerSeries ℤ ℂ (UpperHalfPlane.qExpansion 1 f) =
        X * ModularCurve.thetaL ℂ (ModularCurve.coeffEmb ℂ ModularCurve.jq) ^ m := by
  classical
  obtain ⟨m, rfl⟩ : ∃ m' : ℕ, m = m' + 1 := ⟨m - 1, (Nat.sub_add_cancel hm).symm⟩
  obtain ⟨k, g, h, hh, hXh⟩ :=
    ModularCurve.exists_modularForm_mul_qExpansion_eq_of_mem_laurentBaseChange N X hX
  obtain ⟨E4N, hE4⟩ := ModularForm.exists_gamma0_qExpansion_eq_of_levelOne N ModularForm.E₄
  obtain ⟨E6N, hE6⟩ := ModularForm.exists_gamma0_qExpansion_eq_of_levelOne N ModularForm.E₆
  obtain ⟨DN, hD⟩ := ModularForm.exists_gamma0_qExpansion_eq_of_levelOne N
    (ModularFormClass.modularForm (CuspForm.discriminant))
  have hDcoe : (DN : ℍ → ℂ) = ModularForm.discriminant := by
    rw [hD]
    funext z
    rw [← CuspForm.toModularFormₗ_eq_coe, CuspForm.toModularFormₗ_apply]
    rfl
  have h1 := one_mem_strictPeriods_gamma0 N
  obtain ⟨P, hPdef⟩ : ∃ P : ModularForm (CongruenceSubgroup.Gamma0 N) ((4 + 4) + 6), P = (E4N.mul E4N).mul E6N := ⟨_, rfl⟩
  have hPcoe : (P : ℍ → ℂ) = fun z => ModularForm.E₄ z ^ 2 * ModularForm.E₆ z := by
    funext z
    simp only [hPdef, ModularForm.coe_mul, Pi.mul_apply, hE4, hE6]
    ring
  obtain ⟨Φ, hΦdef⟩ : ∃ Φ : ModularForm (CongruenceSubgroup.Gamma0 N) (k + ((m + 1 : ℕ) : ℤ) * ((4 + 4) + 6)),
      Φ = g.mul (powMF P (m + 1)) := ⟨_, rfl⟩
  obtain ⟨Ψ, hΨdef⟩ : ∃ Ψ : ModularForm (CongruenceSubgroup.Gamma0 N) (k + ((m + 1 : ℕ) : ℤ) * 12),
      Ψ = h.mul (powMF DN (m + 1)) := ⟨_, rfl⟩
  have hΦcoe : (Φ : ℍ → ℂ) = fun z => g z * (ModularForm.E₄ z ^ 2 * ModularForm.E₆ z) ^ (m + 1) := by
    funext z
    rw [hΦdef, ModularForm.coe_mul, coe_powMF, hPcoe, Pi.mul_apply, Pi.pow_apply]
  have hΨcoe : (Ψ : ℍ → ℂ) = fun z => h z * ModularForm.discriminant z ^ (m + 1) := by
    funext z
    rw [hΨdef, ModularForm.coe_mul, coe_powMF, hDcoe, Pi.mul_apply, Pi.pow_apply]
  have hΨ0 : Ψ ≠ 0 := by
    intro h0
    apply hh
    have hfun : (Ψ : ℍ → ℂ) = 0 := by rw [h0]; rfl
    rw [hΨcoe] at hfun
    rw [← FunLike.coe_zero_iff]
    funext z
    have := congr_fun hfun z
    simp only [Pi.zero_apply, mul_eq_zero] at this
    rcases this with hz | hz
    · exact hz
    · exact absurd (pow_eq_zero_iff (Nat.succ_ne_zero m) |>.mp hz) (ModularForm.discriminant_ne_zero z)
  have hm1 : 1 ≤ m + 1 := Nat.le_add_left 1 m
  have hord : ∀ τ : ℍ, analyticOrderAt ((Ψ : ℍ → ℂ) ∘ ofComplex) (τ : ℂ) ≤
      analyticOrderAt ((Φ : ℍ → ℂ) ∘ ofComplex) (τ : ℂ) := by
    intro τ
    rw [hΦcoe, hΨcoe]
    exact ModularCurve.analyticOrderAt_le_of_isIntegral_adjoin_coeffEmb_jq_pow N (m + 1) g h X hXh h₁ τ
  have hcusp : ∀ (A : SL(2, ℤ)) (ε : ℝ), 0 < ε → ∀ᶠ τ : ℍ in atImInfty,
      ‖((Φ : ℍ → ℂ) ∣[k + ((m + 1 : ℕ) : ℤ) * ((4 + 4) + 6)] (A : GL (Fin 2) ℝ)) τ‖ ≤
        ε * ‖((Ψ : ℍ → ℂ) ∣[k + ((m + 1 : ℕ) : ℤ) * 12] (A : GL (Fin 2) ℝ)) τ‖ := by
    intro A ε hε
    rw [hΦcoe, hΨcoe, show k + ((m + 1 : ℕ) : ℤ) * ((4 + 4) + 6) = k + 14 * ((m + 1 : ℕ) : ℤ) by ring,
      show k + ((m + 1 : ℕ) : ℤ) * 12 = k + 12 * ((m + 1 : ℕ) : ℤ) by ring]
    exact ModularCurve.eventually_norm_slash_le_of_isIntegral_adjoin_coeffEmb_jq_inv_pow N (m + 1) g h X hXh M h₂ A ε hε
  obtain ⟨f, hf⟩ := ModularForm.exists_cuspForm_mul_eq_of_analyticOrderAt_le N (2 * ((m + 1 : ℕ) : ℤ))
    (by push_cast; ring) Φ Ψ hΨ0 hord hcusp
  have hfΨ : ((ModularFormClass.modularForm f).mul Ψ : ℍ → ℂ) = (Φ : ℍ → ℂ) := by
    funext z
    rw [ModularForm.coe_mul, Pi.mul_apply, ← CuspForm.toModularFormₗ_eq_coe, CuspForm.toModularFormₗ_apply]
    exact hf z
  have hcoef : ((ModularFormClass.modularForm f : ModularForm (CongruenceSubgroup.Gamma0 N) (2 * ((m + 1 : ℕ) : ℤ))) : ℍ → ℂ) = (f : ℍ → ℂ) := by
    rw [← CuspForm.toModularFormₗ_eq_coe]
    funext z
    exact CuspForm.toModularFormₗ_apply f z
  have hq : qExpansion 1 (f : ℍ → ℂ) * qExpansion 1 (Ψ : ℍ → ℂ) = qExpansion 1 (Φ : ℍ → ℂ) := by
    have e := ModularForm.qExpansion_mul one_pos h1 (ModularFormClass.modularForm f) Ψ
    rw [hfΨ, hcoef] at e
    exact e.symm
  have hqD : qExpansion 1 (powMF DN (m + 1) : ℍ → ℂ) = qExpansion 1 ModularForm.discriminant ^ (m + 1) := by
    rw [qExpansion_powMF_succ DN h1 m, hDcoe]
  have hqP : qExpansion 1 (powMF P (m + 1) : ℍ → ℂ) =
      (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) * qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) *
        qExpansion 1 (ModularForm.E₆ : ℍ → ℂ)) ^ (m + 1) := by
    rw [qExpansion_powMF_succ P h1 m, hPdef, ModularForm.qExpansion_mul one_pos h1, ModularForm.qExpansion_mul one_pos h1,
      hE4, hE6]
  have hqΨ : qExpansion 1 (Ψ : ℍ → ℂ) = qExpansion 1 (h : ℍ → ℂ) * qExpansion 1 ModularForm.discriminant ^ (m + 1) := by
    rw [hΨdef, ModularForm.qExpansion_mul one_pos h1, hqD]
  have hqΦ : qExpansion 1 (Φ : ℍ → ℂ) =
      qExpansion 1 (g : ℍ → ℂ) * (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) * qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) *
        qExpansion 1 (ModularForm.E₆ : ℍ → ℂ)) ^ (m + 1) := by
    rw [hΦdef, ModularForm.qExpansion_mul one_pos h1, hqP]
  set F : LaurentSeries ℂ := ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) with hF
  set Hh : LaurentSeries ℂ := ((qExpansion 1 (h : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) with hHh
  set G : LaurentSeries ℂ := ((qExpansion 1 (g : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) with hG
  set D : LaurentSeries ℂ := ((qExpansion 1 ModularForm.discriminant : PowerSeries ℂ) : LaurentSeries ℂ) with hDD
  set A4 : LaurentSeries ℂ := ((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) with hA4
  set A6 : LaurentSeries ℂ := ((qExpansion 1 (ModularForm.E₆ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) with hA6
  set T : LaurentSeries ℂ := thetaL ℂ (coeffEmb ℂ jq) with hT
  have hT2 : T * D = -(A4 ^ 2 * A6) := by
    rw [hT, thetaL_coeffEmb_jq]
    exact omegaRow_T2
  have eq1 : F * (Hh * D ^ (m + 1)) = G * (A4 * A4 * A6) ^ (m + 1) := by
    rw [hF, hHh, hDD, hG, hA4, hA6, ← PowerSeries.coe_pow, ← PowerSeries.coe_mul, ← PowerSeries.coe_mul, ← hqΨ, hq, hqΦ,
      PowerSeries.coe_mul, PowerSeries.coe_pow, PowerSeries.coe_mul, PowerSeries.coe_mul]
  have hhq : Hh ≠ 0 := by
    intro h0
    apply hh
    have h0' : qExpansion 1 (h : ℍ → ℂ) = 0 :=
      HahnSeries.ofPowerSeries_injective (by rw [← hHh, h0, map_zero])
    exact (ModularForm.qExpansion_eq_zero_iff one_pos h1 h).mp h0'
  have hDN0 : DN ≠ 0 := by
    intro h0
    have hI : (DN : ℍ → ℂ) UpperHalfPlane.I = 0 := by rw [h0]; rfl
    rw [hDcoe] at hI
    exact ModularForm.discriminant_ne_zero _ hI
  have hDq : D ≠ 0 := by
    intro h0
    apply hDN0
    have h0' : qExpansion 1 (DN : ℍ → ℂ) = 0 :=
      HahnSeries.ofPowerSeries_injective (by rw [hDcoe, ← hDD, h0, map_zero])
    exact (ModularForm.qExpansion_eq_zero_iff one_pos h1 DN).mp h0'
  have hHD : Hh * D ^ (m + 1) ≠ 0 := mul_ne_zero hhq (pow_ne_zero _ hDq)
  set X2 : LaurentSeries ℂ := A4 ^ 2 * A6 with hX2
  have eq1' : F * (Hh * D ^ (m + 1)) = X * Hh * X2 ^ (m + 1) := by
    rw [eq1, ← hXh, hX2]; ring
  rcases Nat.even_or_odd (m + 1) with hev | hodd
  · obtain ⟨r, hr⟩ := hev
    have hsq : (T * D) ^ 2 = X2 ^ 2 := by rw [hT2]; ring
    have hP2 : X2 ^ (m + 1) = (T * D) ^ (m + 1) := by
      rw [hr, ← two_mul, pow_mul, pow_mul, hsq]
    have key : (F - X * T ^ (m + 1)) * (Hh * D ^ (m + 1)) = 0 := by
      rw [sub_mul, eq1', hP2, mul_pow]; ring
    have hF' : F = X * T ^ (m + 1) := sub_eq_zero.mp ((mul_eq_zero.mp key).resolve_right hHD)
    exact ⟨f, hF'⟩
  · obtain ⟨r, hr⟩ := hodd
    have hsq : (T * D) ^ 2 = X2 ^ 2 := by rw [hT2]; ring
    have hP2 : X2 ^ (m + 1) = -(T * D) ^ (m + 1) := by
      rw [hr, pow_succ, pow_succ, pow_mul, pow_mul, hsq, hT2]; ring
    have key : (F + X * T ^ (m + 1)) * (Hh * D ^ (m + 1)) = 0 := by
      rw [add_mul, eq1', hP2, mul_pow]; ring
    have hF' : F = -(X * T ^ (m + 1)) := eq_neg_of_add_eq_zero_left ((mul_eq_zero.mp key).resolve_right hHD)
    refine ⟨-f, ?_⟩
    have hneg : qExpansion 1 ((-f : CuspForm (CongruenceSubgroup.Gamma0 N) (2 * ((m + 1 : ℕ) : ℤ))) : ℍ → ℂ) =
        -qExpansion 1 (f : ℍ → ℂ) := by
      rw [FunLike.coe_neg]
      exact ModularForm.qExpansion_neg one_pos h1 f
    show ((qExpansion 1 ((-f : CuspForm (CongruenceSubgroup.Gamma0 N) (2 * ((m + 1 : ℕ) : ℤ))) : ℍ → ℂ) : PowerSeries ℂ) :
      LaurentSeries ℂ) = X * T ^ (m + 1)
    rw [hneg, PowerSeries.coe_neg, ← hF, hF', neg_neg]

end
end S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral
end P2MW
export P2MW.S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral (N : ℕ) [NeZero N] (m : ℕ) (hm : 1 ≤ m)
    (X : LaurentSeries ℂ)
    (hX : X ∈ ModularCurve.laurentBaseChange ℂ (ModularCurve.modularFunctionFieldFull N)) (M : ℕ)
    (h₁ : IsIntegral (Algebra.adjoin ℂ ({ModularCurve.coeffEmb ℂ ModularCurve.jq} : Set (LaurentSeries ℂ)))
      (X ^ 6 * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ (4 * m) *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ (3 * m)))
    (h₂ : IsIntegral (Algebra.adjoin ℂ ({(ModularCurve.coeffEmb ℂ ModularCurve.jq)⁻¹} : Set (LaurentSeries ℂ)))
      (X ^ (2 * M) * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ (m * M + 1) *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ (m * M))) :
    ∃ f : CuspForm (CongruenceSubgroup.Gamma0 N) (2 * (m : ℤ)),
      HahnSeries.ofPowerSeries ℤ ℂ (UpperHalfPlane.qExpansion 1 f) =
        X * ModularCurve.thetaL ℂ (ModularCurve.coeffEmb ℂ ModularCurve.jq) ^ m := _root_.P2MW.S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_pow_of_isIntegral.solution N m hm X hX M h₁ h₂

end publicSection
