/-
Based on Prove2Me node WeierstrassCurve.j_mem_of_a_mem
(63242fe7-1a80-5296-b967-717644bfb1a0) by Claude (2026-09-05).

Proof based on Prove2Me submission 27068548-cb19-503d-8ad1-c4be8770a508
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Weierstrass

import Definitions.FLT.Def_P2M_Util

/-!
# The j-invariant lies in any subfield containing the aᵢ

Theorem statement: `WeierstrassCurve.j_mem_of_a_mem` (`63242fe7-1a80-5296-b967-717644bfb1a0`), by
Claude, 2026-09-05.

Proof: submission `27068548-cb19-503d-8ad1-c4be8770a508`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be a field and let $S$ be a type of subobjects of $F$ that are subfields, i.e. a `SetLike`
structure on $F$ satisfying `SubfieldClass`. Let $W$ be a Weierstrass curve over $F$, given by
coefficients $a_1, a_2, a_3, a_4, a_6$ and assumed elliptic (its discriminant is a unit, so that the
$j$-invariant $j = \Delta^{-1} c_4^3$ is defined). Let $K : S$ be such a subfield of $F$, and assume
the five membership hypotheses $a_1 \in K$, $a_2 \in K$, $a_3 \in K$, $a_4 \in K$ and $a_6 \in K$.
The conclusion is that $W.j \in K$. Because $S$ is an arbitrary `SubfieldClass`, the statement
applies simultaneously to `Subfield F` and to intermediate fields of an extension. Note the shape:
the curve itself remains a curve over $F$, and only its $j$-invariant is asserted to be a member of
the subset $K$; nothing is claimed about a model of $W$ over $K$.

This is the elementary rationality statement that $j(E) \in \mathbb{Q}(a_1,a_2,a_3,a_4,a_6)$, in
membership form rather than as a descent of the curve. It is used to show that the $j$-invariant of
a Vélu quotient lies in a prescribed subfield, via
[`WeierstrassCurve.veluQuotient_j_mem_of_mem`](thm.html#WeierstrassCurve.veluQuotient_j_mem_of_mem).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_j_mem_of_a_mem.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_j_mem_of_a_mem

open WeierstrassCurve in
theorem solution {F : Type*} [Field F] {S : Type*} [SetLike S F] [SubfieldClass S F]
    (W : WeierstrassCurve F) [W.IsElliptic] (K : S)
    (h₁ : W.a₁ ∈ K) (h₂ : W.a₂ ∈ K) (h₃ : W.a₃ ∈ K) (h₄ : W.a₄ ∈ K) (h₆ : W.a₆ ∈ K) : W.j ∈ K := by
  have hb₂ : W.b₂ ∈ K := by
    rw [b₂]; exact add_mem (pow_mem h₁ 2) (mul_mem (ofNat_mem K 4) h₂)
  have hb₄ : W.b₄ ∈ K := by
    rw [b₄]; exact add_mem (mul_mem (ofNat_mem K 2) h₄) (mul_mem h₁ h₃)
  have hb₆ : W.b₆ ∈ K := by
    rw [b₆]; exact add_mem (pow_mem h₃ 2) (mul_mem (ofNat_mem K 4) h₆)
  have hb₈ : W.b₈ ∈ K := by
    rw [b₈]
    exact sub_mem (add_mem (sub_mem (add_mem (mul_mem (pow_mem h₁ 2) h₆)
      (mul_mem (mul_mem (ofNat_mem K 4) h₂) h₆)) (mul_mem (mul_mem h₁ h₃) h₄))
      (mul_mem h₂ (pow_mem h₃ 2))) (pow_mem h₄ 2)
  have hc₄ : W.c₄ ∈ K := by
    rw [c₄]; exact sub_mem (pow_mem hb₂ 2) (mul_mem (ofNat_mem K 24) hb₄)
  have hΔ : W.Δ ∈ K := by
    rw [Δ]
    exact add_mem (sub_mem (sub_mem (mul_mem (neg_mem (pow_mem hb₂ 2)) hb₈)
      (mul_mem (ofNat_mem K 8) (pow_mem hb₄ 3))) (mul_mem (ofNat_mem K 27) (pow_mem hb₆ 2)))
      (mul_mem (mul_mem (mul_mem (ofNat_mem K 9) hb₂) hb₄) hb₆)
  rw [WeierstrassCurve.j]
  refine mul_mem ?_ (pow_mem hc₄ 3)
  rw [Units.val_inv_eq_inv_val, WeierstrassCurve.coe_Δ']
  exact inv_mem hΔ

end S_WeierstrassCurve_j_mem_of_a_mem
end P2MW
export P2MW.S_WeierstrassCurve_j_mem_of_a_mem (solution)

end privateSection

public section publicSection

theorem WeierstrassCurve.j_mem_of_a_mem {F : Type*} [Field F] {S : Type*} [SetLike S F] [SubfieldClass S F]
    (W : WeierstrassCurve F) [W.IsElliptic] (K : S)
    (h₁ : W.a₁ ∈ K) (h₂ : W.a₂ ∈ K) (h₃ : W.a₃ ∈ K) (h₄ : W.a₄ ∈ K) (h₆ : W.a₆ ∈ K) : W.j ∈ K := _root_.P2MW.S_WeierstrassCurve_j_mem_of_a_mem.solution W K h₁ h₂ h₃ h₄ h₆

end publicSection
