/-
Based on Prove2Me node ModularCurve.PhiGen.PhiGenDescends.intCoeffs
(ae0a893b-f12e-59f5-a601-8cf451da577a) by Claude (2026-09-05).

Proof based on Prove2Me submission b5b2f85b-7e0c-5ab0-abce-6c675d90775d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0
public import Definitions.FLT.Def_ModularCurve_PhiGen

import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.RingTheory.Polynomial.RationalRoot
import Definitions.FLT.Def_P2M_Util

/-!
# Integrality of the descended coefficients of Φ_ℓ

Theorem statement: `ModularCurve.PhiGen.PhiGenDescends.intCoeffs`
(`ae0a893b-f12e-59f5-a601-8cf451da577a`), by Claude, 2026-09-05.

Proof: submission `b5b2f85b-7e0c-5ab0-abce-6c675d90775d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field equipped with an algebra structure over $\mathbb{Q}$, let $\ell$ be a prime, let
$\zeta$ be a unit of $K$, and let $c \colon \mathbb{N} \to \mathrm{LaurentSeries}\,\mathbb{Q}$ be a
family of rational Laurent series. Assume `PhiGenDescends ℓ ζ c`, that is: for every $k$, the
coefficient of $X^k$ in the monic polynomial $\prod_{i \in \mathrm{Fin}(\ell+1)} (X -
\mathrm{conj}\,\ell\,\zeta\,i)$ over $\mathrm{LaurentSeries}\,K$ equals the image under `coeffEmb K`
(the coefficientwise application of $\mathbb{Q} \to K$) of `qExpand ℚ ℓ (c k)`, the Laurent series
obtained from $c_k$ by multiplying all exponents by $\ell$; here the $\ell+1$ series
$\mathrm{conj}\,\ell\,\zeta\,i$ are obtained from the coefficientwise image in $K$ of the series
`jq` by the substitution `cosetSubst` attached to $\zeta$ and to the data `cosetA ℓ i`, `cosetB ℓ
i`. Assume further that $\zeta^\ell = 1$. Then for every $k$ the series $c_k$ satisfies `IntCoeffs`:
for each $m \in \mathbb{Z}$ there is an integer $z$ with $c_k$'s coefficient in degree $m$ equal to
the image of $z$ in $\mathbb{Q}$.

This is the integrality of the coefficients of the modular equation of prime level $\ell$: the
elementary symmetric functions of the $\ell+1$ conjugates of the $q$-expansion of $j$ descend to
Laurent series with integral coefficients. It feeds the construction of the modular polynomial data
for $X_0(\ell)$, being used in
[`ModularCurve.ModularPolynomialData.weighted_support_le`](thm.html#ModularCurve.ModularPolynomialData.weighted_support_le),
[`ModularCurve.PhiGen.splits_of_prime`](thm.html#ModularCurve.PhiGen.splits_of_prime) and
[`ModularCurve.exists_modularPolynomialData_evalSymm`](thm.html#ModularCurve.exists_modularPolynomialData_evalSymm).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs

noncomputable section

open Polynomial

namespace ModularCurve
p2m_export "ModularCurve" "qExpand qExpand_coeff_mul qExpand_coeff_of_not_dvd jNum jNumQ jq ofPowerSeries_coeff_of_neg jq_pow qTwist qTwist_coeff PhiGen.PhiGenDescends coeffEmb coeffEmb_coeff"
p2m_open "ModularCurve"

namespace PhiGen
p2m_export "ModularCurve.PhiGen" "conj conj_zero conj_succ phiProd IntCoeffs PhiGenDescends"
p2m_open "ModularCurve.PhiGen"

section JqIntegrality

private theorem intCoeffs_jq_pow (n : ℕ) : IntCoeffs (jq ^ n) := by
  intro m
  rw [jq_pow, HahnSeries.coeff_single_mul, one_mul]
  by_cases hneg : (m - -(n : ℤ)) < 0
  · exact ⟨0, by rw [ofPowerSeries_coeff_of_neg _ hneg, Int.cast_zero]⟩
  · refine ⟨(PowerSeries.coeff (m - -(n : ℤ)).toNat (jNum ^ n) : ℤ), ?_⟩
    have hcast : (m - -(n : ℤ)) = (((m - -(n : ℤ)).toNat : ℕ) : ℤ) :=
      (Int.toNat_of_nonneg (not_lt.mp hneg)).symm
    rw [hcast, HahnSeries.ofPowerSeries_apply_coeff]
    show PowerSeries.coeff _ (jNumQ ^ n) = _
    rw [jNumQ, ← map_pow, PowerSeries.coeff_map]
    rfl

private theorem intCoeffs_jq : IntCoeffs jq := by
  have h := intCoeffs_jq_pow 1
  rwa [pow_one] at h

end JqIntegrality

section IntegralCoeffs

variable {K : Type*} [Field K]

private def CoeffsIntegral (f : LaurentSeries K) : Prop :=
  ∀ m : ℤ, f.coeff m ∈ integralClosure ℤ K

private theorem coeffsIntegral_zero : CoeffsIntegral (0 : LaurentSeries K) := fun _ =>
  Subalgebra.zero_mem _

private theorem coeffsIntegral_one : CoeffsIntegral (1 : LaurentSeries K) := by
  intro m
  rw [HahnSeries.coeff_one]
  split
  · exact Subalgebra.one_mem _
  · exact Subalgebra.zero_mem _

private theorem CoeffsIntegral.neg {f : LaurentSeries K} (hf : CoeffsIntegral f) :
    CoeffsIntegral (-f) := by
  intro m
  rw [HahnSeries.coeff_neg]
  exact Subalgebra.neg_mem _ (hf m)

private theorem CoeffsIntegral.mul {f g : LaurentSeries K} (hf : CoeffsIntegral f)
    (hg : CoeffsIntegral g) : CoeffsIntegral (f * g) := by
  intro m
  rw [HahnSeries.coeff_mul]
  exact Subalgebra.sum_mem _ fun ij _ => Subalgebra.mul_mem _ (hf ij.1) (hg ij.2)

private theorem CoeffsIntegral.qExpand {f : LaurentSeries K} (hf : CoeffsIntegral f)
    (N : ℕ) [NeZero N] : CoeffsIntegral (ModularCurve.qExpand K N f) := by
  intro m
  by_cases hdvd : (N : ℤ) ∣ m
  · obtain ⟨c, rfl⟩ := hdvd
    rw [qExpand_coeff_mul]
    exact hf c
  · rw [qExpand_coeff_of_not_dvd N f hdvd]
    exact Subalgebra.zero_mem _

private theorem CoeffsIntegral.qTwist {f : LaurentSeries K} (hf : CoeffsIntegral f)
    (u : Kˣ) (hu : ∀ m : ℤ, ((u ^ m : Kˣ) : K) ∈ integralClosure ℤ K) :
    CoeffsIntegral (ModularCurve.qTwist u f) := by
  intro m
  rw [qTwist_coeff]
  exact Subalgebra.mul_mem _ (hu m) (hf m)

private theorem intCast_mem_integralClosure (z : ℤ) : (z : K) ∈ integralClosure ℤ K := by
  rw [mem_integralClosure_iff]
  refine ⟨Polynomial.X - Polynomial.C z, Polynomial.monic_X_sub_C z, ?_⟩
  simp

private theorem val_mem_integralClosure_of_pow_eq_one {u : Kˣ} {n : ℕ} (hn : n ≠ 0)
    (hu : u ^ n = 1) : (u : K) ∈ integralClosure ℤ K := by
  rw [mem_integralClosure_iff]
  refine ⟨Polynomial.X ^ n - Polynomial.C 1, Polynomial.monic_X_pow_sub_C 1 hn, ?_⟩
  have hval : (u : K) ^ n = 1 := by
    rw [← Units.val_pow_eq_pow_val, hu, Units.val_one]
  simp [hval]

private theorem zpow_val_mem_integralClosure_of_pow_eq_one {u : Kˣ} {n : ℕ} (hn : n ≠ 0)
    (hu : u ^ n = 1) (m : ℤ) : ((u ^ m : Kˣ) : K) ∈ integralClosure ℤ K := by
  have hrw : u ^ m = u ^ (m % (n : ℤ)).toNat := by
    have h1 : u ^ m = u ^ (m % (n : ℤ)) := by
      conv_lhs => rw [← Int.emod_add_mul_ediv m (n : ℤ)]
      rw [zpow_add, zpow_mul, zpow_natCast, hu, one_zpow, mul_one]
    rw [h1, ← zpow_natCast,
      Int.toNat_of_nonneg (Int.emod_nonneg m (by exact_mod_cast hn))]
  rw [hrw, Units.val_pow_eq_pow_val]
  exact Subalgebra.pow_mem _ (val_mem_integralClosure_of_pow_eq_one hn hu) _

private theorem coeffsIntegral_coeff_X_sub_C {a : LaurentSeries K}
    (ha : CoeffsIntegral a) (k : ℕ) :
    CoeffsIntegral ((Polynomial.X - Polynomial.C a).coeff k) := by
  match k with
  | 0 =>
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X_zero, Polynomial.coeff_C_zero,
      zero_sub]
    exact CoeffsIntegral.neg ha
  | 1 =>
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X_one, Polynomial.coeff_C,
      ite_eq_right (one_ne_zero), sub_zero]
    exact coeffsIntegral_one
  | (k + 2) =>
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X, Polynomial.coeff_C]
    rw [ite_eq_right (by omega), ite_eq_right (by omega), sub_zero]
    exact coeffsIntegral_zero

private theorem coeffsIntegral_coeff_mul {p q : Polynomial (LaurentSeries K)}
    (hp : ∀ k, CoeffsIntegral (p.coeff k)) (hq : ∀ k, CoeffsIntegral (q.coeff k))
    (k : ℕ) : CoeffsIntegral ((p * q).coeff k) := by
  rw [Polynomial.coeff_mul]
  intro a
  rw [HahnSeries.coeff_sum]
  exact Subalgebra.sum_mem _ fun ij _ => CoeffsIntegral.mul (hp ij.1) (hq ij.2) a

private theorem coeffsIntegral_coeff_prod {ι : Type*} (s : Finset ι)
    (p : ι → Polynomial (LaurentSeries K))
    (hp : ∀ i ∈ s, ∀ k, CoeffsIntegral ((p i).coeff k)) :
    ∀ k, CoeffsIntegral ((∏ i ∈ s, p i).coeff k) := by
  induction s using Finset.cons_induction with
  | empty =>
    intro k
    simp only [Finset.prod_empty]
    rcases Nat.eq_zero_or_pos k with rfl | hk
    · simpa using coeffsIntegral_one
    · rw [Polynomial.coeff_one, ite_eq_right (by omega)]
      exact coeffsIntegral_zero
  | cons a s _ha ih =>
    intro k
    rw [Finset.prod_cons]
    exact coeffsIntegral_coeff_mul (hp a (Finset.mem_cons_self a s))
      (ih fun i hi k => hp i (Finset.mem_cons_of_mem hi) k) k

end IntegralCoeffs

section ConjIntegral

variable {K : Type*} [Field K] [Algebra ℚ K]

private theorem coeffsIntegral_jqK : CoeffsIntegral (coeffEmb K jq) := by
  intro m
  obtain ⟨z, hz⟩ := intCoeffs_jq m
  rw [coeffEmb_coeff, hz, map_intCast]
  exact intCast_mem_integralClosure z

variable (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : Kˣ)

private theorem coeffsIntegral_conj (hζ1 : ζ ^ ℓ = 1) (i : Fin (ℓ + 1)) :
    CoeffsIntegral (conj ℓ ζ i) := by
  induction i using Fin.cases with
  | zero =>
    rw [conj_zero]
    exact CoeffsIntegral.qExpand coeffsIntegral_jqK (ℓ * ℓ)
  | succ b =>
    rw [conj_succ]
    refine CoeffsIntegral.qTwist coeffsIntegral_jqK _ fun m => ?_
    refine zpow_val_mem_integralClosure_of_pow_eq_one hℓ.out.ne_zero ?_ m
    rw [← pow_mul, mul_comm (b : ℕ) ℓ, pow_mul, hζ1, one_pow]

variable {ℓ ζ}

private theorem coeffsIntegral_phiProd_coeff (hζ1 : ζ ^ ℓ = 1) (k : ℕ) :
    CoeffsIntegral ((phiProd ℓ (conj ℓ ζ)).coeff k) := by
  rw [phiProd]
  exact coeffsIntegral_coeff_prod Finset.univ _
    (fun i _ k => coeffsIntegral_coeff_X_sub_C (coeffsIntegral_conj ℓ ζ hζ1 i) k) k

end ConjIntegral

section IntegralityDescent

variable {K : Type*} [Field K] [Algebra ℚ K]

private theorem exists_intCast_eq_of_mem {q : ℚ}
    (h : algebraMap ℚ K q ∈ integralClosure ℤ K) : ∃ z : ℤ, q = (z : ℚ) := by
  rw [mem_integralClosure_iff] at h
  obtain ⟨P, hPmonic, hPeval⟩ := h
  have hcomp : algebraMap ℤ K = (algebraMap ℚ K).comp (Int.castRingHom ℚ) :=
    Subsingleton.elim _ _
  rw [hcomp, ← Polynomial.hom_eval₂] at hPeval
  have h0 : Polynomial.eval₂ (Int.castRingHom ℚ) q P = 0 :=
    FaithfulSMul.algebraMap_injective ℚ K (by rw [hPeval, map_zero])
  have hint : IsIntegral ℤ q :=
    ⟨P, hPmonic, by
      rwa [show algebraMap ℤ ℚ = Int.castRingHom ℚ from Subsingleton.elim _ _]⟩
  obtain ⟨z, hz⟩ := IsIntegrallyClosed.isIntegral_iff.mp hint
  exact ⟨z, by rw [← hz]; simp⟩

variable {ℓ : ℕ} [hℓ : Fact (Nat.Prime ℓ)] {ζ : Kˣ} {c : ℕ → LaurentSeries ℚ}

private theorem PhiGenDescends.intCoeffs (hc : PhiGenDescends ℓ ζ c) (hζ1 : ζ ^ ℓ = 1) (k : ℕ) :
    IntCoeffs (c k) := by
  intro m
  have h1 : algebraMap ℚ K ((c k).coeff m)
      = ((phiProd ℓ (conj ℓ ζ)).coeff k).coeff ((ℓ : ℤ) * m) := by
    rw [hc k, coeffEmb_coeff, qExpand_coeff_mul]
  have h2 := coeffsIntegral_phiProd_coeff hζ1 k ((ℓ : ℤ) * m)
  rw [← h1] at h2
  exact exists_intCast_eq_of_mem h2

end IntegralityDescent

end PhiGen

end ModularCurve

end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs.ModularCurve _root_.ModularCurve.PhiGen _root_.P2MW.S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs.ModularCurve.PhiGen in

theorem solution {K : Type*} [Field K] [Algebra ℚ K] {ℓ : ℕ} [hℓ : Fact (Nat.Prime ℓ)] {ζ : Kˣ} {c : ℕ → LaurentSeries ℚ} (hc : PhiGenDescends ℓ ζ c) (hζ1 : ζ ^ ℓ = 1) (k : ℕ) : IntCoeffs (c k) :=
  ModularCurve.PhiGen.PhiGenDescends.intCoeffs hc hζ1 k

end S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs
end P2MW
export P2MW.S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve ModularCurve.PhiGen
theorem ModularCurve.PhiGen.PhiGenDescends.intCoeffs {K : Type*} [Field K] [Algebra ℚ K] {ℓ : ℕ} [hℓ : Fact (Nat.Prime ℓ)] {ζ : Kˣ} {c : ℕ → LaurentSeries ℚ} (hc : PhiGenDescends ℓ ζ c) (hζ1 : ζ ^ ℓ = 1) (k : ℕ) : IntCoeffs (c k) := _root_.P2MW.S_ModularCurve_PhiGen_PhiGenDescends_intCoeffs.solution hc hζ1 k

end publicSection
