/-
Based on Prove2Me node ModularCurve.discriminant_div_discriminant_heckeDiagMatrix_smul
(93e2ea46-9411-5e7f-8098-309280a7ef5c) by Claude (2026-09-05).

Proof based on Prove2Me submission 770d0625-92a8-5cd1-b933-e875da2cf6a9
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
public import Mathlib.NumberTheory.ModularForms.Discriminant
public import Definitions.FLT.Def_ModularForm_HeckeOperator

import Theorems.FLT.Thm_ModularCurve_exists_sl2_heckeDiagMatrix_smul_eq
import Definitions.FLT.Def_P2M_Util

/-!
# Γ₀(N)-invariance of Δ(τ)/Δ(Nτ)

Theorem statement: `ModularCurve.discriminant_div_discriminant_heckeDiagMatrix_smul`
(`93e2ea46-9411-5e7f-8098-309280a7ef5c`), by Claude, 2026-09-05.

Proof: submission `770d0625-92a8-5cd1-b933-e875da2cf6a9`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number with $N \neq 0$, let $\gamma$ be an element of
$\mathrm{SL}_2(\mathbb{Z})$ lying in the congruence subgroup $\Gamma_0(N)$, and let $\tau$ be a
point of the upper half-plane. Write $\Delta$ for Mathlib's `ModularForm.discriminant`, the
holomorphic function on the upper half-plane underlying the weight-$12$ cusp form for
$\mathrm{SL}_2(\mathbb{Z})$, and write $\mathrm{heckeDiagMatrix}\ N$ for the element of
$\mathrm{GL}_2(\mathbb{R})$ which, since $N \neq 0$, is the upper triangular matrix
$\bigl(\begin{smallmatrix} N & 0 \\ 0 & 1\end{smallmatrix}\bigr)$ (of nonzero determinant $N$), so
that its action on the upper half-plane sends $\tau$ to $N\tau$. The assertion is the equality of
quotients of complex numbers
$$\frac{\Delta(\gamma \cdot \tau)}{\Delta(N\,(\gamma\cdot\tau))} \;=\;
\frac{\Delta(\tau)}{\Delta(N\tau)},$$
where $\gamma$ acts through the usual fractional linear action of $\mathrm{SL}_2(\mathbb{Z})$ on the
upper half-plane. Thus the function $\tau \mapsto \Delta(\tau)/\Delta(N\tau)$ is invariant under
$\Gamma_0(N)$, pointwise in $\tau$.

This is the analytic invariance of the classical modular unit $u_N(\tau) =
\Delta(\tau)/\Delta(N\tau) = (\eta(\tau)/\eta(N\tau))^{24}$, a nowhere-vanishing holomorphic
function on the upper half-plane whose $\Gamma_0(N)$-invariance makes it a function on the modular
curve $X_0(N)$ away from the cusps. It is used downstream in the construction and $q$-expansion
analysis of this unit and of the associated series, for instance in the study of its behaviour under
the Fricke involution and in the integrality statements over $\mathbb{Q}[j]$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_discriminant_div_discriminant_heckeDiagMatrix_smul.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_discriminant_div_discriminant_heckeDiagMatrix_smul

noncomputable section

open UpperHalfPlane Matrix.SpecialLinearGroup
open scoped MatrixGroups ModularForm

namespace ModularCurve
p2m_export "ModularCurve" "exists_sl2_heckeDiagMatrix_smul_eq"
p2m_open "ModularCurve"

namespace QexpN

theorem discriminant_div_discriminant_heckeDiagMatrix_smul' (N : ℕ) [NeZero N]
    (γ : Matrix.SpecialLinearGroup (Fin 2) ℤ) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N)
    (τ : UpperHalfPlane) :
    ModularForm.discriminant (γ • τ)
        / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • γ • τ)
      = ModularForm.discriminant τ
        / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ) := by
  obtain ⟨γ', hact, hden⟩ := ModularCurve.exists_sl2_heckeDiagMatrix_smul_eq N γ hγ
  have hγSL : (mapGL ℝ γ : GL (Fin 2) ℝ) ∈ 𝒮ℒ := ⟨γ, rfl⟩
  have hγ'SL : (mapGL ℝ γ' : GL (Fin 2) ℝ) ∈ 𝒮ℒ := ⟨γ', rfl⟩
  have hΔγ : ModularForm.discriminant (γ • τ)
      = UpperHalfPlane.denom (γ : Matrix.GeneralLinearGroup (Fin 2) ℝ) (τ : ℂ) ^ (12 : ℤ)
        * ModularForm.discriminant τ := by
    have h := SlashInvariantForm.slash_action_eqn'' CuspForm.discriminant hγSL τ
    simp [CuspForm.coe_discriminant] at h
    exact h
  have hΔγ' : ModularForm.discriminant (γ' • ModularForm.heckeDiagMatrix N • τ)
      = UpperHalfPlane.denom (γ' : Matrix.GeneralLinearGroup (Fin 2) ℝ)
          (((ModularForm.heckeDiagMatrix N • τ : UpperHalfPlane)) : ℂ) ^ (12 : ℤ)
        * ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ) := by
    have h := SlashInvariantForm.slash_action_eqn'' CuspForm.discriminant hγ'SL
        (ModularForm.heckeDiagMatrix N • τ)
    simp [CuspForm.coe_discriminant] at h
    exact h
  rw [hact τ, hΔγ, hΔγ', hden τ,
    mul_div_mul_left _ _ (zpow_ne_zero 12 (UpperHalfPlane.denom_ne_zero _ _))]

end QexpN

end ModularCurve

end

theorem solution (N : ℕ) [NeZero N] (γ : Matrix.SpecialLinearGroup (Fin 2) ℤ) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N) (τ : UpperHalfPlane) : ModularForm.discriminant (γ • τ) / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • γ • τ) = ModularForm.discriminant τ / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ) :=
  ModularCurve.QexpN.discriminant_div_discriminant_heckeDiagMatrix_smul' N γ hγ τ

end S_ModularCurve_discriminant_div_discriminant_heckeDiagMatrix_smul
end P2MW
export P2MW.S_ModularCurve_discriminant_div_discriminant_heckeDiagMatrix_smul (solution)

end privateSection

public section publicSection

theorem ModularCurve.discriminant_div_discriminant_heckeDiagMatrix_smul (N : ℕ) [NeZero N] (γ : Matrix.SpecialLinearGroup (Fin 2) ℤ) (hγ : γ ∈ CongruenceSubgroup.Gamma0 N) (τ : UpperHalfPlane) : ModularForm.discriminant (γ • τ) / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • γ • τ) = ModularForm.discriminant τ / ModularForm.discriminant (ModularForm.heckeDiagMatrix N • τ) := _root_.P2MW.S_ModularCurve_discriminant_div_discriminant_heckeDiagMatrix_smul.solution N γ hγ τ

end publicSection
