/-
Based on Prove2Me node FrobeniusEndo.det_frobPencilEnd_eq_zero_iff_dvd_kerDeg
(a3aa1ea4-c840-55bc-ab5b-e662f9e8a3cc) by Claude (2026-09-05).

Proof based on Prove2Me submission 06de0199-abd1-5669-8f61-5717b335730b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_EllipticCurve_FrobeniusEndo
public import Mathlib.LinearAlgebra.Determinant

import Mathlib.GroupTheory.Perm.Cycle.Type
import Theorems.FLT.Thm_FrobeniusEndo_dvd_kerDeg_of_det_frobPencilEnd_eq_zero
import Definitions.FLT.Def_P2M_Util

/-!
# Vanishing of det(̄ m-̄ nσ) on p-torsion versus p∣#ker

Theorem statement: `FrobeniusEndo.det_frobPencilEnd_eq_zero_iff_dvd_kerDeg`
(`a3aa1ea4-c840-55bc-ab5b-e662f9e8a3cc`), by Claude, 2026-09-05.

Proof: submission `06de0199-abd1-5669-8f61-5717b335730b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$, $S$ be commutative rings and $K$ a field, with algebra structures making $R\to S\to K$ a
scalar tower, let $W$ be a Weierstrass curve over $R$, let $\sigma$ be an $S$-algebra automorphism
of $K$, and let $p$ be a prime. Write $(W\!\downharpoonright\!K)$ for the base change of $W$ to $K$
and $(W\!\downharpoonright\!K).\mathrm{Point}$ for its group of $K$-points; $\sigma$ acts on this
group, and `frobEnd W σ` is the resulting additive endomorphism. For integers $m,n$, `kerDeg
(frobEnd W σ) m n` is the cardinality (in the sense of `Nat.card`, hence $0$ for an infinite set) of
the kernel of the additive endomorphism $m\cdot\mathrm{id}-n\cdot\sigma$ of
$(W\!\downharpoonright\!K).\mathrm{Point}$, and `frobPencilEnd W σ p m n` is the
$\mathbb{Z}/p$-linear endomorphism $\bar m\cdot 1-\bar n\cdot\rho(\sigma)$ of the $p$-torsion
submodule $\{P: p\cdot P=0\}$, where $\rho(\sigma)$ is the endomorphism induced by the action of
$\sigma$. Assume the $p$-torsion submodule has nonzero `Nat.card` (i.e. is finite) and that
$\mathrm{kerDeg}(\mathrm{frobEnd}\ W\ \sigma)\ m\ n\neq 0$. Then $\det(\bar m\cdot1-\bar
n\cdot\rho(\sigma))=0$ if and only if $p$ divides $\mathrm{kerDeg}(\mathrm{frobEnd}\ W\ \sigma)\ m\
n$.

This is the dictionary between the kernel counts $\#\ker(m-n\sigma)$ on $K$-points and the
eigenvalues of $\sigma$ on the $p$-torsion: $\bar m/\bar n$ is an eigenvalue of the mod $p$ Galois
representation exactly when $p$ divides the kernel count. It is used in the computation of the trace
and determinant of Frobenius on $p$-torsion from kernel degrees, via
[`FrobeniusEndo.trace_det_frob_of_line_of_isotropic`](thm.html#FrobeniusEndo.trace_det_frob_of_line_of_isotropic).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_FrobeniusEndo_det_frobPencilEnd_eq_zero_iff_dvd_kerDeg.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_FrobeniusEndo_det_frobPencilEnd_eq_zero_iff_dvd_kerDeg

p2m_open "WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point FrobeniusEndo P2MW.S_FrobeniusEndo_det_frobPencilEnd_eq_zero_iff_dvd_kerDeg.FrobeniusEndo"

namespace FrobeniusEndo
p2m_export "FrobeniusEndo" "linePencil linePencil_apply kerDeg kerDeg_def frobEnd frobEnd_apply frobPencilEnd dvd_kerDeg_of_det_frobPencilEnd_eq_zero"
p2m_open "FrobeniusEndo"

section Pencil

variable {R : Type*} {S : Type*} {K : Type*} [CommRing R] [CommRing S] [Field K] [DecidableEq K]
  [Algebra R S] [Algebra R K] [Algebra S K] [IsScalarTower R S K]
  (W : WeierstrassCurve R) (σ : K ≃ₐ[S] K) (p : ℕ)

lemma coe_galois_smul_torsionBy (x : Submodule.torsionBy ℤ (W⁄K).Point p) :
    ((σ • x : Submodule.torsionBy ℤ (W⁄K).Point p) : (W⁄K).Point) = σ • (x : (W⁄K).Point) :=
  rfl

lemma coe_frobPencilEnd_apply (m n : ℤ) (x : Submodule.torsionBy ℤ (W⁄K).Point p) :
    ((frobPencilEnd W σ p m n x : Submodule.torsionBy ℤ (W⁄K).Point p) : (W⁄K).Point)
      = linePencil (frobEnd W σ) m n x := by
  simp only [LinearMap.sub_apply, LinearMap.smul_apply, Module.End.one_apply, linePencil_apply,
    frobEnd_apply, Int.cast_smul_eq_zsmul, Submodule.coe_sub, Submodule.coe_smul_of_tower]
  rfl

lemma frobPencilEnd_eq_zero_iff (m n : ℤ) (x : Submodule.torsionBy ℤ (W⁄K).Point p) :
    frobPencilEnd W σ p m n x = 0 ↔ (x : (W⁄K).Point) ∈ (linePencil (frobEnd W σ) m n).ker := by
  rw [AddMonoidHom.mem_ker, ← coe_frobPencilEnd_apply, ZeroMemClass.coe_eq_zero]

lemma frobPencilEnd_natCast_one (m : ℕ) :
    frobPencilEnd W σ p (m : ℤ) 1
      = (m : ZMod p) • (1 : Module.End (ZMod p) (Submodule.torsionBy ℤ (W⁄K).Point p))
          - galoisRepModuleEnd S W p σ := by
  simp only [frobPencilEnd, Int.cast_natCast, Int.cast_one, one_smul]

end Pencil

section Dictionary

variable {R : Type*} {S : Type*} {K : Type*} [CommRing R] [CommRing S] [Field K] [DecidableEq K]
  [Algebra R S] [Algebra R K] [Algebra S K] [IsScalarTower R S K]
  (W : WeierstrassCurve R) (σ : K ≃ₐ[S] K) (p : ℕ) [Fact p.Prime]

theorem det_eq_zero_of_dvd_kerDeg [Finite (Submodule.torsionBy ℤ (W⁄K).Point p)] {m n : ℤ}
    (hpos : kerDeg (frobEnd W σ) m n ≠ 0) (hdvd : p ∣ kerDeg (frobEnd W σ) m n) :
    LinearMap.det (frobPencilEnd W σ p m n) = 0 := by

  have hfin : Finite ((linePencil (frobEnd W σ) m n).ker) := Nat.finite_of_card_ne_zero hpos
  have : Fintype ((linePencil (frobEnd W σ) m n).ker) := Fintype.ofFinite _
  have hdvd' : p ∣ Fintype.card ((linePencil (frobEnd W σ) m n).ker) := by
    rwa [kerDeg_def, Nat.card_eq_fintype_card] at hdvd
  obtain ⟨y, hyord⟩ := exists_prime_addOrderOf_dvd_card p hdvd'

  have hyp : p • (y : (W⁄K).Point) = 0 := by
    have h1 : p • y = 0 := by
      rw [← hyord]
      exact addOrderOf_nsmul_eq_zero y
    exact congrArg Subtype.val h1
  have hy0 : (y : (W⁄K).Point) ≠ 0 := by
    intro h0
    have hy0' : y = 0 := Subtype.ext h0
    rw [hy0', addOrderOf_zero] at hyord
    exact (Fact.out : p.Prime).ne_one hyord.symm

  rw [LinearMap.det_eq_zero_iff_ker_ne_bot, Submodule.ne_bot_iff]
  refine ⟨⟨(y : (W⁄K).Point), ?_⟩, ?_, ?_⟩
  · rw [Submodule.mem_torsionBy_iff, Nat.cast_smul_eq_nsmul]
    exact hyp
  · rw [LinearMap.mem_ker, frobPencilEnd_eq_zero_iff]
    exact y.2
  · intro h0
    exact hy0 (congrArg Subtype.val h0)

end Dictionary

end FrobeniusEndo

theorem solution {R : Type*} {S : Type*} {K : Type*} [CommRing R] [CommRing S] [Field K] [DecidableEq K] [Algebra R S] [Algebra R K] [Algebra S K] [IsScalarTower R S K] (W : WeierstrassCurve R) (σ : K ≃ₐ[S] K) (p : ℕ) [Fact p.Prime] (hfin : Nat.card (Submodule.torsionBy ℤ (W⁄K).Point p) ≠ 0) {m n : ℤ} (hpos : kerDeg (frobEnd W σ) m n ≠ 0) : LinearMap.det (frobPencilEnd W σ p m n) = 0 ↔ p ∣ kerDeg (frobEnd W σ) m n :=
  haveI : Finite (Submodule.torsionBy ℤ (W⁄K).Point p) := Nat.finite_of_card_ne_zero hfin
  ⟨FrobeniusEndo.dvd_kerDeg_of_det_frobPencilEnd_eq_zero W σ p,
    FrobeniusEndo.det_eq_zero_of_dvd_kerDeg W σ p hpos⟩

end S_FrobeniusEndo_det_frobPencilEnd_eq_zero_iff_dvd_kerDeg
end P2MW
export P2MW.S_FrobeniusEndo_det_frobPencilEnd_eq_zero_iff_dvd_kerDeg (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point FrobeniusEndo

theorem FrobeniusEndo.det_frobPencilEnd_eq_zero_iff_dvd_kerDeg {R : Type*} {S : Type*} {K : Type*} [CommRing R] [CommRing S] [Field K] [DecidableEq K] [Algebra R S] [Algebra R K] [Algebra S K] [IsScalarTower R S K] (W : WeierstrassCurve R) (σ : K ≃ₐ[S] K) (p : ℕ) [Fact p.Prime] (hfin : Nat.card (Submodule.torsionBy ℤ (W⁄K).Point p) ≠ 0) {m n : ℤ} (hpos : kerDeg (frobEnd W σ) m n ≠ 0) : LinearMap.det (frobPencilEnd W σ p m n) = 0 ↔ p ∣ kerDeg (frobEnd W σ) m n := _root_.P2MW.S_FrobeniusEndo_det_frobPencilEnd_eq_zero_iff_dvd_kerDeg.solution W σ p hfin hpos

end publicSection
