/-
Based on Prove2Me node Field.nonempty_ringHom_complex_of_countable
(b0d9247e-2403-5333-8974-53b3fcd60c6b) by Claude (2026-09-05).

Proof based on Prove2Me submission 49ffa1c1-9056-5743-88c2-7a71f441c292
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Basic.Complex.Basic
public import Mathlib.Basic.Countable.Defs

import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.FieldTheory.IsAlgClosed.Classification
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.SimpleRing.Principal
import Definitions.FLT.Def_P2M_Util

/-!
# Countable fields of characteristic zero embed into ℂ

Theorem statement: `Field.nonempty_ringHom_complex_of_countable`
(`b0d9247e-2403-5333-8974-53b3fcd60c6b`), by Claude, 2026-09-05.

Proof: submission `49ffa1c1-9056-5743-88c2-7a71f441c292`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a type in an arbitrary universe, equipped with a field structure, of characteristic zero,
and countable (in the sense that its underlying type admits an injection into $\mathbb{N}$, i.e. is
finite or countably infinite). The assertion is that the type $K \to+^* \mathbb{C}$ of ring
homomorphisms from $K$ to the field of complex numbers is nonempty: there exists at least one ring
homomorphism $K \to \mathbb{C}$. Since $K$ is a field, any such homomorphism is automatically
injective, so the conclusion is an embedding of $K$ as a subfield of $\mathbb{C}$; the statement
itself, however, asserts only the existence of a ring homomorphism, with no further properties and
no compatibility with prescribed data. Note that the conclusion is a statement of nonemptiness (a
`Prop`), not a chosen map, and that the universe of $K$ is unrestricted, so the cardinality
comparison involved is a cross-universe one.

This is the set-theoretic half of the Lefschetz principle for countable fields of characteristic
zero. It is used to transfer a statement about $j$-invariants and modular polynomials from an
arbitrary countable characteristic-zero base field to $\mathbb{C}$, in the proof of
[`WeierstrassCurve.Affine.eval_modularPolynomial_map_j_eq_zero_of_isAddCyclic_ker_pointMapOfPushforward`](thm.html#WeierstrassCurve.Affine.eval_modularPolynomial_map_j_eq_zero_of_isAddCyclic_ker_pointMapOfPushforward).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_Field_nonempty_ringHom_complex_of_countable.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_Field_nonempty_ringHom_complex_of_countable

open Cardinal

universe u

theorem solution
    (K : Type u) [Field K] [CharZero K] [Countable K] : Nonempty (K →+* ℂ) := by
  classical
  have : FaithfulSMul ℚ K :=
    (faithfulSMul_iff_algebraMap_injective ℚ K).2 (algebraMap ℚ K).injective
  have : FaithfulSMul ℚ ℂ :=
    (faithfulSMul_iff_algebraMap_injective ℚ ℂ).2 (algebraMap ℚ ℂ).injective
  obtain ⟨s, hs⟩ := exists_isTranscendenceBasis ℚ K
  obtain ⟨t, ht⟩ := exists_isTranscendenceBasis ℚ ℂ
  have hct : #ℂ = #t :=
    IsAlgClosed.cardinal_eq_cardinal_transcendence_basis_of_aleph0_lt' (R := ℚ) _ ht
      mk_le_aleph0 (by rw [mk_complex]; exact aleph0_lt_continuum)
  have h1 : Cardinal.lift.{0} #s ≤ Cardinal.lift.{u} #t := by
    rw [← hct, mk_complex, lift_continuum]
    calc Cardinal.lift.{0} #s ≤ Cardinal.lift.{0} ℵ₀ := lift_le.2 mk_le_aleph0
      _ = ℵ₀ := lift_aleph0
      _ ≤ 𝔠 := aleph0_le_continuum
  obtain ⟨e⟩ := Cardinal.lift_mk_le'.1 h1
  have hind : AlgebraicIndependent ℚ (fun i : s => ((e i : t) : ℂ)) :=
    ht.1.comp e e.injective
  set A := Algebra.adjoin ℚ (Set.range ((↑) : s → K)) with hA
  let g : A →ₐ[ℚ] ℂ :=
    (MvPolynomial.aeval (fun i : s => ((e i : t) : ℂ))).comp hs.1.aevalEquiv.symm.toAlgHom
  have hg : Function.Injective g :=
    (algebraicIndependent_iff_injective_aeval.1 hind).comp hs.1.aevalEquiv.symm.injective
  have : Algebra.IsAlgebraic A K := hs.isAlgebraic
  let : Algebra A ℂ := g.toRingHom.toAlgebra
  have : Module.IsTorsionFree A ℂ :=
    Module.isTorsionFree_iff_algebraMap_injective.mpr hg
  have : Module.IsTorsionFree A K :=
    Module.isTorsionFree_iff_algebraMap_injective.mpr Subtype.val_injective
  exact ⟨(IsAlgClosed.lift (R := A) (S := K) (M := ℂ)).toRingHom⟩

end S_Field_nonempty_ringHom_complex_of_countable
end P2MW
export P2MW.S_Field_nonempty_ringHom_complex_of_countable (solution)

end privateSection

public section publicSection


universe u
theorem Field.nonempty_ringHom_complex_of_countable
    (K : Type u) [Field K] [CharZero K] [Countable K] : Nonempty (K →+* ℂ) := _root_.P2MW.S_Field_nonempty_ringHom_complex_of_countable.solution K

end publicSection
