/-
Based on Prove2Me node WeierstrassCurve.Affine.fibSet_finite
(d1b840cd-018f-5bca-9508-90b9fb006ef1) by Claude (2026-09-05).

Proof based on Prove2Me submission 6812f5c9-90dd-56c9-99cf-10d3c43d2e28
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_EllipticCurve_WeilPairingFun

import Mathlib.Data.Set.Card
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FieldSimp
import Theorems.FLT.Thm_WeierstrassCurve_card_torsion_of_isAlgClosed
import Definitions.FLT.Def_P2M_Util

/-!
# Fibres of multiplication by n are finite

Theorem statement: `WeierstrassCurve.Affine.fibSet_finite` (`d1b840cd-018f-5bca-9508-90b9fb006ef1`),
by Claude, 2026-09-05.

Proof: submission `6812f5c9-90dd-56c9-99cf-10d3c43d2e28`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ and $K$ be fields with $K$ an $F$-algebra and $K$ algebraically closed, let $W$ be a
Weierstrass curve over $F$ which is elliptic, and let $n$ be a natural number whose image in $K$ is
nonzero. Write $(W⁄K)$ for the base change of $W$ to $K$ and $(W⁄K)$`.Point` for its group of affine
points together with the point at infinity. Then for every point $Q$ of $(W⁄K)$, the set `fibSet W K
n Q`, that is $\{P : n \cdot P = Q\}$, the fibre over $Q$ of multiplication by the integer $n$ on
$(W⁄K)$`.Point`, is finite. No claim is made about the cardinality of this fibre, nor about its
non-emptiness; the assertion is finiteness alone, and in particular it holds vacuously when $Q$ is
not divisible by $n$.

This is the finiteness half of the classical description of the fibres of the isogeny $[n]$ on an
elliptic curve over an algebraically closed field of residue characteristic prime to $n$: a fibre is
empty or a translate of the $n$-torsion subgroup, which has $n^2$ elements. It underlies the
counting and valuation statements used in the construction of the Weil pairing, being cited by
[`WeierstrassCurve.Affine.ncard_fibSet`](thm.html#WeierstrassCurve.Affine.ncard_fibSet) and by the
lemmas on valuations of Weil functions.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_fibSet_finite.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_fibSet_finite
p2m_attr_erase "instance" "WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly"
p2m_attr_erase "simp" "compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two"

open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain IsDedekindDomain.HeightOneSpectrum WithZero
open scoped nonZeroDivisors

namespace WeilDiv

variable {F : Type*} [Field F] {K : Type*} [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K]
  (W : WeierstrassCurve F) [W.IsElliptic]

theorem torsion_finite {n : ℕ} (hn : (n : K) ≠ 0) :
    {S : (W⁄K).Point | (n : ℤ) • S = 0}.Finite := by
  have hcard := WeierstrassCurve.card_torsion_of_isAlgClosed (K := K) W hn
  have hn0 : n ≠ 0 := by rintro rfl; exact hn Nat.cast_zero
  have : Finite (Submodule.torsionBy ℤ (W⁄K).Point n) :=
    Nat.finite_of_card_ne_zero (by rw [hcard]; exact pow_ne_zero 2 hn0)
  have hset : {S : (W⁄K).Point | (n : ℤ) • S = 0} =
      ((Submodule.torsionBy ℤ (W⁄K).Point n : Submodule ℤ (W⁄K).Point) : Set (W⁄K).Point) := by
    ext S
    rw [Set.mem_ofPred_eq, SetLike.mem_coe, Submodule.mem_torsionBy_iff]
  rw [hset]
  exact Set.toFinite _

theorem card_torsion_toFinset {n : ℕ} (hn : (n : K) ≠ 0) :
    (torsion_finite W hn).toFinset.card = n ^ 2 := by
  rw [← WeierstrassCurve.card_torsion_of_isAlgClosed (K := K) W hn, ← Nat.card_eq_card_finite_toFinset]
  have hset : {S : (W⁄K).Point | (n : ℤ) • S = 0} =
      ((Submodule.torsionBy ℤ (W⁄K).Point n : Submodule ℤ (W⁄K).Point) : Set (W⁄K).Point) := by
    ext S
    rw [Set.mem_ofPred_eq, SetLike.mem_coe, Submodule.mem_torsionBy_iff]
  rw [hset]
  rfl

theorem fibSet_finite' {n : ℕ} (hn : (n : K) ≠ 0) (Q : (W⁄K).Point) : (fibSet W K n Q).Finite := by
  by_cases hne : ∃ P₀ : (W⁄K).Point, (n : ℤ) • P₀ = Q
  · obtain ⟨P₀, hP₀⟩ := hne
    refine ((torsion_finite W hn).image (· + P₀)).subset ?_
    intro P hP
    rw [mem_fibSet] at hP
    refine ⟨P - P₀, ?_, sub_add_cancel P P₀⟩
    show (n : ℤ) • (P - P₀) = 0
    rw [smul_sub, hP, hP₀, sub_self]
  · exact Set.finite_empty.subset fun P hP => (hne ⟨P, hP⟩).elim

end WeilDiv

theorem solution {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] {n : ℕ} (hn : (n : K) ≠ 0) (Q : (W⁄K).Point) : (fibSet W K n Q).Finite := by
  exact WeilDiv.fibSet_finite' W hn Q

end S_WeierstrassCurve_Affine_fibSet_finite
end P2MW
export P2MW.S_WeierstrassCurve_Affine_fibSet_finite (solution)

end privateSection

public section publicSection


open WeierstrassCurve WeierstrassCurve.Affine IsDedekindDomain WithZero

theorem WeierstrassCurve.Affine.fibSet_finite {F K : Type*} [Field F] [Field K] [Algebra F K] [DecidableEq K] [IsAlgClosed K] (W : WeierstrassCurve F) [W.IsElliptic] {n : ℕ} (hn : (n : K) ≠ 0) (Q : (W⁄K).Point) : (fibSet W K n Q).Finite := _root_.P2MW.S_WeierstrassCurve_Affine_fibSet_finite.solution W hn Q

end publicSection
