/-
Based on Prove2Me node MvPolynomial.IsHomogeneous.iterate_pderiv_eq_zero_of_lt
(6acf2c45-10bd-553c-81b2-a6163bfe51ad) by Claude (2026-09-05).

Proof based on Prove2Me submission 6026d3ff-85d3-50dd-bcae-ee5de615de95
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.RingTheory.MvPolynomial.Homogeneous

import Mathlib.RingTheory.MvPolynomial.EulerIdentity

/-!
# Iterated partial derivatives of order >n annihilate degree-n forms

Theorem statement: `MvPolynomial.IsHomogeneous.iterate_pderiv_eq_zero_of_lt`
(`6acf2c45-10bd-553c-81b2-a6163bfe51ad`), by Claude, 2026-09-05.

Proof: submission `6026d3ff-85d3-50dd-bcae-ee5de615de95`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$ be a commutative semiring and $\sigma$ an arbitrary type of variables, and let $\varphi \in
R[X_s : s \in \sigma]$ be a multivariate polynomial. Assume $\varphi$ is homogeneous of degree $n$
in the sense of Mathlib's `MvPolynomial.IsHomogeneous`, i.e. every monomial occurring in $\varphi$
with nonzero coefficient has total degree $n$. Let $k \in \sigma$ be one of the variables, and let
$i$ be a natural number with $n < i$. The conclusion is that the $i$-fold iterate of the partial
derivative operator $\partial/\partial X_k$, applied to $\varphi$, is the zero polynomial:
$(\mathrm{pderiv}\ k)^{[i]} \varphi = 0$. Note that only the single variable $k$ is differentiated
repeatedly, and that the statement holds over an arbitrary commutative semiring, with no finiteness
assumption on the set $\sigma$ of variables.

This is the elementary fact that a homogeneous polynomial of degree $n$ is annihilated by any $n+1$
iterated derivatives in a single variable. It is used in the treatment of Eichler integrals and the
Bol identity, where it shows that the rung above the top of the differentiation ladder vanishes; it
is cited by
[`HeckeEis.IsEichlerIntegral.eq_zero_of_eval_eq_const`](thm.html#HeckeEis.IsEichlerIntegral.eq_zero_of_eval_eq_const)
and
[`HeckeEis.IsEichlerIntegral.isBoundedAtImInfty_eval`](thm.html#HeckeEis.IsEichlerIntegral.isBoundedAtImInfty_eval).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_MvPolynomial_IsHomogeneous_iterate_pderiv_eq_zero_of_lt.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

namespace MvPolynomial
namespace DegAux
open MvPolynomial

open MvPolynomial

theorem isHomogeneous_iterate_pderiv
    {σ R : Type*} [CommSemiring R] {φ : MvPolynomial σ R} {n : ℕ} (k : σ)
    (hφ : φ.IsHomogeneous n) (j : ℕ) : ((pderiv k)^[j] φ).IsHomogeneous (n - j) := by
  induction j with
  | zero => simpa using hφ
  | succ j ih =>
    rw [Function.iterate_succ_apply']
    simpa [Nat.sub_sub] using ih.pderiv

theorem iterate_pderiv_eq_zero_of_lt {σ R : Type*} [CommSemiring R] {φ : MvPolynomial σ R} {n : ℕ}
    (hφ : φ.IsHomogeneous n) (k : σ) {i : ℕ} (hi : n < i) : (pderiv k)^[i] φ = 0 := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_lt hi
  rw [show n + m + 1 = m + 1 + n by ring, Function.iterate_add_apply,
    Function.iterate_succ_apply]
  have h0 : ((pderiv k)^[n] φ).IsHomogeneous 0 := by
    simpa using isHomogeneous_iterate_pderiv k hφ n
  have hC : (pderiv k)^[n] φ = C (AddMonoidAlgebra.coeff ((pderiv k)^[n] φ) 0) :=
    totalDegree_eq_zero_iff_eq_C.mp (Nat.eq_zero_of_le_zero h0.totalDegree_le)
  rw [hC, pderiv_C]
  exact Function.iterate_fixed (map_zero _) m

end MvPolynomial.DegAux

theorem solution {σ R : Type*} [CommSemiring R] {φ : MvPolynomial σ R}
    {n : ℕ} (hφ : φ.IsHomogeneous n) (k : σ) {i : ℕ} (hi : n < i) :
    (MvPolynomial.pderiv k)^[i] φ = 0 :=
  MvPolynomial.DegAux.iterate_pderiv_eq_zero_of_lt hφ k hi

end privateSection

public section publicSection

theorem MvPolynomial.IsHomogeneous.iterate_pderiv_eq_zero_of_lt
    {σ R : Type*} [CommSemiring R] {φ : MvPolynomial σ R}
    {n : ℕ} (hφ : φ.IsHomogeneous n) (k : σ) {i : ℕ} (hi : n < i) :
    (MvPolynomial.pderiv k)^[i] φ = 0 := by
  exact solution hφ k hi

end publicSection
