/-
Based on Prove2Me node AlgebraicCurve.Place.ord_smul_of_ne_zero
(ade5b407-0841-5603-9f32-5eed766c44cb) by Claude (2026-09-05).

Proof based on Prove2Me submission 1674e0b0-7466-5d27-9782-8d136657c972
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_P2M_Util

/-!
# Order at a place is invariant under nonzero constants

Theorem statement: `AlgebraicCurve.Place.ord_smul_of_ne_zero`
(`ade5b407-0841-5603-9f32-5eed766c44cb`), by Claude, 2026-09-05.

Proof: submission `1674e0b0-7466-5d27-9782-8d136657c972`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F/K$ in the sense of
the project: a valuation subring `v.toValuationSubring` of $F$ that contains
$\operatorname{algebraMap} K F\,(a)$ for every $a \in K$, is not all of $F$, and is a principal
ideal ring. For such a $v$, `v.adicValuation` denotes the $\mathbb{Z}^{m0}$-valued valuation on $F$
attached to the corresponding height-one prime of the valuation ring, and `v.ord f` is defined as
$-\log$ of `v.adicValuation f`, an integer, with the convention arising from $\log$ on
$\mathbb{Z}^{m0}$ that $\operatorname{ord}_v(0) = 0$. The theorem asserts: for every $c \in K$ with
$c \neq 0$ and every $x \in F$, the scalar multiple $c \bullet x$ satisfies $\operatorname{ord}_v(c
\bullet x) = \operatorname{ord}_v(x)$. Note that no hypothesis is placed on $x$; the case $x = 0$ is
covered by the convention just described.

This is the statement that the normalised order function at a place of $F/K$ is constant on
$K^\times$-orbits, i.e. that nonzero elements of the constant field are units of every place's
valuation ring. It is used throughout the divisor-theoretic part of the development, for instance
when computing orders of elements modified by a nonzero constant factor.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_ord_smul_of_ne_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_ord_smul_of_ne_zero

open AlgebraicCurve

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {c : K} (hc : c ≠ 0) (x : F) : v.ord (c • x) = v.ord x := by
  rcases eq_or_ne x 0 with rfl | hx0
  · rw [smul_zero]
  · have halg : algebraMap K F c ≠ 0 :=
      fun h => hc ((algebraMap K F).injective (by rw [h, map_zero]))
    have hunit : IsUnit (⟨algebraMap K F c, v.algebraMap_mem' c⟩ : v.toValuationSubring) := by
      refine isUnit_iff_exists_inv.mpr ⟨⟨algebraMap K F c⁻¹, v.algebraMap_mem' c⁻¹⟩, ?_⟩
      ext
      simp [mul_inv_cancel₀ halg]
    have h0 : v.ord (algebraMap K F c) = 0 := by
      have h1 : v.adicValuation (algebraMap K F c) = 1 :=
        (v.adicValuation_coe_eq_one_iff ⟨algebraMap K F c, v.algebraMap_mem' c⟩).mpr hunit
      simp [AlgebraicCurve.Place.ord, h1]
    rw [Algebra.smul_def, v.ord_mul halg hx0, h0, zero_add]

end S_AlgebraicCurve_Place_ord_smul_of_ne_zero
end P2MW
export P2MW.S_AlgebraicCurve_Place_ord_smul_of_ne_zero (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Place.ord_smul_of_ne_zero {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F) {c : K} (hc : c ≠ 0) (x : F) : v.ord (c • x) = v.ord x := _root_.P2MW.S_AlgebraicCurve_Place_ord_smul_of_ne_zero.solution v hc x

end publicSection
