/-
Based on Prove2Me node ModularCurve.emd_of_beta_docks
(964f8ad0-2fbd-509c-95ec-81dda4e54880) by Claude (2026-09-05).

Proof based on Prove2Me submission 207ad85b-14ba-5aa7-9cf2-2bd8be889a0c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_EMD
public import Mathlib.RingTheory.HahnSeries.PowerSeries
public import Mathlib.SetTheory.Cardinal.Finite

import Definitions.FLT.Def_P2M_Util

/-!
# Assembly of `EMD` from five local inputs

Theorem statement: `ModularCurve.emd_of_beta_docks` (`964f8ad0-2fbd-509c-95ec-81dda4e54880`), by
Claude, 2026-09-05.

Proof: submission `207ad85b-14ba-5aa7-9cf2-2bd8be889a0c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix a natural number $N \neq 0$ and an element $j_0$ of $\overline{\mathbb{Q}} =$ `AlgebraicClosure
ℚ`, and write $F_N =$ `modularFunctionFieldBar N` for the subfield of $\overline{\mathbb{Q}}((q))$
generated over $\overline{\mathbb{Q}}$ by the coefficientwise image of `modularFunctionFieldFull N`
(itself the subfield of $\mathbb{Q}((q))$ generated by the divisor expansions at level $N$), and
`jBar N` for the element of $F_N$ given by the $q$-expansion of $j$. Places here are valuation
subrings of $F_N$ containing $\overline{\mathbb{Q}}$, distinct from $F_N$ and principal, with `ord`
the associated normalised integer valuation. Four hypotheses are assumed. First, `hβ`: there is an
elliptic Weierstrass curve $E_0/\overline{\mathbb{Q}}$ with $j(E_0) = j_0$ together with a map $f$
from `CycSub E₀ N` (the subgroups of the affine points of $E_0$ generated by a point of order
exactly $N$) to the places $w$ with $\operatorname{ord}_w(\,\mathrm{jBar}\,N - j_0) > 0$, such that
$f(H) = f(H')$ holds exactly when `SameOrbit E₀ H H'`, i.e. some variable change $\gamma$ fixing
$E_0$ carries a generator of $H$ to one of $H'$ via `Point.vcInvFun`, and such that for each such
$w$ the number of $H$ with $f(H) = w$ equals $\operatorname{ord}_w(\,\mathrm{jBar}\,N - j_0)$.
Second, `hfin`: every elliptic Weierstrass curve over $\overline{\mathbb{Q}}$ has finitely many such
cyclic subgroups. Third, `hEP`: every $\overline{\mathbb{Q}}$-algebra map $\psi : F_N \to$
`HahnSeries ℚ` $\overline{\mathbb{Q}}$ normalised by $\psi(\mathrm{jBar}\,N) = j_0 + q$ induces a
place, that is, admits a place $w$ and a rational $g > 0$ with $g \cdot \operatorname{ord}_w(x) =
\operatorname{order}(\psi x)$ for all $x$. Fourth, `hPEO`: for each place $w$ with
$\operatorname{ord}_w(\,\mathrm{jBar}\,N - j_0) > 0$, the number of such normalised $\psi$ inducing
$w$ equals $\operatorname{ord}_w(\,\mathrm{jBar}\,N - j_0)$. Fifth, `hC535`: a $\psi$ induces at
most one place. The conclusion is `EMD N j₀`: there are an elliptic $E_0$ with $j(E_0) = j_0$ and a
bijection $\Phi$ between `Emb N j₀`, whose elements are carried by $\overline{\mathbb{Q}}$-algebra
maps $F_N \to$ `HahnSeries ℚ` $\overline{\mathbb{Q}}$, and `CycSub E₀ N`, such that two embeddings
induce a common place exactly when the corresponding subgroups lie in the same orbit.

This is the level-$N$ comparison between the normalised embeddings of the modular function field at
$j_0$ and the cyclic subgroups of order $N$ of an elliptic curve with invariant $j_0$, the form in
which the Hecke correspondence enters the local analysis of the covering $X_0(N) \to X(1)$ above
$j_0$. Here it is derived purely formally from a geometric input, a finiteness input, and the
existence, counting and uniqueness of the place induced by a normalised embedding; it is used in the
determination of the numbers of elliptic points, via
[`ModularCurve.card_filter_ord_jBar_eq_one_eq_nuThree`](thm.html#ModularCurve.card_filter_ord_jBar_eq_one_eq_nuThree)
and
[`ModularCurve.card_filter_ord_jBar_sub_1728_eq_one_eq_nuTwo`](thm.html#ModularCurve.card_filter_ord_jBar_sub_1728_eq_one_eq_nuTwo),
and in [`ModularCurve.emd_holds`](thm.html#ModularCurve.emd_holds).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_emd_of_beta_docks.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_emd_of_beta_docks

noncomputable section

p2m_open "ModularCurve P2MW.S_ModularCurve_emd_of_beta_docks.ModularCurve AlgebraicCurve"

namespace ModularCurve
p2m_export "ModularCurve" "Emb Induces SamePlace CycSub SameOrbit EMD jBar modularFunctionFieldBar"
p2m_open "ModularCurve"

private theorem emd_of_beta_docks (N : ℕ) [NeZero N] (j₀ : (AlgebraicClosure ℚ))
    (hβ : ∃ (E₀ : WeierstrassCurve (AlgebraicClosure ℚ)) (_ : E₀.IsElliptic), E₀.j = j₀ ∧
      ∃ f : CycSub E₀ N →
          {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
            0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)},
        (∀ H H' : CycSub E₀ N, f H = f H' ↔ SameOrbit E₀ H.1 H'.1) ∧
        ∀ w : {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
            0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)},
          ((w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N)).ord
              (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat =
            Nat.card {H : CycSub E₀ N // f H = w})
    (hfin : ∀ (E₀ : WeierstrassCurve (AlgebraicClosure ℚ)) [E₀.IsElliptic], Finite (CycSub E₀ N))
    (hEP : ∀ ψ : {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ) //
        ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)},
      ∃ (w : AlgebraicCurve.Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)) (g : ℚ),
        0 < g ∧ ∀ x : ↥(modularFunctionFieldBar N), (w.ord x : ℚ) * g = (ψ.1 x).order)
    (hPEO : ∀ w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N),
      0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) →
      Nat.card {ψ : modularFunctionFieldBar N →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ) //
        ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ) ∧
        ∃ g : ℚ, 0 < g ∧ ∀ x, (w.ord x : ℚ) * g = (ψ x).order} =
      (w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat)
    (hC535 : ∀ {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ)}
      {w w' : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)},
      Induces ψ w → Induces ψ w' → w = w')
    : EMD N j₀ := by
  classical
  obtain ⟨E₀, hell, hj, f, hiff, hsize⟩ := hβ
  have hInd : ∀ ψ : Emb N j₀, ∃ w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N), Induces ψ.1 w := by
    intro ψ
    obtain ⟨w, g, hg, hx⟩ := hEP ψ
    exact ⟨w, g, hg, hx⟩
  choose wOf hwOf using hInd
  have hC : ∀ c : (AlgebraicClosure ℚ), algebraMap (AlgebraicClosure ℚ) (HahnSeries ℚ (AlgebraicClosure ℚ)) c = HahnSeries.C c := by
    intro c
    rw [HahnSeries.algebraMap_apply', PowerSeries.algebraMap_eq, HahnSeries.ofPowerSeries_C]
  have habove : ∀ ψ : Emb N j₀,
      0 < (wOf ψ).ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) := by
    intro ψ
    obtain ⟨g, hg, hx⟩ := hwOf ψ
    have h1 := hx (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)
    have himg : ψ.1 (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) =
        HahnSeries.single (1 : ℚ) (1 : (AlgebraicClosure ℚ)) := by
      rw [map_sub, ψ.2, AlgHom.commutes, hC]
      ring
    rw [himg, HahnSeries.order_single one_ne_zero] at h1
    have hgne : g ≠ 0 := ne_of_gt hg
    have h2 : ((wOf ψ).ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) : ℚ) =
        1 / g := (eq_div_iff hgne).mpr h1
    have h3 : (0 : ℚ) <
        ((wOf ψ).ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) : ℚ) := by
      rw [h2]
      exact div_pos one_pos hg
    exact_mod_cast h3
  let F : Emb N j₀ → {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
      0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)} :=
    fun ψ => ⟨wOf ψ, habove ψ⟩
  have hFiff : ∀ (ψ : Emb N j₀) (w), F ψ = w ↔ Induces ψ.1 w.1 := by
    intro ψ w
    constructor
    · rintro rfl
      exact hwOf ψ
    · intro h
      exact Subtype.ext (hC535 (hwOf ψ) h)
  have hcardψ : ∀ w, Nat.card {ψ : Emb N j₀ // F ψ = w} =
      (w.1.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat := by
    intro w
    have e1 : {ψ : Emb N j₀ // F ψ = w} ≃ {ψ : Emb N j₀ // Induces ψ.1 w.1} :=
      Equiv.subtypeEquivRight fun ψ => hFiff ψ w
    have e2 : {ψ : Emb N j₀ // Induces ψ.1 w.1} ≃
        {ψ : ↥(modularFunctionFieldBar N) →ₐ[(AlgebraicClosure ℚ)] HahnSeries ℚ (AlgebraicClosure ℚ) //
          ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : (AlgebraicClosure ℚ)) ∧
          Induces ψ w.1} :=
      Equiv.subtypeSubtypeEquivSubtypeInter
        (fun ψ : ↥(modularFunctionFieldBar N) →ₐ[(AlgebraicClosure ℚ)] HahnSeries ℚ (AlgebraicClosure ℚ) =>
          ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : (AlgebraicClosure ℚ)))
        (fun ψ => Induces ψ w.1)
    rw [Nat.card_congr (e1.trans e2)]
    exact hPEO w.1 w.2
  have : E₀.IsElliptic := hell
  have : Finite (CycSub E₀ N) := hfin E₀
  have hfinH : ∀ w, Finite {H : CycSub E₀ N // f H = w} := fun _ => Subtype.finite
  have hfinψ : ∀ w, Finite {ψ : Emb N j₀ // F ψ = w} := by
    intro w
    have hne : Nat.card {ψ : Emb N j₀ // F ψ = w} ≠ 0 := by
      rw [hcardψ w]
      have := w.2
      omega
    exact (Nat.card_ne_zero.mp hne).2
  have fibEquiv : ∀ w, {ψ : Emb N j₀ // F ψ = w} ≃ {H : CycSub E₀ N // f H = w} := by
    intro w
    haveI := hfinψ w
    haveI := hfinH w
    haveI := Fintype.ofFinite {ψ : Emb N j₀ // F ψ = w}
    haveI := Fintype.ofFinite {H : CycSub E₀ N // f H = w}
    refine Fintype.equivOfCardEq ?_
    have h := (hcardψ w).trans (hsize w)
    rwa [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card] at h
  let Φ : Emb N j₀ ≃ CycSub E₀ N :=
    ((Equiv.sigmaFiberEquiv F).symm.trans
      (Equiv.sigmaCongrRight fibEquiv)).trans (Equiv.sigmaFiberEquiv f)
  have hfΦ : ∀ ψ, f (Φ ψ) = F ψ := fun ψ => ((fibEquiv (F ψ)) ⟨ψ, rfl⟩).2
  have hSP : ∀ ψ ψ' : Emb N j₀, SamePlace ψ.1 ψ'.1 ↔ F ψ = F ψ' := by
    intro ψ ψ'
    constructor
    · rintro ⟨w, h, h'⟩
      exact Subtype.ext ((hC535 (hwOf ψ) h).trans (hC535 (hwOf ψ') h').symm)
    · intro h
      refine ⟨wOf ψ, hwOf ψ, ?_⟩
      have hv : wOf ψ' = wOf ψ := congrArg Subtype.val h.symm
      rw [← hv]
      exact hwOf ψ'
  refine ⟨E₀, hell, hj, Φ, fun ψ ψ' => ?_⟩
  rw [hSP ψ ψ', ← hiff (Φ ψ) (Φ ψ')]
  rw [hfΦ ψ, hfΦ ψ']

end ModularCurve

end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_emd_of_beta_docks.ModularCurve AlgebraicCurve in

theorem solution (N : ℕ) [NeZero N] (j₀ : (AlgebraicClosure ℚ))
    (hβ : ∃ (E₀ : WeierstrassCurve (AlgebraicClosure ℚ)) (_ : E₀.IsElliptic), E₀.j = j₀ ∧
      ∃ f : CycSub E₀ N →
          {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
            0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)},
        (∀ H H' : CycSub E₀ N, f H = f H' ↔ SameOrbit E₀ H.1 H'.1) ∧
        ∀ w : {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
            0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)},
          ((w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N)).ord
              (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat =
            Nat.card {H : CycSub E₀ N // f H = w})
    (hfin : ∀ (E₀ : WeierstrassCurve (AlgebraicClosure ℚ)) [E₀.IsElliptic], Finite (CycSub E₀ N))
    (hEP : ∀ ψ : {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ) //
        ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)},
      ∃ (w : AlgebraicCurve.Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)) (g : ℚ),
        0 < g ∧ ∀ x : ↥(modularFunctionFieldBar N), (w.ord x : ℚ) * g = (ψ.1 x).order)
    (hPEO : ∀ w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N),
      0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) →
      Nat.card {ψ : modularFunctionFieldBar N →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ) //
        ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ) ∧
        ∃ g : ℚ, 0 < g ∧ ∀ x, (w.ord x : ℚ) * g = (ψ x).order} =
      (w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat)
    (hC535 : ∀ {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ)}
      {w w' : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)},
      Induces ψ w → Induces ψ w' → w = w')
    : EMD N j₀ :=
  ModularCurve.emd_of_beta_docks N j₀ hβ hfin hEP hPEO hC535

end S_ModularCurve_emd_of_beta_docks
end P2MW
export P2MW.S_ModularCurve_emd_of_beta_docks (solution)

end privateSection

public section publicSection


open ModularCurve AlgebraicCurve
theorem ModularCurve.emd_of_beta_docks (N : ℕ) [NeZero N] (j₀ : (AlgebraicClosure ℚ))
    (hβ : ∃ (E₀ : WeierstrassCurve (AlgebraicClosure ℚ)) (_ : E₀.IsElliptic), E₀.j = j₀ ∧
      ∃ f : CycSub E₀ N →
          {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
            0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)},
        (∀ H H' : CycSub E₀ N, f H = f H' ↔ SameOrbit E₀ H.1 H'.1) ∧
        ∀ w : {w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) //
            0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)},
          ((w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N)).ord
              (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat =
            Nat.card {H : CycSub E₀ N // f H = w})
    (hfin : ∀ (E₀ : WeierstrassCurve (AlgebraicClosure ℚ)) [E₀.IsElliptic], Finite (CycSub E₀ N))
    (hEP : ∀ ψ : {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ) //
        ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ)},
      ∃ (w : AlgebraicCurve.Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)) (g : ℚ),
        0 < g ∧ ∀ x : ↥(modularFunctionFieldBar N), (w.ord x : ℚ) * g = (ψ.1 x).order)
    (hPEO : ∀ w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N),
      0 < w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀) →
      Nat.card {ψ : modularFunctionFieldBar N →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ) //
        ψ (jBar N) = HahnSeries.C j₀ + HahnSeries.single (1 : ℚ) (1 : AlgebraicClosure ℚ) ∧
        ∃ g : ℚ, 0 < g ∧ ∀ x, (w.ord x : ℚ) * g = (ψ x).order} =
      (w.ord (jBar N - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) j₀)).toNat)
    (hC535 : ∀ {ψ : ↥(modularFunctionFieldBar N) →ₐ[AlgebraicClosure ℚ]
          HahnSeries ℚ (AlgebraicClosure ℚ)}
      {w w' : Place (AlgebraicClosure ℚ) ↥(modularFunctionFieldBar N)},
      Induces ψ w → Induces ψ w' → w = w')
    : EMD N j₀ := _root_.P2MW.S_ModularCurve_emd_of_beta_docks.solution N j₀ hβ hfin hEP hPEO hC535

end publicSection
