/-
Based on Prove2Me node ModularCurve.jqModC_mem_intFormRatiosC
(ba43d59b-e15b-5d68-810c-9c701699d584) by Claude (2026-09-05).

Proof based on Prove2Me submission 5306c1cb-d541-58ef-979c-6dd8b0dfe090
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff
public import Definitions.FLT.Def_ModularCurve_X1

import Theorems.FLT.Thm_ModularCurve_qExpansion_discriminant_eq_map_X_mul_dedekindEtaUnit
import Definitions.FLT.Def_P2M_Util

/-!
# j-series lies in the integral form ratios over any K, Γ

Theorem statement: `ModularCurve.jqModC_mem_intFormRatiosC`
(`ba43d59b-e15b-5d68-810c-9c701699d584`), by Claude, 2026-09-05.

Proof: submission `5306c1cb-d541-58ef-979c-6dd8b0dfe090`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $\Gamma$ be an arbitrary subgroup of $\mathrm{SL}_2(\mathbb{Z})$. Write
$\bar\jmath =$ [`ModularCurve.jqModC K`](def/ModularCurve_JqCoeff.html#L15) for the Laurent series
over $K$ given by $X^{-1}$ (the Hahn series `single (-1) 1`) times the image in $K[[X]]$ of the
integral power series `jNum` $=$ `eisenstein4`$^3 \cdot$ `dedekindEtaUnitInv`, the coefficients
being reduced along $\mathbb{Z} \to K$. The assertion is that $\bar\jmath$ belongs to
`intFormRatiosC K Γ`, i.e. that there are an integer $k$, two modular forms $f, g$ of weight $k$ for
the image of $\Gamma$ in $\mathrm{GL}_2(\mathbb{R})$, and two power series $p_f, p_g \in
\mathbb{Z}[[X]]$ such that $p_f$ and $p_g$, mapped to $\mathbb{C}[[X]]$, are the $q$-expansions
(with respect to period $1$) of $f$ and of $g$ respectively, such that the reduction of $p_g$ to a
Laurent series over $K$ is nonzero, and such that $\bar\jmath$ equals the quotient of the reductions
of $p_f$ and $p_g$ in $K((X))$. The witnesses are $k = 12$, $f$ the restriction to $\Gamma$ of
$E_4^3$ and $g$ the restriction to $\Gamma$ of the discriminant, with $p_f =$ `eisenstein4`$^3$ and
$p_g = X \cdot$ `dedekindEtaUnit`.

This is the classical identity $j = E_4^3/\Delta$, recorded in the shape needed here: the formal
$q$-expansion of the modular invariant, read over an arbitrary coefficient field, is a ratio of
$q$-expansions of two weight-$12$ forms with integral expansions on any subgroup of
$\mathrm{SL}_2(\mathbb{Z})$. It supplies the transcendental element inside the $q$-expansion
function field of a modular curve over $K$, and is used throughout the treatment of modular curves
and their function fields, including in positive characteristic.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_jqModC_mem_intFormRatiosC.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_jqModC_mem_intFormRatiosC

set_option linter.unusedSectionVars false
noncomputable section

namespace JqMemRatios

open ModularForm UpperHalfPlane EisensteinSeries ModularCurve HahnSeries
open scoped MatrixGroups ModularForm

theorem isIntegralQExp_E4 : IsIntegralQExp (E₄ : ℍ → ℂ) eisenstein4 := by
  rw [isIntegralQExp_iff]
  intro n
  rw [E_qExpansion_coeff (by norm_num) (by decide) n, eisenstein4, PowerSeries.coeff_mk]
  split_ifs with h
  · simp
  · rw [show _root_.bernoulli 4 = -1 / 30 by decide +kernel, ArithmeticFunction.sigma_apply]
    push_cast
    ring

variable (Γ : Subgroup SL(2, ℤ))

def e4cube : ModularForm (Γ : Subgroup (GL (Fin 2) ℝ)) 12 :=
  restrictForm (Subgroup.map_le_range _ Γ) ((E₄.pow 3).mcast (by norm_num))

def delta : ModularForm (Γ : Subgroup (GL (Fin 2) ℝ)) 12 :=
  restrictForm (Subgroup.map_le_range _ Γ) (CuspForm.discriminant : ModularForm 𝒮ℒ 12)

theorem isIntegralQExp_e4cube : IsIntegralQExp (e4cube Γ : ℍ → ℂ) (eisenstein4 ^ 3) := by
  rw [IsIntegralQExp, e4cube, coe_restrictForm, map_pow, isIntegralQExp_E4,
    ModularForm.qExpansion_mcast, ModularForm.qExpansion_pow one_pos one_mem_strictPeriods_SL]

theorem coe_delta : (delta Γ : ℍ → ℂ) = ModularForm.discriminant := rfl

theorem isIntegralQExp_delta :
    IsIntegralQExp (delta Γ : ℍ → ℂ) (PowerSeries.X * dedekindEtaUnit) := by
  rw [IsIntegralQExp, coe_delta]
  exact ModularCurve.qExpansion_discriminant_eq_map_X_mul_dedekindEtaUnit.symm

variable (K : Type*) [Field K]

theorem intSeriesC_delta_ne_zero : intSeriesC K (PowerSeries.X * dedekindEtaUnit) ≠ 0 := by
  intro h
  have h1 := congrArg (fun z : LaurentSeries K => z.coeff 1) h
  simp only [intSeriesC, HahnSeries.coeff_zero] at h1
  have h2 : (HahnSeries.ofPowerSeries ℤ K
      ((PowerSeries.X * dedekindEtaUnit).map (Int.castRingHom K))).coeff ((1 : ℕ) : ℤ) = 1 := by
    rw [HahnSeries.ofPowerSeries_apply_coeff, PowerSeries.coeff_map,
      show (1 : ℕ) = 0 + 1 from rfl, PowerSeries.coeff_succ_X_mul,
      PowerSeries.coeff_zero_eq_constantCoeff_apply, constantCoeff_dedekindEtaUnit, map_one]
  rw [show ((1 : ℕ) : ℤ) = 1 from rfl] at h2
  rw [h2] at h1
  exact one_ne_zero h1

theorem jqModC_mul_delta :
    jqModC K * intSeriesC K (PowerSeries.X * dedekindEtaUnit) = intSeriesC K (eisenstein4 ^ 3) := by
  rw [jqModC, intSeriesC, intSeriesC, jNum, mul_assoc, ← map_mul, ← map_mul,
    show eisenstein4 ^ 3 * dedekindEtaUnitInv * (PowerSeries.X * dedekindEtaUnit) =
      PowerSeries.X * eisenstein4 ^ 3 by
        rw [mul_comm PowerSeries.X dedekindEtaUnit, ← mul_assoc, mul_assoc (eisenstein4 ^ 3),
          mul_comm dedekindEtaUnitInv, dedekindEtaUnit_mul_inv, mul_one, mul_comm],
    map_mul, PowerSeries.map_X, map_mul, HahnSeries.ofPowerSeries_X, ← mul_assoc,
    HahnSeries.single_mul_single]
  simp

theorem jqModC_eq_div :
    jqModC K = intSeriesC K (eisenstein4 ^ 3) / intSeriesC K (PowerSeries.X * dedekindEtaUnit) := by
  rw [eq_div_iff (intSeriesC_delta_ne_zero K), jqModC_mul_delta]

end JqMemRatios

open JqMemRatios in
theorem solution (K : Type*) [Field K]
    (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ)) :
    ModularCurve.jqModC K ∈ ModularCurve.intFormRatiosC K Γ :=
  ⟨12, e4cube Γ, delta Γ, ModularCurve.eisenstein4 ^ 3, PowerSeries.X * ModularCurve.dedekindEtaUnit,
    isIntegralQExp_e4cube Γ, isIntegralQExp_delta Γ, intSeriesC_delta_ne_zero K, jqModC_eq_div K⟩

end

end S_ModularCurve_jqModC_mem_intFormRatiosC
end P2MW
export P2MW.S_ModularCurve_jqModC_mem_intFormRatiosC (solution)

end privateSection

public section publicSection

theorem ModularCurve.jqModC_mem_intFormRatiosC (K : Type*) [Field K]
    (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ)) :
    ModularCurve.jqModC K ∈ ModularCurve.intFormRatiosC K Γ := _root_.P2MW.S_ModularCurve_jqModC_mem_intFormRatiosC.solution K Γ

end publicSection
