/-
Based on Prove2Me node ModularCurve.HahnSpecialise.specialiseCycSub_bijective
(9307f9d2-7f83-55bd-a537-afd602522dd1) by Claude (2026-09-05).

Proof based on Prove2Me submission b8e9b129-d73f-5b34-b4d4-1de090874d1f
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_HahnSpecialise

import Theorems.FLT.Thm_ModularCurve_HahnSpecialise_specialiseCycSub_injective
import Theorems.FLT.Thm_ModularCurve_HahnSpecialise_specialise_bijOn_torsion
import Definitions.FLT.Def_P2M_Util

/-!
# Bijectivity of specialisation on cyclic subgroups of order N

Theorem statement: `ModularCurve.HahnSpecialise.specialiseCycSub_bijective`
(`9307f9d2-7f83-55bd-a537-afd602522dd1`), by Claude, 2026-09-05.

Proof: submission `b8e9b129-d73f-5b34-b4d4-1de090874d1f`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let `E` be a Weierstrass curve over the series field `H`, and assume `IntegralCoeffs E`, i.e. each
of the five coefficients $a_1,a_2,a_3,a_4,a_6$ of `E` has non-negative `orderTop`. Let `specialFibre
E` be the Weierstrass curve over $\bar{\mathbb Q}$ (the algebraic closure of $\mathbb Q$) whose
coefficients are the degree-$0$ coefficients $a_i.\mathrm{coeff}\,0$, and assume its discriminant is
non-zero. Let $N$ be a natural number, non-zero. The statement concerns the specialisation map on
cyclic subgroups: the source is the set of additive subgroups $G$ of the affine point group $E(\,)$
of `E` for which there is a point $g$ of additive order exactly $N$ with $G$ the group of integer
multiples of $g$, the target is the analogous set for `specialFibre E`, and the map sends such a $G$
to its image under the specialisation homomorphism `specialise E hE hΔ` on points (reduction into
the special fibre). The conclusion is that this map is bijective: a cyclic subgroup of order $N$
upstairs has image a cyclic subgroup of order $N$ in the special fibre, and every such subgroup
downstairs arises from exactly one subgroup upstairs.

This is the level-structure counterpart of good-reduction specialisation: over the series field the
cyclic subgroups of exact order $N$ of the generic curve correspond bijectively to those of its
special fibre over $\bar{\mathbb Q}$. It is the curve-side input used by
[`ModularCurve.B3.specialisationEquivariance_level`](thm.html#ModularCurve.B3.specialisationEquivariance_level),
where cyclic $N$-isogenies (level structures) must be matched between the generic and the special
curve.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_HahnSpecialise_specialiseCycSub_bijective.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_HahnSpecialise_specialiseCycSub_bijective
p2m_attr_erase "instance" "WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly"
p2m_attr_erase "simp" "compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec compl₂EDS_two"

noncomputable section

open ModularCurve ModularCurve.B3 ModularCurve.HahnSpecialise
open ModularCurve.TatePoint (Qbar H CycSubH)
open scoped Classical

namespace CycSubOf
p2m_export "CycSubOf" "map coe_map"
p2m_open "CycSubOf"

variable {G G' : Type*} [AddCommGroup G] [AddCommGroup G'] (f : G →+ G') {N : ℕ}
variable (hf : ∀ ⦃P Q : G⦄, N • P = 0 → N • Q = 0 → f P = f Q → P = Q)

include hf in

theorem addOrderOf_map_eq_of_injOn {g : G} (hg : N • g = 0) : addOrderOf (f g) = addOrderOf g := by
  apply Nat.dvd_antisymm (addOrderOf_map_dvd f g)
  apply addOrderOf_dvd_of_nsmul_eq_zero
  refine hf ?_ (smul_zero _) ?_
  · rw [smul_comm, hg, smul_zero]
  · rw [map_nsmul, addOrderOf_nsmul_eq_zero, map_zero]

include hf in

theorem map_surjective_of_surjOn
    (hs : ∀ P' : G', N • P' = 0 → ∃ P : G, N • P = 0 ∧ f P = P') :
    Function.Surjective (map f hf) := by
  intro T
  obtain ⟨g', hg', hT⟩ := T.2
  obtain ⟨g, hgN, hgg'⟩ := hs g' (by rw [← hg']; exact addOrderOf_nsmul_eq_zero g')
  have hg : addOrderOf g = N := by rw [← addOrderOf_map_eq_of_injOn f hf hgN, hgg', hg']
  refine ⟨⟨AddSubgroup.zmultiples g, g, hg, rfl⟩, Subtype.ext ?_⟩
  rw [coe_map, hT, AddMonoidHom.map_zmultiples, hgg']

end CycSubOf

theorem solution (E : WeierstrassCurve H) (hE : IntegralCoeffs E)
    (hΔ : (specialFibre E).Δ ≠ 0) (N : ℕ) [NeZero N] :
    Function.Bijective (specialiseCycSub E hE hΔ N) := by
  refine ⟨ModularCurve.HahnSpecialise.specialiseCycSub_injective E hE hΔ N, ?_⟩
  have hb := ModularCurve.HahnSpecialise.specialise_bijOn_torsion E hE hΔ N
  exact CycSubOf.map_surjective_of_surjOn _ _ (fun Q hQ => by
    obtain ⟨P, hP, hPQ⟩ := hb.2.2 hQ
    exact ⟨P, hP, hPQ⟩)

end

end S_ModularCurve_HahnSpecialise_specialiseCycSub_bijective
end P2MW
export P2MW.S_ModularCurve_HahnSpecialise_specialiseCycSub_bijective (solution)

end privateSection

public section publicSection


open ModularCurve ModularCurve.B3 ModularCurve.HahnSpecialise
open ModularCurve.TatePoint (Qbar H CycSubH)
open scoped Classical
theorem ModularCurve.HahnSpecialise.specialiseCycSub_bijective (E : WeierstrassCurve H) (hE : IntegralCoeffs E)
    (hΔ : (specialFibre E).Δ ≠ 0) (N : ℕ) [NeZero N] :
    Function.Bijective (specialiseCycSub E hE hΔ N) := _root_.P2MW.S_ModularCurve_HahnSpecialise_specialiseCycSub_bijective.solution E hE hΔ N

end publicSection
