/-
Based on Prove2Me node AlgebraicCurve.Place.exists_ord_algebraMap_eq_mul_ord
(4a6afafb-d24c-5767-be5f-dfacc8bd73c8) by Claude (2026-09-05).

Proof based on Prove2Me submission f2955a9a-20c1-503c-be86-1a1a4684b62c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_P2M_Util

/-!
# Ramification index: ord_w = ecdotordᵥ on F

Theorem statement: `AlgebraicCurve.Place.exists_ord_algebraMap_eq_mul_ord`
(`4a6afafb-d24c-5767-be5f-dfacc8bd73c8`), by Claude, 2026-09-05.

Proof: submission `f2955a9a-20c1-503c-be86-1a1a4684b62c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$, $F$, $F'$ be fields with $F$ and $F'$ algebras over $K$ and $F'$ an algebra over $F$ (no
compatibility between the three structure maps, and no algebraicity or finiteness of $F'/F$, is
assumed). Here a place of a field $L$ over $K$ consists of a valuation subring $\mathcal O \subseteq
L$ which contains the image of $K$, is not all of $L$, and is a principal ideal ring; its order
function $\operatorname{ord}$ is the negative of the logarithm of the associated adic valuation at
the height-one point of $\mathcal O$, i.e. the normalised discrete valuation, with the convention
$\operatorname{ord}(0)=0$. Given such a place $w$ of $F'$ over $K$, a place $v$ of $F$ over $K$, and
the hypothesis that the valuation subring of $v$ is exactly the preimage of the valuation subring of
$w$ under the structure map $F \to F'$ (that is, $\mathcal O_v = \mathcal O_w \cap F$, so $w$ lies
over $v$), the assertion is that there exists a natural number $e$ with $e > 0$ such that for every
$f \in F$ one has $\operatorname{ord}_w(\operatorname{alg}(f)) = e \cdot \operatorname{ord}_v(f)$,
where $\operatorname{alg}$ denotes the map $F \to F'$.

This is the existence of the ramification index $e(w\mid v)$ of a place $w$ lying over a place $v$,
in the form of proportionality of the two normalised order functions on $F$. It underpins the
comparison of orders in towers of function fields, and is used for the criteria that a function with
nowhere-negative order lies in the base field and for the order computations for the $j$-coordinate
on the modular function field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord

noncomputable section

open IsDedekindDomain WithZero IsLocalRing

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place"
p2m_open "AlgebraicCurve"

namespace Place
p2m_export "AlgebraicCurve.Place" "ord ord_one ord_mul ord_inv ord_coe_irreducible ord_zpow ord_unit_smul_zpow exists_unit_mul_zpow toValuationSubring"
p2m_open "AlgebraicCurve.Place"

section SinglePlace

variable {K F : Type*} [Field K] [Field F] [Algebra K F] (v : Place K F)

private theorem _root_.AlgebraicCurve.Place.ord_nonneg_of_mem' {f : F} (hf : f ∈ v.toValuationSubring) : 0 ≤ v.ord f := by
  rcases eq_or_ne f 0 with rfl | hf0
  · simp
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  obtain ⟨n, u, hu⟩ :=
    IsDiscreteValuationRing.eq_unit_mul_pow_irreducible
      (x := (⟨f, hf⟩ : v.toValuationSubring)) (by simpa [Subtype.ext_iff] using hf0) hπ
  have hcoe : f = ((u : v.toValuationSubring) : F) * ((π : F) ^ (n : ℤ)) := by
    have h := congrArg (Subtype.val) hu
    push_cast at h
    rw [zpow_natCast]
    exact h
  rw [hcoe, v.ord_unit_smul_zpow u hπ (n : ℤ)]
  exact Int.natCast_nonneg n

p2m_export "AlgebraicCurve.Place" "ord_nonneg_of_mem'"
private theorem _root_.AlgebraicCurve.Place.mem_of_ord_nonneg' {f : F} (hf : f ≠ 0) (h : 0 ≤ v.ord f) :
    f ∈ v.toValuationSubring := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  obtain ⟨u, hu⟩ := v.exists_unit_mul_zpow hf hπ
  rw [hu, show v.ord f = (((v.ord f).toNat : ℕ) : ℤ) from (Int.toNat_of_nonneg h).symm,
    zpow_natCast]
  exact mul_mem (u : v.toValuationSubring).2 (pow_mem (π : v.toValuationSubring).2 _)

p2m_export "AlgebraicCurve.Place" "mem_of_ord_nonneg'"
private theorem mem_iff_ord_nonneg' {f : F} (hf : f ≠ 0) :
    f ∈ v.toValuationSubring ↔ 0 ≤ v.ord f :=
  ⟨v.ord_nonneg_of_mem', v.mem_of_ord_nonneg' hf⟩

private theorem exists_ord_pos_mem' : ∃ f : F, f ≠ 0 ∧ 0 < v.ord f ∧ f ∈ v.toValuationSubring := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  refine ⟨(π : F), ?_, ?_, π.2⟩
  · simpa [ne_eq, ZeroMemClass.coe_eq_zero] using hπ.ne_zero
  · rw [v.ord_coe_irreducible hπ]
    exact one_pos

end SinglePlace

section Fiber

variable {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [Algebra F F']

theorem rowMain (w : Place K F') (v : Place K F)
    (hv : v.toValuationSubring = w.toValuationSubring.comap (algebraMap F F')) :
    ∃ e : ℕ, 0 < e ∧ ∀ f : F, w.ord (algebraMap F F' f) = e * v.ord f := by
  have hmem : ∀ {f : F}, f ∈ v.toValuationSubring → algebraMap F F' f ∈ w.toValuationSubring :=
    fun {f} h => by
      rw [hv] at h
      exact (ValuationSubring.mem_comap).mp h
  have hmem' : ∀ {f : F}, algebraMap F F' f ∈ w.toValuationSubring → f ∈ v.toValuationSubring :=
    fun {f} h => by
      rw [hv]
      exact (ValuationSubring.mem_comap).mpr h
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v.toValuationSubring
  have hπF : (π : F) ≠ 0 := by
    simpa [ne_eq, ZeroMemClass.coe_eq_zero] using hπ.ne_zero
  have hπF' : algebraMap F F' (π : F) ≠ 0 := by simpa using hπF
  have he0 : 0 ≤ w.ord (algebraMap F F' (π : F)) := w.ord_nonneg_of_mem' (hmem π.2)
  have hepos : 0 < w.ord (algebraMap F F' (π : F)) := by
    rcases eq_or_lt_of_le he0 with h0 | h
    · exfalso
      have hinv : (algebraMap F F' (π : F))⁻¹ ∈ w.toValuationSubring :=
        w.mem_of_ord_nonneg' (inv_ne_zero hπF') (by rw [w.ord_inv, ← h0, neg_zero])
      have hinv' : (π : F)⁻¹ ∈ v.toValuationSubring := hmem' (by rwa [map_inv₀])
      have h1 := v.ord_nonneg_of_mem' hinv'
      rw [v.ord_inv, v.ord_coe_irreducible hπ] at h1
      omega
    · exact h
  have hunit : ∀ u : v.toValuationSubringˣ,
      w.ord (algebraMap F F' ((u : v.toValuationSubring) : F)) = 0 := by
    intro u
    have h1 : 0 ≤ w.ord (algebraMap F F' ((u : v.toValuationSubring) : F)) :=
      w.ord_nonneg_of_mem' (hmem (u : v.toValuationSubring).2)
    have h2 : 0 ≤ w.ord (algebraMap F F' ((↑(u⁻¹) : v.toValuationSubring) : F)) :=
      w.ord_nonneg_of_mem' (hmem (↑(u⁻¹) : v.toValuationSubring).2)
    have hu0 : ((u : v.toValuationSubring) : F) ≠ 0 := by
      simp [ne_eq, ZeroMemClass.coe_eq_zero]
    have hu0' : ((↑(u⁻¹) : v.toValuationSubring) : F) ≠ 0 := by
      simp [ne_eq, ZeroMemClass.coe_eq_zero]
    have hprod : ((u : v.toValuationSubring) : F) * ((↑(u⁻¹) : v.toValuationSubring) : F) = 1 := by
      have := u.mul_inv
      rw [Subtype.ext_iff] at this
      push_cast at this
      exact this
    have hsum : w.ord (algebraMap F F' ((u : v.toValuationSubring) : F))
        + w.ord (algebraMap F F' ((↑(u⁻¹) : v.toValuationSubring) : F)) = 0 := by
      rw [← w.ord_mul ((map_ne_zero (algebraMap F F')).mpr hu0)
        ((map_ne_zero (algebraMap F F')).mpr hu0'), ← map_mul, hprod, map_one, w.ord_one]
    omega
  refine ⟨(w.ord (algebraMap F F' (π : F))).toNat, by omega, fun f => ?_⟩
  rw [Int.toNat_of_nonneg he0]
  rcases eq_or_ne f 0 with rfl | hf
  · simp
  obtain ⟨u, hu⟩ := v.exists_unit_mul_zpow hf hπ
  have hu0 : ((u : v.toValuationSubring) : F) ≠ 0 := by
    simp [ne_eq, ZeroMemClass.coe_eq_zero]
  conv_lhs => rw [hu]
  rw [map_mul, map_zpow₀, w.ord_mul ((map_ne_zero (algebraMap F F')).mpr hu0) (zpow_ne_zero _ hπF'),
    hunit u, zero_add, w.ord_zpow, mul_comm]

end Fiber

end Place

end AlgebraicCurve

end

open _root_.AlgebraicCurve _root_.P2MW.S_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord.AlgebraicCurve in
theorem solution {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [Algebra F F'] (w : Place K F') (v : Place K F) (hv : v.toValuationSubring = w.toValuationSubring.comap (algebraMap F F')) :
    ∃ e : ℕ, 0 < e ∧ ∀ f : F, w.ord (algebraMap F F' f) = e * v.ord f :=
  AlgebraicCurve.Place.rowMain w v hv

end S_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord
end P2MW
export P2MW.S_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Place.exists_ord_algebraMap_eq_mul_ord {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [Algebra F F'] (w : Place K F') (v : Place K F) (hv : v.toValuationSubring = w.toValuationSubring.comap (algebraMap F F')) : ∃ e : ℕ, 0 < e ∧ ∀ f : F, w.ord (algebraMap F F' f) = e * v.ord f := _root_.P2MW.S_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord.solution w v hv

end publicSection
