/-
Based on Prove2Me node ModularCurve.CuspSpace.card_cuspSpace_eq_cuspCount
(64ad9f87-b150-5ecf-b3a9-63fad04f9afe) by Claude (2026-09-05).

Proof based on Prove2Me submission b17bf4a0-4372-5461-84de-9c063fcbef3b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_CuspSpace
public import Definitions.FLT.Def_ModularCurve_GenusNumerics

import Theorems.FLT.Thm_ModularCurve_CuspSpace_classification
import Definitions.FLT.Def_P2M_Util

/-!
# Number of cusps of Γ₀(N) equals sum_{d∣ N}φ(gcd(d,N/d))

Theorem statement: `ModularCurve.CuspSpace.card_cuspSpace_eq_cuspCount`
(`64ad9f87-b150-5ecf-b3a9-63fad04f9afe`), by Claude, 2026-09-05.

Proof: submission `b17bf4a0-4372-5461-84de-9c063fcbef3b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number with $N \neq 0$. Consider the subgroup $\Gamma_0(N)$ of
$\mathrm{SL}_2(\mathbb{Z})$, pushed forward along the map to $\mathrm{GL}_2(\mathbb{Q})$, so that
`Gamma0Q N` is its image as a subgroup of $\mathrm{GL}_2(\mathbb{Q})$; this group acts on the
one-point compactification `OnePoint ℚ` of $\mathbb{Q}$, i.e. on $\mathbb{P}^1(\mathbb{Q})$
presented as $\mathbb{Q} \cup \{\infty\}$. The type [`ModularCurve.CuspSpace
N`](def/ModularCurve_CuspSpace.html#L103) is the quotient of $\mathbb{P}^1(\mathbb{Q})$ by the orbit
relation for this action, that is the set of cusps $\Gamma_0(N) \backslash
\mathbb{P}^1(\mathbb{Q})$. The assertion is that the cardinality of this quotient, taken as a
natural number via `Nat.card`, equals $$\mathrm{cuspCount}(N) = \sum_{d \mid N} \varphi\bigl(\gcd(d,
N/d)\bigr),$$ the sum being over the positive divisors $d$ of $N$ and $\varphi$ the Euler totient
function; in particular the quotient is finite, since `Nat.card` of an infinite type would be $0$
while the right-hand side is positive.

This is the classical count of the cusps of the modular curve $X_0(N)$, $\nu_\infty(N) = \sum_{d
\mid N} \varphi(\gcd(d, N/d))$. It feeds the numerical input for the genus computations and related
estimates for $X_0(N)$, being used for the count of orbits of the unipotent subgroup generated by
$T$ and for the bound on the rank of the space of parabolic homomorphisms in terms of the genus
formula.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount

open Matrix Matrix.SpecialLinearGroup OnePoint CongruenceSubgroup
open scoped MatrixGroups
p2m_open "ModularCurve P2MW.S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount.ModularCurve ModularCurve.CuspSpace P2MW.S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount.ModularCurve.CuspSpace"

namespace ModularCurve
p2m_export "ModularCurve" "CuspSpace cuspCount CuspSpace.classification"
namespace CuspSpace
p2m_export "ModularCurve.CuspSpace" "Classification classification"
p2m_open "ModularCurve.CuspSpace ModularCurve"

open Finset

variable {N : ℕ}

theorem card_sigma_units :
    Nat.card ((d : N.divisors) × (ZMod (Nat.gcd d (N / (d : ℕ))))ˣ) = cuspCount N := by
  have hgcd : ∀ d : N.divisors, NeZero (Nat.gcd (d : ℕ) (N / (d : ℕ))) := by
    rintro ⟨d, hd⟩
    rw [Nat.mem_divisors] at hd
    exact ⟨(Nat.gcd_pos_of_pos_left _ (Nat.pos_of_ne_zero
      (fun h => hd.2 (Nat.eq_zero_of_zero_dvd (h ▸ hd.1))))).ne'⟩
  rw [Nat.card_sigma]
  simp only [cuspCount]
  rw [← Finset.sum_attach N.divisors fun d => Nat.totient (Nat.gcd d (N / d)),
    ← Finset.univ_eq_attach]
  refine Finset.sum_congr rfl fun d _ => ?_
  have := hgcd d
  rw [Nat.card_eq_fintype_card, ZMod.card_units_eq_totient]

theorem card_eq_cuspCount_of_classification (hcl : Classification N) :
    Nat.card (CuspSpace N) = cuspCount N := by
  obtain ⟨e⟩ := hcl
  rw [Nat.card_congr e, card_sigma_units]

end ModularCurve.CuspSpace

theorem solution {N : ℕ} (hN : N ≠ 0) :
    Nat.card (ModularCurve.CuspSpace N) = ModularCurve.cuspCount N :=
  ModularCurve.CuspSpace.card_eq_cuspCount_of_classification (ModularCurve.CuspSpace.classification hN)

end S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount
end P2MW
export P2MW.S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount (solution)

end privateSection

public section publicSection


open OnePoint
theorem ModularCurve.CuspSpace.card_cuspSpace_eq_cuspCount {N : ℕ} (hN : N ≠ 0) :
    Nat.card (ModularCurve.CuspSpace N) = ModularCurve.cuspCount N := _root_.P2MW.S_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount.solution hN

end publicSection
