/-
Based on Prove2Me node ModularForm.coeffHeckeT_coeffHeckeU_comm
(d67181b2-d9a8-52ab-ab08-d4ed37010b41) by Claude (2026-09-05).

Proof based on Prove2Me submission 67be7ef0-0c1b-5ef1-b21b-e725ceaeed0e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularForm_HeckeOperator

import Mathlib.Data.Nat.GCD.Basic
import Mathlib.Basic.Complex.Basic
import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Algebra.Rat
import Definitions.FLT.Def_P2M_Util

/-!
# Coefficient operators Tₚ and U_q commute for coprime p,q

Theorem statement: `ModularForm.coeffHeckeT_coeffHeckeU_comm`
(`d67181b2-d9a8-52ab-ab08-d4ed37010b41`), by Claude, 2026-09-05.

Proof: submission `67be7ef0-0c1b-5ef1-b21b-e725ceaeed0e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $k$ be an integer, let $p,q$ be natural numbers with $\gcd(p,q)=1$, and let
$a:\mathbb{N}\to\mathbb{C}$ be an arbitrary sequence of complex numbers. The two coefficient-level
operators involved are defined purely combinatorially: [`ModularForm.coeffHeckeU
q`](def/ModularForm_HeckeOperator.html#L165) sends $a$ to the sequence $n\mapsto a(nq)$, and
[`ModularForm.coeffHeckeT k p`](def/ModularForm_HeckeOperator.html#L162) sends $a$ to the sequence
$n\mapsto a(np) + p^{k-1}a(n/p)$ when $p\mid n$, and $n\mapsto a(np)$ otherwise (the correction term
being literally $\mathbf{1}_{p\mid n}\,(p:\mathbb{C})^{k-1}a(n/p)$, with $n/p$ natural division and
the power taken in $\mathbb{C}$ with integer exponent). The assertion is the equality of functions
$\mathbb{N}\to\mathbb{C}$
$$\mathrm{coeffHeckeT}_k^p\bigl(\mathrm{coeffHeckeU}^q a\bigr) =
\mathrm{coeffHeckeU}^q\bigl(\mathrm{coeffHeckeT}_k^p a\bigr),$$
both sides sending $n$ to $a(npq) + \mathbf{1}_{p\mid n}\,p^{k-1}a((n/p)q)$. No modularity, growth
or holomorphy hypothesis on $a$ is imposed: this is an identity about arbitrary complex sequences.

This is the commutation relation $T_pU_q = U_qT_p$ for coprime indices, read on $q$-expansion
coefficients, as it holds classically for $T_p$ with $p\nmid N$ and $U_q$ with $q\mid N$ acting on
$M_k(\Gamma_0(N))$. It is used by
[`ModularFormClass.heckeT_heckeU_comm`](thm.html#ModularFormClass.heckeT_heckeU_comm) to transport
the relation to the operators on modular forms themselves, and thence in
[`CuspForm.exists_isNormalizedEigenform`](thm.html#CuspForm.exists_isNormalizedEigenform), the
existence of a normalised eigenform in the relevant eigenspace.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_coeffHeckeT_coeffHeckeU_comm.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_coeffHeckeT_coeffHeckeU_comm

namespace M4cP1W2

open ModularForm

theorem coeffHeckeU_comm (p q : ℕ) (a : ℕ → ℂ) :
    coeffHeckeU p (coeffHeckeU q a) = coeffHeckeU q (coeffHeckeU p a) := by
  funext n
  simp only [coeffHeckeU_apply, Nat.mul_right_comm]

theorem coeffHeckeT_coeffHeckeU_comm (k : ℤ) {p q : ℕ} (hpq : Nat.Coprime p q) (a : ℕ → ℂ) :
    coeffHeckeT k p (coeffHeckeU q a) = coeffHeckeU q (coeffHeckeT k p a) := by
  funext n
  simp only [coeffHeckeT_apply, coeffHeckeU_apply]
  have hiff : p ∣ n * q ↔ p ∣ n := hpq.dvd_mul_right
  by_cases hpn : p ∣ n
  · rw [ite_eq_left hpn, ite_eq_left (hiff.mpr hpn), Nat.mul_right_comm, Nat.div_mul_right_comm hpn]
  · rw [ite_eq_right hpn, ite_eq_right (fun h => hpn (hiff.mp h)), Nat.mul_right_comm]

theorem coeffHeckeT_comm (k : ℤ) {p q : ℕ} (hpq : Nat.Coprime p q) (a : ℕ → ℂ) :
    coeffHeckeT k p (coeffHeckeT k q a) = coeffHeckeT k q (coeffHeckeT k p a) := by
  funext n
  simp only [coeffHeckeT_apply]
  have hq : q ∣ n * p ↔ q ∣ n := hpq.symm.dvd_mul_right
  have hp : p ∣ n * q ↔ p ∣ n := hpq.dvd_mul_right
  have hpq' : ∀ {m : ℕ}, p ∣ m → (q ∣ m / p ↔ p * q ∣ m) := fun h =>
    Nat.dvd_div_iff_mul_dvd h
  have hqp' : ∀ {m : ℕ}, q ∣ m → (p ∣ m / q ↔ q * p ∣ m) := fun h =>
    Nat.dvd_div_iff_mul_dvd h
  by_cases hpn : p ∣ n <;> by_cases hqn : q ∣ n
  · have hpqn : p * q ∣ n := hpq.mul_dvd_of_dvd_of_dvd hpn hqn
    rw [ite_eq_left (hq.mpr hqn), ite_eq_left hpn, ite_eq_left ((hpq' hpn).mpr hpqn), ite_eq_left (hp.mpr hpn),
      ite_eq_left hqn, ite_eq_left ((hqp' hqn).mpr (mul_comm p q ▸ hpqn)),
      Nat.mul_right_comm, Nat.div_mul_right_comm hqn, Nat.div_mul_right_comm hpn,
      Nat.div_div_eq_div_mul, Nat.div_div_eq_div_mul, mul_comm q p]
    ring
  · have h1 : ¬ q ∣ n / p := fun h => hqn (Nat.dvd_trans (Nat.dvd_mul_left q p) ((hpq' hpn).mp h))
    rw [ite_eq_right (fun h => hqn (hq.mp h)), ite_eq_left hpn, ite_eq_right h1, ite_eq_left (hp.mpr hpn), ite_eq_right hqn,
      Nat.mul_right_comm, Nat.div_mul_right_comm hpn]
    ring
  · have h1 : ¬ p ∣ n / q := fun h => hpn (Nat.dvd_trans (Nat.dvd_mul_left p q) ((hqp' hqn).mp h))
    rw [ite_eq_left (hq.mpr hqn), ite_eq_right hpn, ite_eq_right (fun h => hpn (hp.mp h)), ite_eq_left hqn, ite_eq_right h1,
      Nat.mul_right_comm, Nat.div_mul_right_comm hqn]
    ring
  · rw [ite_eq_right (fun h => hqn (hq.mp h)), ite_eq_right hpn, ite_eq_right (fun h => hpn (hp.mp h)), ite_eq_right hqn,
      Nat.mul_right_comm]

end M4cP1W2

theorem solution (k : ℤ) {p q : ℕ} (hpq : Nat.Coprime p q) (a : ℕ → ℂ) : ModularForm.coeffHeckeT k p (ModularForm.coeffHeckeU q a) = ModularForm.coeffHeckeU q (ModularForm.coeffHeckeT k p a) :=
  M4cP1W2.coeffHeckeT_coeffHeckeU_comm k hpq a

end S_ModularForm_coeffHeckeT_coeffHeckeU_comm
end P2MW
export P2MW.S_ModularForm_coeffHeckeT_coeffHeckeU_comm (solution)

end privateSection

public section publicSection

theorem ModularForm.coeffHeckeT_coeffHeckeU_comm (k : ℤ) {p q : ℕ} (hpq : Nat.Coprime p q) (a : ℕ → ℂ) : ModularForm.coeffHeckeT k p (ModularForm.coeffHeckeU q a) = ModularForm.coeffHeckeU q (ModularForm.coeffHeckeT k p a) := _root_.P2MW.S_ModularForm_coeffHeckeT_coeffHeckeU_comm.solution k hpq a

end publicSection
