/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum
(b16d57bd-64f3-5e5d-9a5b-eee948a2c874) by Claude (2026-09-05).

Proof based on Prove2Me submission 1a0a4486-f528-5d32-9478-0270db9fe56b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.RatFunc.Valuation
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Mathlib.NumberTheory.RatFunc.Ostrowski
import Theorems.FLT.Thm_P2M_Dup_AlgebraicCurve_Place_adicValuation_valuationSubring
import Theorems.FLT.Thm_AlgebraicCurve_Place_adicValuation_isRankOneDiscrete
import Theorems.FLT.Thm_AlgebraicCurve_Place_adicValuation_isTrivialOn
import Definitions.FLT.Def_P2M_Util

/-!
# Places of K(t)/K other than the finite ones lie at infinity

Theorem statement:
`AlgebraicCurve.RationalFunctionField.toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum`
(`b16d57bd-64f3-5e5d-9a5b-eee948a2c874`), by Claude, 2026-09-05.

Proof: submission `1a0a4486-f528-5d32-9478-0270db9fe56b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $v$ be a place of the rational function field $\mathrm{RatFunc}\,K$ over
$K$ in the sense of the project structure `Place`: a datum consisting of a valuation subring
$v.\mathrm{toValuationSubring}$ of $\mathrm{RatFunc}\,K$ which contains the image of $K$ under the
structure map, which is not the whole field, and which is a principal ideal ring. Assume that for
every height-one prime $w$ of the polynomial ring $K[X]$ the place $v$ differs from
`Place.ofHeightOneSpectrum w`, the place whose valuation subring is that of the $w$-adic valuation
of $K[X]$ extended to its fraction field $\mathrm{RatFunc}\,K$. The conclusion is an equality of
subrings of $\mathrm{RatFunc}\,K$: $v.\mathrm{toValuationSubring}$ equals the valuation subring of
Mathlib's valuation at infinity `RatFunc.inftyValuation K`, i.e. the ring of rational functions
whose numerator degree does not exceed its denominator degree. The hypothesis is a statement about
places, not merely about valuation subrings, and the conclusion identifies only the subring, not a
normalised valuation.

This is the classification of the places of the rational function field $K(t)$ trivial on $K$ (the
function-field analogue of Ostrowski's theorem): the finite places come from the height-one primes
of $K[X]$, and the remaining one is the place at infinity. It is used in the divisor-theoretic
treatment of $\mathbb{P}^1$, where it feeds the computation of the degree of the place at infinity
and of the order function attached to it at that place.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum

open AlgebraicCurve
open IsDedekindDomain WithZero IsLocalRing
open scoped Polynomial

theorem solution {K : Type*} [Field K] [DecidableEq (RatFunc K)] (v : Place K (RatFunc K)) (hv : ∀ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v ≠ Place.ofHeightOneSpectrum w) : v.toValuationSubring = (RatFunc.inftyValuation K).valuationSubring := by
  have := v.adicValuation_isRankOneDiscrete
  have := v.adicValuation_isTrivialOn
  rcases (RatFunc.valuation_isEquiv_infty_or_adic (v := v.adicValuation)).or with h | h
  · exact v.adicValuation_valuationSubring.symm.trans
      ((Valuation.isEquiv_iff_valuationSubring _ _).mp h)
  · obtain ⟨w, hw, -⟩ := h
    exact absurd (Place.ext (v.adicValuation_valuationSubring.symm.trans
      ((Valuation.isEquiv_iff_valuationSubring _ _).mp hw))) (hv w)

end S_AlgebraicCurve_RationalFunctionField_toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.RationalFunctionField.toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum {K : Type*} [Field K] [DecidableEq (RatFunc K)] (v : Place K (RatFunc K)) (hv : ∀ w : IsDedekindDomain.HeightOneSpectrum (Polynomial K), v ≠ Place.ofHeightOneSpectrum w) : v.toValuationSubring = (RatFunc.inftyValuation K).valuationSubring := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_toValuationSubring_eq_of_forall_ne_ofHeightOneSpectrum.solution v hv

end publicSection
