/-
Based on Prove2Me node HeckeEis.eichlerShimuraMap_eq_coeffH1parMk
(c45b784f-df99-52af-9e4f-b91b69432be5) by Claude (2026-09-05).

Proof based on Prove2Me submission 0f02be45-b7e6-5874-9237-54a5c34d271d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_HeckeEis_EichlerIntegral

import Theorems.FLT.Thm_HeckeEis_IsEichlerIntegral_exists_sub_eq_const
import Theorems.FLT.Thm_HeckeEis_IsEquivariantPrimitiveWith_cocycle_sub_cocycle_mem_coeffCoboundaries

/-!
# Eichler–Shimura map computed by any admissible Eichler integral

Theorem statement: `HeckeEis.eichlerShimuraMap_eq_coeffH1parMk`
(`c45b784f-df99-52af-9e4f-b91b69432be5`), by Claude, 2026-09-05.

Proof: submission `0f02be45-b7e6-5874-9237-54a5c34d271d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix natural numbers $n$ and $N$ and a function $f\colon\mathfrak H\to\mathbb C$ on the upper
half-plane, and let $V_n =$ [`HeckeEis.BinaryForm ℂ n`](def/HeckeEis_BinaryFormRep.html#L25) be the
space of homogeneous polynomials of degree $n$ in two variables $X_0,X_1$ over $\mathbb C$, on which
$\rho$ denotes the representation `(HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0
N).subtype`, i.e. $\mathrm{SL}_2(\mathbb Z)$ acting by the linear substitution $X_j\mapsto\sum_i
M_{ij}X_i$, restricted to $\Gamma_0(N)$. Let $F\colon\mathfrak H\to V_n$ satisfy three hypotheses:
(i) $F$ is an Eichler integral of $f$, meaning that for every exponent $d$ and every
$\tau\in\mathfrak H$ the coefficient function $z\mapsto \mathrm{coeff}_d(F(z))$ has complex
derivative $f(\tau)\,\mathrm{coeff}_d\big((\tau X_0+X_1)^n\big)$ at $\tau$; (ii) $F$ is an
equivariant primitive for $\rho$, i.e. for each $\gamma\in\Gamma_0(N)$ the function $\tau\mapsto
F(\gamma\tau)-\rho(\gamma)F(\tau)$ is a constant of $V_n$; (iii) the associated cocycle
$z_F(\gamma)=F(\gamma\cdot i)-\rho(\gamma)F(i)$ is parabolic, i.e.
$z_F(\gamma)\in\mathrm{range}(\rho(\gamma)-1)$ whenever $\mathrm{tr}(\gamma)^2=4$. The conclusion is
that [`HeckeEis.eichlerShimuraMap n N f`](def/HeckeEis_EichlerIntegral.html#L114), defined by
choosing some such $F$ when one exists and $0$ otherwise, equals the class of $z_F$ in
[`HeckeEis.coeffH1par`](def/Gamma0CoeffCohomology.html#L100), the quotient of the module of
parabolic cocycles by those which are coboundaries.

This identifies the Eichler–Shimura class attached to $f$ with the cohomology class of the cocycle
of any Eichler integral of $f$ that is an equivariant primitive with parabolic cocycle, so that the
choice implicit in the definition is immaterial. It is the computational entry point for the
additivity and Hecke-compatibility statements about the Eichler–Shimura map, being cited by
[`HeckeEis.eichlerShimuraMap_add`](thm.html#HeckeEis.eichlerShimuraMap_add),
[`HeckeEis.eichlerShimuraMap_heckeTLin`](thm.html#HeckeEis.eichlerShimuraMap_heckeTLin) and
[`HeckeEis.eichlerShimuraMap_heckeULin`](thm.html#HeckeEis.eichlerShimuraMap_heckeULin).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_eichlerShimuraMap_eq_coeffH1parMk.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

noncomputable section

namespace HeckeEis

open UpperHalfPlane CongruenceSubgroup

theorem SolMain.eqmk (n N : ℕ) (f : ℍ → ℂ) {F : ℍ → ↥(BinaryForm ℂ n)}
    (hEI : IsEichlerIntegral n f F)
    (hF : IsEquivariantPrimitiveWith ((binaryFormRepSL ℂ n).comp (Gamma0 N).subtype) F)
    (hpar : IsParabolicCocycle ((binaryFormRepSL ℂ n).comp (Gamma0 N).subtype) hF.cocycle) :
    eichlerShimuraMap n N f
      = coeffH1parMk _ ⟨hF.cocycle, ⟨hF.cocycle_mem_coeffCocycles, hpar⟩⟩ := by
  obtain ⟨F₀, hEI₀, h₀, hpar₀, heq⟩ := eichlerShimuraMap_def n N f hEI hF hpar
  rw [heq, ← sub_eq_zero, ← map_sub, coeffH1parMk_eq_zero_iff]
  obtain ⟨v, hv⟩ := hEI₀.exists_sub_eq_const hEI
  exact h₀.cocycle_sub_cocycle_mem_coeffCoboundaries hF hv

end HeckeEis

end

theorem solution (n N : ℕ) (f : UpperHalfPlane → ℂ)
    {F : UpperHalfPlane → ↥(HeckeEis.BinaryForm ℂ n)}
    (hEI : HeckeEis.IsEichlerIntegral n f F)
    (hF : HeckeEis.IsEquivariantPrimitiveWith
      ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) F)
    (hpar : HeckeEis.IsParabolicCocycle
      ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) hF.cocycle) :
    HeckeEis.eichlerShimuraMap n N f
      = HeckeEis.coeffH1parMk _ ⟨hF.cocycle, ⟨hF.cocycle_mem_coeffCocycles, hpar⟩⟩ :=
  HeckeEis.SolMain.eqmk n N f hEI hF hpar

end privateSection

public section publicSection

theorem HeckeEis.eichlerShimuraMap_eq_coeffH1parMk (n N : ℕ) (f : UpperHalfPlane → ℂ)
    {F : UpperHalfPlane → ↥(HeckeEis.BinaryForm ℂ n)}
    (hEI : HeckeEis.IsEichlerIntegral n f F)
    (hF : HeckeEis.IsEquivariantPrimitiveWith
      ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) F)
    (hpar : HeckeEis.IsParabolicCocycle
      ((HeckeEis.binaryFormRepSL ℂ n).comp (CongruenceSubgroup.Gamma0 N).subtype) hF.cocycle) :
    HeckeEis.eichlerShimuraMap n N f
      = HeckeEis.coeffH1parMk _ ⟨hF.cocycle, ⟨hF.cocycle_mem_coeffCocycles, hpar⟩⟩ := _root_.solution n N f hEI hF hpar

end publicSection
