/-
Based on Prove2Me node ModularCurve.deg_jLinePlace1728
(60ae1463-3d99-596c-bf72-18deed415732) by Claude (2026-09-05).

Proof based on Prove2Me submission 5f6bcf1c-a579-5ad7-b4fe-a50f72f40176
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JLinePlaces

import Definitions.FLT.Def_P2M_Util

/-!
# The j-line place at j=1728 has degree 1

Theorem statement: `ModularCurve.deg_jLinePlace1728` (`60ae1463-3d99-596c-bf72-18deed415732`), by
Claude, 2026-09-05.

Proof: submission `5f6bcf1c-a579-5ad7-b4fe-a50f72f40176`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let `jq` be the transcendental element over $\mathbb{Q}$ out of which the $j$-line is built, and let
$\mathbb{Q}\langle$`jq`$\rangle$ denote the intermediate field it generates; `jLineRingEquiv` is the
ring isomorphism $\mathrm{RatFunc}\,\mathbb{Q} \cong \mathbb{Q}\langle$`jq`$\rangle$ sending the
indeterminate to `jq`, obtained from the transcendence of `jq`. Here a place of an extension $F/K$
is a valuation subring of $F$ that contains the image of $K$, is not the whole of $F$, and is a
principal ideal ring, and its degree is the $K$-dimension of the residue field of that valuation
subring. The place `jLinePlace1728` is the transport along `jLineRingEquiv` (which fixes
$\mathbb{Q}$, so that the transported valuation subring, the preimage under the inverse isomorphism,
is again a place over $\mathbb{Q}$) of the finite place `placeOfPoint ℚ 1728` of
$\mathrm{RatFunc}\,\mathbb{Q}$ attached to the irreducible polynomial $X - 1728$. The theorem
asserts that the degree of `jLinePlace1728` equals $1$; equivalently, its residue field is
$\mathbb{Q}$ itself, so the place is rational.

This records that the point $j = 1728$ of the $j$-line is a rational place, one of the two
distinguished points (together with $j = 0$, and the cusp) around which ramification of the modular
covers is concentrated. It is used in the identification of the number of points of the modular
curve with $\bar{j} = 1728$, respectively $\bar{j} = 0$, with the counts $\nu_2$ and $\nu_3$ of
elliptic points of order $2$ and $3$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_deg_jLinePlace1728.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_deg_jLinePlace1728

open IntermediateField AlgebraicCurve AlgebraicCurve.RationalFunctionField

attribute [local instance 2000] RatFunc.instAlgebraOfPolynomial
attribute [local instance] ModularCurve.instDecidableEqRatFuncRat

theorem solution : ModularCurve.jLinePlace1728.deg = 1 := by
  unfold ModularCurve.jLinePlace1728
  rw [Place.deg_congrRingEquiv]
  exact deg_placeOfPoint ℚ 1728

end S_ModularCurve_deg_jLinePlace1728
end P2MW
export P2MW.S_ModularCurve_deg_jLinePlace1728 (solution)

end privateSection

public section publicSection


open IntermediateField AlgebraicCurve
theorem ModularCurve.deg_jLinePlace1728 : ModularCurve.jLinePlace1728.deg = 1 := _root_.P2MW.S_ModularCurve_deg_jLinePlace1728.solution

end publicSection
