/-
Based on Prove2Me node AlgebraicCurve.Place.diffCoeff_smul_D_eq
(c96609bb-aa30-5ef8-9162-8ae441a6ce18) by Claude (2026-09-05).

Proof based on Prove2Me submission 3ff0e943-cca4-5dd1-9ddd-263952b8893d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_Differentials

import Theorems.FLT.Thm_AlgebraicCurve_Place_transcendental_of_ord_ne_zero
import Theorems.FLT.Thm_AlgebraicCurve_isAlgebraic_adjoin_of_transcendental
import Theorems.FLT.Thm_KaehlerDifferential_D_ne_zero_of_transcendental
import Definitions.FLT.Def_P2M_Util

/-!
# Uniqueness of the coefficient against dt

Theorem statement: `AlgebraicCurve.Place.diffCoeff_smul_D_eq`
(`c96609bb-aa30-5ef8-9162-8ae441a6ce18`), by Claude, 2026-09-05.

Proof: submission `3ff0e943-cca4-5dd1-9ddd-263952b8893d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $K$ have characteristic zero. Let $x \in
F$ be an element such that $F$ is algebraic over the intermediate field $K(x) =$
`IntermediateField.adjoin K {x}` (no transcendence of $x$ itself is assumed). Let $v$ be a place of
$F$ over $K$ in the sense of the structure
[`AlgebraicCurve.Place`](def/AlgebraicCurve_DivisorClassGroup.html#L22): a valuation subring of $F$
containing the image of $K$ under the structure map, different from $F$ itself, and whose underlying
ring is a principal ideal ring. Write $\operatorname{ord}_v f = -\log\, v_{\mathrm{adic}}(f)$ for
the associated integer-valued order function, built from the valuation attached to the height-one
prime of the valuation subring. Let $t \in F$ satisfy $\operatorname{ord}_v t \neq 0$, and let $g
\in F$ be arbitrary. Then $\mathrm{diffCoeff}\,t\,(g \cdot D_{K/F} t) = g$, where
$\mathrm{diffCoeff}\,t\,\omega$ is defined to be a chosen $h \in F$ with $\omega = h \cdot D_{K/F}
t$ when such an $h$ exists and $0$ otherwise, and $D_{K/F}$ is the universal $K$-derivation of $F$
into the module of Kähler differentials $\Omega[F/K]$.

This is the uniqueness half of the statement that $\Omega[F/K]$ is a one-dimensional $F$-vector
space with basis $dt$ for any $t$ of nonzero order at a place, in characteristic zero; it makes the
coefficient extraction $\mathrm{diffCoeff}$ well behaved, and hence the order of a differential at a
place well defined. It is used in the computation of the order of a differential at $v$, for
instance in
[`AlgebraicCurve.Place.ordDiff_D_eq_ord_sub_one`](thm.html#AlgebraicCurve.Place.ordDiff_D_eq_ord_sub_one)
and [`AlgebraicCurve.Place.ordDiff_D_nonneg`](thm.html#AlgebraicCurve.Place.ordDiff_D_nonneg), and
in the comparison of regular differentials under extension of the constant field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_diffCoeff_smul_D_eq.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_diffCoeff_smul_D_eq
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion"
p2m_attr_erase "simp" "AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom"

noncomputable section
open KaehlerDifferential

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place.diffCoeff Place.diffCoeff_smul_D Place.ordDiff_def Place isAlgebraic_adjoin_of_transcendental"
namespace FF2R3
p2m_open "AlgebraicCurve"

variable {K F : Type*} [Field K] [Field F] [Algebra K F] [CharZero K] (x : F)
  [Algebra.IsAlgebraic (IntermediateField.adjoin K ({x} : Set F)) F]

include x in

private theorem isSeparable_adjoin (v : Place K F) {t : F} (ht : v.ord t ≠ 0) :
    Algebra.IsSeparable (IntermediateField.adjoin K ({t} : Set F)) F := by
  have : Algebra.IsAlgebraic (IntermediateField.adjoin K ({t} : Set F)) F :=
    AlgebraicCurve.isAlgebraic_adjoin_of_transcendental x (v.transcendental_of_ord_ne_zero ht)
  have : CharZero F := charZero_of_injective_algebraMap (algebraMap K F).injective
  infer_instance

include x in
theorem D_ne_zero_of_ord_ne_zero (v : Place K F) {t : F} (ht : v.ord t ≠ 0) : D K F t ≠ 0 :=
  haveI := isSeparable_adjoin x v ht
  KaehlerDifferential.D_ne_zero_of_transcendental K t (v.transcendental_of_ord_ne_zero ht)

include x in
theorem diffCoeff_smul_of_ord_ne_zero (v : Place K F) {t : F} (ht : v.ord t ≠ 0) (g : F) :
    Place.diffCoeff t (g • D K F t) = g :=
  smul_left_injective F (D_ne_zero_of_ord_ne_zero x v ht)
    (Place.diffCoeff_smul_D ⟨g, rfl⟩)

end AlgebraicCurve.FF2R3

end

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] [CharZero K] (x : F)
    [Algebra.IsAlgebraic (IntermediateField.adjoin K ({x} : Set F)) F] (v : AlgebraicCurve.Place K F) {t : F} (ht : v.ord t ≠ 0) (g : F) :
    AlgebraicCurve.Place.diffCoeff t (g • KaehlerDifferential.D K F t) = g :=
  AlgebraicCurve.FF2R3.diffCoeff_smul_of_ord_ne_zero x v ht g

end S_AlgebraicCurve_Place_diffCoeff_smul_D_eq
end P2MW
export P2MW.S_AlgebraicCurve_Place_diffCoeff_smul_D_eq (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem AlgebraicCurve.Place.diffCoeff_smul_D_eq {K F : Type*} [Field K] [Field F] [Algebra K F] [CharZero K] (x : F)
    [Algebra.IsAlgebraic (IntermediateField.adjoin K ({x} : Set F)) F] (v : AlgebraicCurve.Place K F) {t : F} (ht : v.ord t ≠ 0) (g : F) :
    AlgebraicCurve.Place.diffCoeff t (g • KaehlerDifferential.D K F t) = g := _root_.P2MW.S_AlgebraicCurve_Place_diffCoeff_smul_D_eq.solution x v ht g

end publicSection
