/-
Based on Prove2Me node ModularCurve.aeval_jq_eq_zero
(6b297b57-a728-5c3d-8a7f-cf5ca651241c) by Claude (2026-09-05).

Proof based on Prove2Me submission f457ae50-edbf-5862-b501-c5254443a6dd
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0

import Definitions.FLT.Def_P2M_Util

/-!
# A rational polynomial vanishing at j(q) is zero

Theorem statement: `ModularCurve.aeval_jq_eq_zero` (`6b297b57-a728-5c3d-8a7f-cf5ca651241c`), by
Claude, 2026-09-05.

Proof: submission `f457ae50-edbf-5862-b501-c5254443a6dd`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $p$ be a polynomial in one variable over $\mathbb{Q}$, and suppose that evaluating $p$ at the
Laurent series `jq` gives $0$, that is, $p(\mathrm{jq}) = 0$ in the field of Laurent series
`LaurentSeries ℚ` (Hahn series over $\mathbb{Q}$ with value group $\mathbb{Z}$), where the
evaluation is the $\mathbb{Q}$-algebra map `Polynomial.aeval`. Here `jq` is the element $q^{-1}\cdot
\mathrm{jNumQ}(q)$, obtained as the product of the Hahn series `HahnSeries.single (-1) 1` supported
in degree $-1$ with coefficient $1$ and the image under `HahnSeries.ofPowerSeries` of `jNumQ`, the
power series over $\mathbb{Q}$ got from the integral power series `jNum` by the coefficientwise ring
map $\mathbb{Z} \to \mathbb{Q}$; thus `jq` is the formal $q$-expansion of the modular $j$-invariant.
The conclusion is that $p = 0$. Equivalently, `jq` is transcendental over $\mathbb{Q}$ inside
$\mathbb{Q}((q))$.

This is the basic transcendence statement underlying the construction of the modular function fields
of $X_0(N)$ inside $\mathbb{Q}((q))$: the $q$-expansion of $j$ satisfies no algebraic relation over
$\mathbb{Q}$. It is used for
[`ModularCurve.transcendental_jq`](thm.html#ModularCurve.transcendental_jq) and, after substituting
$q \mapsto q^N$, for [`ModularCurve.transcendental_jqN`](thm.html#ModularCurve.transcendental_jqN).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_aeval_jq_eq_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_aeval_jq_eq_zero

open ModularCurve IntermediateField

noncomputable section

theorem solution {p : Polynomial ℚ} (hp : Polynomial.aeval jq p = 0) : p = 0 :=by
  by_contra hp0
  set n := p.natDegree with hn
  have hcoeff : (Polynomial.aeval jq p).coeff (-(n : ℤ)) = p.coeff n := by
    rw [Polynomial.aeval_def, Polynomial.eval₂_eq_sum_range, HahnSeries.coeff_sum,
      Finset.sum_eq_single n]
    · rw [algebraMap_apply_eq_single, HahnSeries.coeff_single_zero_mul, coeff_jq_pow_self,
        mul_one]
    · intro i hi hin
      have hilt : i < n := lt_of_le_of_ne (Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)) hin
      rw [algebraMap_apply_eq_single, HahnSeries.coeff_single_zero_mul, coeff_jq_pow_of_lt,
        mul_zero]
      omega
    · intro hn'
      exact absurd (Finset.self_mem_range_succ n) hn'
  rw [hp] at hcoeff
  simp only [HahnSeries.coeff_zero] at hcoeff
  exact hp0 (Polynomial.leadingCoeff_eq_zero.mp hcoeff.symm)

end

end S_ModularCurve_aeval_jq_eq_zero
end P2MW
export P2MW.S_ModularCurve_aeval_jq_eq_zero (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve IntermediateField
theorem ModularCurve.aeval_jq_eq_zero {p : Polynomial ℚ} (hp : Polynomial.aeval jq p = 0) : p = 0 := _root_.P2MW.S_ModularCurve_aeval_jq_eq_zero.solution hp

end publicSection
