/-
Based on Prove2Me node IsAddCyclic.of_squarefree_natCard
(14855747-d0f6-58c2-8d76-6caa8c9e1383) by Claude (2026-09-05).

Proof based on Prove2Me submission fa1809a7-8c5a-585b-a63d-4367dd32ade8
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Algebra.Squarefree.Basic
public import Mathlib.SetTheory.Cardinal.Finite

import Mathlib.GroupTheory.SpecificGroups.ZGroup
import Definitions.FLT.Def_P2M_Util

/-!
# Abelian groups of squarefree order are cyclic

Theorem statement: `IsAddCyclic.of_squarefree_natCard` (`14855747-d0f6-58c2-8d76-6caa8c9e1383`), by
Claude, 2026-09-05.

Proof: submission `fa1809a7-8c5a-585b-a63d-4367dd32ade8`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $A$ be an additive abelian group (no finiteness is assumed as a separate hypothesis) and suppose
the natural number $\mathrm{Nat.card}\,A$ is squarefree, i.e. every element of $\mathbb{N}$ whose
square divides it is a unit. Since a squarefree natural number is nonzero, this hypothesis already
forces $A$ to be finite, with $\mathrm{Nat.card}\,A$ its order. The conclusion is `IsAddCyclic A`:
the group $A$ is cyclic, that is, there is an element $g \in A$ such that every element of $A$ is an
integer multiple of $g$. Note that the hypothesis is on the cardinality in the `Nat.card` sense, so
for an infinite $A$ the value would be $0$, which is not squarefree; thus the statement is exactly
the assertion that a finite abelian group whose order is squarefree is cyclic, phrased additively.

This is the classical fact that a finite abelian group of squarefree order is cyclic. In this
development it supplies the cyclicity of subgroups of torsion groups of elliptic curves of
squarefree order, and is used by
[`WeierstrassCurve.Affine.IsogenyEndDatum.aeval_j_diag_eq_zero_of_finrankAlong_eq`](thm.html#WeierstrassCurve.Affine.IsogenyEndDatum.aeval_j_diag_eq_zero_of_finrankAlong_eq).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_IsAddCyclic_of_squarefree_natCard.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_IsAddCyclic_of_squarefree_natCard

theorem solution
    {A : Type*} [AddCommGroup A] (hA : Squarefree (Nat.card A)) : IsAddCyclic A := by
  have : Finite A := Nat.finite_of_card_ne_zero hA.ne_zero
  rw [← isCyclic_multiplicative_iff]
  have hM : Squarefree (Nat.card (Multiplicative A)) := by
    rwa [Nat.card_congr Multiplicative.toAdd]
  have : IsZGroup (Multiplicative A) := IsZGroup.of_squarefree hM
  exact IsCyclic.of_exponent_eq_card (IsZGroup.exponent_eq_card (Multiplicative A))

end S_IsAddCyclic_of_squarefree_natCard
end P2MW
export P2MW.S_IsAddCyclic_of_squarefree_natCard (solution)

end privateSection

public section publicSection

theorem IsAddCyclic.of_squarefree_natCard
    {A : Type*} [AddCommGroup A] (hA : Squarefree (Nat.card A)) : IsAddCyclic A := _root_.P2MW.S_IsAddCyclic_of_squarefree_natCard.solution hA

end publicSection
