/-
Based on Prove2Me node ModularCurve.dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0
(2ce1ed64-8cdd-574d-99d7-02f3ead4fec5) by Claude (2026-09-05).

Proof based on Prove2Me submission 76485080-d23d-5c87-b12e-eb8b70859a13
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff
public import Definitions.FLT.Def_ModularCurve_X1

import Mathlib.FieldTheory.Relrank
import Mathlib.RingTheory.Flat.TorsionFree
import Theorems.FLT.Thm_ModularCurve_finrank_adjoin_jqModC_modularFunctionFieldFullC_eq_dedekindPsi
import Theorems.FLT.Thm_ModularCurve_modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0
import Definitions.FLT.Def_P2M_Util

/-!
# Degree at least ψ(M) over K(j) for X₀(M)

Theorem statement: `ModularCurve.dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0`
(`2ce1ed64-8cdd-574d-99d7-02f3ead4fec5`), by Claude, 2026-09-05.

Proof: submission `76485080-d23d-5c87-b12e-eb8b70859a13`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and $M$ a positive integer whose image in $K$ is nonzero. Let $F =$
[`ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M)`](def/ModularCurve_X1.html#L101)
be the intermediate field of the Laurent series field `LaurentSeries K` generated over $K$ by the
set of all quotients $\overline{p_f}/\overline{p_g}$, where $f,g$ are modular forms of one and the
same weight $k \in \mathbb{Z}$ for $\Gamma_0(M)$ regarded inside $\mathrm{GL}_2(\mathbb{R})$, $p_f,
p_g$ are power series over $\mathbb{Z}$ satisfying `IsIntegralQExp f pf` and `IsIntegralQExp g pg`,
and the coefficientwise image $\overline{p_g}$ of $p_g$ in $K$ is nonzero. Let $x \in F$ be an
element whose underlying Laurent series is [`ModularCurve.jqModC
K`](def/ModularCurve_JqCoeff.html#L15), that is $q^{-1}$ times the image in $K$ of the power series
$E_4^3 \eta^{-24}$ (the $q$-expansion of the modular invariant $j$). Assume that $F$ is
finite-dimensional over the intermediate field $K(x)$ obtained by adjoining $x$ to $K$ inside $F$.
Then $\psi(M) \le [F : K(x)]$, where $\psi(M)$ is [`ModularCurve.dedekindPsi
M`](def/ModularCurve_X0.html#L201), defined as $\sum_{d \mid M,\ d \text{ squarefree}} M/d$.

This is Igusa's lower bound for the degree of $X_0(M)$ over the $j$-line, in $q$-expansion form and
over an arbitrary coefficient field in which $M$ is invertible. It is used in the computation of
relative degrees and indices for the congruence subgroups $\Gamma_0$ and $\Gamma_H$, and in the
local analysis of valuation subrings on $X_0(p)$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0
p2m_attr_erase "instance" "ModularCurve.PhiGen.instNeZeroPhiGenCosetA WeierstrassCurve.Affine.Point.instFinite"
p2m_attr_erase "simp" "ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

private theorem igT3s_finrank_adjoin_eq_relfinrank {K E : Type*} [Field K] [Field E] [Algebra K E]
    (F : IntermediateField K E) (x : F) :
    Module.finrank (IntermediateField.adjoin K ({x} : Set F)) F =
      (IntermediateField.adjoin K ({(x : E)} : Set E)).relfinrank F := by
  have hlift : IntermediateField.lift (IntermediateField.adjoin K ({x} : Set F)) =
      IntermediateField.adjoin K ({(x : E)} : Set E) := by
    rw [IntermediateField.lift_adjoin]; simp
  have hle : IntermediateField.adjoin K ({(x : E)} : Set E) ≤ F := by
    rw [← hlift]; exact IntermediateField.lift_le _
  rw [IntermediateField.relfinrank_eq_finrank_of_le hle]
  let i : (IntermediateField.adjoin K ({x} : Set F)) ≃+*
      (IntermediateField.adjoin K ({(x : E)} : Set E)) :=
    ((IntermediateField.liftAlgEquiv (IntermediateField.adjoin K ({x} : Set F))).trans
      (IntermediateField.equivOfEq hlift)).toRingEquiv
  let j : F ≃+* (IntermediateField.extendScalars hle) := RingEquiv.refl _
  refine Algebra.finrank_eq_of_equiv_equiv i j ?_
  ext a
  rfl

theorem solution
    (K : Type*) [Field K] (M : ℕ) [NeZero M] (hM : (M : K) ≠ 0)
    (x : ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))
    (hx : (x : LaurentSeries K) = ModularCurve.jqModC K)
    [FiniteDimensional
      (IntermediateField.adjoin K
        ({x} : Set (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))))
      (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))] :
    ModularCurve.dedekindPsi M ≤
      Module.finrank
        (IntermediateField.adjoin K
          ({x} : Set (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))))
        (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M)) := by
  have hn : 0 < Module.finrank (IntermediateField.adjoin K
      ({x} : Set (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))))
      (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M)) := Module.finrank_pos
  have h1 : Module.finrank (IntermediateField.adjoin K
      ({x} : Set (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))))
      (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M)) =
      (IntermediateField.adjoin K ({ModularCurve.jqModC K} : Set (LaurentSeries K))).relfinrank
        (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M)) := by
    rw [← hx]
    exact igT3s_finrank_adjoin_eq_relfinrank _ x
  have h2 : (IntermediateField.adjoin K ({ModularCurve.jqModC K} : Set (LaurentSeries K))).relfinrank
      (ModularCurve.modularFunctionFieldFullC K M) = ModularCurve.dedekindPsi M := by
    rw [← ModularCurve.finrank_adjoin_jqModC_modularFunctionFieldFullC_eq_dedekindPsi K M hM]
    exact (igT3s_finrank_adjoin_eq_relfinrank (ModularCurve.modularFunctionFieldFullC K M)
      ⟨ModularCurve.jqModC K, ModularCurve.jqModC_mem_full K M⟩).symm
  have hAB : IntermediateField.adjoin K ({ModularCurve.jqModC K} : Set (LaurentSeries K)) ≤
      ModularCurve.modularFunctionFieldFullC K M :=
    IntermediateField.adjoin_le_iff.mpr (Set.singleton_subset_iff.mpr (ModularCurve.jqModC_mem_full K M))
  have hBC : ModularCurve.modularFunctionFieldFullC K M ≤
      ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M) :=
    ModularCurve.modularFunctionFieldFullC_le_qExpFunctionFieldC_gamma0 K M
  have htower := IntermediateField.relfinrank_mul_relfinrank hAB hBC
  rw [h2, ← h1] at htower
  exact Nat.le_of_dvd hn ⟨_, htower.symm⟩

end S_ModularCurve_dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0
end P2MW
export P2MW.S_ModularCurve_dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0 (solution)

end privateSection

public section publicSection

theorem ModularCurve.dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0
    (K : Type*) [Field K] (M : ℕ) [NeZero M] (hM : (M : K) ≠ 0)
    (x : ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))
    (hx : (x : LaurentSeries K) = ModularCurve.jqModC K)
    [FiniteDimensional
      (IntermediateField.adjoin K
        ({x} : Set (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))))
      (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))] :
    ModularCurve.dedekindPsi M ≤
      Module.finrank
        (IntermediateField.adjoin K
          ({x} : Set (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M))))
        (ModularCurve.qExpFunctionFieldC K (CongruenceSubgroup.Gamma0 M)) := _root_.P2MW.S_ModularCurve_dedekindPsi_le_finrank_adjoin_qExpFunctionFieldC_gamma0.solution K M hM x hx

end publicSection
