/-
Based on Prove2Me node HeckeEis.exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self
(f0572a19-e7e9-5a76-9764-969b69c4c9d7) by Claude (2026-09-05).

Proof based on Prove2Me submission 366cfae1-47bc-538a-be49-9d1ca67982e6
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_HeckeEis_BinaryFormRep

import Theorems.FLT.Thm_HeckeEis_exists_eq_smul_X_pow_of_binaryFormRepSL_T_zpow_eq_self
import Definitions.FLT.Def_P2M_Util

/-!
# Fixed forms of a lower unipotent are multiples of X₁ⁿ

Theorem statement: `HeckeEis.exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self`
(`f0572a19-e7e9-5a76-9764-969b69c4c9d7`), by Claude, 2026-09-05.

Proof: submission `366cfae1-47bc-538a-be49-9d1ca67982e6`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$ be a commutative ring which is an integral domain, let $n$ be a natural number, and let $h$
be an integer whose image in $R$ is nonzero; assume moreover that the image in $R$ of every integer
$j$ with $1 \le j \le n$ is nonzero. Let $g$ be an element of $\mathrm{SL}_2(\mathbb{Z})$ whose
underlying $2\times 2$ integer matrix is $!![1,0;h,1]$, and let $P$ belong to [`HeckeEis.BinaryForm
R n`](def/HeckeEis_BinaryFormRep.html#L25), i.e. the submodule of $R$-homogeneous polynomials of
degree $n$ in $R[X_0,X_1] =$ `MvPolynomial (Fin 2) R`. The action used is [`HeckeEis.binaryFormRepSL
R n`](def/HeckeEis_BinaryFormRep.html#L61), the representation of $\mathrm{SL}_2(\mathbb{Z})$ on
this submodule induced by the substitution algebra endomorphism
[`HeckeEis.binarySubst`](def/HeckeEis_BinaryFormRep.html#L28), which sends $X_j$ to $\sum_{i} M_{ij}
X_i$ for the matrix $M$ of the group element; for $M = !![1,0;h,1]$ this is $X_0 \mapsto X_0 +
hX_1$, $X_1 \mapsto X_1$. Assume that $P$ is fixed by $g$ under this action, that is $P(X_0 + hX_1,
X_1) = P(X_0,X_1)$. The conclusion is that there exists $c \in R$ with $P = c \cdot X_1^{\,n}$ as
elements of $R[X_0,X_1]$.

This is the determination of the fixed subspace of a lower triangular unipotent matrix acting on
binary forms of degree $n$ (the symmetric power $\mathrm{Sym}^n$ of the standard representation), in
the case where $h$ and the integers $1,\dots,n$ are invertible enough to be nonzero in $R$: the
fixed vectors form the line spanned by $X_1^n$. It is applied to
$\begin{pmatrix}1&0\\N&1\end{pmatrix} \in \Gamma_0(N)$ in the proof that certain parabolic
cohomology classes vanish, namely in
[`HeckeEis.coeffH1par_binaryFormRepSL_int_eq_zero_of_smul_eq_zero`](thm.html#HeckeEis.coeffH1par_binaryFormRepSL_int_eq_zero_of_smul_eq_zero).
The group element is specified by its matrix rather than by a fixed presentation, so any element
with that matrix may be used.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HeckeEis_exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self

namespace HeckeEis
p2m_export "HeckeEis" "BinaryForm binarySubst binarySubst_X binaryFormRepSL binaryFormRepSL_apply_coe exists_eq_smul_X_pow_of_binaryFormRepSL_T_zpow_eq_self"
p2m_open "HeckeEis"

open MvPolynomial
open scoped MatrixGroups

theorem UnipotentFixedAux.eq_S_mul_T_zpow_neg_mul_S_inv {h : ℤ} (g : SL(2, ℤ))
    (hg : (g : Matrix (Fin 2) (Fin 2) ℤ) = !![1, 0; h, 1]) :
    g = ModularGroup.S * ModularGroup.T ^ (-h) * ModularGroup.S⁻¹ := by
  rw [eq_mul_inv_iff_mul_eq]
  apply Subtype.ext
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.SpecialLinearGroup.coe_mul, hg, ModularGroup.coe_T_zpow, ModularGroup.coe_S]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, Fin.sum_univ_two]

theorem UnipotentFixedAux.binarySubst_S_X_zero_pow (R : Type*) [CommRing R] (n : ℕ) :
    binarySubst R ((ModularGroup.S : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) (MvPolynomial.X 0 ^ n)
      = (MvPolynomial.X 1 ^ n : MvPolynomial (Fin 2) R) := by
  rw [map_pow, binarySubst_X, ModularGroup.coe_S]
  simp [Fin.sum_univ_two]

open UnipotentFixedAux in

theorem SolMain.A3 {R : Type*} [CommRing R] [IsDomain R] (n : ℕ)
    {h : ℤ} (hh : (h : R) ≠ 0) (hn : ∀ j : ℕ, 1 ≤ j → j ≤ n → (j : R) ≠ 0)
    (g : SL(2, ℤ)) (hg : (g : Matrix (Fin 2) (Fin 2) ℤ) = !![1, 0; h, 1])
    (P : ↥(BinaryForm R n)) (hP : binaryFormRepSL R n g P = P) :
    ∃ c : R, (P : MvPolynomial (Fin 2) R) = c • MvPolynomial.X 1 ^ n := by
  have hgS := eq_S_mul_T_zpow_neg_mul_S_inv g hg
  set Q : ↥(BinaryForm R n) := binaryFormRepSL R n ModularGroup.S⁻¹ P with hQ
  have hQfix : binaryFormRepSL R n (ModularGroup.T ^ (-h)) Q = Q := by
    have h1 : binaryFormRepSL R n ModularGroup.S⁻¹ (binaryFormRepSL R n g P) = Q := by rw [hP]
    rwa [hgS, map_mul, map_mul, Module.End.mul_apply, Module.End.mul_apply, ← Module.End.mul_apply (binaryFormRepSL R n _),
      ← map_mul, inv_mul_cancel, map_one, Module.End.one_apply] at h1
  have hh' : ((-h : ℤ) : R) ≠ 0 := by rw [Int.cast_neg]; exact neg_ne_zero.mpr hh
  obtain ⟨c, hc⟩ := exists_eq_smul_X_pow_of_binaryFormRepSL_T_zpow_eq_self n hh' hn Q hQfix
  refine ⟨c, ?_⟩
  have hPQ : P = binaryFormRepSL R n ModularGroup.S Q := by
    rw [hQ, ← Module.End.mul_apply, ← map_mul, mul_inv_cancel, map_one, Module.End.one_apply]
  rw [hPQ, binaryFormRepSL_apply_coe, hc, map_smul, binarySubst_S_X_zero_pow]

end HeckeEis

open scoped MatrixGroups in
theorem solution {R : Type*} [CommRing R] [IsDomain R] (n : ℕ)
    {h : ℤ} (hh : (h : R) ≠ 0) (hn : ∀ j : ℕ, 1 ≤ j → j ≤ n → (j : R) ≠ 0)
    (g : SL(2, ℤ)) (hg : (g : Matrix (Fin 2) (Fin 2) ℤ) = !![1, 0; h, 1])
    (P : ↥(HeckeEis.BinaryForm R n)) (hP : HeckeEis.binaryFormRepSL R n g P = P) :
    ∃ c : R, (P : MvPolynomial (Fin 2) R) = c • MvPolynomial.X 1 ^ n :=
  HeckeEis.SolMain.A3 n hh hn g hg P hP

end S_HeckeEis_exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self
end P2MW
export P2MW.S_HeckeEis_exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self (solution)

end privateSection

public section publicSection


open scoped MatrixGroups
theorem HeckeEis.exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self {R : Type*} [CommRing R] [IsDomain R] (n : ℕ)
    {h : ℤ} (hh : (h : R) ≠ 0) (hn : ∀ j : ℕ, 1 ≤ j → j ≤ n → (j : R) ≠ 0)
    (g : SL(2, ℤ)) (hg : (g : Matrix (Fin 2) (Fin 2) ℤ) = !![1, 0; h, 1])
    (P : ↥(HeckeEis.BinaryForm R n)) (hP : HeckeEis.binaryFormRepSL R n g P = P) :
    ∃ c : R, (P : MvPolynomial (Fin 2) R) = c • MvPolynomial.X 1 ^ n := _root_.P2MW.S_HeckeEis_exists_eq_smul_X_pow_of_binaryFormRepSL_lowerUnipotent_eq_self.solution n hh hn g hg P hP

end publicSection
