/-
Based on Prove2Me node AlgebraicCurve.Place.D_ne_zero_of_ord_eq_one
(fe86f260-e2d6-5e72-9cd3-7282d3522a54) by Claude (2026-09-05).

Proof based on Prove2Me submission 7f52b57c-5ccf-50e9-adeb-7a6d9a0bcb1b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_Differentials

import Theorems.FLT.Thm_AlgebraicCurve_Place_isSeparable_adjoin_of_ord_eq_one
import Theorems.FLT.Thm_KaehlerDifferential_D_ne_zero_of_transcendental
import Theorems.FLT.Thm_AlgebraicCurve_Place_transcendental_of_ord_ne_zero
import Definitions.FLT.Def_P2M_Util

/-!
# A uniformiser at a place has nonzero differential

Theorem statement: `AlgebraicCurve.Place.D_ne_zero_of_ord_eq_one`
(`fe86f260-e2d6-5e72-9cd3-7282d3522a54`), by Claude, 2026-09-05.

Proof: submission `7f52b57c-5ccf-50e9-adeb-7a6d9a0bcb1b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a perfect field and $F$ a field equipped with a $K$-algebra structure, and let $x \in F$
be such that $F$ is algebraic over the intermediate field $K(x) =$ `IntermediateField.adjoin K {x}`.
Let $v$ be a place of $F$ over $K$ in the sense of this development, that is, a valuation subring of
$F$ which contains $\operatorname{algebraMap} K F (a)$ for every $a \in K$, is not all of $F$, and
is a principal ideal ring; for $f \in F$ the integer $\operatorname{ord}_v f$ is defined as $-\log$
of the value of $f$ under the $\mathbb{Z}^{m0}$-valued adic valuation attached to the height-one
prime of that valuation subring. Let $t \in F$ satisfy $\operatorname{ord}_v t = 1$, i.e. $t$ is a
uniformiser at $v$. Then the universal derivation of $t$ in the module of Kähler differentials
$\Omega_{F/K}$, namely `KaehlerDifferential.D K F t`, is nonzero.

This is the statement that over a perfect constant field a uniformiser at a place of a function
field of one variable is a separating element, so that its differential does not vanish; it is the
perfect-field counterpart of the characteristic-zero statement for elements of nonzero order. It is
used in the construction of residues and pole-order estimates for differentials at a place, and in
results comparing two differentials at a point of order one.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_D_ne_zero_of_ord_eq_one.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_D_ne_zero_of_ord_eq_one
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion"
p2m_attr_erase "simp" "AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom"

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] [PerfectField K] (x : F)
    [Algebra.IsAlgebraic (IntermediateField.adjoin K ({x} : Set F)) F]
    (v : AlgebraicCurve.Place K F) {t : F} (ht : v.ord t = 1) :
    KaehlerDifferential.D K F t ≠ 0 :=
  haveI := AlgebraicCurve.Place.isSeparable_adjoin_of_ord_eq_one x v ht
  KaehlerDifferential.D_ne_zero_of_transcendental K t
    (v.transcendental_of_ord_ne_zero (ht ▸ one_ne_zero))

end S_AlgebraicCurve_Place_D_ne_zero_of_ord_eq_one
end P2MW
export P2MW.S_AlgebraicCurve_Place_D_ne_zero_of_ord_eq_one (solution)

end privateSection

public section publicSection

theorem AlgebraicCurve.Place.D_ne_zero_of_ord_eq_one {K F : Type*} [Field K] [Field F] [Algebra K F] [PerfectField K] (x : F)
    [Algebra.IsAlgebraic (IntermediateField.adjoin K ({x} : Set F)) F] (v : AlgebraicCurve.Place K F) {t : F} (ht : v.ord t = 1) :
    KaehlerDifferential.D K F t ≠ 0 := _root_.P2MW.S_AlgebraicCurve_Place_D_ne_zero_of_ord_eq_one.solution x v ht

end publicSection
