/-
Based on Prove2Me node ModularCurve.ord_cuspZeroBar_coeffEmb_qExpand
(918a55bc-1304-52e9-9b9c-eb02ca4b4cc8) by Claude (2026-09-05).

Proof based on Prove2Me submission 2d6904dd-d459-56a3-876b-432c79d64da5
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_CuspidalClass

import Theorems.FLT.Thm_ModularCurve_frickeInvolutionBar_coeffEmb_qExpand
import Theorems.FLT.Thm_ModularCurve_ord_cuspInftyBar_coeffEmb_qExpand
import Definitions.FLT.Def_P2M_Util

/-!
# Order of j(qᵇ) at the cusp ̄ 0

Theorem statement: `ModularCurve.ord_cuspZeroBar_coeffEmb_qExpand`
(`918a55bc-1304-52e9-9b9c-eb02ca4b4cc8`), by Claude, 2026-09-05.

Proof: submission `2d6904dd-d459-56a3-876b-432c79d64da5`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a nonzero natural number and suppose the distinguished automorphism `frickeInvolutionFull
N` of the field $F_N :=$ `modularFunctionFieldFull N` $= \mathbb{Q}(\text{divisorExpansions } N)
\subseteq \mathbb{Q}((q))$ satisfies `IsFrickeAutFull N`, i.e. for every factorisation $N = a'b'$
into nonzero natural numbers it carries the element $j(q^{a'})$ of $F_N$ to $j(q^{b'})$, where
$j(q^{d}) =$ `qExpand ℚ d jq` is obtained from the Laurent series $jq = q^{-1}\cdot(\text{power
series } jNumQ)$ by the substitution $q \mapsto q^{d}$. Let further $a, b$ be nonzero natural
numbers with $ab = N$. Consider the place $\bar 0 :=$ `cuspZeroBar N`, defined as the translate of
`cuspInftyBar N` under the action of `frickeInvolutionBar N`, the
$\overline{\mathbb{Q}}$-automorphism of $\bar F_N :=$ `modularFunctionFieldBar N` $=$
`laurentBaseChange` of $F_N$ obtained from `frickeInvolutionFull N` by base change of coefficients;
here a place is a valuation subring of $\bar F_N$ containing $\overline{\mathbb{Q}}$, distinct from
$\bar F_N$, and a principal ideal ring, and `Place.ord` is the normalised additive valuation
attached to its maximal ideal. The assertion is that the order at $\bar 0$ of the element of $\bar
F_N$ given by the coefficientwise image `coeffEmb` of $j(q^{b})$ under $\mathbb{Q} \hookrightarrow
\overline{\mathbb{Q}}$ equals $-a$.

This records the order of vanishing of the modular function $j(q^{b})$ at the cusp $0$ of $X_0(N)$
over $\overline{\mathbb{Q}}$, the cusp being obtained from the cusp at infinity by the Fricke
involution $w_N$. It is used in the computation of cuspidal divisors and of Hecke operators on them,
and in the verification that $\bar 0$ lies outside the chart at infinity.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_ord_cuspZeroBar_coeffEmb_qExpand.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_ord_cuspZeroBar_coeffEmb_qExpand

open ModularCurve AlgebraicCurve
open scoped Pointwise

theorem solution (N : ℕ) [NeZero N] (h : IsFrickeAutFull N (frickeInvolutionFull N)) (a b : ℕ) (hab : a * b = N) [NeZero a] [NeZero b] :
    (cuspZeroBar N).ord ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ b jq), coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (Dvd.intro_left a hab))⟩ = -a := by
  rw [cuspZeroBar_def, ← ModularCurve.frickeInvolutionBar_coeffEmb_qExpand N h a b hab, Place.ord_smul]
  exact ModularCurve.ord_cuspInftyBar_coeffEmb_qExpand N a (Dvd.intro b hab)

end S_ModularCurve_ord_cuspZeroBar_coeffEmb_qExpand
end P2MW
export P2MW.S_ModularCurve_ord_cuspZeroBar_coeffEmb_qExpand (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve AlgebraicCurve
theorem ModularCurve.ord_cuspZeroBar_coeffEmb_qExpand (N : ℕ) [NeZero N] (h : IsFrickeAutFull N (frickeInvolutionFull N)) (a b : ℕ) (hab : a * b = N) [NeZero a] [NeZero b] : (cuspZeroBar N).ord ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ b jq), coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (Dvd.intro_left a hab))⟩ = -a := _root_.P2MW.S_ModularCurve_ord_cuspZeroBar_coeffEmb_qExpand.solution N h a b hab

end publicSection
