/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.ord_placeInfty_algebraMap
(46a8360b-25ea-521c-a346-d4c9dd16f8eb) by Claude (2026-09-05).

Proof based on Prove2Me submission d0c6e3bd-3cd7-5b5b-9098-77408598336a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceInfty

import Mathlib.FieldTheory.RatFunc.Degree
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_placeInfty
import Definitions.FLT.Def_P2M_Util

/-!
# Order at infinity of a polynomial is -deg q

Theorem statement: `AlgebraicCurve.RationalFunctionField.ord_placeInfty_algebraMap`
(`46a8360b-25ea-521c-a346-d4c9dd16f8eb`), by Claude, 2026-09-05.

Proof: submission `d0c6e3bd-3cd7-5b5b-9098-77408598336a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $q \in K[t]$ be a non-zero polynomial. Consider the place at infinity
$\mathtt{placeInfty}\,K$ of the rational function field $K(t)$: in the sense of the project's notion
of a place of $K(t)$ over $K$, it is given by the valuation subring of the infinity valuation
`RatFunc.inftyValuation K` on $K(t)$, which contains the image of $K$, is not all of $K(t)$, and is
a principal ideal ring. For a place $v$, $v.\mathtt{ord}(f)$ is defined as minus the
`WithZero`-logarithm of the value of $f$ under the adic valuation attached to the height-one prime
of the valuation subring of $v$, so that it is the usual normalised order of vanishing, negative at
a pole. The assertion is that for the image of $q$ under the structure map $K[t] \to K(t)$ one has
$$(\mathtt{placeInfty}\,K).\mathtt{ord}\bigl(\mathrm{alg}(q)\bigr) = -\,\deg q,$$ the degree being
`Polynomial.natDegree` viewed as an integer; equivalently, a non-zero polynomial of degree $d$ has a
pole of order exactly $d$ at infinity.

This is the computation of the divisor of a polynomial at the point at infinity of $\mathbb{P}^1$,
in the standard description of the places of $K(t)$ as the monic irreducibles together with
$\infty$. It is part of the function-field foundations used in the genus-zero computations for
$K(t)$ and in the local analysis of orders at places, for instance in
[`AlgebraicCurve.RationalFunctionField.ell_sub_ell_eq_genus_zero`](thm.html#AlgebraicCurve.RationalFunctionField.ell_sub_ell_eq_genus_zero).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_ord_placeInfty_algebraMap.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_ord_placeInfty_algebraMap
p2m_attr_erase "instance" "AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

open AlgebraicCurve AlgebraicCurve.RationalFunctionField

theorem solution {K : Type*} [Field K] [DecidableEq (RatFunc K)] {q : Polynomial K} (hq : q ≠ 0) : (placeInfty K).ord (algebraMap (Polynomial K) (RatFunc K) q) = -(q.natDegree : ℤ) := by
  rw [AlgebraicCurve.RationalFunctionField.ord_placeInfty (RatFunc.algebraMap_ne_zero hq), RatFunc.intDegree_polynomial]

end S_AlgebraicCurve_RationalFunctionField_ord_placeInfty_algebraMap
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_ord_placeInfty_algebraMap (solution)

end privateSection

public section publicSection


open AlgebraicCurve AlgebraicCurve.RationalFunctionField
theorem AlgebraicCurve.RationalFunctionField.ord_placeInfty_algebraMap {K : Type*} [Field K] [DecidableEq (RatFunc K)] {q : Polynomial K} (hq : q ≠ 0) : (placeInfty K).ord (algebraMap (Polynomial K) (RatFunc K) q) = -(q.natDegree : ℤ) := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_ord_placeInfty_algebraMap.solution hq

end publicSection
