/-
Based on Prove2Me node AlgebraicCurve.Place.ord_natCast
(e2a0b930-e803-57bb-9cf6-8e5d4e7bd6cd) by Claude (2026-09-05).

Proof based on Prove2Me submission 30234e90-66a2-57c0-9e40-ebc2f672ca39
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Theorems.FLT.Thm_AlgebraicCurve_Place_ord_algebraMap
import Definitions.FLT.Def_P2M_Util

/-!
# Natural-number constants have order zero at a place

Theorem statement: `AlgebraicCurve.Place.ord_natCast` (`e2a0b930-e803-57bb-9cf6-8e5d4e7bd6cd`), by
Claude, 2026-09-05.

Proof: submission `30234e90-66a2-57c0-9e40-ebc2f672ca39`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $v$ be a place of $F$ over $K$ in the
sense of the divisor-class-group module: a valuation subring of $F$ that contains the image of $K$
under the structure map, is not all of $F$, and is a principal ideal ring. Attached to such a $v$ is
its adic valuation $v.adicValuation$, the $\mathbb{Z}^{m0}$-valued valuation on $F$ associated with
the height-one prime determined by $v$, and the order function $v.\mathrm{ord}(f) =
-\mathrm{log}\,(v.adicValuation\,f)$, where $\mathrm{log}$ is the `WithZero` logarithm, so that in
particular $v.\mathrm{ord}(0) = 0$ by convention. The assertion is that for every natural number
$n$, the image of $n$ in $F$ under the canonical cast satisfies $v.\mathrm{ord}(n) = 0$. No
hypothesis on the characteristic of $F$ is imposed: in characteristic $p$ the cast of $n$ may
vanish, and the conclusion still holds because of the convention giving $0$ order zero.

This is the familiar statement that a place of $F$ over $K$ is trivial on constants, specialised to
the constants coming from the prime ring; it is used in the computations of orders of differentials,
being cited by
[`AlgebraicCurve.Place.ordDiff_D_eq_ord_sub_one`](thm.html#AlgebraicCurve.Place.ordDiff_D_eq_ord_sub_one),
[`AlgebraicCurve.Place.ordDiff_D_nonneg`](thm.html#AlgebraicCurve.Place.ordDiff_D_nonneg) and
[`AlgebraicCurve.Place.ordDiff_eq_ord_diffCoeff`](thm.html#AlgebraicCurve.Place.ordDiff_eq_ord_diffCoeff).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Place_ord_natCast.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Place_ord_natCast

namespace AlgebraicCurve
p2m_export "AlgebraicCurve" "Place Place.ord_algebraMap"
namespace FF2S
p2m_open "AlgebraicCurve"

variable {K F : Type*} [Field K] [Field F] [Algebra K F]

theorem ord_natCast (v : Place K F) (n : ℕ) : v.ord (n : F) = 0 := by
  rw [show (n : F) = algebraMap K F n by simp]
  exact v.ord_algebraMap n

end AlgebraicCurve.FF2S

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (v : AlgebraicCurve.Place K F) (n : ℕ) :
    v.ord (n : F) = 0 :=
  AlgebraicCurve.FF2S.ord_natCast v n

end S_AlgebraicCurve_Place_ord_natCast
end P2MW
export P2MW.S_AlgebraicCurve_Place_ord_natCast (solution)

end privateSection

public section publicSection

theorem AlgebraicCurve.Place.ord_natCast {K F : Type*} [Field K] [Field F] [Algebra K F] (v : AlgebraicCurve.Place K F) (n : ℕ) :
    v.ord (n : F) = 0 := _root_.P2MW.S_AlgebraicCurve_Place_ord_natCast.solution v n

end publicSection
