/-
Based on Prove2Me node ModularCurve.order_coeffEmb
(b59606ce-9f0c-522b-a285-96a1a61dafa6) by Claude (2026-09-05).

Proof based on Prove2Me submission 00163c79-24b1-51b5-a206-ad8d62088758
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_LaurentCoeff

import Definitions.FLT.Def_P2M_Util

/-!
# Coefficientwise base change preserves the order of a Laurent series

Theorem statement: `ModularCurve.order_coeffEmb` (`b59606ce-9f0c-522b-a285-96a1a61dafa6`), by
Claude, 2026-09-05.

Proof: submission `00163c79-24b1-51b5-a206-ad8d62088758`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $L$ be a field equipped with a $\mathbb{Q}$-algebra structure, and let $x$ be a formal Laurent
series with rational coefficients, i.e. an element of `LaurentSeries ℚ`, the Hahn series ring over
$\mathbb{Q}$ with value group $\mathbb{Z}$. Write `coeffEmb L` for the ring homomorphism
`LaurentSeries ℚ →+* LaurentSeries L` obtained from `coeffMap` applied to the structure map
$\mathbb{Q} \to L$, that is, the map sending a series to the series whose coefficient at each
exponent is the image of the corresponding coefficient of $x$ under $\mathbb{Q} \to L$ (this is a
ring homomorphism: it preserves $0$, $1$, sums and products). The assertion is the equality of
orders $$\operatorname{order}(\mathrm{coeffEmb}_L(x)) = \operatorname{order}(x),$$ where the order
of a Hahn series is its least exponent carrying a nonzero coefficient, with the convention that the
zero series has order $0$. No hypothesis beyond $L$ being a field that is a $\mathbb{Q}$-algebra is
imposed; in particular $L$ may be of arbitrary transcendence degree, and $x$ may be zero.

This records that base change of coefficients along a field extension of $\mathbb{Q}$ is
order-preserving on $q$-expansions, so that vanishing orders at the cusp computed over $\mathbb{Q}$
may be transported to $L$. It is used in the treatment of $q$-expansions of modular functions and
modular units over a general coefficient field, for instance in the computations of orders of $j(q)$
and of modular unit series and in the divisibility statement for the order of a cuspidal divisor
class.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_order_coeffEmb.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_order_coeffEmb

open ModularCurve

theorem solution (L : Type*) [Field L] [Algebra ℚ L] (x : LaurentSeries ℚ) : (coeffEmb L x).order = x.order := by
  rcases eq_or_ne x 0 with rfl | hx
  · rw [map_zero, HahnSeries.order_zero, HahnSeries.order_zero]
  have hLx : coeffEmb L x ≠ 0 := by
    intro h0
    have h1 : (coeffEmb L x).coeff x.order = 0 := by rw [h0]; rfl
    rw [coeffEmb_coeff, map_eq_zero_iff _ (algebraMap ℚ L).injective] at h1
    exact HahnSeries.coeff_order_eq_zero.not.mpr hx h1
  refine le_antisymm (HahnSeries.order_le_of_coeff_ne_zero ?_)
    (HahnSeries.order_le_of_coeff_ne_zero ?_)
  · rw [coeffEmb_coeff]
    exact fun h => HahnSeries.coeff_order_eq_zero.not.mpr hx
      ((map_eq_zero_iff _ (algebraMap ℚ L).injective).mp h)
  · intro h
    exact HahnSeries.coeff_order_eq_zero.not.mpr hLx (by rw [coeffEmb_coeff, h, map_zero])

end S_ModularCurve_order_coeffEmb
end P2MW
export P2MW.S_ModularCurve_order_coeffEmb (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.order_coeffEmb (L : Type*) [Field L] [Algebra ℚ L] (x : LaurentSeries ℚ) : (coeffEmb L x).order = x.order := _root_.P2MW.S_ModularCurve_order_coeffEmb.solution L x

end publicSection
