/-
Based on Prove2Me node UpperHalfPlane.qCoeff_comp_heckeDiagMatrix_smul
(9cbe736c-cda2-5e3a-b708-dbc4e42582e4) by Claude (2026-09-05).

Proof based on Prove2Me submission 276b173c-b4da-596b-b834-943f491bcf70
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularForm_HeckeOperator
public import Definitions.FLT.Def_FLTPrelim_Modularity

import Definitions.FLT.Def_P2M_Util

/-!
# q-expansion of f(dτ): coefficients shifted by d

Theorem statement: `UpperHalfPlane.qCoeff_comp_heckeDiagMatrix_smul`
(`9cbe736c-cda2-5e3a-b708-dbc4e42582e4`), by Claude, 2026-09-05.

Proof: submission `276b173c-b4da-596b-b834-943f491bcf70`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $f : \mathbb{H} \to \mathbb{C}$ be a function on the upper half-plane subject to three
hypotheses: the composite of `UpperHalfPlane.ofComplex` with $f$ is periodic with period $1$ as a
function on $\mathbb{C}$; $f$ is holomorphic, in the sense of being `MDifferentiable` for the
standard model with corners of $\mathbb{C}$ over itself on both source and target; and $f$ is
bounded at $i\infty$ (`UpperHalfPlane.IsBoundedAtImInfty`). Let $d$ be a natural number with $d \neq
0$ and let $n$ be a natural number. Here [`ModularForm.heckeDiagMatrix
d`](def/ModularForm_HeckeOperator.html#L21) is, for $d \neq 0$, the element of
$\mathrm{GL}_2(\mathbb{R})$ given by the upper triangular matrix $\begin{pmatrix} d & 0 \\ 0 &
1\end{pmatrix}$ (and $1$ when $d = 0$), so that its action on $\mathbb{H}$ sends $\tau$ to $d\tau$;
and [`ModularFormClass.qCoeff g n`](def/FLTPrelim_Modularity.html#L19) denotes the $n$-th
coefficient of the $q$-expansion of $g$ taken with respect to the period $1$. The assertion is that
the $n$-th such coefficient of $\tau \mapsto f(\mathrm{heckeDiagMatrix}\, d \cdot \tau)$ equals the
$(n/d)$-th coefficient of $f$ when $d \mid n$, and $0$ otherwise.

This is the coefficient formula for the degeneracy (oldform) operator $V_d : \sum_n a_n q^n \mapsto
\sum_n a_n q^{dn}$, stated for bare functions on $\mathbb{H}$ rather than for elements of a space of
modular forms, so that it applies before any slash-invariance is recorded. It is used throughout the
level-lowering and oldform bookkeeping, for instance in the analysis of eigenforms under the
operators $U_\ell$ and the degeneracy maps between levels.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul

p2m_open "Complex Filter Function UpperHalfPlane P2MW.S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul.UpperHalfPlane ModularForm"
open scoped Real MatrixGroups Topology Manifold ModularForm

noncomputable section

namespace UpperHalfPlane
p2m_export "UpperHalfPlane" "cuspFunction qExpansion ofComplex_apply_of_im_pos analyticAt_cuspFunction_zero atImInfty ofComplex_apply_of_im_nonpos hasSum_qExpansion qExpansion_coeff_unique im_smul_eq_div_normSq re IsBoundedAtImInfty im ofComplex"
namespace DegeneracyQExp
p2m_open "UpperHalfPlane"

private def FnLike : Type := ℍ → ℂ

private scoped instance : FunLike FnLike ℍ ℂ where
  coe f := f
  coe_injective _ _ h := h

variable {d : ℕ}

theorem heckeDiagMatrix_smul_ofComplex (hd : d ≠ 0) {z : ℂ} (hz : 0 < z.im) :
    heckeDiagMatrix d • ofComplex z = ofComplex ((d : ℂ) * z) := by
  have hz' : 0 < ((d : ℂ) * z).im := by
    rw [show ((d : ℂ) * z).im = d * z.im by simp]
    have : (0 : ℝ) < d := by exact_mod_cast Nat.pos_of_ne_zero hd
    positivity
  apply UpperHalfPlane.ext
  rw [coe_heckeDiagMatrix_smul hd, ofComplex_apply_of_im_pos hz, ofComplex_apply_of_im_pos hz']

theorem periodic_comp_smul (hd : d ≠ 0) {F : ℍ → ℂ} (hper : Periodic (F ∘ ofComplex) 1) :
    Periodic ((fun τ ↦ F (heckeDiagMatrix d • τ)) ∘ ofComplex) 1 := by
  intro w
  by_cases hw : 0 < w.im
  · have hw1 : 0 < (w + 1).im := by simpa using hw
    simp only [comp_apply]
    rw [heckeDiagMatrix_smul_ofComplex hd hw1, heckeDiagMatrix_smul_ofComplex hd hw, mul_add, mul_one]
    have h := hper.nat_mul d ((d : ℂ) * w)
    simpa using h
  · push Not at hw
    have hw1 : (w + 1).im ≤ 0 := by simpa using hw
    simp only [comp_apply, ofComplex_apply_of_im_nonpos hw, ofComplex_apply_of_im_nonpos hw1]

theorem mdifferentiable_comp_smul (hd : d ≠ 0) {F : ℍ → ℂ} (hhol : MDiff F) :
    MDiff (fun τ ↦ F (heckeDiagMatrix d • τ)) := by
  have hd' : (d : ℂ) ≠ 0 := by exact_mod_cast hd
  have h := (hhol.slash 0 (heckeDiagMatrix d)).const_smul (d : ℂ)
  convert h using 1
  funext τ
  rw [Pi.smul_apply, slash_heckeDiagMatrix_apply 0 hd, smul_eq_mul, zero_sub, zpow_neg_one,
    ← mul_assoc, mul_inv_cancel₀ hd', one_mul]

theorem isBoundedAtImInfty_comp_smul (hd : d ≠ 0) {F : ℍ → ℂ} (hbdd : IsBoundedAtImInfty F) :
    IsBoundedAtImInfty (fun τ ↦ F (heckeDiagMatrix d • τ)) := by
  refine hbdd.comp_tendsto ?_
  rw [atImInfty, tendsto_comap_iff]
  have him : (UpperHalfPlane.im ∘ fun τ : ℍ ↦ heckeDiagMatrix d • τ) = fun τ ↦ (d : ℝ) * τ.im := by
    funext τ
    simp only [comp_apply]
    rw [UpperHalfPlane.im_smul_eq_div_normSq, denom_heckeDiagMatrix hd, det_heckeDiagMatrix hd]
    simp
  rw [him]
  have hd0 : (0 : ℝ) < d := by exact_mod_cast Nat.pos_of_ne_zero hd
  exact tendsto_comap.const_mul_atTop hd0

theorem qCoeff_comp_smul {F : ℍ → ℂ} (hper : Periodic (F ∘ ofComplex) 1) (hhol : MDiff F)
    (hbdd : IsBoundedAtImInfty F) (hd : d ≠ 0) (n : ℕ) :
    ModularFormClass.qCoeff (fun τ ↦ F (heckeDiagMatrix d • τ)) n =
      if d ∣ n then ModularFormClass.qCoeff F (n / d) else 0 := by
  set G : ℍ → ℂ := fun τ ↦ F (heckeDiagMatrix d • τ) with hG
  have han : AnalyticAt ℂ (cuspFunction 1 G) 0 :=
    analyticAt_cuspFunction_zero one_pos (periodic_comp_smul hd hper) (mdifferentiable_comp_smul hd hhol)
      (isBoundedAtImInfty_comp_smul hd hbdd)
  set c : ℕ → ℂ := fun n ↦ if d ∣ n then (qExpansion 1 F).coeff (n / d) else 0 with hc
  have hsum : ∀ τ : ℍ, HasSum (fun m ↦ c m • Periodic.qParam 1 τ ^ m) (G τ) := by
    intro τ
    have hq : Periodic.qParam 1 ((heckeDiagMatrix d • τ : ℍ) : ℂ) = Periodic.qParam 1 τ ^ d := by
      simp only [Periodic.qParam, ← Complex.exp_nat_mul, coe_heckeDiagMatrix_smul hd]
      congr 1
      push_cast
      ring
    have hs := hasSum_qExpansion one_pos hper hhol hbdd (heckeDiagMatrix d • τ)
    simp_rw [hq, ← pow_mul] at hs
    have hinj : Injective (fun m : ℕ ↦ d * m) := mul_right_injective₀ hd
    have hsupp : ∀ x ∉ Set.range (fun m : ℕ ↦ d * m),
        (fun m ↦ c m • Periodic.qParam 1 τ ^ m) x = 0 := by
      intro x hx
      have : ¬ d ∣ x := by
        rintro ⟨e, rfl⟩
        exact hx ⟨e, rfl⟩
      simp [hc, this]
    refine (hinj.hasSum_iff hsupp).mp ?_
    convert hs using 1
    ext m
    simp [hc, Nat.mul_div_cancel_left _ (Nat.pos_of_ne_zero hd)]
  have key := qExpansion_coeff_unique (F := FnLike) (show FnLike from G) one_pos han hsum n
  show (qExpansion 1 G).coeff n = if d ∣ n then (qExpansion 1 F).coeff (n / d) else 0
  exact key.symm

theorem qCoeff_comp_smul_of_modularFormClass {FF : Type*} [FunLike FF ℍ ℂ]
    {Γ : Subgroup (GL (Fin 2) ℝ)} {k : ℤ} [ModularFormClass FF Γ k] (f : FF)
    (hΓ : (1 : ℝ) ∈ Γ.strictPeriods) (hd : d ≠ 0) (n : ℕ) :
    ModularFormClass.qCoeff (fun τ ↦ f (heckeDiagMatrix d • τ)) n =
      if d ∣ n then ModularFormClass.qCoeff f (n / d) else 0 :=
  haveI : Fact (IsCusp OnePoint.infty Γ) := ⟨Γ.isCusp_of_mem_strictPeriods one_pos hΓ⟩
  qCoeff_comp_smul (SlashInvariantFormClass.periodic_comp_ofComplex f hΓ) (ModularFormClass.holo f)
    (ModularFormClass.bdd_at_infty f) hd n

end UpperHalfPlane.DegeneracyQExp
end
p2m_reactivate "P2MW.S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul.UpperHalfPlane P2MW.S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul.UpperHalfPlane.DegeneracyQExp"

theorem solution {f : UpperHalfPlane → ℂ} (hper : Function.Periodic (f ∘ UpperHalfPlane.ofComplex) 1) (hhol : MDifferentiable (modelWithCornersSelf ℂ ℂ) (modelWithCornersSelf ℂ ℂ) f) (hbdd : UpperHalfPlane.IsBoundedAtImInfty f) {d : ℕ} (hd : d ≠ 0) (n : ℕ) : ModularFormClass.qCoeff (fun τ ↦ f (ModularForm.heckeDiagMatrix d • τ)) n = if d ∣ n then ModularFormClass.qCoeff f (n / d) else 0 :=
  UpperHalfPlane.DegeneracyQExp.qCoeff_comp_smul hper hhol hbdd hd n

end S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul
end P2MW
export P2MW.S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul (solution)

end privateSection

public section publicSection

theorem UpperHalfPlane.qCoeff_comp_heckeDiagMatrix_smul {f : UpperHalfPlane → ℂ} (hper : Function.Periodic (f ∘ UpperHalfPlane.ofComplex) 1) (hhol : MDifferentiable (modelWithCornersSelf ℂ ℂ) (modelWithCornersSelf ℂ ℂ) f) (hbdd : UpperHalfPlane.IsBoundedAtImInfty f) {d : ℕ} (hd : d ≠ 0) (n : ℕ) : ModularFormClass.qCoeff (fun τ ↦ f (ModularForm.heckeDiagMatrix d • τ)) n = if d ∣ n then ModularFormClass.qCoeff f (n / d) else 0 := _root_.P2MW.S_UpperHalfPlane_qCoeff_comp_heckeDiagMatrix_smul.solution hper hhol hbdd hd n

end publicSection
