/-
Based on Prove2Me node ModularCurve.exists_isFrickeAutFull
(15ca057b-f5a1-5d87-b099-8eae7183423f) by Claude (2026-09-05).

Proof based on Prove2Me submission 9354c7a4-b2b7-59df-a528-3890efdc9285
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_AtkinLehner

import Theorems.FLT.Thm_ModularCurve_exists_isFrickeAut
import Theorems.FLT.Thm_ModularCurve_full_eq_of_prime
import Definitions.FLT.Def_P2M_Util

/-!
# Fricke automorphism of ℚ(j(qᵈ):d∣ℓ) at prime level

Theorem statement: `ModularCurve.exists_isFrickeAutFull` (`15ca057b-f5a1-5d87-b099-8eae7183423f`),
by Claude, 2026-09-05.

Proof: submission `9354c7a4-b2b7-59df-a528-3890efdc9285`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\ell$ be a natural number carrying the instance that it is prime. The field in play is
`modularFunctionFieldFull ℓ`, the intermediate field of $\mathbb{Q} \subseteq \mathbb{Q}((q))$
(Laurent series over $\mathbb{Q}$) obtained by adjoining to $\mathbb{Q}$ the set of Laurent series
$\mathrm{qExpand}\,\mathbb{Q}\,d\ (\mathrm{jq})$ for all nonzero $d$ dividing $\ell$, where `jq` is
the distinguished Laurent series playing the role of the $q$-expansion of $j$ and `qExpand ℚ d` is
the ring homomorphism of Laurent series that multiplies all exponents by $d$ (substitution $q
\mapsto q^{d}$). The assertion is that there exists a $\mathbb{Q}$-algebra automorphism $\sigma$ of
this field satisfying `IsFrickeAutFull ℓ σ`, that is: for all natural numbers $a, b$ with $a \cdot b
= \ell$, both nonzero, $\sigma$ carries the element of `modularFunctionFieldFull ℓ` given by
$\mathrm{qExpand}\,\mathbb{Q}\,a\ (\mathrm{jq})$ (together with its membership witness, coming from
$a \mid \ell$) to the element given by $\mathrm{qExpand}\,\mathbb{Q}\,b\ (\mathrm{jq})$. No further
conditions on $\sigma$ are imposed, and no claim of uniqueness or of $\sigma$ being an involution is
made.

This is the existence of the Fricke involution $w_\ell$, $\tau \mapsto -1/(\ell\tau)$, in its
function-field form: an automorphism of the function field of $X_0(\ell)$ interchanging $j$ and
$j(\ell\,\cdot)$, stated for the divisor-generated presentation $\mathbb{Q}(j(q^{d}) : d \mid
\ell)$. It feeds the Atkin–Lehner input used downstream in the analysis of values and poles of
modular functions at points of $X_0(\ell)$, including the treatment of nodes and of Frobenius node
pairs.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_isFrickeAutFull.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_isFrickeAutFull
p2m_attr_erase "instance" "ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

p2m_open "ModularCurve P2MW.S_ModularCurve_exists_isFrickeAutFull.ModularCurve AlgebraicCurve IntermediateField"

noncomputable section

namespace ModularCurve
p2m_export "ModularCurve" "IsFrickeAutFull qExpand qExpand_one_apply jq jqN modularFunctionField modularFunctionFieldFull exists_isFrickeAut full_eq_of_prime"
p2m_open "ModularCurve"

namespace W2B

theorem cast_algEquiv_exists {E E' : IntermediateField ℚ (LaurentSeries ℚ)} (h : E = E') (σ : E ≃ₐ[ℚ] E) :
    ∃ σ' : E' ≃ₐ[ℚ] E', ∀ x : E', ((σ' x : E') : LaurentSeries ℚ) = σ ⟨x, h ▸ x.2⟩ := by
  subst h
  exact ⟨σ, fun _ => rfl⟩

end W2B

end ModularCurve

theorem solution (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] : ∃ σ : modularFunctionFieldFull ℓ ≃ₐ[ℚ] modularFunctionFieldFull ℓ, IsFrickeAutFull ℓ σ := by
  have : NeZero ℓ := ⟨hℓ.out.ne_zero⟩
  have hfull : modularFunctionFieldFull ℓ = modularFunctionField ℓ := ModularCurve.full_eq_of_prime hℓ.out
  obtain ⟨σ, hσ⟩ := ModularCurve.exists_isFrickeAut ℓ
  obtain ⟨σ', hσ'⟩ := ModularCurve.W2B.cast_algEquiv_exists hfull.symm σ
  refine ⟨σ', ?_⟩
  intro a b hab _ _
  have hcases : a = 1 ∧ ℓ = b ∨ ℓ = a ∧ b = 1 := by
    have hprime : (a * b).Prime := hab ▸ hℓ.out
    rcases Nat.prime_mul_iff.mp hprime with ⟨_, rfl⟩ | ⟨_, rfl⟩
    · right; exact ⟨hab.symm.trans (mul_one a), rfl⟩
    · left; exact ⟨rfl, hab.symm.trans (one_mul b)⟩
  rcases hcases with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · have H : ∀ (y : LaurentSeries ℚ) (hy : y ∈ modularFunctionField ℓ), y = jq →
        ((σ ⟨y, hy⟩ : modularFunctionField ℓ) : LaurentSeries ℚ) = qExpand ℚ ℓ jq := by
      rintro y hy rfl
      exact congrArg Subtype.val hσ.1
    apply Subtype.ext
    rw [hσ']
    exact H _ _ (qExpand_one_apply jq)
  · have H : ∀ (y : LaurentSeries ℚ) (hy : y ∈ modularFunctionField ℓ), y = jqN ℓ →
        ((σ ⟨y, hy⟩ : modularFunctionField ℓ) : LaurentSeries ℚ) = qExpand ℚ 1 jq := by
      rintro y hy rfl
      exact (congrArg Subtype.val hσ.2).trans (qExpand_one_apply jq).symm
    apply Subtype.ext
    rw [hσ']
    exact H _ _ rfl

end

end S_ModularCurve_exists_isFrickeAutFull
end P2MW
export P2MW.S_ModularCurve_exists_isFrickeAutFull (solution)

end privateSection

public section publicSection


open ModularCurve AlgebraicCurve IntermediateField
theorem ModularCurve.exists_isFrickeAutFull (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] : ∃ σ : modularFunctionFieldFull ℓ ≃ₐ[ℚ] modularFunctionFieldFull ℓ, IsFrickeAutFull ℓ σ := _root_.P2MW.S_ModularCurve_exists_isFrickeAutFull.solution ℓ

end publicSection
