/-
Based on Prove2Me node WeierstrassCurve.tateModuleRep_charpoly_frobenius
(8f4634d9-5aa8-53ac-b6f3-426deb1a8659) by Claude (2026-09-05).

Proof based on Prove2Me submission 2484721f-668a-5089-b666-d28b67b8632a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_FLTPrelim_Modularity
public import Definitions.FLT.Def_EllipticCurve_TateModule
public import Definitions.FLT.Def_EllipticCurve_FrobeniusTrace
public import Mathlib.LinearAlgebra.Charpoly.Basic

import Theorems.FLT.Thm_WeierstrassCurve_frobenius_cayleyHamilton_on_torsion
import Theorems.FLT.Thm_LinearMap_charpoly_eq_iff_of_finrank_eq_two
import Theorems.FLT.Thm_WeierstrassCurve_tateModuleRep_det_frobenius
import Theorems.FLT.Thm_LinearMap_trace_eq_of_sq_sub_smul_add_eq_zero_of_det_eq
import Mathlib.Algebra.Module.NatInt
import Definitions.FLT.Def_P2M_Util

/-!
# Frobenius characteristic polynomial on the p-adic Tate module

Theorem statement: `WeierstrassCurve.tateModuleRep_charpoly_frobenius`
(`8f4634d9-5aa8-53ac-b6f3-426deb1a8659`), by Claude, 2026-09-05.

Proof: submission `2484721f-668a-5089-b666-d28b67b8632a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $W$ be a Weierstrass curve over $\mathbb{Z}$ and $p$ a prime, and assume that for every $n$ the
$p^n$-torsion subgroup of the group of points of the base change of $W$ to $\overline{\mathbb{Q}}$
(via $\mathbb{Z} \to \mathbb{Q}$) has cardinality $(p^n)^2$; this is the hypothesis under which the
rank-two $\mathbb{Z}_p$-representation `tateModuleRep` of the absolute Galois group
$\operatorname{Aut}_{\mathbb{Q}}(\overline{\mathbb{Q}})$ on the Tate module — sequences $(x_n)$ of
points with $p^n x_n = 0$ and $p\,x_{n+1} = x_n$ — is formed. Let $\ell$ be a prime with $\ell \ne
p$ and with $\ell \nmid \Delta(W)$ in $\mathbb{Z}$ (`IsGoodPrimeFor`), let $A$ be a valuation
subring of $\overline{\mathbb{Q}}$ such that $\ell$ is a non-unit of $A$, and let $\sigma$ be a
$\mathbb{Q}$-algebra automorphism of $\overline{\mathbb{Q}}$ lying in the decomposition subgroup of
$A$ over $\mathbb{Q}$ and acting on the residue field of $A$ by $x \mapsto x^{\ell}$. Then the
characteristic polynomial of the $\mathbb{Z}_p$-linear endomorphism by which $\sigma$ acts on the
Tate module is $X^2 - C(a_\ell)X + C(\ell)$ in $\mathbb{Z}_p[X]$, where $a_\ell$ is the integer
$\ell + 1 - \#\big(W \bmod \ell\big)(\mathbb{Z}/\ell)$ attached to the model $W$ by `apOfModel`, and
both $a_\ell$ and $\ell$ are cast into $\mathbb{Z}_p$.

This is the Eichler–Shimura style description of Frobenius on the $p$-adic Tate module of an
elliptic curve at a prime of good reduction: trace $a_\ell$ and determinant $\ell$. It is what ties
the Galois representation attached to a Frobenius curve to the $L$-series coefficients of its
reduction, and it feeds the modularity and level-lowering steps of the argument, in particular the
comparison of the Tate-module representation with the one coming from a modular form.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_tateModuleRep_charpoly_frobenius.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_tateModuleRep_charpoly_frobenius
p2m_attr_erase "instance" "ValuationSubring.instIsAlgClosedResidueField WeierstrassCurve.instIsEllipticBaseChange WeierstrassCurve.Univ.Affine.instAddGroupPointFieldBaseChangeMvPolynomialCoeffIntCurve WeierstrassCurve.Univ.instIsEllipticFieldPointedCurve WeierstrassCurve.Univ.instCommRingPoly WeierstrassCurve.Affine.CoordinateRing.moduleFinite WeierstrassCurve.Affine.instDecidableEqFunctionField WeierstrassCurve.Affine.CoordinateRing.isIntegral"
p2m_attr_erase "simp" "FrobeniusEndo.linePencil_apply WeierstrassCurve.reducePoint_zero WeierstrassCurve.Affine.Point.galoisRep_apply ValuationSubring.reduceAt_coe ValuationSubring.reduceAt_one ValuationSubring.reduceAt_natCast ValuationSubring.reduceAt_intCast ValuationSubring.reduceAt_zero compl₂EDSAux_neg_two compl₂EDSAux_zero WeierstrassCurve.ωe_zero WeierstrassCurve.Univ.pointedCurve_a₁ WeierstrassCurve.Univ.polyToField_polynomial WeierstrassCurve.Coeff.A₁.sizeOf_spec compl₂EDS_zero compl₂EDS_one WeierstrassCurve.Univ.Affine.smulY_zero Param.C.sizeOf_spec EllSequence.redInvarDenom_zero compl₂EDSAux_two compl₂EDSAux_neg_one compl₂EDSAux_one WeierstrassCurve.Coeff.A₆.sizeOf_spec WeierstrassCurve.ψc_neg WeierstrassCurve.Univ.Affine.smulY_one WeierstrassCurve.Univ.Affine.smulX_one WeierstrassCurve.Coeff.A₂.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₄ compl₂EDS_neg WeierstrassCurve.Univ.pointedCurve_a₃ EllSequence.redInvarDenom_two WeierstrassCurve.Univ.pointedCurve_a₆ Param.D.sizeOf_spec WeierstrassCurve.ωe_one WeierstrassCurve.Univ.Affine.smulX_zero WeierstrassCurve.Coeff.A₃.sizeOf_spec EllSequence.redInvarDenom_one WeierstrassCurve.Coeff.A₄.sizeOf_spec WeierstrassCurve.Univ.pointedCurve_a₂ Param.B.sizeOf_spec"
p2m_attr_erase "simp" "compl₂EDS_two WeierstrassCurve.Universal.halveX_zero WeierstrassCurve.Universal.specialize_X_one WeierstrassCurve.Universal.coeff_halve WeierstrassCurve.Universal.specialize_X_two WeierstrassCurve.Universal.halveCoeff_zero WeierstrassCurve.Universal.specialize_X_four WeierstrassCurve.Universal.coeff_halveX WeierstrassCurve.Universal.specialize_X_three WeierstrassCurve.Universal.specialize_X_zero WeierstrassCurve.Affine.mem_fibSet WeierstrassCurve.Affine.pointHom_mk_C_C WeierstrassCurve.Affine.Point.yc_some WeierstrassCurve.Affine.Point.xc_some WeierstrassCurve.Affine.pointPull_algebraMap WeierstrassCurve.Affine.pointHom_mk_C_X WeierstrassCurve.Affine.pointHom_mk_Y WeierstrassCurve.Affine.placeOf_asIdeal"

open Polynomial WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point ValuationSubring

private lemma apOfModel_dict (W : WeierstrassCurve ℤ) (ℓ : ℕ) :
    W.apOfModel ℓ = (ℓ : ℤ) + 1 - (Nat.card (W⁄(ZMod ℓ)).Point : ℤ) := by
  unfold WeierstrassCurve.apOfModel WeierstrassCurve.traceOfFrobenius WeierstrassCurve.card
    WeierstrassCurve.reductionMod
  rw [Nat.card_zmod]
  rfl

private lemma intCast_padicInt_smul_apply {p : ℕ} {M : Type} [AddCommGroup M] [Fact p.Prime]
    (c : ℤ) (x : TateModule p M) (n : ℕ) :
    (((c : ℤ_[p]) • x : TateModule p M) : ℕ → M) n = c • ((x : ℕ → M) n) := by
  rw [Int.cast_smul_eq_zsmul ℤ_[p], AddSubgroupClass.coe_zsmul, Pi.smul_apply]

section endoId

variable (W : WeierstrassCurve ℤ) (p : ℕ) [Fact p.Prime]

private abbrev MPoint := ((W.map (Int.castRingHom ℚ))⁄(AlgebraicClosure ℚ)).Point

private lemma tateModule_frobenius_endoIdentity
    (ℓ : ℕ) (hℓ : ℓ.Prime) (hgood : W.IsGoodPrimeFor ℓ) (hℓp : ℓ ≠ p)
    (A : ValuationSubring (AlgebraicClosure ℚ)) (hA : A.LiesOverPrime ℓ)
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hσ : A.IsFrobeniusAt σ ℓ)
    (x : TateModule p (MPoint W)) (k : ℕ) :
    σ • σ • (x : ℕ → MPoint W) k - (W.apOfModel ℓ) • σ • (x : ℕ → MPoint W) k
      + (ℓ : ℤ) • (x : ℕ → MPoint W) k = 0 := by
  rw [apOfModel_dict, sub_add_eq_add_sub, sub_eq_zero]
  refine WeierstrassCurve.frobenius_cayleyHamilton_on_torsion W ℓ hℓ hgood A hA σ hσ
    (p ^ k) (pow_pos (Fact.out (p := p.Prime)).pos k)
    (fun hdvd => hℓp ((Nat.prime_dvd_prime_iff_eq hℓ Fact.out).mp (hℓ.dvd_of_dvd_pow hdvd)))
    ((x : ℕ → MPoint W) k) ?_
  have h := TateModule.torsion x k
  rwa [natCast_zsmul] at h

end endoId

theorem solution
    (W : WeierstrassCurve ℤ) (p : ℕ) [Fact p.Prime]
    (hcard : ∀ n : ℕ, Nat.card (Submodule.torsionBy ℤ
      ((W.map (Int.castRingHom ℚ))⁄(AlgebraicClosure ℚ)).Point ((p ^ n : ℕ) : ℤ)) = (p ^ n) ^ 2)
    (ℓ : ℕ) (hℓ : ℓ.Prime) (hgood : W.IsGoodPrimeFor ℓ) (hℓp : ℓ ≠ p)
    (A : ValuationSubring (AlgebraicClosure ℚ)) (hA : A.LiesOverPrime ℓ)
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hσ : A.IsFrobeniusAt σ ℓ) :
    LinearMap.charpoly (((W.map (Int.castRingHom ℚ)).tateModuleRep p hcard).ρ σ)
      = X ^ 2 - C ((W.apOfModel ℓ : ℤ) : ℤ_[p]) * X + C ((ℓ : ℕ) : ℤ_[p]) := by

  have : Module.Free ℤ_[p] (TateModule p (MPoint W)) := TateModule.free hcard
  have : Module.Finite ℤ_[p] (TateModule p (MPoint W)) := TateModule.finite hcard
  have hrank : Module.finrank ℤ_[p] (TateModule p (MPoint W)) = 2 := TateModule.finrank_eq_two hcard
  set f : Module.End ℤ_[p] (TateModule p (MPoint W)) :=
    ((W.map (Int.castRingHom ℚ)).tateModuleRep p hcard).ρ σ

  have hΔℤ : W.Δ ≠ 0 := fun h => hgood (h ▸ dvd_zero _)
  have hΔℚ : (W.map (Int.castRingHom ℚ)).Δ ≠ 0 := by
    rw [WeierstrassCurve.map_Δ, eq_intCast]
    exact_mod_cast hΔℤ
  have hdet : LinearMap.det f = ((ℓ : ℕ) : ℤ_[p]) :=
    WeierstrassCurve.tateModuleRep_det_frobenius (W.map (Int.castRingHom ℚ)) p hΔℚ hcard ℓ hℓ hℓp A hA σ hσ
  have hd : ((ℓ : ℕ) : ℤ_[p]) ≠ 0 := by exact_mod_cast hℓ.pos.ne'

  have hendo : f * f - ((W.apOfModel ℓ : ℤ) : ℤ_[p]) • f
      + ((ℓ : ℕ) : ℤ_[p]) • (1 : Module.End ℤ_[p] (TateModule p (MPoint W))) = 0 := by
    refine LinearMap.ext fun x => ?_
    have hx : (f * f - ((W.apOfModel ℓ : ℤ) : ℤ_[p]) • f
        + ((ℓ : ℕ) : ℤ_[p]) • (1 : Module.End ℤ_[p] (TateModule p (MPoint W)))) x
        = f (f x) - ((W.apOfModel ℓ : ℤ) : ℤ_[p]) • (f x) + ((ℓ : ℕ) : ℤ_[p]) • x := by
      simp only [LinearMap.add_apply, LinearMap.sub_apply, Module.End.mul_apply,
        LinearMap.smul_apply, Module.End.one_apply]
    rw [hx, LinearMap.zero_apply]
    rw [show ((ℓ : ℕ) : ℤ_[p]) = ((ℓ : ℤ) : ℤ_[p]) by push_cast; ring]
    refine Subtype.ext (funext fun k => ?_)
    show ((f (f x) - ((W.apOfModel ℓ : ℤ) : ℤ_[p]) • (f x)
        + ((ℓ : ℤ) : ℤ_[p]) • x : TateModule p (MPoint W)) : ℕ → MPoint W) k
      = (((0 : TateModule p (MPoint W)) : ℕ → MPoint W)) k
    rw [TateModule.coe_add, TateModule.coe_sub, TateModule.coe_zero, Pi.add_apply, Pi.sub_apply,
      Pi.zero_apply, intCast_padicInt_smul_apply, intCast_padicInt_smul_apply]

    exact tateModule_frobenius_endoIdentity W p ℓ hℓ hgood hℓp A hA σ hσ x k

  exact (LinearMap.charpoly_eq_iff_of_finrank_eq_two hrank f
      ((W.apOfModel ℓ : ℤ) : ℤ_[p]) ((ℓ : ℕ) : ℤ_[p])).mpr
    ⟨LinearMap.trace_eq_of_sq_sub_smul_add_eq_zero_of_det_eq hrank f _ _ hendo hdet hd, hdet⟩

end S_WeierstrassCurve_tateModuleRep_charpoly_frobenius
end P2MW
export P2MW.S_WeierstrassCurve_tateModuleRep_charpoly_frobenius (solution)

end privateSection

public section publicSection


open Polynomial WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point ValuationSubring

theorem WeierstrassCurve.tateModuleRep_charpoly_frobenius
    (W : WeierstrassCurve ℤ) (p : ℕ) [Fact p.Prime]
    (hcard : ∀ n : ℕ, Nat.card (Submodule.torsionBy ℤ
      ((W.map (Int.castRingHom ℚ))⁄(AlgebraicClosure ℚ)).Point ((p ^ n : ℕ) : ℤ)) = (p ^ n) ^ 2)
    (ℓ : ℕ) (hℓ : ℓ.Prime) (hgood : W.IsGoodPrimeFor ℓ) (hℓp : ℓ ≠ p)
    (A : ValuationSubring (AlgebraicClosure ℚ)) (hA : A.LiesOverPrime ℓ)
    (σ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ) (hσ : A.IsFrobeniusAt σ ℓ) :
    LinearMap.charpoly (((W.map (Int.castRingHom ℚ)).tateModuleRep p hcard).ρ σ)
      = X ^ 2 - C ((W.apOfModel ℓ : ℤ) : ℤ_[p]) * X + C ((ℓ : ℕ) : ℤ_[p]) := _root_.P2MW.S_WeierstrassCurve_tateModuleRep_charpoly_frobenius.solution W p hcard ℓ hℓ hgood hℓp A hA σ hσ

end publicSection
