/-
Based on Prove2Me node ModularCurve.exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf
(f8d8616a-dfb9-5303-95c1-39d6175869af) by Claude (2026-09-05).

Proof based on Prove2Me submission 781b93e0-8ab9-58b2-894d-c8ea49f426de
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ComplexPlaceDictionaryOf
public import Definitions.FLT.Def_ModularCurve_JqCoeff
public import Definitions.FLT.Def_ModularCurve_X1

import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_forall_ord_eq_finset
import Theorems.FLT.Thm_ModularCurve_ord_eq_zero_of_not_mem_of_realizeOf_tendsto
import Definitions.FLT.Def_P2M_Util

/-!
# Cusp places of ℂ·ℚ(X(Γ)) are exhausted by Pl

Theorem statement: `ModularCurve.exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf`
(`f8d8616a-dfb9-5303-95c1-39d6175869af`), by Claude, 2026-09-05.

Proof: submission `781b93e0-8ab9-58b2-894d-c8ea49f426de`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\Gamma\le \mathrm{SL}_2(\mathbb Z)$ be a subgroup of finite index which contains the
translation matrix `ModularGroup.T` and satisfies the predicate
`CongruenceSubgroup.IsCongruenceSubgroup`, and let $F_0$ be an intermediate field of $\mathbb
Q\subset\mathbb Q((q))$ equal to [`ModularCurve.qExpFunctionFieldC ℚ
Γ`](def/ModularCurve_X1.html#L101), the subfield generated over $\mathbb Q$ by the quotients
$p_f/p_g$ of integral $q$-expansions of pairs of modular forms of level $\Gamma$ and equal weight
(with $p_g\ne 0$). Write $F$ for [`ModularCurve.laurentBaseChange ℂ
F₀`](def/ModularCurve_LaurentCoeff.html#L103), the subfield of $\mathbb C((q))$ generated over
$\mathbb C$ by the image of $F_0$ under coefficientwise extension of scalars. Let $y\in F$ have
Laurent series [`ModularCurve.jqModC ℂ`](def/ModularCurve_JqCoeff.html#L15), that is $q^{-1}$ times
the power series $E_4^3\cdot\eta^{-24}$-type numerator `jNum` pushed to $\mathbb C$. Let
$\mathrm{Pl}$ assign to each $\sigma\in \mathrm{SL}_2(\mathbb Z)$ a place of $F/\mathbb C$ in the
sense of [`AlgebraicCurve.Place`](def/AlgebraicCurve_DivisorClassGroup.html#L22) (a proper valuation
subring of $F$ containing $\mathbb C$ whose ring is a principal ideal ring), subject to two
hypotheses: $\mathrm{Pl}(\gamma\sigma)=\mathrm{Pl}(\sigma)$ for all $\gamma\in\Gamma$ and all
$\sigma$; and for every $\sigma$ and every nonzero $x\in F$ with
$\operatorname{ord}_{\mathrm{Pl}(\sigma)}x=0$ (the negated logarithm of the associated adic
valuation) there is $L\ne 0$ such that $\tau\mapsto$
[`ModularCurve.realizeOf`](def/ModularCurve_ComplexPlaceDictionaryOf.html#L15)
$\Gamma\,x\,(\sigma\cdot\tau)$ tends to $L$ as $\operatorname{Im}\tau\to\infty$, where `realizeOf`
evaluates $x$ at $\tau$ as $f(\tau)/g(\tau)$ for some choice of modular forms $f,g$ of level
$\Gamma$ and equal weight with $g(\tau)\ne0$ and $x\cdot q\text{-exp}(g)=q\text{-exp}(f)$, and is
$0$ if no such pair exists. Then every place $P$ of $F/\mathbb C$ with $y\notin P$ is of the form
$\mathrm{Pl}(\sigma)$ for some $\sigma\in\mathrm{SL}_2(\mathbb Z)$.

This is the completeness half of the dictionary between cusps of $X(\Gamma)$ and places of its
function field: the places at which the $j$-expansion fails to be integral, i.e. the cusp places,
are exactly those produced by the family $\mathrm{Pl}$ indexed by right $\Gamma$-cosets in
$\mathrm{SL}_2(\mathbb Z)$. It is used in the divisor-theoretic analysis of $q$-expansions at cusps,
notably in computing orders of vanishing in terms of cusp widths.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy"
p2m_attr_erase "simp" "ModularCurve.LevelN.coe_jGen PeriodPair.weierstrassCurve_a₆ PeriodPair.weierstrassCurve_a₃ PeriodPair.weierstrassCurve_a₁ PeriodPair.ofTau_ω₂ PeriodPair.scale_ω₂ PeriodPair.ofTau_ω₁ PeriodPair.toPoint_zero PeriodPair.toPoint_of_mem PeriodPair.weierstrassCurve_a₂ PeriodPair.ofTau_lattice PeriodPair.scale_ω₁ PeriodPair.weierstrassCurve_a₄ AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk"
p2m_attr_erase "simp" "ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply"

open CongruenceSubgroup ModularCurve
open scoped MatrixGroups ModularForm

theorem solution
    (Γ : Subgroup SL(2, ℤ)) [Γ.FiniteIndex] (hT : ModularGroup.T ∈ Γ)
    (hΓ : CongruenceSubgroup.IsCongruenceSubgroup Γ)
    (F₀ : IntermediateField ℚ (LaurentSeries ℚ)) (hF : F₀ = ModularCurve.qExpFunctionFieldC ℚ Γ)
    (y : ↥(ModularCurve.laurentBaseChange ℂ F₀)) (hy : (y : LaurentSeries ℂ) = ModularCurve.jqModC ℂ)
    (Pl : SL(2, ℤ) → AlgebraicCurve.Place ℂ ↥(ModularCurve.laurentBaseChange ℂ F₀))
    (hΓPl : ∀ γ ∈ Γ, ∀ σ : SL(2, ℤ), Pl (γ * σ) = Pl σ)
    (hlim : ∀ (σ : SL(2, ℤ)) (x : ↥(ModularCurve.laurentBaseChange ℂ F₀)), x ≠ 0 → (Pl σ).ord x = 0 →
      ∃ L : ℂ, L ≠ 0 ∧
        Filter.Tendsto (fun τ : UpperHalfPlane => ModularCurve.realizeOf Γ (x : LaurentSeries ℂ) (σ • τ))
          UpperHalfPlane.atImInfty (nhds L))
    (P : AlgebraicCurve.Place ℂ ↥(ModularCurve.laurentBaseChange ℂ F₀)) (hP : y ∉ P.toValuationSubring) :
    ∃ σ : SL(2, ℤ), Pl σ = P := by
  classical
  by_contra hcon
  push Not at hcon
  let Pl' : Quotient (QuotientGroup.rightRel Γ) → AlgebraicCurve.Place ℂ ↥(ModularCurve.laurentBaseChange ℂ F₀) :=
    Quotient.lift Pl (by
      intro a b hab
      have hab' : b * a⁻¹ ∈ Γ := QuotientGroup.rightRel_apply.mp hab
      have h := hΓPl (b * a⁻¹) hab' a
      rw [inv_mul_cancel_right] at h
      exact h.symm)
  have : Finite (Quotient (QuotientGroup.rightRel Γ)) :=
    Finite.of_equiv _ (QuotientGroup.quotientRightRelEquivQuotientLeftRel Γ).symm
  have hfin : (Set.range Pl).Finite := by
    refine (Set.finite_range Pl').subset ?_
    rintro _ ⟨σ, rfl⟩
    exact ⟨Quotient.mk _ σ, rfl⟩
  obtain ⟨S₀, hS₀⟩ : ∃ S₀ : Finset (AlgebraicCurve.Place ℂ ↥(ModularCurve.laurentBaseChange ℂ F₀)),
      ∀ σ, Pl σ ∈ S₀ := ⟨hfin.toFinset, fun σ => hfin.mem_toFinset.mpr ⟨σ, rfl⟩⟩
  obtain ⟨g, hg0, hg⟩ := AlgebraicCurve.Place.exists_forall_ord_eq_finset (insert P S₀)
    (fun v => if v = P then (1 : ℤ) else 0)
  have hPg : P.ord g = 1 := by
    have h := hg P (Finset.mem_insert_self P S₀)
    rwa [ite_eq_left rfl] at h
  have hσg : ∀ σ : SL(2, ℤ), (Pl σ).ord g = 0 := fun σ => by
    have h := hg (Pl σ) (Finset.mem_insert_of_mem (hS₀ σ))
    rwa [ite_eq_right (hcon σ)] at h
  have hcusp : ∀ σ : SL(2, ℤ), ∃ L : ℂ, L ≠ 0 ∧
      Filter.Tendsto (fun τ : UpperHalfPlane => ModularCurve.realizeOf Γ (g : LaurentSeries ℂ) (σ • τ)) UpperHalfPlane.atImInfty (nhds L) :=
    fun σ => hlim σ g hg0 (hσg σ)
  have h0 : P.ord g = 0 :=
    ModularCurve.ord_eq_zero_of_not_mem_of_realizeOf_tendsto Γ hT hΓ F₀ hF g
      (fun τ : UpperHalfPlane => ModularCurve.realizeOf Γ (g : LaurentSeries ℂ) τ) (fun τ => Filter.EventuallyEq.rfl) hcusp P y hy hP
  rw [h0] at hPg
  exact zero_ne_one hPg

end S_ModularCurve_exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf
end P2MW
export P2MW.S_ModularCurve_exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf (solution)

end privateSection

public section publicSection


open CongruenceSubgroup ModularCurve
open scoped MatrixGroups ModularForm
theorem ModularCurve.exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf
    (Γ : Subgroup SL(2, ℤ)) [Γ.FiniteIndex] (hT : ModularGroup.T ∈ Γ)
    (hΓ : CongruenceSubgroup.IsCongruenceSubgroup Γ)
    (F₀ : IntermediateField ℚ (LaurentSeries ℚ)) (hF : F₀ = ModularCurve.qExpFunctionFieldC ℚ Γ)
    (y : ↥(ModularCurve.laurentBaseChange ℂ F₀)) (hy : (y : LaurentSeries ℂ) = ModularCurve.jqModC ℂ)
    (Pl : SL(2, ℤ) → AlgebraicCurve.Place ℂ ↥(ModularCurve.laurentBaseChange ℂ F₀))
    (hΓPl : ∀ γ ∈ Γ, ∀ σ : SL(2, ℤ), Pl (γ * σ) = Pl σ)
    (hlim : ∀ (σ : SL(2, ℤ)) (x : ↥(ModularCurve.laurentBaseChange ℂ F₀)), x ≠ 0 → (Pl σ).ord x = 0 →
      ∃ L : ℂ, L ≠ 0 ∧
        Filter.Tendsto (fun τ : UpperHalfPlane => ModularCurve.realizeOf Γ (x : LaurentSeries ℂ) (σ • τ))
          UpperHalfPlane.atImInfty (nhds L))
    (P : AlgebraicCurve.Place ℂ ↥(ModularCurve.laurentBaseChange ℂ F₀)) (hP : y ∉ P.toValuationSubring) :
    ∃ σ : SL(2, ℤ), Pl σ = P := _root_.P2MW.S_ModularCurve_exists_apply_eq_of_forall_ord_eq_zero_tendsto_realizeOf.solution Γ hT hΓ F₀ hF y hy Pl hΓPl hlim P hP

end publicSection
