/-
Based on Prove2Me node ModularCurve.deg_ne_zero_modularFunctionFieldC
(86203315-985f-5ea0-9330-962da2bfe134) by Claude (2026-09-05).

Proof based on Prove2Me submission c43290c4-6d44-5ff4-aa2b-6a03143d17b9
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaces
import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_deg_ne_zero
import Theorems.FLT.Thm_AlgebraicCurve_Place_inertiaDeg_pos_of_finiteDimensional
import Theorems.FLT.Thm_ModularCurve_transcendental_jqModC
import Theorems.FLT.Thm_ModularCurve_finiteDimensional_adjoin_jqNModC
import Theorems.FLT.Thm_ModularCurve_nonempty_modularPolynomialData
import Definitions.FLT.Def_P2M_Util

/-!
# Places of K(j,j_N) have nonzero degree

Theorem statement: `ModularCurve.deg_ne_zero_modularFunctionFieldC`
(`86203315-985f-5ea0-9330-962da2bfe134`), by Claude, 2026-09-05.

Proof: submission `c43290c4-6d44-5ff4-aa2b-6a03143d17b9`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field (arbitrary characteristic) and let $N$ be a natural number with $N \neq 0$.
Inside the field $\mathrm{LaurentSeries}\ K$ of Laurent series over $K$, write $j$ for `jqModC K`,
the series $q^{-1}$ times the image under $K$-coefficient reduction of the integral power series
`jNum`, and $j_N$ for `jqNModC K N`, obtained from $j$ by the substitution `qExpand K N` (raising
the variable to the $N$-th power); let `modularFunctionFieldC K N` be the intermediate field
$K(j,j_N)$ of $\mathrm{LaurentSeries}\ K$ generated over $K$ by these two elements. Let $w$ be a
place of $K(j,j_N)$ over $K$ in the sense of the project's structure `Place`, that is, a valuation
subring of $K(j,j_N)$ which contains the image of $K$, is not the whole field, and is a principal
ideal ring. The conclusion is that $w.\mathrm{deg} \neq 0$, where $w.\mathrm{deg}$ is the
$K$-dimension $\operatorname{finrank}_K$ of the residue field of that valuation subring;
equivalently, the residue field of $w$ is a finite extension of $K$.

This is the statement that the level-$N$ modular function field, realised concretely as the subfield
$K(j,j_N)$ of $K((q))$, is a function field over $K$ in the sense that all its places have finite
residue degree. It is used in the construction of places of this field from solutions of the modular
polynomial and in the verifications that the modular function field and its base changes are curves
over the relevant base fields.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_deg_ne_zero_modularFunctionFieldC.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_deg_ne_zero_modularFunctionFieldC
p2m_attr_erase "instance" "ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.coeffEmb_coeff ModularCurve.coeffMap_coeff ModularCurve.coeffMap_id ModularCurve.coeffMap_single ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

open AlgebraicCurve ModularCurve IntermediateField Polynomial

noncomputable section

namespace S09T3

section Generic
variable {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F']
  [Algebra F F'] [IsScalarTower K F F'] [FiniteDimensional F F']

theorem deg_ne_zero_of_restrict (w : Place K F') (h : (w.restrict F).deg ≠ 0) : w.deg ≠ 0 := by
  rw [← w.deg_restrict_mul_inertiaDeg (F := F)]
  exact mul_ne_zero h (Place.inertiaDeg_pos_of_finiteDimensional (F := F) w).ne'
end Generic

variable (K : Type*) [Field K]

abbrev Fj : IntermediateField K (LaurentSeries K) := adjoin K ({jqModC K} : Set (LaurentSeries K))

noncomputable def psi : RatFunc K →ₐ[K] LaurentSeries K :=
  RatFunc.liftAlgHom (aeval (jqModC K))
    (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _
      (transcendental_iff_injective.mp (transcendental_jqModC K)))

theorem psi_injective : Function.Injective (psi K) :=
  RatFunc.liftAlgHom_injective _ (transcendental_iff_injective.mp (transcendental_jqModC K))

theorem psi_mem (f : RatFunc K) : psi K f ∈ Fj K := by
  rw [← f.num_div_denom, psi, RatFunc.liftAlgHom_apply_div]
  exact (mem_adjoin_simple_iff K _).mpr ⟨_, _, rfl⟩

noncomputable def ratFuncEquiv : RatFunc K ≃+* Fj K :=
  RingEquiv.ofBijective
    ({ toFun := fun f => ⟨psi K f, psi_mem K f⟩
       map_one' := Subtype.ext (map_one (psi K))
       map_mul' := fun a b => Subtype.ext (map_mul (psi K) a b)
       map_zero' := Subtype.ext (map_zero (psi K))
       map_add' := fun a b => Subtype.ext (map_add (psi K) a b) } : RatFunc K →+* Fj K)
    ⟨fun a b hab => psi_injective K (congrArg Subtype.val hab), by
      rintro ⟨x, hx⟩
      obtain ⟨r, s, rfl⟩ := (mem_adjoin_simple_iff K _).mp hx
      refine ⟨algebraMap _ _ r / algebraMap _ _ s, Subtype.ext ?_⟩
      show psi K (algebraMap _ _ r / algebraMap _ _ s) = _
      rw [psi, RatFunc.liftAlgHom_apply_div]⟩

theorem ratFuncEquiv_algebraMap (a : K) :
    ratFuncEquiv K (algebraMap K (RatFunc K) a) = algebraMap K (Fj K) a :=
  Subtype.ext (by exact (psi K).commutes a)

theorem deg_ne_zero_Fj (v : Place K (Fj K)) : v.deg ≠ 0 := by
  rw [← Place.deg_congrRingEquiv (ratFuncEquiv K).symm
    (Place.symm_algebraMap_comm _ (ratFuncEquiv_algebraMap K)) v]
  exact RationalFunctionField.deg_ne_zero _

variable (N : ℕ) [NeZero N]

abbrev FjN : IntermediateField (Fj K) (LaurentSeries K) :=
  adjoin (Fj K) ({jqNModC K N} : Set (LaurentSeries K))

theorem modularFunctionFieldC_eq_restrictScalars :
    modularFunctionFieldC K N = (FjN K N).restrictScalars K := by
  show modularFunctionFieldC K N =
    (adjoin (adjoin K ({jqModC K} : Set (LaurentSeries K))) ({jqNModC K N} : Set (LaurentSeries K))).restrictScalars K
  erw [adjoin_adjoin_left]
  rw [Set.singleton_union]
  rfl

noncomputable def toFjN : modularFunctionFieldC K N ≃+* FjN K N :=
  (equivOfEq (modularFunctionFieldC_eq_restrictScalars K N)).toRingEquiv.trans
    { toFun := fun x => ⟨x.1, x.2⟩
      invFun := fun x => ⟨x.1, x.2⟩
      left_inv := fun _ => rfl
      right_inv := fun _ => rfl
      map_mul' := fun _ _ => rfl
      map_add' := fun _ _ => rfl }

theorem toFjN_algebraMap (a : K) :
    toFjN K N (algebraMap K (modularFunctionFieldC K N) a) = algebraMap K (FjN K N) a :=
  Subtype.ext rfl

end S09T3

end

open S09T3 in
theorem solution (K : Type*) [Field K] (N : ℕ) [NeZero N] (w : Place K (modularFunctionFieldC K N)) : w.deg ≠ 0 := by
  obtain ⟨data⟩ := nonempty_modularPolynomialData N
  have : FiniteDimensional (Fj K) (FjN K N) := finiteDimensional_adjoin_jqNModC K data
  rw [← Place.deg_congrRingEquiv (toFjN K N) (toFjN_algebraMap K N) w]
  exact deg_ne_zero_of_restrict (F := Fj K) _ (deg_ne_zero_Fj K _)

end S_ModularCurve_deg_ne_zero_modularFunctionFieldC
end P2MW
export P2MW.S_ModularCurve_deg_ne_zero_modularFunctionFieldC (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve ModularCurve
theorem ModularCurve.deg_ne_zero_modularFunctionFieldC (K : Type*) [Field K] (N : ℕ) [NeZero N] (w : Place K (modularFunctionFieldC K N)) : w.deg ≠ 0 := _root_.P2MW.S_ModularCurve_deg_ne_zero_modularFunctionFieldC.solution K N w

end publicSection
