/-
Based on Prove2Me node ModularCurve.finrank_parabolicHoms_le_two_mul_genusFormula
(9f17692d-cfb8-560d-b46e-cc581ff77365) by Claude (2026-09-05).

Proof based on Prove2Me submission 1c1c96df-f2de-5249-b01b-3b1ff32f017f
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
public import Definitions.FLT.Def_ModularCurve_GenusNumerics
public import Definitions.FLT.Def_ModularCurve_PeriodMap

import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Rat.Star
import Theorems.FLT.Thm_ModularCurve_CuspSpace_card_cuspSpace_eq_cuspCount
import Theorems.FLT.Thm_ModularCurve_Gamma0_index
import Theorems.FLT.Thm_ModularCurve_Period_six_mul_finrank_parabolicHoms_add_le_index
import Theorems.FLT.Thm_ModularCurve_natCard_fixedPoints_ST_cosets_Gamma0_eq_nuThree
import Theorems.FLT.Thm_ModularCurve_natCard_fixedPoints_S_cosets_Gamma0_eq_nuTwo
import Definitions.FLT.Def_P2M_Util

/-!
# dim_K H¹ₚₐᵣ(Γ₀(N),K) ≤ 2g(N)

Theorem statement: `ModularCurve.finrank_parabolicHoms_le_two_mul_genusFormula`
(`9f17692d-cfb8-560d-b46e-cc581ff77365`), by Claude, 2026-09-05.

Proof: submission `1c1c96df-f2de-5249-b01b-3b1ff32f017f`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a nonzero natural number and let $K$ be a field of characteristic zero. Write
$\Gamma_0(N) \le \mathrm{SL}_2(\mathbb{Z})$ for the usual congruence subgroup and let
$\mathrm{Period.parabolicHoms}$ denote the $K$-submodule of the additive homomorphisms $\varphi$
from the abelianisation-free additive group $\mathrm{Additive}\,\Gamma_0(N)$ to $K$ consisting of
those $\varphi$ satisfying the predicate `IsParabolicHom`, i.e. $\varphi(\gamma) = 0$ for every
$\gamma \in \Gamma_0(N)$ whose underlying integral $2\times 2$ matrix has
$(\operatorname{tr}\gamma)^2 = 4$ (so $\varphi$ kills $\pm 1$ and all parabolic elements). The
assertion is that the $K$-dimension of this space, taken as `Module.finrank` and cast into
$\mathbb{Q}$, satisfies $$\dim_K \mathrm{parabolicHoms} \;\le\; 2\left(1 + \frac{\psi(N)}{12} -
\frac{\nu_2(N)}{4} - \frac{\nu_3(N)}{3} - \frac{\nu_\infty(N)}{2}\right),$$ where the right-hand
side is twice [`ModularCurve.genusFormula N`](def/ModularCurve_GenusNumerics.html#L20), with
$\psi(N) = \sum_{d \mid N,\ d \text{ squarefree}} N/d$, $\nu_2(N) = \#\{x \in \mathbb{Z}/N : x^2+1 =
0\}$, $\nu_3(N) = \#\{x \in \mathbb{Z}/N : x^2+x+1 = 0\}$ and $\nu_\infty(N) = \sum_{d \mid N}
\varphi(\gcd(d, N/d))$. Only the inequality is asserted, not the classical equality.

This is the group-theoretic half of the Eichler–Shimura dimension count: classically the space of
parabolic characters of $\Gamma_0(N)$ with values in a characteristic-zero field has dimension
exactly $2g(X_0(N))$, and here the upper bound by twice the rational genus formula is recorded. It
feeds the comparison of parabolic cohomology with cusp forms and the Eichler–Shimura dimension
statement, and thence the Hecke-equivariant period computations.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_finrank_parabolicHoms_le_two_mul_genusFormula.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_finrank_parabolicHoms_le_two_mul_genusFormula
p2m_attr_erase "instance" "ModularCurve.instFiniteProjectiveLine ModularCurve.unimodularRowSetoid ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.ProjectiveLine.map_mk ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularCurve.coeffEmb_coeff ModularCurve.coeffMap_coeff ModularCurve.coeffMap_id ModularCurve.coeffMap_single"

theorem solution (N : ℕ) [NeZero N]
    (K : Type*) [Field K] [CharZero K] :
    (Module.finrank K (ModularCurve.Period.parabolicHoms K (CongruenceSubgroup.Gamma0 N) K) : ℚ) ≤
      2 * ModularCurve.genusFormula N := by
  have hE := ModularCurve.Period.six_mul_finrank_parabolicHoms_add_le_index N K
  rw [ModularCurve.natCard_fixedPoints_S_cosets_Gamma0_eq_nuTwo N,
    ModularCurve.natCard_fixedPoints_ST_cosets_Gamma0_eq_nuThree N,
    ModularCurve.Gamma0_index N,
    ModularCurve.CuspSpace.card_cuspSpace_eq_cuspCount (NeZero.ne N)] at hE
  have hQ : (6 * Module.finrank K
        (ModularCurve.Period.parabolicHoms K (CongruenceSubgroup.Gamma0 N) K)
      + 6 * ModularCurve.cuspCount N + 3 * ModularCurve.nuTwo N + 4 * ModularCurve.nuThree N : ℚ)
      ≤ 12 + ModularCurve.dedekindPsi N := by
    exact_mod_cast hE
  unfold ModularCurve.genusFormula
  linarith

end S_ModularCurve_finrank_parabolicHoms_le_two_mul_genusFormula
end P2MW
export P2MW.S_ModularCurve_finrank_parabolicHoms_le_two_mul_genusFormula (solution)

end privateSection

public section publicSection

theorem ModularCurve.finrank_parabolicHoms_le_two_mul_genusFormula (N : ℕ) [NeZero N]
    (K : Type*) [Field K] [CharZero K] :
    (Module.finrank K (ModularCurve.Period.parabolicHoms K (CongruenceSubgroup.Gamma0 N) K) : ℚ) ≤
      2 * ModularCurve.genusFormula N := _root_.P2MW.S_ModularCurve_finrank_parabolicHoms_le_two_mul_genusFormula.solution N K

end publicSection
