/-
Based on Prove2Me node HeckeEis.finrank_coeffH1par_zero_le_two_mul_genusFormula
(1a32e6da-a69a-5c0e-9765-9a87792e6245) by Claude (2026-09-05).

Proof based on Prove2Me submission 8eb9a271-e577-5325-8f4f-e4386cc8dea8
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Basic.Complex.Basic
public import Definitions.FLT.Def_Gamma0CoeffCohomology
public import Definitions.FLT.Def_HeckeEis_BinaryFormRep
public import Definitions.FLT.Def_ModularCurve_GenusNumerics

import Mathlib.Analysis.CStarAlgebra.Classes
import Theorems.FLT.Thm_ModularCurve_Period_exists_basis_parabolicHoms_castAddHom_comp
import Theorems.FLT.Thm_ModularCurve_finrank_parabolicHoms_le_two_mul_genusFormula
import Definitions.FLT.Def_P2M_Util

/-!
# Weight-two parabolic cohomology bound for Γ₀(N)

Theorem statement: `HeckeEis.finrank_coeffH1par_zero_le_two_mul_genusFormula`
(`1a32e6da-a69a-5c0e-9765-9a87792e6245`), by Claude, 2026-09-05.

Proof: submission `8eb9a271-e577-5325-8f4f-e4386cc8dea8`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number, assumed nonzero. Consider the representation of $\Gamma_0(N)$ obtained
by restricting, along the inclusion of $\Gamma_0(N)$ into $\mathrm{SL}(2,\mathbb{Z})$, the
representation [`HeckeEis.binaryFormRepSL ℂ 0`](def/HeckeEis_BinaryFormRep.html#L61) of
$\mathrm{SL}(2,\mathbb{Z})$ on the space of homogeneous binary forms of degree $0$ over $\mathbb{C}$
(a one-dimensional space, on which $g$ acts by the substitution $X_j \mapsto \sum_i g_{ij} X_i$,
hence trivially in degree $0$). For this representation $\rho$, the space
[`HeckeEis.coeffH1par`](def/Gamma0CoeffCohomology.html#L100) is the quotient of the submodule of
parabolic cocycles, i.e. those $z : \Gamma_0(N) \to \mathbb{C}$ lying in `coeffCocycles ρ` and
satisfying `IsParabolicCocycle ρ`, by the intersection of that submodule with the coboundaries, the
range of `coeffCoboundaryMap ρ`. The assertion is that the $\mathbb{C}$-dimension of this quotient,
viewed as a rational number, satisfies $$\dim_{\mathbb C} H^1_{\mathrm{par}} \le 2\Bigl(1 +
\tfrac{\psi(N)}{12} - \tfrac{\nu_2(N)}{4} - \tfrac{\nu_3(N)}{3} - \tfrac{c(N)}{2}\Bigr),$$ where
$\psi(N) = \sum_{d \mid N,\ d \text{ squarefree}} N/d$, $\nu_2(N)$ and $\nu_3(N)$ count the
solutions in $\mathbb{Z}/N$ of $x^2+1=0$ and of $x^2+x+1=0$, and $c(N) = \sum_{d \mid N}
\varphi(\gcd(d, N/d))$.

This is the weight-two ($n=0$) instance of the bound $\dim H^1_{\mathrm{par}}(\Gamma_0(N),
\mathrm{Sym}^n) \le 2g(X_0(N))$, stated in the binary-form vocabulary: for trivial coefficients a
parabolic cocycle is a homomorphism $\Gamma_0(N) \to \mathbb{C}$ killing the parabolic elements, so
the count reduces to
[`ModularCurve.finrank_parabolicHoms_le_two_mul_genusFormula`](thm.html#ModularCurve.finrank_parabolicHoms_le_two_mul_genusFormula)
together with the integral basis statement
[`ModularCurve.Period.exists_basis_parabolicHoms_castAddHom_comp`](thm.html#ModularCurve.Period.exists_basis_parabolicHoms_castAddHom_comp).
It supplies the degree-zero slice used by
[`HeckeEis.isCompl_range_eichlerShimuraMap_range_conj`](thm.html#HeckeEis.isCompl_range_eichlerShimuraMap_range_conj).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula
p2m_attr_erase "instance" "ModularCurve.CuspSpace.instNonempty ModularCurve.CuspSpace.instSubsingletonOfOne ModularCurve.CuspSpace.instFinite ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.CuspSpace.cuspDenomAux_infty ModularCurve.CuspSpace.cuspDenomAux_coe ModularCurve.CuspSpace.cuspDenom_mk_zero ModularCurve.CuspSpace.cuspDenom_mk_infty ModularCurve.mapGL_apply_coe ModularCurve.ratPoint_one_zero ModularCurve.ratPoint_zero_right ModularCurve.CuspSpace.fromCoset_mk ModularCurve.CuspSpace.cuspDenom_mk ModularCurve.ratPoint_zero_one ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularCurve.coeffEmb_coeff ModularCurve.coeffMap_coeff ModularCurve.coeffMap_id ModularCurve.coeffMap_single"

set_option maxHeartbeats 800000
set_option synthInstance.maxHeartbeats 80000

open scoped MatrixGroups

noncomputable section

namespace HeckeEis
p2m_export "HeckeEis" "mem_coeffCocycles_iff mem_coeffCoboundaries_iff coeffParabolicCocycles coeffH1par coeffH1parMk coeffH1parMk_surjective coeffH1parMk_eq_zero_iff BinaryForm binarySubst binarySubst_C binaryFormRepSL"
namespace N0Sol
p2m_open "HeckeEis"

open MvPolynomial CongruenceSubgroup ModularCurve.Period

variable (N : ℕ)

abbrev ρ0 : Representation ℂ (Gamma0 N) ↥(BinaryForm ℂ 0) := (binaryFormRepSL ℂ 0).comp (Gamma0 N).subtype

theorem coe_eq_C (P : ↥(BinaryForm ℂ 0)) :
    (P : MvPolynomial (Fin 2) ℂ) = C (AddMonoidAlgebra.coeff (P : MvPolynomial (Fin 2) ℂ) 0) := by
  have hP : (P : MvPolynomial (Fin 2) ℂ).IsHomogeneous 0 := (mem_homogeneousSubmodule 0 _).mp P.2
  ext d
  rw [coeff_C]
  split_ifs with hd
  · rw [← hd]
  · by_contra h
    have hw := hP h
    have hdeg : d.degree = 0 := by rw [Finsupp.degree_eq_weight_one]; exact hw
    rw [Finsupp.degree_eq_zero_iff] at hdeg
    exact hd hdeg.symm

theorem ext0 {P Q : ↥(BinaryForm ℂ 0)}
    (h : AddMonoidAlgebra.coeff (P : MvPolynomial (Fin 2) ℂ) 0 =
      AddMonoidAlgebra.coeff (Q : MvPolynomial (Fin 2) ℂ) 0) :
    P = Q := by
  apply Subtype.ext
  rw [coe_eq_C P, coe_eq_C Q, h]

theorem rho0_apply (g : Gamma0 N) (P : ↥(BinaryForm ℂ 0)) : ρ0 N g P = P := by
  apply Subtype.ext
  show binarySubst ℂ (((g : Gamma0 N) : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) (P : MvPolynomial (Fin 2) ℂ) = P
  conv_lhs => rw [coe_eq_C P]
  rw [binarySubst_C, ← coe_eq_C P]

variable {N}

def toHom (z : ↥(coeffParabolicCocycles (ρ0 N))) : Additive (Gamma0 N) →+ ℂ where
  toFun a := AddMonoidAlgebra.coeff
    (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) (Additive.toMul a) : ↥(BinaryForm ℂ 0)) :
      MvPolynomial (Fin 2) ℂ) 0
  map_zero' := by
    have h := (mem_coeffCocycles_iff (ρ0 N) _).mp z.2.1 1 1
    rw [mul_one, rho0_apply] at h
    have h0 : (z : Gamma0 N → ↥(BinaryForm ℂ 0)) 1 = 0 := by
      have := congrArg (fun v => v - (z : Gamma0 N → ↥(BinaryForm ℂ 0)) 1) h
      have h0' : (0 : ↥(BinaryForm ℂ 0)) = (z : Gamma0 N → ↥(BinaryForm ℂ 0)) 1 := by simpa using this
      exact h0'.symm
    show AddMonoidAlgebra.coeff
      (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) 1 : ↥(BinaryForm ℂ 0)) :
        MvPolynomial (Fin 2) ℂ) 0 = 0
    rw [h0]; rfl
  map_add' a b := by
    show AddMonoidAlgebra.coeff
      (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) (Additive.toMul a * Additive.toMul b) :
        ↥(BinaryForm ℂ 0)) : MvPolynomial (Fin 2) ℂ) 0 =
      AddMonoidAlgebra.coeff
          (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) (Additive.toMul a) : ↥(BinaryForm ℂ 0)) :
            MvPolynomial (Fin 2) ℂ) 0 +
        AddMonoidAlgebra.coeff
          (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) (Additive.toMul b) : ↥(BinaryForm ℂ 0)) :
            MvPolynomial (Fin 2) ℂ) 0
    rw [(mem_coeffCocycles_iff (ρ0 N) _).mp z.2.1, rho0_apply, Submodule.coe_add,
      AddMonoidAlgebra.coeff_add, Finsupp.add_apply]

@[scoped simp] theorem toHom_apply (z : ↥(coeffParabolicCocycles (ρ0 N))) (g : Gamma0 N) :
    toHom z (Additive.ofMul g) = AddMonoidAlgebra.coeff
      (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) g : ↥(BinaryForm ℂ 0)) :
        MvPolynomial (Fin 2) ℂ) 0 := rfl

theorem toHom_mem (z : ↥(coeffParabolicCocycles (ρ0 N))) : toHom z ∈ parabolicHoms ℂ (Gamma0 N) ℂ := by
  intro γ hγ
  rw [toHom_apply]
  obtain ⟨u, hu⟩ := z.2.2 γ hγ
  rw [LinearMap.sub_apply, Module.End.one_apply, rho0_apply, sub_self] at hu
  rw [← hu]; rfl

def φ : ↥(coeffParabolicCocycles (ρ0 N)) →ₗ[ℂ] ↥(parabolicHoms ℂ (Gamma0 N) ℂ) where
  toFun z := ⟨toHom z, toHom_mem z⟩
  map_add' z w := by
    apply Subtype.ext; apply AddMonoidHom.ext; intro a
    show AddMonoidAlgebra.coeff
      ((((z + w : ↥(coeffParabolicCocycles (ρ0 N))) : Gamma0 N → ↥(BinaryForm ℂ 0))
        (Additive.toMul a) : ↥(BinaryForm ℂ 0)) : MvPolynomial (Fin 2) ℂ) 0 = _
    rw [Submodule.coe_add, Pi.add_apply, Submodule.coe_add, AddMonoidAlgebra.coeff_add,
      Finsupp.add_apply]
    rfl
  map_smul' c z := by
    apply Subtype.ext; apply AddMonoidHom.ext; intro a
    show AddMonoidAlgebra.coeff
      ((((c • z : ↥(coeffParabolicCocycles (ρ0 N))) : Gamma0 N → ↥(BinaryForm ℂ 0))
        (Additive.toMul a) : ↥(BinaryForm ℂ 0)) : MvPolynomial (Fin 2) ℂ) 0 = _
    rw [Submodule.coe_smul, Pi.smul_apply, Submodule.coe_smul, coeff_smul]
    rfl

theorem φ_apply_coe (z : ↥(coeffParabolicCocycles (ρ0 N))) (g : Gamma0 N) :
    ((φ z : ↥(parabolicHoms ℂ (Gamma0 N) ℂ)) : Additive (Gamma0 N) →+ ℂ) (Additive.ofMul g)
      = AddMonoidAlgebra.coeff
        (((z : Gamma0 N → ↥(BinaryForm ℂ 0)) g : ↥(BinaryForm ℂ 0)) :
          MvPolynomial (Fin 2) ℂ) 0 := rfl

theorem φ_injective : Function.Injective (φ (N := N)) := by
  intro z w h
  apply Subtype.ext; funext g
  apply ext0
  have := congrArg (fun ψ : ↥(parabolicHoms ℂ (Gamma0 N) ℂ) => (ψ : Additive (Gamma0 N) →+ ℂ) (Additive.ofMul g)) h
  simpa [φ_apply_coe] using this

theorem eq_of_mk_eq {a b : ↥(coeffParabolicCocycles (ρ0 N))} (h : coeffH1parMk _ a = coeffH1parMk _ b) : a = b := by
  rw [← sub_eq_zero, ← map_sub, coeffH1parMk_eq_zero_iff, mem_coeffCoboundaries_iff] at h
  obtain ⟨v, hv⟩ := h
  rw [← sub_eq_zero]
  apply Subtype.ext; funext g
  have := congrFun hv g
  rw [rho0_apply, sub_self] at this
  rw [← this]; rfl

def Ψ : coeffH1par (ρ0 N) →ₗ[ℂ] ↥(parabolicHoms ℂ (Gamma0 N) ℂ) where
  toFun x := φ (Function.surjInv (coeffH1parMk_surjective (ρ0 N)) x)
  map_add' x y := by
    rw [← map_add]
    congr 1
    apply eq_of_mk_eq
    rw [map_add, Function.surjInv_eq (coeffH1parMk_surjective _), Function.surjInv_eq (coeffH1parMk_surjective _),
      Function.surjInv_eq (coeffH1parMk_surjective _)]
  map_smul' c x := by
    rw [RingHom.id_apply, ← map_smul]
    congr 1
    apply eq_of_mk_eq
    rw [map_smul, Function.surjInv_eq (coeffH1parMk_surjective _), Function.surjInv_eq (coeffH1parMk_surjective _)]

theorem Ψ_mk (z : ↥(coeffParabolicCocycles (ρ0 N))) : Ψ (coeffH1parMk _ z) = φ z := by
  show φ (Function.surjInv (coeffH1parMk_surjective (ρ0 N)) (coeffH1parMk _ z)) = φ z
  congr 1
  apply eq_of_mk_eq
  rw [Function.surjInv_eq (coeffH1parMk_surjective _)]

theorem Ψ_injective : Function.Injective (Ψ (N := N)) := by
  intro x y h
  obtain ⟨a, rfl⟩ := coeffH1parMk_surjective _ x
  obtain ⟨b, rfl⟩ := coeffH1parMk_surjective _ y
  rw [Ψ_mk, Ψ_mk] at h
  rw [φ_injective h]

end HeckeEis.N0Sol
end
p2m_reactivate "P2MW.S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula.HeckeEis P2MW.S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula.HeckeEis.N0Sol"

theorem solution (N : ℕ) [NeZero N] :
    (Module.finrank ℂ (HeckeEis.coeffH1par ((HeckeEis.binaryFormRepSL ℂ 0).comp (CongruenceSubgroup.Gamma0 N).subtype)) : ℚ)
      ≤ 2 * ModularCurve.genusFormula N := by
  obtain ⟨t, b, hb⟩ := ModularCurve.Period.exists_basis_parabolicHoms_castAddHom_comp (CongruenceSubgroup.Gamma0 N)
  obtain ⟨bK, -⟩ := hb ℂ
  have : FiniteDimensional ℂ ↥(ModularCurve.Period.parabolicHoms ℂ (CongruenceSubgroup.Gamma0 N) ℂ) := Module.Finite.of_basis bK
  have h1 : Module.finrank ℂ (HeckeEis.coeffH1par ((HeckeEis.binaryFormRepSL ℂ 0).comp (CongruenceSubgroup.Gamma0 N).subtype))
      ≤ Module.finrank ℂ ↥(ModularCurve.Period.parabolicHoms ℂ (CongruenceSubgroup.Gamma0 N) ℂ) :=
    LinearMap.finrank_le_finrank_of_injective (HeckeEis.N0Sol.Ψ_injective (N := N))
  have h2 := ModularCurve.finrank_parabolicHoms_le_two_mul_genusFormula N ℂ
  calc (Module.finrank ℂ (HeckeEis.coeffH1par ((HeckeEis.binaryFormRepSL ℂ 0).comp (CongruenceSubgroup.Gamma0 N).subtype)) : ℚ)
      ≤ Module.finrank ℂ ↥(ModularCurve.Period.parabolicHoms ℂ (CongruenceSubgroup.Gamma0 N) ℂ) := by exact_mod_cast h1
    _ ≤ 2 * ModularCurve.genusFormula N := h2

end S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula
end P2MW
export P2MW.S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula (solution)

end privateSection

public section publicSection


open scoped MatrixGroups
theorem HeckeEis.finrank_coeffH1par_zero_le_two_mul_genusFormula (N : ℕ) [NeZero N] :
    (Module.finrank ℂ (HeckeEis.coeffH1par ((HeckeEis.binaryFormRepSL ℂ 0).comp (CongruenceSubgroup.Gamma0 N).subtype)) : ℚ)
      ≤ 2 * ModularCurve.genusFormula N := _root_.P2MW.S_HeckeEis_finrank_coeffH1par_zero_le_two_mul_genusFormula.solution N

end publicSection
