/-
Based on Prove2Me node ModularCurve.thetaL_jq_mul_deltaSeries
(024ea356-97da-57e2-b8b3-0fb6abb9f7ca) by Claude (2026-09-05).

Proof based on Prove2Me submission 203004d2-1ded-585d-8ad5-d584c9ae13c7
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ModularUnit
public import Definitions.FLT.Def_ModularCurve_QExpansionDiff
public import Definitions.FLT.Def_ModularCurve_TateFormal

import Theorems.FLT.Thm_ModularCurve_eisenstein4_mul_thetaL_delta_sub_eq_eisenstein6_mul_delta
import Theorems.FLT.Thm_ModularCurve_theta_mul
import Definitions.FLT.Def_P2M_Util

/-!
# Ramanujan's formula θ j·Δ=-E₄²E₆

Theorem statement: `ModularCurve.thetaL_jq_mul_deltaSeries`
(`024ea356-97da-57e2-b8b3-0fb6abb9f7ca`), by Claude, 2026-09-05.

Proof: submission `203004d2-1ded-585d-8ad5-d584c9ae13c7`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

The assertion is a single identity in the field of formal Laurent series $\mathbb{Q}(\!(q)\!)$,
realised as Hahn series over the integers with rational coefficients; it carries no variables and no
hypotheses. Here `jq` is the Laurent series $\mathrm{single}(-1,1)$ times the image of the power
series `jNum` (base-changed from $\mathbb{Z}$ to $\mathbb{Q}$), i.e. $q^{-1}$ times the
$q$-expansion numerator of the $j$-invariant; `deltaSeries` is $\mathrm{single}(1,1)$ times the
image of the unit power series `dedekindEtaUnit` base-changed to $\mathbb{Q}$, i.e.
$q\cdot\prod$-type discriminant series; and `thetaL ℚ` is the $\mathbb{Q}$-linear operator on
$\mathbb{Q}(\!(q)\!)$ sending $f$ to $\mathrm{single}(1,1)$ times the formal derivative of $f$, that
is $\theta=q\,d/dq$. The power series `eisenstein4` has constant term $1$ and $n$-th coefficient
$240\sum_{d\mid n}d^3$ for $n\ge 1$, and `eisenstein6` has constant term $1$ and $n$-th coefficient
$-504\sum_{d\mid n}d^5$. The conclusion is $\theta(j)\cdot\Delta = -\,(E_4^2E_6)$, the right-hand
side being the product `eisenstein4 ^ 2 * eisenstein6` mapped from $\mathbb{Z}$ to $\mathbb{Q}$ and
viewed as a Laurent series, negated.

This is Ramanujan's formula for the logarithmic derivative of the modular invariant, $\theta j =
-E_4^2E_6/\Delta = -E_{14}/\Delta$, in the formal $q$-expansion setting. It feeds the project's
treatment of $q$-expansions of differentials on $X_0(N)$: it is used for the statements about
regular differentials and their $q$-expansions along a cusp, and for membership of $\theta(j)$-type
series in the modular function field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_thetaL_jq_mul_deltaSeries.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_thetaL_jq_mul_deltaSeries
p2m_attr_erase "instance" "AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.Place.instIsScalarTowerSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Divisor.instDistribMulActionAlgEquiv AlgebraicCurve.Place.instSMulAlgEquiv AlgebraicCurve.Place.instIsPrincipalIdealRingSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Place.instIsDiscreteValuationRingSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Pic0.instDistribMulActionAlgEquiv AlgebraicCurve.Place.instAlgebraSubtypeMemValuationSubringToValuationSubring AlgebraicCurve.Place.instMulActionAlgEquiv AlgebraicCurve.Pic0.instSMulAlgEquiv AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup ModularCurve.instSMulAlgEquivRatPic0SubtypeLaurentSeriesMemIntermediateFieldLaurentBaseChange ModularCurve.instDistribMulActionAlgEquivRatPic0SubtypeLaurentSeriesMemIntermediateFieldLaurentBaseChange"
p2m_attr_erase "simp" "ModularCurve.coe_towerInclBar ModularCurve.coe_towerSubstBar ModularCurve.coe_heckeBetaBarRingHom ModularCurve.coe_heckeBetaBar ModularCurve.coe_heckeAlphaBar AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.Place.mk.injEq AlgebraicCurve.Divisor.degree_single AlgebraicCurve.Divisor.smul_single AlgebraicCurve.Place.smul_toValuationSubring AlgebraicCurve.Place.heightOneSpectrum_asIdeal AlgebraicCurve.Place.coe_algebraMap AlgebraicCurve.Place.ord_one AlgebraicCurve.Place.coe_smulRingEquiv_apply AlgebraicCurve.Pic0.coe_degZeroSMulHom AlgebraicCurve.Place.deg_smul AlgebraicCurve.Pic0.mk_zero AlgebraicCurve.Place.mk.sizeOf_spec AlgebraicCurve.Divisor.degree_smul AlgebraicCurve.Pic0.mk_add AlgebraicCurve.Place.ord_zero AlgebraicCurve.Place.ofHeightOneSpectrum_toValuationSubring AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut"
p2m_attr_erase "simp" "AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul ModularCurve.baseAut_arithmeticGalois ModularCurve.JZero.torsionGaloisRep_apply ModularCurve.coe_arithmeticRingAut_apply ModularCurve.toRingAut_arithmeticGalois ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

p2m_open "ModularCurve P2MW.S_ModularCurve_thetaL_jq_mul_deltaSeries.ModularCurve"

namespace ModularCurve
p2m_export "ModularCurve" "eisenstein6 laurentOfInt laurentOfInt_apply eisenstein4 dedekindEtaUnit dedekindEtaUnitInv dedekindEtaUnit_mul_inv jNum jNumQ jq dedekindEtaUnitQ deltaSeries deltaSeries_ne_zero thetaL thetaL_apply eisenstein4_mul_thetaL_delta_sub_eq_eisenstein6_mul_delta theta_mul"
namespace RC18C3
end ModularCurve.RC18C3
p2m_open_scoped "ModularCurve" in

theorem ModularCurve.RC18C3.jq_mul_deltaSeries :
    jq * deltaSeries = laurentOfInt ℚ (eisenstein4 ^ 3) := by
  have hι : ∀ f : PowerSeries ℤ,
      HahnSeries.ofPowerSeries ℤ ℚ (PowerSeries.map (Int.castRingHom ℚ) f) = laurentOfInt ℚ f := fun f => rfl
  rw [jq, deltaSeries, dedekindEtaUnitQ, jNumQ, jNum, hι, hι, mul_mul_mul_comm, HahnSeries.single_mul_single,
    ← map_mul, mul_assoc, mul_comm dedekindEtaUnitInv, dedekindEtaUnit_mul_inv, mul_one, mul_one,
    show (-1 : ℤ) + 1 = 0 by norm_num, HahnSeries.single_zero_one, one_mul]

p2m_open_scoped "ModularCurve" in

theorem ModularCurve.RC18C3.deltaSeries_eq_laurentOfInt :
    deltaSeries = laurentOfInt ℚ (PowerSeries.X * dedekindEtaUnit) := by
  rw [deltaSeries, dedekindEtaUnitQ, map_mul, laurentOfInt_apply, laurentOfInt_apply, PowerSeries.map_X,
    HahnSeries.ofPowerSeries_X]

theorem solution :
    thetaL ℚ jq * deltaSeries =
      -(HahnSeries.ofPowerSeries ℤ ℚ (PowerSeries.map (Int.castRingHom ℚ) (eisenstein4 ^ 2 * eisenstein6))) := by
  have hι : ∀ f : PowerSeries ℤ,
      HahnSeries.ofPowerSeries ℤ ℚ (PowerSeries.map (Int.castRingHom ℚ) f) = laurentOfInt ℚ f := fun f => rfl
  have hC2 := ModularCurve.eisenstein4_mul_thetaL_delta_sub_eq_eisenstein6_mul_delta
  rw [hι, hι, hι, ← ModularCurve.RC18C3.deltaSeries_eq_laurentOfInt] at hC2
  have hjΔ := ModularCurve.RC18C3.jq_mul_deltaSeries
  rw [map_pow] at hjΔ
  have hL := ModularCurve.theta_mul jq deltaSeries
  rw [hjΔ, show laurentOfInt ℚ eisenstein4 ^ 3 =
      laurentOfInt ℚ eisenstein4 * laurentOfInt ℚ eisenstein4 * laurentOfInt ℚ eisenstein4 by ring,
    ModularCurve.theta_mul (laurentOfInt ℚ eisenstein4 * laurentOfInt ℚ eisenstein4) (laurentOfInt ℚ eisenstein4),
    ModularCurve.theta_mul (laurentOfInt ℚ eisenstein4) (laurentOfInt ℚ eisenstein4)] at hL
  simp only [thetaL_apply] at hC2 ⊢
  rw [hι, map_mul, map_pow]
  apply mul_right_cancel₀ deltaSeries_ne_zero
  linear_combination (-deltaSeries) * hL + (-(laurentOfInt ℚ eisenstein4) ^ 2) * hC2 +
    (-((HahnSeries.single (1 : ℤ) (1 : ℚ) : LaurentSeries ℚ) * LaurentSeries.derivative ℚ deltaSeries)) * hjΔ

end S_ModularCurve_thetaL_jq_mul_deltaSeries
end P2MW
export P2MW.S_ModularCurve_thetaL_jq_mul_deltaSeries (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.thetaL_jq_mul_deltaSeries :
    thetaL ℚ jq * deltaSeries =
      -(HahnSeries.ofPowerSeries ℤ ℚ (PowerSeries.map (Int.castRingHom ℚ) (eisenstein4 ^ 2 * eisenstein6))) := _root_.P2MW.S_ModularCurve_thetaL_jq_mul_deltaSeries.solution

end publicSection
