/-
Based on Prove2Me node AlgebraicCurve.Divisor.evalFun_mul
(0855e902-069f-50bf-ba69-8866a1d7de0f) by Claude (2026-09-05).

Proof based on Prove2Me submission e0624130-76dc-55c8-b2ea-9d2cde60744a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_PlaceEvaluation

import Theorems.FLT.Thm_AlgebraicCurve_Place_evalAt_mul
import Definitions.FLT.Def_P2M_Util

/-!
# Multiplicativity of f ↦ f(D) at rational places

Theorem statement: `AlgebraicCurve.Divisor.evalFun_mul` (`0855e902-069f-50bf-ba69-8866a1d7de0f`), by
Claude, 2026-09-05.

Proof: submission `e0624130-76dc-55c8-b2ea-9d2cde60744a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, let $f, g \in F$, and let $D$ be a divisor of
$F/K$, that is, a finitely supported function from the type [`AlgebraicCurve.Place K
F`](def/AlgebraicCurve_DivisorClassGroup.html#L22) of places of $F/K$ to $\mathbb{Z}$; here a place
is a valuation subring of $F$ which contains the image of $K$, is not all of $F$, and is a principal
ideal ring. Assume three conditions on the places $v$ in the support of $D$: each such $v$ satisfies
`Place.IsRational`, i.e. the composite $K \to v \to \kappa(v)$ into the residue field of $v$ is
surjective; and both $f$ and $g$ lie in the valuation subring attached to $v$. Then the conclusion
is the identity $(fg)(D) = f(D)\,g(D)$ for the evaluation $h(D) := \prod_{v \in \operatorname{supp}
D} \mathrm{ev}_v(h)^{D(v)} \in K$, the product over the support of $D$ of integral powers of the
local values $\mathrm{ev}_v(h)$, where $\mathrm{ev}_v(h) \in K$ is, for $h$ in the valuation subring
of $v$, the preimage in $K$ (via the chosen inverse `residueInv` of the surjection onto $\kappa(v)$)
of the residue class of $h$, and is $0$ otherwise.

This is multiplicativity in the function of the local symbol $f(D)$ attached to a divisor supported
on rational places. It belongs to the layer of evaluation of functions at divisors underlying Weil
reciprocity and the bilinearity of the Weil pairing, and is used in the computations for the
rational function field, for instance in identifying values at the place at infinity and at places
coming from points.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Divisor_evalFun_mul.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Divisor_evalFun_mul

open AlgebraicCurve

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] {f g : F} {D : Divisor K F} (hrat : ∀ v ∈ D.support, Place.IsRational v) (hf : ∀ v ∈ D.support, f ∈ v.toValuationSubring) (hg : ∀ v ∈ D.support, g ∈ v.toValuationSubring) : Divisor.evalFun (f * g) D = Divisor.evalFun f D * Divisor.evalFun g D := by
  rw [show Divisor.evalFun (f * g) D = D.prod fun v n => v.evalAt f ^ n * v.evalAt g ^ n from
    Finsupp.prod_congr fun v hv => by
      rw [AlgebraicCurve.Place.evalAt_mul v (hrat v hv) (hf v hv) (hg v hv), mul_zpow]]
  exact Finsupp.prod_mul

end S_AlgebraicCurve_Divisor_evalFun_mul
end P2MW
export P2MW.S_AlgebraicCurve_Divisor_evalFun_mul (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.Divisor.evalFun_mul {K F : Type*} [Field K] [Field F] [Algebra K F] {f g : F} {D : Divisor K F} (hrat : ∀ v ∈ D.support, Place.IsRational v) (hf : ∀ v ∈ D.support, f ∈ v.toValuationSubring) (hg : ∀ v ∈ D.support, g ∈ v.toValuationSubring) : Divisor.evalFun (f * g) D = Divisor.evalFun f D * Divisor.evalFun g D := _root_.P2MW.S_AlgebraicCurve_Divisor_evalFun_mul.solution hrat hf hg

end publicSection
