/-
Based on Prove2Me node ModularForm.levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant
(d50a0369-6f22-53be-8459-cdd59ce95206) by Claude (2026-09-05).

Proof based on Prove2Me submission 7be5f29a-1076-51f5-8a10-56a56cc887e4
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_FLTPrelim_Modularity
public import Mathlib.NumberTheory.ModularForms.Discriminant

import Mathlib.NumberTheory.ModularForms.LevelOne.DimensionFormula
import Definitions.FLT.Def_P2M_Util

/-!
# Level-one weight-12 forms with vanishing constant term are τ-multiples

Theorem statement: `ModularForm.levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant`
(`d50a0369-6f22-53be-8459-cdd59ce95206`), by Claude, 2026-09-05.

Proof: submission `7be5f29a-1076-51f5-8a10-56a56cc887e4`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $Z$ be a modular form of weight $12$ for the full modular group $\mathrm{SL}_2(\mathbb{Z})$
(written $\mathcal{SL}$ in the statement). For a function $f \colon \mathbb{H} \to \mathbb{C}$ and
$n \in \mathbb{N}$, write $\mathrm{qCoeff}(f, n)$ for the $n$-th coefficient of the $q$-expansion of
$f$ taken with respect to the period $1$, i.e. the coefficient of $q^n$ in `qExpansion 1 f`. Assume
that the constant term of $Z$ vanishes, $\mathrm{qCoeff}(Z, 0) = 0$. Then for every natural number
$n$, $$\mathrm{qCoeff}(Z, n) = \mathrm{qCoeff}(Z, 1) \cdot \mathrm{qCoeff}(\Delta, n),$$ where
$\Delta$ denotes the modular discriminant `ModularForm.discriminant`, regarded as a function on the
upper half plane. Thus all $q$-expansion coefficients of such a $Z$ are determined by its first
coefficient, being $a_1(Z)\tau(n)$ with $\tau$ the Ramanujan function, and in particular $Z$ is a
scalar multiple of $\Delta$ at the level of $q$-expansions.

This is the coefficient form of the statement that the space of cusp forms of weight $12$ and level
one is one-dimensional, spanned by $\Delta = q - 24q^2 + \cdots$: a weight-$12$ level-one form with
vanishing constant term is a multiple of $\Delta$. It is used in the project's analysis of the
$q$-expansion of modular functions on the modular curve, in particular in the bounds on analytic
orders of vanishing in terms of integrality of the $j$-function's $q$-expansion coefficients.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant
set_option Elab.async false
open scoped MatrixGroups

namespace WL12Pen

private theorem exists_coe_eq_smul_discriminant (Z : ModularForm 𝒮ℒ 12)
    (h0 : ModularFormClass.qCoeff ⇑Z 0 = 0) :
    ∃ c : ℂ, (⇑Z : UpperHalfPlane → ℂ) = c • ⇑CuspForm.discriminant := by
  obtain ⟨c, hc⟩ :=
    CuspForm.exists_smul_discriminant_of_weight_eq_twelve (ModularForm.toCuspForm Z h0)
  exact ⟨c, (show (c • ⇑CuspForm.discriminant : UpperHalfPlane → ℂ)
    = ⇑(ModularForm.toCuspForm Z h0) from congrArg DFunLike.coe hc).symm⟩

private theorem qExpansion_eq_smul (Z : ModularForm 𝒮ℒ 12) (c : ℂ)
    (hZ : (⇑Z : UpperHalfPlane → ℂ) = c • ⇑CuspForm.discriminant) :
    UpperHalfPlane.qExpansion 1 ⇑Z = c • UpperHalfPlane.qExpansion 1 ModularForm.discriminant := by
  rw [hZ, ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL c CuspForm.discriminant,
    CuspForm.coe_discriminant]

private theorem qCoeff_eq_mul (Z : ModularForm 𝒮ℒ 12) (c : ℂ)
    (hq : UpperHalfPlane.qExpansion 1 ⇑Z
      = c • UpperHalfPlane.qExpansion 1 ModularForm.discriminant) (n : ℕ) :
    ModularFormClass.qCoeff ⇑Z n = c * ModularFormClass.qCoeff ModularForm.discriminant n := by
  unfold ModularFormClass.qCoeff
  rw [hq, PowerSeries.coeff_smul, smul_eq_mul]

private theorem qCoeff_one_eq (Z : ModularForm 𝒮ℒ 12) (c : ℂ)
    (hq : UpperHalfPlane.qExpansion 1 ⇑Z
      = c • UpperHalfPlane.qExpansion 1 ModularForm.discriminant) :
    ModularFormClass.qCoeff ⇑Z 1 = c := by
  have h1 : ModularFormClass.qCoeff ModularForm.discriminant 1 = 1 := by
    unfold ModularFormClass.qCoeff
    exact ModularForm.discriminant_qExpansion_coeff_one
  rw [qCoeff_eq_mul Z c hq 1, h1, mul_one]

end WL12Pen

namespace ModularForm
p2m_export "ModularForm" "toCuspForm discriminant discriminant_qExpansion_coeff_one"
end ModularForm
p2m_open_scoped "ModularForm" in
private theorem ModularForm.levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant (Z : ModularForm 𝒮ℒ 12) (h0 : ModularFormClass.qCoeff ⇑Z 0 = 0) : ∀ n : ℕ, ModularFormClass.qCoeff ⇑Z n = ModularFormClass.qCoeff ⇑Z 1 * ModularFormClass.qCoeff ModularForm.discriminant n := by
  obtain ⟨c, hZ⟩ := WL12Pen.exists_coe_eq_smul_discriminant Z h0
  have hq := WL12Pen.qExpansion_eq_smul Z c hZ
  intro n
  rw [WL12Pen.qCoeff_eq_mul Z c hq n, WL12Pen.qCoeff_one_eq Z c hq]

theorem solution (Z : ModularForm 𝒮ℒ 12) (h0 : ModularFormClass.qCoeff ⇑Z 0 = 0) : ∀ n : ℕ, ModularFormClass.qCoeff ⇑Z n = ModularFormClass.qCoeff ⇑Z 1 * ModularFormClass.qCoeff ModularForm.discriminant n :=
  ModularForm.levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant Z h0

end S_ModularForm_levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant
end P2MW
export P2MW.S_ModularForm_levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant (solution)

end privateSection

public section publicSection


open scoped MatrixGroups
theorem ModularForm.levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant (Z : ModularForm 𝒮ℒ 12) (h0 : ModularFormClass.qCoeff ⇑Z 0 = 0) : ∀ n : ℕ, ModularFormClass.qCoeff ⇑Z n = ModularFormClass.qCoeff ⇑Z 1 * ModularFormClass.qCoeff ModularForm.discriminant n := _root_.P2MW.S_ModularForm_levelOne_weight_twelve_qCoeff_eq_qCoeff_one_mul_discriminant.solution Z h0

end publicSection
