/-
Based on Prove2Me node ModularCurve.laurentBaseChange_modularFunctionField
(965445f6-eb6c-557d-834d-71e1f7ea99ac) by Claude (2026-09-05).

Proof based on Prove2Me submission 506d7936-d4d7-5270-83b8-310c8cb62fbb
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_LaurentCoeff
public import Definitions.FLT.Def_ModularCurve_JqCoeff

import Theorems.FLT.Thm_ModularCurve_coeffEmb_jq
import Theorems.FLT.Thm_ModularCurve_coeffEmb_jqN
import Definitions.FLT.Def_P2M_Util

/-!
# Base change of the modular function field along ℚ↪ L

Theorem statement: `ModularCurve.laurentBaseChange_modularFunctionField`
(`965445f6-eb6c-557d-834d-71e1f7ea99ac`), by Claude, 2026-09-05.

Proof: submission `506d7936-d4d7-5270-83b8-310c8cb62fbb`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $L$ be a field equipped with a $\mathbb{Q}$-algebra structure and let $N$ be a nonzero natural
number. Inside the field $L((q))$ of Laurent series over $L$, consider two intermediate fields of
$L((q))/L$. The first is `laurentBaseChange L (modularFunctionField N)`: starting from the
intermediate field `modularFunctionField N` of $\mathbb{Q}((q))/\mathbb{Q}$ generated over
$\mathbb{Q}$ by the two elements `jq` and `qExpand ℚ N jq`, where `qExpand R N` is the ring
endomorphism of $R((q))$ obtained by multiplying all exponents by $N$ (substitution $q \mapsto
q^{N}$), one takes the image of this field under the coefficient embedding `coeffEmb L : ℚ((q)) →
L((q))` induced by $\mathbb{Q} \to L$, and adjoins that image to $L$. The second is
`modularFunctionFieldC L N`, the subfield of $L((q))$ generated over $L$ by `jqModC L`, namely
$q^{-1}$ times the power series `jNum` with coefficients cast into $L$, together with `jqNModC L N =
qExpand L N (jqModC L)`. The assertion is that these two intermediate fields of $L((q))/L$ coincide.

This identifies the base change to $L$ of the two-generator modular function field $\mathbb{Q}(j(q),
j(q^{N})) \subseteq \mathbb{Q}((q))$ with the field $L(j(q), j(q^{N})) \subseteq L((q))$ generated
by the same $q$-expansions read with coefficients in $L$; no statement is made about the field
generated by $j(q^{d})$ for all divisors $d \mid N$. It serves as the compatibility step allowing
arguments about $X_0(N)$ and its function field to be transported from $\mathbb{Q}$ to an arbitrary
field of characteristic zero, and is used in the construction of fibre models on cusp charts and in
the study of the cuspidal divisor class.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_laurentBaseChange_modularFunctionField.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_laurentBaseChange_modularFunctionField

open ModularCurve IntermediateField HahnSeries

theorem solution (L : Type*) [Field L] [Algebra ℚ L] (N : ℕ) [NeZero N] : ModularCurve.laurentBaseChange L (ModularCurve.modularFunctionField N) = ModularCurve.modularFunctionFieldC L N := by
  apply le_antisymm
  · change IntermediateField.adjoin L (⇑(coeffEmb L) '' (modularFunctionField N : Set (LaurentSeries ℚ)))
      ≤ modularFunctionFieldC L N
    rw [IntermediateField.adjoin_le_iff]
    rintro _ ⟨x, hx, rfl⟩
    change x ∈ IntermediateField.adjoin ℚ {jq, qExpand ℚ N jq} at hx
    induction hx using IntermediateField.adjoin_induction with
    | mem x hx =>
        rcases hx with rfl | rfl
        · rw [coeffEmb_jq]; exact jqModC_mem L N
        · rw [show qExpand ℚ N jq = jqN N from rfl, coeffEmb_jqN]; exact jqNModC_mem L N
    | algebraMap c =>
        have h : (coeffEmb L).comp (algebraMap ℚ (LaurentSeries ℚ))
            = (algebraMap L (LaurentSeries L)).comp (algebraMap ℚ L) := RingHom.ext_rat _ _
        have hc := congrArg (fun f : ℚ →+* LaurentSeries L => f c) h
        simp only [RingHom.coe_comp, Function.comp_apply] at hc
        simp only [SetLike.mem_coe, hc]
        exact (modularFunctionFieldC L N).algebraMap_mem _
    | add x y _ _ hx hy => simpa only [SetLike.mem_coe, map_add] using add_mem hx hy
    | inv x _ hx => simpa only [SetLike.mem_coe, map_inv₀] using inv_mem hx
    | mul x y _ _ hx hy => simpa only [SetLike.mem_coe, map_mul] using mul_mem hx hy
  · change IntermediateField.adjoin L {jqModC L, jqNModC L N}
      ≤ IntermediateField.adjoin L (⇑(coeffEmb L) '' (modularFunctionField N : Set (LaurentSeries ℚ)))
    apply IntermediateField.adjoin.mono
    rintro _ (rfl | rfl)
    · exact ⟨jq, jq_mem N, coeffEmb_jq L⟩
    · exact ⟨qExpand ℚ N jq, jqN_mem N, coeffEmb_jqN L N⟩

end S_ModularCurve_laurentBaseChange_modularFunctionField
end P2MW
export P2MW.S_ModularCurve_laurentBaseChange_modularFunctionField (solution)

end privateSection

public section publicSection

theorem ModularCurve.laurentBaseChange_modularFunctionField (L : Type*) [Field L] [Algebra ℚ L] (N : ℕ) [NeZero N] : ModularCurve.laurentBaseChange L (ModularCurve.modularFunctionField N) = ModularCurve.modularFunctionFieldC L N := _root_.P2MW.S_ModularCurve_laurentBaseChange_modularFunctionField.solution L N

end publicSection
