/-
Based on Prove2Me node CuspForm.heckeULin_comm
(1a0bb677-dd7a-5d47-abbc-26825c474234) by Claude (2026-09-05).

Proof based on Prove2Me submission a3d29882-3a25-524d-bcfa-f938897fcf12
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularForm_HeckeOperatorForms

import Theorems.FLT.Thm_ModularFormClass_heckeU_heckeU_comm
import Definitions.FLT.Def_P2M_Util

/-!
# Commutativity of Uₚ and U_q on S_k(Γ₀(N))

Theorem statement: `CuspForm.heckeULin_comm` (`1a0bb677-dd7a-5d47-abbc-26825c474234`), by Claude,
2026-09-05.

Proof: submission `a3d29882-3a25-524d-bcfa-f938897fcf12`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number, assumed nonzero, let $k$ be an integer, and let $p,q$ be natural
numbers with $p \mid N$ and $q \mid N$. For a divisor $p$ of $N$, [`CuspForm.heckeULin k
hpN`](def/ModularForm_HeckeOperatorForms.html#L83) is the $\mathbb{C}$-linear endomorphism of the
space `CuspForm (CongruenceSubgroup.Gamma0 N) k` of weight $k$ cusp forms on $\Gamma_0(N)$ that
sends $f$ to the cusp form whose underlying function on the upper half plane is
$\mathrm{heckeU}\,k\,p\,f = \sum_{j<p} f \mid_k \mathrm{heckeMatrix}\,p\,j$, the slash invariance
under $\Gamma_0(N)$, the holomorphy and the vanishing at the cusps of this sum being supplied by the
construction; the divisibility proofs are literally arguments of the operators, which is why they
occur as binders. The assertion is that these two endomorphisms commute in the ring of
$\mathbb{C}$-linear endomorphisms of $S_k(\Gamma_0(N))$, i.e. `Commute (CuspForm.heckeULin k hpN)
(CuspForm.heckeULin k hqN)`, so $U_p U_q = U_q U_p$. No primality of $p$ or $q$ is required.

This is the commutativity of the Hecke operators $U_p$ for primes dividing the level, part of the
commutativity of the full Hecke algebra acting on $S_k(\Gamma_0(N))$. It is used in the construction
of normalized Hecke eigenforms
([`CuspForm.exists_isNormalizedEigenform_of_forall_heckeTLin_eq_smul`](thm.html#CuspForm.exists_isNormalizedEigenform_of_forall_heckeTLin_eq_smul),
[`CuspForm.exists_normalized_eigenvector`](thm.html#CuspForm.exists_normalized_eigenvector)) and in
computing traces of the $U$-operators
([`CuspForm.traceLin_heckeULin`](thm.html#CuspForm.traceLin_heckeULin)).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_CuspForm_heckeULin_comm.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_CuspForm_heckeULin_comm

theorem solution {N : ℕ} [NeZero N] (k : ℤ) {p q : ℕ} (hpN : p ∣ N) (hqN : q ∣ N) :
    Commute (CuspForm.heckeULin k hpN) (CuspForm.heckeULin k hqN) := by
  rw [commute_iff_eq]; ext f τ
  simpa using congrFun (ModularFormClass.heckeU_heckeU_comm f (by simp) p q) τ

end S_CuspForm_heckeULin_comm
end P2MW
export P2MW.S_CuspForm_heckeULin_comm (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem CuspForm.heckeULin_comm {N : ℕ} [NeZero N] (k : ℤ) {p q : ℕ} (hpN : p ∣ N) (hqN : q ∣ N) :
    Commute (CuspForm.heckeULin k hpN) (CuspForm.heckeULin k hqN) := _root_.P2MW.S_CuspForm_heckeULin_comm.solution k hpN hqN

end publicSection
