/-
Based on Prove2Me node ModularCurve.qExpansion_E4_eq_map_eisenstein4
(24fcb766-5d41-5d56-976b-59ad4bde647b) by Claude (2026-09-05).

Proof based on Prove2Me submission 7b1feb85-48db-5059-8057-aadc774bbe0a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0
public import Mathlib.NumberTheory.ModularForms.EisensteinSeries.QExpansion

import Definitions.FLT.Def_P2M_Util

/-!
# q-expansion of E₄ equals 1+240sumσ₃(n)qⁿ

Theorem statement: `ModularCurve.qExpansion_E4_eq_map_eisenstein4`
(`24fcb766-5d41-5d56-976b-59ad4bde647b`), by Claude, 2026-09-05.

Proof: submission `7b1feb85-48db-5059-8057-aadc774bbe0a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

The statement compares two power series with no hypotheses or parameters. On the analytic side,
`UpperHalfPlane.qExpansion 1 ⇑ModularForm.E₄` is Mathlib's $q$-expansion, with respect to the period
$1$, of the function underlying the weight-$4$ normalised Eisenstein series `ModularForm.E₄` on the
upper half-plane; it is the element of $\mathbb{C}[[q]]$ whose $n$-th coefficient is the $n$-th
Taylor coefficient at $q=0$ of the function of $q=e^{2\pi i\tau}$ induced by $E_4$. On the formal
side, [`ModularCurve.eisenstein4`](def/ModularCurve_X0.html#L111) is the power series over
$\mathbb{Z}$ whose $n$-th coefficient is $1$ when $n=0$ and $240\sum_{d\mid n} d^3$ otherwise, the
sum being over the divisors of $n$ in the sense of `Nat.divisors`; `PowerSeries.map (Int.castRingHom
ℂ)` applies the canonical ring homomorphism $\mathbb{Z}\to\mathbb{C}$ to each coefficient. The
assertion is that these two elements of $\mathbb{C}[[q]]$ coincide, i.e. that $E_4(\tau) = 1 +
240\sum_{n\ge 1}\sigma_3(n)q^n$ coefficientwise as formal power series.

This is the classical $q$-expansion of the normalised weight-$4$ Eisenstein series for
$\mathrm{SL}_2(\mathbb{Z})$. It identifies the purely formal integral series used in the
$q$-expansion description of modular curves and their function fields with the analytic modular form
`ModularForm.E₄`, and is used by the level-structure and Tate-curve computations that invoke $E_4$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_qExpansion_E4_eq_map_eisenstein4.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_qExpansion_E4_eq_map_eisenstein4

noncomputable section

open UpperHalfPlane Complex Filter Topology
open scoped MatrixGroups PowerSeries.WithPiTopology

local notation "𝕢" => Function.Periodic.qParam

namespace ModularCurve
p2m_export "ModularCurve" "eisenstein4"
end ModularCurve

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_qExpansion_E4_eq_map_eisenstein4.ModularCurve in
theorem solution : UpperHalfPlane.qExpansion 1 ⇑ModularForm.E₄ = PowerSeries.map (Int.castRingHom ℂ) ModularCurve.eisenstein4 := by
  ext m
  rw [EisensteinSeries.E_qExpansion_coeff _ ⟨2, rfl⟩ m, PowerSeries.coeff_map, eisenstein4,
    PowerSeries.coeff_mk]
  split_ifs with hm
  · simp
  · rw [bernoulli_eq_bernoulli'_of_ne_one (by norm_num), bernoulli'_four,
      ArithmeticFunction.sigma_apply]
    simp only [eq_intCast, Int.cast_mul, Int.cast_ofNat, Int.cast_sum, Int.cast_pow,
      Int.cast_natCast]
    push_cast
    ring
end

end S_ModularCurve_qExpansion_E4_eq_map_eisenstein4
end P2MW
export P2MW.S_ModularCurve_qExpansion_E4_eq_map_eisenstein4 (solution)

end privateSection

public section publicSection

theorem ModularCurve.qExpansion_E4_eq_map_eisenstein4 : UpperHalfPlane.qExpansion 1 ⇑ModularForm.E₄ = PowerSeries.map (Int.castRingHom ℂ) ModularCurve.eisenstein4 := _root_.P2MW.S_ModularCurve_qExpansion_E4_eq_map_eisenstein4.solution

end publicSection
