/-
Based on Prove2Me node ModularCurve.exists_phiIrreducible_evalSymm
(66befd22-55d2-533d-a261-ddb7399e4802) by Claude (2026-09-05).

Proof based on Prove2Me submission d69154cc-2187-5d53-8545-df3b03f29595
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0
public import Definitions.FLT.Def_ModularCurve_PhiGen

import Theorems.FLT.Thm_ModularCurve_PhiGen_exists_phiGenDescends
import Theorems.FLT.Thm_ModularCurve_PhiGen_PhiGenDescends_intCoeffs
import Theorems.FLT.Thm_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends
import Theorems.FLT.Thm_ModularCurve_PhiGen_exists_modularPolynomialData_coeff_eq
import Theorems.FLT.Thm_ModularCurve_PhiGen_evalSymm_of_coeff_evalAtJ_eq
import Theorems.FLT.Thm_ModularCurve_PhiGen_splits_of_coeff_evalAtJ_eq
import Theorems.FLT.Thm_ModularCurve_PhiGen_phiIrreducible_of_splits
import Mathlib.NumberTheory.Cyclotomic.Basic
import Definitions.FLT.Def_P2M_Util

/-!
# Existence of an irreducible symmetric modular polynomial Φ_ℓ

Theorem statement: `ModularCurve.exists_phiIrreducible_evalSymm`
(`66befd22-55d2-533d-a261-ddb7399e4802`), by Claude, 2026-09-05.

Proof: submission `d69154cc-2187-5d53-8545-df3b03f29595`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\ell$ be a prime. The assertion is that there exists a term `data` of the structure
`ModularPolynomialData ℓ`, that is, a polynomial $\Phi =$ `data.Φ` in $(\mathbb{Z}[X])[Y]$ which is
monic, whose degree in $Y$ equals `dedekindPsi ℓ`, the sum of $\ell/d$ over the squarefree divisors
$d$ of $\ell$ (so $\ell+1$), and which satisfies $\Phi.\mathrm{eval}_2(\mathrm{evalAtJ},
\mathrm{jqN}\ \ell) = 0$, where `evalAtJ` is the ring homomorphism $\mathbb{Z}[X] \to$
`LaurentSeries ℚ` evaluating a coefficient polynomial at the Laurent series `jq`, and `jqN ℓ` is the
Laurent series of that name; and such that this same packet has both of the following two
properties. First, `PhiIrreducible data`: the polynomial `data.toAdjoin`, obtained from $\Phi$ by
mapping its coefficients through `evalAtJGen` into the intermediate field
$\mathbb{Q}\langle\mathrm{jq}\rangle$ generated by `jq`, is irreducible over that field. Second,
`EvalSymm data.Φ`: for all Laurent series $x, y$ over $\mathbb{Q}$, evaluating $\Phi$ by
substituting $x$ into the coefficient polynomials and $y$ into the outer variable gives the same
result as substituting $y$ into the coefficients and $x$ into the outer variable.

This is the existence, for each prime $\ell$, of the classical modular polynomial $\Phi_\ell(X,Y)$
relating $j(q)$ and $j(q^\ell)$, in the strong form in which irreducibility over $\mathbb{Q}(j)$ and
the symmetry $\Phi_\ell(X,Y)=\Phi_\ell(Y,X)$ hold for one and the same packet; the pair of
properties is what pins the packet down. It feeds the uniqueness statement
[`ModularCurve.ModularPolynomialData.eq_of_prime`](thm.html#ModularCurve.ModularPolynomialData.eq_of_prime),
the construction of the Fricke involution
[`ModularCurve.exists_isFrickeAut`](thm.html#ModularCurve.exists_isFrickeAut), and the existence of
a monic relation
[`ModularCurve.exists_monic_evalAtJ_jqN_eq_zero`](thm.html#ModularCurve.exists_monic_evalAtJ_jqN_eq_zero).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_phiIrreducible_evalSymm.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_phiIrreducible_evalSymm
p2m_attr_erase "simp" "ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL"

noncomputable section

open Polynomial

namespace ModularCurve
p2m_export "ModularCurve" "jq ModularPolynomialData EvalSymm PhiIrreducible PhiGen.IntCoeffs PhiGen.exists_phiGenDescends PhiGen.mem_adjoin_jq_of_phiGenDescends PhiGen.exists_modularPolynomialData_coeff_eq PhiGen.evalSymm_of_coeff_evalAtJ_eq PhiGen.splits_of_coeff_evalAtJ_eq PhiGen.phiIrreducible_of_splits"
p2m_open "ModularCurve"

private theorem exists_phiIrreducible_evalSymm (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] :
    ∃ data : ModularPolynomialData ℓ, PhiIrreducible data ∧ EvalSymm data.Φ := by
  have : NeZero ((ℓ : ℕ) : ℚ) := ⟨Nat.cast_ne_zero.mpr hℓ.out.ne_zero⟩
  have hcyc : IsCyclotomicExtension {ℓ} ℚ (CyclotomicField ℓ ℚ) :=
    CyclotomicField.isCyclotomicExtension (n := ℓ) (K := ℚ)
  have : FiniteDimensional ℚ (CyclotomicField ℓ ℚ) :=
    IsCyclotomicExtension.finiteDimensional {ℓ} ℚ (CyclotomicField ℓ ℚ)
  have : IsGalois ℚ (CyclotomicField ℓ ℚ) :=
    IsCyclotomicExtension.isGalois (S := {ℓ}) (K := ℚ) (L := CyclotomicField ℓ ℚ)
  obtain ⟨z, hz⟩ := IsCyclotomicExtension.exists_isPrimitiveRoot ℚ (CyclotomicField ℓ ℚ)
    (Set.mem_singleton ℓ) hℓ.out.ne_zero
  have hzu : IsUnit z := hz.isUnit hℓ.out.ne_zero
  have hζ : IsPrimitiveRoot ((hzu.unit : (CyclotomicField ℓ ℚ)ˣ) : CyclotomicField ℓ ℚ) ℓ := by
    rw [hzu.unit_spec]; exact hz
  have hζ1 : hzu.unit ^ ℓ = 1 := by
    refine Units.ext ?_
    rw [Units.val_pow_eq_pow_val, hζ.pow_eq_one, Units.val_one]
  obtain ⟨c, hc⟩ := PhiGen.exists_phiGenDescends ℓ hzu.unit hζ
  have hint : ∀ k, PhiGen.IntCoeffs (c k) := fun k => hc.intCoeffs hζ1 k
  have hmem : ∀ k, c k ∈ Algebra.adjoin ℚ {jq} :=
    fun k => PhiGen.mem_adjoin_jq_of_phiGenDescends ℓ hzu.unit hζ c hc k
  obtain ⟨data, hcoeff⟩ := PhiGen.exists_modularPolynomialData_coeff_eq hc hint hmem
  exact ⟨data,
    PhiGen.phiIrreducible_of_splits ℓ hzu.unit hζ data (PhiGen.splits_of_coeff_evalAtJ_eq hzu.unit hc data hcoeff),
    PhiGen.evalSymm_of_coeff_evalAtJ_eq hζ hc data hcoeff⟩

end ModularCurve

end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_exists_phiIrreducible_evalSymm.ModularCurve ModularCurve.PhiGen in

theorem solution (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] : ∃ data : ModularPolynomialData ℓ, PhiIrreducible data ∧ EvalSymm data.Φ :=
  ModularCurve.exists_phiIrreducible_evalSymm ℓ

end S_ModularCurve_exists_phiIrreducible_evalSymm
end P2MW
export P2MW.S_ModularCurve_exists_phiIrreducible_evalSymm (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open ModularCurve ModularCurve.PhiGen
theorem ModularCurve.exists_phiIrreducible_evalSymm (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] : ∃ data : ModularPolynomialData ℓ, PhiIrreducible data ∧ EvalSymm data.Φ := _root_.P2MW.S_ModularCurve_exists_phiIrreducible_evalSymm.solution ℓ

end publicSection
