/-
Based on Prove2Me node ModularCurve.exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral
(51fe59e7-e662-5bf4-ab8e-93e14458f18f) by Claude (2026-09-05).

Proof based on Prove2Me submission f224858c-cd3c-5edb-b878-ea5eca81ae56
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.QExpansion
public import Definitions.FLT.Def_ModularCurve_LaurentCoeff
public import Definitions.FLT.Def_ModularCurve_QExpansionDiff
public import Definitions.FLT.Def_ModularCurve_X0

import Theorems.FLT.Thm_ModularCurve_analyticOrderAt_le_of_isIntegral_adjoin_coeffEmb_jq
import Theorems.FLT.Thm_ModularCurve_eventually_norm_slash_le_of_isIntegral_adjoin_coeffEmb_jq_inv
import Theorems.FLT.Thm_ModularCurve_exists_modularForm_mul_qExpansion_eq_of_mem_laurentBaseChange
import Theorems.FLT.Thm_ModularCurve_thetaL_coeffMap_eq_coeffMap_single_mul_derivative
import Theorems.FLT.Thm_ModularForm_exists_cuspForm_mul_eq_of_analyticOrderAt_le
import Theorems.FLT.Thm_ModularForm_exists_gamma0_qExpansion_eq_of_levelOne
import Theorems.FLT.Thm_omegaRow_T2
import Definitions.FLT.Def_P2M_Util

/-!
# Integrality criterion making X θ j a weight-two cusp form

Theorem statement: `ModularCurve.exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral`
(`51fe59e7-e662-5bf4-ab8e-93e14458f18f`), by Claude, 2026-09-05.

Proof: submission `f224858c-cd3c-5edb-b878-ea5eca81ae56`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a nonzero natural number and let $J :=$ `coeffEmb ℂ jq` denote the image in $\mathbb
C((q))$, under the coefficientwise ring map induced by $\mathbb Q \to \mathbb C$, of the Laurent
series `jq` $= q^{-1}\cdot$ (the rational power series `jNumQ`), i.e. the $q$-expansion of the
modular invariant $j$. Let $X \in \mathbb C((q))$ be an element of `laurentBaseChange ℂ
(modularFunctionFieldFull N)`, the intermediate field of $\mathbb C((q))$ obtained by adjoining to
$\mathbb C$ the coefficientwise images of the subfield of $\mathbb Q((q))$ generated over $\mathbb
Q$ by the series $q$-rescalings `qExpand ℚ d jq` for the nonzero divisors $d$ of $N$. Let $M$ be a
natural number, and assume two integrality hypotheses: first, $X^{6} J^{4}(J - 1728)^{3}$ is
integral over the $\mathbb C$-subalgebra of $\mathbb C((q))$ generated by $J$; second, $X^{2M}
J^{M+1}(J-1728)^{M}$ is integral over the $\mathbb C$-subalgebra generated by $J^{-1}$. Then there
exists a cusp form $f$ of weight $2$ for $\Gamma_0(N)$ whose $q$-expansion of period $1$, viewed as
an element of $\mathbb C((q))$, equals $X \cdot \theta J$, where $\theta$ is the $\mathbb C$-linear
operator `thetaL` sending a Laurent series to $q$ times its formal derivative.

This is the analytic core of the implication that a regular differential on $X_0(N)$ gives a
weight-two cusp form, stated purely in terms of $q$-expansions: the two integrality conditions
encode regularity at the finite points and at the cusps, with no place, valuation or differential
appearing. It is used in the passage from elements of the space of regular differentials, presented
by their $q$-expansions, to cusp forms in $S_2(\Gamma_0(N))$.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral
p2m_attr_erase "simp" "ModularCurve.jqNModC_one"

open ModularCurve UpperHalfPlane HahnSeries
open scoped MatrixGroups ModularForm

namespace ANGlue

theorem one_mem_strictPeriods_gamma0 (N : ℕ) :
    (1 : ℝ) ∈ (Subgroup.map (Matrix.SpecialLinearGroup.mapGL ℝ) (CongruenceSubgroup.Gamma0 N)).strictPeriods := by
  rw [CongruenceSubgroup.strictPeriods_Gamma0]
  exact AddSubgroup.mem_zmultiples 1

theorem thetaL_coeffEmb_jq :
    thetaL ℂ (coeffEmb ℂ jq) = coeffMap (algebraMap ℚ ℂ) (thetaL ℚ jq) := by
  rw [coeffEmb, ModularCurve.thetaL_coeffMap_eq_coeffMap_single_mul_derivative]
  rfl

end ANGlue

open ANGlue in
theorem solution (N : ℕ) [NeZero N]
    (X : LaurentSeries ℂ)
    (hX : X ∈ ModularCurve.laurentBaseChange ℂ (ModularCurve.modularFunctionFieldFull N)) (M : ℕ)
    (h₁ : IsIntegral (Algebra.adjoin ℂ ({ModularCurve.coeffEmb ℂ ModularCurve.jq} : Set (LaurentSeries ℂ)))
      (X ^ 6 * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ 4 *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ 3))
    (h₂ : IsIntegral (Algebra.adjoin ℂ ({(ModularCurve.coeffEmb ℂ ModularCurve.jq)⁻¹} : Set (LaurentSeries ℂ)))
      (X ^ (2 * M) * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ (M + 1) *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ M)) :
    ∃ f : CuspForm (CongruenceSubgroup.Gamma0 N) 2,
      HahnSeries.ofPowerSeries ℤ ℂ (UpperHalfPlane.qExpansion 1 f) =
        X * ModularCurve.thetaL ℂ (ModularCurve.coeffEmb ℂ ModularCurve.jq) := by
  classical
  obtain ⟨k, g, h, hh, hXh⟩ :=
    ModularCurve.exists_modularForm_mul_qExpansion_eq_of_mem_laurentBaseChange N X hX
  obtain ⟨E4N, hE4⟩ := ModularForm.exists_gamma0_qExpansion_eq_of_levelOne N ModularForm.E₄
  obtain ⟨E6N, hE6⟩ := ModularForm.exists_gamma0_qExpansion_eq_of_levelOne N ModularForm.E₆
  obtain ⟨DN, hD⟩ := ModularForm.exists_gamma0_qExpansion_eq_of_levelOne N
    (ModularFormClass.modularForm (CuspForm.discriminant))
  have hDcoe : (DN : ℍ → ℂ) = ModularForm.discriminant := by
    rw [hD]
    funext z
    rw [← CuspForm.toModularFormₗ_eq_coe, CuspForm.toModularFormₗ_apply]
    rfl
  obtain ⟨Φ, hΦdef⟩ : ∃ Φ : ModularForm (CongruenceSubgroup.Gamma0 N) (k + (4 + 4) + 6),
      Φ = (g.mul (E4N.mul E4N)).mul E6N := ⟨_, rfl⟩
  obtain ⟨Ψ, hΨdef⟩ : ∃ Ψ : ModularForm (CongruenceSubgroup.Gamma0 N) (k + 12), Ψ = h.mul DN := ⟨_, rfl⟩
  have hΦcoe : (Φ : ℍ → ℂ) = fun z => g z * ModularForm.E₄ z ^ 2 * ModularForm.E₆ z := by
    funext z
    simp only [hΦdef, ModularForm.coe_mul, Pi.mul_apply, hE4, hE6]
    ring
  have hΨcoe : (Ψ : ℍ → ℂ) = fun z => h z * ModularForm.discriminant z := by
    funext z
    simp only [hΨdef, ModularForm.coe_mul, Pi.mul_apply, hDcoe]
  have hΨ0 : Ψ ≠ 0 := by
    intro h0
    apply hh
    have hfun : (Ψ : ℍ → ℂ) = 0 := by rw [h0]; rfl
    rw [hΨcoe] at hfun
    rw [← FunLike.coe_zero_iff]
    funext z
    have := congr_fun hfun z
    simp only [Pi.zero_apply, mul_eq_zero] at this
    rcases this with hz | hz
    · exact hz
    · exact absurd hz (ModularForm.discriminant_ne_zero z)
  have hord : ∀ τ : ℍ, analyticOrderAt ((Ψ : ℍ → ℂ) ∘ ofComplex) (τ : ℂ) ≤
      analyticOrderAt ((Φ : ℍ → ℂ) ∘ ofComplex) (τ : ℂ) := by
    intro τ
    rw [hΦcoe, hΨcoe]
    exact ModularCurve.analyticOrderAt_le_of_isIntegral_adjoin_coeffEmb_jq N g h X hXh h₁ τ
  have hcusp : ∀ (A : SL(2, ℤ)) (ε : ℝ), 0 < ε → ∀ᶠ τ : ℍ in atImInfty,
      ‖((Φ : ℍ → ℂ) ∣[k + (4 + 4) + 6] (A : GL (Fin 2) ℝ)) τ‖ ≤ ε * ‖((Ψ : ℍ → ℂ) ∣[k + 12] (A : GL (Fin 2) ℝ)) τ‖ := by
    intro A ε hε
    rw [hΦcoe, hΨcoe, show k + (4 + 4) + 6 = k + 14 by ring]
    exact ModularCurve.eventually_norm_slash_le_of_isIntegral_adjoin_coeffEmb_jq_inv N g h X hXh M h₂ A ε hε
  obtain ⟨f, hf⟩ := ModularForm.exists_cuspForm_mul_eq_of_analyticOrderAt_le N 2 (by ring) Φ Ψ hΨ0 hord hcusp
  refine ⟨-f, ?_⟩
  have h1 := one_mem_strictPeriods_gamma0 N
  have hfΨ : ((ModularFormClass.modularForm f).mul Ψ : ℍ → ℂ) = (Φ : ℍ → ℂ) := by
    funext z
    rw [ModularForm.coe_mul, Pi.mul_apply, ← CuspForm.toModularFormₗ_eq_coe, CuspForm.toModularFormₗ_apply]
    exact hf z
  have hcoef : ((ModularFormClass.modularForm f : ModularForm (CongruenceSubgroup.Gamma0 N) 2) : ℍ → ℂ) = (f : ℍ → ℂ) := by
    rw [← CuspForm.toModularFormₗ_eq_coe]
    funext z
    exact CuspForm.toModularFormₗ_apply f z
  have hq : qExpansion 1 (f : ℍ → ℂ) * qExpansion 1 (Ψ : ℍ → ℂ) = qExpansion 1 (Φ : ℍ → ℂ) := by
    have e := ModularForm.qExpansion_mul one_pos h1 (ModularFormClass.modularForm f) Ψ
    rw [hfΨ, hcoef] at e
    exact e.symm
  have hqΨ : qExpansion 1 (Ψ : ℍ → ℂ) = qExpansion 1 (h : ℍ → ℂ) * qExpansion 1 ModularForm.discriminant := by
    rw [hΨdef, ModularForm.qExpansion_mul one_pos h1, hDcoe]
  have hqΦ : qExpansion 1 (Φ : ℍ → ℂ) =
      qExpansion 1 (g : ℍ → ℂ) * (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) * qExpansion 1 (ModularForm.E₄ : ℍ → ℂ)) *
        qExpansion 1 (ModularForm.E₆ : ℍ → ℂ) := by
    rw [hΦdef, ModularForm.qExpansion_mul one_pos h1, ModularForm.qExpansion_mul one_pos h1,
      ModularForm.qExpansion_mul one_pos h1, hE4, hE6]
  have hT2 : thetaL ℂ (coeffEmb ℂ jq) * ((qExpansion 1 ModularForm.discriminant : PowerSeries ℂ) : LaurentSeries ℂ) =
      -((((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) ^ 2 *
        ((qExpansion 1 (ModularForm.E₆ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) := by
    rw [thetaL_coeffEmb_jq]
    exact omegaRow_T2
  have eq1 : ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) *
      ((qExpansion 1 (Ψ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
      ((qExpansion 1 (Φ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) := by
    rw [← PowerSeries.coe_mul, hq]
  have eq2 : ((qExpansion 1 (Ψ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
      ((qExpansion 1 (h : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) *
        ((qExpansion 1 ModularForm.discriminant : PowerSeries ℂ) : LaurentSeries ℂ) := by
    rw [hqΨ, PowerSeries.coe_mul]
  have eq3 : ((qExpansion 1 (Φ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
      ((qExpansion 1 (g : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) *
        (((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) *
          ((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) *
        ((qExpansion 1 (ModularForm.E₆ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) := by
    rw [hqΦ, PowerSeries.coe_mul, PowerSeries.coe_mul, PowerSeries.coe_mul]
  have hhq : ((qExpansion 1 (h : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ≠ 0 := by
    intro h0
    apply hh
    have h0' : qExpansion 1 (h : ℍ → ℂ) = 0 :=
      HahnSeries.ofPowerSeries_injective (by rw [h0, map_zero])
    exact (ModularForm.qExpansion_eq_zero_iff one_pos h1 h).mp h0'
  have hDN0 : DN ≠ 0 := by
    intro h0
    have hI : (DN : ℍ → ℂ) UpperHalfPlane.I = 0 := by rw [h0]; rfl
    rw [hDcoe] at hI
    exact ModularForm.discriminant_ne_zero _ hI
  have hDq : ((qExpansion 1 ModularForm.discriminant : PowerSeries ℂ) : LaurentSeries ℂ) ≠ 0 := by
    intro h0
    apply hDN0
    have h0' : qExpansion 1 (DN : ℍ → ℂ) = 0 :=
      HahnSeries.ofPowerSeries_injective (by rw [hDcoe, h0, map_zero])
    exact (ModularForm.qExpansion_eq_zero_iff one_pos h1 DN).mp h0'
  have key : (((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) + X * thetaL ℂ (coeffEmb ℂ jq)) *
      (((qExpansion 1 (h : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) *
        ((qExpansion 1 ModularForm.discriminant : PowerSeries ℂ) : LaurentSeries ℂ)) = 0 := by
    linear_combination eq1 + eq3 - ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) * eq2 +
      X * ((qExpansion 1 (h : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) * hT2 -
      ((((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) ^ 2 *
        ((qExpansion 1 (ModularForm.E₆ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) * hXh
  have hsum : ((qExpansion 1 (f : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) + X * thetaL ℂ (coeffEmb ℂ jq) = 0 := by
    rcases mul_eq_zero.mp key with h0 | h0
    · exact h0
    · exact absurd h0 (mul_ne_zero hhq hDq)
  have hneg : qExpansion 1 ((-f : CuspForm (CongruenceSubgroup.Gamma0 N) 2) : ℍ → ℂ) = -qExpansion 1 (f : ℍ → ℂ) := by
    rw [FunLike.coe_neg]
    exact ModularForm.qExpansion_neg one_pos h1 f
  show ((qExpansion 1 ((-f : CuspForm (CongruenceSubgroup.Gamma0 N) 2) : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) = _
  rw [hneg, PowerSeries.coe_neg, eq_neg_of_add_eq_zero_left hsum, neg_neg]

end S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral
end P2MW
export P2MW.S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral (N : ℕ) [NeZero N]
    (X : LaurentSeries ℂ)
    (hX : X ∈ ModularCurve.laurentBaseChange ℂ (ModularCurve.modularFunctionFieldFull N)) (M : ℕ)
    (h₁ : IsIntegral (Algebra.adjoin ℂ ({ModularCurve.coeffEmb ℂ ModularCurve.jq} : Set (LaurentSeries ℂ)))
      (X ^ 6 * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ 4 *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ 3))
    (h₂ : IsIntegral (Algebra.adjoin ℂ ({(ModularCurve.coeffEmb ℂ ModularCurve.jq)⁻¹} : Set (LaurentSeries ℂ)))
      (X ^ (2 * M) * ModularCurve.coeffEmb ℂ ModularCurve.jq ^ (M + 1) *
        (ModularCurve.coeffEmb ℂ ModularCurve.jq - algebraMap ℂ (LaurentSeries ℂ) 1728) ^ M)) :
    ∃ f : CuspForm (CongruenceSubgroup.Gamma0 N) 2,
      HahnSeries.ofPowerSeries ℤ ℂ (UpperHalfPlane.qExpansion 1 f) =
        X * ModularCurve.thetaL ℂ (ModularCurve.coeffEmb ℂ ModularCurve.jq) := _root_.P2MW.S_ModularCurve_exists_cuspForm_qExpansion_eq_mul_thetaL_of_isIntegral.solution N X hX M h₁ h₂

end publicSection
