/-
Based on Prove2Me node ModularCurve.deg_eq_one_modularFunctionFieldBar
(462b7d63-c2fe-5723-b46e-ce8ae3eba2df) by Claude (2026-09-05).

Proof based on Prove2Me submission 914c2faf-9973-5702-8ae3-82356f87970e
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ArithmeticGalois
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_ModularCurve_QAdicPlace
import Definitions.FLT.Def_AlgebraicCurve_DivisorPushPull
import Definitions.FLT.Def_AlgebraicCurve_IsCurveOver
import Theorems.FLT.Thm_ModularCurve_relfinrank_laurentBaseChange_modularFunctionFieldFull
import Theorems.FLT.Thm_ModularCurve_relfinrank_full_eq_dedekindPsi
import Theorems.FLT.Thm_ModularCurve_dedekindPsi_pos
import Theorems.FLT.Thm_AlgebraicCurve_isAlgebraic_adjoin_of_transcendental
import Mathlib.FieldTheory.Relrank
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.FieldTheory.Minpoly.Basic
import Mathlib.RingTheory.Algebraic.Integral
import Definitions.FLT.Def_P2M_Util

/-!
# All places of ℚ̄· F_M have degree one

Theorem statement: `ModularCurve.deg_eq_one_modularFunctionFieldBar`
(`462b7d63-c2fe-5723-b46e-ce8ae3eba2df`), by Claude, 2026-09-05.

Proof: submission `914c2faf-9973-5702-8ae3-82356f87970e`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $M$ be a positive integer. Write $F_M$ for `modularFunctionFieldFull M`, the subfield of the
Laurent series field $\mathbb Q((X))$ generated over $\mathbb Q$ by the set `divisorExpansions M`,
and let `modularFunctionFieldBar M` be its base change `laurentBaseChange`, namely the intermediate
field of $\overline{\mathbb Q}((X))$ over $\overline{\mathbb Q}$ generated by the image of $F_M$
under the coefficientwise embedding $\mathbb Q((X)) \to \overline{\mathbb Q}((X))$. The assertion is
that every place $w$ of `modularFunctionFieldBar M` over $\overline{\mathbb Q}$ has degree one. Here
a place consists of a valuation subring of the field `modularFunctionFieldBar M` which contains the
image of $\overline{\mathbb Q}$, is not the whole field, and is a principal ideal ring; its degree
is the $\overline{\mathbb Q}$-dimension of the residue field of that local ring. Thus the conclusion
says that the residue field at every such place is $\overline{\mathbb Q}$ itself, i.e. all places of
the base-changed modular function field are rational over the constant field.

This is the standard fact that over an algebraically closed constant field every place of a function
field has residue degree one, here for the function field of the modular curve of level $M$ after
base change to $\overline{\mathbb Q}$. It supplies the degree-one hypothesis used throughout the
divisor-level Eichler–Shimura bookkeeping and the comparison of places of the characteristic-zero
model with those of its reductions.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_deg_eq_one_modularFunctionFieldBar.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_deg_eq_one_modularFunctionFieldBar
p2m_attr_erase "instance" "ModularCurve.instIsDomainTensorProduct AlgebraicClosure.Rat.isGalois AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.coe_baseChangeEquiv_apply ModularCurve.baseChangeHom_tmul ModularCurve.jqNModC_one ModularCurve.coe_cuspidalDivisor₀ AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X"
p2m_attr_erase "simp" "ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ"

noncomputable section

p2m_open "AlgebraicCurve ModularCurve P2MW.S_ModularCurve_deg_eq_one_modularFunctionFieldBar.ModularCurve Polynomial"

namespace B2Deg

theorem valuation_aeval_eq_one {K F : Type*} [Field K] [Field F] [Algebra K F] [IsAlgClosed K]
    (w : Place K F) (y : F)
    (hy : ∀ c : K, w.toValuationSubring.valuation (y - algebraMap K F c) = 1)
    (p : K[X]) (hp : p ≠ 0) :
    w.toValuationSubring.valuation (aeval y p) = 1 := by
  have hconst : ∀ a : K, a ≠ 0 → w.toValuationSubring.valuation (algebraMap K F a) = 1 := by
    intro a ha
    have hu := (IsUnit.mk0 a ha).map (algebraMap K w.toValuationSubring)
    have h1 := (w.toValuationSubring.valuation_eq_one_iff _).mp hu
    rwa [Place.coe_algebraMap] at h1
  have hsplit := IsAlgClosed.splits p
  have hp' : aeval y p = aeval y (C p.leadingCoeff * (p.roots.map (X - C ·)).prod) := by
    rw [← hsplit.eq_prod_roots]
  rw [hp']
  simp only [map_mul, map_multiset_prod, Multiset.map_map]
  rw [aeval_C, hconst _ (leadingCoeff_ne_zero.mpr hp), one_mul]
  refine Multiset.prod_eq_one fun x hx => ?_
  obtain ⟨c, -, rfl⟩ := Multiset.mem_map.mp hx
  simpa using hy c

theorem surjective_algebraMap_residueField {K F : Type*} [Field K] [Field F] [Algebra K F]
    [IsAlgClosed K] (t : F)
    [Algebra.IsAlgebraic (IntermediateField.adjoin K ({t} : Set F)) F] (w : Place K F) :
    Function.Surjective (algebraMap K w.ResidueField) := by
  intro yb
  obtain ⟨y, rfl⟩ := IsLocalRing.residue_surjective yb
  suffices h : ∃ c : K, y - algebraMap K w.toValuationSubring c ∈
      IsLocalRing.maximalIdeal w.toValuationSubring by
    obtain ⟨c, hc⟩ := h
    refine ⟨c, ?_⟩
    show IsLocalRing.residue _ (algebraMap K w.toValuationSubring c) = IsLocalRing.residue _ y
    rw [eq_comm, ← sub_eq_zero, ← map_sub, IsLocalRing.residue_eq_zero_iff]
    exact hc
  by_cases halg : IsAlgebraic K (y : F)
  · have hdeg := IsAlgClosed.degree_eq_one_of_irreducible K (minpoly.irreducible halg.isIntegral)
    obtain ⟨c, hc⟩ := minpoly.mem_range_of_degree_eq_one K (y : F) hdeg
    refine ⟨c, ?_⟩
    have h0 : y - algebraMap K w.toValuationSubring c = 0 := Subtype.ext (by simp [← hc])
    rw [h0]
    exact zero_mem _
  · have ht : Transcendental K (y : F) := halg
    have := AlgebraicCurve.isAlgebraic_adjoin_of_transcendental t ht
    by_contra hcon
    simp only [not_exists] at hcon
    have hunit : ∀ c : K, w.toValuationSubring.valuation ((y : F) - algebraMap K F c) = 1 := by
      intro c
      have hle := w.toValuationSubring.valuation_le_one (y - algebraMap K w.toValuationSubring c)
      have hnlt : ¬ w.toValuationSubring.valuation
          ((y - algebraMap K w.toValuationSubring c : w.toValuationSubring) : F) < 1 :=
        fun hlt => hcon c ((w.toValuationSubring.valuation_lt_one_iff _).mpr hlt)
      have heq := hle.eq_of_not_lt hnlt
      simpa using heq
    have hadj : ∀ z : F, z ∈ IntermediateField.adjoin K ({(y : F)} : Set F) →
        z ∈ w.toValuationSubring := by
      intro z hz
      rw [IntermediateField.mem_adjoin_simple_iff] at hz
      obtain ⟨r, s, rfl⟩ := hz
      rw [← w.toValuationSubring.valuation_le_one_iff, map_div₀]
      by_cases hr : r = 0
      · simp [hr]
      by_cases hs : s = 0
      · simp [hs]
      simp only [valuation_aeval_eq_one w y hunit r hr, valuation_aeval_eq_one w y hunit s hs, div_one,
        le_refl]
    apply (w.restrict (IntermediateField.adjoin K ({(y : F)} : Set F))).ne_top'
    refine SetLike.ext fun z => ⟨fun _ => ValuationSubring.mem_top z, fun _ => ?_⟩
    rw [Place.mem_restrict_iff, IntermediateField.algebraMap_apply]
    exact hadj z z.2

theorem deg_eq_one_of_isAlgebraic_adjoin {K F : Type*} [Field K] [Field F] [Algebra K F]
    [IsAlgClosed K] (t : F)
    [Algebra.IsAlgebraic (IntermediateField.adjoin K ({t} : Set F)) F] (w : Place K F) :
    w.deg = 1 := by
  have : Module.Finite K w.ResidueField :=
    Module.Finite.of_surjective (Algebra.linearMap K w.ResidueField)
      (surjective_algebraMap_residueField t w)
  exact w.deg_eq_one_of_isAlgClosed_of_finite

theorem finiteDimensional_adjoin_jBar (M : ℕ) [NeZero M] :
    FiniteDimensional
      (IntermediateField.adjoin (AlgebraicClosure ℚ)
        ({(⟨coeffEmb (AlgebraicClosure ℚ) jq,
            coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jq_mem_full M)⟩ :
            modularFunctionFieldBar M)} : Set (modularFunctionFieldBar M)))
      (modularFunctionFieldBar M) := by
  set j : modularFunctionFieldBar M := ⟨coeffEmb (AlgebraicClosure ℚ) jq,
    coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jq_mem_full M)⟩ with hj
  have hcm : IntermediateField.comap (modularFunctionFieldBar M).val
        (IntermediateField.adjoin (AlgebraicClosure ℚ)
          ({(j : LaurentSeries (AlgebraicClosure ℚ))} :
            Set (LaurentSeries (AlgebraicClosure ℚ))))
      = IntermediateField.adjoin (AlgebraicClosure ℚ) ({j} : Set (modularFunctionFieldBar M)) := by
    rw [← IntermediateField.lift_adjoin_simple]
    exact IntermediateField.comap_map (modularFunctionFieldBar M).val _
  have h1 := IntermediateField.finrank_comap
    (IntermediateField.adjoin (AlgebraicClosure ℚ)
      ({(j : LaurentSeries (AlgebraicClosure ℚ))} : Set (LaurentSeries (AlgebraicClosure ℚ))))
    (modularFunctionFieldBar M).val
  rw [hcm, IntermediateField.fieldRange_val] at h1
  have h2 : IntermediateField.relfinrank
      (IntermediateField.adjoin (AlgebraicClosure ℚ)
        ({(j : LaurentSeries (AlgebraicClosure ℚ))} : Set (LaurentSeries (AlgebraicClosure ℚ))))
      (modularFunctionFieldBar M) = dedekindPsi M := by
    rw [← ModularCurve.relfinrank_full_eq_dedekindPsi M,
      ← ModularCurve.relfinrank_laurentBaseChange_modularFunctionFieldFull (AlgebraicClosure ℚ) M]
  have hpos : 0 < IntermediateField.relfinrank
      (IntermediateField.adjoin (AlgebraicClosure ℚ)
        ({(j : LaurentSeries (AlgebraicClosure ℚ))} : Set (LaurentSeries (AlgebraicClosure ℚ))))
      (modularFunctionFieldBar M) := by
    rw [h2]
    exact ModularCurve.dedekindPsi_pos M (NeZero.ne M)
  rw [← h1] at hpos
  exact Module.finite_of_finrank_pos hpos

end B2Deg

namespace ModularCurve
p2m_export "ModularCurve" "modularFunctionFieldBar jq dedekindPsi coeffEmb laurentBaseChange coeffEmb_mem_laurentBaseChange jq_mem_full relfinrank_laurentBaseChange_modularFunctionFieldFull relfinrank_full_eq_dedekindPsi dedekindPsi_pos"
end ModularCurve
p2m_open_scoped "ModularCurve" in

private theorem ModularCurve.deg_eq_one_modularFunctionFieldBar (M : ℕ) [NeZero M]
    (w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar M)) : w.deg = 1 := by
  have := B2Deg.finiteDimensional_adjoin_jBar M
  exact B2Deg.deg_eq_one_of_isAlgebraic_adjoin
    (⟨coeffEmb (AlgebraicClosure ℚ) jq,
      coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jq_mem_full M)⟩ :
      modularFunctionFieldBar M) w

end

open AlgebraicCurve _root_.ModularCurve _root_.P2MW.S_ModularCurve_deg_eq_one_modularFunctionFieldBar.ModularCurve in

theorem solution (M : ℕ) [NeZero M] (w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar M)) : w.deg = 1 :=
  ModularCurve.deg_eq_one_modularFunctionFieldBar M w

end S_ModularCurve_deg_eq_one_modularFunctionFieldBar
end P2MW
export P2MW.S_ModularCurve_deg_eq_one_modularFunctionFieldBar (solution)

end privateSection

public section publicSection


open AlgebraicCurve ModularCurve
theorem ModularCurve.deg_eq_one_modularFunctionFieldBar (M : ℕ) [NeZero M] (w : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar M)) : w.deg = 1 := _root_.P2MW.S_ModularCurve_deg_eq_one_modularFunctionFieldBar.solution M w

end publicSection
