/-
Based on Prove2Me node ModularCurve.ratPoint_eq_ratPoint_iff_of_isCoprime
(6ea43388-53a5-59b1-918f-b834013d43a5) by Claude (2026-09-05).

Proof based on Prove2Me submission 31dfc0f7-ac9a-56d4-a45d-943788ca886f
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_CuspSpace

import Definitions.FLT.Def_P2M_Util

/-!
# Coprime integral coordinates on P¹(ℚ) are unique up to sign

Theorem statement: `ModularCurve.ratPoint_eq_ratPoint_iff_of_isCoprime`
(`6ea43388-53a5-59b1-918f-b834013d43a5`), by Claude, 2026-09-05.

Proof: submission `31dfc0f7-ac9a-56d4-a45d-943788ca886f`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

For integers $a, c, a', c'$ the map [`ModularCurve.ratPoint`](def/ModularCurve_CuspSpace.html#L11)
sends a pair $(a,c)$ to the point of the one-point compactification `OnePoint ℚ` given by $\infty$
if $c = 0$ and by the image of the rational number $a/c$ otherwise. The theorem assumes that $a$ and
$c$ are coprime in $\mathbb{Z}$ (in the Bézout sense of `IsCoprime`, i.e. there exist $x, y$ with
$xa + yc = 1$) and likewise that $a'$ and $c'$ are coprime, and asserts the equivalence:
[`ModularCurve.ratPoint a c`](def/ModularCurve_CuspSpace.html#L11) equals [`ModularCurve.ratPoint a'
c'`](def/ModularCurve_CuspSpace.html#L11) if and only if either $a = a'$ and $c = c'$, or $a = -a'$
and $c = -c'$. Thus a point of $\mathbb{P}^1(\mathbb{Q})$, presented in this chart form, determines
its coprime integral homogeneous coordinates up to a single global sign.

This is the standard uniqueness of normalised homogeneous coordinates for points of
$\mathbb{P}^1(\mathbb{Q})$, the elementary input for putting cusps of $\Gamma_0(N)$ into a normal
form. It is used by
[`ModularCurve.CuspSpace.normalFormCriterion`](thm.html#ModularCurve.CuspSpace.normalFormCriterion)
in the treatment of the cusps of the modular curve.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_ratPoint_eq_ratPoint_iff_of_isCoprime.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_ratPoint_eq_ratPoint_iff_of_isCoprime

open Matrix Matrix.SpecialLinearGroup OnePoint CongruenceSubgroup
open scoped MatrixGroups
open ModularCurve ModularCurve.CuspSpace

theorem solution {a c a' c' : ℤ} (h : IsCoprime a c)
    (h' : IsCoprime a' c') :
    ModularCurve.ratPoint a c = ModularCurve.ratPoint a' c' ↔ (a = a' ∧ c = c') ∨ (a = -a' ∧ c = -c') := by
  constructor
  · intro heq
    rcases eq_or_ne c 0 with rfl | hc
    · have hc' : c' = 0 := by
        rw [ratPoint_zero_right] at heq
        exact ratPoint_eq_infty_iff.mp heq.symm
      subst hc'
      have hu : IsUnit a := isCoprime_zero_right.mp h
      have hu' : IsUnit a' := isCoprime_zero_right.mp h'
      rcases Int.isUnit_iff.mp hu with rfl | rfl <;>
          rcases Int.isUnit_iff.mp hu' with rfl | rfl <;>
        norm_num
    · have hc' : c' ≠ 0 := by
        intro h0
        rw [h0, ratPoint_zero_right, ratPoint_eq_infty_iff] at heq
        exact hc heq
      have hcQ : (c : ℚ) ≠ 0 := Int.cast_ne_zero.mpr hc
      have hcQ' : (c' : ℚ) ≠ 0 := Int.cast_ne_zero.mpr hc'
      rw [ratPoint_of_ne_zero _ hc, ratPoint_of_ne_zero _ hc', OnePoint.coe_eq_coe,
        div_eq_div_iff hcQ hcQ'] at heq
      have hZ : a * c' = a' * c := by exact_mod_cast heq
      have h1 : c ∣ c' := h.symm.dvd_of_dvd_mul_left ⟨a', by linear_combination hZ⟩
      have h2 : c' ∣ c := h'.symm.dvd_of_dvd_mul_left ⟨a, by linear_combination - hZ⟩
      obtain ⟨u, hu⟩ := h1
      obtain ⟨v, hv⟩ := h2
      have huv : u * v = 1 := by
        have h3 : c * (u * v) = c * 1 := by
          rw [mul_one, ← mul_assoc, ← hu, ← hv]
        exact mul_left_cancel₀ hc h3
      rcases Int.isUnit_iff.mp (IsUnit.of_mul_eq_one v huv) with hu1 | hu1
      · rw [hu1, mul_one] at hu
        rw [hu] at hZ
        exact Or.inl ⟨mul_right_cancel₀ hc hZ, hu.symm⟩
      · rw [hu1, mul_neg_one] at hu
        have hc2 : c = -c' := by rw [hu]; ring
        have h4 : a * c' = -a' * c' := by
          rw [hc2] at hZ
          linear_combination hZ
        exact Or.inr ⟨mul_right_cancel₀ hc' h4, hc2⟩
  · rintro (⟨rfl, rfl⟩ | ⟨rfl, rfl⟩)
    · rfl
    · exact ratPoint_neg_neg a' c'

namespace CuspSpace

end CuspSpace
end S_ModularCurve_ratPoint_eq_ratPoint_iff_of_isCoprime
end P2MW
export P2MW.S_ModularCurve_ratPoint_eq_ratPoint_iff_of_isCoprime (solution)

end privateSection

public section publicSection


open OnePoint
theorem ModularCurve.ratPoint_eq_ratPoint_iff_of_isCoprime {a c a' c' : ℤ} (h : IsCoprime a c)
    (h' : IsCoprime a' c') :
    ModularCurve.ratPoint a c = ModularCurve.ratPoint a' c' ↔ (a = a' ∧ c = c') ∨ (a = -a' ∧ c = -c') := _root_.P2MW.S_ModularCurve_ratPoint_eq_ratPoint_iff_of_isCoprime.solution h h'

end publicSection
