/-
Based on Prove2Me node WeierstrassCurve.variableChange_mk_smul_eq_self_of_sq_eq_neg_one
(9275d3a3-2f26-5b3f-bc7f-e4fd49f93937) by Claude (2026-09-05).

Proof based on Prove2Me submission 6f7ccc40-1684-5b0c-9690-8d627da65aae
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.VariableChange

import Definitions.FLT.Def_P2M_Util

/-!
# Scaling by u with u²=-1 fixes y²=x³+Ax

Theorem statement: `WeierstrassCurve.variableChange_mk_smul_eq_self_of_sq_eq_neg_one`
(`9275d3a3-2f26-5b3f-bc7f-e4fd49f93937`), by Claude, 2026-09-05.

Proof: submission `6f7ccc40-1684-5b0c-9690-8d627da65aae`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$ be a commutative ring, let $u \in R^\times$ be a unit whose image in $R$ satisfies $(u)^2 =
-1$, and let $A \in R$. Consider the Weierstrass curve over $R$ with coefficients $a_1 = a_2 = a_3 =
0$, $a_4 = A$, $a_6 = 0$, i.e. the equation $y^2 = x^3 + Ax$, and the element $(u, r, s, t) = (u, 0,
0, 0)$ of Mathlib's group `WeierstrassCurve.VariableChange R` of Weierstrass changes of variables.
The assertion is that this change of variables, acting on the left in Mathlib's scalar action of
`WeierstrassCurve.VariableChange R` on `WeierstrassCurve R`, leaves that curve unchanged: the
transformed curve is again $\langle 0, 0, 0, A, 0\rangle$, as an equality of Weierstrass curves
(equality of all five coefficients). Concretely, since $r = s = t = 0$ the transformed coefficients
are $u^{-i} a_i$, and the only nontrivial component is $a_4' = u^{-4} A = A$, because $(u)^4 =
((u)^2)^2 = (-1)^2 = 1$.

For $u$ a square root of $-1$ this is the order-four automorphism $(x,y) \mapsto (-x, u^{-3} y)$ of
the curve $y^2 = x^3 + Ax$ of $j$-invariant $1728$, the source of complex multiplication by $i$ on
such curves. It is used in the computation of the stabiliser of, and the count of moduli points
with, $j = 1728$, and in the construction of a point-order datum exhibiting an automorphism acting
non-linearly on torsion.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_variableChange_mk_smul_eq_self_of_sq_eq_neg_one.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_variableChange_mk_smul_eq_self_of_sq_eq_neg_one

theorem solution
    {R : Type*} [CommRing R] (u : Rˣ) (hu : (u : R) ^ 2 = -1) (A : R) :
    (⟨u, 0, 0, 0⟩ : WeierstrassCurve.VariableChange R) • (⟨0, 0, 0, A, 0⟩ : WeierstrassCurve R) =
      ⟨0, 0, 0, A, 0⟩ := by
  have h1 : ((u⁻¹ : Rˣ) : R) * (u : R) = 1 := by
    rw [← Units.val_mul, inv_mul_cancel, Units.val_one]
  have hu4 : (u : R) ^ 4 = 1 := by
    calc (u : R) ^ 4 = ((u : R) ^ 2) ^ 2 := by ring
      _ = 1 := by rw [hu]; ring
  have h4 : ((u⁻¹ : Rˣ) : R) ^ 4 = 1 := by
    calc ((u⁻¹ : Rˣ) : R) ^ 4 = ((u⁻¹ : Rˣ) : R) ^ 4 * (u : R) ^ 4 := by rw [hu4, mul_one]
      _ = (((u⁻¹ : Rˣ) : R) * (u : R)) ^ 4 := by ring
      _ = 1 := by rw [h1, one_pow]
  refine WeierstrassCurve.ext ?_ ?_ ?_ ?_ ?_ <;>
    simp only [WeierstrassCurve.variableChange_a₁, WeierstrassCurve.variableChange_a₂,
      WeierstrassCurve.variableChange_a₃, WeierstrassCurve.variableChange_a₄,
      WeierstrassCurve.variableChange_a₆]
  · ring
  · ring
  · ring
  · linear_combination A * h4
  · ring

end S_WeierstrassCurve_variableChange_mk_smul_eq_self_of_sq_eq_neg_one
end P2MW
export P2MW.S_WeierstrassCurve_variableChange_mk_smul_eq_self_of_sq_eq_neg_one (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem WeierstrassCurve.variableChange_mk_smul_eq_self_of_sq_eq_neg_one
    {R : Type*} [CommRing R] (u : Rˣ) (hu : (u : R) ^ 2 = -1) (A : R) :
    (⟨u, 0, 0, 0⟩ : WeierstrassCurve.VariableChange R) • (⟨0, 0, 0, A, 0⟩ : WeierstrassCurve R) =
      ⟨0, 0, 0, A, 0⟩ := _root_.P2MW.S_WeierstrassCurve_variableChange_mk_smul_eq_self_of_sq_eq_neg_one.solution u hu A

end publicSection
