/-
Based on Prove2Me node WeierstrassCurve.finite_torsionBy_of_natCast_ne_zero
(8a534e52-d39c-55e9-af16-ca242f72b778) by Claude (2026-09-05).

Proof based on Prove2Me submission 8f45ac4e-31dc-5db4-ab7d-5079a10e8abb
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point

import Mathlib.Algebra.Order.Star.Basic
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.SimpleRing.Principal
import Theorems.FLT.Thm_WeierstrassCurve_card_torsion_of_isAlgClosed
import Definitions.FLT.Def_P2M_Util

/-!
# Finiteness of n-torsion when n ≠ 0 in k

Theorem statement: `WeierstrassCurve.finite_torsionBy_of_natCast_ne_zero`
(`8a534e52-d39c-55e9-af16-ca242f72b778`), by Claude, 2026-09-05.

Proof: submission `8f45ac4e-31dc-5db4-ab7d-5079a10e8abb`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $k$ be a field and let $W$ be a Weierstrass curve over $k$ which is elliptic (in the sense of
Mathlib's `IsElliptic`: its discriminant is a unit). Let $n$ be a natural number whose image in $k$
is nonzero. Then the $\mathbb{Z}$-submodule $\mathrm{torsionBy}\ \mathbb{Z}\
W.\mathrm{toAffine.Point}\ n$ — that is, the subgroup of those points $P$ of the group $W(k)$ of
$k$-rational points of the associated affine Weierstrass curve (the points of the affine model
together with the point at infinity, with the usual chord–tangent group law) satisfying $n \cdot P =
0$ — is a finite type. Note that the hypothesis $(n : k) \neq 0$ already forces $n \neq 0$, so there
is no separate nondegeneracy assumption; nothing is asserted about the structure of this group, only
its finiteness.

This is the standard finiteness of the $n$-torsion of the group of rational points of an elliptic
curve over a field of residue characteristic not dividing $n$, obtained from the fact that over an
algebraically closed field the $n$-torsion has exactly $n^2$ elements. It serves as the finiteness
guarantee underlying the torsion-subgroup counts used in the modular-curve part of the development,
and is cited by [`ModularCurve.finite_cycSub`](thm.html#ModularCurve.finite_cycSub) and by
[`WeierstrassCurve.Affine.IsogenyEndDatum.exists_dualEndData_dual_mem_and_norm_eq_finrankAlong`](thm.html#WeierstrassCurve.Affine.IsogenyEndDatum.exists_dualEndData_dual_mem_and_norm_eq_finrankAlong).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_finite_torsionBy_of_natCast_ne_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_finite_torsionBy_of_natCast_ne_zero

open WeierstrassCurve WeierstrassCurve.Affine WeierstrassCurve.Affine.Point

theorem solution (k : Type*) [Field k] [DecidableEq k] (W : WeierstrassCurve k) [W.IsElliptic]
    (n : ℕ) (hn : (n : k) ≠ 0) :
    Finite (Submodule.torsionBy ℤ W.toAffine.Point n) := by
  classical
  let K := AlgebraicClosure k
  have hnK : (n : K) ≠ 0 := by
    rw [← map_natCast (algebraMap k K) n]
    exact (map_ne_zero _).mpr hn
  have hn0 : n ≠ 0 := by
    rintro rfl
    exact hn (by simp)
  have hcard : Nat.card (Submodule.torsionBy ℤ (W⁄K).Point n) = n ^ 2 :=
    WeierstrassCurve.card_torsion_of_isAlgClosed (K := K) W hnK
  have : Finite (Submodule.torsionBy ℤ (W⁄K).Point n) :=
    Nat.finite_of_card_ne_zero (by rw [hcard]; exact pow_ne_zero 2 hn0)
  let φ : (W.toAffine⁄k).Point →+ (W.toAffine⁄K).Point := Point.baseChange k K
  have hφ : Function.Injective φ := Point.map_injective _
  have hmem : ∀ P : Submodule.torsionBy ℤ W.toAffine.Point n, φ P.1 ∈ Submodule.torsionBy ℤ (W⁄K).Point n := by
    intro P
    have hP := P.2
    rw [Submodule.mem_torsionBy_iff] at hP ⊢
    show (n : ℤ) • φ P.1 = 0
    rw [← map_zsmul φ]
    exact (congrArg φ hP).trans (map_zero φ)
  refine Finite.of_injective (fun P => (⟨φ P.1, hmem P⟩ : Submodule.torsionBy ℤ (W⁄K).Point n)) ?_
  intro P Q h
  exact Subtype.ext (hφ (congrArg Subtype.val h))

end S_WeierstrassCurve_finite_torsionBy_of_natCast_ne_zero
end P2MW
export P2MW.S_WeierstrassCurve_finite_torsionBy_of_natCast_ne_zero (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem WeierstrassCurve.finite_torsionBy_of_natCast_ne_zero (k : Type*) [Field k] [DecidableEq k] (W : WeierstrassCurve k) [W.IsElliptic]
    (n : ℕ) (hn : (n : k) ≠ 0) :
    Finite (Submodule.torsionBy ℤ W.toAffine.Point n) := _root_.P2MW.S_WeierstrassCurve_finite_torsionBy_of_natCast_ne_zero.solution k W n hn

end publicSection
