/-
Based on Prove2Me node WeierstrassCurve.Affine.FunctionField.adjoin_X_Y_eq_top
(76a7f793-52a9-5d4b-9edd-47ed8f4898fa) by Claude (2026-09-05).

Proof based on Prove2Me submission e2686d34-6332-5d00-a75c-a46b6ff22811
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Defs
public import Mathlib.RingTheory.SimpleRing.Principal

import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Definitions.FLT.Def_P2M_Util

/-!
# The function field of a Weierstrass curve is K(x,y)

Theorem statement: `WeierstrassCurve.Affine.FunctionField.adjoin_X_Y_eq_top`
(`76a7f793-52a9-5d4b-9edd-47ed8f4898fa`), by Claude, 2026-09-05.

Proof: submission `e2686d34-6332-5d00-a75c-a46b6ff22811`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field and let $W$ be a Weierstrass curve over $K$, i.e. a tuple of coefficients
$a_1,a_2,a_3,a_4,a_6$; no nonsingularity hypothesis is imposed. Write $W.\mathrm{toAffine}$ for the
associated affine Weierstrass curve, $W.\mathrm{toAffine.CoordinateRing}$ for its coordinate ring,
the quotient of the bivariate polynomial ring $K[X][Y]$ by the ideal generated by the Weierstrass
polynomial $Y^2+a_1XY+a_3Y-(X^3+a_2X^2+a_4X+a_6)$, with quotient map
`WeierstrassCurve.Affine.CoordinateRing.mk`, and $W.\mathrm{toAffine.FunctionField}$ for the
fraction field of this coordinate ring. Let $\bar x$ and $\bar y$ be the images in the function
field, under the structure map from the coordinate ring, of the classes of `Polynomial.C
Polynomial.X` and of `Polynomial.X`, which are the inner and outer variables $X$ and $Y$ of
$K[X][Y]$ respectively. The assertion is that the intermediate field of
$W.\mathrm{toAffine.FunctionField}/K$ generated by the two-element set $\{\bar x,\bar y\}$, in the
sense of `IntermediateField.adjoin`, is the whole function field: $K(\bar x,\bar y)=\top$.

This is the standard fact $K(W)=K(x,y)$ for a curve given by a Weierstrass equation: the function
field is generated over the base field by the two coordinate functions. It is the tool by which
$K$-algebra maps out of the function field are pinned down by their values on $\bar x$ and $\bar y$,
and it is used in the project in the bound on the degree of the function field over the subfield
pulled back along multiplication-type maps,
[`WeierstrassCurve.Affine.finrank_fieldRange_mulPull_le`](thm.html#WeierstrassCurve.Affine.finrank_fieldRange_mulPull_le).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top

open Polynomial
open scoped Polynomial.Bivariate

namespace WeierstrassCurve
p2m_export "WeierstrassCurve" "Affine map Affine.CoordinateRing mk toAffine Affine.Point Affine.CoordinateRing.mk"
namespace Affine
p2m_export "WeierstrassCurve.Affine" "CoordinateRing map FunctionField Point CoordinateRing.mk"
p2m_open "WeierstrassCurve.Affine WeierstrassCurve"

variable {K : Type*} [Field K] (W : WeierstrassCurve K)

namespace CoordinateRing p2m_export "WeierstrassCurve.Affine.CoordinateRing" "mk map" end CoordinateRing
p2m_open_scoped "WeierstrassCurve.Affine.CoordinateRing" in

theorem CoordinateRing.adjoin_mk_X_mk_Y :
    Algebra.adjoin K {CoordinateRing.mk W.toAffine (C X), CoordinateRing.mk W.toAffine Y} = ⊤ := by
  set x := CoordinateRing.mk W.toAffine (C X) with hx
  set y := CoordinateRing.mk W.toAffine Y with hy
  apply Algebra.eq_top_iff.mpr
  intro r
  induction r using AdjoinRoot.induction_on with
  | ih p =>

    have hC : ∀ c : K[X], CoordinateRing.mk W.toAffine (C c) ∈ Algebra.adjoin K {x, y} := by
      intro c
      have : CoordinateRing.mk W.toAffine (C c) = aeval x c := by
        have h1 : (CoordinateRing.mk W.toAffine).comp C = (aeval x : K[X] →ₐ[K] _).toRingHom := by
          apply Polynomial.ringHom_ext
          · intro k
            rw [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, aeval_C]
            rfl
          · rw [RingHom.comp_apply, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom, aeval_X]
        exact congrArg (fun f : K[X] →+* _ => f c) h1
      rw [this]
      exact Algebra.adjoin_mono (Set.singleton_subset_iff.mpr (Set.mem_insert _ _))
        (Polynomial.aeval_mem_adjoin_singleton K x)
    induction p using Polynomial.induction_on with
    | C c => exact hC c
    | add p q hp hq => rw [map_add]; exact add_mem hp hq
    | monomial n c _ =>
      rw [map_mul, map_pow]
      exact mul_mem (hC c)
        (pow_mem (Algebra.subset_adjoin (Set.mem_insert_of_mem x (Set.mem_singleton y))) _)

end WeierstrassCurve.Affine

open _root_.WeierstrassCurve _root_.P2MW.S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top.WeierstrassCurve _root_.WeierstrassCurve.Affine _root_.P2MW.S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top.WeierstrassCurve.Affine in
theorem solution {K : Type*} [Field K] (W : WeierstrassCurve K) : IntermediateField.adjoin K {algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField (WeierstrassCurve.Affine.CoordinateRing.mk W.toAffine (Polynomial.C Polynomial.X)), algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField (WeierstrassCurve.Affine.CoordinateRing.mk W.toAffine Polynomial.X)} = ⊤ := by
  set x := CoordinateRing.mk W.toAffine (C X)
  set y := CoordinateRing.mk W.toAffine Y
  set S : IntermediateField K W.toAffine.FunctionField := IntermediateField.adjoin K
    {algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField x,
      algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField y} with hS

  have hR : ∀ r : W.toAffine.CoordinateRing,
      algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField r ∈ S := by
    intro r
    let φ : W.toAffine.CoordinateRing →ₐ[K] W.toAffine.FunctionField :=
      IsScalarTower.toAlgHom K W.toAffine.CoordinateRing W.toAffine.FunctionField
    have hr : r ∈ (⊤ : Subalgebra K W.toAffine.CoordinateRing) := Algebra.mem_top
    rw [← CoordinateRing.adjoin_mk_X_mk_Y W] at hr
    have himg : φ r ∈ (Algebra.adjoin K {x, y}).map φ := Subalgebra.mem_map.mpr ⟨r, hr, rfl⟩
    rw [AlgHom.map_adjoin] at himg
    have hle : Algebra.adjoin K (φ '' {x, y}) ≤ S.toSubalgebra := by
      rw [Set.image_pair]
      exact IntermediateField.algebra_adjoin_le_adjoin K _
    exact hle himg
  apply eq_top_iff.mpr
  intro z _
  obtain ⟨a, b, -, rfl⟩ := IsFractionRing.div_surjective (A := W.toAffine.CoordinateRing) z
  exact div_mem (hR a) (hR b)

end S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top
end P2MW
export P2MW.S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top (solution)

end privateSection

public section publicSection


theorem WeierstrassCurve.Affine.FunctionField.adjoin_X_Y_eq_top {K : Type*} [Field K] (W : WeierstrassCurve K) : IntermediateField.adjoin K {algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField (WeierstrassCurve.Affine.CoordinateRing.mk W.toAffine (Polynomial.C Polynomial.X)), algebraMap W.toAffine.CoordinateRing W.toAffine.FunctionField (WeierstrassCurve.Affine.CoordinateRing.mk W.toAffine Polynomial.X)} = ⊤ := _root_.P2MW.S_WeierstrassCurve_Affine_FunctionField_adjoin_X_Y_eq_top.solution W

end publicSection
