/-
Based on Prove2Me node ModularCurve.periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf
(0113dc16-2a0e-5225-bf3e-ef9894c1eec1) by Claude (2026-09-05).

Proof based on Prove2Me submission 64337d03-0904-5fbc-b8e1-dc2e9a29da31
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_PeriodOf

import Definitions.FLT.Def_P2M_Util

/-!
# Segment period equals difference of primitive values

Theorem statement: `ModularCurve.periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf`
(`0113dc16-2a0e-5225-bf3e-ef9894c1eec1`), by Claude, 2026-09-05.

Proof: submission `64337d03-0904-5fbc-b8e1-dc2e9a29da31`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\Gamma$ be a subgroup of $\mathrm{SL}_2(\mathbb Z)$, let $f$ be a cusp form of weight $2$ for
$\Gamma$, and let $F\colon\mathfrak H\to\mathbb C$ satisfy
[`ModularCurve.HasEquivariantPrimitiveOf`](def/ModularCurve_PeriodOf.html#L71)$\,\Gamma\,f\,F$, that
is: (i) for every $\tau\in\mathfrak H$ the function $F\circ\mathrm{ofComplex}$ has derivative
$f(\tau)$ at the point $\tau$ of $\mathbb C$; (ii) $F$ tends to $0$ along the filter `atImInfty`;
(iii) $F$ is an equivariant primitive in the sense that for each $\gamma\in\Gamma$ there is a
constant $c\in\mathbb C$ with $F(\gamma\cdot z)-F(z)=c$ for all $z\in\mathfrak H$; and (iv) for
every $\delta\in\mathrm{SL}_2(\mathbb Z)$ the function $w\mapsto F(\delta\cdot w)$ has a limit
$L\in\mathbb C$ along `atImInfty`. Then for every $\gamma\in\Gamma$ the value at $f$ of the linear
functional [`ModularCurve.periodOf`](def/ModularCurve_PeriodOf.html#L56)$\,\Gamma\,\gamma$ on
$S_2(\Gamma)$ — by definition the integral $\int_0^1$ of the project's period integrand along the
straight segment from $i$ to $\gamma\cdot i$, namely $t\mapsto f\bigl((1-t)i+t\,\gamma
i\bigr)\,(\gamma i-i)$ — equals $F(\gamma\cdot i)-F(i)$.

This is the fundamental theorem of calculus along a segment in the upper half plane, identifying the
two standard descriptions of the periods of a weight-$2$ cusp form: segment integrals, which define
the period lattice inside $S_2(\Gamma)^\vee$, and differences of values of a primitive, which define
the period map into group cohomology. It is used throughout the construction of the period lattice
and the Abel–Jacobi dictionary for modular curves, and in the recognition of eigenforms by their
$q$-coefficients.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf

open scoped MatrixGroups
open UpperHalfPlane

namespace ModularCurve
p2m_export "ModularCurve" "intervalIntegrable_periodIntegrandOf periodAlongOf periodAlongOf_apply periodOf HasEquivariantPrimitiveOf clamp01_of_mem segmentPoint continuous_segmentPoint segmentPath coe_segmentPath period"
namespace PeriodFTCOf
p2m_open "ModularCurve"

theorem hasDerivAt_affine (a b : ℂ) (t : ℝ) :
    HasDerivAt (fun s : ℝ => (1 - (s : ℂ)) * a + (s : ℂ) * b) (b - a) t := by
  have h1 : HasDerivAt (fun s : ℝ => (s : ℂ)) 1 t := Complex.ofRealCLM.hasDerivAt
  have h2 : HasDerivAt (fun s : ℝ => (1 - (s : ℂ)) * a) (-(1 : ℂ) * a) t := by
    simpa using ((hasDerivAt_const t (1 : ℂ)).sub h1).mul_const a
  have h3 : HasDerivAt (fun s : ℝ => (s : ℂ) * b) (1 * b) t := h1.mul_const b
  have := h2.add h3
  convert this using 1
  · ring

theorem segmentPoint_eq_of_mem {τ₀ τ₁ : ℍ} {t : ℝ} (ht : t ∈ Set.Icc (0 : ℝ) 1) :
    ModularCurve.segmentPoint τ₀ τ₁ t = (1 - (t : ℂ)) * (τ₀ : ℂ) + (t : ℂ) * (τ₁ : ℂ) := by
  simp only [ModularCurve.segmentPoint, ModularCurve.clamp01_of_mem ht, Complex.real_smul,
    Complex.ofReal_sub, Complex.ofReal_one]

theorem periodAlongOf_eq_sub (Γ : Subgroup SL(2, ℤ)) (f : CuspForm Γ 2)
    {F : ℍ → ℂ} (hF : ∀ τ : ℍ, HasDerivAt (F ∘ ofComplex) (f τ) ↑τ) (τ₀ τ₁ : ℍ) :
    ModularCurve.periodAlongOf Γ τ₀ τ₁ f = F τ₁ - F τ₀ := by
  rw [ModularCurve.periodAlongOf_apply]
  set g : ℝ → ℂ := fun t => F (ModularCurve.segmentPath τ₀ τ₁ t) with hg
  have hgF : ∀ t, g t = (F ∘ ofComplex) (ModularCurve.segmentPoint τ₀ τ₁ t) := by
    intro t
    simp only [hg, Function.comp]
    congr 1
    rw [← ModularCurve.coe_segmentPath, ofComplex_apply]
  have hg0 : g 0 = F τ₀ := by
    rw [hgF]
    have : ModularCurve.segmentPoint τ₀ τ₁ 0 = (τ₀ : ℂ) := by
      rw [segmentPoint_eq_of_mem ⟨le_rfl, zero_le_one⟩]; push_cast; ring
    simp only [Function.comp, this, ofComplex_apply]
  have hg1 : g 1 = F τ₁ := by
    rw [hgF]
    have : ModularCurve.segmentPoint τ₀ τ₁ 1 = (τ₁ : ℂ) := by
      rw [segmentPoint_eq_of_mem ⟨zero_le_one, le_rfl⟩]; push_cast; ring
    simp only [Function.comp, this, ofComplex_apply]
  have hFcont : ∀ τ : ℍ, ContinuousAt (F ∘ ofComplex) (τ : ℂ) := fun τ => (hF τ).continuousAt
  have hgcont : Continuous g := by
    have : g = (F ∘ ofComplex) ∘ ModularCurve.segmentPoint τ₀ τ₁ := funext hgF
    rw [this]
    refine continuous_iff_continuousAt.mpr fun t => ?_
    refine ContinuousAt.comp ?_ (ModularCurve.continuous_segmentPoint τ₀ τ₁).continuousAt
    have := hFcont (ModularCurve.segmentPath τ₀ τ₁ t)
    rwa [ModularCurve.coe_segmentPath] at this
  have hderiv : ∀ t ∈ Set.Ioo (0 : ℝ) 1,
      HasDerivAt g (f (ModularCurve.segmentPath τ₀ τ₁ t) * ((τ₁ : ℂ) - τ₀)) t := by
    intro t ht
    have hpath : HasDerivAt (ModularCurve.segmentPoint τ₀ τ₁) ((τ₁ : ℂ) - τ₀) t := by
      refine (hasDerivAt_affine (τ₀ : ℂ) (τ₁ : ℂ) t).congr_of_eventuallyEq ?_
      filter_upwards [Ioo_mem_nhds ht.1 ht.2] with s hs
      exact segmentPoint_eq_of_mem (Set.Ioo_subset_Icc_self hs)
    have hFat : HasDerivAt (F ∘ ofComplex) (f (ModularCurve.segmentPath τ₀ τ₁ t))
        (ModularCurve.segmentPoint τ₀ τ₁ t) := by
      have := hF (ModularCurve.segmentPath τ₀ τ₁ t)
      rwa [ModularCurve.coe_segmentPath] at this
    have hcomp := hFat.comp t hpath
    have : g = (F ∘ ofComplex) ∘ ModularCurve.segmentPoint τ₀ τ₁ := funext hgF
    rw [this]
    exact hcomp
  have hint : IntervalIntegrable
      (fun t => f (ModularCurve.segmentPath τ₀ τ₁ t) * ((τ₁ : ℂ) - τ₀)) MeasureTheory.volume 0 1 :=
    ModularCurve.intervalIntegrable_periodIntegrandOf Γ τ₀ τ₁ f 0 1
  have key := intervalIntegral.integral_eq_sub_of_hasDerivAt_of_le zero_le_one
    hgcont.continuousOn hderiv hint
  rw [key, hg0, hg1]

end ModularCurve.PeriodFTCOf

theorem solution (Γ : Subgroup SL(2, ℤ))
    (f : CuspForm Γ 2) {F : UpperHalfPlane → ℂ}
    (hF : ModularCurve.HasEquivariantPrimitiveOf Γ f F) (γ : Γ) :
    ModularCurve.periodOf Γ γ f =
      F ((γ : SL(2, ℤ)) • UpperHalfPlane.I) - F UpperHalfPlane.I :=
  ModularCurve.PeriodFTCOf.periodAlongOf_eq_sub Γ f hF.1 _ _

end S_ModularCurve_periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf
end P2MW
export P2MW.S_ModularCurve_periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open scoped MatrixGroups
theorem ModularCurve.periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf (Γ : Subgroup SL(2, ℤ))
    (f : CuspForm Γ 2) {F : UpperHalfPlane → ℂ}
    (hF : ModularCurve.HasEquivariantPrimitiveOf Γ f F) (γ : Γ) :
    ModularCurve.periodOf Γ γ f =
      F ((γ : SL(2, ℤ)) • UpperHalfPlane.I) - F UpperHalfPlane.I := _root_.P2MW.S_ModularCurve_periodOf_apply_eq_sub_of_hasEquivariantPrimitiveOf.solution Γ f hF γ

end publicSection
