/-
Based on Prove2Me node AlgebraicCurve.exists_divisor_eq_max_ord_sub_algebraMap
(bfacb035-0084-5562-9e11-8a52d16fde3c) by Claude (2026-09-05).

Proof based on Prove2Me submission 4f54069c-e429-5fd5-8e91-e98ad1b66a55
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.SimpleRing.Principal
import Definitions.FLT.Def_P2M_Util

/-!
# Existence of the divisor of zeros of x-a

Theorem statement: `AlgebraicCurve.exists_divisor_eq_max_ord_sub_algebraMap`
(`bfacb035-0084-5562-9e11-8a52d16fde3c`), by Claude, 2026-09-05.

Proof: submission `4f54069c-e429-5fd5-8e91-e98ad1b66a55`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and assume `HasPrincipalDivisors K F`, i.e. that
for every nonzero $f \in F$ there is a finitely supported integer-valued function $D$ on the places
of $F/K$ with $D(v) = \operatorname{ord}_v(f)$ for every place $v$ and with $\deg D = 0$; here a
place of $F/K$ is a valuation subring of $F$ that contains the image of $K$ under the structure map,
is not all of $F$, and is a principal ideal ring, $\operatorname{ord}_v(f)$ is minus the logarithm
of the value of $f$ under the adic valuation attached to the height-one prime of $v$, and the degree
is the sum of the coefficients weighted by the residue degrees of the places. Let $x \in F$ be
transcendental over $K$ and let $a \in K$. Then there exists a divisor $D$ on the places of $F/K$,
that is a finitely supported function from `Place K F` to $\mathbb{Z}$, such that for every place
$v$ one has $D(v) = \max\bigl(0, \operatorname{ord}_v(x -
\operatorname{algebraMap}_{K,F}(a))\bigr)$. No assertion is made about the degree of $D$.

This is the existence of the divisor of zeros of $x-a$, the positive part of the principal divisor
$\operatorname{div}(x-a)$; its support enumerates the places of $F/K$ lying over the value $a$ of
$x$, so that the fibre of $x$ above $a$ is finite. It feeds the computation of the number of such
places, used in
[`AlgebraicCurve.exists_finset_sum_ord_sub_algebraMap_eq_finrank_of_isAlgClosed`](thm.html#AlgebraicCurve.exists_finset_sum_ord_sub_algebraMap_eq_finrank_of_isAlgClosed).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_exists_divisor_eq_max_ord_sub_algebraMap.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_exists_divisor_eq_max_ord_sub_algebraMap

open AlgebraicCurve

theorem solution
    {K F : Type*} [Field K] [Field F] [Algebra K F] [HasPrincipalDivisors K F]
    (x : F) (hx : Transcendental K x) (a : K) :
    ∃ D : Divisor K F, ∀ v : Place K F, D v = max 0 (v.ord (x - algebraMap K F a)) := by
  classical
  have hxa : x - algebraMap K F a ≠ 0 := by
    intro h
    apply hx
    rw [sub_eq_zero] at h
    rw [h]
    exact isAlgebraic_algebraMap a
  obtain ⟨P, hP, -⟩ := HasPrincipalDivisors.exists_divisor (K := K) (x - algebraMap K F a) hxa
  exact ⟨P.mapRange (fun n => max 0 n) (by simp), fun v => by rw [Finsupp.mapRange_apply, hP v]⟩

end S_AlgebraicCurve_exists_divisor_eq_max_ord_sub_algebraMap
end P2MW
export P2MW.S_AlgebraicCurve_exists_divisor_eq_max_ord_sub_algebraMap (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.exists_divisor_eq_max_ord_sub_algebraMap
    {K F : Type*} [Field K] [Field F] [Algebra K F] [HasPrincipalDivisors K F]
    (x : F) (hx : Transcendental K x) (a : K) :
    ∃ D : Divisor K F, ∀ v : Place K F, D v = max 0 (v.ord (x - algebraMap K F a)) := _root_.P2MW.S_AlgebraicCurve_exists_divisor_eq_max_ord_sub_algebraMap.solution x hx a

end publicSection
