/-
Based on Prove2Me node ModularCurve.frickeInvolutionBar_coeffEmb_qExpand
(05415233-8d55-57c1-b642-f13d86be225b) by Claude (2026-09-05).

Proof based on Prove2Me submission d9f5a616-a9e0-5b6f-9df3-20d8c9a8705f
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_CuspidalClass

import Definitions.FLT.Def_P2M_Util

/-!
# Fricke involution over ℚ̄ exchanges j(qᵃ) and j(qᵇ)

Theorem statement: `ModularCurve.frickeInvolutionBar_coeffEmb_qExpand`
(`05415233-8d55-57c1-b642-f13d86be225b`), by Claude, 2026-09-05.

Proof: submission `d9f5a616-a9e0-5b6f-9df3-20d8c9a8705f`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a positive natural number and suppose the canonically chosen automorphism
`frickeInvolutionFull N` of the modular function field $F_N =$ `modularFunctionFieldFull N` — the
intermediate field of $\mathbb{Q} \subseteq \mathbb{Q}((q))$ generated over $\mathbb{Q}$ by
`divisorExpansions N` — satisfies `IsFrickeAutFull N`, i.e. for every factorisation $a'b' = N$ into
positive naturals it carries the element $j(q^{a'})$, namely the image of the $q$-expansion `jq` $=
q^{-1}\cdot$`jNumQ` under the substitution $q \mapsto q^{a'}$ (`qExpand ℚ a'`), to $j(q^{b'})$;
membership of these elements in $F_N$ is provided by `jqd_mem_full`. Let $a, b$ be positive naturals
with $a \cdot b = N$. Then the base-changed automorphism `frickeInvolutionBar N`, the image of
`frickeInvolutionFull N` under `geomAut` and hence an $\bar{\mathbb{Q}}$-algebra automorphism of
`modularFunctionFieldBar N` $=$ `laurentBaseChange (AlgebraicClosure ℚ)`$F_N$ inside
$\bar{\mathbb{Q}}((q))$, sends the element with underlying series the coefficientwise image
`coeffEmb` of $j(q^{a})$ along $\mathbb{Q} \to \bar{\mathbb{Q}}$ to the element with underlying
series the coefficientwise image of $j(q^{b})$.

This transports the defining exchange property of the Fricke involution $w_N$ on the function field
of $X_0(N)$ over $\mathbb{Q}$ to the geometric function field over $\bar{\mathbb{Q}}$, where the
geometric theory of $X_0(N)$, its cusps and its cuspidal divisor classes is developed. It is used
throughout that development, for instance in identifying the $w_N$-image of the generator
$j(q^{\,\cdot})$ and in the analysis of charts and centredness conditions on the geometric curve.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_frickeInvolutionBar_coeffEmb_qExpand.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_frickeInvolutionBar_coeffEmb_qExpand

open ModularCurve AlgebraicCurve
open scoped Pointwise

theorem solution (N : ℕ) [NeZero N] (h : IsFrickeAutFull N (frickeInvolutionFull N)) (a b : ℕ) (hab : a * b = N) [NeZero a] [NeZero b] :
    frickeInvolutionBar N ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ a jq), coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (Dvd.intro b hab))⟩ = ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ b jq), coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (Dvd.intro_left a hab))⟩ := by
  rw [frickeInvolutionBar_def]
  refine (geomAut_coeffEmb (AlgebraicClosure ℚ) (modularFunctionFieldFull N) (frickeInvolutionFull N)
    ⟨qExpand ℚ a jq, jqd_mem_full N (Dvd.intro b hab)⟩).trans (Subtype.ext ?_)
  change coeffEmb (AlgebraicClosure ℚ) ((frickeInvolutionFull N ⟨qExpand ℚ a jq, _⟩ : modularFunctionFieldFull N) :
    LaurentSeries ℚ) = coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ b jq)
  rw [h a b hab ‹NeZero a› ‹NeZero b›]

end S_ModularCurve_frickeInvolutionBar_coeffEmb_qExpand
end P2MW
export P2MW.S_ModularCurve_frickeInvolutionBar_coeffEmb_qExpand (solution)

end privateSection

public section publicSection


open ModularCurve AlgebraicCurve
theorem ModularCurve.frickeInvolutionBar_coeffEmb_qExpand (N : ℕ) [NeZero N] (h : IsFrickeAutFull N (frickeInvolutionFull N)) (a b : ℕ) (hab : a * b = N) [NeZero a] [NeZero b] : frickeInvolutionBar N ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ a jq), coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (Dvd.intro b hab))⟩ = ⟨coeffEmb (AlgebraicClosure ℚ) (qExpand ℚ b jq), coeffEmb_mem_laurentBaseChange (AlgebraicClosure ℚ) (jqd_mem_full N (Dvd.intro_left a hab))⟩ := _root_.P2MW.S_ModularCurve_frickeInvolutionBar_coeffEmb_qExpand.solution N h a b hab

end publicSection
