/-
Based on Prove2Me node AlgebraicCurve.SemilinearAut.ord_algebraMap_smul
(efeaf7d0-be37-5ce2-98dc-743bf6ddda48) by Claude (2026-09-05).

Proof based on Prove2Me submission 242bea13-f29e-53ae-9a1a-356922a8bd1d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_Correspondence

import Definitions.FLT.Def_P2M_Util

/-!
# Order at a transported place of an element from the subfield

Theorem statement: `AlgebraicCurve.SemilinearAut.ord_algebraMap_smul`
(`efeaf7d0-be37-5ce2-98dc-743bf6ddda48`), by Claude, 2026-09-05.

Proof: submission `242bea13-f29e-53ae-9a1a-356922a8bd1d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$, $F$, $F'$ be fields with $F$ and $F'$ algebras over $K$ and $F'$ an algebra over $F$. Let
$g$ be an element of `SemilinearAut K F`, that is, a pair consisting of a ring automorphism of $F$
and a ring automorphism of $K$ that are compatible with the structure map $K \to F$ (the
automorphism of $F$ sends the image of $a \in K$ to the image of the $K$-automorphism applied to
$a$), and likewise let $g'$ be an element of `SemilinearAut K F'`. Assume `IntertwinesAlong
(algebraMap F F') g g'`, i.e. $g' \cdot (\iota x) = \iota (g \cdot x)$ for every $x \in F$, where
$\iota =$ `algebraMap F F'`. Let $w$ be a place of $F'$ over $K$, namely a valuation subring of $F'$
which contains the image of $K$, is not all of $F'$, and is a principal ideal ring; and let $f \in
F$. Then the order of $\iota f$ at the place $g' \cdot w$ obtained by transporting $w$ by $g'$
equals the order of $\iota(g^{-1} \cdot f)$ at $w$, where the order of an element at a place is the
negative of the logarithm of the value of the associated adic valuation.

This is the formal compatibility, for semilinear automorphisms intertwined along a field extension
$F \subseteq F'$, between transport of places and the induced action on elements coming from the
subfield: the order at the transported place of an element of $F$ is the order at the original place
of the inversely transported element. It is used in the corresponding statement for ramification
indices,
[`AlgebraicCurve.SemilinearAut.ramificationIndex_smul`](thm.html#AlgebraicCurve.SemilinearAut.ramificationIndex_smul).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_SemilinearAut_ord_algebraMap_smul.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_SemilinearAut_ord_algebraMap_smul

open AlgebraicCurve AlgebraicCurve.SemilinearAut
open scoped Pointwise

noncomputable section

theorem solution {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [Algebra F F'] {g : SemilinearAut K F} {g' : SemilinearAut K F'} (hgg' : IntertwinesAlong (algebraMap F F') g g') (w : Place K F') (f : F) : (g' • w).ord (algebraMap F F' f) = w.ord (algebraMap F F' (g⁻¹ • f)) := by
  have hrw : algebraMap F F' f = g' • (algebraMap F F' (g⁻¹ • f)) := by
    rw [hgg' (g⁻¹ • f), smul_inv_smul]
  rw [hrw]
  exact ord_smul g' w _

end

end S_AlgebraicCurve_SemilinearAut_ord_algebraMap_smul
end P2MW
export P2MW.S_AlgebraicCurve_SemilinearAut_ord_algebraMap_smul (solution)

end privateSection

public section publicSection


open AlgebraicCurve AlgebraicCurve.SemilinearAut
theorem AlgebraicCurve.SemilinearAut.ord_algebraMap_smul {K F F' : Type*} [Field K] [Field F] [Field F'] [Algebra K F] [Algebra K F'] [Algebra F F'] {g : SemilinearAut K F} {g' : SemilinearAut K F'} (hgg' : IntertwinesAlong (algebraMap F F') g g') (w : Place K F') (f : F) : (g' • w).ord (algebraMap F F' f) = w.ord (algebraMap F F' (g⁻¹ • f)) := _root_.P2MW.S_AlgebraicCurve_SemilinearAut_ord_algebraMap_smul.solution hgg' w f

end publicSection
