/-
Based on Prove2Me node ModularCurve.eq_jLinePlaceInfty_iff_ord_jGen_neg
(413ef15d-0bcf-59bf-a139-83d5e14af46e) by Claude (2026-09-05).

Proof based on Prove2Me submission 1de9d5da-fc0b-5eb9-8ff9-37e9c945f759
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JLinePlaces

import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceClassification
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_X_sub_C
import Definitions.FLT.Def_P2M_Util

/-!
# A place of the j-line is v_∞ iff j has a pole

Theorem statement: `ModularCurve.eq_jLinePlaceInfty_iff_ord_jGen_neg`
(`413ef15d-0bcf-59bf-a139-83d5e14af46e`), by Claude, 2026-09-05.

Proof: submission `1de9d5da-fc0b-5eb9-8ff9-37e9c945f759`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Here $jq$ denotes the Laurent series $q^{-1}\cdot \mathrm{jNumQ}$ over $\mathbb{Q}$ (the
$q$-expansion of the modular invariant $j$, with $\mathrm{jNumQ}$ the rational-coefficient power
series obtained from the integral numerator series), and $\mathbb{Q}\langle jq\rangle$ is the simple
extension of $\mathbb{Q}$ generated by $jq$ inside the field of Laurent series;
[`ModularCurve.jGen`](def/ModularCurve_X0.html#L268) is $jq$ viewed as an element of that field. A
place of $\mathbb{Q}\langle jq\rangle$ over $\mathbb{Q}$ is, by the project's definition, a
valuation subring of $\mathbb{Q}\langle jq\rangle$ which contains the image of $\mathbb{Q}$, is not
the whole field, and is a principal ideal ring; for such a place $v$ and $f$ in the field,
$v.\mathrm{ord}\,f$ is minus the logarithm of the value of $f$ under the adic valuation attached to
$v$. The place [`ModularCurve.jLinePlaceInfty`](def/ModularCurve_JLinePlaces.html#L58) is the
transport, along the isomorphism $\mathrm{RatFunc}\,\mathbb{Q}\cong\mathbb{Q}\langle jq\rangle$
sending the variable to $jq$ (available since $jq$ is transcendental over $\mathbb{Q}$), of the
place at infinity of $\mathbb{Q}(T)$, i.e. of the valuation subring of the degree valuation. The
assertion is that for every place $v$ of $\mathbb{Q}\langle jq\rangle$ over $\mathbb{Q}$ one has $v
=$ `jLinePlaceInfty` if and only if $v.\mathrm{ord}\,(jGen) < 0$.

This identifies the place at infinity of the $j$-line $X(1)$ over $\mathbb{Q}$ as the unique place
at which $j$ has a pole, all other places lying in the subring where $j$ is integral. It is used by
[`ModularCurve.restrict_eq_jLinePlaceInfty_iff`](thm.html#ModularCurve.restrict_eq_jLinePlaceInfty_iff)
in the analysis of places of modular function fields above the $j$-line.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_eq_jLinePlaceInfty_iff_ord_jGen_neg.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_eq_jLinePlaceInfty_iff_ord_jGen_neg
p2m_attr_erase "instance" "AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.jqNModC_one ModularCurve.reduceModBivar_C_X"
p2m_attr_erase "simp" "ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"

open IntermediateField AlgebraicCurve AlgebraicCurve.RationalFunctionField

attribute [local instance 2000] RatFunc.instAlgebraOfPolynomial
attribute [local instance] ModularCurve.instDecidableEqRatFuncRat

namespace ModularCurve
p2m_export "ModularCurve" "jLineRingEquiv jLineRingEquiv_X instDecidableEqRatFuncRat jLinePlaceInfty jq jGen"
namespace JLineOrdAux
p2m_open "ModularCurve"

theorem equiv_X_sub_C (b : ℚ) :
    ModularCurve.jLineRingEquiv (algebraMap (Polynomial ℚ) (RatFunc ℚ) (Polynomial.X - Polynomial.C b))
      = ModularCurve.jGen - algebraMap ℚ ↥ℚ⟮ModularCurve.jq⟯ b := by
  rw [map_sub, RatFunc.algebraMap_X, map_sub, ModularCurve.jLineRingEquiv_X, RatFunc.algebraMap_C]
  congr 1
  exact RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom b

theorem exists_eq_congr (v : Place ℚ ↥ℚ⟮ModularCurve.jq⟯) :
    ∃ v' : Place ℚ (RatFunc ℚ), v = Place.congrRingEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) v' :=
  ⟨(Place.congrEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom)).symm v,
    ((Place.congrEquiv _ _).apply_symm_apply v).symm⟩

theorem ord_congr_jGen_sub (b : ℚ) (v' : Place ℚ (RatFunc ℚ)) :
    (Place.congrRingEquiv ModularCurve.jLineRingEquiv
        (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) v').ord
      (ModularCurve.jGen - algebraMap ℚ ↥ℚ⟮ModularCurve.jq⟯ b)
    = (Finsupp.single (placeOfPoint ℚ b) (1 : ℤ) + Finsupp.single (placeInfty ℚ) (-1 : ℤ)) v' := by
  rw [← equiv_X_sub_C, Place.ord_congrRingEquiv]
  exact ord_X_sub_C ℚ b v'

theorem injective_congr : Function.Injective (Place.congrRingEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom) : Place ℚ (RatFunc ℚ) → _) :=
  (Place.congrEquiv ModularCurve.jLineRingEquiv
      (RingHom.map_rat_algebraMap ModularCurve.jLineRingEquiv.toRingHom)).injective

end ModularCurve.JLineOrdAux

open ModularCurve.JLineOrdAux

theorem solution (v : AlgebraicCurve.Place ℚ ↥ℚ⟮ModularCurve.jq⟯) :
    v = ModularCurve.jLinePlaceInfty ↔ v.ord ModularCurve.jGen < 0 := by
  obtain ⟨v', rfl⟩ := exists_eq_congr v
  have h := ord_congr_jGen_sub 0 v'
  rw [map_zero, sub_zero] at h
  rw [h]
  have h01 := placeOfPoint_ne_placeInfty ℚ 0
  unfold ModularCurve.jLinePlaceInfty
  constructor
  · intro hv
    rw [injective_congr hv]
    simp [h01.symm]
  · intro hlt
    by_contra hne
    have hne' : v' ≠ placeInfty ℚ := fun h' => hne (by rw [h'])
    rcases eq_or_ne v' (placeOfPoint ℚ 0) with h0 | h0
    · subst h0
      simp [h01] at hlt
    · simp [hne', h0] at hlt

end S_ModularCurve_eq_jLinePlaceInfty_iff_ord_jGen_neg
end P2MW
export P2MW.S_ModularCurve_eq_jLinePlaceInfty_iff_ord_jGen_neg (solution)

end privateSection

public section publicSection


open IntermediateField AlgebraicCurve
theorem ModularCurve.eq_jLinePlaceInfty_iff_ord_jGen_neg (v : AlgebraicCurve.Place ℚ ↥ℚ⟮ModularCurve.jq⟯) :
    v = ModularCurve.jLinePlaceInfty ↔ v.ord ModularCurve.jGen < 0 := _root_.P2MW.S_ModularCurve_eq_jLinePlaceInfty_iff_ord_jGen_neg.solution v

end publicSection
