/-
Based on Prove2Me node ModularCurve.realizeOf_eq_div
(189c50d4-7af7-5360-ad95-f58a8c9162f0) by Claude (2026-09-05).

Proof based on Prove2Me submission 761815dc-7dd5-5884-b656-0972b95adad5
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ComplexPlaceDictionaryOf

import Definitions.FLT.Def_P2M_Util

/-!
# Independence of the realisation from the chosen presentation

Theorem statement: `ModularCurve.realizeOf_eq_div` (`189c50d4-7af7-5360-ad95-f58a8c9162f0`), by
Claude, 2026-09-05.

Proof: submission `761815dc-7dd5-5884-b656-0972b95adad5`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\Gamma \le \mathrm{SL}_2(\mathbb{Z})$ be a subgroup containing the translation matrix
`ModularGroup.T`, let $k \in \mathbb{Z}$, and let $g, h$ be modular forms of weight $k$ on $\Gamma$.
Let $x$ be a Laurent series over $\mathbb{C}$ and suppose that $x$ times the image in
$\mathbb{C}((q))$ of the period-$1$ $q$-expansion of $h$ equals the image of the period-$1$
$q$-expansion of $g$. Let $\tau$ lie in the upper half plane and suppose $h(\tau) \neq 0$. Then
[`ModularCurve.realizeOf`](def/ModularCurve_ComplexPlaceDictionaryOf.html#L15) $\Gamma\, x\, \tau$
equals $g(\tau)/h(\tau)$. Here
[`ModularCurve.realizeOf`](def/ModularCurve_ComplexPlaceDictionaryOf.html#L15) $\Gamma\, x\, \tau$
is defined by cases: if there exists a triple consisting of a weight $j \in \mathbb{Z}$ and a pair
$(G, H)$ of modular forms of weight $j$ on $\Gamma$ with $H(\tau) \neq 0$ and $x \cdot \widetilde{H}
= \widetilde{G}$ in $\mathbb{C}((q))$ (tilde denoting the period-$1$ $q$-expansion pushed into
Laurent series), it is $G(\tau)/H(\tau)$ for one such triple chosen by the axiom of choice, and
otherwise it is $0$. Thus the assertion is that the chosen value agrees with the value computed from
the given presentation $x \cdot \widetilde{h} = \widetilde{g}$.

This is the well-definedness statement for the realisation of a Laurent series as a meromorphic
function on the upper half plane as a ratio of modular forms of equal weight on $\Gamma$: the value
at $\tau$ does not depend on the presentation. It underlies the complex-place dictionary for modular
curves and is invoked throughout that development, for instance in the treatment of Abel–Jacobi
images, of the action of complex conjugation on points, and of stabiliser orders and ramification.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_realizeOf_eq_div.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_realizeOf_eq_div

open UpperHalfPlane
open scoped MatrixGroups Topology Manifold

namespace ModularCurve
p2m_export "ModularCurve" "realizeOf realizeOf_def"
namespace RealizeOfWD
end ModularCurve.RealizeOfWD
p2m_open_scoped "ModularCurve" in

theorem ModularCurve.RealizeOfWD.one_mem_strictPeriods (Γ : Subgroup SL(2, ℤ)) (hT : ModularGroup.T ∈ Γ) :
    (1 : ℝ) ∈ (Γ : Subgroup (GL (Fin 2) ℝ)).strictPeriods := by
  rw [Subgroup.strictPeriods_eq_zmultiples_one_of_T_mem hT]
  exact AddSubgroup.mem_zmultiples _

open scoped MatrixGroups in
theorem solution
    (Γ : Subgroup SL(2, ℤ)) (hT : ModularGroup.T ∈ Γ) {k : ℤ}
    (g h : ModularForm Γ k) (x : LaurentSeries ℂ)
    (hx : x * ((UpperHalfPlane.qExpansion 1 (h : UpperHalfPlane → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
      ((UpperHalfPlane.qExpansion 1 (g : UpperHalfPlane → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ))
    (τ : UpperHalfPlane) (hτ : (h : UpperHalfPlane → ℂ) τ ≠ 0) :
    ModularCurve.realizeOf Γ x τ = (g : UpperHalfPlane → ℂ) τ / (h : UpperHalfPlane → ℂ) τ := by
  classical
  have h1 : (1 : ℝ) ∈ (Γ : Subgroup (GL (Fin 2) ℝ)).strictPeriods :=
    ModularCurve.RealizeOfWD.one_mem_strictPeriods Γ hT
  have H : ∃ p : (k : ℤ) × (ModularForm Γ k × ModularForm Γ k),
      (p.2.2 : ℍ → ℂ) τ ≠ 0 ∧
        x * ((qExpansion 1 (p.2.2 : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
          ((qExpansion 1 (p.2.1 : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) :=
    ⟨⟨k, g, h⟩, hτ, hx⟩
  have hval : ModularCurve.realizeOf Γ x τ = (H.choose.2.1 : ℍ → ℂ) τ / (H.choose.2.2 : ℍ → ℂ) τ := by
    rw [ModularCurve.realizeOf_def]
    exact dite_eq_left H
  rw [hval]
  obtain ⟨hτ', hx'⟩ := H.choose_spec
  set p := H.choose with hp
  obtain ⟨k', g', h'⟩ := p
  simp only at hτ' hx' ⊢
  have hq : qExpansion 1 ((g' : ℍ → ℂ) * (h : ℍ → ℂ)) = qExpansion 1 ((g : ℍ → ℂ) * (h' : ℍ → ℂ)) := by
    apply (HahnSeries.ofPowerSeries_injective (Γ := ℤ) (R := ℂ))
    rw [ModularForm.qExpansion_mul_coe one_pos h1, ModularForm.qExpansion_mul_coe one_pos h1,
      PowerSeries.coe_mul, PowerSeries.coe_mul, ← hx, ← hx']
    ring
  have hAB : (g'.mul h : ModularForm Γ (k' + k)) = ModularForm.mcast (add_comm k k') (g.mul h') := by
    rw [← sub_eq_zero, ← ModularForm.qExpansion_eq_zero_iff one_pos h1, FunLike.coe_sub,
      ModularForm.qExpansion_sub one_pos h1, sub_eq_zero, ModularForm.coe_mcast,
      ModularForm.coe_mul, ModularForm.coe_mul, hq]
  have hτeq : (g' : ℍ → ℂ) τ * (h : ℍ → ℂ) τ = (g : ℍ → ℂ) τ * (h' : ℍ → ℂ) τ := by
    have := congrArg (fun f : ModularForm Γ (k' + k) => (f : ℍ → ℂ) τ) hAB
    simpa [ModularForm.coe_mul, ModularForm.coe_mcast] using this
  rw [div_eq_div_iff hτ' hτ, hτeq]

end S_ModularCurve_realizeOf_eq_div
end P2MW
export P2MW.S_ModularCurve_realizeOf_eq_div (solution)

end privateSection

public section publicSection


open scoped MatrixGroups
theorem ModularCurve.realizeOf_eq_div
    (Γ : Subgroup SL(2, ℤ)) (hT : ModularGroup.T ∈ Γ) {k : ℤ}
    (g h : ModularForm Γ k) (x : LaurentSeries ℂ)
    (hx : x * ((UpperHalfPlane.qExpansion 1 (h : UpperHalfPlane → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) =
      ((UpperHalfPlane.qExpansion 1 (g : UpperHalfPlane → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ))
    (τ : UpperHalfPlane) (hτ : (h : UpperHalfPlane → ℂ) τ ≠ 0) :
    ModularCurve.realizeOf Γ x τ = (g : UpperHalfPlane → ℂ) τ / (h : UpperHalfPlane → ℂ) τ := _root_.P2MW.S_ModularCurve_realizeOf_eq_div.solution Γ hT g h x hx τ hτ

end publicSection
