/-
Based on Prove2Me node ModularCurve.Period.finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one
(0f90f902-6270-5272-a743-919daad53e1d) by Claude (2026-09-05).

Proof based on Prove2Me submission e8a15ddc-6513-5410-9aca-ec001d8484c8
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_PeriodMap

import Mathlib.GroupTheory.Schreier
import Mathlib.LinearAlgebra.Matrix.FixedDetMatrices
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.PicardGroup
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.SimpleRing.Principal
import Theorems.FLT.Thm_Matrix_SpecialLinearGroup_exists_addMonoidHom_conj_T_pow_minimalPeriod_eq_of_finsum_eq_zero
import Definitions.FLT.Def_P2M_Util

/-!
# Parabolic characters plus cusp count bounded by dimHom(Γ,K)+1

Theorem statement:
`ModularCurve.Period.finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one`
(`0f90f902-6270-5272-a743-919daad53e1d`), by Claude, 2026-09-05.

Proof: submission `e8a15ddc-6513-5410-9aca-ec001d8484c8`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\Gamma$ be a subgroup of finite index in $\mathrm{SL}_2(\mathbb{Z})$ containing $-1$, and let
$K$ be a field. Consider the $K$-vector space $\mathrm{Hom}(\Gamma,K)$ of additive group
homomorphisms from the additive group underlying $\Gamma$ (that is, `Additive Γ`) to $K$, and inside
it the subspace [`ModularCurve.Period.parabolicHoms K Γ K`](def/ModularCurve_PeriodMap.html#L62)
consisting of those $\varphi$ with $\varphi(\gamma)=0$ for every $\gamma\in\Gamma$ whose image in
$M_2(\mathbb{Z})$ has $(\operatorname{tr}\gamma)^2=4$, i.e. trace $\pm 2$. Let the cusp set be the
quotient of $\mathrm{SL}_2(\mathbb{Z})/\Gamma$ by the orbit equivalence relation for the action of
the cyclic group $\langle T\rangle$ of integer powers of $T=\begin{pmatrix}1&1\\0&1\end{pmatrix}$,
and let its cardinality be measured by `Nat.card`. The assertion is the numerical inequality
$$\dim_K \big(\text{parabolic homomorphisms}\big) + \#\big(\langle T\rangle\text{-orbits on
}\mathrm{SL}_2(\mathbb{Z})/\Gamma\big) \le \dim_K \mathrm{Hom}(\Gamma,K) + 1,$$
the dimensions being Mathlib's `Module.finrank`.

This is the standard dimension count comparing parabolic cohomology in degree one with the full
character space of $\Gamma$, the discrepancy being governed by the number of cusps: the evaluation
of a character on the cusp generators covers the hyperplane of sum-zero functions on the cusps. It
is used in the project's computations of $\dim_K H^1_{\mathrm{par}}$ for $\Gamma_0(N)$ and
$\Gamma(N)$, namely in
[`ModularCurve.finrank_parabolicHoms_gamma0_le_two_mul_genusFormula`](thm.html#ModularCurve.finrank_parabolicHoms_gamma0_le_two_mul_genusFormula)
and
[`ModularCurve.six_mul_level_mul_finrank_parabolicHoms_Gamma_add_eq`](thm.html#ModularCurve.six_mul_level_mul_finrank_parabolicHoms_Gamma_add_eq).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_Period_finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_Period_finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one

set_option linter.unusedSectionVars false

open Matrix MatrixGroups Subgroup MulAction ModularCurve.Period

noncomputable section

namespace BassSerreCuspDim

variable (Γ : Subgroup SL(2, ℤ)) [Γ.FiniteIndex] (K : Type) [Field K]

abbrev Cu : Type := orbitRel.Quotient (zpowers ModularGroup.T) (SL(2, ℤ) ⧸ Γ)

def cusp (x : SL(2, ℤ) ⧸ Γ) : Cu Γ := Quotient.mk (orbitRel (zpowers ModularGroup.T) _) x

theorem cusp_surjective : Function.Surjective (cusp Γ) := Quotient.mk_surjective

def wd (x : SL(2, ℤ) ⧸ Γ) : ℕ := Function.minimalPeriod (fun y => ModularGroup.T • y) x

theorem gen_mem (g : SL(2, ℤ)) : g⁻¹ * ModularGroup.T ^ wd Γ (g : SL(2, ℤ) ⧸ Γ) * g ∈ Γ := by
  have h0 : ModularGroup.T ^ wd Γ (g : SL(2, ℤ) ⧸ Γ) • (g : SL(2, ℤ) ⧸ Γ) = (g : SL(2, ℤ) ⧸ Γ) :=
    (MulAction.pow_smul_eq_iff_minimalPeriod_dvd).mpr dvd_rfl
  have h1 : ((ModularGroup.T ^ wd Γ (g : SL(2, ℤ) ⧸ Γ) * g : SL(2, ℤ)) : SL(2, ℤ) ⧸ Γ)
      = (g : SL(2, ℤ) ⧸ Γ) := h0
  rw [QuotientGroup.eq] at h1
  have h2 := Γ.inv_mem h1
  simpa only [_root_.mul_inv_rev, inv_inv, mul_assoc] using h2

def rep (c : Cu Γ) : SL(2, ℤ) := Quotient.out (Quotient.out c)

theorem cusp_rep (c : Cu Γ) : cusp Γ (rep Γ c : SL(2, ℤ) ⧸ Γ) = c := by
  rw [rep, QuotientGroup.out_eq', cusp]; exact Quotient.out_eq c

def genOf (c : Cu Γ) : Γ := ⟨_, gen_mem Γ (rep Γ c)⟩

theorem trace_genOf (c : Cu Γ) :
    ((genOf Γ c : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ).trace = 2 := by
  show (((rep Γ c)⁻¹ * ModularGroup.T ^ wd Γ (rep Γ c : SL(2, ℤ) ⧸ Γ) * rep Γ c : SL(2, ℤ)) :
      Matrix (Fin 2) (Fin 2) ℤ).trace = 2
  rw [Matrix.SpecialLinearGroup.coe_mul, Matrix.trace_mul_comm, Matrix.SpecialLinearGroup.coe_mul,
    ← Matrix.mul_assoc, ← Matrix.SpecialLinearGroup.coe_mul, mul_inv_cancel,
    Matrix.SpecialLinearGroup.coe_one, Matrix.one_mul, ← zpow_natCast, ModularGroup.coe_T_zpow]
  simp [Matrix.trace_fin_two]

def ev : (Additive Γ →+ K) →ₗ[K] (Cu Γ → K) where
  toFun φ c := φ (Additive.ofMul (genOf Γ c))
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

theorem parabolicHoms_le_ker : parabolicHoms K Γ K ≤ LinearMap.ker (ev Γ K) := by
  intro φ hφ
  rw [LinearMap.mem_ker]
  funext c
  exact hφ (genOf Γ c) (by rw [trace_genOf]; norm_num)

def sumL [Fintype (Cu Γ)] : (Cu Γ → K) →ₗ[K] K where
  toFun v := ∑ c, v c
  map_add' _ _ := by simp [Finset.sum_add_distrib]
  map_smul' _ _ := by simp [Finset.mul_sum]

theorem ker_sumL_le_range (hneg : (-1 : SL(2, ℤ)) ∈ Γ) [Fintype (Cu Γ)] :
    LinearMap.ker (sumL Γ K) ≤ LinearMap.range (ev Γ K) := by
  intro v hv
  rw [LinearMap.mem_ker] at hv
  have hv' : ∑ᶠ c, v c = 0 := by rw [finsum_eq_sum_of_fintype]; exact hv
  obtain ⟨φ, hφ⟩ :=
    Matrix.SpecialLinearGroup.exists_addMonoidHom_conj_T_pow_minimalPeriod_eq_of_finsum_eq_zero
      Γ hneg K v hv'
  refine ⟨φ, funext fun c => ?_⟩
  show φ (Additive.ofMul (genOf Γ c)) = v c
  have key := hφ (rep Γ c) (gen_mem Γ (rep Γ c))
  exact key.trans (congrArg v (cusp_rep Γ c))

theorem finrank_ker_sumL_add_one [Fintype (Cu Γ)] :
    Module.finrank K (LinearMap.ker (sumL Γ K)) + 1 = Fintype.card (Cu Γ) := by
  classical
  have c₀ : Cu Γ := cusp Γ ((1 : SL(2, ℤ)) : SL(2, ℤ) ⧸ Γ)
  have hsurj : Function.Surjective (sumL Γ K) := fun r =>
    ⟨Pi.single c₀ r, by simp [sumL]⟩
  have h1 : Module.finrank K (LinearMap.range (sumL Γ K)) = 1 := by
    rw [LinearMap.range_eq_top.mpr hsurj, finrank_top, Module.finrank_self]
  have h2 := LinearMap.finrank_range_add_finrank_ker (sumL Γ K)
  rw [h1, Module.finrank_fintype_fun_eq_card] at h2
  omega

theorem moduleFinite_hom : Module.Finite K (Additive Γ →+ K) := by
  classical
  have : Group.FG SL(2, ℤ) := Group.fg_iff.mpr
    ⟨{ModularGroup.S, ModularGroup.T}, SpecialLinearGroup.SL2Z_generators,
      (Set.finite_singleton _).insert _⟩
  have hΓ : Group.FG Γ := Subgroup.fg_of_index_ne_zero _
  obtain ⟨_, s, _, hs⟩ := Group.fg_iff'.mp hΓ
  let e : (Additive Γ →+ K) →ₗ[K] (s → K) :=
    { toFun := fun φ i => φ (Additive.ofMul (i : Γ))
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
  refine Module.Finite.of_injective e ?_
  intro φ ψ h
  have key : ∀ γ : Γ, φ (Additive.ofMul γ) = ψ (Additive.ofMul γ) := by
    intro γ
    have hγ : γ ∈ Subgroup.closure (s : Set Γ) := by rw [hs]; exact Subgroup.mem_top γ
    induction hγ using Subgroup.closure_induction with
    | mem x hx => exact congrFun h ⟨x, hx⟩
    | one => rw [ofMul_one, map_zero, map_zero]
    | mul x y _ _ hx hy => rw [ofMul_mul, map_add, map_add, hx, hy]
    | inv x _ hx => rw [ofMul_inv, map_neg, map_neg, hx]
  exact AddMonoidHom.ext fun x => key (Additive.toMul x)

theorem main (hneg : (-1 : SL(2, ℤ)) ∈ Γ) :
    Module.finrank K (parabolicHoms K Γ K) + Nat.card (Cu Γ)
      ≤ Module.finrank K (Additive Γ →+ K) + 1 := by
  classical
  have : Fintype (Cu Γ) := Fintype.ofFinite _
  have := moduleFinite_hom Γ K
  have h1 : Module.finrank K (parabolicHoms K Γ K) ≤ Module.finrank K (LinearMap.ker (ev Γ K)) :=
    Submodule.finrank_mono (parabolicHoms_le_ker Γ K)
  have h2 : Module.finrank K (LinearMap.ker (sumL Γ K))
      ≤ Module.finrank K (LinearMap.range (ev Γ K)) :=
    Submodule.finrank_mono (ker_sumL_le_range Γ K hneg)
  have h3 := finrank_ker_sumL_add_one Γ K
  have h4 := LinearMap.finrank_range_add_finrank_ker (ev Γ K)
  rw [Nat.card_eq_fintype_card]
  omega

end BassSerreCuspDim

theorem solution (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ)) [Γ.FiniteIndex]
    (hneg : (-1 : Matrix.SpecialLinearGroup (Fin 2) ℤ) ∈ Γ) (K : Type) [Field K] :
    Module.finrank K (ModularCurve.Period.parabolicHoms K Γ K)
      + Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers ModularGroup.T)
          (Matrix.SpecialLinearGroup (Fin 2) ℤ ⧸ Γ))
      ≤ Module.finrank K (Additive Γ →+ K) + 1 :=
  BassSerreCuspDim.main Γ K hneg

end
end S_ModularCurve_Period_finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one
end P2MW
export P2MW.S_ModularCurve_Period_finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one (solution)

end privateSection

public section publicSection


theorem ModularCurve.Period.finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one
    (Γ : Subgroup (Matrix.SpecialLinearGroup (Fin 2) ℤ)) [Γ.FiniteIndex]
    (hneg : (-1 : Matrix.SpecialLinearGroup (Fin 2) ℤ) ∈ Γ) (K : Type) [Field K] :
    Module.finrank K (ModularCurve.Period.parabolicHoms K Γ K)
      + Nat.card (MulAction.orbitRel.Quotient (Subgroup.zpowers ModularGroup.T)
          (Matrix.SpecialLinearGroup (Fin 2) ℤ ⧸ Γ))
      ≤ Module.finrank K (Additive Γ →+ K) + 1 := _root_.P2MW.S_ModularCurve_Period_finrank_parabolicHoms_add_natCard_le_finrank_addMonoidHom_add_one.solution Γ hneg K

end publicSection
