/-
Based on Prove2Me node ModularCurve.PhiGen.mem_adjoin_jq_of_phiGenDescends
(a4ed865b-516c-5b55-8d36-8079c307dc26) by Claude (2026-09-05).

Proof based on Prove2Me submission 1ee80e3a-fc52-5318-8dcc-0ec47b387159
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_X0
public import Definitions.FLT.Def_ModularCurve_PhiGen
public import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots
public import Mathlib.NumberTheory.Cyclotomic.Basic

import Definitions.FLT.Def_ModularForm_HeckeOperator
import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots
import Mathlib.RingTheory.RootsOfUnity.Complex
import Mathlib.NumberTheory.ModularForms.EisensteinSeries.Basic
import Mathlib.NumberTheory.ModularForms.Discriminant
import Theorems.FLT.Thm_ModularCurve_PhiGen_PhiGenDescends_hasSum_cosetPoly_coeff
import Theorems.FLT.Thm_ModularCurve_mem_adjoin_jq_of_hasSum_of_slash_invariant
import Theorems.FLT.Thm_ModularCurve_cosetPoly_smul
import Theorems.FLT.Thm_ModularCurve_E4_cube_div_discriminant_smul
import Definitions.FLT.Def_P2M_Util

/-!
# Coefficients of the generic level-ℓ modular polynomial lie in ℚ[j]

Theorem statement: `ModularCurve.PhiGen.mem_adjoin_jq_of_phiGenDescends`
(`a4ed865b-516c-5b55-8d36-8079c307dc26`), by Claude, 2026-09-05.

Proof: submission `1ee80e3a-fc52-5318-8dcc-0ec47b387159`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $\ell$ be a prime, let $\zeta$ be a unit of the cyclotomic field `CyclotomicField ℓ ℚ` whose
underlying element is a primitive $\ell$-th root of unity, and let $c : \mathbb{N} \to$
`LaurentSeries ℚ` be a family of rational Laurent series. Assume `PhiGenDescends ℓ ζ c`: for every
$k$, the $k$-th coefficient of the monic polynomial $\prod_{i : \mathrm{Fin}(\ell+1)} (X -
C(\mathrm{conj}\ \ell\ \zeta\ i))$ over the Laurent series of the cyclotomic field, whose roots are
the formal conjugates `conj ℓ ζ i` obtained by applying the substitution `cosetSubst ζ (cosetA ℓ i)
(cosetB ℓ i)` to the coefficientwise image `coeffEmb` of the formal $q$-expansion `jq`, equals the
coefficientwise image under `coeffEmb` of `qExpand ℚ ℓ (c k)`, the series $c_k$ with its exponents
multiplied by $\ell$. Then, for every natural number $k$, the series $c_k$ lies in `Algebra.adjoin ℚ
{jq}`, the $\mathbb{Q}$-subalgebra of `LaurentSeries ℚ` generated by `jq` $=
q^{-1}\cdot$`ofPowerSeries jNumQ`. Thus each solution of the descent equations is a polynomial in
$j$ with rational coefficients.

This is the analytic leg of the construction of the modular polynomial $\Phi_\ell$: it identifies
the coefficients of $\prod_i (X - j\circ\beta_i)$, taken over the $\ell+1$ Hecke cosets of level
$\ell$, as elements of $\mathbb{Q}[j]$, so that $\Phi_\ell(X,Y) \in \mathbb{Q}[X,Y]$ with
$\Phi_\ell(X,j) = \prod_i (X - j\circ\beta_i)$. It is used in the construction of the modular
polynomial data for $X_0(\ell)$ and in the statements about splitting and about the weighted support
of that data; integrality, symmetry and the degree bounds are established separately.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends

noncomputable section

open UpperHalfPlane Complex Filter Topology Function Polynomial
open scoped MatrixGroups

local notation "𝕢" => Function.Periodic.qParam

namespace ModularCurve
p2m_export "ModularCurve" "jq PhiGen.PhiGenDescends PhiGen.PhiGenDescends.hasSum_cosetPoly_coeff mem_adjoin_jq_of_hasSum_of_slash_invariant cosetPoly_smul E4_cube_div_discriminant_smul"
p2m_open "ModularCurve"

section JT

def jt (τ : ℍ) : ℂ := ModularForm.E₄ τ ^ 3 / ModularForm.discriminant τ

lemma jt_smul (γ : SL(2, ℤ)) (τ : ℍ) : jt (γ • τ) = jt τ :=
  ModularCurve.E4_cube_div_discriminant_smul γ τ

end JT

end ModularCurve

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends.ModularCurve ModularCurve.PhiGen in
theorem solution (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : (CyclotomicField ℓ ℚ)ˣ) (hζ : IsPrimitiveRoot (ζ : CyclotomicField ℓ ℚ) ℓ) (c : ℕ → LaurentSeries ℚ) (hc : PhiGenDescends ℓ ζ c) (k : ℕ) : c k ∈ Algebra.adjoin ℚ {jq} := by
  refine ModularCurve.mem_adjoin_jq_of_hasSum_of_slash_invariant (c k) _
    (ModularCurve.PhiGen.PhiGenDescends.hasSum_cosetPoly_coeff ℓ ζ hζ c hc k) fun γ τ => ?_
  exact congrArg (fun p : Polynomial ℂ => p.coeff k)
    (ModularCurve.cosetPoly_smul ℓ hℓ.out ModularCurve.jt ModularCurve.jt_smul γ τ)

end

end S_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends
end P2MW
export P2MW.S_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends (solution)

end privateSection

public section publicSection


open ModularCurve ModularCurve.PhiGen
theorem ModularCurve.PhiGen.mem_adjoin_jq_of_phiGenDescends (ℓ : ℕ) [hℓ : Fact (Nat.Prime ℓ)] (ζ : (CyclotomicField ℓ ℚ)ˣ) (hζ : IsPrimitiveRoot (ζ : CyclotomicField ℓ ℚ) ℓ) (c : ℕ → LaurentSeries ℚ) (hc : PhiGenDescends ℓ ζ c) (k : ℕ) : c k ∈ Algebra.adjoin ℚ {jq} := _root_.P2MW.S_ModularCurve_PhiGen_mem_adjoin_jq_of_phiGenDescends.solution ℓ ζ hζ c hc k

end publicSection
