/-
Based on Prove2Me node AlgebraicCurve.Pic0.zsmul_mk
(233f8b8e-9734-5a46-b2fc-b00da497bc2c) by Claude (2026-09-05).

Proof based on Prove2Me submission 21ca4afd-e7bb-5aca-9a8c-05cb0aa0d9e7
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Definitions.FLT.Def_P2M_Util

/-!
# Integer multiples commute with passage to divisor classes

Theorem statement: `AlgebraicCurve.Pic0.zsmul_mk` (`233f8b8e-9734-5a46-b2fc-b00da497bc2c`), by
Claude, 2026-09-05.

Proof: submission `21ca4afd-e7bb-5aca-9a8c-05cb0aa0d9e7`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, let $m$ be an integer, and let $D$ be an element
of `Divisor.degZero`, that is, a divisor of degree zero. Here a place of $F$ over $K$ is a valuation
subring of $F$ that contains the image of $K$ under the structure map, is not all of $F$, and is a
principal ideal ring; a divisor is a finitely supported function from the set of such places to
$\mathbb{Z}$; the degree homomorphism sends a divisor to the sum of its coefficients weighted by the
integer invariant `deg` of the corresponding place, and `Divisor.degZero` is its kernel. The group
`Pic0` is the quotient of `Divisor.degZero` by the subgroup of those degree-zero divisors that are
principal, i.e. that satisfy the predicate `IsPrincipal`: there is a nonzero $f \in F$ whose order
at every place gives the coefficient of the divisor there, and `Pic0.mk` is the associated quotient
map. The assertion is that $m \cdot \mathrm{mk}(D) = \mathrm{mk}(m \cdot D)$, the scalar
multiplication on the left being that of the additive group `Pic0` and on the right that of
`Divisor.degZero`.

This is the routine compatibility of the divisor-class map with integer multiples, used whenever
orders of divisor classes are computed from explicit multiples of a degree-zero divisor. It is cited
in the proof that a class is trivial as soon as the corresponding multiple of the divisor is
principal, and in the determination of the order of the cuspidal class on a modular curve.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_Pic0_zsmul_mk.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_Pic0_zsmul_mk

open AlgebraicCurve

theorem solution {K F : Type*} [Field K] [Field F] [Algebra K F] (m : ℤ) (D : Divisor.degZero (K := K) (F := F)) : m • Pic0.mk D = Pic0.mk (m • D) :=
  (map_zsmul (QuotientAddGroup.mk' _) m D).symm

end S_AlgebraicCurve_Pic0_zsmul_mk
end P2MW
export P2MW.S_AlgebraicCurve_Pic0_zsmul_mk (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open AlgebraicCurve
theorem AlgebraicCurve.Pic0.zsmul_mk {K F : Type*} [Field K] [Field F] [Algebra K F] (m : ℤ) (D : Divisor.degZero (K := K) (F := F)) : m • Pic0.mk D = Pic0.mk (m • D) := _root_.P2MW.S_AlgebraicCurve_Pic0_zsmul_mk.solution m D

end publicSection
