/-
Based on Prove2Me node AlgebraicCurve.finiteDimensional_lSpace_zero
(2237db3c-cf22-51ab-9ad1-840755d4ac5f) by Claude (2026-09-05).

Proof based on Prove2Me submission 6d18a7c7-683f-5c3d-875b-2a48478665d4
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_AlgebraicCurve_AdelicIndex
public import Definitions.FLT.Def_AlgebraicCurve_IsCurveOver

import Definitions.FLT.Def_P2M_Util

/-!
# Finite-dimensionality of L(0) on a curve

Theorem statement: `AlgebraicCurve.finiteDimensional_lSpace_zero`
(`2237db3c-cf22-51ab-9ad1-840755d4ac5f`), by Claude, 2026-09-05.

Proof: submission `6d18a7c7-683f-5c3d-875b-2a48478665d4`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ and $F$ be fields with $F$ a $K$-algebra, and let $\mathrm{Place}\,K\,F$ denote the set of
places of $F/K$, a place being a valuation subring of $F$ that contains the image of $K$ under the
structure map, is not all of $F$, and is a principal ideal ring. A divisor is a finitely supported
function from places to $\mathbb{Z}$. Assume `IsCurveOver K F`, that is: every nonzero $f \in F$
admits a divisor $D$ with $D(v) = \operatorname{ord}_v(f)$ at every place $v$ and of degree $0$; the
residue field of every place is a finite $K$-module; and the module of Kähler differentials
$\Omega_{F/K}$ is free of rank one over $F$. Assume further that $F$ is essentially of finite type
over $K$ and that at least one place of $F/K$ exists. Then the Riemann–Roch space of the zero
divisor, $L(0) = \{f \in F \mid v(f) \le 1 \text{ for every place } v\}$, regarded as a
$K$-submodule of $F$, is a finite-dimensional $K$-vector space.

This is the statement that the ring of constants of a one-variable function field is finite over the
base field, in the form of finite-dimensionality of $L(0)$. It is the base case of the finiteness
statements for Riemann–Roch spaces in this development and is cited by the results bounding $\dim_K
L(D)$ in terms of $\deg D$ and by the constructions of functions with prescribed orders at a place.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_finiteDimensional_lSpace_zero.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_finiteDimensional_lSpace_zero

noncomputable section

universe u v

open AlgebraicCurve

theorem solution
    (K : Type u) (F : Type v) [Field K] [Field F] [Algebra K F]
    [IsCurveOver K F] [Algebra.EssFiniteType K F] [Nonempty (Place K F)] :
    FiniteDimensional K (LSpace (0 : Divisor K F)) := by
  classical
  have hord : ∀ f : F, f ∈ LSpace (0 : Divisor K F) → f ≠ 0 →
      ∀ v : Place K F, v.ord f = 0 := by
    intro f hf hf0
    have hnn : ∀ v : Place K F, 0 ≤ v.ord f := by
      rcases (mem_lSpace_iff_ord).mp hf with h0 | h
      · exact absurd h0 hf0
      · intro v; simpa using h v
    obtain ⟨D, hDord, hDdeg⟩ :=
      HasPrincipalDivisors.exists_divisor (K := K) (F := F) f hf0
    have hdeg_sum : Divisor.degree D = D.sum (fun w n => n * (w.deg : ℤ)) := by
      simp [Divisor.degree, Finsupp.liftAddHom_apply, AddMonoidHom.coe_mulRight]
    have hdegpos : ∀ w : Place K F, 0 < (w.deg : ℤ) := by
      intro w
      have : Module.Finite K w.ResidueField := IsCurveOver.finiteResidue w
      exact_mod_cast Module.finrank_pos
    have hterm : ∀ w ∈ D.support, D w * (w.deg : ℤ) = 0 := by
      refine (Finset.sum_eq_zero_iff_of_nonneg ?_).mp ?_
      · intro w _
        exact mul_nonneg (hDord w ▸ hnn w) (le_of_lt (hdegpos w))
      · have h := hDdeg
        rw [hdeg_sum] at h
        exact h
    have hD0 : ∀ w : Place K F, D w = 0 := by
      intro w
      by_cases hw : w ∈ D.support
      · rcases mul_eq_zero.mp (hterm w hw) with h | h
        · exact h
        · exact absurd h (ne_of_gt (hdegpos w))
      · exact Finsupp.notMem_support_iff.mp hw
    intro v
    rw [← hDord v]; exact hD0 v
  obtain ⟨v₀⟩ := ‹Nonempty (Place K F)›
  have hmem : ∀ f : LSpace (0 : Divisor K F), (f : F) ∈ v₀.toValuationSubring := by
    intro f
    by_cases hf0 : (f : F) = 0
    · rw [hf0]; exact zero_mem _
    · obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v₀.toValuationSubring
      obtain ⟨u, hu⟩ := v₀.exists_unit_mul_zpow hf0 hπ
      rw [hord f f.2 hf0 v₀, zpow_zero, mul_one] at hu
      rw [hu]; exact (u : v₀.toValuationSubring).2
  let φ : LSpace (0 : Divisor K F) →ₗ[K] v₀.ResidueField :=
    { toFun := fun f => IsLocalRing.residue _ (⟨f, hmem f⟩ : v₀.toValuationSubring)
      map_add' := by
        intro f g
        have h : (⟨((f + g : LSpace (0 : Divisor K F)) : F), hmem (f + g)⟩ :
            v₀.toValuationSubring) = ⟨f, hmem f⟩ + ⟨g, hmem g⟩ := rfl
        rw [h, map_add]
      map_smul' := by
        intro k f
        have h : (⟨((k • f : LSpace (0 : Divisor K F)) : F), hmem (k • f)⟩ :
            v₀.toValuationSubring) = algebraMap K v₀.toValuationSubring k * ⟨f, hmem f⟩ := by
          apply Subtype.ext
          show (k • (f : F)) = _
          rw [Algebra.smul_def]; rfl
        rw [h, map_mul]
        show algebraMap K v₀.ResidueField k * _ = k • _
        rw [Algebra.smul_def] }
  have hker : ∀ f : LSpace (0 : Divisor K F), φ f = 0 → f = 0 := by
    intro f hφf
    by_contra hf
    have hf0 : (f : F) ≠ 0 := fun h => hf (Subtype.ext h)
    obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible v₀.toValuationSubring
    obtain ⟨u, hu⟩ := v₀.exists_unit_mul_zpow hf0 hπ
    rw [hord f f.2 hf0 v₀, zpow_zero, mul_one] at hu
    have huf : (⟨f, hmem f⟩ : v₀.toValuationSubring) = (u : v₀.toValuationSubring) :=
      Subtype.ext hu
    have : IsUnit (φ f) := by
      show IsUnit (IsLocalRing.residue _ (⟨f, hmem f⟩ : v₀.toValuationSubring))
      rw [huf]
      exact (IsLocalRing.residue _).isUnit_map u.isUnit
    rw [hφf] at this
    exact this.ne_zero rfl
  have : Module.Finite K v₀.ResidueField := IsCurveOver.finiteResidue v₀
  exact FiniteDimensional.of_injective φ ((injective_iff_map_eq_zero φ).mpr hker)

end
end S_AlgebraicCurve_finiteDimensional_lSpace_zero
end P2MW
export P2MW.S_AlgebraicCurve_finiteDimensional_lSpace_zero (solution)

end privateSection

public section publicSection


noncomputable section

universe u v
theorem AlgebraicCurve.finiteDimensional_lSpace_zero
    (K : Type u) (F : Type v) [Field K] [Field F] [Algebra K F]
    [IsCurveOver K F] [Algebra.EssFiniteType K F] [Nonempty (Place K F)] :
    FiniteDimensional K (LSpace (0 : Divisor K F)) := _root_.P2MW.S_AlgebraicCurve_finiteDimensional_lSpace_zero.solution K F
end

end publicSection
