/-
Based on Prove2Me node ModularCurve.jCoordinate_spec_modularFunctionFieldBar
(408383eb-30ec-5fbd-ae5b-f0942d44a202) by Claude (2026-09-05).

Proof based on Prove2Me submission 9b2a04a5-501e-5c2d-9dca-c20e8ba09f76
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_AtkinLehner

import Mathlib.NumberTheory.Height.NumberField
import Mathlib.NumberTheory.Height.Projectivization
import Mathlib.Order.Northcott
import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaces
import Definitions.FLT.Def_AlgebraicCurve_RatFuncPlaceClassification
import Theorems.FLT.Thm_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full
import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_toValuationSubring_eq_comap
import Theorems.FLT.Thm_AlgebraicCurve_Place_exists_ord_algebraMap_eq_mul_ord
import Theorems.FLT.Thm_P2M_Dup_AlgebraicCurve_RationalFunctionField_eq_placeOfPoint_or_eq_placeInfty
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_placeOfPoint_algebraMap
import Theorems.FLT.Thm_AlgebraicCurve_RationalFunctionField_ord_placeInfty_algebraMap
import Theorems.FLT.Thm_AlgebraicCurve_Place_ord_algebraMap
import Theorems.FLT.Thm_ModularCurve_ord_cuspInftyBar_coeffEmb_jq
import Theorems.FLT.Thm_AlgebraicCurve_Place_transcendental_of_ord_ne_zero
import Theorems.FLT.Thm_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar_unconditional
import Definitions.FLT.Def_P2M_Util

/-!
# Values of the j-coordinate at places of X₀(N)

Theorem statement: `ModularCurve.jCoordinate_spec_modularFunctionFieldBar`
(`408383eb-30ec-5fbd-ae5b-f0942d44a202`), by Claude, 2026-09-05.

Proof: submission `9b2a04a5-501e-5c2d-9dca-c20e8ba09f76`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a non-zero natural number. Let $\bar{\jmath}$ denote the element of the intermediate
field $\overline{\mathbb{Q}} \subseteq$ `modularFunctionFieldBar N` $\subseteq
\overline{\mathbb{Q}}((q))$ obtained by applying `coeffEmb` (coefficientwise application of
$\mathbb{Q} \to \overline{\mathbb{Q}}$ to a Laurent series) to `jq` $= q^{-1} \cdot$ `jNumQ`, the
$q$-expansion of the modular invariant $j$; here `modularFunctionFieldBar N` is the field generated
over $\overline{\mathbb{Q}}$ inside $\overline{\mathbb{Q}}((q))$ by the `coeffEmb`-images of
`modularFunctionFieldFull N` $= \mathbb{Q}(\mathrm{divisorExpansions}\ N)$, and the membership of
$\bar{\jmath}$ is supplied by `coeffEmb_mem_laurentBaseChange` applied to `jq_mem_full N`. Places
here are the structures `Place` $\overline{\mathbb{Q}}$ (`modularFunctionFieldBar N`): valuation
subrings containing the constants $\overline{\mathbb{Q}}$, proper, and principal ideal rings; `ord`
is the associated $\mathbb{Z}$-valued order function. The conclusion is the conjunction of three
assertions: (1) for every such place $v$ with $v.\mathrm{ord}\,\bar{\jmath} \ge 0$ there is exactly
one constant $c \in \overline{\mathbb{Q}}$ with $v.\mathrm{ord}(\bar{\jmath} - c) > 0$; (2) for
every $c \in \overline{\mathbb{Q}}$ the set of places $v$ with $v.\mathrm{ord}(\bar{\jmath} - c) >
0$ is finite; (3) the set of places $v$ with $v.\mathrm{ord}\,\bar{\jmath} < 0$ is finite.

This is the statement that the $j$-coordinate defines a finite map from the places of the geometric
function field of $X_0(N)$ to $\mathbb{P}^1$ over $\overline{\mathbb{Q}}$: every place at which
$\bar{\jmath}$ is regular has a well-defined value in $\overline{\mathbb{Q}}$ (so residue fields are
$\overline{\mathbb{Q}}$), fibres over constants are finite, and the poles, i.e. the cusps, are
finitely many. It is used in the comparison of the naive logarithmic height of the $j$-coordinate
with the height attached to places, and in the Northcott property for that height.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_jCoordinate_spec_modularFunctionFieldBar.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_jCoordinate_spec_modularFunctionFieldBar
p2m_attr_erase "instance" "ModularCurve.instIsDomainTensorProduct AlgebraicClosure.Rat.isGalois AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy ModularCurve.PhiGen.instNeZeroPhiGenCosetA AlgebraicCurve.RationalFunctionField.instNontrivialSubtypeUnitsWithZeroMultiplicativeIntMemSubgroupValueGroupRatFuncValuationInftyValuation_definitions"
p2m_attr_erase "simp" "ModularCurve.coe_baseChangeEquiv_apply ModularCurve.baseChangeHom_tmul ModularCurve.jqNModC_one ModularCurve.coe_cuspidalDivisor₀ AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff"
p2m_attr_erase "simp" "ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ"
p2m_attr_erase "simp" "AlgebraicCurve.RationalFunctionField.placeEquivOption_placeInfty AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_some AlgebraicCurve.RationalFunctionField.placeEquivOption_placeOfPoint AlgebraicCurve.RationalFunctionField.placeEquivOption_symm_none"
set_option Elab.async false

open ModularCurve AlgebraicCurve

section GenericHelpers

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

private lemma mwP2_ord_pos_iff (v : Place K L) {f : L} (hf : f ≠ 0) :
    0 < v.ord f ↔ v.adicValuation f < 1 := by
  have hval : v.adicValuation f ≠ 0 := v.adicValuation_ne_zero hf
  have hdef : v.ord f = -(WithZero.log (v.adicValuation f)) := rfl
  constructor
  · intro h
    have hlog : WithZero.log (v.adicValuation f) < 0 := by
      rw [hdef] at h; omega
    calc v.adicValuation f
        = WithZero.exp (WithZero.log (v.adicValuation f)) := (WithZero.exp_log hval).symm
      _ < WithZero.exp 0 := WithZero.exp_lt_exp.mpr hlog
      _ = 1 := WithZero.exp_zero
  · intro h
    have h2 : WithZero.exp (WithZero.log (v.adicValuation f)) < WithZero.exp (0 : ℤ) := by
      rw [WithZero.exp_log hval, WithZero.exp_zero]; exact h
    have hlog := WithZero.exp_lt_exp.mp h2
    rw [hdef]; omega

private lemma mwP2_eq_of_ord_sub_pos (v : Place K L) {x : L} {a b : K}
    (ha : 0 < v.ord (x - algebraMap K L a)) (hb : 0 < v.ord (x - algebraMap K L b)) :
    b = a := by
  by_contra hne
  have ha0 : x - algebraMap K L a ≠ 0 := by
    intro h; rw [h, Place.ord_zero] at ha; omega
  have hb0 : x - algebraMap K L b ≠ 0 := by
    intro h; rw [h, Place.ord_zero] at hb; omega
  have hva : v.adicValuation (x - algebraMap K L a) < 1 := (mwP2_ord_pos_iff v ha0).mp ha
  have hvb : v.adicValuation (x - algebraMap K L b) < 1 := (mwP2_ord_pos_iff v hb0).mp hb
  have hδ : algebraMap K L (a - b) = (x - algebraMap K L b) - (x - algebraMap K L a) := by
    rw [map_sub]; ring
  have hab : a - b ≠ 0 := sub_ne_zero.mpr (Ne.symm hne)
  have hδ0 : algebraMap K L (a - b) ≠ 0 :=
    (map_ne_zero_iff _ (algebraMap K L).injective).mpr hab
  have hval1 : v.adicValuation (algebraMap K L (a - b)) = 1 :=
    (v.ord_eq_zero_iff_adicValuation_eq_one hδ0).mp (Place.ord_algebraMap v (a - b))
  have hle : v.adicValuation (algebraMap K L (a - b)) ≤
      max (v.adicValuation (x - algebraMap K L b)) (v.adicValuation (x - algebraMap K L a)) := by
    rw [hδ, sub_eq_add_neg]
    refine le_trans (v.adicValuation.map_add _ _) ?_
    rw [Valuation.map_neg]
  rw [hval1] at hle
  rcases le_max_iff.mp hle with h | h
  · exact absurd (lt_of_le_of_lt h hvb) (lt_irrefl _)
  · exact absurd (lt_of_le_of_lt h hva) (lt_irrefl _)

private lemma mwP2_finite_ord_support [HasPrincipalDivisors K L] {f : L} (hf : f ≠ 0) :
    {v : Place K L | v.ord f ≠ 0}.Finite := by
  obtain ⟨D, hD, -⟩ := HasPrincipalDivisors.exists_divisor (K := K) (F := L) f hf
  refine Set.Finite.subset D.support.finite_toSet fun v hv => ?_
  simp only [Set.mem_ofPred_eq] at hv
  exact Finset.mem_coe.mpr (Finsupp.mem_support_iff.mpr (by rw [hD v]; exact hv))

private lemma mwP2_module_finite_of_adjoin {R : Type*} [Field R] [Algebra R L]
    (E : IntermediateField K L) (hFD : FiniteDimensional E L)
    (hsurj : ∀ y : E, ∃ r : R, algebraMap R L r = y) :
    Module.Finite R L := by
  obtain ⟨s, hs⟩ := Module.finite_def.mp hFD
  refine Module.finite_def.mpr ⟨s, ?_⟩
  rw [eq_top_iff]
  rintro z -
  have hz : z ∈ Submodule.span E (↑s : Set L) := by rw [hs]; exact Submodule.mem_top
  induction hz using Submodule.span_induction with
  | mem y hy => exact Submodule.subset_span hy
  | zero => exact Submodule.zero_mem _
  | add y z' _ _ ihy ihz => exact Submodule.add_mem _ ihy ihz
  | smul e y _ ihy =>
      obtain ⟨r, hr⟩ := hsurj e
      have hsm : e • y = r • y := by
        rw [Algebra.smul_def, Algebra.smul_def, IntermediateField.algebraMap_apply, hr]
      rw [hsm]
      exact Submodule.smul_mem _ _ ihy

private theorem mwP2_exists_unique_coord [IsAlgClosed K] {x : L}
    (htr : Transcendental K x)
    (hFD : FiniteDimensional (IntermediateField.adjoin K ({x} : Set L)) L)
    (v : Place K L) (hv : 0 ≤ v.ord x) :
    ∃! c : K, 0 < v.ord (x - algebraMap K L c) := by
  have hinj : Function.Injective (Polynomial.aeval x : Polynomial K →ₐ[K] L) :=
    transcendental_iff_injective.mp htr
  have hφ0 := nonZeroDivisors_le_comap_nonZeroDivisors_of_injective _ hinj
  let : Algebra (RatFunc K) L := (RatFunc.liftAlgHom (Polynomial.aeval x) hφ0).toRingHom.toAlgebra
  have hψalg : ∀ p : Polynomial K,
      algebraMap (RatFunc K) L (algebraMap (Polynomial K) (RatFunc K) p)
        = Polynomial.aeval x p := by
    intro p
    have h := RatFunc.liftAlgHom_apply_div (Polynomial.aeval x) hφ0 p 1
    simp at h
    exact h
  have : IsScalarTower K (RatFunc K) L :=
    IsScalarTower.of_algebraMap_eq fun c =>
      ((RatFunc.liftAlgHom (Polynomial.aeval x) hφ0).commutes c).symm
  have : Module.Finite (RatFunc K) L := by
    refine mwP2_module_finite_of_adjoin (IntermediateField.adjoin K ({x} : Set L)) hFD ?_
    intro y
    obtain ⟨p, q, hpq⟩ := (IntermediateField.mem_adjoin_simple_iff K (y : L)).mp y.2
    refine ⟨algebraMap (Polynomial K) (RatFunc K) p / algebraMap (Polynomial K) (RatFunc K) q, ?_⟩
    rw [map_div₀, hψalg, hψalg]
    exact hpq.symm
  have : Algebra.IsIntegral (RatFunc K) L := Algebra.IsIntegral.of_finite _ _
  obtain ⟨v₀, hv₀⟩ := Place.exists_toValuationSubring_eq_comap (K := K) (F := RatFunc K) v
  obtain ⟨e, he, hord⟩ := Place.exists_ord_algebraMap_eq_mul_ord v v₀ hv₀
  have : DecidableEq (RatFunc K) := Classical.decEq _
  rcases RationalFunctionField.eq_placeOfPoint_or_eq_placeInfty K v₀ with ⟨a, ha⟩ | hinf
  · have hXa : (Polynomial.X - Polynomial.C a : Polynomial K) ≠ 0 := Polynomial.X_sub_C_ne_zero a
    have h1 : v₀.ord (algebraMap (Polynomial K) (RatFunc K) (Polynomial.X - Polynomial.C a)) = 1 := by
      rw [ha, RationalFunctionField.ord_placeOfPoint_algebraMap a hXa,
        Polynomial.rootMultiplicity_X_sub_C_self]
      simp
    have h2 : algebraMap (RatFunc K) L
        (algebraMap (Polynomial K) (RatFunc K) (Polynomial.X - Polynomial.C a))
        = x - algebraMap K L a := by
      rw [hψalg, map_sub, Polynomial.aeval_X, Polynomial.aeval_C]
    have h3 : 0 < v.ord (x - algebraMap K L a) := by
      rw [← h2, hord, h1, mul_one]
      exact_mod_cast he
    exact ⟨a, h3, fun y hy => mwP2_eq_of_ord_sub_pos v h3 hy⟩
  · exfalso
    have h1 : v₀.ord (algebraMap (Polynomial K) (RatFunc K) Polynomial.X) = -1 := by
      rw [hinf, RationalFunctionField.ord_placeInfty_algebraMap Polynomial.X_ne_zero,
        Polynomial.natDegree_X]
      simp
    have h2 : algebraMap (RatFunc K) L (algebraMap (Polynomial K) (RatFunc K) Polynomial.X)
        = x := by
      rw [hψalg, Polynomial.aeval_X]
    have h3 : v.ord x = -(e : ℤ) := by
      rw [← h2, hord, h1]
      ring
    rw [h3] at hv
    have he' : (0 : ℤ) < (e : ℤ) := mod_cast he
    omega

end GenericHelpers

theorem solution (N : ℕ) [NeZero N] :
    (∀ (v : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N)),
        0 ≤ v.ord ⟨coeffEmb (AlgebraicClosure ℚ) jq,
          coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ →
        ∃! c : AlgebraicClosure ℚ,
          0 < v.ord (⟨coeffEmb (AlgebraicClosure ℚ) jq,
              coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ -
            algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) c)) ∧
      (∀ c : AlgebraicClosure ℚ,
        {v : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) |
          0 < v.ord (⟨coeffEmb (AlgebraicClosure ℚ) jq,
              coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ -
            algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) c)}.Finite) ∧
      ({v : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) |
        v.ord ⟨coeffEmb (AlgebraicClosure ℚ) jq,
          coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ < 0}.Finite) := by
  have hcusp : (cuspInftyBar N).ord
      ⟨coeffEmb (AlgebraicClosure ℚ) jq,
        coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ = -1 :=
    ModularCurve.ord_cuspInftyBar_coeffEmb_jq N
  have htr : Transcendental (AlgebraicClosure ℚ)
      (⟨coeffEmb (AlgebraicClosure ℚ) jq,
        coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ :
        modularFunctionFieldBar N) :=
    Place.transcendental_of_ord_ne_zero (cuspInftyBar N) (by rw [hcusp]; omega)
  have hjb0 : (⟨coeffEmb (AlgebraicClosure ℚ) jq,
      coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ :
      modularFunctionFieldBar N) ≠ 0 := by
    intro h
    rw [h, Place.ord_zero] at hcusp
    omega
  have hFD := ModularCurve.finiteDimensional_adjoin_coeffEmb_jq_full (AlgebraicClosure ℚ) N
  have hpd : HasPrincipalDivisors (AlgebraicClosure ℚ) (modularFunctionFieldBar N) :=
    ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar_unconditional N
  refine ⟨fun v hv => mwP2_exists_unique_coord htr hFD v hv, fun c => ?_, ?_⟩
  · have hne : (⟨coeffEmb (AlgebraicClosure ℚ) jq,
        coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ :
        modularFunctionFieldBar N)
        - algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) c ≠ 0 := by
      rw [sub_ne_zero]
      intro h
      exact htr (by rw [h]; exact isAlgebraic_algebraMap c)
    refine Set.Finite.subset (mwP2_finite_ord_support hne) fun v hv => ?_
    simp only [Set.mem_ofPred_eq] at hv ⊢
    omega
  · refine Set.Finite.subset (mwP2_finite_ord_support hjb0) fun v hv => ?_
    simp only [Set.mem_ofPred_eq] at hv ⊢
    omega

end S_ModularCurve_jCoordinate_spec_modularFunctionFieldBar
end P2MW
export P2MW.S_ModularCurve_jCoordinate_spec_modularFunctionFieldBar (solution)

end privateSection

public section publicSection


open ModularCurve AlgebraicCurve
theorem ModularCurve.jCoordinate_spec_modularFunctionFieldBar (N : ℕ) [NeZero N] :
    (∀ (v : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N)),
        0 ≤ v.ord ⟨coeffEmb (AlgebraicClosure ℚ) jq,
          coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ →
        ∃! c : AlgebraicClosure ℚ,
          0 < v.ord (⟨coeffEmb (AlgebraicClosure ℚ) jq,
              coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ -
            algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) c)) ∧
      (∀ c : AlgebraicClosure ℚ,
        {v : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) |
          0 < v.ord (⟨coeffEmb (AlgebraicClosure ℚ) jq,
              coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ -
            algebraMap (AlgebraicClosure ℚ) (modularFunctionFieldBar N) c)}.Finite) ∧
      ({v : Place (AlgebraicClosure ℚ) (modularFunctionFieldBar N) |
        v.ord ⟨coeffEmb (AlgebraicClosure ℚ) jq,
          coeffEmb_mem_laurentBaseChange (L := AlgebraicClosure ℚ) (hx := jq_mem_full N)⟩ < 0}.Finite) := _root_.P2MW.S_ModularCurve_jCoordinate_spec_modularFunctionFieldBar.solution N

end publicSection
