/-
Based on Prove2Me node WeierstrassCurve.reducePoint_some
(6811c24a-05be-5b4a-b485-5b5364653347) by Claude (2026-09-05).

Proof based on Prove2Me submission 786f7348-8ae7-5e05-9544-9424c3aa433c
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_EllipticCurve_PointReduction

import Mathlib.AlgebraicGeometry.EllipticCurve.Reduction
import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Definitions.FLT.Def_P2M_Util

/-!
# Reduction of an integral affine point has residue coordinates

Theorem statement: `WeierstrassCurve.reducePoint_some` (`6811c24a-05be-5b4a-b485-5b5364653347`), by
Claude, 2026-09-05.

Proof: submission `786f7348-8ae7-5e05-9544-9424c3aa433c`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $R$ be a discrete valuation ring which is a domain, $K$ a field equipped with an $R$-algebra
structure making it a fraction field of $R$, and $W$ a Weierstrass curve over $K$ satisfying
`HasGoodReduction R`. Let $x,y \in K$ together with a proof $h$ that $(x,y)$ is a nonsingular point
of the affine curve attached to $W$, and suppose that the $\mathrm{maximalIdeal}\ R$-adic valuation
on $K$ satisfies $v(x) \le 1$ and $v(y) \le 1$, i.e. both coordinates are integral. The conclusion
asserts the existence of a proof $h'$ that $(\mathrm{reduceCoord}\ R\ x, \mathrm{reduceCoord}\ R\
y)$ is a nonsingular point of the reduced curve `W.reduction R` over the residue field of $R$, such
that `reducePoint_alt R W` applied to the affine point `.some x y h` equals the affine point `.some`
with these two coordinates and witness $h'$. Here $\mathrm{reduceCoord}\ R\ z$ is the residue in the
residue field of some $r \in R$ with $\mathrm{algebraMap}\ R\ K\ r = z$ when such $r$ exists, and
$0$ otherwise; and `reducePoint_alt` is defined by cases, sending `.some x y _` to the point with
reduced coordinates when both valuations are $\le 1$ and the reduced pair is nonsingular, and to the
zero point otherwise.

This is the specification lemma for the reduction map $W(K) \to \tilde W(k)$ on points with integral
coordinates: on such a point the map is given by reducing the coordinates, and no branch of the case
distinction in its definition is taken trivially. It is used in the construction of specialisation
homomorphisms on points and in the proof that the Galois representation attached to a curve with
good reduction at a place is unramified there.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_reducePoint_some.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_reducePoint_some

set_option autoImplicit false

open WeierstrassCurve IsDiscreteValuationRing IsLocalRing IsDedekindDomain.HeightOneSpectrum

namespace ReduceSome

theorem reducePoint_some' (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K] (W : WeierstrassCurve K) [W.HasGoodReduction R] {x y : K} (h : W.toAffine.Nonsingular x y)
    (hx : valuation K (IsDiscreteValuationRing.maximalIdeal R) x ≤ 1) (hy : valuation K (IsDiscreteValuationRing.maximalIdeal R) y ≤ 1) :
    ∃ h', reducePoint_alt R W (.some x y h) = .some (reduceCoord R x) (reduceCoord R y) h' := by
  obtain ⟨rx, hrx⟩ := exists_lift_of_le_one hx
  obtain ⟨ry, hry⟩ := exists_lift_of_le_one hy
  have hex : ∃ r : R, algebraMap R K r = x := ⟨rx, hrx⟩
  have hey : ∃ r : R, algebraMap R K r = y := ⟨ry, hry⟩

  have hcx : reduceCoord R x = residue R rx := by
    rw [reduceCoord, dite_eq_left hex]
    exact congrArg _ (IsFractionRing.injective R K (hex.choose_spec.trans hrx.symm))
  have hcy : reduceCoord R y = residue R ry := by
    rw [reduceCoord, dite_eq_left hey]
    exact congrArg _ (IsFractionRing.injective R K (hey.choose_spec.trans hry.symm))

  have heqK : ((integralModel R W).map (algebraMap R K)).toAffine.Equation
      (algebraMap R K rx) (algebraMap R K ry) := by
    have hbc : (integralModel R W).map (algebraMap R K) = W := baseChange_integralModel_eq R W
    rw [hbc, hrx, hry]
    exact h.1
  have heqR : (integralModel R W).toAffine.Equation rx ry :=
    (Affine.map_equation _ (IsFractionRing.injective R K) _ _).mp heqK

  have heqk : (reduction R W).toAffine.Equation (residue R rx) (residue R ry) :=
    heqR.map (residue R)

  have hell : (reduction R W).IsElliptic :=
    (hasGoodReduction_iff_isElliptic_reduction R).mp ‹W.HasGoodReduction R›
  have hns : (reduction R W).toAffine.Nonsingular (reduceCoord R x) (reduceCoord R y) := by
    rw [hcx, hcy]
    exact Affine.equation_iff_nonsingular.mp heqk
  have hxy : valuation K (IsDiscreteValuationRing.maximalIdeal R) x ≤ 1 ∧ valuation K (IsDiscreteValuationRing.maximalIdeal R) y ≤ 1 := ⟨hx, hy⟩
  refine ⟨hns, ?_⟩
  simp only [reducePoint_alt, dite_eq_left hxy, dite_eq_left hns]

end ReduceSome

theorem solution
    (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]
    (W : WeierstrassCurve K) [W.HasGoodReduction R] {x y : K} (h : W.toAffine.Nonsingular x y)
    (hx : IsDedekindDomain.HeightOneSpectrum.valuation K (IsDiscreteValuationRing.maximalIdeal R) x ≤ 1)
    (hy : IsDedekindDomain.HeightOneSpectrum.valuation K (IsDiscreteValuationRing.maximalIdeal R) y ≤ 1) :
    ∃ h', WeierstrassCurve.reducePoint_alt R W (.some x y h)
      = .some (WeierstrassCurve.reduceCoord R x) (WeierstrassCurve.reduceCoord R y) h' :=
  ReduceSome.reducePoint_some' R W h hx hy

end S_WeierstrassCurve_reducePoint_some
end P2MW
export P2MW.S_WeierstrassCurve_reducePoint_some (solution)

end privateSection

public section publicSection

theorem WeierstrassCurve.reducePoint_some
    (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]
    (W : WeierstrassCurve K) [W.HasGoodReduction R] {x y : K} (h : W.toAffine.Nonsingular x y)
    (hx : IsDedekindDomain.HeightOneSpectrum.valuation K (IsDiscreteValuationRing.maximalIdeal R) x ≤ 1)
    (hy : IsDedekindDomain.HeightOneSpectrum.valuation K (IsDiscreteValuationRing.maximalIdeal R) y ≤ 1) :
    ∃ h', WeierstrassCurve.reducePoint_alt R W (.some x y h)
      = .some (WeierstrassCurve.reduceCoord R x) (WeierstrassCurve.reduceCoord R y) h' := _root_.P2MW.S_WeierstrassCurve_reducePoint_some.solution R W h hx hy

end publicSection
