/-
Based on Prove2Me node WeierstrassCurve.Affine.IsogenyEndDatum.pointEnd_apply_eq_sub
(2a48382c-2930-5c17-be93-7b0083958996) by Claude (2026-09-05).

Proof based on Prove2Me submission 412fe9f9-b1d7-5d9d-ba2d-1f0ded8b5588
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_Isogeny_ConditionalCurrency

import Definitions.FLT.Def_P2M_Util

/-!
# Point endomorphism of an isogeny datum equals h(P)-h(O)

Theorem statement: `WeierstrassCurve.Affine.IsogenyEndDatum.pointEnd_apply_eq_sub`
(`2a48382c-2930-5c17-be93-7b0083958996`), by Claude, 2026-09-05.

Proof: submission `412fe9f9-b1d7-5d9d-ba2d-1f0ded8b5588`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be an algebraically closed field of characteristic $0$ and let $W$ be an affine Weierstrass
curve over $F$ which is elliptic, equipped with two structures: `GenusOnePlaceGate W`, consisting of
a bijection `pointEquivPlace` between the group $W(F)$ of points `W.Point` and the set of places of
the function field `W.FunctionField` over $F$ (a place being a proper valuation subring containing
the image of $F$ and having principal ideals) together with the assertion that every such place has
degree $1$; and `AbelTheorem W`, the assertion that a divisor of degree $0$ on `W.FunctionField` is
principal exactly when its `divisorSum`, the image of its point support under the dictionary,
vanishes. Let $D$ be an `IsogenyEndDatum` for $W$, i.e. an $F$-algebra endomorphism $\iota =
D.\iota$ of `W.FunctionField` whose underlying ring map is integral and which makes
`W.FunctionField` a finite module over itself, and assume `hN`, the push-forward norm formula along
$\iota$: for every nonzero $f$ and every divisor equal to $\operatorname{div}(f)$ upstairs, the
push-forward takes at each place $v$ downstairs the value $v(\mathrm{N}(f))$. Then for every point
$P$ the additive endomorphism `D.pointEnd hN` of `W.Point` satisfies $$D.\text{pointEnd}\,hN\,(P) =
\iota^{*}(v_P) - \iota^{*}(v_O),$$ where $v_Q$ denotes `placeOfPoint Q`, $\iota^{*}$ is
`Place.restrictAlong D.ι D.hι` (the valuation subring pulled back along $\iota$), and both places
are carried back to points by the inverse of `pointEquivPlace`; here $O$ is the zero point.

This is the rigidity statement in the conditional place-theoretic set-up: the group endomorphism of
$W(F)$ obtained by transporting push-forward of degree-zero divisors along $\iota$ through the
Abel–Jacobi dictionary is the geometric self-map $h$ determined by $\iota$ on places, corrected by
subtracting $h(O)$, so that $h$ is a translation composed with an isogeny. It is used by
[`WeierstrassCurve.Affine.IsogenyEndDatum.exists_pointEnd_eq_add`](thm.html#WeierstrassCurve.Affine.IsogenyEndDatum.exists_pointEnd_eq_add),
which passes between morphism-level identities for $\iota$ and additive identities for `pointEnd`.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Affine_IsogenyEndDatum_pointEnd_apply_eq_sub.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Affine_IsogenyEndDatum_pointEnd_apply_eq_sub

open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve

universe u

theorem solution
    {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    {W : WeierstrassCurve.Affine F} [W.IsElliptic] [GenusOnePlaceGate W] [AbelTheorem W]
    (D : IsogenyEndDatum W) (hN : NormFormulaAlong F D.ι D.hfin) (P : W.Point) :
    D.pointEnd hN P
      = (pointEquivPlace (W := W)).symm ((placeOfPoint P).restrictAlong D.ι D.hι)
        - (pointEquivPlace (W := W)).symm ((placeOfPoint (0 : W.Point)).restrictAlong D.ι D.hι) := by
  set Q : W.Point := (pointEquivPlace (W := W)).symm ((placeOfPoint P).restrictAlong D.ι D.hι) with hQ
  set Q₀ : W.Point :=
    (pointEquivPlace (W := W)).symm ((placeOfPoint (0 : W.Point)).restrictAlong D.ι D.hι) with hQ₀
  have hP : (placeOfPoint P).restrictAlong D.ι D.hι = placeOfPoint Q :=
    ((pointEquivPlace (W := W)).apply_symm_apply _).symm
  have h0 : (placeOfPoint (0 : W.Point)).restrictAlong D.ι D.hι = placeOfPoint Q₀ :=
    ((pointEquivPlace (W := W)).apply_symm_apply _).symm
  have hdiv : (Pic0.pushforwardAlongDegZero D.ι D.hι (pointDivisor P) :
      AlgebraicCurve.Divisor F W.FunctionField)
        = Finsupp.single (placeOfPoint Q) 1 - Finsupp.single (placeOfPoint Q₀) 1 := by
    rw [Pic0.coe_pushforwardAlongDegZero, coe_pointDivisor, map_sub,
      pushforwardAlong_single_eq D.ι D.hι, pushforwardAlong_single_eq D.ι D.hι, hP, h0]
  rw [IsogenyEndDatum.pointEnd_apply, pointClass, Pic0.pushforwardAlongHom_mk,
    genusOnePic0Equiv_apply, pic0ToPoint_mk, hdiv, map_sub, divisorSum_single_placeOfPoint,
    divisorSum_single_placeOfPoint, one_smul, one_smul]

end S_WeierstrassCurve_Affine_IsogenyEndDatum_pointEnd_apply_eq_sub
end P2MW
export P2MW.S_WeierstrassCurve_Affine_IsogenyEndDatum_pointEnd_apply_eq_sub (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

open WeierstrassCurve WeierstrassCurve.Affine AlgebraicCurve

universe u
theorem WeierstrassCurve.Affine.IsogenyEndDatum.pointEnd_apply_eq_sub
    {F : Type u} [Field F] [DecidableEq F] [IsAlgClosed F] [CharZero F]
    {W : WeierstrassCurve.Affine F} [W.IsElliptic] [GenusOnePlaceGate W] [AbelTheorem W]
    (D : IsogenyEndDatum W) (hN : NormFormulaAlong F D.ι D.hfin) (P : W.Point) :
    D.pointEnd hN P
      = (pointEquivPlace (W := W)).symm ((placeOfPoint P).restrictAlong D.ι D.hι)
        - (pointEquivPlace (W := W)).symm ((placeOfPoint (0 : W.Point)).restrictAlong D.ι D.hι) := _root_.P2MW.S_WeierstrassCurve_Affine_IsogenyEndDatum_pointEnd_apply_eq_sub.solution D hN P

end publicSection
