/-
Based on Prove2Me node AlgebraicCurve.RationalFunctionField.ord_ofHeightOneSpectrum_eq_neg_log
(2bd8c823-9b6f-5635-a092-45542aa65bd1) by Claude (2026-09-05).

Proof based on Prove2Me submission ec2907c6-cfaf-5459-9320-98fa7771fe1b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.FieldTheory.RatFunc.Basic
public import Definitions.FLT.Def_AlgebraicCurve_DivisorClassGroup

import Theorems.FLT.Thm_AlgebraicCurve_Place_ord_eq_neg_log_of_valuationSubring_eq
import Definitions.FLT.Def_P2M_Util

/-!
# Order at a finite place of K(t) equals the adic valuation

Theorem statement: `AlgebraicCurve.RationalFunctionField.ord_ofHeightOneSpectrum_eq_neg_log`
(`2bd8c823-9b6f-5635-a092-45542aa65bd1`), by Claude, 2026-09-05.

Proof: submission `ec2907c6-cfaf-5459-9320-98fa7771fe1b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, let $w$ be a height-one prime of the polynomial ring $K[X]$, let $p \in K[X]$ be
nonzero with $w.\mathrm{asIdeal} = (p)$, and let $f \in \mathrm{RatFunc}\,K$ be nonzero. Attached to
$w$ is the place `Place.ofHeightOneSpectrum w` of $\mathrm{RatFunc}\,K$ over $K$, namely the
$K$-subalgebra-containing valuation subring of $\mathrm{RatFunc}\,K$ cut out by the
$\mathbb{Z}^{m0}$-valued $w$-adic valuation $w.\mathrm{valuation}\,(\mathrm{RatFunc}\,K)$, together
with the facts that this subring is not all of $\mathrm{RatFunc}\,K$ and is a principal ideal ring.
For a place $v$, $\mathrm{ord}\,f$ is defined as $-\mathrm{log}$ of the value at $f$ of the adic
valuation intrinsically associated with $v$ (the valuation of the height-one prime of the valuation
ring of $v$). The assertion is that for this place the intrinsic normalised order of $f$ agrees with
the extrinsic one: $$\mathrm{ord}\,f =
-\mathrm{log}\bigl(w.\mathrm{valuation}\,(\mathrm{RatFunc}\,K)\,f\bigr),$$ an equality of integers,
i.e. $\mathrm{ord}\,f$ is the multiplicity of $p$ in $f$.

This identifies the normalised order function of a finite place of the rational function field
$K(t)$, defined through the place's own valuation ring, with the exponent of the corresponding
$w$-adic valuation on $\mathrm{RatFunc}\,K$; it is the computational form in which orders at finite
places are used. It is cited by
[`AlgebraicCurve.RationalFunctionField.ord_ofHeightOneSpectrum_of_span`](thm.html#AlgebraicCurve.RationalFunctionField.ord_ofHeightOneSpectrum_of_span)
and by
[`AlgebraicCurve.RationalFunctionField.trace_localResidue_finitePlace_div_pow_eq_zero`](thm.html#AlgebraicCurve.RationalFunctionField.trace_localResidue_finitePlace_div_pow_eq_zero).

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_AlgebraicCurve_RationalFunctionField_ord_ofHeightOneSpectrum_eq_neg_log.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_AlgebraicCurve_RationalFunctionField_ord_ofHeightOneSpectrum_eq_neg_log
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation"
p2m_attr_erase "simp" "AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint"

open AlgebraicCurve
open IsDedekindDomain WithZero IsLocalRing
open scoped Polynomial

theorem solution {K : Type*} [Field K] (w : IsDedekindDomain.HeightOneSpectrum (Polynomial K)) {p : Polynomial K} (hp : p ≠ 0) (hw : w.asIdeal = Ideal.span {p}) {f : RatFunc K} (hf : f ≠ 0) : (Place.ofHeightOneSpectrum (K := K) (F := RatFunc K) w).ord f = -WithZero.log (w.valuation (RatFunc K) f) := by
  have hval : w.valuation (RatFunc K) (algebraMap K[X] (RatFunc K) p) = exp (-1 : ℤ) := by
    have h := w.intValuation_singleton hp hw
    rw [← h]
    simpa using w.valuation_of_algebraMap (K := RatFunc K) p
  exact (Place.ofHeightOneSpectrum (K := K) (F := RatFunc K)
    w).ord_eq_neg_log_of_valuationSubring_eq (w.valuation (RatFunc K)) rfl hval hf

end S_AlgebraicCurve_RationalFunctionField_ord_ofHeightOneSpectrum_eq_neg_log
end P2MW
export P2MW.S_AlgebraicCurve_RationalFunctionField_ord_ofHeightOneSpectrum_eq_neg_log (solution)

end privateSection

public section publicSection


open AlgebraicCurve
theorem AlgebraicCurve.RationalFunctionField.ord_ofHeightOneSpectrum_eq_neg_log {K : Type*} [Field K] (w : IsDedekindDomain.HeightOneSpectrum (Polynomial K)) {p : Polynomial K} (hp : p ≠ 0) (hw : w.asIdeal = Ideal.span {p}) {f : RatFunc K} (hf : f ≠ 0) : (Place.ofHeightOneSpectrum (K := K) (F := RatFunc K) w).ord f = -WithZero.log (w.valuation (RatFunc K) f) := _root_.P2MW.S_AlgebraicCurve_RationalFunctionField_ord_ofHeightOneSpectrum_eq_neg_log.solution w hp hw hf

end publicSection
