/-
Based on Prove2Me node ModularCurve.finiteDimensional_adjoin_coeffEmb_jq_full
(7ced3fad-1396-570b-88c4-c0308909da0f) by Claude (2026-09-05).

Proof based on Prove2Me submission 91748df3-063d-5092-8536-d3cb4ce44c55
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_LaurentCoeff
public import Definitions.FLT.Def_ModularCurve_QAdicPlace

import Definitions.FLT.Def_ModularCurve_X0
import Theorems.FLT.Thm_ModularCurve_relfinrank_laurentBaseChange_modularFunctionFieldFull
import Theorems.FLT.Thm_ModularCurve_relfinrank_full_eq_dedekindPsi
import Theorems.FLT.Thm_ModularCurve_dedekindPsi_pos
import Definitions.FLT.Def_P2M_Util

/-!
# Finiteness of the base-changed level-N function field over L(j)

Theorem statement: `ModularCurve.finiteDimensional_adjoin_coeffEmb_jq_full`
(`7ced3fad-1396-570b-88c4-c0308909da0f`), by Claude, 2026-09-05.

Proof: submission `91748df3-063d-5092-8536-d3cb4ce44c55`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $L$ be a field equipped with a $\mathbb{Q}$-algebra structure and let $N$ be a natural number
with $N \neq 0$. Inside $\mathrm{LaurentSeries}\,\mathbb{Q}$ let $\mathtt{jq}$ be the Laurent series
$q^{-1}$ times the image of the integral power series $\mathtt{jNum}$ under $\mathbb{Z} \to
\mathbb{Q}$ (the $q$-expansion of the $j$-invariant), and let $\mathtt{modularFunctionFieldFull}\ N$
be the intermediate field of $\mathrm{LaurentSeries}\,\mathbb{Q}$ obtained by adjoining to
$\mathbb{Q}$ all the expansions $\mathtt{qExpand}\ \mathbb{Q}\ d\ \mathtt{jq}$ for nonzero divisors
$d$ of $N$. Let $\mathtt{coeffEmb}\ L$ be the ring embedding $\mathrm{LaurentSeries}\,\mathbb{Q} \to
\mathrm{LaurentSeries}\,L$ acting on coefficients through $\mathbb{Q} \to L$, and let $E =
\mathtt{laurentBaseChange}\ L\ (\mathtt{modularFunctionFieldFull}\ N)$ be the intermediate field of
$\mathrm{LaurentSeries}\,L$ generated over $L$ by the image of $\mathtt{modularFunctionFieldFull}\
N$ under this embedding. The element $\mathtt{coeffEmb}\ L\ \mathtt{jq}$ lies in $E$, and the
assertion is that $E$ is finite-dimensional as a vector space over the intermediate field of $E$
generated over $L$ by that single element. Only finiteness is asserted, not the value of the degree.

This is the statement that the function field of $X_0(N)$, realised as a field of formal
$q$-expansions with coefficients extended from $\mathbb{Q}$ to an arbitrary field $L$ of
characteristic zero, is a finite extension of $L(j)$; taking $L = \overline{\mathbb{Q}}$ or $L =
\mathbb{C}$ gives the cases used later. It underlies the separability statement proved alongside it
and is invoked throughout the $q$-expansion model of $X_0(N)$, where finiteness over $L(j)$ is what
makes orders of differentials, place-reduction dictionaries and residue computations available.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full
p2m_attr_erase "instance" "ModularCurve.instIsDomainTensorProduct AlgebraicClosure.Rat.isGalois ModularCurve.instSMulAlgEquivRatPic0SubtypeLaurentSeriesMemIntermediateFieldLaurentBaseChange ModularCurve.instDistribMulActionAlgEquivRatPic0SubtypeLaurentSeriesMemIntermediateFieldLaurentBaseChange AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instDistribMulActionSubtypeProdRingAutMemSubgroupDivisor AlgebraicCurve.Pic0.instModuleZModTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instDistribMulActionTorsion AlgebraicCurve.SemilinearAut.instSMulSubtypeProdRingAutMemSubgroupPic0 AlgebraicCurve.SemilinearAut.instSMulTorsion AlgebraicCurve.SemilinearAut.instMulActionSubtypeProdRingAutMemSubgroupPlace AlgebraicCurve.SemilinearAut.instSMulCommClassZModTorsion AlgebraicCurve.SemilinearAut.instMulSemiringActionSubtypeProdRingAutMemSubgroup AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy ModularCurve.PhiGen.instNeZeroPhiGenCosetA"
p2m_attr_erase "simp" "ModularCurve.coe_baseChangeEquiv_apply ModularCurve.baseChangeHom_tmul ModularCurve.jqNModC_one ModularCurve.coe_cuspidalDivisor₀ ModularCurve.baseAut_arithmeticGalois ModularCurve.JZero.torsionGaloisRep_apply ModularCurve.coe_arithmeticRingAut_apply ModularCurve.toRingAut_arithmeticGalois AlgebraicCurve.SemilinearAut.toRingAut_inv AlgebraicCurve.SemilinearAut.smul_def AlgebraicCurve.SemilinearAut.smul_single AlgebraicCurve.SemilinearAut.smul_toValuationSubring AlgebraicCurve.SemilinearAut.baseAut_inv AlgebraicCurve.SemilinearAut.baseAut_ofAlgAut AlgebraicCurve.SemilinearAut.toRingAut_ofAlgAut AlgebraicCurve.SemilinearAut.torsionRep_apply AlgebraicCurve.SemilinearAut.toRingAut_one AlgebraicCurve.SemilinearAut.deg_smul AlgebraicCurve.SemilinearAut.degree_smul AlgebraicCurve.SemilinearAut.coe_degZeroSMulHom AlgebraicCurve.SemilinearAut.baseAut_mul AlgebraicCurve.SemilinearAut.coe_smulValuationSubringEquiv_apply AlgebraicCurve.SemilinearAut.baseAut_one AlgebraicCurve.SemilinearAut.ofAlgAut_smul AlgebraicCurve.SemilinearAut.coe_torsion_smul AlgebraicCurve.SemilinearAut.toRingAut_mul AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply"
p2m_attr_erase "simp" "ModularCurve.evalAtJqN_X ModularCurve.qTwistFun_coeff ModularCurve.swapBivar_C_X ModularCurve.PhiGen.cosetA_succ ModularCurve.qTwist_coeff ModularCurve.PhiGen.cosetB_zero ModularCurve.PhiGen.cosetA_zero ModularCurve.qTwist_single ModularCurve.swapBivar_X ModularCurve.aeval_toRingHom_X ModularCurve.PhiGen.cosetB_succ ModularForm.val_heckeDiagMatrix ModularForm.heckeU_zero ModularForm.heckeU_zero_left ModularForm.heckeT_zero ModularForm.val_heckeMatrix ModularForm.heckeMatrix_zero ModularForm.heckeT_zero_left ModularForm.heckeDiagMatrix_zero ModularForm.val_upperTriangularGL ModularCurve.eisensteinNumerator_nineteen ModularCurve.eisensteinNumerator_seventeen ModularCurve.eisensteinNumerator_eleven ModularCurve.eisensteinNumerator_five ModularCurve.eisensteinNumerator_seven ModularCurve.eisensteinNumerator_twentythree ModularCurve.eisensteinNumerator_thirteen ModularCurve.constantCoeff_dedekindEtaUnitQ"

p2m_open "ModularCurve~modularFunctionFieldBar P2MW.S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full.ModularCurve"

namespace ModularCurve
p2m_export "ModularCurve" "jq dedekindPsi modularFunctionFieldFull coeffEmb laurentBaseChange coeffEmb_mem_laurentBaseChange relfinrank_laurentBaseChange_modularFunctionFieldFull jq_mem_full relfinrank_full_eq_dedekindPsi dedekindPsi_pos"
end ModularCurve
p2m_open_scoped "ModularCurve" in
private theorem ModularCurve.finiteDimensional_adjoin_coeffEmb_jq_full (L : Type*) [Field L] [Algebra ℚ L] (N : ℕ) [NeZero N] : FiniteDimensional (IntermediateField.adjoin L ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} : Set (laurentBaseChange L (modularFunctionFieldFull N)))) (laurentBaseChange L (modularFunctionFieldFull N)) := by
  have hmap : (IntermediateField.adjoin L
        ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} :
          Set (laurentBaseChange L (modularFunctionFieldFull N)))).map
        (laurentBaseChange L (modularFunctionFieldFull N)).val =
      IntermediateField.adjoin L ({coeffEmb L jq} : Set (LaurentSeries L)) := by
    have h := IntermediateField.adjoin_map (F := L) (E := laurentBaseChange L (modularFunctionFieldFull N))
      (S := ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} :
        Set (laurentBaseChange L (modularFunctionFieldFull N))))
      (laurentBaseChange L (modularFunctionFieldFull N)).val
    rw [Set.image_singleton] at h
    exact h
  have hcomap : (IntermediateField.adjoin L ({coeffEmb L jq} : Set (LaurentSeries L))).comap
        (laurentBaseChange L (modularFunctionFieldFull N)).val =
      IntermediateField.adjoin L
        ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} :
          Set (laurentBaseChange L (modularFunctionFieldFull N))) := by
    rw [← hmap, IntermediateField.comap_map]
  have hrank : Module.finrank
      ((IntermediateField.adjoin L ({coeffEmb L jq} : Set (LaurentSeries L))).comap
        (laurentBaseChange L (modularFunctionFieldFull N)).val)
      (laurentBaseChange L (modularFunctionFieldFull N)) = dedekindPsi N := by
    rw [IntermediateField.finrank_comap, IntermediateField.fieldRange_val,
      relfinrank_laurentBaseChange_modularFunctionFieldFull, relfinrank_full_eq_dedekindPsi]
  have hfin : FiniteDimensional
      ((IntermediateField.adjoin L ({coeffEmb L jq} : Set (LaurentSeries L))).comap
        (laurentBaseChange L (modularFunctionFieldFull N)).val)
      (laurentBaseChange L (modularFunctionFieldFull N)) :=
    Module.finite_of_finrank_pos (by rw [hrank]; exact dedekindPsi_pos N (NeZero.ne N))
  rwa [hcomap] at hfin

p2m_open_scoped "ModularCurve" in
set_option synthInstance.maxHeartbeats 400000 in
private theorem ModularCurve.isSeparable_adjoin_coeffEmb_jq_full (L : Type*) [Field L] [Algebra ℚ L] (N : ℕ) [NeZero N] : Algebra.IsSeparable (IntermediateField.adjoin L ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} : Set (laurentBaseChange L (modularFunctionFieldFull N)))) (laurentBaseChange L (modularFunctionFieldFull N)) := by
  set X : IntermediateField L (laurentBaseChange L (modularFunctionFieldFull N)) :=
    IntermediateField.adjoin L ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} :
      Set (laurentBaseChange L (modularFunctionFieldFull N))) with hX
  have : FiniteDimensional X (laurentBaseChange L (modularFunctionFieldFull N)) :=
    finiteDimensional_adjoin_coeffEmb_jq_full L N
  have : CharZero L := charZero_of_injective_algebraMap (algebraMap ℚ L).injective
  have : CharZero X := charZero_of_injective_algebraMap (algebraMap L X).injective
  infer_instance

p2m_open "ModularCurve~modularFunctionFieldBar" in open _root_.P2MW.S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full.ModularCurve in

theorem solution (L : Type*) [Field L] [Algebra ℚ L] (N : ℕ) [NeZero N] : FiniteDimensional (IntermediateField.adjoin L ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} : Set (laurentBaseChange L (modularFunctionFieldFull N)))) (laurentBaseChange L (modularFunctionFieldFull N)) :=
  ModularCurve.finiteDimensional_adjoin_coeffEmb_jq_full L N

end S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full
end P2MW
export P2MW.S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.finiteDimensional_adjoin_coeffEmb_jq_full (L : Type*) [Field L] [Algebra ℚ L] (N : ℕ) [NeZero N] : FiniteDimensional (IntermediateField.adjoin L ({⟨coeffEmb L jq, coeffEmb_mem_laurentBaseChange L (jq_mem_full N)⟩} : Set (laurentBaseChange L (modularFunctionFieldFull N)))) (laurentBaseChange L (modularFunctionFieldFull N)) := _root_.P2MW.S_ModularCurve_finiteDimensional_adjoin_coeffEmb_jq_full.solution L N

end publicSection
