/-
Based on Prove2Me node ModularForm.exists_qExpansion_eq_aeval_mul_pow_levelOne
(dc26842e-3c37-5ba0-aaba-e83bcd87e7b3) by Claude (2026-09-05).

Proof based on Prove2Me submission 74ab1c20-fb2b-5f2f-88be-47b82744a75a
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.LevelOne.DimensionFormula
public import Mathlib.RingTheory.LaurentSeries

import Definitions.FLT.Def_P2M_Util

/-!
# Level one: weight 12N forms are P(j) Δ^N in ℂ((q))

Theorem statement: `ModularForm.exists_qExpansion_eq_aeval_mul_pow_levelOne`
(`dc26842e-3c37-5ba0-aaba-e83bcd87e7b3`), by Claude, 2026-09-05.

Proof: submission `74ab1c20-fb2b-5f2f-88be-47b82744a75a`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $N$ be a natural number and let $F$ be a modular form of weight $12N$ for the full modular group
$\mathrm{SL}_2(\mathbb{Z})$ (an element of `ModularForm 𝒮ℒ (12 * (N : ℤ))`, the weight being the
integer $12N$). The assertion is that there exists a polynomial $P \in \mathbb{C}[X]$ whose
`natDegree` is at most $N$ such that, after the canonical embedding of power series into Laurent
series $\mathbb{C}((q))$, the $q$-expansion of $F$ at width $1$ satisfies $$\widetilde{F} =
P\bigl(\widetilde{E_4}^{\,3}/\widetilde{\Delta}\bigr)\cdot \widetilde{\Delta}^{\,N},$$ where
$\widetilde{\,\cdot\,}$ denotes `qExpansion 1` of the underlying function on the upper half-plane,
$E_4$ is the normalised weight-$4$ Eisenstein series `ModularForm.E₄`, $\Delta$ is
`ModularForm.discriminant`, the quotient and the $N$-th power are formed in the field of Laurent
series, and $P$ is evaluated at that quotient through the $\mathbb{C}$-algebra structure of
$\mathbb{C}((q))$. Thus the bound on $P$ is on its natural degree, and the identity is an identity
of Laurent series, not of modular forms.

This is the level-one structure statement in $q$-expansion form: every weight-$12N$ form for
$\mathrm{SL}_2(\mathbb{Z})$ is a polynomial of degree at most $N$ in $j = E_4^3/\Delta$ multiplied
by $\Delta^N$. It is used in the integrality arguments for $q$-expansion coefficients on modular
curves, for instance in the results establishing integrality of coefficient data over an algebra
generated by $j$-series data and in the Hasse-polynomial descent step.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularForm_exists_qExpansion_eq_aeval_mul_pow_levelOne.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularForm_exists_qExpansion_eq_aeval_mul_pow_levelOne

open UpperHalfPlane
open scoped MatrixGroups

theorem solution (N : ℕ) (F : ModularForm 𝒮ℒ (12 * (N : ℤ))) : ∃ P : Polynomial ℂ, P.natDegree ≤ N ∧ ((qExpansion 1 (F : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) = Polynomial.aeval (((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ^ 3 / ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) P * ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ^ N := by
  induction N with
  | zero =>
    obtain ⟨c, hc⟩ := ModularFormClass.levelOne_weight_zero_const
      (ModularForm.mcast (show (12 * ((0 : ℕ) : ℤ)) = 0 by simp) F)
    rw [ModularForm.coe_mcast] at hc
    have hconst : Function.const ℍ c = ⇑(c • (1 : ModularForm 𝒮ℒ 0)) := by
      funext τ
      simp
    have hq : qExpansion 1 (F : ℍ → ℂ) = c • (1 : PowerSeries ℂ) := by
      rw [hc, hconst, FunLike.coe_smul,
        ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
        ModularForm.qExpansion_one]
    have hbridge : (algebraMap ℂ (LaurentSeries ℂ)) c
        = ((PowerSeries.C c : PowerSeries ℂ) : LaurentSeries ℂ) := by
      rw [HahnSeries.algebraMap_apply', PowerSeries.algebraMap_eq]
    refine ⟨Polynomial.C c, by simp, ?_⟩
    rw [hq, PowerSeries.smul_eq_C_mul, mul_one, Polynomial.aeval_C, pow_zero, mul_one, hbridge]
  | succ N ih =>
    have hw : ((3 * (N + 1) : ℕ) : ℤ) * 4 = 12 * ((N + 1 : ℕ) : ℤ) := by push_cast; ring
    set c : ℂ := (qExpansion 1 (F : ℍ → ℂ)).coeff 0 with hcdef
    set Epow : ModularForm 𝒮ℒ (12 * ((N + 1 : ℕ) : ℤ)) :=
      ModularForm.mcast hw (ModularForm.E₄.pow (3 * (N + 1))) with hEpow
    set G : ModularForm 𝒮ℒ (12 * ((N + 1 : ℕ) : ℤ)) := F - c • Epow with hGdef
    have hE40 : (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ)).coeff 0 = 1 :=
      EisensteinSeries.E_qExpansion_coeff_zero (by norm_num) ⟨2, rfl⟩
    have hGq : qExpansion 1 (G : ℍ → ℂ) = qExpansion 1 (F : ℍ → ℂ)
        - PowerSeries.C c * (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ)) ^ (3 * (N + 1)) := by
      rw [hGdef, FunLike.coe_sub, ModularForm.qExpansion_sub one_pos one_mem_strictPeriods_SL,
        FunLike.coe_smul, ModularForm.qExpansion_smul one_pos one_mem_strictPeriods_SL,
        hEpow, ModularForm.qExpansion_mcast,
        ModularForm.qExpansion_pow one_pos one_mem_strictPeriods_SL, PowerSeries.smul_eq_C_mul]
    have hpow0 : ((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ)) ^ (3 * (N + 1))).coeff 0 = 1 := by
      rw [PowerSeries.coeff_zero_eq_constantCoeff_apply, map_pow,
        ← PowerSeries.coeff_zero_eq_constantCoeff_apply, hE40, one_pow]
    have hCc : (PowerSeries.C c
        * (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ)) ^ (3 * (N + 1))).coeff 0 = c := by
      rw [PowerSeries.coeff_zero_eq_constantCoeff_apply, map_mul, PowerSeries.constantCoeff_C,
        ← PowerSeries.coeff_zero_eq_constantCoeff_apply, hpow0, mul_one]
    have h0 : (qExpansion 1 (G : ℍ → ℂ)).coeff 0 = 0 := by
      rw [hGq, map_sub, hCc, ← hcdef, sub_self]
    have hkey := ModularForm.qExpansion_eq_qExpansion_discriminant_mul G h0
    have hw2 : (12 * ((N + 1 : ℕ) : ℤ)) - 12 = 12 * ((N : ℕ) : ℤ) := by push_cast; ring
    obtain ⟨P', hdeg', hP'⟩ :=
      ih (ModularForm.mcast hw2 (CuspForm.discriminantEquiv (ModularForm.toCuspForm G h0)))
    rw [ModularForm.coe_mcast] at hP'
    refine ⟨Polynomial.C c * Polynomial.X ^ (N + 1) + P', ?_, ?_⟩
    · exact Polynomial.natDegree_add_le_of_degree_le
        (Polynomial.natDegree_C_mul_X_pow_le c (N + 1)) (hdeg'.trans (Nat.le_succ N))
    · have hsum : qExpansion 1 (ModularForm.discriminant : ℍ → ℂ)
          * qExpansion 1 (CuspForm.discriminantEquiv (ModularForm.toCuspForm G h0) : ℍ → ℂ)
          + PowerSeries.C c * (qExpansion 1 (ModularForm.E₄ : ℍ → ℂ)) ^ (3 * (N + 1))
          = qExpansion 1 (F : ℍ → ℂ) := by
        rw [← hkey]
        exact eq_sub_iff_add_eq.mp hGq
      have hL : ((qExpansion 1 (F : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)
          = ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)
            * ((qExpansion 1 (CuspForm.discriminantEquiv (ModularForm.toCuspForm G h0) : ℍ → ℂ) :
                PowerSeries ℂ) : LaurentSeries ℂ)
            + ((PowerSeries.C c : PowerSeries ℂ) : LaurentSeries ℂ)
              * ((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)
                ^ (3 * (N + 1)) := by
        rw [← hsum]
        push_cast
        ring
      rw [hL, hP']
      have hΔ0 : qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) ≠ 0 := by
        intro h
        simpa [h] using ModularForm.discriminant_qExpansion_coeff_one
      have hΔL0 : ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) :
          LaurentSeries ℂ) ≠ 0 := by
        rw [Ne, ← PowerSeries.coe_zero]
        exact fun h => hΔ0 (HahnSeries.ofPowerSeries_injective h)
      have hsplit : (((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ^ 3)
            ^ (N + 1)
          = (((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ^ 3
              / ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ))
              ^ (N + 1)
            * ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)
              ^ (N + 1) := by
        rw [← mul_pow, div_mul_cancel₀ _ hΔL0]
      have hbridge : (algebraMap ℂ (LaurentSeries ℂ)) c
          = ((PowerSeries.C c : PowerSeries ℂ) : LaurentSeries ℂ) := by
        rw [HahnSeries.algebraMap_apply', PowerSeries.algebraMap_eq]
      rw [pow_mul, hsplit, map_add, map_mul, Polynomial.aeval_C, Polynomial.aeval_X_pow, hbridge]
      ring

end S_ModularForm_exists_qExpansion_eq_aeval_mul_pow_levelOne
end P2MW
export P2MW.S_ModularForm_exists_qExpansion_eq_aeval_mul_pow_levelOne (solution)

end privateSection

public section publicSection


open UpperHalfPlane
open scoped MatrixGroups
theorem ModularForm.exists_qExpansion_eq_aeval_mul_pow_levelOne (N : ℕ) (F : ModularForm 𝒮ℒ (12 * (N : ℤ))) : ∃ P : Polynomial ℂ, P.natDegree ≤ N ∧ ((qExpansion 1 (F : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) = Polynomial.aeval (((qExpansion 1 (ModularForm.E₄ : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ^ 3 / ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ)) P * ((qExpansion 1 (ModularForm.discriminant : ℍ → ℂ) : PowerSeries ℂ) : LaurentSeries ℂ) ^ N := _root_.P2MW.S_ModularForm_exists_qExpansion_eq_aeval_mul_pow_levelOne.solution N F

end publicSection
