/-
Based on Prove2Me node ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar
(203f466e-501a-57ea-b9c6-211b1bfca7d2) by Claude (2026-09-05).

Proof based on Prove2Me submission 528ef3a1-b8f8-5b9e-b204-2d42ff3375ce
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_ArithmeticGalois
public import Definitions.FLT.Def_ModularCurve_PhiGen

import Theorems.FLT.Thm_ModularCurve_hasPrincipalDivisors_laurentBaseChange_modularFunctionFieldFull
import Definitions.FLT.Def_P2M_Util

/-!
# Principal divisors on the function field of X₀(N) over ℚ̄

Theorem statement: `ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar`
(`203f466e-501a-57ea-b9c6-211b1bfca7d2`), by Claude, 2026-09-05.

Proof: submission `528ef3a1-b8f8-5b9e-b204-2d42ff3375ce`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Fix a natural number $N$ with $N \neq 0$, and assume `ModularPolynomialFamily`: for every prime
$\ell$ (nonzero) there is a datum consisting of a polynomial $\Phi \in \mathbb{Z}[X][Y]$ that is
monic, has degree equal to `dedekindPsi` $\ell$, satisfies $\Phi(j, j_\ell) = 0$ when evaluated by
`evalAtJ` on the coefficients and at the Laurent series `jqN` $\ell$, and is symmetric in the sense
that for all Laurent series $x, y$ over $\mathbb{Q}$ the two evaluations of $\Phi$ obtained by
substituting $x$ into the coefficients and $y$ into the outer variable, and vice versa, agree. The
conclusion is `HasPrincipalDivisors` for the field extension $\overline{\mathbb{Q}} \subseteq$
`modularFunctionFieldBar` $N$, the latter being the subfield of $\overline{\mathbb{Q}}((q))$
generated over $\overline{\mathbb{Q}}$ by the coefficientwise image of `modularFunctionFieldFull`
$N$, itself the subfield of $\mathbb{Q}((q))$ generated over $\mathbb{Q}$ by `divisorExpansions`
$N$. Concretely: for every nonzero $f$ in that field there is a finitely supported integer-valued
function $D$ on the places of the extension (valuation subrings of the Laurent series field
containing $\overline{\mathbb{Q}}$, proper, and principal ideal rings) with $D(v) =
\operatorname{ord}_v(f)$ for every place $v$, and with $\sum_v D(v) \deg(v) = 0$.

This is the statement that the divisor of a nonzero function on $X_0(N)$ over
$\overline{\mathbb{Q}}$ is a well-defined finitely supported divisor of degree zero — the classical
degree-zero theorem for principal divisors in an algebraic function field, here for the
$q$-expansion model $\overline{\mathbb{Q}}(j(q^d) : d \mid N)$ whose degree-zero divisor class group
plays the role of $J_0(N)(\overline{\mathbb{Q}})$. It supplies the `HasPrincipalDivisors` instance
assumed by the statements about places, specialisations and Hecke correspondences on this function
field.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar
p2m_attr_erase "instance" "AlgebraicCurve.Place.instIsPrimeCenter AlgebraicCurve.Place.instIsFractionRingIntegralClosureAt AlgebraicCurve.Place.instIsTorsionFreeSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.Place.instIsDedekindDomainIntegralClosureAt AlgebraicCurve.Place.instFiniteSubtypeMemValuationSubringToValuationSubringIntegralClosureAt AlgebraicCurve.instFundamentalIdentityOfSumRamificationInertia AlgebraicCurve.Place.instIsScalarTowerResidueFieldRestrictPushforward AlgebraicCurve.Place.instAlgebraResidueFieldRestrictPushforward AlgebraicCurve.Place.instIsLocalHomRestrictInclusion AlgebraicCurve.IsCurveOver.instNontrivialKaehler AlgebraicCurve.IsCurveOver.instFreeKaehler AlgebraicCurve.IsCurveOver.toHasPrincipalDivisors AlgebraicCurve.IsCurveOver.instFiniteResidue AlgebraicCurve.Place.instIsRankOneDiscreteWithZeroMultiplicativeIntAdicValuation AlgebraicCurve.Place.instIsTrivialOnWithZeroMultiplicativeIntAdicValuation instDecEqAlgebraicClosureRat WeierstrassCurve.Affine.Point.instDistribMulActionAlgEquiv WeierstrassCurve.Affine.Point.instModuleZModTorsionBy WeierstrassCurve.Affine.Point.instSMulTorsionBy WeierstrassCurve.Affine.Point.instDistribMulActionTorsionBy WeierstrassCurve.Affine.Point.instSMulAlgEquiv WeierstrassCurve.Affine.Point.instSMulCommClassAlgEquivZModTorsionBy"
p2m_attr_erase "simp" "ModularCurve.jqNModC_one AlgebraicCurve.Place.placeOfPrime_toValuationSubring AlgebraicCurve.Place.mem_fiberOver AlgebraicCurve.Place.fiberEquiv_symm_apply AlgebraicCurve.Place.fiberEquiv_apply AlgebraicCurve.Place.centerHeightOneSpectrum_asIdeal AlgebraicCurve.Divisor.mapRestrict_single AlgebraicCurve.Divisor.pushforward_single AlgebraicCurve.Place.coe_restrictInclusion AlgebraicCurve.Place.mem_fiber AlgebraicCurve.Place.restrict_toValuationSubring AlgebraicCurve.Divisor.degree_pushforward AlgebraicCurve.Place.restrictResidueMap_residue AlgebraicCurve.Pic0.coe_pushforwardDegZeroHom AlgebraicCurve.Pic0.coe_pullbackDegZeroHom AlgebraicCurve.IsFrobeniusEndo.frobNormRingHom_apply ModularCurve.frobeniusPushforwardGeomLevelPic0_mk ModularCurve.coe_frobeniusGeomLevelEquiv_apply ModularCurve.coe_frobeniusPushforwardGeomLevelDegZero ModularCurve.heckeFibreGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusGeomLevel_apply_coe ModularCurve.frobeniusPullbackGeomLevelPic0OfIsCurveOver_mk ModularCurve.coe_heckeFibreGeomLevelDegZero ModularCurve.coe_frobeniusPullbackGeomLevelDegZero ModularCurve.frobeniusPullbackGeomLevelPic0_mk ModularCurve.frobeniusPullbackGeomLevel_single ModularCurve.heckeFibreGeomLevelPic0_mk ModularCurve.frobeniusPushforwardGeomLevelPic0OfIsCurveOver_mk ModularCurve.frobeniusPushforwardGeomLevel_single ModularCurve.qExpandAlgC_apply AlgebraicCurve.Place.congrEquiv_symm_apply AlgebraicCurve.RationalFunctionField.heightOneSpectrumOfIrreducible_asIdeal AlgebraicCurve.Place.congrRingEquiv_toValuationSubring AlgebraicCurve.Place.congrEquiv_apply AlgebraicCurve.Place.coe_comapSymmRingEquiv_apply AlgebraicCurve.RationalFunctionField.deg_placeOfPoint AlgebraicCurve.Divisor.degree_pushforwardAlong AlgebraicCurve.Pic0.coe_degZeroCorrespondence AlgebraicCurve.Place.mem_fiberAlong AlgebraicCurve.coe_frobeniusPushforwardDegZero"
p2m_attr_erase "simp" "AlgebraicCurve.IsFrobeniusEndo.coe_frobeniusPullbackDegZero ModularCurve.reduceModBivar_C_X ModularCurve.laurentMap_coeff ModularCurve.reduceModBivar_X ModularCurve.laurentMap_single ModularCurve.evalAtJInt_X ModularCurve.evalAtJMod_X ModularCurve.jqNMod_one ModularCurve.aeval_heckeGen ModularCurve.coe_mTorsionGaloisRep_apply ModularCurve.eisensteinSystem_of_dvd ModularCurve.eisensteinSystem_of_not_dvd FreyPackage.mk.sizeOf_spec FreyPackage.mk.injEq WeierstrassCurve.Affine.Point.galoisRepModuleEnd_apply"

noncomputable section
open IntermediateField

open ModularCurve AlgebraicCurve

theorem solution (hΦ : ModularPolynomialFamily) (N : ℕ) [NeZero N] :
    HasPrincipalDivisors (AlgebraicClosure ℚ) (modularFunctionFieldBar N) :=
  hasPrincipalDivisors_laurentBaseChange_modularFunctionFieldFull (AlgebraicClosure ℚ) hΦ N

end

end S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar
end P2MW
export P2MW.S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar (solution)

end privateSection

public section publicSection


open ModularCurve AlgebraicCurve
theorem ModularCurve.hasPrincipalDivisors_modularFunctionFieldBar (hΦ : ModularPolynomialFamily) (N : ℕ) [NeZero N] :
    HasPrincipalDivisors (AlgebraicClosure ℚ) (modularFunctionFieldBar N) := _root_.P2MW.S_ModularCurve_hasPrincipalDivisors_modularFunctionFieldBar.solution hΦ N

end publicSection
