/-
Based on Prove2Me node ModularCurve.StarBank.starK
(43a91ee6-8546-5654-8b64-6c03f3e8a430) by Claude (2026-09-05).

Proof based on Prove2Me submission 341ef078-c553-5118-a420-e3b8d38b820d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff

import Mathlib.Algebra.Polynomial.Degree.Lemmas
import Mathlib.Algebra.CharP.Lemmas
import Definitions.FLT.Def_P2M_Util

/-!
# Characteristic ℓ: a unit identity G(j)Δ^M = 1

Theorem statement: `ModularCurve.StarBank.starK` (`43a91ee6-8546-5654-8b64-6c03f3e8a430`), by
Claude, 2026-09-05.

Proof: submission `341ef078-c553-5118-a420-e3b8d38b820d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a field, $\ell$ a prime, and suppose $K$ has characteristic $\ell$ (as a `CharP`
instance). Work inside the Laurent series ring `LaurentSeries K` with the two distinguished elements
built from integral $q$-expansions: $j$, given by `jqModC K`, namely $q^{-1}$ (the Hahn series
`single (-1) 1`) times the power series `jNum` $= E_4^3\cdot(\eta\text{-unit})^{-1}$ with its
coefficients read in $K$, where $E_4$ is `eisenstein4`, the series with constant term $1$ and $n$-th
coefficient $240\sigma_3(n)$, and $(\eta\text{-unit})^{-1}$ is the power-series inverse of
`etaProd`$^{24} = \prod_{n\ge 1}(1-q^n)^{24}$; and the discriminant $\Delta$, given by
$q\cdot\big(\prod_{n\ge1}(1-q^n)\big)^{24}$, i.e. `single 1 1` times the $24$th power of the image
of `etaProd` in $K$. The single hypothesis is conditional: if $5\le\ell$, there are a power series
$T\in\mathbb{Z}[[q]]$ and a polynomial $G\in\mathbb{Z}[X]$ such that $\ell$ divides every
coefficient of $T$ of index $\ge 1$, $\ell$ does not divide the constant coefficient of $T$, $G$ has
degree $\ell-1$ with $(\ell-1)$-st coefficient equal to that constant coefficient, and the identity
$T = G(j)\,\Delta^{\ell-1}$ holds in `LaurentSeries ℤ` (with $j$ and $\Delta$ formed over
$\mathbb{Z}$ as above). The conclusion is that there exist a natural number $M$ with $1\le M$ whose
image in $K$ is nonzero, and a polynomial $G\in K[X]$ of degree exactly $M$, such that
$G(j)\cdot\Delta^{M} = 1$ in `LaurentSeries K`, the evaluation being `Polynomial.aeval` at `jqModC
K`.

The hypothesis packages, for $\ell\ge 5$, the reduction modulo $\ell$ of the classical congruence
for the Eisenstein series of weight $\ell-1$ (the Hasse invariant), expressed entirely in terms of
$q$-expansions: $E_{\ell-1} = G(j)\Delta^{\ell-1}$ with $G$ of degree $\ell-1$. Unlike the textbook
formulation, nothing here concerns modular forms or the curve $X_0(N)$ as such: all objects are
formal Laurent series, and the output is a purely formal unit identity saying that $\Delta^{-M}$ is
a polynomial in $j$ of degree $M$ with $M$ invertible in $K$. The identity is used in the proof that
$j(q^p)$ does not lie in $K(j(q))$ for a prime $p\ne\ell$
([`ModularCurve.StarBank.starBank`](thm.html#ModularCurve.StarBank.starBank)), where the finitely
many roots of $G$ supply the $j$-values on which the characteristic-$\ell$ argument is run and the
invertibility of $M$ in $K$ is needed.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_StarBank_starK.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_StarBank_starK

open HahnSeries PowerSeries

namespace ModularCurve
p2m_export "ModularCurve" "jqModC map_jqModC eisenstein4 etaProd dedekindEtaUnit dedekindEtaUnitInv dedekindEtaUnit_mul_inv jNum ofPowerSeries_coeff_of_neg"
namespace W1
p2m_open "ModularCurve"

noncomputable abbrev Dseries (K : Type*) [CommRing K] : LaurentSeries K :=
  HahnSeries.single (1 : ℤ) (1 : K)
    * HahnSeries.ofPowerSeries ℤ K (PowerSeries.map (Int.castRingHom K) ModularCurve.etaProd) ^ 24

private def hahnMapRingHom {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S) :
    LaurentSeries R →+* LaurentSeries S where
  toFun x := x.map f
  map_one' := HahnSeries.map_one f.toMonoidWithZeroHom
  map_mul' _ _ := HahnSeries.map_mul f.toNonUnitalRingHom
  map_zero' := HahnSeries.map_zero f.toZeroHom
  map_add' _ _ := HahnSeries.map_add f.toAddMonoidHom

private theorem hahnMapRingHom_apply {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (x : LaurentSeries R) : hahnMapRingHom f x = x.map f := rfl

theorem ofPowerSeries_map {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (u : PowerSeries R) :
    (HahnSeries.ofPowerSeries ℤ R u).map f = HahnSeries.ofPowerSeries ℤ S (PowerSeries.map f u) := by
  ext k
  rw [HahnSeries.map_coeff]
  rcases le_or_gt 0 k with hk | hk
  · lift k to ℕ using hk
    rw [HahnSeries.ofPowerSeries_apply_coeff, HahnSeries.ofPowerSeries_apply_coeff,
      PowerSeries.coeff_map]
  · rw [ModularCurve.ofPowerSeries_coeff_of_neg _ hk,
      ModularCurve.ofPowerSeries_coeff_of_neg _ hk, map_zero]

private theorem hahnMapRingHom_ofPowerSeries {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (u : PowerSeries R) :
    hahnMapRingHom f (HahnSeries.ofPowerSeries ℤ R u)
      = HahnSeries.ofPowerSeries ℤ S (PowerSeries.map f u) :=
  ofPowerSeries_map f u

private theorem hahnMapRingHom_single {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
    (g : ℤ) (r : R) :
    hahnMapRingHom f (HahnSeries.single g r) = HahnSeries.single g (f r) :=
  HahnSeries.map_single (f := f.toZeroHom)

private theorem hahnMapRingHom_etaBlock (K : Type*) [CommRing K] :
    hahnMapRingHom (Int.castRingHom K)
        (HahnSeries.single (1 : ℤ) (1 : ℤ)
          * HahnSeries.ofPowerSeries ℤ ℤ ModularCurve.etaProd ^ 24)
      = HahnSeries.single (1 : ℤ) (1 : K)
          * HahnSeries.ofPowerSeries ℤ K
              (PowerSeries.map (Int.castRingHom K) ModularCurve.etaProd) ^ 24 := by
  rw [map_mul, map_pow, hahnMapRingHom_single, hahnMapRingHom_ofPowerSeries, map_one]

private theorem hahnMapRingHom_aeval_jqModC (K : Type*) [CommRing K] (G : Polynomial ℤ) :
    hahnMapRingHom (Int.castRingHom K) (Polynomial.aeval (ModularCurve.jqModC ℤ) G)
      = Polynomial.aeval (ModularCurve.jqModC K) (G.map (Int.castRingHom K)) := by
  have h := Polynomial.map_aeval_eq_aeval_map
    (R := ℤ) (S := LaurentSeries ℤ) (T := K) (U := LaurentSeries K)
    (φ := Int.castRingHom K) (ψ := hahnMapRingHom (Int.castRingHom K))
    (RingHom.ext_int _ _) G (ModularCurve.jqModC ℤ)
  rw [h, hahnMapRingHom_apply, ModularCurve.map_jqModC]

private theorem powerSeries_map_eq_C_of_dvd {K : Type*} [CommRing K] {ℓ : ℕ} [CharP K ℓ]
    {T : PowerSeries ℤ} (hT : ∀ m, 1 ≤ m → (ℓ : ℤ) ∣ T.coeff m) :
    T.map (Int.castRingHom K) = PowerSeries.C ((PowerSeries.constantCoeff T : ℤ) : K) := by
  ext m
  rw [PowerSeries.coeff_map, PowerSeries.coeff_C]
  rcases Nat.eq_zero_or_pos m with rfl | hm
  · rw [ite_eq_left rfl, ← PowerSeries.coeff_zero_eq_constantCoeff_apply, eq_intCast]
  · rw [ite_eq_right hm.ne']
    exact_mod_cast (CharP.intCast_eq_zero_iff K ℓ _).mpr (hT m hm)

private theorem eisenstein4_map_of_240 {K : Type*} [CommRing K] (h240 : (240 : K) = 0) :
    PowerSeries.map (Int.castRingHom K) ModularCurve.eisenstein4 = 1 := by
  ext n
  rw [PowerSeries.coeff_map, ModularCurve.eisenstein4, PowerSeries.coeff_mk, PowerSeries.coeff_one]
  rcases Nat.eq_zero_or_pos n with rfl | hn
  · simp
  · rw [ite_eq_right hn.ne', ite_eq_right hn.ne']
    have h240Z : (Int.castRingHom K) (240 : ℤ) = 0 := by
      simp only [eq_intCast]; exact_mod_cast h240
    rw [map_mul, h240Z, zero_mul]

theorem jqModC_mul_Dseries_of_240 {K : Type*} [CommRing K] (h240 : (240 : K) = 0) :
    ModularCurve.jqModC K * Dseries K = 1 := by
  have heis := eisenstein4_map_of_240 h240
  have hjnum : PowerSeries.map (Int.castRingHom K) ModularCurve.jNum
      = PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnitInv := by
    rw [ModularCurve.jNum, map_mul, map_pow, heis, one_pow, one_mul]
  have heta : HahnSeries.ofPowerSeries ℤ K
        (PowerSeries.map (Int.castRingHom K) ModularCurve.etaProd) ^ 24
      = HahnSeries.ofPowerSeries ℤ K
        (PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnit) := by
    rw [ModularCurve.dedekindEtaUnit, map_pow, map_pow]
  rw [ModularCurve.jqModC, Dseries, hjnum, heta]
  have hinv : PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnitInv
      * PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnit = 1 := by
    rw [← map_mul, mul_comm, ModularCurve.dedekindEtaUnit_mul_inv, map_one]
  calc HahnSeries.single (-1 : ℤ) (1 : K)
        * HahnSeries.ofPowerSeries ℤ K
            (PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnitInv)
        * (HahnSeries.single (1 : ℤ) (1 : K)
            * HahnSeries.ofPowerSeries ℤ K
                (PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnit))
      = (HahnSeries.single (-1 : ℤ) (1 : K) * HahnSeries.single (1 : ℤ) (1 : K))
        * (HahnSeries.ofPowerSeries ℤ K
              (PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnitInv)
            * HahnSeries.ofPowerSeries ℤ K
              (PowerSeries.map (Int.castRingHom K) ModularCurve.dedekindEtaUnit)) := by ring
    _ = HahnSeries.single (0 : ℤ) (1 : K)
        * HahnSeries.ofPowerSeries ℤ K (1 : PowerSeries K) := by
        rw [HahnSeries.single_mul_single, ← map_mul, hinv]; ring_nf
    _ = 1 := by rw [HahnSeries.single_zero_one, map_one, one_mul]

end ModularCurve.W1

p2m_open "P2MW.S_ModularCurve_StarBank_starK.ModularCurve.W1 ModularCurve P2MW.S_ModularCurve_StarBank_starK.ModularCurve"

namespace ModularCurve
p2m_export "ModularCurve" "jqModC map_jqModC eisenstein4 etaProd dedekindEtaUnit dedekindEtaUnitInv dedekindEtaUnit_mul_inv jNum ofPowerSeries_coeff_of_neg"
namespace StarBank
end ModularCurve.StarBank
p2m_open_scoped "ModularCurve" in

private theorem ModularCurve.StarBank.starK_of_240 (K : Type*) [Field K] (h240 : (240 : K) = 0) :
    ∃ M : ℕ, 1 ≤ M ∧ (M : K) ≠ 0 ∧ ∃ G : Polynomial K, G.natDegree = M
      ∧ Polynomial.aeval (jqModC K) G
          * (HahnSeries.single (1 : ℤ) (1 : K)
              * HahnSeries.ofPowerSeries ℤ K
                  (PowerSeries.map (Int.castRingHom K) etaProd) ^ 24) ^ M = 1 := by
  refine ⟨1, le_refl 1, ?_, Polynomial.X, Polynomial.natDegree_X, ?_⟩
  · exact_mod_cast one_ne_zero (α := K)
  · rw [Polynomial.aeval_X, pow_one]
    exact ModularCurve.W1.jqModC_mul_Dseries_of_240 h240

p2m_open_scoped "ModularCurve" in

private theorem ModularCurve.StarBank.starK (K : Type*) [Field K] {ℓ : ℕ} [Fact ℓ.Prime] [CharP K ℓ]
    (hHasse : 5 ≤ ℓ → ∃ (T : PowerSeries ℤ) (G : Polynomial ℤ),
        (∀ m, 1 ≤ m → (ℓ : ℤ) ∣ T.coeff m) ∧ ¬ (ℓ : ℤ) ∣ PowerSeries.constantCoeff T
        ∧ G.natDegree = ℓ - 1 ∧ G.coeff (ℓ - 1) = PowerSeries.constantCoeff T
        ∧ HahnSeries.ofPowerSeries ℤ ℤ T
            = Polynomial.aeval (jqModC ℤ) G
              * (HahnSeries.single (1 : ℤ) (1 : ℤ)
                  * HahnSeries.ofPowerSeries ℤ ℤ etaProd ^ 24) ^ (ℓ - 1)) :
    ∃ M : ℕ, 1 ≤ M ∧ (M : K) ≠ 0 ∧ ∃ G : Polynomial K, G.natDegree = M
      ∧ Polynomial.aeval (jqModC K) G
          * (HahnSeries.single (1 : ℤ) (1 : K)
              * HahnSeries.ofPowerSeries ℤ K
                  (PowerSeries.map (Int.castRingHom K) etaProd) ^ 24) ^ M = 1 := by
  have hℓp : ℓ.Prime := Fact.out
  rcases lt_or_ge ℓ 5 with hℓ5 | hℓ5
  · have hℓdvd : ℓ ∣ 240 := by
      interval_cases ℓ <;> first | decide | exact absurd hℓp (by decide)
    exact ModularCurve.StarBank.starK_of_240 K ((CharP.cast_eq_zero_iff K ℓ 240).mpr hℓdvd)
  · obtain ⟨T, G₀, hTdvd, hTconst, hGdeg, hGcoeff, hId⟩ := hHasse hℓ5
    set cT := PowerSeries.constantCoeff T with hcTdef
    have hcTK : ((cT : ℤ) : K) ≠ 0 := fun h =>
      hTconst ((CharP.intCast_eq_zero_iff K ℓ cT).mp h)
    have hmap := congrArg (hahnMapRingHom (Int.castRingHom K)) hId
    rw [map_mul, map_pow, hahnMapRingHom_aeval_jqModC, hahnMapRingHom_etaBlock,
      hahnMapRingHom_apply, ofPowerSeries_map, powerSeries_map_eq_C_of_dvd hTdvd,
      HahnSeries.ofPowerSeries_C] at hmap
    refine ⟨ℓ - 1, by omega, ?_,
      Polynomial.C (((cT : ℤ) : K)⁻¹) * G₀.map (Int.castRingHom K), ?_, ?_⟩
    · have h1 : (1 : ℕ) ≤ ℓ := hℓp.one_lt.le
      have : ((ℓ - 1 : ℕ) : K) = (ℓ : K) - 1 := by exact_mod_cast Nat.cast_sub h1
      rw [this, CharP.cast_eq_zero K ℓ, zero_sub]
      exact neg_ne_zero.mpr one_ne_zero
    · have hdegK : (G₀.map (Int.castRingHom K)).natDegree = ℓ - 1 := by
        refine Polynomial.natDegree_map_of_leadingCoeff_ne_zero _ ?_ |>.trans hGdeg
        rw [Polynomial.leadingCoeff, hGdeg, hGcoeff]; simpa using hcTK
      rw [Polynomial.natDegree_C_mul (inv_ne_zero hcTK), hdegK]
    · rw [map_mul (Polynomial.aeval (jqModC K)), Polynomial.aeval_C, mul_assoc, ← hmap,
        ← hcTdef, HahnSeries.algebraMap_apply', PowerSeries.algebraMap_eq,
        HahnSeries.ofPowerSeries_C, ← map_mul, inv_mul_cancel₀ hcTK, map_one]

example : ((720 : ℤ) : ℚ) ≠ 0 := by decide

open HahnSeries PowerSeries _root_.ModularCurve _root_.P2MW.S_ModularCurve_StarBank_starK.ModularCurve in

theorem solution (K : Type*) [Field K] {ℓ : ℕ} [Fact ℓ.Prime] [CharP K ℓ]
    (hHasse : 5 ≤ ℓ → ∃ (T : PowerSeries ℤ) (G : Polynomial ℤ),
        (∀ m, 1 ≤ m → (ℓ : ℤ) ∣ T.coeff m) ∧ ¬ (ℓ : ℤ) ∣ PowerSeries.constantCoeff T
        ∧ G.natDegree = ℓ - 1 ∧ G.coeff (ℓ - 1) = PowerSeries.constantCoeff T
        ∧ HahnSeries.ofPowerSeries ℤ ℤ T
            = Polynomial.aeval (jqModC ℤ) G
              * (HahnSeries.single (1 : ℤ) (1 : ℤ)
                  * HahnSeries.ofPowerSeries ℤ ℤ etaProd ^ 24) ^ (ℓ - 1)) :
    ∃ M : ℕ, 1 ≤ M ∧ (M : K) ≠ 0 ∧ ∃ G : Polynomial K, G.natDegree = M
      ∧ Polynomial.aeval (jqModC K) G
          * (HahnSeries.single (1 : ℤ) (1 : K)
              * HahnSeries.ofPowerSeries ℤ K
                  (PowerSeries.map (Int.castRingHom K) etaProd) ^ 24) ^ M = 1 :=
  ModularCurve.StarBank.starK K hHasse

end S_ModularCurve_StarBank_starK
end P2MW
export P2MW.S_ModularCurve_StarBank_starK (solution)

end privateSection

public section publicSection


open HahnSeries PowerSeries ModularCurve
theorem ModularCurve.StarBank.starK (K : Type*) [Field K] {ℓ : ℕ} [Fact ℓ.Prime] [CharP K ℓ]
    (hHasse : 5 ≤ ℓ → ∃ (T : PowerSeries ℤ) (G : Polynomial ℤ),
        (∀ m, 1 ≤ m → (ℓ : ℤ) ∣ T.coeff m) ∧ ¬ (ℓ : ℤ) ∣ PowerSeries.constantCoeff T
        ∧ G.natDegree = ℓ - 1 ∧ G.coeff (ℓ - 1) = PowerSeries.constantCoeff T
        ∧ HahnSeries.ofPowerSeries ℤ ℤ T
            = Polynomial.aeval (jqModC ℤ) G
              * (HahnSeries.single (1 : ℤ) (1 : ℤ)
                  * HahnSeries.ofPowerSeries ℤ ℤ etaProd ^ 24) ^ (ℓ - 1)) :
    ∃ M : ℕ, 1 ≤ M ∧ (M : K) ≠ 0 ∧ ∃ G : Polynomial K, G.natDegree = M
      ∧ Polynomial.aeval (jqModC K) G
          * (HahnSeries.single (1 : ℤ) (1 : K)
              * HahnSeries.ofPowerSeries ℤ K
                  (PowerSeries.map (Int.castRingHom K) etaProd) ^ 24) ^ M = 1 := _root_.P2MW.S_ModularCurve_StarBank_starK.solution K hHasse

end publicSection
