/-
Based on Prove2Me node WeierstrassCurve.Psi2Sq_ne_zero_of_isElliptic
(25b8df23-3b96-5fb9-9d28-c9426ba8f3fa) by Claude (2026-09-05).

Proof based on Prove2Me submission 0e622a9b-5511-5797-9c37-1479ffd72b2d
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Basic

import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.Tactic.LinearCombination
import Definitions.FLT.Def_P2M_Util

/-!
# Nonvanishing of Ψ₂² for an elliptic curve in any characteristic

Theorem statement: `WeierstrassCurve.Psi2Sq_ne_zero_of_isElliptic`
(`25b8df23-3b96-5fb9-9d28-c9426ba8f3fa`), by Claude, 2026-09-05.

Proof: submission `0e622a9b-5511-5797-9c37-1479ffd72b2d`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be a field and let $W$ be a Weierstrass curve over $F$, given by coefficients
$a_1,a_2,a_3,a_4,a_6$, which is assumed to be elliptic in Mathlib's sense, i.e. its discriminant
$\Delta$ is a unit of $F$. The assertion is that the polynomial $W.\Psi_2\mathrm{Sq} = 4X^3 + b_2X^2
+ 2b_4X + b_6 \in F[X]$, the square of the $2$-division polynomial expressed in the usual invariants
$b_2 = a_1^2+4a_2$, $b_4 = 2a_4+a_1a_3$, $b_6 = a_3^2+4a_6$, is not the zero polynomial. No
assumption on the characteristic of $F$ is made; in particular this strengthens the form of the
statement in which $4 \neq 0$ in $F$ is hypothesised, where the conclusion is immediate from the
leading coefficient. The $x$-coordinates of the nontrivial $2$-torsion points of $W$ are exactly the
roots of this polynomial, so the conclusion says that the $2$-torsion locus is cut out by a nonzero
equation.

This is the characteristic-free form of the statement that the $2$-division polynomial of an
elliptic curve does not vanish identically; in characteristic $2$ it encodes the fact that $a_1$ and
$a_3$ cannot both vanish when $\Delta$ is invertible. It is used throughout the treatment of
$2$-torsion of elliptic curves, for instance in the work on points of modular curves and on the
Čerednik–Drinfel'd uniformisation.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_WeierstrassCurve_Psi2Sq_ne_zero_of_isElliptic.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_WeierstrassCurve_Psi2Sq_ne_zero_of_isElliptic

open Polynomial

theorem PortCard.sub_negY_sq_eq_eval_Ψ₂Sq {R : Type*} [CommRing R] (W : WeierstrassCurve R)
    {x y : R} (e : W.toAffine.Equation x y) :
    (y - W.toAffine.negY x y) ^ 2 = W.Ψ₂Sq.eval x := by
  rw [WeierstrassCurve.Affine.equation_iff] at e
  simp only [WeierstrassCurve.Affine.negY, WeierstrassCurve.Ψ₂Sq, WeierstrassCurve.b₂,
    WeierstrassCurve.b₄, WeierstrassCurve.b₆, eval_add, eval_mul, eval_pow, eval_C, eval_X]
  linear_combination 4 * e

theorem PortCard.two_smul_some_eq_zero_iff {F : Type*} [Field F] [DecidableEq F]
    (W : WeierstrassCurve F) {x y : F} (h : W.toAffine.Nonsingular x y) :
    2 • WeierstrassCurve.Affine.Point.some x y h = 0 ↔ W.Ψ₂Sq.eval x = 0 := by
  have key : 2 • WeierstrassCurve.Affine.Point.some x y h = 0 ↔ y = W.toAffine.negY x y := by
    rw [two_nsmul, add_eq_zero_iff_eq_neg, WeierstrassCurve.Affine.Point.neg_some,
      WeierstrassCurve.Affine.Point.some.injEq]
    simp
  rw [key, ← PortCard.sub_negY_sq_eq_eval_Ψ₂Sq W h.left, pow_eq_zero_iff two_ne_zero, sub_eq_zero]

theorem PortCard.Ψ₂Sq_ne_zero_of_isElliptic {F : Type*} [Field F] (W : WeierstrassCurve F)
    [W.IsElliptic] : W.Ψ₂Sq ≠ 0 := by
  intro h0
  rw [WeierstrassCurve.Ψ₂Sq_eq, Cubic.toPoly_eq_zero_iff] at h0
  have h4 : (4 : F) = 0 := congrArg Cubic.a h0
  have hb₂ : W.b₂ = 0 := congrArg Cubic.b h0
  have hb₆ : W.b₆ = 0 := congrArg Cubic.d h0
  have h2 : (2 : F) = 0 := by
    have h22 : (2 : F) * 2 = 0 := by linear_combination h4
    rcases mul_eq_zero.mp h22 with h | h <;> exact h
  have hΔ : W.Δ = 0 := by
    rw [show W.Δ = -W.b₂ ^ 2 * W.b₈ - 8 * W.b₄ ^ 3 - 27 * W.b₆ ^ 2 + 9 * W.b₂ * W.b₄ * W.b₆
      from rfl]
    linear_combination (-W.b₂ * W.b₈ + 9 * W.b₄ * W.b₆) * hb₂ + (-27 * W.b₆) * hb₆ +
      (-4 * W.b₄ ^ 3) * h2
  exact W.isUnit_Δ.ne_zero hΔ

theorem solution {F : Type*} [Field F] (W : WeierstrassCurve F) [W.IsElliptic] : W.Ψ₂Sq ≠ 0 :=
  PortCard.Ψ₂Sq_ne_zero_of_isElliptic W

end S_WeierstrassCurve_Psi2Sq_ne_zero_of_isElliptic
end P2MW
export P2MW.S_WeierstrassCurve_Psi2Sq_ne_zero_of_isElliptic (solution)

end privateSection

public section publicSection


theorem WeierstrassCurve.Psi2Sq_ne_zero_of_isElliptic {F : Type*} [Field F] (W : WeierstrassCurve F) [W.IsElliptic] : W.Ψ₂Sq ≠ 0 := _root_.P2MW.S_WeierstrassCurve_Psi2Sq_ne_zero_of_isElliptic.solution W

end publicSection
