/-
Based on Prove2Me node ModularFormClass.heckeT_heckeT_comm
(44b9a042-0038-5d3e-b7e5-70f8a32ddeeb) by Claude (2026-09-05).

Proof based on Prove2Me submission ac188186-6cc5-544c-826e-641d46eb8f9b
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Mathlib.NumberTheory.ModularForms.Basic
public import Definitions.FLT.Def_ModularForm_HeckeOperator

import Definitions.FLT.Def_FLTPrelim_Modularity
import Theorems.FLT.Thm_UpperHalfPlane_qCoeff_heckeT
import Theorems.FLT.Thm_ModularForm_mdifferentiable_heckeT
import Theorems.FLT.Thm_ModularForm_isBoundedAtImInfty_heckeT
import Theorems.FLT.Thm_ModularForm_periodic_heckeT_comp_ofComplex
import Theorems.FLT.Thm_UpperHalfPlane_eq_of_forall_qCoeff_eq
import Theorems.FLT.Thm_ModularForm_coeffHeckeT_comm
import Definitions.FLT.Def_P2M_Util

/-!
# Hecke translates Tₚ, T_q commute for coprime p,q

Theorem statement: `ModularFormClass.heckeT_heckeT_comm` (`44b9a042-0038-5d3e-b7e5-70f8a32ddeeb`),
by Claude, 2026-09-05.

Proof: submission `ac188186-6cc5-544c-826e-641d46eb8f9b`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $F$ be a type of functions on the upper half-plane $\mathbb{H}$ with values in $\mathbb{C}$ (via
a `FunLike` structure), let $\Gamma$ be a subgroup of $\mathrm{GL}_2(\mathbb{R})$ and $k$ an
integer, and suppose $F$ is a class of modular forms of weight $k$ for $\Gamma$ (`ModularFormClass F
Γ k`, so in particular each element is holomorphic on $\mathbb{H}$, weight-$k$ invariant under
$\Gamma$ and bounded at the cusps). Let $f : F$, and assume that $1$ belongs to
$\Gamma$`.strictPeriods`, the set of strict real periods of $\Gamma$; this hypothesis supplies the
$1$-periodicity of $f \circ$ `ofComplex` and, via the fact that $\infty$ is then a cusp of $\Gamma$,
the boundedness of $f$ at $i\infty$. Let $p, q$ be coprime natural numbers. For a function $g$ on
$\mathbb{H}$ write $\mathrm{heckeT}\,k\,p\,g = \sum_{j < p} g \mid_k \mathrm{heckeMatrix}\,p\,j + g
\mid_k \mathrm{heckeDiagMatrix}\,p$, where $\mid_k$ is the weight-$k$ slash action, the
$\mathrm{heckeMatrix}\,p\,j$ ($0 \le j < p$) are the matrices used for the sum part, and
$\mathrm{heckeDiagMatrix}\,p$ is the identity if $p = 0$ and otherwise the upper triangular element
`upperTriangularGL p 0 1` of $\mathrm{GL}_2(\mathbb{R})$. The conclusion is the equality of
functions $\mathbb{H} \to \mathbb{C}$: $\mathrm{heckeT}\,k\,p(\mathrm{heckeT}\,k\,q\,f) =
\mathrm{heckeT}\,k\,q(\mathrm{heckeT}\,k\,p\,f)$. No modularity of the Hecke translates themselves
is asserted or required.

This is the commutativity of the Hecke operators $T_p$ and $T_q$ at coprime indices, in the concrete
form of an identity between the Hecke translates of the underlying function on $\mathbb{H}$. It is
the analytic input for the corresponding statements about the linear Hecke operators on spaces of
modular and cusp forms, [`ModularForm.heckeTLin_comm`](thm.html#ModularForm.heckeTLin_comm) and
[`CuspForm.heckeTLin_comm`](thm.html#CuspForm.heckeTLin_comm), and thence for the existence of
simultaneous eigenforms.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularFormClass_heckeT_heckeT_comm.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularFormClass_heckeT_heckeT_comm

noncomputable section

open Complex Function Filter
p2m_open "UpperHalfPlane~I"
open scoped Real MatrixGroups ModularForm Manifold Topology

open ModularForm ModularFormClass

namespace W2WsF

private theorem _root_.W2WsF.eq_of_forall_qCoeff_eq {f g : ℍ → ℂ} (hfper : Periodic (f ∘ ofComplex) 1) (hfhol : MDiff f)
    (hfbdd : IsBoundedAtImInfty f) (hgper : Periodic (g ∘ ofComplex) 1) (hghol : MDiff g)
    (hgbdd : IsBoundedAtImInfty g) (h : ∀ n : ℕ, qCoeff f n = qCoeff g n) : f = g :=
  UpperHalfPlane.eq_of_forall_qCoeff_eq hfper hfhol hfbdd hgper hghol hgbdd h

p2m_export "W2WsF" "eq_of_forall_qCoeff_eq"

theorem qCoeff_const_smul {f : ℍ → ℂ} (hper : Periodic (f ∘ ofComplex) 1) (hhol : MDiff f)
    (hbdd : IsBoundedAtImInfty f) (c : ℂ) (n : ℕ) : qCoeff (c • f) n = c * qCoeff f n := by
  simp only [qCoeff]
  rw [UpperHalfPlane.qExpansion_smul (analyticAt_cuspFunction_zero one_pos hper hhol hbdd)]
  simp

theorem periodic_const_smul {f : ℍ → ℂ} (hper : Periodic (f ∘ ofComplex) 1) (c : ℂ) :
    Periodic ((c • f) ∘ ofComplex) 1 := fun z ↦ by
  simpa using congrArg (c * ·) (hper z)

section Class

variable {F : Type*} [FunLike F ℍ ℂ] {Γ : Subgroup (GL (Fin 2) ℝ)} {k : ℤ}

theorem mf_periodic [ModularFormClass F Γ k] (f : F) (hΓ : (1 : ℝ) ∈ Γ.strictPeriods) :
    Periodic (⇑f ∘ ofComplex) 1 :=
  SlashInvariantFormClass.periodic_comp_ofComplex f hΓ

theorem mf_bdd [ModularFormClass F Γ k] (f : F) (hΓ : (1 : ℝ) ∈ Γ.strictPeriods) :
    IsBoundedAtImInfty ⇑f :=
  haveI : Fact (IsCusp OnePoint.infty Γ) := ⟨Γ.isCusp_of_mem_strictPeriods one_pos hΓ⟩
  bdd_at_infty f

end Class

theorem heckeT_heckeT_comm_bare {f : ℍ → ℂ} (hper : Periodic (f ∘ ofComplex) 1) (hhol : MDiff f)
    (hbdd : IsBoundedAtImInfty f) (k : ℤ) {p q : ℕ} (hpq : p.Coprime q) :
    heckeT k p (heckeT k q f) = heckeT k q (heckeT k p f) := by
  rcases eq_or_ne p 0 with rfl | hp
  · simp
  rcases eq_or_ne q 0 with rfl | hq
  · simp
  refine eq_of_forall_qCoeff_eq
    (periodic_heckeT_comp_ofComplex (periodic_heckeT_comp_ofComplex hper k q) k p)
    (mdifferentiable_heckeT (mdifferentiable_heckeT hhol k q) k p)
    (isBoundedAtImInfty_heckeT (isBoundedAtImInfty_heckeT hbdd k q) k p)
    (periodic_heckeT_comp_ofComplex (periodic_heckeT_comp_ofComplex hper k p) k q)
    (mdifferentiable_heckeT (mdifferentiable_heckeT hhol k p) k q)
    (isBoundedAtImInfty_heckeT (isBoundedAtImInfty_heckeT hbdd k p) k q) fun n ↦ ?_
  rw [UpperHalfPlane.qCoeff_heckeT (periodic_heckeT_comp_ofComplex hper k q)
      (mdifferentiable_heckeT hhol k q) (isBoundedAtImInfty_heckeT hbdd k q) k hp,
    UpperHalfPlane.qCoeff_heckeT (periodic_heckeT_comp_ofComplex hper k p)
      (mdifferentiable_heckeT hhol k p) (isBoundedAtImInfty_heckeT hbdd k p) k hq]
  have hq' : qCoeff (heckeT k q f) = coeffHeckeT k q (qCoeff f) :=
    funext fun m ↦ UpperHalfPlane.qCoeff_heckeT hper hhol hbdd k hq m
  have hp' : qCoeff (heckeT k p f) = coeffHeckeT k p (qCoeff f) :=
    funext fun m ↦ UpperHalfPlane.qCoeff_heckeT hper hhol hbdd k hp m
  rw [hq', hp', coeffHeckeT_comm k hpq]

end W2WsF

theorem solution {F : Type*} [FunLike F UpperHalfPlane ℂ] {Γ : Subgroup (Matrix.GeneralLinearGroup (Fin 2) ℝ)} {k : ℤ} [ModularFormClass F Γ k] (f : F) (hΓ : (1 : ℝ) ∈ Γ.strictPeriods) {p q : ℕ} (hpq : Nat.Coprime p q) : ModularForm.heckeT k p (ModularForm.heckeT k q ⇑f) = ModularForm.heckeT k q (ModularForm.heckeT k p ⇑f) :=
  W2WsF.heckeT_heckeT_comm_bare (W2WsF.mf_periodic f hΓ) (ModularFormClass.holo f)
    (W2WsF.mf_bdd f hΓ) k hpq

end

end S_ModularFormClass_heckeT_heckeT_comm
end P2MW
export P2MW.S_ModularFormClass_heckeT_heckeT_comm (solution)

end privateSection

public section publicSection

set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false
theorem ModularFormClass.heckeT_heckeT_comm {F : Type*} [FunLike F UpperHalfPlane ℂ] {Γ : Subgroup (Matrix.GeneralLinearGroup (Fin 2) ℝ)} {k : ℤ} [ModularFormClass F Γ k] (f : F) (hΓ : (1 : ℝ) ∈ Γ.strictPeriods) {p q : ℕ} (hpq : Nat.Coprime p q) : ModularForm.heckeT k p (ModularForm.heckeT k q ⇑f) = ModularForm.heckeT k q (ModularForm.heckeT k p ⇑f) := _root_.P2MW.S_ModularFormClass_heckeT_heckeT_comm.solution f hΓ hpq

end publicSection
