/-
Based on Prove2Me node ModularCurve.coeff_jqModC_pow_self
(1918cc1f-3da5-53c7-b67e-2a94e1e9e5f8) by Claude (2026-09-05).

Proof based on Prove2Me submission 9265beca-7791-5ecb-8229-8f29ae6b70dc
by Claude (2026-09-05); locally adapted.

Licensed under Apache License 2.0
(https://www.apache.org/licenses/LICENSE-2.0).
-/

module

public import Definitions.FLT.Def_ModularCurve_JqCoeff

import Mathlib.RingTheory.Algebraic.Basic
import Definitions.FLT.Def_P2M_Util

/-!
# The coefficient of q⁻ᵇ in j(q)ᵇ is 1

Theorem statement: `ModularCurve.coeff_jqModC_pow_self` (`1918cc1f-3da5-53c7-b67e-2a94e1e9e5f8`), by
Claude, 2026-09-05.

Proof: submission `9265beca-7791-5ecb-8229-8f29ae6b70dc`, by Claude, 2026-09-05 (ACCEPTED); locally
adapted.

Let $K$ be a commutative ring and let $b$ be a natural number. Work in the Laurent series ring
`LaurentSeries K`, realised as Hahn series over $\mathbb{Z}$ with coefficients in $K$. The element
`jqModC K` is defined as the product of the Hahn series `HahnSeries.single (-1) 1`, i.e. $q^{-1}$,
with the image under `HahnSeries.ofPowerSeries` of the power series `jNum` pushed forward along the
canonical ring map $\mathbb{Z} \to K$, where `jNum` $=$ `eisenstein4`$^3\cdot$`dedekindEtaUnitInv`
is the integral power series giving the holomorphic part of the $q$-expansion of the modular
invariant. The theorem asserts that the coefficient of `jqModC K` raised to the power $b$ at the
index $-(b : \mathbb{Z})$ equals $1$ in $K$. In other words, in $K((q))$ the $b$-th power of the
reduction of the $j$-expansion has coefficient $1$ at $q^{-b}$; no hypothesis beyond commutativity
of $K$ is imposed, and the case $b = 0$ is included.

This records the normalisation of the leading term of the $q$-expansion of the modular invariant $j
= q^{-1} + 744 + \cdots$: its leading coefficient is $1$, hence a unit in every coefficient ring,
and the same holds for all powers. It is used throughout the treatment of the models of the modular
curves, for instance in the construction and comparison of prolongations of places where the order
of vanishing of the $j$-function has to be computed.

## Explanation of the source proof

Proof transplanted from the FLT repository:
https://github.com/anthropics/fermats-last-theorem/blob/aa2d8b34692b16c70f699536de0d8e75b9a3e9ef/P2M/Sol/S_ModularCurve_coeff_jqModC_pow_self.lean

<!-- Generated by add_prove2me_provenance.py -->
-/

section privateSection

set_option synthInstance.maxHeartbeats 400000
set_option backward.isDefEq.respectTransparency.types false

namespace P2MW.S_ModularCurve_coeff_jqModC_pow_self

noncomputable section
open HahnSeries

namespace ModularCurve
p2m_export "ModularCurve" "jqModC jNum constantCoeff_jNum ofPowerSeries_coeff_of_neg jq_pow"
p2m_open "ModularCurve"
namespace CharLRows

variable (K : Type*) [CommRing K]

theorem jqModC_pow (n : ℕ) :
    (jqModC K) ^ n = HahnSeries.single (-(n : ℤ)) 1 *
      HahnSeries.ofPowerSeries ℤ K ((jNum.map (Int.castRingHom K)) ^ n) := by
  have h : n • (-1 : ℤ) = -(n : ℤ) := by simp
  rw [jqModC, mul_pow, HahnSeries.single_pow, one_pow, h, ← map_pow]

theorem constantCoeff_jNum_map : PowerSeries.constantCoeff (jNum.map (Int.castRingHom K)) = 1 := by
  rw [← PowerSeries.coeff_zero_eq_constantCoeff, PowerSeries.coeff_map, PowerSeries.coeff_zero_eq_constantCoeff,
    constantCoeff_jNum, map_one]

theorem coeff_jqModC_pow_self (n : ℕ) : ((jqModC K) ^ n).coeff (-(n : ℤ)) = 1 := by
  rw [jqModC_pow, HahnSeries.coeff_single_mul, one_mul, sub_neg_eq_add, neg_add_cancel,
    show (0 : ℤ) = ((0 : ℕ) : ℤ) from rfl, HahnSeries.ofPowerSeries_apply_coeff,
    PowerSeries.coeff_zero_eq_constantCoeff, map_pow, constantCoeff_jNum_map, one_pow]

theorem coeff_jqModC_pow_of_lt {n : ℕ} {m : ℤ} (hm : m < -(n : ℤ)) : ((jqModC K) ^ n).coeff m = 0 := by
  rw [jqModC_pow, HahnSeries.coeff_single_mul, one_mul]
  exact ofPowerSeries_coeff_of_neg _ (by omega)

theorem coeff_jqModC_neg_one : (jqModC K).coeff (-1 : ℤ) = 1 := by
  simpa using coeff_jqModC_pow_self K 1

theorem algebraMap_laurentSeries_eq_single (c : K) :
    algebraMap K (LaurentSeries K) c = HahnSeries.single 0 c := by
  have h1 : algebraMap K (PowerSeries K) c = PowerSeries.C c := by simp
  rw [HahnSeries.algebraMap_apply', h1, HahnSeries.ofPowerSeries_C]
  rfl

theorem aeval_jqModC_eq_zero {p : Polynomial K} (hp : Polynomial.aeval (jqModC K) p = 0) : p = 0 := by
  by_contra hp0
  set n := p.natDegree with hn
  have hcoeff : (Polynomial.aeval (jqModC K) p).coeff (-(n : ℤ)) = p.coeff n := by
    rw [Polynomial.aeval_def, Polynomial.eval₂_eq_sum_range, HahnSeries.coeff_sum,
      Finset.sum_eq_single n]
    · rw [algebraMap_laurentSeries_eq_single, HahnSeries.coeff_single_zero_mul,
        coeff_jqModC_pow_self, mul_one]
    · intro i hi hin
      have hilt : i < n := lt_of_le_of_ne (Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)) hin
      rw [algebraMap_laurentSeries_eq_single, HahnSeries.coeff_single_zero_mul,
        coeff_jqModC_pow_of_lt, mul_zero]
      omega
    · intro hn'
      exact absurd (Finset.self_mem_range_succ n) hn'
  rw [hp] at hcoeff
  simp only [HahnSeries.coeff_zero] at hcoeff
  exact hp0 (Polynomial.leadingCoeff_eq_zero.mp hcoeff.symm)

theorem transcendental_jqModC : Transcendental K (jqModC K) :=
  transcendental_iff.mpr fun _ hp => aeval_jqModC_eq_zero K hp

theorem jqModC_ne_zero [Nontrivial K] : jqModC K ≠ 0 := by
  intro h
  have h1 : (jqModC K).coeff (-1 : ℤ) = 1 := coeff_jqModC_neg_one K
  rw [h, HahnSeries.coeff_zero] at h1
  exact zero_ne_one h1

theorem order_jqModC [Nontrivial K] : (jqModC K).order = -1 := by
  refine le_antisymm (HahnSeries.order_le_of_coeff_ne_zero ?_) ?_
  · rw [coeff_jqModC_neg_one]
    exact one_ne_zero
  · by_contra hlt
    rw [not_le] at hlt
    refine HahnSeries.coeff_order_eq_zero.not.mpr (jqModC_ne_zero K) ?_
    have h := coeff_jqModC_pow_of_lt K (n := 1) (m := (jqModC K).order)
      (by simpa using hlt)
    simpa using h

end CharLRows

end ModularCurve
end

open _root_.ModularCurve _root_.P2MW.S_ModularCurve_coeff_jqModC_pow_self.ModularCurve in
theorem solution (K : Type*) [CommRing K] (b : ℕ) :
    ((jqModC K) ^ b).coeff (-(b : ℤ)) = 1 :=
  CharLRows.coeff_jqModC_pow_self K b

end S_ModularCurve_coeff_jqModC_pow_self
end P2MW
export P2MW.S_ModularCurve_coeff_jqModC_pow_self (solution)

end privateSection

public section publicSection


open ModularCurve
theorem ModularCurve.coeff_jqModC_pow_self (K : Type*) [CommRing K] (b : ℕ) :
    ((jqModC K) ^ b).coeff (-(b : ℤ)) = 1 := _root_.P2MW.S_ModularCurve_coeff_jqModC_pow_self.solution K b

end publicSection
